name: linuxserver-overseerr
services:
  app:
    image: linuxserver/overseerr:1.33.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_US: Contains all relevant configuration files.
      ports:
        - container: '5055'
          description:
            en_US: Port for Overseerr's web interface.
    ports:
      - target: 5055
        published: 5055
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/overseerr/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    zh_CN: |-
      Overseerr 是为现有 Plex 生态打造的请求管理和媒体发现工具。

      访问项目主页：https://github.com/orgs/linuxserver/packages/container/package/overseerr
    ca_ES: 'Visita la pàgina principal: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    cs_CZ: 'Navštivte domovskou stránku: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    da_DK: 'Besøg hjemmesiden: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    de_DE: 'Besuchen Sie die Homepage: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    el_GR: 'Επισκεφθείτε την αρχική σελίδα: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    en_GB: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    es_ES: 'Visite la página principal: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    fr_FR: "Consultez la page d'accueil\_: https://github.com/orgs/linuxserver/packages/container/package/overseaerr"
    ga_IE: 'Tabhair cuairt ar an leathanach baile: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    hr_HR: 'Posjetite početnu stranicu: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    hu_HU: 'Látogassa meg a honlapot: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    it_IT: 'Visita la homepage: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    ja_JP: 'ホームページをご覧ください: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    ko_KR: '홈페이지 방문: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    ml_IN: 'ഹോംപേജ് സന്ദർശിക്കുക: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    nb_NO: 'Besøk hjemmesiden: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    nl_NL: 'Bezoek de homepage: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    pl_PL: 'Odwiedź stronę główną: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    pt_BR: 'Visite a página inicial: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    ro_RO: 'Vizitați pagina principală: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    ru_RU: 'Перейдите на главную страницу: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    sk_SK: 'Navštívte domovskú stránku: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    sv_SE: 'Besök hemsidan: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    tr_TR: 'Ana sayfayı ziyaret edin: https://github.com/orgs/linuxserver/packages/container/package/overseerr'
    zh_TW: |-
      Overseerr 是為現有 Plex 生態打造的請求管理和媒體發現工具。

      訪問專案主頁：https://github.com/orgs/linuxserver/packages/container/package/overseerr
  tagline:
    en_US: 'A request management and media discovery tool built to work with your existing Plex ecosystem. '
    zh_CN: 为 Plex 生态提供媒体发现和请求管理。
    ca_ES: Una eina de gestió de sol·licituds i descobriment de contingut multimèdia dissenyada per funcionar amb el vostre ecosistema Plex existent.
    cs_CZ: Nástroj pro správu požadavků a vyhledávání médií, který je vytvořen pro práci s vaším stávajícím ekosystémem Plex.
    da_DK: Et værktøj til anmodningshåndtering og medieopdagelse, der er bygget til at fungere med dit eksisterende Plex-økosystem.
    de_DE: Ein Tool zur Anforderungsverwaltung und Medienerkennung, das für die Zusammenarbeit mit Ihrem bestehenden Plex-Ökosystem entwickelt wurde.
    el_GR: Ένα εργαλείο διαχείρισης αιτημάτων και ανακάλυψης πολυμέσων που έχει σχεδιαστεί για να λειτουργεί με το υπάρχον οικοσύστημα Plex.
    en_GB: 'A request management and media discovery tool built to work with your existing Plex ecosystem. '
    es_ES: Una herramienta de gestión de solicitudes y descubrimiento de contenido multimedia diseñada para funcionar con tu ecosistema Plex existente.
    fr_FR: Un outil de gestion des requêtes et de découverte de médias conçu pour fonctionner avec votre écosystème Plex existant.
    ga_IE: Uirlis bainistíochta iarratas agus fionnachtana meán atá deartha chun oibriú le d'éiceachóras Plex atá ann cheana féin.
    hr_HR: Alat za upravljanje zahtjevima i otkrivanje medija izgrađen za rad s vašim postojećim Plex ekosustavom.
    hu_HU: Egy kéréskezelő és médiafelderítő eszköz, amelyet a meglévő Plex ökoszisztémájához terveztek.
    it_IT: Uno strumento di gestione delle richieste e di individuazione dei contenuti multimediali, progettato per integrarsi con il tuo ecosistema Plex esistente.
    ja_JP: 既存のPlexエコシステムと連携するように構築された、リクエスト管理およびメディア検索ツールです。
    ko_KR: 기존 Plex 생태계와 연동되도록 설계된 요청 관리 및 미디어 검색 도구입니다.
    ml_IN: നിങ്ങളുടെ നിലവിലുള്ള പ്ലെക്സ് ഇക്കോസിസ്റ്റവുമായി പ്രവർത്തിക്കാൻ നിർമ്മിച്ച ഒരു റിക്വസ്റ്റ് മാനേജ്‌മെന്റ്, മീഡിയ കണ്ടെത്തൽ ഉപകരണം.
    nb_NO: Et verktøy for forespørselshåndtering og medieoppdagelse som er bygget for å fungere med ditt eksisterende Plex-økosystem.
    nl_NL: Een tool voor het beheren van aanvragen en het vinden van media, ontworpen om te werken met uw bestaande Plex-ecosysteem.
    pl_PL: Narzędzie do zarządzania żądaniami i wyszukiwania multimediów stworzone z myślą o współpracy z istniejącym ekosystemem Plex.
    pt_BR: Uma ferramenta de gerenciamento de solicitações e descoberta de mídia criada para funcionar com seu ecossistema Plex existente.
    ro_RO: Un instrument de gestionare a solicitărilor și de descoperire a conținutului media, conceput pentru a funcționa cu ecosistemul Plex existent.
    ru_RU: Инструмент для управления запросами и поиска медиафайлов, разработанный для работы с вашей существующей экосистемой Plex.
    sk_SK: Nástroj na správu požiadaviek a vyhľadávanie médií vytvorený pre prácu s vaším existujúcim ekosystémom Plex.
    sv_SE: Ett verktyg för förfrågningshantering och medieupptäckt, byggt för att fungera med ditt befintliga Plex-ekosystem.
    tr_TR: Mevcut Plex ekosisteminizle çalışmak üzere tasarlanmış bir istek yönetimi ve medya keşif aracı.
    zh_TW: 為 Plex 生態提供媒體發現和請求管理。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/overseerr.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/overseerr.png
  title:
    en_US: Overseerr
    zh_CN: Overseerr
    ca_ES: Overseerr
    cs_CZ: Overseerr
    da_DK: Overseerr
    de_DE: Overseerr
    el_GR: Overseerr
    en_GB: Overseerr
    es_ES: Overseerr
    fr_FR: Overseerr
    ga_IE: Overseerr
    hr_HR: Overseerr
    hu_HU: Overseerr
    it_IT: Overseerr
    ja_JP: Overseerr
    ko_KR: Overseerr
    ml_IN: Overseerr
    nb_NO: Overseerr
    nl_NL: Overseerr
    pl_PL: Overseerr
    pt_BR: Overseerr
    ro_RO: Overseerr
    ru_RU: Overseerr
    sk_SK: Overseerr
    sv_SE: Overseerr
    tr_TR: Overseerr
    zh_TW: Overseerr
  category: Others
  project_url: https://overseerr.dev/
  port_map: '5055'
  id: wisdomsky.linuxserver.linuxserveroverseerr
  version: 1.33.2
  website: https://overseerr.dev/
