name: linuxserver-nntp2nntp
services:
  app:
    image: linuxserver/nntp2nntp:0.3.20230704
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: PUID
          description:
            en_US: specify your UID
        - container: PGID
          description:
            en_US: specify your GID
      volumes:
        - container: /config
          description:
            en_US: appdata
      ports:
        - container: '1563'
          description:
            en_US: Proxy Port
    ports:
      - target: 1563
        published: 1563
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nntp2nntp/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: 'Visit homepage: https://hub.docker.com/r/linuxserver/nntp2nntp/'
    zh_CN: |-
      Nntp2nntp 代理允许多个系统共享 NNTP 账户，各系统可使用独立的用户名和密码。它完整支持 SSL，也可通过 SSL 证书限制代理访问。该代理简单且快速。警告：虽然未发现已知安全问题，但上游代码自上游注明的 06.08.15 以来未有更新，项目很可能已被永久弃置。因此强烈建议不要将其暴露到公网；如必须公开访问，额外安全防护和 SSL 应作为最低要求。其主要用途是在局域网内，让各个 NNTP 应用共享一组内部凭据，并集中管理上游账户，例如通过一次全局配置变更切换服务商、服务器或连接线程限制。

      访问项目主页：https://hub.docker.com/r/linuxserver/nntp2nntp/
  tagline:
    en_US: 'Proxy allow you to use your NNTP Account from multiple systems, each with own user name and password. It fully supports SSL and you can also limit the access to proxy with SSL certificates. Nntp2nntp proxy is very simple and pretty fast. ## Warning Whilst we know of no nntp2nntp security issues the upstream code for this project has received no changes since 06. 08. 15 and is likely abandoned permanently. For this reason we strongly recommend you do not make this application public facing and if you must do so other layers of security and SSL should be considered an absolute bare minimum requirement. We see this proxy being used primarily on a LAN so that all the users NNTP applications can share a common set of internal credentials allowing for central managment of the upstream account e. G change provider, server, thread limits for all applications with one global config change.'
    zh_CN: 让多个系统通过独立凭据共享 NNTP 账户。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nntp2nntp.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nntp2nntp.png
  title:
    en_US: Nntp2nntp
    zh_CN: Nntp2nntp
  category: Others
  project_url: https://github.com/linuxserver/nntp2nntp
  id: wisdomsky.linuxserver.linuxservernntp2nntp
  version: 0.3.20230704
  website: https://github.com/linuxserver/nntp2nntp
