name: linuxserver-pairdrop
services:
  app:
    image: linuxserver/pairdrop:1.11.2@sha256:3d7043d519293ce579e5d3c62c2e333d120a989e6be8a4a261b7bb23ce5b8fb8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RATE_LIMIT: ''
      WS_FALLBACK: ''
      RTC_CONFIG: ''
      DEBUG_MODE: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pairdrop/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverpairdrop/assets/icon.png
  title:
    en_US: Pairdrop (LinuxServer.io)
    zh_CN: Pairdrop（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverpairdrop
  port_map: '3000'
  version: 1.11.2
