name: linuxserver-pairdrop
services:
  app:
    image: linuxserver/pairdrop:1.11.2@sha256:3d7043d519293ce579e5d3c62c2e333d120a989e6be8a4a261b7bb23ce5b8fb8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RATE_LIMIT: ''
      WS_FALLBACK: ''
      RTC_CONFIG: ''
      DEBUG_MODE: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pairdrop/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverpairdrop/assets/icon.png
  title:
    en_US: Pairdrop (LinuxServer.io)
    ca_ES: Pairdrop (LinuxServer.io)
    cs_CZ: Pairdrop (LinuxServer.io)
    da_DK: Pairdrop (LinuxServer.io)
    de_DE: Pairdrop (LinuxServer.io)
    el_GR: Pairdrop (LinuxServer.io)
    en_GB: Pairdrop (LinuxServer.io)
    es_ES: Pairdrop (LinuxServer.io)
    fr_FR: Pairdrop (LinuxServer.io)
    ga_IE: Pairdrop (LinuxServer.io)
    hr_HR: Pairdrop (LinuxServer.io)
    hu_HU: Pairdrop (LinuxServer.io)
    it_IT: Pairdrop (LinuxServer.io)
    ja_JP: Pairdrop (LinuxServer.io)
    ko_KR: Pairdrop (LinuxServer.io)
    ml_IN: Pairdrop (LinuxServer.io)
    nb_NO: Pairdrop (LinuxServer.io)
    nl_NL: Pairdrop (LinuxServer.io)
    pl_PL: Pairdrop (LinuxServer.io)
    pt_BR: Pairdrop (LinuxServer.io)
    ro_RO: Pairdrop (LinuxServer.io)
    ru_RU: Pairdrop (LinuxServer.io)
    sk_SK: Pairdrop (LinuxServer.io)
    sv_SE: Pairdrop (LinuxServer.io)
    tr_TR: Pairdrop (LinuxServer.io)
    zh_CN: Pairdrop（LinuxServer.io）
    zh_TW: Pairdrop（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverpairdrop
  port_map: '3000'
  version: 1.11.2
