name: linuxserver-mylar3
services:
  app:
    image: linuxserver/mylar3:0.11.0@sha256:af1d74d21f0114788895dabc829d73e9ed4e7725d4f902bf14bc72c64efcda2d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8090
        published: 8090
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mylar3/config
        target: /config
      - type: bind
        source: /DATA/AppData/mylar3/comics
        target: /comics
      - type: bind
        source: /DATA/AppData/mylar3/downloads
        target: /downloads
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermylar3/assets/icon.png
  title:
    en_US: Mylar3 (LinuxServer.io)
    ca_ES: Mylar3 (LinuxServer.io)
    cs_CZ: Mylar3 (LinuxServer.io)
    da_DK: Mylar3 (LinuxServer.io)
    de_DE: Mylar3 (LinuxServer.io)
    el_GR: Mylar3 (LinuxServer.io)
    en_GB: Mylar3 (LinuxServer.io)
    es_ES: Mylar3 (LinuxServer.io)
    fr_FR: Mylar3 (LinuxServer.io)
    ga_IE: Mylar3 (LinuxServer.io)
    hr_HR: Mylar3 (LinuxServer.io)
    hu_HU: Mylar3 (LinuxServer.io)
    it_IT: Mylar3 (LinuxServer.io)
    ja_JP: Mylar3 (LinuxServer.io)
    ko_KR: Mylar3 (LinuxServer.io)
    ml_IN: Mylar3 (LinuxServer.io)
    nb_NO: Mylar3 (LinuxServer.io)
    nl_NL: Mylar3 (LinuxServer.io)
    pl_PL: Mylar3 (LinuxServer.io)
    pt_BR: Mylar3 (LinuxServer.io)
    ro_RO: Mylar3 (LinuxServer.io)
    ru_RU: Mylar3 (LinuxServer.io)
    sk_SK: Mylar3 (LinuxServer.io)
    sv_SE: Mylar3 (LinuxServer.io)
    tr_TR: Mylar3 (LinuxServer.io)
    zh_CN: Mylar3（LinuxServer.io）
    zh_TW: Mylar3（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservermylar3
  port_map: '8090'
  version: 0.11.0
