name: linuxserver-kicad
services:
  app:
    image: linuxserver/kicad:10.0.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kicad/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverkicad/assets/icon.png
  title:
    en_US: Kicad (LinuxServer.io)
    ca_ES: Kicad (LinuxServer.io)
    cs_CZ: Kicad (LinuxServer.io)
    da_DK: Kicad (LinuxServer.io)
    de_DE: Kicad (LinuxServer.io)
    el_GR: Kicad (LinuxServer.io)
    en_GB: Kicad (LinuxServer.io)
    es_ES: Kicad (LinuxServer.io)
    fr_FR: Kicad (LinuxServer.io)
    ga_IE: Kicad (LinuxServer.io)
    hr_HR: Kicad (LinuxServer.io)
    hu_HU: Kicad (LinuxServer.io)
    it_IT: Kicad (LinuxServer.io)
    ja_JP: Kicad (LinuxServer.io)
    ko_KR: Kicad (LinuxServer.io)
    ml_IN: Kicad (LinuxServer.io)
    nb_NO: Kicad (LinuxServer.io)
    nl_NL: Kicad (LinuxServer.io)
    pl_PL: Kicad (LinuxServer.io)
    pt_BR: Kicad (LinuxServer.io)
    ro_RO: Kicad (LinuxServer.io)
    ru_RU: Kicad (LinuxServer.io)
    sk_SK: Kicad (LinuxServer.io)
    sv_SE: Kicad (LinuxServer.io)
    tr_TR: Kicad (LinuxServer.io)
    zh_CN: Kicad（LinuxServer.io）
    zh_TW: Kicad（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverkicad
  port_map: '3000'
  version: 10.0.3
