name: linuxserver-ombi
services:
  app:
    image: linuxserver/ombi:4.53.10
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: BASE_URL
          description:
            en_US: Subfolder can optionally be defined as an env variable for reverse proxies. Keep in mind that once this value is defined, the gui setting for base url no longer works. To use the gui setting, remove this env variable. [OPTIONAL]
    ports:
      - target: 3579
        published: 3579
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ombi/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Ombi allows you to host your own Plex Request and user management system. If you are sharing your Plex server with other users, allow them to request new content using an easy to manage interface! Manage all your requests for Movies and TV with ease, leave notes for the user and get notification when a user requests something. Allow your users to post issues against their requests so you know there is a problem with the audio etc. Even automatically send them weekly newsletters of new content that has been added to your Plex server!
    ca_ES: Ombi et permet allotjar el teu propi sistema de gestió d'usuaris i sol·licituds Plex. Si comparteixes el teu servidor Plex amb altres usuaris, permet-los sol·licitar contingut nou mitjançant una interfície fàcil de gestionar! Gestiona totes les teves sol·licituds de pel·lícules i programes de televisió amb facilitat, deixa notes per a l'usuari i rep notificacions quan un usuari sol·liciti alguna cosa. Permet als teus usuaris publicar problemes relacionats amb les seves sol·licituds perquè sàpigues que hi ha un problema amb l'àudio, etc. Fins i tot envia'ls automàticament butlletins setmanals amb contingut nou que s'ha afegit al teu servidor Plex!
    cs_CZ: Ombi vám umožňuje hostovat vlastní systém pro správu požadavků a uživatelů Plex. Pokud sdílíte svůj server Plex s ostatními uživateli, umožněte jim vyžádat si nový obsah pomocí snadno spravovatelného rozhraní! Snadno spravujte všechny své požadavky na filmy a TV, zanechávejte uživatelům poznámky a dostávejte upozornění, když si uživatel něco vyžádá. Umožněte svým uživatelům zveřejňovat problémy s jejich požadavky, abyste věděli, že existuje problém se zvukem atd. Dokonce jim můžete automaticky zasílat týdenní newslettery s novým obsahem, který byl přidán na váš server Plex!
    da_DK: Ombi giver dig mulighed for at hoste dit eget Plex-forespørgsels- og brugerstyringssystem. Hvis du deler din Plex-server med andre brugere, kan du give dem mulighed for at anmode om nyt indhold ved hjælp af en brugervenlig grænseflade! Administrer alle dine anmodninger om film og tv med lethed, skriv noter til brugeren, og få besked, når en bruger anmoder om noget. Giv dine brugere mulighed for at indsende problemer med deres anmodninger, så du ved, at der er et problem med lyden osv. Du kan endda automatisk sende dem ugentlige nyhedsbreve med nyt indhold, der er blevet tilføjet til din Plex-server!
    de_DE: Mit Ombi hosten Sie Ihr eigenes Plex-Anfrage- und Benutzerverwaltungssystem. Wenn Sie Ihren Plex-Server mit anderen Nutzern teilen, ermöglichen Sie ihnen, neue Inhalte über eine benutzerfreundliche Oberfläche anzufordern! Verwalten Sie alle Anfragen für Filme und Serien ganz einfach, hinterlassen Sie Notizen für die Nutzer und erhalten Sie Benachrichtigungen, sobald eine Anfrage eingeht. Ermöglichen Sie Ihren Nutzern, Probleme mit ihren Anfragen zu melden, damit Sie über etwaige Schwierigkeiten mit dem Ton etc. informiert sind. Versenden Sie sogar automatisch wöchentliche Newsletter mit den neuesten Inhalten auf Ihrem Plex-Server!
    el_GR: Το Ombi σάς επιτρέπει να φιλοξενήσετε το δικό σας σύστημα Plex Request και διαχείρισης χρηστών. Εάν μοιράζεστε τον Plex server σας με άλλους χρήστες, επιτρέψτε τους να ζητούν νέο περιεχόμενο χρησιμοποιώντας ένα εύκολο στη διαχείριση περιβάλλον εργασίας! Διαχειριστείτε όλα τα αιτήματά σας για ταινίες και τηλεοπτικές εκπομπές με ευκολία, αφήστε σημειώσεις για τον χρήστη και λάβετε ειδοποιήσεις όταν ένας χρήστης ζητήσει κάτι. Επιτρέψτε στους χρήστες σας να δημοσιεύουν προβλήματα σχετικά με τα αιτήματά τους, ώστε να γνωρίζετε ότι υπάρχει πρόβλημα με τον ήχο κ.λπ. Στείλτε τους αυτόματα εβδομαδιαία ενημερωτικά δελτία με νέο περιεχόμενο που έχει προστεθεί στον Plex server σας!
    en_GB: Ombi allows you to host your own Plex Request and user management system. If you are sharing your Plex server with other users, allow them to request new content using an easy to manage interface! Manage all your requests for Movies and Tv with ease, leave notes for the user and get notification when a user requests something. Allow your users to post issues against their requests so you know there is a problem with the audio etc. Even automatically send them weekly newsletters of new content that has been added to your Plex server!
    es_ES: Ombi te permite alojar tu propio sistema de gestión de usuarios y solicitudes de Plex. Si compartes tu servidor Plex con otros usuarios, permíteles solicitar contenido nuevo mediante una interfaz fácil de usar. Gestiona todas las solicitudes de películas y series con facilidad, deja notas para los usuarios y recibe notificaciones cuando soliciten algo. Permite que tus usuarios reporten problemas con sus solicitudes para que sepas si hay algún inconveniente con el audio, etc. ¡Incluso puedes enviarles automáticamente boletines semanales con el nuevo contenido añadido a tu servidor Plex!
    fr_FR: "Ombi vous permet d'héberger votre propre système de gestion des demandes et des utilisateurs Plex. Si vous partagez votre serveur Plex, offrez à vos utilisateurs la possibilité de demander du contenu via une interface intuitive\_! Gérez facilement toutes vos demandes de films et de séries, laissez des notes aux utilisateurs et recevez des notifications lorsqu'une demande est faite. Vos utilisateurs peuvent signaler les problèmes rencontrés avec leurs demandes, notamment au niveau audio. Vous pouvez même leur envoyer automatiquement une newsletter hebdomadaire les informant des nouveaux contenus ajoutés à votre serveur Plex\_!"
    ga_IE: Ligeann Ombi duit do chóras bainistíochta úsáideoirí agus Iarratas Plex féin a óstáil. Má tá tú ag roinnt do fhreastalaí Plex le húsáideoirí eile, lig dóibh ábhar nua a iarraidh trí chomhéadan atá éasca le bainistiú! Bainistigh do chuid iarratais go léir ar Scannáin agus ar Theilifís go héasca, fág nótaí don úsáideoir agus faigh fógra nuair a iarrann úsáideoir rud éigin. Lig do d’úsáideoirí saincheisteanna a phostáil i gcoinne a n-iarratais ionas go mbeidh a fhios agat go bhfuil fadhb leis an bhfuaim srl. Seol nuachtlitreacha seachtainiúla chucu go huathoibríoch fiú d’ábhar nua atá curtha le do fhreastalaí Plex!
    hr_HR: Ombi vam omogućuje hostiranje vlastitog Plex sustava za zahtjeve i upravljanje korisnicima. Ako dijelite svoj Plex poslužitelj s drugim korisnicima, omogućite im da zatraže novi sadržaj pomoću jednostavnog sučelja! S lakoćom upravljajte svim svojim zahtjevima za filmove i TV emisije, ostavljajte bilješke za korisnika i primajte obavijesti kada korisnik nešto zatraži. Omogućite svojim korisnicima da objavljuju probleme sa svojim zahtjevima kako biste znali da postoji problem sa zvukom itd. Čak im automatski šaljite tjedne biltene o novom sadržaju koji je dodan na vaš Plex poslužitelj!
    hu_HU: Az Ombi lehetővé teszi saját Plex kérések és felhasználókezelő rendszer üzemeltetését. Ha megosztod a Plex szerveredet más felhasználókkal, engedélyezd számukra új tartalmak kérését egy könnyen kezelhető felületen keresztül! Kezeld könnyedén az összes film- és tévésorozat-kérést, hagyj jegyzeteket a felhasználónak, és kapj értesítést, ha egy felhasználó kér valamit. Engedd meg a felhasználóidnak, hogy problémákat tegyenek közzé a kéréseikkel kapcsolatban, így tudhatod, hogy probléma van a hanggal stb. Akár automatikusan küldhetsz nekik heti hírleveleket a Plex szerveredre feltöltött új tartalmakról!
    it_IT: Ombi ti permette di ospitare il tuo sistema di gestione delle richieste e degli utenti Plex. Se condividi il tuo server Plex con altri utenti, consenti loro di richiedere nuovi contenuti tramite un'interfaccia facile da gestire! Gestisci con facilità tutte le richieste di film e serie TV, lascia note per gli utenti e ricevi notifiche quando qualcuno effettua una richiesta. Permetti ai tuoi utenti di segnalare eventuali problemi relativi alle loro richieste, così saprai sempre se ci sono problemi con l'audio, ecc. Puoi anche inviare loro automaticamente newsletter settimanali con i nuovi contenuti aggiunti al tuo server Plex!
    ja_JP: Ombiを使えば、独自のPlexリクエストおよびユーザー管理システムをホストできます。Plexサーバーを他のユーザーと共有している場合、使いやすいインターフェースを使って新しいコンテンツをリクエストできるようにしましょう。映画やテレビ番組のリクエストをすべて簡単に管理し、ユーザーにメモを残したり、リクエストがあった際に通知を受け取ったりできます。ユーザーがリクエストに対して問題を投稿できるようにすることで、音声などに問題があるかどうかを把握できます。さらに、Plexサーバーに追加された新しいコンテンツを毎週自動的にニュースレターで配信することも可能です。
    ko_KR: Ombi를 사용하면 자신만의 Plex 콘텐츠 요청 및 사용자 관리 시스템을 호스팅할 수 있습니다. 다른 사용자와 Plex 서버를 공유하는 경우, 사용하기 쉬운 인터페이스를 통해 다른 사용자가 새로운 콘텐츠를 요청할 수 있도록 하세요! 영화 및 TV 프로그램 요청을 간편하게 관리하고, 사용자에게 메모를 남기고, 사용자가 콘텐츠를 요청할 때 알림을 받을 수 있습니다. 사용자가 요청에 대한 문제를 보고할 수 있도록 하여 오디오 문제 등을 파악할 수 있습니다. 또한 Plex 서버에 새로 추가된 콘텐츠에 대한 주간 뉴스레터를 자동으로 발송할 수도 있습니다!
    ml_IN: നിങ്ങളുടെ സ്വന്തം പ്ലെക്സ് അഭ്യർത്ഥനയും ഉപയോക്തൃ മാനേജ്മെന്റ് സിസ്റ്റവും ഹോസ്റ്റ് ചെയ്യാൻ ഓംബി നിങ്ങളെ അനുവദിക്കുന്നു. നിങ്ങളുടെ പ്ലെക്സ് സെർവർ മറ്റ് ഉപയോക്താക്കളുമായി പങ്കിടുകയാണെങ്കിൽ, എളുപ്പത്തിൽ കൈകാര്യം ചെയ്യാവുന്ന ഇന്റർഫേസ് ഉപയോഗിച്ച് പുതിയ ഉള്ളടക്കം അഭ്യർത്ഥിക്കാൻ അവരെ അനുവദിക്കുക! സിനിമകൾക്കും ടിവിക്കുമുള്ള നിങ്ങളുടെ എല്ലാ അഭ്യർത്ഥനകളും എളുപ്പത്തിൽ കൈകാര്യം ചെയ്യുക, ഉപയോക്താവിനായി കുറിപ്പുകൾ ഇടുക, ഒരു ഉപയോക്താവ് എന്തെങ്കിലും അഭ്യർത്ഥിക്കുമ്പോൾ അറിയിപ്പ് നേടുക. ഓഡിയോ മുതലായവയിൽ ഒരു പ്രശ്നമുണ്ടെന്ന് അറിയാൻ നിങ്ങളുടെ ഉപയോക്താക്കളെ അവരുടെ അഭ്യർത്ഥനകൾക്കെതിരെ പ്രശ്നങ്ങൾ പോസ്റ്റ് ചെയ്യാൻ അനുവദിക്കുക. നിങ്ങളുടെ പ്ലെക്സ് സെർവറിലേക്ക് ചേർത്ത പുതിയ ഉള്ളടക്കത്തിന്റെ ആഴ്ചതോറുമുള്ള വാർത്താക്കുറിപ്പുകൾ പോലും അവർക്ക് സ്വയമേവ അയയ്ക്കുക!
    nb_NO: Med Ombi kan du være vert for ditt eget Plex-forespørsels- og brukeradministrasjonssystem. Hvis du deler Plex-serveren din med andre brukere, kan du la dem be om nytt innhold ved hjelp av et brukervennlig grensesnitt! Administrer alle forespørslene dine om filmer og TV-serier enkelt, legg igjen notater til brukeren og få varsel når en bruker ber om noe. La brukerne dine legge ut problemer mot forespørslene sine, slik at du vet at det er et problem med lyden osv. Du kan til og med automatisk sende dem ukentlige nyhetsbrev med nytt innhold som er lagt til Plex-serveren din!
    nl_NL: Met Ombi kunt u uw eigen Plex-aanvraag- en gebruikersbeheersysteem hosten. Als u uw Plex-server deelt met andere gebruikers, kunt u hen via een gebruiksvriendelijke interface nieuwe content laten aanvragen! Beheer al uw aanvragen voor films en tv-series eenvoudig, voeg notities toe voor de gebruiker en ontvang meldingen wanneer een gebruiker iets aanvraagt. Laat uw gebruikers problemen melden bij hun aanvragen, zodat u weet of er bijvoorbeeld een probleem is met het geluid. U kunt ze zelfs automatisch wekelijkse nieuwsbrieven sturen met nieuwe content die aan uw Plex-server is toegevoegd!
    pl_PL: Ombi pozwala na hostowanie własnego systemu Plex Request i zarządzania użytkownikami. Jeśli udostępniasz serwer Plex innym użytkownikom, pozwól im zgłaszać prośby o nowe treści za pomocą łatwego w obsłudze interfejsu! Zarządzaj z łatwością wszystkimi swoimi prośbami o filmy i programy telewizyjne, zostawiaj notatki dla użytkowników i otrzymuj powiadomienia, gdy o coś poproszą. Pozwól użytkownikom zgłaszać problemy związane z ich prośbami, aby wiedzieć, czy wystąpił problem z dźwiękiem itp. Możesz nawet automatycznie wysyłać im cotygodniowe newslettery z informacjami o nowych treściach dodanych do Twojego serwera Plex!
    pt_BR: O Ombi permite que você hospede seu próprio sistema de gerenciamento de solicitações e usuários do Plex. Se você compartilha seu servidor Plex com outros usuários, permita que eles solicitem novos conteúdos usando uma interface fácil de usar! Gerencie todas as suas solicitações de filmes e séries com facilidade, deixe recados para os usuários e receba notificações quando um usuário solicitar algo. Permita que seus usuários relatem problemas com suas solicitações para que você saiba se há algum problema com o áudio, por exemplo. Você pode até enviar newsletters semanais automáticas com os novos conteúdos adicionados ao seu servidor Plex!
    ro_RO: Ombi vă permite să găzduiți propriul sistem Plex Request și de gestionare a utilizatorilor. Dacă partajați serverul Plex cu alți utilizatori, permiteți-le să solicite conținut nou folosind o interfață ușor de gestionat! Gestionați cu ușurință toate solicitările pentru filme și emisiuni TV, lăsați note pentru utilizator și primiți notificări atunci când un utilizator solicită ceva. Permiteți utilizatorilor să posteze probleme legate de solicitările lor, astfel încât să știți că există o problemă cu sunetul etc. Le puteți chiar trimite automat newslettere săptămânale cu conținut nou adăugat pe serverul Plex!
    ru_RU: Ombi позволяет разместить собственную систему запросов и управления пользователями Plex. Если вы делите свой сервер Plex с другими пользователями, позвольте им запрашивать новый контент, используя простой в управлении интерфейс! Легко управляйте всеми запросами на фильмы и сериалы, оставляйте заметки для пользователей и получайте уведомления, когда пользователь что-то запрашивает. Позвольте пользователям сообщать о проблемах со своими запросами, чтобы вы знали о проблемах со звуком и т.д. Вы даже можете автоматически отправлять им еженедельные информационные бюллетени о новом контенте, добавленном на ваш сервер Plex!
    sk_SK: Ombi vám umožňuje hostiť vlastný systém Plex Request a správy používateľov. Ak zdieľate svoj Plex server s inými používateľmi, umožnite im žiadať o nový obsah pomocou ľahko spravovateľného rozhrania! Spravujte všetky svoje požiadavky na filmy a televíziu s ľahkosťou, zanechajte používateľom poznámky a dostávajte upozornenia, keď používateľ niečo požaduje. Umožnite svojim používateľom uverejňovať problémy s ich požiadavkami, aby ste vedeli, že existuje problém so zvukom atď. Dokonca im automaticky posielajte týždenné newslettery s novým obsahom, ktorý bol pridaný na váš Plex server!
    sv_SE: Med Ombi kan du ha ditt eget Plex-system för förfrågningar och användarhantering. Om du delar din Plex-server med andra användare kan du låta dem begära nytt innehåll med ett lätthanterligt gränssnitt! Hantera alla dina förfrågningar om film och TV enkelt, lämna anteckningar till användaren och få meddelanden när en användare begär något. Låt dina användare posta problem med sina förfrågningar så att du vet att det finns problem med ljudet etc. Du kan till och med automatiskt skicka dem veckovisa nyhetsbrev med nytt innehåll som har lagts till på din Plex-server!
    tr_TR: Ombi, kendi Plex istek ve kullanıcı yönetim sisteminizi barındırmanıza olanak tanır. Plex sunucunuzu diğer kullanıcılarla paylaşıyorsanız, kullanımı kolay bir arayüz kullanarak yeni içerik talep etmelerine izin verin! Film ve dizi isteklerinizin tümünü kolayca yönetin, kullanıcı için notlar bırakın ve bir kullanıcı bir şey talep ettiğinde bildirim alın. Kullanıcılarınızın istekleriyle ilgili sorunları bildirmelerine izin verin, böylece sesle ilgili bir sorun olduğunu bilirsiniz. Hatta Plex sunucunuza eklenen yeni içeriklerle ilgili haftalık bültenleri otomatik olarak onlara gönderin!
    zh_CN: Ombi 让你自行托管 Plex 内容请求和用户管理系统。如果你与他人共享 Plex 服务器，他们可以通过易于管理的界面请求新内容。你可轻松管理电影和电视剧请求、为用户留言，并在收到请求时获得通知。用户还可报告请求内容的问题，例如音频异常。系统甚至可以每周自动发送新增 Plex 内容的电子简报。
    zh_TW: Ombi 讓你自行託管 Plex 內容請求和使用者管理系統。如果你與他人共享 Plex 伺服器，他們可以透過易於管理的介面請求新內容。你可輕鬆管理電影和電視劇請求、為使用者留言，並在收到請求時獲得通知。使用者還可報告請求內容的問題，例如音訊異常。系統甚至可以每週自動傳送新增 Plex 內容的電子簡報。
  tagline:
    en_US: Allows you to host your own Plex Request and user management system. If you are sharing your Plex server with other users, allow them to request new content using an easy to manage interface. Manage all your requests for Movies and TV with ease, leave notes for the user and get notification when a user requests something. Allow your users to post issues against their requests so you know there is a problem with the audio etc. Even automatically send them weekly newsletters of new content that has been added to your Plex server.
    ca_ES: Et permet allotjar el teu propi sistema de gestió d'usuaris i sol·licituds Plex. Si comparteixes el teu servidor Plex amb altres usuaris, permet-los sol·licitar contingut nou mitjançant una interfície fàcil de gestionar. Gestiona totes les teves sol·licituds de pel·lícules i programes de televisió amb facilitat, deixa notes per a l'usuari i rep notificacions quan un usuari sol·liciti alguna cosa. Permet als teus usuaris publicar problemes relacionats amb les seves sol·licituds perquè sàpigues que hi ha un problema amb l'àudio, etc. Fins i tot els pots enviar automàticament butlletins setmanals amb contingut nou que s'ha afegit al teu servidor Plex.
    cs_CZ: Umožňuje vám hostovat vlastní systém pro správu požadavků a uživatelů Plex. Pokud sdílíte svůj server Plex s ostatními uživateli, umožněte jim vyžádat si nový obsah pomocí snadno spravovatelného rozhraní. Snadno spravujte všechny své požadavky na filmy a TV, zanechávejte uživatelům poznámky a dostávejte upozornění, když uživatel něco požaduje. Umožněte svým uživatelům zveřejňovat problémy s jejich požadavky, abyste věděli, že existuje problém se zvukem atd. Dokonce jim automaticky zasílejte týdenní newslettery s novým obsahem, který byl přidán na váš server Plex.
    da_DK: Giver dig mulighed for at hoste dit eget Plex-forespørgsels- og brugerstyringssystem. Hvis du deler din Plex-server med andre brugere, kan du give dem mulighed for at anmode om nyt indhold ved hjælp af en brugervenlig grænseflade. Administrer alle dine anmodninger om film og tv-serier med lethed, skriv noter til brugeren, og få besked, når en bruger anmoder om noget. Giv dine brugere mulighed for at indsende problemer med deres anmodninger, så du ved, at der er et problem med lyden osv. Du kan endda automatisk sende dem ugentlige nyhedsbreve med nyt indhold, der er blevet tilføjet til din Plex-server.
    de_DE: Mit diesem System können Sie Ihre eigenen Plex-Anfragen und Benutzer verwalten. Wenn Sie Ihren Plex-Server mit anderen Nutzern teilen, ermöglichen Sie ihnen, neue Inhalte über eine benutzerfreundliche Oberfläche anzufordern. Verwalten Sie alle Anfragen für Filme und Serien ganz einfach, hinterlassen Sie Notizen für die Nutzer und erhalten Sie Benachrichtigungen, sobald eine Anfrage eingeht. Ermöglichen Sie Ihren Nutzern, Probleme mit ihren Anfragen zu melden, damit Sie über etwaige Schwierigkeiten mit dem Ton etc. informiert sind. Versenden Sie sogar automatisch wöchentliche Newsletter mit den neuesten Inhalten auf Ihrem Plex-Server.
    el_GR: Σας επιτρέπει να φιλοξενήσετε το δικό σας σύστημα διαχείρισης αιτημάτων και χρηστών Plex. Εάν μοιράζεστε τον διακομιστή Plex σας με άλλους χρήστες, επιτρέψτε τους να ζητούν νέο περιεχόμενο χρησιμοποιώντας ένα εύκολο στη διαχείριση περιβάλλον εργασίας. Διαχειριστείτε όλα τα αιτήματά σας για ταινίες και τηλεοπτικές εκπομπές με ευκολία, αφήστε σημειώσεις για τον χρήστη και λάβετε ειδοποιήσεις όταν ένας χρήστης ζητήσει κάτι. Επιτρέψτε στους χρήστες σας να δημοσιεύουν προβλήματα σχετικά με τα αιτήματά τους, ώστε να γνωρίζετε ότι υπάρχει πρόβλημα με τον ήχο κ.λπ. Στείλτε τους αυτόματα εβδομαδιαία ενημερωτικά δελτία με νέο περιεχόμενο που έχει προστεθεί στον διακομιστή Plex σας.
    en_GB: Allows you to host your own Plex Request and user management system. If you are sharing your Plex server with other users, allow them to request new content using an easy to manage interface. Manage all your requests for Movies and Tv with ease, leave notes for the user and get notification when a user requests something. Allow your users to post issues against their requests so you know there is a problem with the audio etc. Even automatically send them weekly newsletters of new content that has been added to your Plex server.
    es_ES: Te permite alojar tu propio sistema de gestión de usuarios y solicitudes de Plex. Si compartes tu servidor Plex con otros usuarios, permíteles solicitar contenido nuevo mediante una interfaz fácil de usar. Gestiona todas las solicitudes de películas y series con facilidad, deja notas para el usuario y recibe notificaciones cuando soliciten algo. Permite que tus usuarios reporten problemas con sus solicitudes para que sepas si hay algún inconveniente con el audio, etc. Incluso puedes enviarles automáticamente boletines semanales con el nuevo contenido añadido a tu servidor Plex.
    fr_FR: Vous pouvez ainsi héberger votre propre système de gestion des demandes et des utilisateurs Plex. Si vous partagez votre serveur Plex, permettez à d'autres utilisateurs de demander du contenu via une interface simple d'utilisation. Gérez facilement toutes vos demandes de films et de séries, laissez des notes aux utilisateurs et recevez des notifications lorsqu'une demande est faite. Vos utilisateurs peuvent signaler les problèmes rencontrés avec leurs demandes, notamment au niveau audio. Vous pouvez même leur envoyer automatiquement une newsletter hebdomadaire les informant des nouveaux contenus ajoutés à votre serveur Plex.
    ga_IE: Ligeann sé duit do chóras bainistíochta úsáideoirí agus Iarratas Plex féin a óstáil. Má tá tú ag roinnt do fhreastalaí Plex le húsáideoirí eile, lig dóibh ábhar nua a iarraidh trí chomhéadan atá éasca le bainistiú. Bainistigh do chuid iarratais go léir ar Scannáin agus Teilifís go héasca, fág nótaí don úsáideoir agus faigh fógra nuair a iarrann úsáideoir rud éigin. Lig do d’úsáideoirí saincheisteanna a phostáil i gcoinne a n-iarratais ionas go mbeidh a fhios agat go bhfuil fadhb leis an bhfuaim srl. Seol nuachtlitreacha seachtainiúla chucu go huathoibríoch fiú d’ábhar nua atá curtha le do fhreastalaí Plex.
    hr_HR: Omogućuje vam hostiranje vlastitog Plex zahtjeva i sustava za upravljanje korisnicima. Ako dijelite svoj Plex poslužitelj s drugim korisnicima, omogućite im da zatraže novi sadržaj pomoću jednostavnog sučelja. S lakoćom upravljajte svim svojim zahtjevima za filmove i TV emisije, ostavljajte bilješke za korisnika i primajte obavijesti kada korisnik nešto zatraži. Omogućite svojim korisnicima da objavljuju probleme sa svojim zahtjevima kako biste znali da postoji problem sa zvukom itd. Čak im automatski šaljite tjedne biltene o novom sadržaju koji je dodan na vaš Plex poslužitelj.
    hu_HU: Lehetővé teszi saját Plex kérések és felhasználókezelő rendszer üzemeltetését. Ha megosztod a Plex szerveredet más felhasználókkal, engedélyezd számukra új tartalmak kérését egy könnyen kezelhető felületen keresztül. Kezeld könnyedén az összes film- és tévéműsor-kérést, hagyj jegyzeteket a felhasználónak, és kapj értesítést, ha egy felhasználó kér valamit. Lehetővé teszed a felhasználók számára, hogy problémákat tegyenek közzé a kéréseikkel kapcsolatban, így tudhatod, hogy probléma van a hanggal stb. Akár automatikusan küldhetsz nekik heti hírleveleket a Plex szerveredre feltöltött új tartalmakról.
    it_IT: Consente di ospitare il proprio sistema di gestione delle richieste e degli utenti Plex. Se condividi il tuo server Plex con altri utenti, permetti loro di richiedere nuovi contenuti tramite un'interfaccia facile da gestire. Gestisci con facilità tutte le richieste di film e serie TV, lascia note per l'utente e ricevi notifiche quando un utente effettua una richiesta. Permetti ai tuoi utenti di segnalare problemi relativi alle loro richieste, in modo da essere informato su eventuali problemi audio, ecc. Puoi anche inviare loro automaticamente newsletter settimanali con i nuovi contenuti aggiunti al tuo server Plex.
    ja_JP: 独自のPlexリクエストおよびユーザー管理システムをホストできます。Plexサーバーを他のユーザーと共有している場合は、管理しやすいインターフェースを使用して、ユーザーが新しいコンテンツをリクエストできるようにします。映画やテレビ番組のすべてのリクエストを簡単に管理し、ユーザーにメモを残したり、ユーザーが何かをリクエストしたときに通知を受け取ったりできます。ユーザーがリクエストに対して問題を投稿できるようにすることで、オーディオなどの問題があることを把握できます。さらに、Plexサーバーに追加された新しいコンテンツの週刊ニュースレターをユーザーに自動的に送信することもできます。
    ko_KR: Plex 콘텐츠 요청 및 사용자 관리 시스템을 직접 운영할 수 있습니다. 다른 사용자와 Plex 서버를 공유하는 경우, 사용하기 쉬운 인터페이스를 통해 사용자들이 새로운 콘텐츠를 요청할 수 있도록 하세요. 영화 및 TV 프로그램 요청을 간편하게 관리하고, 사용자에게 메모를 남기고, 요청이 접수되면 알림을 받을 수 있습니다. 사용자가 요청에 대한 문제를 보고할 수 있도록 하여 오디오 문제 등을 파악할 수 있습니다. 또한, Plex 서버에 새로 추가된 콘텐츠에 대한 주간 뉴스레터를 자동으로 발송할 수도 있습니다.
    ml_IN: നിങ്ങളുടെ സ്വന്തം പ്ലെക്സ് അഭ്യർത്ഥനയും ഉപയോക്തൃ മാനേജ്മെന്റ് സിസ്റ്റവും ഹോസ്റ്റ് ചെയ്യാൻ നിങ്ങളെ അനുവദിക്കുന്നു. നിങ്ങളുടെ പ്ലെക്സ് സെർവർ മറ്റ് ഉപയോക്താക്കളുമായി പങ്കിടുകയാണെങ്കിൽ, എളുപ്പത്തിൽ കൈകാര്യം ചെയ്യാവുന്ന ഇന്റർഫേസ് ഉപയോഗിച്ച് പുതിയ ഉള്ളടക്കം അഭ്യർത്ഥിക്കാൻ അവരെ അനുവദിക്കുക. സിനിമകൾക്കും ടിവിക്കുമുള്ള നിങ്ങളുടെ എല്ലാ അഭ്യർത്ഥനകളും എളുപ്പത്തിൽ കൈകാര്യം ചെയ്യുക, ഉപയോക്താവിനായി കുറിപ്പുകൾ ഇടുക, ഒരു ഉപയോക്താവ് എന്തെങ്കിലും അഭ്യർത്ഥിക്കുമ്പോൾ അറിയിപ്പ് നേടുക. ഓഡിയോ മുതലായവയിൽ ഒരു പ്രശ്നമുണ്ടെന്ന് അറിയാൻ നിങ്ങളുടെ ഉപയോക്താക്കളെ അവരുടെ അഭ്യർത്ഥനകൾക്കെതിരെ പ്രശ്നങ്ങൾ പോസ്റ്റ് ചെയ്യാൻ അനുവദിക്കുക. നിങ്ങളുടെ പ്ലെക്സ് സെർവറിലേക്ക് ചേർത്തിട്ടുള്ള പുതിയ ഉള്ളടക്കത്തിന്റെ ആഴ്ചതോറുമുള്ള വാർത്താക്കുറിപ്പുകൾ പോലും സ്വയമേവ അവർക്ക് അയയ്ക്കുക.
    nb_NO: Lar deg være vert for ditt eget Plex-forespørsels- og brukeradministrasjonssystem. Hvis du deler Plex-serveren din med andre brukere, kan du la dem be om nytt innhold ved hjelp av et brukervennlig grensesnitt. Administrer alle forespørslene dine om filmer og TV-serier enkelt, legg igjen notater til brukeren og få varsel når en bruker ber om noe. La brukerne dine legge ut problemer mot forespørslene sine, slik at du vet at det er et problem med lyden osv. Du kan til og med automatisk sende dem ukentlige nyhetsbrev med nytt innhold som er lagt til Plex-serveren din.
    nl_NL: Hiermee kunt u uw eigen Plex-aanvraag- en gebruikersbeheersysteem hosten. Als u uw Plex-server deelt met andere gebruikers, kunt u hen via een gebruiksvriendelijke interface nieuwe content laten aanvragen. Beheer al uw aanvragen voor films en tv-series eenvoudig, voeg notities toe voor de gebruiker en ontvang meldingen wanneer een gebruiker iets aanvraagt. Laat uw gebruikers problemen melden bij hun aanvragen, zodat u weet of er bijvoorbeeld een probleem is met het geluid. U kunt hen zelfs automatisch wekelijkse nieuwsbrieven sturen met nieuwe content die aan uw Plex-server is toegevoegd.
    pl_PL: Umożliwia hostowanie własnego systemu Plex Request i zarządzania użytkownikami. Jeśli udostępniasz serwer Plex innym użytkownikom, pozwól im zgłaszać prośby o nowe treści za pomocą łatwego w obsłudze interfejsu. Zarządzaj z łatwością wszystkimi prośbami o filmy i programy telewizyjne, zostawiaj notatki dla użytkowników i otrzymuj powiadomienia, gdy użytkownik o coś poprosi. Pozwól użytkownikom zgłaszać problemy związane z ich prośbami, aby wiedzieć, czy wystąpił problem z dźwiękiem itp. Możesz nawet automatycznie wysyłać im cotygodniowe newslettery z informacjami o nowych treściach dodanych do serwera Plex.
    pt_BR: Permite hospedar seu próprio sistema de gerenciamento de solicitações e usuários do Plex. Se você compartilha seu servidor Plex com outros usuários, permita que eles solicitem novos conteúdos usando uma interface fácil de usar. Gerencie todas as suas solicitações de filmes e séries com facilidade, deixe recados para os usuários e receba notificações quando um usuário solicitar algo. Permita que seus usuários relatem problemas com suas solicitações para que você saiba se há algum problema com o áudio, por exemplo. Você pode até enviar automaticamente newsletters semanais com os novos conteúdos adicionados ao seu servidor Plex.
    ro_RO: Îți permite să găzduiești propriul sistem Plex Request și de gestionare a utilizatorilor. Dacă partajezi serverul Plex cu alți utilizatori, permite-le să solicite conținut nou folosind o interfață ușor de gestionat. Gestionează cu ușurință toate solicitările pentru filme și emisiuni TV, lasă note pentru utilizator și primește notificări atunci când un utilizator solicită ceva. Permite utilizatorilor tăi să posteze probleme legate de solicitările lor, astfel încât să știi că există o problemă cu sunetul etc. Le poți chiar trimite automat newslettere săptămânale cu conținut nou adăugat pe serverul tău Plex.
    ru_RU: Позволяет разместить собственную систему запросов и управления пользователями Plex. Если вы делите свой сервер Plex с другими пользователями, позвольте им запрашивать новый контент, используя простой в управлении интерфейс. Легко управляйте всеми запросами на фильмы и сериалы, оставляйте заметки для пользователей и получайте уведомления, когда пользователь что-то запрашивает. Позвольте пользователям сообщать о проблемах со своими запросами, чтобы вы знали о проблемах со звуком и т.д. Вы даже можете автоматически отправлять им еженедельные информационные бюллетени о новом контенте, добавленном на ваш сервер Plex.
    sk_SK: Umožňuje vám hostiť vlastný systém na správu požiadaviek Plex a používateľov. Ak zdieľate svoj server Plex s inými používateľmi, umožnite im vyžiadať si nový obsah pomocou ľahko spravovateľného rozhrania. Spravujte všetky svoje požiadavky na filmy a televíziu s ľahkosťou, zanechajte používateľom poznámky a dostávajte upozornenia, keď používateľ niečo požiada. Umožnite svojim používateľom uverejňovať problémy s ich požiadavkami, aby ste vedeli, že existuje problém so zvukom atď. Dokonca im automaticky posielajte týždenné newslettery s novým obsahom, ktorý bol pridaný na váš server Plex.
    sv_SE: Låter dig vara värd för ditt eget Plex-förfrågnings- och användarhanteringssystem. Om du delar din Plex-server med andra användare kan du låta dem begära nytt innehåll med hjälp av ett lätthanterligt gränssnitt. Hantera alla dina förfrågningar om film och TV enkelt, lämna anteckningar till användaren och få meddelanden när en användare begär något. Låt dina användare posta problem mot sina förfrågningar så att du vet att det finns problem med ljudet etc. Du kan till och med automatiskt skicka dem veckovisa nyhetsbrev med nytt innehåll som har lagts till på din Plex-server.
    tr_TR: Kendi Plex istek ve kullanıcı yönetim sisteminizi barındırmanıza olanak tanır. Plex sunucunuzu diğer kullanıcılarla paylaşıyorsanız, kullanımı kolay bir arayüz kullanarak yeni içerik talep etmelerine izin verin. Film ve dizi isteklerinizin tümünü kolayca yönetin, kullanıcı için notlar bırakın ve bir kullanıcı bir şey talep ettiğinde bildirim alın. Kullanıcılarınızın istekleriyle ilgili sorunları bildirmelerine izin verin, böylece sesle ilgili bir sorun olduğunu bilirsiniz. Hatta Plex sunucunuza eklenen yeni içeriklerle ilgili haftalık bültenleri otomatik olarak gönderebilirsiniz.
    zh_CN: 为 Plex 用户管理媒体请求和内容通知。
    zh_TW: 為 Plex 使用者管理媒體請求和內容通知。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ombi.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ombi.png
  title:
    en_US: Ombi (LinuxServer.io)
    ca_ES: Ombi (LinuxServer.io)
    cs_CZ: Ombi (LinuxServer.io)
    da_DK: Ombi (LinuxServer.io)
    de_DE: Ombi (LinuxServer.io)
    el_GR: Ombi (LinuxServer.io)
    en_GB: Ombi (LinuxServer.io)
    es_ES: Ombi (LinuxServer.io)
    fr_FR: Ombi (LinuxServer.io)
    ga_IE: Ombi (LinuxServer.io)
    hr_HR: Ombi (LinuxServer.io)
    hu_HU: Ombi (LinuxServer.io)
    it_IT: Ombi (LinuxServer.io)
    ja_JP: Ombi (LinuxServer.io)
    ko_KR: Ombi (LinuxServer.io)
    ml_IN: Ombi (LinuxServer.io)
    nb_NO: Ombi (LinuxServer.io)
    nl_NL: Ombi (LinuxServer.io)
    pl_PL: Ombi (LinuxServer.io)
    pt_BR: Ombi (LinuxServer.io)
    ro_RO: Ombi (LinuxServer.io)
    ru_RU: Ombi (LinuxServer.io)
    sk_SK: Ombi (LinuxServer.io)
    sv_SE: Ombi (LinuxServer.io)
    tr_TR: Ombi (LinuxServer.io)
    zh_CN: Ombi（LinuxServer.io）
    zh_TW: Ombi（LinuxServer.io）
  category: Media
  id: wisdomsky.linuxserver.linuxserverombi
  port_map: '3579'
  version: 4.53.10
