name: linuxserver-ombi
services:
  app:
    image: linuxserver/ombi:4.53.10
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: BASE_URL
          description:
            en_US: Subfolder can optionally be defined as an env variable for reverse proxies. Keep in mind that once this value is defined, the gui setting for base url no longer works. To use the gui setting, remove this env variable. [OPTIONAL]
    ports:
      - target: 3579
        published: 3579
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ombi/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Ombi allows you to host your own Plex Request and user management system. If you are sharing your Plex server with other users, allow them to request new content using an easy to manage interface! Manage all your requests for Movies and TV with ease, leave notes for the user and get notification when a user requests something. Allow your users to post issues against their requests so you know there is a problem with the audio etc. Even automatically send them weekly newsletters of new content that has been added to your Plex server!
    zh_CN: Ombi 让你自行托管 Plex 内容请求和用户管理系统。如果你与他人共享 Plex 服务器，他们可以通过易于管理的界面请求新内容。你可轻松管理电影和电视剧请求、为用户留言，并在收到请求时获得通知。用户还可报告请求内容的问题，例如音频异常。系统甚至可以每周自动发送新增 Plex 内容的电子简报。
  tagline:
    en_US: Allows you to host your own Plex Request and user management system. If you are sharing your Plex server with other users, allow them to request new content using an easy to manage interface. Manage all your requests for Movies and TV with ease, leave notes for the user and get notification when a user requests something. Allow your users to post issues against their requests so you know there is a problem with the audio etc. Even automatically send them weekly newsletters of new content that has been added to your Plex server.
    zh_CN: 为 Plex 用户管理媒体请求和内容通知。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ombi.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ombi.png
  title:
    en_US: Ombi (LinuxServer.io)
    zh_CN: Ombi（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverombi
  port_map: '3579'
  version: 4.53.10
