name: linuxserver-grocy
services:
  app:
    image: linuxserver/grocy:4.7.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 9283
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/grocy/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: 'Grocy is an ERP system for your kitchen! Cut down on food waste, and manage your chores with this brilliant utility. Keep track of your purchases, how much food you are wasting, what chores need doing and what batteries need charging with this proudly Open Source tool For more information on grocy visit their website and check it out: https://grocy.info'
    zh_CN: Grocy 是面向厨房的 ERP 系统，可帮助减少食物浪费并管理家务。使用这个开源工具，你可以追踪采购、食物浪费、待办家务以及需要充电的电池。更多信息请访问：https://grocy.info
  tagline:
    en_US: 'An ERP system for your kitchen. Cut down on food waste, and manage your chores with this brilliant utility. Keep track of your purchases, how much food you are wasting, what chores need doing and what batteries need charging with this proudly Open Source tool For more information on grocy visit their website and check it out: https://grocy. Info'
    zh_CN: 管理厨房库存、采购、家务和耗材。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/grocy-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/grocy-logo.png
  title:
    en_US: Grocy (LinuxServer.io)
    zh_CN: Grocy（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxservergrocy
  port_map: '80'
  version: 4.7.1
