name: linuxserver-phpmyadmin
services:
  app:
    image: linuxserver/phpmyadmin:5.2.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PMA_ARBITRARY: ''
      PMA_ABSOLUTE_URI: ''
      PMA_HOST: 172.17.0.1
      PMA_USER: casaos
      PMA_PASSWORD: casaos
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: PMA_ARBITRARY
          description:
            en_US: Set to 1 to allow you to connect to any server. Setting to 0 will only allow you to connect to specified hosts (See Application Setup) [OPTIONAL]
        - container: PMA_ABSOLUTE_URI
          description:
            en_US: Set the URL you will use to access the web frontend [OPTIONAL]
    ports:
      - target: 8081
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/phpmyadmin/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Phpmyadmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web. phpMyAdmin supports a wide range of operations on MySQL and MariaDB.
    zh_CN: phpMyAdmin 是用 PHP 编写的自由软件工具，旨在通过网页管理 MySQL。它支持 MySQL 和 MariaDB 的多种操作。
  tagline:
    en_US: A free software tool written in PHP, intended to handle the administration of MySQL over the Web. PhpMyAdmin supports a wide range of operations on MySQL and MariaDB.
    zh_CN: 通过网页管理 MySQL 和 MariaDB。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/phpmyadmin-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/phpmyadmin-logo.png
  title:
    en_US: Phpmyadmin (LinuxServer.io)
    zh_CN: Phpmyadmin（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverphpmyadmin
  port_map: '8081'
  version: 5.2.3
