name: linuxserver-hishtory-server
services:
  app:
    image: linuxserver/hishtory-server:0.335.20260911@sha256:8d152fdc745e4a27b410ab960ee6f186ed7c95c9b70057ee926c6c5a1748badb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HISHTORY_POSTGRES_DB: ''
      HISHTORY_SQLITE_DB: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/hishtory-server/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverhishtoryserver/assets/icon.png
  title:
    en_US: Hishtory server (LinuxServer.io)
    ca_ES: Hishtory server (LinuxServer.io)
    cs_CZ: Hishtory server (LinuxServer.io)
    da_DK: Hishtory server (LinuxServer.io)
    de_DE: Hishtory server (LinuxServer.io)
    el_GR: Hishtory server (LinuxServer.io)
    en_GB: Hishtory server (LinuxServer.io)
    es_ES: Hishtory server (LinuxServer.io)
    fr_FR: Hishtory server (LinuxServer.io)
    ga_IE: Hishtory server (LinuxServer.io)
    hr_HR: Hishtory server (LinuxServer.io)
    hu_HU: Hishtory server (LinuxServer.io)
    it_IT: Hishtory server (LinuxServer.io)
    ja_JP: Hishtory server (LinuxServer.io)
    ko_KR: Hishtory server (LinuxServer.io)
    ml_IN: Hishtory server (LinuxServer.io)
    nb_NO: Hishtory server (LinuxServer.io)
    nl_NL: Hishtory server (LinuxServer.io)
    pl_PL: Hishtory server (LinuxServer.io)
    pt_BR: Hishtory server (LinuxServer.io)
    ro_RO: Hishtory server (LinuxServer.io)
    ru_RU: Hishtory server (LinuxServer.io)
    sk_SK: Hishtory server (LinuxServer.io)
    sv_SE: Hishtory server (LinuxServer.io)
    tr_TR: Hishtory server (LinuxServer.io)
    zh_CN: Hishtory server（LinuxServer.io）
    zh_TW: Hishtory server（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverhishtoryserver
  port_map: '8080'
  version: 0.335.20260911
