name: linuxserver-hishtory-server
services:
  app:
    image: linuxserver/hishtory-server:0.335.20260911@sha256:8d152fdc745e4a27b410ab960ee6f186ed7c95c9b70057ee926c6c5a1748badb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HISHTORY_POSTGRES_DB: ''
      HISHTORY_SQLITE_DB: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/hishtory-server/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverhishtoryserver/assets/icon.png
  title:
    en_US: Hishtory server (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverhishtoryserver
  port_map: '8080'
  version: 0.335.20260911
