name: linuxserver-vscodium
services:
  app:
    image: linuxserver/vscodium:1.135.06055
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vscodium/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservervscodium/assets/icon.png
  title:
    en_US: Vscodium (LinuxServer.io)
    ca_ES: Vscodium (LinuxServer.io)
    cs_CZ: Vscodium (LinuxServer.io)
    da_DK: Vscodium (LinuxServer.io)
    de_DE: Vscodium (LinuxServer.io)
    el_GR: Vscodium (LinuxServer.io)
    en_GB: Vscodium (LinuxServer.io)
    es_ES: Vscodium (LinuxServer.io)
    fr_FR: Vscodium (LinuxServer.io)
    ga_IE: Vscodium (LinuxServer.io)
    hr_HR: Vscodium (LinuxServer.io)
    hu_HU: Vscodium (LinuxServer.io)
    it_IT: Vscodium (LinuxServer.io)
    ja_JP: Vscodium (LinuxServer.io)
    ko_KR: Vscodium (LinuxServer.io)
    ml_IN: Vscodium (LinuxServer.io)
    nb_NO: Vscodium (LinuxServer.io)
    nl_NL: Vscodium (LinuxServer.io)
    pl_PL: Vscodium (LinuxServer.io)
    pt_BR: Vscodium (LinuxServer.io)
    ro_RO: Vscodium (LinuxServer.io)
    ru_RU: Vscodium (LinuxServer.io)
    sk_SK: Vscodium (LinuxServer.io)
    sv_SE: Vscodium (LinuxServer.io)
    tr_TR: Vscodium (LinuxServer.io)
    zh_CN: Vscodium（LinuxServer.io）
    zh_TW: Vscodium（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservervscodium
  port_map: '3000'
  version: 1.135.06055
