name: linuxserver-piper
services:
  app:
    image: linuxserver/piper:2.5.2@sha256:d312dfe0aee95eb6498376de1c0b583ee9ae421d74f817caf4b1bf63a34b5892
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PIPER_VOICE: ''
      LOCAL_ONLY: ''
      PIPER_LENGTH: ''
      PIPER_NOISE: ''
      PIPER_NOISEW: ''
      PIPER_SPEAKER: ''
      NO_STREAMING: ''
    ports:
      - target: 10200
        published: 10200
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/piper/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverpiper/assets/icon.png
  title:
    en_US: Piper (LinuxServer.io)
    ca_ES: Piper (LinuxServer.io)
    cs_CZ: Piper (LinuxServer.io)
    da_DK: Piper (LinuxServer.io)
    de_DE: Piper (LinuxServer.io)
    el_GR: Piper (LinuxServer.io)
    en_GB: Piper (LinuxServer.io)
    es_ES: Piper (LinuxServer.io)
    fr_FR: Piper (LinuxServer.io)
    ga_IE: Piper (LinuxServer.io)
    hr_HR: Piper (LinuxServer.io)
    hu_HU: Piper (LinuxServer.io)
    it_IT: Piper (LinuxServer.io)
    ja_JP: Piper (LinuxServer.io)
    ko_KR: Piper (LinuxServer.io)
    ml_IN: Piper (LinuxServer.io)
    nb_NO: Piper (LinuxServer.io)
    nl_NL: Piper (LinuxServer.io)
    pl_PL: Piper (LinuxServer.io)
    pt_BR: Piper (LinuxServer.io)
    ro_RO: Piper (LinuxServer.io)
    ru_RU: Piper (LinuxServer.io)
    sk_SK: Piper (LinuxServer.io)
    sv_SE: Piper (LinuxServer.io)
    tr_TR: Piper (LinuxServer.io)
    zh_CN: Piper（LinuxServer.io）
    zh_TW: Piper（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverpiper
  port_map: '10200'
  version: 2.5.2
