name: linuxserver-vivaldi
services:
  app:
    image: linuxserver/vivaldi:8.2.4133@sha256:8884e7aa655404b113b15214329d6e828da93d54d5be1cb72800b7f60c0d37a8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VIVALDI_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vivaldi/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservervivaldi/assets/icon.png
  title:
    en_US: Vivaldi (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxservervivaldi
  port_map: '3000'
  version: 8.2.4133
