name: linuxserver-vivaldi
services:
  app:
    image: linuxserver/vivaldi:8.2.4133@sha256:f31e7a92696be8f6e93080272714067a4e06b480812261c0debcf91c1cb5a271
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VIVALDI_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vivaldi/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservervivaldi/assets/icon.png
  title:
    en_US: Vivaldi (LinuxServer.io)
    ca_ES: Vivaldi (LinuxServer.io)
    cs_CZ: Vivaldi (LinuxServer.io)
    da_DK: Vivaldi (LinuxServer.io)
    de_DE: Vivaldi (LinuxServer.io)
    el_GR: Vivaldi (LinuxServer.io)
    en_GB: Vivaldi (LinuxServer.io)
    es_ES: Vivaldi (LinuxServer.io)
    fr_FR: Vivaldi (LinuxServer.io)
    ga_IE: Vivaldi (LinuxServer.io)
    hr_HR: Vivaldi (LinuxServer.io)
    hu_HU: Vivaldi (LinuxServer.io)
    it_IT: Vivaldi (LinuxServer.io)
    ja_JP: Vivaldi (LinuxServer.io)
    ko_KR: Vivaldi (LinuxServer.io)
    ml_IN: Vivaldi (LinuxServer.io)
    nb_NO: Vivaldi (LinuxServer.io)
    nl_NL: Vivaldi (LinuxServer.io)
    pl_PL: Vivaldi (LinuxServer.io)
    pt_BR: Vivaldi (LinuxServer.io)
    ro_RO: Vivaldi (LinuxServer.io)
    ru_RU: Vivaldi (LinuxServer.io)
    sk_SK: Vivaldi (LinuxServer.io)
    sv_SE: Vivaldi (LinuxServer.io)
    tr_TR: Vivaldi (LinuxServer.io)
    zh_CN: Vivaldi（LinuxServer.io）
    zh_TW: Vivaldi（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservervivaldi
  port_map: '3000'
  version: 8.2.4133
