name: linuxserver-pidgin
services:
  app:
    image: linuxserver/pidgin:2.14.14
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pidgin/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverpidgin/assets/icon.png
  title:
    en_US: Pidgin (LinuxServer.io)
    ca_ES: Pidgin (LinuxServer.io)
    cs_CZ: Pidgin (LinuxServer.io)
    da_DK: Pidgin (LinuxServer.io)
    de_DE: Pidgin (LinuxServer.io)
    el_GR: Pidgin (LinuxServer.io)
    en_GB: Pidgin (LinuxServer.io)
    es_ES: Pidgin (LinuxServer.io)
    fr_FR: Pidgin (LinuxServer.io)
    ga_IE: Pidgin (LinuxServer.io)
    hr_HR: Pidgin (LinuxServer.io)
    hu_HU: Pidgin (LinuxServer.io)
    it_IT: Pidgin (LinuxServer.io)
    ja_JP: Pidgin (LinuxServer.io)
    ko_KR: Pidgin (LinuxServer.io)
    ml_IN: Pidgin (LinuxServer.io)
    nb_NO: Pidgin (LinuxServer.io)
    nl_NL: Pidgin (LinuxServer.io)
    pl_PL: Pidgin (LinuxServer.io)
    pt_BR: Pidgin (LinuxServer.io)
    ro_RO: Pidgin (LinuxServer.io)
    ru_RU: Pidgin (LinuxServer.io)
    sk_SK: Pidgin (LinuxServer.io)
    sv_SE: Pidgin (LinuxServer.io)
    tr_TR: Pidgin (LinuxServer.io)
    zh_CN: Pidgin（LinuxServer.io）
    zh_TW: Pidgin（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverpidgin
  port_map: '3000'
  version: 2.14.14
