name: linuxserver-limnoria
services:
  app:
    image: linuxserver/limnoria:2026.5.8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/limnoria/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Limnoria A robust, full-featured, and user/programmer-friendly Python IRC bot, with many existing plugins. Successor of the well-known Supybot.
    zh_CN: Limnoria 是一个稳健、功能完整且对用户和开发者友好的 Python IRC 机器人，已有大量插件。它是知名项目 Supybot 的继任者。
  tagline:
    en_US: A robust, full-featured, and user/programmer-friendly Python IRC bot, with many existing plugins. Successor of the well-known Supybot.
    zh_CN: 功能丰富、支持插件的 Python IRC 机器人。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/limnoria-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/limnoria-icon.png
  title:
    en_US: Limnoria (LinuxServer.io)
    zh_CN: Limnoria（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverlimnoria
  port_map: '8080'
  version: 2026.5.8
