name: linuxserver-resilio-sync
services:
  app:
    image: linuxserver/resilio-sync:3.1.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 55555
        published: 55555
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/resilio-sync/config
        target: /config
      - type: bind
        source: /DATA/AppData/resilio-sync/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/resilio-sync/sync
        target: /sync
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Resilio-sync (formerly BitTorrent Sync) uses the BitTorrent protocol to sync files and folders between all of your devices. There are both free and paid versions, this container supports both. There is an official sync image but we created this one as it supports user mapping to simplify permissions for volumes.
    ca_ES: Resilio-sync (anteriorment BitTorrent Sync) utilitza el protocol BitTorrent per sincronitzar fitxers i carpetes entre tots els dispositius. Hi ha versions gratuïtes i de pagament, i aquest contenidor admet totes dues. Hi ha una imatge de sincronització oficial, però hem creat aquesta perquè admet el mapatge d'usuaris per simplificar els permisos dels volums.
    cs_CZ: Resilio-sync (dříve BitTorrent Sync) používá protokol BitTorrent k synchronizaci souborů a složek mezi všemi vašimi zařízeními. Existují bezplatné i placené verze, tento kontejner podporuje obě. Existuje oficiální synchronizační obraz, ale my jsme vytvořili tento, protože podporuje mapování uživatelů pro zjednodušení oprávnění pro svazky.
    da_DK: Resilio-sync (tidligere BitTorrent Sync) bruger BitTorrent-protokollen til at synkronisere filer og mapper mellem alle dine enheder. Der findes både gratis og betalte versioner, og denne container understøtter begge dele. Der findes et officielt synkroniseringsbillede, men vi har oprettet dette, da det understøtter brugertilknytning for at forenkle tilladelser for volumener.
    de_DE: Resilio-sync (ehemals BitTorrent Sync) synchronisiert Dateien und Ordner mithilfe des BitTorrent-Protokolls zwischen all Ihren Geräten. Es gibt sowohl eine kostenlose als auch eine kostenpflichtige Version; dieser Container unterstützt beide. Es existiert zwar ein offizielles Synchronisierungs-Image, wir haben jedoch dieses hier erstellt, da es die Benutzerzuordnung unterstützt und somit die Berechtigungen für Volumes vereinfacht.
    el_GR: Το Resilio-sync (πρώην BitTorrent Sync) χρησιμοποιεί το πρωτόκολλο BitTorrent για τον συγχρονισμό αρχείων και φακέλων μεταξύ όλων των συσκευών σας. Υπάρχουν δωρεάν και επί πληρωμή εκδόσεις, αυτό το κοντέινερ υποστηρίζει και τις δύο. Υπάρχει μια επίσημη εικόνα συγχρονισμού, αλλά δημιουργήσαμε αυτήν, καθώς υποστηρίζει την αντιστοίχιση χρηστών για την απλοποίηση των δικαιωμάτων για τους τόμους.
    en_GB: Resilio-sync (formerly Bittorrent Sync) uses the Bittorrent protocol to sync files and folders between all of your devices. There are both free and paid versions, this container supports both. There is an official sync image but we created this one as it supports user mapping to simplify permissions for volumes.
    es_ES: Resilio-sync (antes BitTorrent Sync) utiliza el protocolo BitTorrent para sincronizar archivos y carpetas entre todos tus dispositivos. Existen versiones gratuitas y de pago, y este contenedor es compatible con ambas. Hay una imagen de sincronización oficial, pero creamos esta porque permite la asignación de usuarios para simplificar los permisos de los volúmenes.
    fr_FR: Resilio-sync (anciennement BitTorrent Sync) utilise le protocole BitTorrent pour synchroniser les fichiers et dossiers entre tous vos appareils. Il existe une version gratuite et une version payante, toutes deux compatibles avec ce conteneur. Bien qu'une image de synchronisation officielle soit disponible, nous avons créé celle-ci car elle prend en charge le mappage des utilisateurs, simplifiant ainsi la gestion des permissions des volumes.
    ga_IE: Úsáideann Resilio-sync (BitTorrent Sync roimhe seo) an prótacal BitTorrent chun comhaid agus fillteáin a shioncronú idir do ghléasanna go léir. Tá leaganacha saor in aisce agus íoctha ann, agus tacaíonn an coimeádán seo leis an dá cheann. Tá íomhá oifigiúil sioncrónaithe ann ach chruthaíomar an ceann seo mar go dtacaíonn sé le mapáil úsáideoirí chun ceadanna do na himleabhair a shimpliú.
    hr_HR: Resilio-sync (prije BitTorrent Sync) koristi BitTorrent protokol za sinkronizaciju datoteka i mapa između svih vaših uređaja. Postoje besplatne i plaćene verzije, ovaj kontejner podržava obje. Postoji službena slika za sinkronizaciju, ali mi smo stvorili ovu jer podržava mapiranje korisnika radi pojednostavljenja dozvola za volumene.
    hu_HU: A Resilio-sync (korábban BitTorrent Sync) a BitTorrent protokollt használja fájlok és mappák szinkronizálására az összes eszközöd között. Létezik ingyenes és fizetős verzió is, ez a konténer mindkettőt támogatja. Létezik egy hivatalos szinkronizálási kép, de ezt azért hoztuk létre, mert támogatja a felhasználó-hozzárendelést a kötetek engedélyeinek egyszerűsítése érdekében.
    it_IT: Resilio-sync (precedentemente BitTorrent Sync) utilizza il protocollo BitTorrent per sincronizzare file e cartelle tra tutti i tuoi dispositivi. Esistono versioni gratuite e a pagamento, e questo container le supporta entrambe. Esiste un'immagine di sincronizzazione ufficiale, ma ne abbiamo creata una nostra perché supporta la mappatura degli utenti per semplificare la gestione dei permessi dei volumi.
    ja_JP: Resilio-sync（旧称BitTorrent Sync）は、BitTorrentプロトコルを使用して、すべてのデバイス間でファイルとフォルダを同期します。無料版と有料版があり、このコンテナは両方をサポートしています。公式の同期イメージもありますが、ボリュームのアクセス権限を簡素化するためにユーザーマッピングをサポートするこのイメージを作成しました。
    ko_KR: 'Resilio-sync(이전 명칭: BitTorrent Sync)는 BitTorrent 프로토콜을 사용하여 모든 장치 간에 파일과 폴더를 동기화합니다. 무료 버전과 유료 버전이 있으며, 이 컨테이너는 두 버전을 모두 지원합니다. 공식 동기화 이미지가 있지만, 볼륨 권한 설정을 간소화하기 위해 사용자 매핑을 지원하는 이 이미지를 저희가 직접 제작했습니다.'
    ml_IN: നിങ്ങളുടെ എല്ലാ ഉപകരണങ്ങൾക്കിടയിലും ഫയലുകളും ഫോൾഡറുകളും സമന്വയിപ്പിക്കുന്നതിന് റെസിലിയോ-സിങ്ക് (മുമ്പ് ബിറ്റ്‌ടോറന്റ് സിങ്ക്) ബിറ്റ്‌ടോറന്റ് പ്രോട്ടോക്കോൾ ഉപയോഗിക്കുന്നു. സൗജന്യവും പണമടച്ചുള്ളതുമായ പതിപ്പുകൾ ഉണ്ട്, ഈ കണ്ടെയ്‌നർ രണ്ടും പിന്തുണയ്ക്കുന്നു. ഒരു ഔദ്യോഗിക സിങ്ക് ഇമേജ് ഉണ്ട്, പക്ഷേ വോള്യങ്ങൾക്കുള്ള അനുമതികൾ ലളിതമാക്കുന്നതിന് ഉപയോക്തൃ മാപ്പിംഗിനെ പിന്തുണയ്ക്കുന്നതിനാലാണ് ഞങ്ങൾ ഇത് സൃഷ്ടിച്ചത്.
    nb_NO: Resilio-sync (tidligere BitTorrent Sync) bruker BitTorrent-protokollen til å synkronisere filer og mapper mellom alle enhetene dine. Det finnes både gratis og betalte versjoner, og denne containeren støtter begge. Det finnes et offisielt synkroniseringsbilde, men vi opprettet dette fordi det støtter brukertilordning for å forenkle tillatelser for volumer.
    nl_NL: Resilio-sync (voorheen BitTorrent Sync) gebruikt het BitTorrent-protocol om bestanden en mappen tussen al uw apparaten te synchroniseren. Er zijn zowel gratis als betaalde versies, en deze container ondersteunt beide. Er is een officiële synchronisatie-image, maar we hebben deze gemaakt omdat deze gebruikersmapping ondersteunt om de machtigingen voor volumes te vereenvoudigen.
    pl_PL: Resilio-sync (dawniej BitTorrent Sync) wykorzystuje protokół BitTorrent do synchronizacji plików i folderów między wszystkimi urządzeniami. Dostępna jest wersja darmowa i płatna, a ten kontener obsługuje obie. Istnieje oficjalny obraz synchronizacji, ale stworzyliśmy ten, ponieważ obsługuje mapowanie użytkowników, aby uprościć uprawnienia do woluminów.
    pt_BR: O Resilio-sync (anteriormente BitTorrent Sync) usa o protocolo BitTorrent para sincronizar arquivos e pastas entre todos os seus dispositivos. Existem versões gratuitas e pagas, e este contêiner é compatível com ambas. Há uma imagem de sincronização oficial, mas criamos esta versão porque ela oferece suporte ao mapeamento de usuários, simplificando as permissões para volumes.
    ro_RO: Resilio-sync (fostul BitTorrent Sync) folosește protocolul BitTorrent pentru a sincroniza fișiere și foldere între toate dispozitivele tale. Există atât versiuni gratuite, cât și versiuni plătite, iar acest container le acceptă pe ambele. Există o imagine oficială de sincronizare, dar am creat-o pe aceasta deoarece acceptă maparea utilizatorilor pentru a simplifica permisiunile pentru volume.
    ru_RU: Resilio-sync (ранее BitTorrent Sync) использует протокол BitTorrent для синхронизации файлов и папок между всеми вашими устройствами. Существуют как бесплатная, так и платная версии, и этот контейнер поддерживает обе. Существует официальный образ для синхронизации, но мы создали этот, поскольку он поддерживает сопоставление пользователей для упрощения прав доступа к томам.
    sk_SK: Resilio-sync (predtým BitTorrent Sync) používa protokol BitTorrent na synchronizáciu súborov a priečinkov medzi všetkými vašimi zariadeniami. Existujú bezplatné aj platené verzie, tento kontajner podporuje obe. Existuje oficiálny synchronizačný obraz, ale tento sme vytvorili, pretože podporuje mapovanie používateľov pre zjednodušenie oprávnení pre zväzky.
    sv_SE: Resilio-sync (tidigare BitTorrent Sync) använder BitTorrent-protokollet för att synkronisera filer och mappar mellan alla dina enheter. Det finns både gratis- och betalversioner, och den här containern stöder båda. Det finns en officiell synkroniseringsavbildning, men vi skapade den här eftersom den stöder användarmappning för att förenkla behörigheter för volymer.
    tr_TR: Resilio-sync (eski adıyla BitTorrent Sync), tüm cihazlarınız arasında dosya ve klasörleri senkronize etmek için BitTorrent protokolünü kullanır. Hem ücretsiz hem de ücretli sürümleri mevcuttur ve bu konteyner her ikisini de destekler. Resmi bir senkronizasyon imajı olsa da, bu imajı oluşturduk çünkü kullanıcı eşlemesini destekleyerek birimler için izinleri basitleştiriyor.
    zh_CN: Resilio Sync（原名 BitTorrent Sync）使用 BitTorrent 协议在你的所有设备之间同步文件和文件夹。它有免费版和付费版，此容器均支持。虽然已有官方同步镜像，此镜像提供用户映射，以简化数据卷权限管理。
    zh_TW: Resilio Sync（原名 BitTorrent Sync）使用 BitTorrent 協議在你的所有裝置之間同步檔案和資料夾。它有免費版和付費版，此容器均支援。雖然已有官方同步映象，此映象提供使用者對映，以簡化資料卷許可權管理。
  tagline:
    en_US: (formerly BitTorrent Sync) uses the BitTorrent protocol to sync files and folders between all of your devices. There are both free and paid versions, this container supports both. There is an official sync image but we created this one as it supports user mapping to simplify permissions for volumes.
    ca_ES: (anteriorment BitTorrent Sync) utilitza el protocol BitTorrent per sincronitzar fitxers i carpetes entre tots els vostres dispositius. Hi ha versions gratuïtes i de pagament, aquest contenidor admet totes dues. Hi ha una imatge de sincronització oficial, però hem creat aquesta perquè admet el mapatge d'usuaris per simplificar els permisos dels volums.
    cs_CZ: (dříve BitTorrent Sync) používá protokol BitTorrent k synchronizaci souborů a složek mezi všemi vašimi zařízeními. Existují bezplatné i placené verze, tento kontejner podporuje obě. Existuje oficiální synchronizační obraz, ale my jsme vytvořili tento, protože podporuje mapování uživatelů pro zjednodušení oprávnění pro svazky.
    da_DK: (tidligere BitTorrent Sync) bruger BitTorrent-protokollen til at synkronisere filer og mapper mellem alle dine enheder. Der findes både gratis og betalte versioner, og denne container understøtter begge dele. Der findes et officielt synkroniseringsbillede, men vi har oprettet dette, da det understøtter brugertilknytning for at forenkle tilladelser for enheder.
    de_DE: (ehemals BitTorrent Sync) nutzt das BitTorrent-Protokoll, um Dateien und Ordner zwischen all Ihren Geräten zu synchronisieren. Es gibt sowohl eine kostenlose als auch eine kostenpflichtige Version; dieser Container unterstützt beide. Es existiert zwar ein offizielles Synchronisierungs-Image, wir haben jedoch dieses hier erstellt, da es die Benutzerzuordnung unterstützt und somit die Berechtigungen für Volumes vereinfacht.
    el_GR: (πρώην BitTorrent Sync) χρησιμοποιεί το πρωτόκολλο BitTorrent για τον συγχρονισμό αρχείων και φακέλων μεταξύ όλων των συσκευών σας. Υπάρχουν δωρεάν και επί πληρωμή εκδόσεις, αυτό το κοντέινερ υποστηρίζει και τις δύο. Υπάρχει μια επίσημη εικόνα συγχρονισμού, αλλά δημιουργήσαμε αυτήν, καθώς υποστηρίζει την αντιστοίχιση χρηστών για την απλοποίηση των δικαιωμάτων για τους τόμους.
    en_GB: (formerly Bittorrent Sync) uses the Bittorrent protocol to sync files and folders between all of your devices. There are both free and paid versions, this container supports both. There is an official sync image but we created this one as it supports user mapping to simplify permissions for volumes.
    es_ES: (anteriormente BitTorrent Sync) utiliza el protocolo BitTorrent para sincronizar archivos y carpetas entre todos tus dispositivos. Existen versiones gratuitas y de pago, y este contenedor admite ambas. Hay una imagen de sincronización oficial, pero creamos esta porque admite la asignación de usuarios para simplificar los permisos de los volúmenes.
    fr_FR: (Anciennement BitTorrent Sync) utilise le protocole BitTorrent pour synchroniser les fichiers et dossiers entre tous vos appareils. Il existe une version gratuite et une version payante, toutes deux compatibles avec ce conteneur. Bien qu'une image de synchronisation officielle soit disponible, nous avons créé celle-ci car elle prend en charge le mappage des utilisateurs, simplifiant ainsi la gestion des permissions des volumes.
    ga_IE: (BitTorrent Sync roimhe seo) úsáideann sé an prótacal BitTorrent chun comhaid agus fillteáin a shioncronú idir do ghléasanna go léir. Tá leaganacha saor in aisce agus íoctha ann, agus tacaíonn an coimeádán seo leis an dá cheann. Tá íomhá sioncrónaithe oifigiúil ann ach chruthaíomar an ceann seo mar go dtacaíonn sé le mapáil úsáideoirí chun ceadanna do na toirteanna a shimpliú.
    hr_HR: (prije BitTorrent Sync) koristi BitTorrent protokol za sinkronizaciju datoteka i mapa između svih vaših uređaja. Postoje i besplatne i plaćene verzije, ovaj kontejner podržava obje. Postoji službena slika za sinkronizaciju, ali mi smo stvorili ovu jer podržava mapiranje korisnika radi pojednostavljenja dozvola za volumene.
    hu_HU: (korábban BitTorrent Sync) a BitTorrent protokollt használja fájlok és mappák szinkronizálására az összes eszközöd között. Létezik ingyenes és fizetős verzió is, ez a konténer mindkettőt támogatja. Létezik egy hivatalos szinkronizálási kép, de ezt azért hoztuk létre, mert támogatja a felhasználó-hozzárendelést a kötetek engedélyeinek egyszerűsítése érdekében.
    it_IT: (precedentemente BitTorrent Sync) utilizza il protocollo BitTorrent per sincronizzare file e cartelle tra tutti i tuoi dispositivi. Esistono versioni gratuite e a pagamento, e questo container le supporta entrambe. Esiste un'immagine di sincronizzazione ufficiale, ma abbiamo creato questa perché supporta la mappatura degli utenti per semplificare le autorizzazioni per i volumi.
    ja_JP: （旧称 BitTorrent Sync）は、BitTorrent プロトコルを使用して、すべてのデバイス間でファイルとフォルダを同期します。無料版と有料版があり、このコンテナは両方をサポートしています。公式の同期イメージもありますが、ボリュームのアクセス許可を簡素化するためにユーザーマッピングをサポートするこのイメージを作成しました。
    ko_KR: '(이전 명칭: BitTorrent Sync)는 BitTorrent 프로토콜을 사용하여 모든 장치 간에 파일과 폴더를 동기화합니다. 무료 버전과 유료 버전이 있으며, 이 컨테이너는 두 버전 모두를 지원합니다. 공식 동기화 이미지가 있지만, 볼륨 권한 설정을 간소화하기 위해 사용자 매핑을 지원하는 이 이미지를 저희가 제작했습니다.'
    ml_IN: (മുമ്പ് ബിറ്റ്‌ടോറന്റ് സമന്വയം) നിങ്ങളുടെ എല്ലാ ഉപകരണങ്ങൾക്കിടയിലും ഫയലുകളും ഫോൾഡറുകളും സമന്വയിപ്പിക്കുന്നതിന് ബിറ്റ്‌ടോറന്റ് പ്രോട്ടോക്കോൾ ഉപയോഗിക്കുന്നു. സൗജന്യവും പണമടച്ചുള്ളതുമായ പതിപ്പുകൾ ഉണ്ട്, ഈ കണ്ടെയ്‌നർ രണ്ടും പിന്തുണയ്ക്കുന്നു. ഒരു ഔദ്യോഗിക സമന്വയ ഇമേജ് ഉണ്ട്, പക്ഷേ വോള്യങ്ങൾക്കുള്ള അനുമതികൾ ലളിതമാക്കുന്നതിന് ഉപയോക്തൃ മാപ്പിംഗിനെ പിന്തുണയ്ക്കുന്നതിനാൽ ഞങ്ങൾ ഇത് സൃഷ്ടിച്ചു.
    nb_NO: (tidligere BitTorrent Sync) bruker BitTorrent-protokollen til å synkronisere filer og mapper mellom alle enhetene dine. Det finnes både gratis og betalte versjoner, og denne containeren støtter begge. Det finnes et offisielt synkroniseringsbilde, men vi opprettet dette fordi det støtter brukertilordning for å forenkle tillatelser for volumer.
    nl_NL: (voorheen BitTorrent Sync) gebruikt het BitTorrent-protocol om bestanden en mappen tussen al uw apparaten te synchroniseren. Er zijn zowel gratis als betaalde versies, en deze container ondersteunt beide. Er is een officiële synchronisatie-image, maar we hebben deze gemaakt omdat deze gebruikersmapping ondersteunt om de machtigingen voor volumes te vereenvoudigen.
    pl_PL: (dawniej BitTorrent Sync) wykorzystuje protokół BitTorrent do synchronizacji plików i folderów między wszystkimi urządzeniami. Dostępna jest wersja darmowa i płatna, a ten kontener obsługuje obie. Istnieje oficjalny obraz synchronizacji, ale stworzyliśmy ten, ponieważ obsługuje mapowanie użytkowników, aby uprościć uprawnienia do woluminów.
    pt_BR: (Anteriormente BitTorrent Sync) usa o protocolo BitTorrent para sincronizar arquivos e pastas entre todos os seus dispositivos. Existem versões gratuitas e pagas, e este contêiner é compatível com ambas. Existe uma imagem de sincronização oficial, mas criamos esta porque ela oferece suporte ao mapeamento de usuários para simplificar as permissões de volumes.
    ro_RO: (anterior BitTorrent Sync) folosește protocolul BitTorrent pentru a sincroniza fișiere și foldere între toate dispozitivele tale. Există atât versiuni gratuite, cât și versiuni plătite, iar acest container le acceptă pe ambele. Există o imagine oficială de sincronizare, dar am creat-o pe aceasta deoarece acceptă maparea utilizatorilor pentru a simplifica permisiunile pentru volume.
    ru_RU: (ранее BitTorrent Sync) использует протокол BitTorrent для синхронизации файлов и папок между всеми вашими устройствами. Существуют как бесплатная, так и платная версии, и этот контейнер поддерживает обе. Существует официальный образ для синхронизации, но мы создали этот, поскольку он поддерживает сопоставление пользователей для упрощения разрешений для томов.
    sk_SK: (predtým BitTorrent Sync) používa protokol BitTorrent na synchronizáciu súborov a priečinkov medzi všetkými vašimi zariadeniami. Existujú bezplatné aj platené verzie, tento kontajner podporuje obe. Existuje oficiálny synchronizačný obraz, ale tento sme vytvorili, pretože podporuje mapovanie používateľov pre zjednodušenie oprávnení pre zväzky.
    sv_SE: (tidigare BitTorrent Sync) använder BitTorrent-protokollet för att synkronisera filer och mappar mellan alla dina enheter. Det finns både gratis- och betalversioner, och den här containern stöder båda. Det finns en officiell synkroniseringsavbildning, men vi skapade den här eftersom den stöder användarmappning för att förenkla behörigheter för volymer.
    tr_TR: (Eski adıyla BitTorrent Sync), tüm cihazlarınız arasında dosya ve klasörleri senkronize etmek için BitTorrent protokolünü kullanır. Hem ücretsiz hem de ücretli sürümleri mevcuttur ve bu konteyner her ikisini de destekler. Resmi bir senkronizasyon imajı olsa da, bu imajı oluşturduk çünkü kullanıcı eşlemesini destekleyerek birimler için izinleri basitleştiriyor.
    zh_CN: 使用 BitTorrent 协议同步设备间的文件。
    zh_TW: 使用 BitTorrent 協議同步裝置間的檔案。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/resilio-sync-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/resilio-sync-logo.png
  title:
    en_US: Resilio sync (LinuxServer.io)
    ca_ES: Resilio sync (LinuxServer.io)
    cs_CZ: Resilio sync (LinuxServer.io)
    da_DK: Resilio sync (LinuxServer.io)
    de_DE: Resilio sync (LinuxServer.io)
    el_GR: Resilio sync (LinuxServer.io)
    en_GB: Resilio sync (LinuxServer.io)
    es_ES: Resilio sync (LinuxServer.io)
    fr_FR: Resilio sync (LinuxServer.io)
    ga_IE: Resilio sync (LinuxServer.io)
    hr_HR: Resilio sync (LinuxServer.io)
    hu_HU: Resilio sync (LinuxServer.io)
    it_IT: Resilio sync (LinuxServer.io)
    ja_JP: Resilio sync (LinuxServer.io)
    ko_KR: Resilio sync (LinuxServer.io)
    ml_IN: Resilio sync (LinuxServer.io)
    nb_NO: Resilio sync (LinuxServer.io)
    nl_NL: Resilio sync (LinuxServer.io)
    pl_PL: Resilio sync (LinuxServer.io)
    pt_BR: Resilio sync (LinuxServer.io)
    ro_RO: Resilio sync (LinuxServer.io)
    ru_RU: Resilio sync (LinuxServer.io)
    sk_SK: Resilio sync (LinuxServer.io)
    sv_SE: Resilio sync (LinuxServer.io)
    tr_TR: Resilio sync (LinuxServer.io)
    zh_CN: Resilio sync（LinuxServer.io）
    zh_TW: Resilio sync（LinuxServer.io）
  category: Productivity
  id: wisdomsky.linuxserver.linuxserverresiliosync
  version: 3.1.2
