name: linuxserver-freshrss
services:
  app:
    image: linuxserver/freshrss:1.30.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/freshrss/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfreshrss/assets/icon.png
  title:
    en_US: Freshrss (LinuxServer.io)
    ca_ES: Freshrss (LinuxServer.io)
    cs_CZ: Freshrss (LinuxServer.io)
    da_DK: Freshrss (LinuxServer.io)
    de_DE: Freshrss (LinuxServer.io)
    el_GR: Freshrss (LinuxServer.io)
    en_GB: Freshrss (LinuxServer.io)
    es_ES: Freshrss (LinuxServer.io)
    fr_FR: Freshrss (LinuxServer.io)
    ga_IE: Freshrss (LinuxServer.io)
    hr_HR: Freshrss (LinuxServer.io)
    hu_HU: Freshrss (LinuxServer.io)
    it_IT: Freshrss (LinuxServer.io)
    ja_JP: Freshrss (LinuxServer.io)
    ko_KR: Freshrss (LinuxServer.io)
    ml_IN: Freshrss (LinuxServer.io)
    nb_NO: Freshrss (LinuxServer.io)
    nl_NL: Freshrss (LinuxServer.io)
    pl_PL: Freshrss (LinuxServer.io)
    pt_BR: Freshrss (LinuxServer.io)
    ro_RO: Freshrss (LinuxServer.io)
    ru_RU: Freshrss (LinuxServer.io)
    sk_SK: Freshrss (LinuxServer.io)
    sv_SE: Freshrss (LinuxServer.io)
    tr_TR: Freshrss (LinuxServer.io)
    zh_CN: Freshrss（LinuxServer.io）
    zh_TW: Freshrss（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverfreshrss
  port_map: '80'
  version: 1.30.0
