name: linuxserver-freshrss
services:
  app:
    image: linuxserver/freshrss:1.30.0@sha256:bf30661b433e1f1f7143a232efebff1618e7fcf63a5983769cccf08e1b555ae8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/freshrss/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfreshrss/assets/icon.png
  title:
    en_US: Freshrss (LinuxServer.io)
    zh_CN: Freshrss（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverfreshrss
  port_map: '80'
  version: 1.30.0
