name: linuxserver-bazarr
services:
  app:
    image: linuxserver/bazarr:1.6.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 6767
        published: 6767
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bazarr/config
        target: /config
      - type: bind
        source: /DATA/AppData/bazarr/movies
        target: /movies
      - type: bind
        source: /DATA/AppData/bazarr/tv
        target: /tv
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverbazarr/assets/icon.png
  title:
    en_US: Bazarr (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverbazarr
  port_map: '6767'
  version: 1.6.1
