name: linuxserver-bazarr
services:
  app:
    image: linuxserver/bazarr:1.6.1@sha256:d424173fd1de6ecf15f4f8fcc39e6b70fd6610873e157d21e6662122981a7d30
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 6767
        published: 6767
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bazarr/config
        target: /config
      - type: bind
        source: /DATA/AppData/bazarr/movies
        target: /movies
      - type: bind
        source: /DATA/AppData/bazarr/tv
        target: /tv
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverbazarr/assets/icon.png
  title:
    en_US: Bazarr (LinuxServer.io)
    ca_ES: Bazarr (LinuxServer.io)
    cs_CZ: Bazarr (LinuxServer.io)
    da_DK: Bazarr (LinuxServer.io)
    de_DE: Bazarr (LinuxServer.io)
    el_GR: Bazarr (LinuxServer.io)
    en_GB: Bazarr (LinuxServer.io)
    es_ES: Bazarr (LinuxServer.io)
    fr_FR: Bazarr (LinuxServer.io)
    ga_IE: Bazarr (LinuxServer.io)
    hr_HR: Bazarr (LinuxServer.io)
    hu_HU: Bazarr (LinuxServer.io)
    it_IT: Bazarr (LinuxServer.io)
    ja_JP: Bazarr (LinuxServer.io)
    ko_KR: Bazarr (LinuxServer.io)
    ml_IN: Bazarr (LinuxServer.io)
    nb_NO: Bazarr (LinuxServer.io)
    nl_NL: Bazarr (LinuxServer.io)
    pl_PL: Bazarr (LinuxServer.io)
    pt_BR: Bazarr (LinuxServer.io)
    ro_RO: Bazarr (LinuxServer.io)
    ru_RU: Bazarr (LinuxServer.io)
    sk_SK: Bazarr (LinuxServer.io)
    sv_SE: Bazarr (LinuxServer.io)
    tr_TR: Bazarr (LinuxServer.io)
    zh_CN: Bazarr（LinuxServer.io）
    zh_TW: Bazarr（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverbazarr
  port_map: '6767'
  version: 1.6.1
