name: linuxserver-freetube
services:
  app:
    image: linuxserver/freetube:version-190523148
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/freetube/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: FreeTube is a feature-rich and user-friendly YouTube client with a focus on privacy.
    zh_CN: FreeTube 是一款功能丰富、易于使用且注重隐私的 YouTube 客户端。
    ca_ES: FreeTube és un client de YouTube ric en funcions i fàcil d'utilitzar que se centra en la privadesa.
    cs_CZ: FreeTube je funkčně bohatý a uživatelsky přívětivý klient YouTube se zaměřením na soukromí.
    da_DK: FreeTube er en funktionsrig og brugervenlig YouTube-klient med fokus på privatliv.
    de_DE: FreeTube ist ein funktionsreicher und benutzerfreundlicher YouTube-Client mit Fokus auf Datenschutz.
    el_GR: Το FreeTube είναι ένα πρόγραμμα-πελάτης YouTube με πλούσια σε λειτουργίες και φιλικό προς το χρήστη, με έμφαση στην προστασία της ιδιωτικής ζωής.
    en_GB: Freetube is a feature-rich and user-friendly Youtube client with a focus on privacy.
    es_ES: FreeTube es un cliente de YouTube completo y fácil de usar, con especial atención a la privacidad.
    fr_FR: FreeTube est un client YouTube riche en fonctionnalités et convivial, axé sur la protection de la vie privée.
    ga_IE: Is cliant YouTube saibhir i ngnéithe agus atá furasta le húsáid é FreeTube a dhíríonn ar phríobháideacht.
    hr_HR: FreeTube je YouTube klijent bogat značajkama i jednostavan za korištenje s naglaskom na privatnost.
    hu_HU: A FreeTube egy funkciókban gazdag és felhasználóbarát YouTube kliens, amely az adatvédelmet helyezi előtérbe.
    it_IT: FreeTube è un client YouTube ricco di funzionalità e di facile utilizzo, con particolare attenzione alla privacy.
    ja_JP: FreeTubeは、プライバシー保護を重視した、機能豊富で使いやすいYouTubeクライアントです。
    ko_KR: FreeTube는 개인 정보 보호에 중점을 둔 기능이 풍부하고 사용하기 쉬운 YouTube 클라이언트입니다.
    ml_IN: ഫ്രീട്യൂബ് സ്വകാര്യതയിൽ ശ്രദ്ധ കേന്ദ്രീകരിക്കുന്ന, സവിശേഷതകളാൽ സമ്പന്നവും ഉപയോക്തൃ സൗഹൃദവുമായ ഒരു YouTube ക്ലയന്റാണ്.
    nb_NO: FreeTube er en funksjonsrik og brukervennlig YouTube-klient med fokus på personvern.
    nl_NL: FreeTube is een gebruiksvriendelijke YouTube-client met veel functies en een focus op privacy.
    pl_PL: FreeTube to bogaty w funkcje i przyjazny użytkownikowi klient YouTube, który kładzie nacisk na prywatność.
    pt_BR: O FreeTube é um cliente do YouTube repleto de recursos e fácil de usar, com foco na privacidade.
    ro_RO: FreeTube este un client YouTube bogat în funcții și ușor de utilizat, cu accent pe confidențialitate.
    ru_RU: FreeTube — это многофункциональный и удобный в использовании клиент для YouTube, ориентированный на конфиденциальность.
    sk_SK: FreeTube je funkčne bohatý a užívateľsky prívetivý klient YouTube so zameraním na súkromie.
    sv_SE: FreeTube är en funktionsrik och användarvänlig YouTube-klient med fokus på integritet.
    tr_TR: FreeTube, gizliliğe odaklanan, özellik açısından zengin ve kullanıcı dostu bir YouTube istemcisidir.
    zh_TW: FreeTube 是一款功能豐富、易於使用且注重隱私的 YouTube 客戶端。
  tagline:
    en_US: 'A feature-rich and user-friendly YouTube client with a focus on privacy. '
    zh_CN: 注重隐私的 YouTube 客户端。
    ca_ES: Un client de YouTube ric en funcions i fàcil d'utilitzar amb un enfocament en la privadesa.
    cs_CZ: Uživatelsky přívětivý klient YouTube s bohatými funkcemi a zaměřením na soukromí.
    da_DK: En funktionsrig og brugervenlig YouTube-klient med fokus på privatliv.
    de_DE: Ein funktionsreicher und benutzerfreundlicher YouTube-Client mit Fokus auf Datenschutz.
    el_GR: Ένα πρόγραμμα-πελάτης YouTube με πλούσια σε λειτουργίες και φιλικό προς το χρήστη, με έμφαση στο απόρρητο.
    en_GB: 'A feature-rich and user-friendly Youtube client with a focus on privacy. '
    es_ES: Un cliente de YouTube completo y fácil de usar, con especial atención a la privacidad.
    fr_FR: Un client YouTube riche en fonctionnalités et convivial, axé sur la protection de la vie privée.
    ga_IE: Cliant YouTube atá lán de ghnéithe agus atá furasta le húsáid agus a dhíríonn ar phríobháideacht.
    hr_HR: YouTube klijent bogat značajkama i jednostavan za korištenje s naglaskom na privatnost.
    hu_HU: Egy funkciókban gazdag és felhasználóbarát YouTube kliens, amely az adatvédelmet helyezi előtérbe.
    it_IT: Un client YouTube ricco di funzionalità e intuitivo, con particolare attenzione alla privacy.
    ja_JP: プライバシー保護を重視した、機能豊富で使いやすいYouTubeクライアント。
    ko_KR: 개인 정보 보호에 중점을 둔, 기능이 풍부하고 사용하기 쉬운 YouTube 클라이언트입니다.
    ml_IN: സ്വകാര്യതയിൽ ശ്രദ്ധ കേന്ദ്രീകരിക്കുന്ന, സവിശേഷതകളാൽ സമ്പന്നവും ഉപയോക്തൃ സൗഹൃദവുമായ ഒരു YouTube ക്ലയന്റ്.
    nb_NO: En funksjonsrik og brukervennlig YouTube-klient med fokus på personvern.
    nl_NL: Een gebruiksvriendelijke YouTube-client met veel functies en een focus op privacy.
    pl_PL: Bogaty w funkcje i przyjazny użytkownikowi klient YouTube, który kładzie nacisk na prywatność.
    pt_BR: Um cliente do YouTube repleto de recursos e fácil de usar, com foco na privacidade.
    ro_RO: Un client YouTube bogat în funcții și ușor de utilizat, cu accent pe confidențialitate.
    ru_RU: Многофункциональный и удобный в использовании клиент YouTube, ориентированный на конфиденциальность.
    sk_SK: Funkciami bohatý a užívateľsky prívetivý klient YouTube so zameraním na súkromie.
    sv_SE: En funktionsrik och användarvänlig YouTube-klient med fokus på integritet.
    tr_TR: Gizliliğe odaklanan, özellik bakımından zengin ve kullanıcı dostu bir YouTube istemcisi.
    zh_TW: 注重隱私的 YouTube 客戶端。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/freetube-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/freetube-logo.png
  title:
    en_US: Freetube
    zh_CN: Freetube
    ca_ES: Freetube
    cs_CZ: Freetube
    da_DK: Freetube
    de_DE: Freetube
    el_GR: Freetube
    en_GB: Freetube
    es_ES: Freetube
    fr_FR: Freetube
    ga_IE: Freetube
    hr_HR: Freetube
    hu_HU: Freetube
    it_IT: Freetube
    ja_JP: Freetube
    ko_KR: Freetube
    ml_IN: Freetube
    nb_NO: Freetube
    nl_NL: Freetube
    pl_PL: Freetube
    pt_BR: Freetube
    ro_RO: Freetube
    ru_RU: Freetube
    sk_SK: Freetube
    sv_SE: Freetube
    tr_TR: Freetube
    zh_TW: Freetube
  category: Others
  id: wisdomsky.linuxserver.linuxserverfreetube
  version: version-190523148
