name: linuxserver-keepassxc
services:
  app:
    image: linuxserver/keepassxc:2.7.12@sha256:1a745600c80b84d7cbecea9149ef8022ef97a88c12f2467a806090836b4ac9f6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/keepassxc/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverkeepassxc/assets/icon.png
  title:
    en_US: Keepassxc (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverkeepassxc
  port_map: '3000'
  version: 2.7.12
