name: linuxserver-keepassxc
services:
  app:
    image: linuxserver/keepassxc:2.7.12@sha256:1a745600c80b84d7cbecea9149ef8022ef97a88c12f2467a806090836b4ac9f6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/keepassxc/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverkeepassxc/assets/icon.png
  title:
    en_US: Keepassxc (LinuxServer.io)
    ca_ES: Keepassxc (LinuxServer.io)
    cs_CZ: Keepassxc (LinuxServer.io)
    da_DK: Keepassxc (LinuxServer.io)
    de_DE: Keepassxc (LinuxServer.io)
    el_GR: Keepassxc (LinuxServer.io)
    en_GB: Keepassxc (LinuxServer.io)
    es_ES: Keepassxc (LinuxServer.io)
    fr_FR: Keepassxc (LinuxServer.io)
    ga_IE: Keepassxc (LinuxServer.io)
    hr_HR: Keepassxc (LinuxServer.io)
    hu_HU: Keepassxc (LinuxServer.io)
    it_IT: Keepassxc (LinuxServer.io)
    ja_JP: Keepassxc (LinuxServer.io)
    ko_KR: Keepassxc (LinuxServer.io)
    ml_IN: Keepassxc (LinuxServer.io)
    nb_NO: Keepassxc (LinuxServer.io)
    nl_NL: Keepassxc (LinuxServer.io)
    pl_PL: Keepassxc (LinuxServer.io)
    pt_BR: Keepassxc (LinuxServer.io)
    ro_RO: Keepassxc (LinuxServer.io)
    ru_RU: Keepassxc (LinuxServer.io)
    sk_SK: Keepassxc (LinuxServer.io)
    sv_SE: Keepassxc (LinuxServer.io)
    tr_TR: Keepassxc (LinuxServer.io)
    zh_CN: Keepassxc（LinuxServer.io）
    zh_TW: Keepassxc（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverkeepassxc
  port_map: '3000'
  version: 2.7.12
