name: linuxserver-doplarr_rs
services:
  app:
    image: linuxserver/doplarr_rs:4.6.0@sha256:bbd24bd3a967be149c3b0746ad74360461df1da5db2cdd816081be21667d6550
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/doplarr_rs/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverdoplarrrs/assets/icon.png
  title:
    en_US: Doplarr_rs (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverdoplarrrs
  port_map: '80'
  version: 4.6.0
