name: linuxserver-foldingathome
services:
  app:
    image: linuxserver/foldingathome:8.5.6@sha256:09f77735e39a1e474f5a6c562e6d72f70327fb3c6615c45f33be965bc9bd83fb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ACCOUNT_TOKEN: ''
      MACHINE_NAME: ''
      CLI_ARGS: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 7396
        published: 7396
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/foldingathome/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfoldingathome/assets/icon.png
  title:
    en_US: Foldingathome (LinuxServer.io)
    ca_ES: Foldingathome (LinuxServer.io)
    cs_CZ: Foldingathome (LinuxServer.io)
    da_DK: Foldingathome (LinuxServer.io)
    de_DE: Foldingathome (LinuxServer.io)
    el_GR: Foldingathome (LinuxServer.io)
    en_GB: Foldingathome (LinuxServer.io)
    es_ES: Foldingathome (LinuxServer.io)
    fr_FR: Foldingathome (LinuxServer.io)
    ga_IE: Foldingathome (LinuxServer.io)
    hr_HR: Foldingathome (LinuxServer.io)
    hu_HU: Foldingathome (LinuxServer.io)
    it_IT: Foldingathome (LinuxServer.io)
    ja_JP: Foldingathome (LinuxServer.io)
    ko_KR: Foldingathome (LinuxServer.io)
    ml_IN: Foldingathome (LinuxServer.io)
    nb_NO: Foldingathome (LinuxServer.io)
    nl_NL: Foldingathome (LinuxServer.io)
    pl_PL: Foldingathome (LinuxServer.io)
    pt_BR: Foldingathome (LinuxServer.io)
    ro_RO: Foldingathome (LinuxServer.io)
    ru_RU: Foldingathome (LinuxServer.io)
    sk_SK: Foldingathome (LinuxServer.io)
    sv_SE: Foldingathome (LinuxServer.io)
    tr_TR: Foldingathome (LinuxServer.io)
    zh_CN: Foldingathome（LinuxServer.io）
    zh_TW: Foldingathome（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverfoldingathome
  port_map: '80'
  version: 8.5.6
