name: linuxserver-unifi-network-application
services:
  app:
    image: linuxserver/unifi-network-application:10.6.106
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MONGO_USER: ''
      MONGO_PASS: ''
      MONGO_HOST: ''
      MONGO_PORT: ''
      MONGO_DBNAME: ''
      MONGO_AUTHSOURCE: ''
      MEM_LIMIT: ''
      MEM_STARTUP: ''
      MONGO_TLS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: MONGO_USER
          description:
            en_US: Mongodb Username. Only evaluated on first run. Special characters must be url encoded.
        - container: MONGO_PASS
          description:
            en_US: Mongodb Password. Only evaluated on first run. Special characters must be url encoded.
        - container: MONGO_HOST
          description:
            en_US: Mongodb Hostname. Only evaluated on first run.
        - container: MONGO_PORT
          description:
            en_US: Mongodb Port. Only evaluated on first run.
        - container: MONGO_DBNAME
          description:
            en_US: Mongodb Database Name (stats DB is automatically suffixed with _stat). Only evaluated on first run.
        - container: MONGO_AUTHSOURCE
          description:
            en_US: Mongodb authSource. For Atlas set to admin. Only evaluated on first run.
        - container: MEM_LIMIT
          description:
            en_US: Optionally change the Java memory limit (in Megabytes). Set to default to reset to default [OPTIONAL]
        - container: MEM_STARTUP
          description:
            en_US: Optionally change the Java initial/minimum memory (in Megabytes). Set to default to reset to default [OPTIONAL]
        - container: MONGO_TLS
          description:
            en_US: Mongodb enable TLS. Only evaluated on first run. [OPTIONAL]
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
      - target: 3478
        published: 3478
        protocol: udp
      - target: 10001
        published: 10001
        protocol: udp
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 1900
        published: 1900
        protocol: udp
      - target: 8843
        published: 8843
        protocol: tcp
      - target: 8880
        published: 8880
        protocol: tcp
      - target: 6789
        published: 6789
        protocol: tcp
      - target: 5514
        published: 5514
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/unifi-network-application/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: The Unifi-network-application software is a powerful, enterprise wireless software engine ideal for high-density client deployments requiring low latency and high uptime performance.
    ca_ES: El programari d'aplicació de xarxa Unifi és un potent motor de programari sense fil empresarial ideal per a implementacions de clients d'alta densitat que requereixen baixa latència i un alt rendiment de temps de funcionament.
    cs_CZ: Aplikační software Unifi pro síťové sítě je výkonný podnikový bezdrátový softwarový engine, ideální pro klientské nasazení s vysokou hustotou, které vyžadují nízkou latenci a vysokou provozuschopnost.
    da_DK: Unifi-netværksapplikationssoftwaren er en kraftfuld trådløs softwaremotor til virksomheder, der er ideel til klientimplementeringer med høj tæthed, der kræver lav latenstid og høj oppetid.
    de_DE: Die Unifi-Netzwerkanwendungssoftware ist eine leistungsstarke, drahtlose Unternehmenssoftware-Engine, die sich ideal für Client-Bereitstellungen mit hoher Dichte eignet, die geringe Latenz und hohe Verfügbarkeit erfordern.
    el_GR: Το λογισμικό εφαρμογών δικτύου Unifi είναι μια ισχυρή μηχανή λογισμικού ασύρματης δικτύωσης για επιχειρήσεις, ιδανική για αναπτύξεις σε υπολογιστές-πελάτες υψηλής πυκνότητας που απαιτούν χαμηλή καθυστέρηση και υψηλή απόδοση χρόνου λειτουργίας.
    en_GB: The Unifi-network-application software is a powerful, enterprise wireless software engine ideal for high-density client deployments requiring low latency and high uptime performance.
    es_ES: El software Unifi-network-application es un potente motor de software inalámbrico empresarial, ideal para implementaciones de clientes de alta densidad que requieren baja latencia y un alto rendimiento en tiempo de actividad.
    fr_FR: Le logiciel d'application réseau Unifi est un moteur logiciel sans fil puissant, destiné aux entreprises et idéal pour les déploiements clients à haute densité nécessitant une faible latence et une disponibilité élevée.
    ga_IE: Is inneall bogearraí gan sreang cumhachtach fiontraíochta é bogearraí feidhmchláir Unifi-network-application atá oiriúnach d'imscaradh cliant ard-dlúis a éilíonn latency íseal agus feidhmíocht ard-ama ar líne.
    hr_HR: Unifi-network-application softver je moćan, bežični softverski mehanizam za poduzeća, idealan za implementacije klijenata visoke gustoće koji zahtijevaju nisku latenciju i visoku dostupnost.
    hu_HU: Az Unifi-network-application szoftver egy nagy teljesítményű, vállalati szintű vezeték nélküli szoftvermotor, amely ideális nagy sűrűségű klienstelepítésekhez, amelyek alacsony késleltetést és magas üzemidőt igényelnek.
    it_IT: Il software applicativo di rete Unifi è un potente motore software wireless di livello aziendale, ideale per implementazioni con un'elevata densità di client che richiedono bassa latenza e prestazioni con elevata disponibilità.
    ja_JP: Unifiネットワークアプリケーションソフトウェアは、低遅延と高い稼働率が求められる高密度クライアント環境に最適な、強力なエンタープライズ向けワイヤレスソフトウェアエンジンです。
    ko_KR: Unifi 네트워크 애플리케이션 소프트웨어는 높은 지연 시간과 높은 가동 시간 성능이 요구되는 고밀도 클라이언트 구축에 이상적인 강력한 엔터프라이즈급 무선 소프트웨어 엔진입니다.
    ml_IN: കുറഞ്ഞ ലേറ്റൻസിയും ഉയർന്ന അപ്‌ടൈം പ്രകടനവും ആവശ്യമുള്ള ഉയർന്ന സാന്ദ്രതയുള്ള ക്ലയന്റ് വിന്യാസങ്ങൾക്ക് അനുയോജ്യമായ ഒരു ശക്തമായ, എന്റർപ്രൈസ് വയർലെസ് സോഫ്റ്റ്‌വെയർ എഞ്ചിനാണ് യൂണിഫൈ-നെറ്റ്‌വർക്ക്-ആപ്ലിക്കേഷൻ സോഫ്റ്റ്‌വെയർ.
    nb_NO: Unifi-nettverksprogramvaren er en kraftig trådløs programvaremotor for bedrifter som er ideell for klientdistribusjoner med høy tetthet, og som krever lav latens og høy oppetid.
    nl_NL: De Unifi-netwerkapplicatiesoftware is een krachtige, bedrijfsbrede draadloze software-engine, ideaal voor implementaties met een hoge clientdichtheid die lage latentie en hoge uptime vereisen.
    pl_PL: Oprogramowanie Unifi-network-application to wydajny, korporacyjny moduł oprogramowania bezprzewodowego, idealny do wdrożeń klienckich o dużej gęstości, wymagających niskich opóźnień i wysokiej wydajności czasu sprawności.
    pt_BR: O software Unifi-network-application é um poderoso mecanismo de software sem fio empresarial, ideal para implantações de clientes de alta densidade que exigem baixa latência e alto desempenho de disponibilidade.
    ro_RO: Software-ul Unifi-network-application este un motor software wireless puternic, pentru întreprinderi, ideal pentru implementări de clienți cu densitate mare care necesită latență redusă și performanță ridicată de funcționare.
    ru_RU: Программное обеспечение Unifi-network-application представляет собой мощный программный движок для корпоративных беспроводных сетей, идеально подходящий для развертывания сетей с высокой плотностью клиентов, требующих низкой задержки и высокой производительности.
    sk_SK: Softvér Unifi-network-application je výkonný podnikový bezdrôtový softvérový engine, ideálny pre klientske nasadenia s vysokou hustotou, ktoré vyžadujú nízku latenciu a vysokú prevádzkyschopnosť.
    sv_SE: Unifi-nätverksprogramvaran är en kraftfull trådlös programvarumotor för företag som är idealisk för klientdistributioner med hög densitet som kräver låg latens och hög drifttid.
    tr_TR: Unifi ağ uygulama yazılımı, düşük gecikme süresi ve yüksek çalışma süresi performansı gerektiren yüksek yoğunluklu istemci dağıtımları için ideal, güçlü bir kurumsal kablosuz yazılım motorudur.
    zh_CN: UniFi Network Application 是功能强大的企业无线网络软件，适用于要求低延迟和高可用性的高密度客户端部署。
    zh_TW: UniFi Network Application 是功能強大的企業無線網路軟體，適用於要求低延遲和高可用性的高密度客戶端部署。
  tagline:
    en_US: The Unifi-network-application software is a powerful, enterprise wireless software engine ideal for high-density client deployments requiring low latency and high uptime performance.
    ca_ES: El programari d'aplicació de xarxa Unifi és un potent motor de programari sense fil empresarial ideal per a implementacions de clients d'alta densitat que requereixen baixa latència i un alt rendiment de temps de funcionament.
    cs_CZ: Aplikační software Unifi pro síťové sítě je výkonný podnikový bezdrátový softwarový engine, ideální pro klientské nasazení s vysokou hustotou, které vyžadují nízkou latenci a vysokou provozuschopnost.
    da_DK: Unifi-netværksapplikationssoftwaren er en kraftfuld trådløs softwaremotor til virksomheder, der er ideel til klientimplementeringer med høj tæthed, der kræver lav latenstid og høj oppetid.
    de_DE: Die Unifi-Netzwerkanwendungssoftware ist eine leistungsstarke, drahtlose Unternehmenssoftware-Engine, die sich ideal für Client-Bereitstellungen mit hoher Dichte eignet, die geringe Latenz und hohe Verfügbarkeit erfordern.
    el_GR: Το λογισμικό εφαρμογών δικτύου Unifi είναι μια ισχυρή μηχανή λογισμικού ασύρματης δικτύωσης για επιχειρήσεις, ιδανική για αναπτύξεις σε υπολογιστές-πελάτες υψηλής πυκνότητας που απαιτούν χαμηλή καθυστέρηση και υψηλή απόδοση χρόνου λειτουργίας.
    en_GB: The Unifi-network-application software is a powerful, enterprise wireless software engine ideal for high-density client deployments requiring low latency and high uptime performance.
    es_ES: El software Unifi-network-application es un potente motor de software inalámbrico empresarial, ideal para implementaciones de clientes de alta densidad que requieren baja latencia y un alto rendimiento en tiempo de actividad.
    fr_FR: Le logiciel d'application réseau Unifi est un moteur logiciel sans fil puissant, destiné aux entreprises et idéal pour les déploiements clients à haute densité nécessitant une faible latence et une disponibilité élevée.
    ga_IE: Is inneall bogearraí gan sreang cumhachtach fiontraíochta é bogearraí feidhmchláir Unifi-network-application atá oiriúnach d'imscaradh cliant ard-dlúis a éilíonn latency íseal agus feidhmíocht ard-ama ar líne.
    hr_HR: Unifi-network-application softver je moćan, bežični softverski mehanizam za poduzeća, idealan za implementacije klijenata visoke gustoće koji zahtijevaju nisku latenciju i visoku dostupnost.
    hu_HU: Az Unifi-network-application szoftver egy nagy teljesítményű, vállalati szintű vezeték nélküli szoftvermotor, amely ideális nagy sűrűségű klienstelepítésekhez, amelyek alacsony késleltetést és magas üzemidőt igényelnek.
    it_IT: Il software applicativo di rete Unifi è un potente motore software wireless di livello aziendale, ideale per implementazioni con un'elevata densità di client che richiedono bassa latenza e prestazioni con elevata disponibilità.
    ja_JP: Unifiネットワークアプリケーションソフトウェアは、低遅延と高い稼働率が求められる高密度クライアント環境に最適な、強力なエンタープライズ向けワイヤレスソフトウェアエンジンです。
    ko_KR: Unifi 네트워크 애플리케이션 소프트웨어는 높은 지연 시간과 높은 가동 시간 성능이 요구되는 고밀도 클라이언트 구축에 이상적인 강력한 엔터프라이즈급 무선 소프트웨어 엔진입니다.
    ml_IN: കുറഞ്ഞ ലേറ്റൻസിയും ഉയർന്ന അപ്‌ടൈം പ്രകടനവും ആവശ്യമുള്ള ഉയർന്ന സാന്ദ്രതയുള്ള ക്ലയന്റ് വിന്യാസങ്ങൾക്ക് അനുയോജ്യമായ ഒരു ശക്തമായ, എന്റർപ്രൈസ് വയർലെസ് സോഫ്റ്റ്‌വെയർ എഞ്ചിനാണ് യൂണിഫൈ-നെറ്റ്‌വർക്ക്-ആപ്ലിക്കേഷൻ സോഫ്റ്റ്‌വെയർ.
    nb_NO: Unifi-nettverksprogramvaren er en kraftig trådløs programvaremotor for bedrifter som er ideell for klientdistribusjoner med høy tetthet, og som krever lav latens og høy oppetid.
    nl_NL: De Unifi-netwerkapplicatiesoftware is een krachtige, bedrijfsbrede draadloze software-engine, ideaal voor implementaties met een hoge clientdichtheid die lage latentie en hoge uptime vereisen.
    pl_PL: Oprogramowanie Unifi-network-application to wydajny, korporacyjny moduł oprogramowania bezprzewodowego, idealny do wdrożeń klienckich o dużej gęstości, wymagających niskich opóźnień i wysokiej wydajności czasu sprawności.
    pt_BR: O software Unifi-network-application é um poderoso mecanismo de software sem fio empresarial, ideal para implantações de clientes de alta densidade que exigem baixa latência e alto desempenho de disponibilidade.
    ro_RO: Software-ul Unifi-network-application este un motor software wireless puternic, pentru întreprinderi, ideal pentru implementări de clienți cu densitate mare care necesită latență redusă și performanță ridicată de funcționare.
    ru_RU: Программное обеспечение Unifi-network-application представляет собой мощный программный движок для корпоративных беспроводных сетей, идеально подходящий для развертывания сетей с высокой плотностью клиентов, требующих низкой задержки и высокой производительности.
    sk_SK: Softvér Unifi-network-application je výkonný podnikový bezdrôtový softvérový engine, ideálny pre klientske nasadenia s vysokou hustotou, ktoré vyžadujú nízku latenciu a vysokú prevádzkyschopnosť.
    sv_SE: Unifi-nätverksprogramvaran är en kraftfull trådlös programvarumotor för företag som är idealisk för klientdistributioner med hög densitet som kräver låg latens och hög drifttid.
    tr_TR: Unifi ağ uygulama yazılımı, düşük gecikme süresi ve yüksek çalışma süresi performansı gerektiren yüksek yoğunluklu istemci dağıtımları için ideal, güçlü bir kurumsal kablosuz yazılım motorudur.
    zh_CN: 面向高密度部署的企业无线网络管理软件。
    zh_TW: 面向高密度部署的企業無線網路管理軟體。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/unifi-banner.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/unifi-banner.png
  title:
    en_US: Unifi network-application (LinuxServer.io)
    ca_ES: Unifi network-application (LinuxServer.io)
    cs_CZ: Unifi network-application (LinuxServer.io)
    da_DK: Unifi network-application (LinuxServer.io)
    de_DE: Unifi network-application (LinuxServer.io)
    el_GR: Unifi network-application (LinuxServer.io)
    en_GB: Unifi network-application (LinuxServer.io)
    es_ES: Unifi network-application (LinuxServer.io)
    fr_FR: Unifi network-application (LinuxServer.io)
    ga_IE: Unifi network-application (LinuxServer.io)
    hr_HR: Unifi network-application (LinuxServer.io)
    hu_HU: Unifi network-application (LinuxServer.io)
    it_IT: Unifi network-application (LinuxServer.io)
    ja_JP: Unifi network-application (LinuxServer.io)
    ko_KR: Unifi network-application (LinuxServer.io)
    ml_IN: Unifi network-application (LinuxServer.io)
    nb_NO: Unifi network-application (LinuxServer.io)
    nl_NL: Unifi network-application (LinuxServer.io)
    pl_PL: Unifi network-application (LinuxServer.io)
    pt_BR: Unifi network-application (LinuxServer.io)
    ro_RO: Unifi network-application (LinuxServer.io)
    ru_RU: Unifi network-application (LinuxServer.io)
    sk_SK: Unifi network-application (LinuxServer.io)
    sv_SE: Unifi network-application (LinuxServer.io)
    tr_TR: Unifi network-application (LinuxServer.io)
    zh_CN: Unifi network-application（LinuxServer.io）
    zh_TW: Unifi network-application（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverunifinetworkapplication
  port_map: '8080'
  version: 10.6.106
