name: linuxserver-requestrr
services:
  app:
    image: linuxserver/requestrr:2.1.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_US: Contains all relevant configuration files.
      ports:
        - container: '4545'
          description:
            en_US: web gui
    ports:
      - target: 4545
        published: 4545
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/requestrr/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_US: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    zh_CN: |-
      Requestrr 是聊天机器人，可通过聊天简化 Sonarr、Radarr 和 Ombi 等服务的使用。

      访问项目主页：https://github.com/orgs/linuxserver/packages/container/package/requestrr
    ca_ES: 'Visita la pàgina principal: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    cs_CZ: 'Navštivte domovskou stránku: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    da_DK: 'Besøg hjemmesiden: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    de_DE: 'Besuchen Sie die Homepage: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    el_GR: 'Επισκεφθείτε την αρχική σελίδα: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    en_GB: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    es_ES: 'Visite la página principal: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    fr_FR: "Consultez la page d'accueil\_: https://github.com/orgs/linuxserver/packages/container/package/requestrr"
    ga_IE: 'Tabhair cuairt ar an leathanach baile: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    hr_HR: 'Posjetite početnu stranicu: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    hu_HU: 'Látogassa meg a honlapot: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    it_IT: 'Visita la homepage: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    ja_JP: 'ホームページをご覧ください: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    ko_KR: '홈페이지 방문: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    ml_IN: 'ഹോംപേജ് സന്ദർശിക്കുക: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    nb_NO: 'Besøk hjemmesiden: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    nl_NL: 'Bezoek de homepage: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    pl_PL: 'Odwiedź stronę główną: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    pt_BR: 'Visite a página inicial: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    ro_RO: 'Vizitați pagina principală: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    ru_RU: 'Перейдите на главную страницу: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    sk_SK: 'Navštívte domovskú stránku: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    sv_SE: 'Besök hemsidan: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    tr_TR: 'Ana sayfayı ziyaret edin: https://github.com/orgs/linuxserver/packages/container/package/requestrr'
    zh_TW: |-
      Requestrr 是聊天機器人，可透過聊天簡化 Sonarr、Radarr 和 Ombi 等服務的使用。

      訪問專案主頁：https://github.com/orgs/linuxserver/packages/container/package/requestrr
  tagline:
    en_US: A chatbot used to simplify using services like Sonarr/Radarr/Ombi via the use of chat.
    zh_CN: 通过聊天机器人提交媒体请求。
    ca_ES: Un chatbot que s'utilitza per simplificar l'ús de serveis com Sonarr/Radarr/Ombi mitjançant el xat.
    cs_CZ: Chatbot sloužící ke zjednodušení používání služeb jako Sonarr/Radarr/Ombi prostřednictvím chatu.
    da_DK: En chatbot, der bruges til at forenkle brugen af tjenester som Sonarr/Radarr/Ombi via chat.
    de_DE: Ein Chatbot, der die Nutzung von Diensten wie Sonarr/Radarr/Ombi durch die Verwendung von Chat vereinfacht.
    el_GR: Ένα chatbot που χρησιμοποιείται για την απλοποίηση της χρήσης υπηρεσιών όπως το Sonarr/Radarr/Ombi μέσω της χρήσης συνομιλίας.
    en_GB: A chatbot used to simplify using services like Sonarr/Radarr/Ombi via the use of chat.
    es_ES: Un chatbot utilizado para simplificar el uso de servicios como Sonarr/Radarr/Ombi mediante el uso del chat.
    fr_FR: Un chatbot utilisé pour simplifier l'utilisation de services comme Sonarr/Radarr/Ombi via le chat.
    ga_IE: Comhrábot a úsáidtear chun úsáid seirbhísí cosúil le Sonarr/Radarr/Ombi a shimpliú trí úsáid comhrá.
    hr_HR: Chatbot koji se koristi za pojednostavljenje korištenja usluga poput Sonarr/Radarr/Ombi putem chata.
    hu_HU: Egy chatbot, amely a Sonarr/Radarr/Ombihoz hasonló szolgáltatások használatának egyszerűsítésére szolgál a chat segítségével.
    it_IT: Un chatbot utilizzato per semplificare l'utilizzo di servizi come Sonarr/Radarr/Ombi tramite la chat.
    ja_JP: チャット機能を利用して、Sonarr/Radarr/Ombiなどのサービスを簡素化するために使用されるチャットボット。
    ko_KR: Sonarr/Radarr/Ombi와 같은 서비스를 채팅을 통해 간편하게 사용할 수 있도록 도와주는 챗봇입니다.
    ml_IN: ചാറ്റ് ഉപയോഗിച്ച് സോണാർ/റഡാർ/ഓംബി പോലുള്ള സേവനങ്ങൾ ഉപയോഗിക്കുന്നത് ലളിതമാക്കാൻ ഉപയോഗിക്കുന്ന ഒരു ചാറ്റ്ബോട്ട്.
    nb_NO: En chatbot som brukes til å forenkle bruken av tjenester som Sonarr/Radarr/Ombi via chat.
    nl_NL: Een chatbot die het gebruik van diensten zoals Sonarr/Radarr/Ombi vereenvoudigt door middel van chat.
    pl_PL: Chatbot mający na celu uproszczenie korzystania z usług takich jak Sonarr/Radarr/Ombi poprzez wykorzystanie czatu.
    pt_BR: Um chatbot usado para simplificar o uso de serviços como Sonarr/Radarr/Ombi por meio de bate-papo.
    ro_RO: Un chatbot folosit pentru a simplifica utilizarea serviciilor precum Sonarr/Radarr/Ombi prin intermediul chat-ului.
    ru_RU: Чат-бот, предназначенный для упрощения использования таких сервисов, как Sonarr/Radarr/Ombi, посредством чата.
    sk_SK: Chatbot používaný na zjednodušenie používania služieb ako Sonarr/Radarr/Ombi prostredníctvom chatu.
    sv_SE: En chatbot som används för att förenkla användningen av tjänster som Sonarr/Radarr/Ombi via chatt.
    tr_TR: Sonarr/Radarr/Ombi gibi hizmetlerin sohbet yoluyla kullanımını kolaylaştırmak için kullanılan bir chatbot.
    zh_TW: 透過聊天機器人提交媒體請求。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/requestrr.png
  thumbnail: https://github.com/darkalfx/requestrr/raw/master/Logos/requestrr_discord_Icon_512.png
  title:
    en_US: Requestrr
    zh_CN: Requestrr
    ca_ES: Requestrr
    cs_CZ: Requestrr
    da_DK: Requestrr
    de_DE: Requestrr
    el_GR: Requestrr
    en_GB: Requestrr
    es_ES: Requestrr
    fr_FR: Requestrr
    ga_IE: Requestrr
    hr_HR: Requestrr
    hu_HU: Requestrr
    it_IT: Requestrr
    ja_JP: Requestrr
    ko_KR: Requestrr
    ml_IN: Requestrr
    nb_NO: Requestrr
    nl_NL: Requestrr
    pl_PL: Requestrr
    pt_BR: Requestrr
    ro_RO: Requestrr
    ru_RU: Requestrr
    sk_SK: Requestrr
    sv_SE: Requestrr
    tr_TR: Requestrr
    zh_TW: Requestrr
  category: Others
  project_url: https://github.com/darkalfx/requestrr
  port_map: '4545'
  id: wisdomsky.linuxserver.linuxserverrequestrr
  version: 2.1.2
  website: https://github.com/darkalfx/requestrr
