name: linuxserver-gitqlient
services:
  app:
    image: linuxserver/gitqlient:1.6.3@sha256:e089c64fe443c6bbd6fa20855c6d2fbf6fcda06f0b1c70f1389e016f43b59a72
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gitqlient/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservergitqlient/assets/icon.png
  title:
    en_US: Gitqlient (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxservergitqlient
  port_map: '3000'
  version: 1.6.3
