name: linuxserver-foldingathome
services:
  app:
    image: linuxserver/foldingathome:8.5.6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ACCOUNT_TOKEN: ''
      MACHINE_NAME: ''
      CLI_ARGS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: ACCOUNT_TOKEN
          description:
            en_US: Register for an account on https://app.foldingathome.org and retrieve account token in settings. Required on first start.
        - container: MACHINE_NAME
          description:
            en_US: Assign a friendly name to this instance (no spaces). Required on first start.
        - container: CLI_ARGS
          description:
            en_US: Optionally pass additional cli arguments to fah-client on container start. [OPTIONAL]
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 7396
        published: 7396
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/foldingathome/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Folding@home is a distributed computing project for simulating protein dynamics, including the process of protein folding and the movements of proteins implicated in a variety of diseases. It brings together citizen scientists who volunteer to run simulations of protein dynamics on their personal computers. Insights from this data are helping scientists to better understand biology, and providing new opportunities for developing therapeutics.
    ca_ES: Folding@home és un projecte de computació distribuïda per simular la dinàmica de les proteïnes, incloent-hi el procés de plegament de proteïnes i els moviments de les proteïnes implicades en diverses malalties. Reuneix ciutadans científics que s'ofereixen voluntaris per executar simulacions de la dinàmica de les proteïnes als seus ordinadors personals. Els coneixements obtinguts d'aquestes dades ajuden els científics a comprendre millor la biologia i ofereixen noves oportunitats per desenvolupar teràpies.
    cs_CZ: Folding@home je distribuovaný výpočetní projekt pro simulaci dynamiky proteinů, včetně procesu skládání proteinů a pohybů proteinů zapojených do různých onemocnění. Sdružuje občanské vědce, kteří se dobrovolně hlásí k provádění simulací dynamiky proteinů na svých osobních počítačích. Poznatky z těchto dat pomáhají vědcům lépe porozumět biologii a poskytují nové příležitosti pro vývoj léčiv.
    da_DK: Folding@home er et distribueret databehandlingsprojekt til simulering af proteindynamik, herunder processen med proteinfoldning og bevægelserne af proteiner, der er involveret i en række sygdomme. Det samler borgerforskere, der frivilligt kører simuleringer af proteindynamik på deres personlige computere. Indsigt fra disse data hjælper forskere med bedre at forstå biologi og giver nye muligheder for at udvikle behandlinger.
    de_DE: Folding@home ist ein verteiltes Rechenprojekt zur Simulation der Proteindynamik, einschließlich der Proteinfaltung und der Bewegungen von Proteinen, die an verschiedenen Krankheiten beteiligt sind. Es bringt engagierte Bürgerwissenschaftler zusammen, die freiwillig Simulationen der Proteindynamik auf ihren PCs durchführen. Die gewonnenen Erkenntnisse helfen Wissenschaftlern, biologische Prozesse besser zu verstehen und eröffnen neue Möglichkeiten für die Entwicklung von Therapien.
    el_GR: Το Folding@home είναι ένα έργο κατανεμημένων υπολογιστών για την προσομοίωση της δυναμικής των πρωτεϊνών, συμπεριλαμβανομένης της διαδικασίας αναδίπλωσης των πρωτεϊνών και των κινήσεων των πρωτεϊνών που εμπλέκονται σε μια ποικιλία ασθενειών. Φέρνει σε επαφή πολίτες επιστήμονες που προσφέρονται εθελοντικά να εκτελέσουν προσομοιώσεις της δυναμικής των πρωτεϊνών στους προσωπικούς τους υπολογιστές. Οι πληροφορίες από αυτά τα δεδομένα βοηθούν τους επιστήμονες να κατανοήσουν καλύτερα τη βιολογία και παρέχουν νέες ευκαιρίες για την ανάπτυξη θεραπευτικών μεθόδων.
    en_GB: Folding@home is a distributed computing project for simulating protein dynamics, including the process of protein folding and the movements of proteins implicated in a variety of diseases. It brings together citizen scientists who volunteer to run simulations of protein dynamics on their personal computers. Insights from this data are helping scientists to better understand biology, and providing new opportunities for developing therapeutics.
    es_ES: Folding@home es un proyecto de computación distribuida para simular la dinámica de las proteínas, incluyendo el proceso de plegamiento proteico y los movimientos de las proteínas implicadas en diversas enfermedades. Reúne a científicos ciudadanos que se ofrecen como voluntarios para ejecutar simulaciones de la dinámica de las proteínas en sus ordenadores personales. Los conocimientos derivados de estos datos están ayudando a los científicos a comprender mejor la biología y ofreciendo nuevas oportunidades para el desarrollo de terapias.
    fr_FR: Folding@home est un projet de calcul distribué qui simule la dynamique des protéines, notamment le processus de repliement et les mouvements des protéines impliquées dans diverses maladies. Il rassemble des citoyens scientifiques bénévoles qui réalisent des simulations de dynamique protéique sur leurs ordinateurs personnels. Les données issues de ce projet aident les scientifiques à mieux comprendre la biologie et ouvrent de nouvelles perspectives pour le développement de thérapies.
    ga_IE: Is tionscadal ríomhaireachta dáilte é Folding@home chun dinimic próitéine a insamhladh, lena n-áirítear an próiseas fillte próitéine agus gluaiseachtaí próitéiní a bhfuil baint acu le réimse galair. Tugann sé eolaithe saoránach le chéile a dhéanann obair dheonach chun insamhaltaí ar dhinimic próitéine a reáchtáil ar a ríomhairí pearsanta. Tá léargais ó na sonraí seo ag cabhrú le heolaithe tuiscint níos fearr a fháil ar an mbitheolaíocht, agus ag soláthar deiseanna nua chun teiripí a fhorbairt.
    hr_HR: Folding@home je distribuirani računalni projekt za simulaciju dinamike proteina, uključujući proces savijanja proteina i kretanje proteina uključenih u razne bolesti. Okuplja građane znanstvenike koji se dobrovoljno prijavljuju za provođenje simulacija dinamike proteina na svojim osobnim računalima. Uvidi iz ovih podataka pomažu znanstvenicima da bolje razumiju biologiju i pružaju nove mogućnosti za razvoj terapije.
    hu_HU: A Folding@home egy elosztott számítástechnikai projekt, amely fehérjedinamika szimulációjára szolgál, beleértve a fehérjehajtogatás folyamatát és a különféle betegségekkel összefüggő fehérjék mozgását. Összehozza azokat a civil tudósokat, akik önkéntesként fehérjedinamikai szimulációkat futtatnak személyi számítógépeiken. Az ezekből az adatokból származó információk segítik a tudósokat a biológia jobb megértésében, és új lehetőségeket kínálnak a terápiák fejlesztésére.
    it_IT: Folding@home è un progetto di calcolo distribuito per la simulazione delle dinamiche proteiche, inclusi il processo di ripiegamento delle proteine e i movimenti delle proteine implicate in diverse malattie. Riunisce cittadini scienziati che si offrono volontari per eseguire simulazioni delle dinamiche proteiche sui propri computer personali. Le informazioni ricavate da questi dati stanno aiutando gli scienziati a comprendere meglio la biologia e offrono nuove opportunità per lo sviluppo di terapie.
    ja_JP: Folding@homeは、タンパク質の折りたたみ過程や、様々な疾患に関与するタンパク質の動きなど、タンパク質の動態をシミュレーションするための分散コンピューティングプロジェクトです。このプロジェクトは、ボランティアとして個人のコンピュータ上でタンパク質の動態シミュレーションを実行する市民科学者を結集させています。このデータから得られる知見は、科学者が生物学をより深く理解するのに役立ち、新たな治療法開発の機会を提供しています。
    ko_KR: Folding@home은 단백질 접힘 과정과 다양한 질병과 관련된 단백질의 움직임을 포함한 단백질 역학을 시뮬레이션하는 분산 컴퓨팅 프로젝트입니다. 이 프로젝트는 자발적으로 개인용 컴퓨터에서 단백질 역학 시뮬레이션을 실행하는 시민 과학자들을 모아 운영됩니다. 이렇게 얻은 데이터는 과학자들이 생물학을 더 잘 이해하고 새로운 치료법 개발을 위한 가능성을 열어주는 데 도움을 주고 있습니다.
    ml_IN: പ്രോട്ടീൻ ഡൈനാമിക്സ് സിമുലേറ്റ് ചെയ്യുന്നതിനുള്ള ഒരു ഡിസ്ട്രിബ്യൂട്ടഡ് കമ്പ്യൂട്ടിംഗ് പ്രോജക്റ്റാണ് ഫോൾഡിംഗ്@ഹോം, ഇതിൽ പ്രോട്ടീൻ ഫോൾഡിംഗ് പ്രക്രിയയും വിവിധ രോഗങ്ങളിൽ ഉൾപ്പെട്ടിരിക്കുന്ന പ്രോട്ടീനുകളുടെ ചലനങ്ങളും ഉൾപ്പെടുന്നു. തങ്ങളുടെ പേഴ്സണൽ കമ്പ്യൂട്ടറുകളിൽ പ്രോട്ടീൻ ഡൈനാമിക്സിന്റെ സിമുലേഷനുകൾ പ്രവർത്തിപ്പിക്കാൻ സന്നദ്ധത പ്രകടിപ്പിക്കുന്ന പൗര ശാസ്ത്രജ്ഞരെ ഇത് ഒരുമിച്ച് കൊണ്ടുവരുന്നു. ഈ ഡാറ്റയിൽ നിന്നുള്ള ഉൾക്കാഴ്ചകൾ ശാസ്ത്രജ്ഞർക്ക് ജീവശാസ്ത്രത്തെ നന്നായി മനസ്സിലാക്കാൻ സഹായിക്കുകയും ചികിത്സകൾ വികസിപ്പിക്കുന്നതിനുള്ള പുതിയ അവസരങ്ങൾ നൽകുകയും ചെയ്യുന്നു.
    nb_NO: Folding@home er et distribuert databehandlingsprosjekt for simulering av proteindynamikk, inkludert prosessen med proteinfolding og bevegelsene til proteiner som er involvert i en rekke sykdommer. Det samler forskere som frivillig kjører simuleringer av proteindynamikk på sine personlige datamaskiner. Innsikt fra disse dataene hjelper forskere med å bedre forstå biologi og gir nye muligheter for å utvikle behandlinger.
    nl_NL: Folding@home is een gedistribueerd computerproject voor het simuleren van eiwitdynamiek, waaronder het vouwproces van eiwitten en de bewegingen van eiwitten die betrokken zijn bij diverse ziekten. Het brengt burgerwetenschappers samen die vrijwillig simulaties van eiwitdynamiek uitvoeren op hun persoonlijke computers. De inzichten uit deze data helpen wetenschappers om de biologie beter te begrijpen en bieden nieuwe mogelijkheden voor de ontwikkeling van therapieën.
    pl_PL: Folding@home to projekt obliczeń rozproszonych, który symuluje dynamikę białek, w tym proces ich fałdowania oraz ruchy białek zaangażowanych w różnorodne choroby. Projekt skupia naukowców-obywateli, którzy zgłoszą się na ochotnika do przeprowadzania symulacji dynamiki białek na swoich komputerach osobistych. Wiedza uzyskana z tych danych pomaga naukowcom lepiej zrozumieć biologię i stwarza nowe możliwości rozwoju terapii.
    pt_BR: Folding@home é um projeto de computação distribuída para simulação da dinâmica de proteínas, incluindo o processo de dobramento de proteínas e os movimentos de proteínas envolvidas em diversas doenças. Ele reúne cientistas cidadãos que se voluntariam para executar simulações da dinâmica de proteínas em seus computadores pessoais. Os insights obtidos a partir desses dados estão ajudando os cientistas a compreender melhor a biologia e proporcionando novas oportunidades para o desenvolvimento de terapias.
    ro_RO: Folding@home este un proiect de calcul distribuit pentru simularea dinamicii proteinelor, inclusiv procesul de pliere a proteinelor și mișcările proteinelor implicate într-o varietate de boli. Acesta reunește oameni de știință cetățeni care se oferă voluntari să ruleze simulări ale dinamicii proteinelor pe computerele lor personale. Informațiile obținute din aceste date îi ajută pe oamenii de știință să înțeleagă mai bine biologia și oferă noi oportunități pentru dezvoltarea de terapii.
    ru_RU: Folding@home — это проект распределенных вычислений для моделирования динамики белков, включая процесс сворачивания белков и движения белков, участвующих в развитии различных заболеваний. Он объединяет ученых-любителей, которые добровольно запускают моделирование динамики белков на своих персональных компьютерах. Полученные данные помогают ученым лучше понимать биологию и открывают новые возможности для разработки терапевтических средств.
    sk_SK: Folding@home je projekt distribuovaných výpočtov zameraný na simuláciu dynamiky bielkovín vrátane procesu skladania bielkovín a pohybov bielkovín, ktoré sa podieľajú na rôznych ochoreniach. Spája vedcov z radov občanov, ktorí sa dobrovoľne prihlásia na simulácie dynamiky bielkovín na svojich osobných počítačoch. Poznatky z týchto údajov pomáhajú vedcom lepšie pochopiť biológiu a poskytujú nové príležitosti pre vývoj liečebných postupov.
    sv_SE: Folding@home är ett distribuerat databehandlingsprojekt för att simulera proteindynamik, inklusive processen för proteinveckning och proteinernas rörelser som är inblandade i en mängd olika sjukdomar. Det sammanför medborgarforskare som frivilligt kör simuleringar av proteindynamik på sina persondatorer. Insikter från dessa data hjälper forskare att bättre förstå biologi och ger nya möjligheter att utveckla behandlingar.
    tr_TR: Folding@home, protein katlanma süreci ve çeşitli hastalıklarda rol oynayan proteinlerin hareketleri de dahil olmak üzere protein dinamiklerini simüle etmek için kullanılan dağıtık bir hesaplama projesidir. Kişisel bilgisayarlarında protein dinamikleri simülasyonları çalıştırmak için gönüllü olan vatandaş bilim insanlarını bir araya getiriyor. Bu verilerden elde edilen bilgiler, bilim insanlarının biyolojiyi daha iyi anlamalarına ve yeni tedavi yöntemleri geliştirme fırsatları sağlamalarına yardımcı oluyor.
    zh_CN: Folding@home 是一个模拟蛋白质动力学的分布式计算项目，研究内容包括蛋白质折叠过程，以及与多种疾病有关的蛋白质运动。它汇集自愿在个人电脑上运行模拟的公民科学家。这些数据帮助科学家更好地理解生物学，并为开发治疗方法提供新机会。
    zh_TW: Folding@home 是一個模擬蛋白質動力學的分散式計算專案，研究內容包括蛋白質摺疊過程，以及與多種疾病有關的蛋白質運動。它彙集自願在個人電腦上執行模擬的公民科學家。這些資料幫助科學家更好地理解生物學，併為開發治療方法提供新機會。
  tagline:
    en_US: A distributed computing project for simulating protein dynamics, including the process of protein folding and the movements of proteins implicated in a variety of diseases. It brings together citizen scientists who volunteer to run simulations of protein dynamics on their personal computers. Insights from this data are helping scientists to better understand biology, and providing new opportunities for developing therapeutics.
    ca_ES: Un projecte de computació distribuïda per simular la dinàmica de les proteïnes, incloent-hi el procés de plegament de proteïnes i els moviments de les proteïnes implicats en diverses malalties. Reuneix ciutadans científics que s'ofereixen voluntaris per executar simulacions de la dinàmica de les proteïnes als seus ordinadors personals. Els coneixements obtinguts d'aquestes dades ajuden els científics a comprendre millor la biologia i ofereixen noves oportunitats per desenvolupar teràpies.
    cs_CZ: Projekt distribuovaných výpočtů pro simulaci dynamiky proteinů, včetně procesu skládání proteinů a pohybů proteinů zapojených do různých onemocnění. Sdružuje občanské vědce, kteří se dobrovolně hlásí k provádění simulací dynamiky proteinů na svých osobních počítačích. Poznatky z těchto dat pomáhají vědcům lépe porozumět biologii a poskytují nové příležitosti pro vývoj léčiv.
    da_DK: Et distribueret databehandlingsprojekt til simulering af proteindynamik, herunder processen med proteinfoldning og proteiners bevægelser, der er involveret i en række sygdomme. Det samler borgerforskere, der frivilligt kører simuleringer af proteindynamik på deres personlige computere. Indsigt fra disse data hjælper forskere med bedre at forstå biologi og giver nye muligheder for at udvikle behandlinger.
    de_DE: Ein verteiltes Rechenprojekt zur Simulation der Proteindynamik, einschließlich der Proteinfaltung und der Bewegungen von Proteinen, die an verschiedenen Krankheiten beteiligt sind. Es bringt engagierte Bürgerwissenschaftler zusammen, die freiwillig Simulationen der Proteindynamik auf ihren PCs durchführen. Die gewonnenen Erkenntnisse helfen Wissenschaftlern, biologische Prozesse besser zu verstehen und eröffnen neue Möglichkeiten für die Entwicklung von Therapien.
    el_GR: Ένα έργο κατανεμημένων υπολογιστών για την προσομοίωση της δυναμικής των πρωτεϊνών, συμπεριλαμβανομένης της διαδικασίας αναδίπλωσης των πρωτεϊνών και των κινήσεων των πρωτεϊνών που εμπλέκονται σε μια ποικιλία ασθενειών. Φέρνει σε επαφή πολίτες επιστήμονες που προσφέρονται εθελοντικά να εκτελέσουν προσομοιώσεις της δυναμικής των πρωτεϊνών στους προσωπικούς τους υπολογιστές. Οι πληροφορίες από αυτά τα δεδομένα βοηθούν τους επιστήμονες να κατανοήσουν καλύτερα τη βιολογία και παρέχουν νέες ευκαιρίες για την ανάπτυξη θεραπευτικών μεθόδων.
    en_GB: A distributed computing project for simulating protein dynamics, including the process of protein folding and the movements of proteins implicated in a variety of diseases. It brings together citizen scientists who volunteer to run simulations of protein dynamics on their personal computers. Insights from this data are helping scientists to better understand biology, and providing new opportunities for developing therapeutics.
    es_ES: Un proyecto de computación distribuida para simular la dinámica de las proteínas, incluyendo el proceso de plegamiento proteico y los movimientos de las proteínas implicadas en diversas enfermedades. Reúne a científicos ciudadanos que se ofrecen como voluntarios para ejecutar simulaciones de la dinámica de las proteínas en sus ordenadores personales. Los conocimientos derivados de estos datos están ayudando a los científicos a comprender mejor la biología y ofreciendo nuevas oportunidades para el desarrollo de terapias.
    fr_FR: Un projet de calcul distribué pour la simulation de la dynamique des protéines, incluant le processus de repliement et les mouvements des protéines impliquées dans diverses maladies. Il rassemble des citoyens scientifiques bénévoles qui réalisent des simulations de dynamique protéique sur leurs ordinateurs personnels. Les données issues de ce projet aident les scientifiques à mieux comprendre la biologie et ouvrent de nouvelles perspectives pour le développement de thérapies.
    ga_IE: Tionscadal ríomhaireachta dáilte chun dinimic próitéine a insamhladh, lena n-áirítear an próiseas fillte próitéine agus gluaiseachtaí próitéiní a bhfuil baint acu le réimse galair. Tugann sé eolaithe saoránach le chéile a dhéanann obair dheonach chun insamhaltaí ar dhinimic próitéine a reáchtáil ar a ríomhairí pearsanta. Tá léargais ó na sonraí seo ag cabhrú le heolaithe tuiscint níos fearr a fháil ar an mbitheolaíocht, agus ag soláthar deiseanna nua chun teiripí a fhorbairt.
    hr_HR: Projekt distribuiranog računalstva za simulaciju dinamike proteina, uključujući proces savijanja proteina i kretanje proteina uključenih u razne bolesti. Okuplja građane znanstvenike koji se dobrovoljno javljaju za provođenje simulacija dinamike proteina na svojim osobnim računalima. Uvidi iz ovih podataka pomažu znanstvenicima da bolje razumiju biologiju i pružaju nove mogućnosti za razvoj terapije.
    hu_HU: Egy elosztott számítási projekt fehérjedinamika szimulálására, beleértve a fehérjehajtogatás folyamatát és a különféle betegségekkel összefüggő fehérjék mozgását. Összehozza azokat a civil tudósokat, akik önkéntesként fehérjedinamikai szimulációkat futtatnak személyi számítógépeiken. Az ezekből az adatokból származó információk segítik a tudósokat a biológia jobb megértésében, és új lehetőségeket kínálnak a terápiák fejlesztésére.
    it_IT: Un progetto di calcolo distribuito per la simulazione delle dinamiche proteiche, tra cui il processo di ripiegamento delle proteine e i movimenti delle proteine implicate in diverse patologie. Il progetto riunisce cittadini scienziati che si offrono volontari per eseguire simulazioni delle dinamiche proteiche sui propri computer personali. Le informazioni ricavate da questi dati aiutano gli scienziati a comprendere meglio la biologia e offrono nuove opportunità per lo sviluppo di terapie.
    ja_JP: タンパク質の折りたたみ過程や、様々な疾患に関与するタンパク質の動きなど、タンパク質の動態をシミュレーションするための分散コンピューティングプロジェクト。このプロジェクトでは、ボランティアとして個人のコンピュータ上でタンパク質動態のシミュレーションを実行する市民科学者たちが集結しています。このデータから得られる知見は、科学者が生物学をより深く理解するのに役立ち、新たな治療法開発の機会を提供しています。
    ko_KR: 단백질 접힘 과정과 다양한 질병과 관련된 단백질의 움직임을 포함한 단백질 역학을 시뮬레이션하는 분산 컴퓨팅 프로젝트입니다. 이 프로젝트는 자발적으로 개인용 컴퓨터에서 단백질 역학 시뮬레이션을 실행하는 시민 과학자들을 한데 모읍니다. 이 데이터에서 얻은 통찰력은 과학자들이 생물학을 더 잘 이해하고 새로운 치료법 개발을 위한 기회를 제공하는 데 도움이 되고 있습니다.
    ml_IN: പ്രോട്ടീൻ ഡൈനാമിക്സ് സിമുലേറ്റ് ചെയ്യുന്നതിനുള്ള ഒരു ഡിസ്ട്രിബ്യൂട്ടഡ് കമ്പ്യൂട്ടിംഗ് പ്രോജക്റ്റ്, ഇതിൽ പ്രോട്ടീൻ മടക്കൽ പ്രക്രിയയും വിവിധ രോഗങ്ങളിൽ ഉൾപ്പെട്ടിരിക്കുന്ന പ്രോട്ടീനുകളുടെ ചലനങ്ങളും ഉൾപ്പെടുന്നു. തങ്ങളുടെ പേഴ്സണൽ കമ്പ്യൂട്ടറുകളിൽ പ്രോട്ടീൻ ഡൈനാമിക്സിന്റെ സിമുലേഷനുകൾ പ്രവർത്തിപ്പിക്കാൻ സന്നദ്ധത പ്രകടിപ്പിക്കുന്ന പൗര ശാസ്ത്രജ്ഞരെ ഇത് ഒരുമിച്ച് കൊണ്ടുവരുന്നു. ഈ ഡാറ്റയിൽ നിന്നുള്ള ഉൾക്കാഴ്ചകൾ ശാസ്ത്രജ്ഞർക്ക് ജീവശാസ്ത്രത്തെ നന്നായി മനസ്സിലാക്കാൻ സഹായിക്കുകയും ചികിത്സാ രീതികൾ വികസിപ്പിക്കുന്നതിനുള്ള പുതിയ അവസരങ്ങൾ നൽകുകയും ചെയ്യുന്നു.
    nb_NO: Et distribuert databehandlingsprosjekt for simulering av proteindynamikk, inkludert prosessen med proteinfolding og bevegelsene til proteiner involvert i en rekke sykdommer. Det samler forskere som frivillig kjører simuleringer av proteindynamikk på sine personlige datamaskiner. Innsikt fra disse dataene hjelper forskere med å bedre forstå biologi og gir nye muligheter for å utvikle behandlinger.
    nl_NL: Een gedistribueerd computerproject voor het simuleren van eiwitdynamiek, waaronder het proces van eiwitvouwing en de bewegingen van eiwitten die betrokken zijn bij diverse ziekten. Het brengt burgerwetenschappers samen die vrijwillig simulaties van eiwitdynamiek uitvoeren op hun persoonlijke computers. De inzichten uit deze gegevens helpen wetenschappers om de biologie beter te begrijpen en bieden nieuwe mogelijkheden voor de ontwikkeling van therapieën.
    pl_PL: Projekt obliczeń rozproszonych, symulujący dynamikę białek, w tym proces ich fałdowania i ruchy białek zaangażowanych w różnorodne choroby. Zrzesza on naukowców-obywateli, którzy zgłoszą się na ochotnika do przeprowadzania symulacji dynamiki białek na swoich komputerach. Wiedza uzyskana z tych danych pomaga naukowcom lepiej zrozumieć biologię i stwarza nowe możliwości rozwoju terapii.
    pt_BR: Um projeto de computação distribuída para simulação da dinâmica de proteínas, incluindo o processo de dobramento proteico e os movimentos de proteínas envolvidas em diversas doenças. Ele reúne cientistas cidadãos que se voluntariam para executar simulações da dinâmica de proteínas em seus computadores pessoais. Os insights obtidos a partir desses dados estão ajudando os cientistas a compreender melhor a biologia e proporcionando novas oportunidades para o desenvolvimento de terapias.
    ro_RO: Un proiect de calcul distribuit pentru simularea dinamicii proteinelor, inclusiv procesul de pliere a proteinelor și mișcările proteinelor implicate într-o varietate de boli. Acesta reunește oameni de știință cetățeni care se oferă voluntari să ruleze simulări ale dinamicii proteinelor pe computerele lor personale. Informațiile obținute din aceste date îi ajută pe oamenii de știință să înțeleagă mai bine biologia și oferă noi oportunități pentru dezvoltarea de terapii.
    ru_RU: Проект распределенных вычислений для моделирования динамики белков, включая процесс сворачивания белков и движения белков, участвующих в развитии различных заболеваний. Он объединяет ученых-любителей, которые добровольно запускают моделирование динамики белков на своих персональных компьютерах. Полученные данные помогают ученым лучше понимать биологию и открывают новые возможности для разработки терапевтических средств.
    sk_SK: Projekt distribuovaných výpočtov na simuláciu dynamiky bielkovín vrátane procesu skladania bielkovín a pohybov bielkovín zapojených do rôznych ochorení. Spája občianskych vedcov, ktorí sa dobrovoľne prihlásia na simulácie dynamiky bielkovín na svojich osobných počítačoch. Poznatky z týchto údajov pomáhajú vedcom lepšie pochopiť biológiu a poskytujú nové príležitosti pre vývoj liečebných postupov.
    sv_SE: Ett distribuerat databehandlingsprojekt för att simulera proteindynamik, inklusive processen för proteinveckning och proteiners rörelser som är inblandade i en mängd olika sjukdomar. Det sammanför medborgarforskare som frivilligt kör simuleringar av proteindynamik på sina persondatorer. Insikter från dessa data hjälper forskare att bättre förstå biologi och ger nya möjligheter att utveckla behandlingar.
    tr_TR: Protein katlanma süreci ve çeşitli hastalıklarda rol oynayan proteinlerin hareketleri de dahil olmak üzere protein dinamiklerini simüle etmek için geliştirilmiş dağıtık hesaplama projesi. Bu proje, kişisel bilgisayarlarında protein dinamikleri simülasyonları çalıştırmak için gönüllü olan vatandaş bilim insanlarını bir araya getiriyor. Bu verilerden elde edilen bilgiler, bilim insanlarının biyolojiyi daha iyi anlamalarına ve yeni tedavi yöntemleri geliştirme fırsatları yaratmalarına yardımcı oluyor.
    zh_CN: 贡献计算资源，帮助研究蛋白质与疾病。
    zh_TW: 貢獻計算資源，幫助研究蛋白質與疾病。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/foldingathome-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/foldingathome-logo.png
  title:
    en_US: Foldingathome (LinuxServer.io)
    ca_ES: Foldingathome (LinuxServer.io)
    cs_CZ: Foldingathome (LinuxServer.io)
    da_DK: Foldingathome (LinuxServer.io)
    de_DE: Foldingathome (LinuxServer.io)
    el_GR: Foldingathome (LinuxServer.io)
    en_GB: Foldingathome (LinuxServer.io)
    es_ES: Foldingathome (LinuxServer.io)
    fr_FR: Foldingathome (LinuxServer.io)
    ga_IE: Foldingathome (LinuxServer.io)
    hr_HR: Foldingathome (LinuxServer.io)
    hu_HU: Foldingathome (LinuxServer.io)
    it_IT: Foldingathome (LinuxServer.io)
    ja_JP: Foldingathome (LinuxServer.io)
    ko_KR: Foldingathome (LinuxServer.io)
    ml_IN: Foldingathome (LinuxServer.io)
    nb_NO: Foldingathome (LinuxServer.io)
    nl_NL: Foldingathome (LinuxServer.io)
    pl_PL: Foldingathome (LinuxServer.io)
    pt_BR: Foldingathome (LinuxServer.io)
    ro_RO: Foldingathome (LinuxServer.io)
    ru_RU: Foldingathome (LinuxServer.io)
    sk_SK: Foldingathome (LinuxServer.io)
    sv_SE: Foldingathome (LinuxServer.io)
    tr_TR: Foldingathome (LinuxServer.io)
    zh_CN: Foldingathome（LinuxServer.io）
    zh_TW: Foldingathome（LinuxServer.io）
  category: Others
  id: wisdomsky.linuxserver.linuxserverfoldingathome
  port_map: '80'
  version: 8.5.6
