name: linuxserver-remmina
services:
  app:
    image: linuxserver/remmina:1.4.43@sha256:24fb0d51c02df48fcf584bd76866957841844cf0dafd81b37d92f82494af8624
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/remmina/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverremmina/assets/icon.png
  title:
    en_US: Remmina (LinuxServer.io)
    ca_ES: Remmina (LinuxServer.io)
    cs_CZ: Remmina (LinuxServer.io)
    da_DK: Remmina (LinuxServer.io)
    de_DE: Remmina (LinuxServer.io)
    el_GR: Remmina (LinuxServer.io)
    en_GB: Remmina (LinuxServer.io)
    es_ES: Remmina (LinuxServer.io)
    fr_FR: Remmina (LinuxServer.io)
    ga_IE: Remmina (LinuxServer.io)
    hr_HR: Remmina (LinuxServer.io)
    hu_HU: Remmina (LinuxServer.io)
    it_IT: Remmina (LinuxServer.io)
    ja_JP: Remmina (LinuxServer.io)
    ko_KR: Remmina (LinuxServer.io)
    ml_IN: Remmina (LinuxServer.io)
    nb_NO: Remmina (LinuxServer.io)
    nl_NL: Remmina (LinuxServer.io)
    pl_PL: Remmina (LinuxServer.io)
    pt_BR: Remmina (LinuxServer.io)
    ro_RO: Remmina (LinuxServer.io)
    ru_RU: Remmina (LinuxServer.io)
    sk_SK: Remmina (LinuxServer.io)
    sv_SE: Remmina (LinuxServer.io)
    tr_TR: Remmina (LinuxServer.io)
    zh_CN: Remmina（LinuxServer.io）
    zh_TW: Remmina（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverremmina
  port_map: '3000'
  version: 1.4.43
