name: linuxserver-wikijs
services:
  app:
    image: linuxserver/wikijs:2.5.314@sha256:a82146cdf29c70f54e4b9a4a6eaaa42baa045c9ecaa9e107f1af3dae86631d4c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_TYPE: ''
      DB_HOST: ''
      DB_PORT: ''
      DB_NAME: ''
      DB_USER: ''
      DB_PASS: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/wikijs/config
        target: /config
      - type: bind
        source: /DATA/AppData/wikijs/data
        target: /data
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverwikijs/assets/icon.svg
  title:
    en_US: Wikijs (LinuxServer.io)
    ca_ES: Wikijs (LinuxServer.io)
    cs_CZ: Wikijs (LinuxServer.io)
    da_DK: Wikijs (LinuxServer.io)
    de_DE: Wikijs (LinuxServer.io)
    el_GR: Wikijs (LinuxServer.io)
    en_GB: Wikijs (LinuxServer.io)
    es_ES: Wikijs (LinuxServer.io)
    fr_FR: Wikijs (LinuxServer.io)
    ga_IE: Wikijs (LinuxServer.io)
    hr_HR: Wikijs (LinuxServer.io)
    hu_HU: Wikijs (LinuxServer.io)
    it_IT: Wikijs (LinuxServer.io)
    ja_JP: Wikijs (LinuxServer.io)
    ko_KR: Wikijs (LinuxServer.io)
    ml_IN: Wikijs (LinuxServer.io)
    nb_NO: Wikijs (LinuxServer.io)
    nl_NL: Wikijs (LinuxServer.io)
    pl_PL: Wikijs (LinuxServer.io)
    pt_BR: Wikijs (LinuxServer.io)
    ro_RO: Wikijs (LinuxServer.io)
    ru_RU: Wikijs (LinuxServer.io)
    sk_SK: Wikijs (LinuxServer.io)
    sv_SE: Wikijs (LinuxServer.io)
    tr_TR: Wikijs (LinuxServer.io)
    zh_CN: Wikijs（LinuxServer.io）
    zh_TW: Wikijs（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverwikijs
  port_map: '3000'
  version: 2.5.314
