name: linuxserver-python
services:
  app:
    image: linuxserver/python:3.13.1@sha256:ebbb2f9e61f5af7f60d65f32743c0ac29e88d51a6f504c4e994eba3e29fea36d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/python/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverpython/assets/icon.svg
  title:
    en_US: Python
    zh_CN: Python
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserverpython
  version: 3.13.1
