name: linuxserver-plex-meta-manager
services:
  app:
    image: linuxserver/plex-meta-manager:1.21.1@sha256:6c5af3670b4cb210d10c6d953243214442c5ba0b9c5eab0a40f307fecff759ba
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PMM_CONFIG: ''
      PMM_TIME: ''
      PMM_RUN: ''
      PMM_TEST: ''
      PMM_NO_MISSING: ''
    volumes:
      - type: bind
        source: /DATA/AppData/plex-meta-manager/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverplexmetamanager/assets/icon.png
  title:
    en_US: Plex meta-manager
    zh_CN: Plex meta-manager
    ca_ES: Plex meta-manager
    cs_CZ: Plex meta-manager
    da_DK: Plex meta-manager
    de_DE: Plex meta-manager
    el_GR: Plex meta-manager
    en_GB: Plex meta-manager
    es_ES: Plex meta-manager
    fr_FR: Plex meta-manager
    ga_IE: Plex meta-manager
    hr_HR: Plex meta-manager
    hu_HU: Plex meta-manager
    it_IT: Plex meta-manager
    ja_JP: Plex meta-manager
    ko_KR: Plex meta-manager
    ml_IN: Plex meta-manager
    nb_NO: Plex meta-manager
    nl_NL: Plex meta-manager
    pl_PL: Plex meta-manager
    pt_BR: Plex meta-manager
    ro_RO: Plex meta-manager
    ru_RU: Plex meta-manager
    sk_SK: Plex meta-manager
    sv_SE: Plex meta-manager
    tr_TR: Plex meta-manager
    zh_TW: Plex meta-manager
  id: wisdomsky.linuxserver.linuxserverplexmetamanager
  version: 1.21.1
