name: linuxserver-sickchill
services:
  app:
    image: linuxserver/sickchill:2024.3.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /srv/lsio/sickchill/config
        target: /config
      - type: bind
        source: /srv/lsio/sickchill/downloads
        target: /downloads
      - type: bind
        source: /srv/lsio/sickchill/tv
        target: /tv
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Sickchill is an Automatic Video Library Manager for TV Shows. It watches for new episodes of your favorite shows, and when they are posted it does its magic.
  tagline:
    en_us: An Automatic Video Library Manager for TV Shows. It watches for new episodes of your favorite shows, and when they are posted it does its magic.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sickchill-banner.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sickchill-banner.png
  title:
    en_us: Sickchill
  category: LinuxServer.io
