name: linuxserver-digikam
services:
  app:
    image: linuxserver/digikam:8.8.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /srv/lsio/digikam/config
        target: /config
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: 'digiKam: Professional Photo Management with the Power of Open Source'
  tagline:
    en_us: 'digiKam: Professional Photo Management with the Power of Open Source'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/digikam.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/digikam.png
  title:
    en_us: Digikam
  category: LinuxServer.io
