name: linuxserver-ungoogled-chromium
services:
  app:
    image: linuxserver/ungoogled-chromium:153.0.8010
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: CHROME_CLI
          description:
            en_US: Specify one or multiple Chromium CLI flags, this string will be passed to the application in full. [OPTIONAL]
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ungoogled-chromium/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Ungoogled Chromium is Google Chromium, sans dependency on Google web services.
    zh_CN: Ungoogled Chromium 是移除了对 Google 网页服务依赖的 Google Chromium 版本。
  tagline:
    en_US: Google Chromium, sans dependency on Google web services.
    zh_CN: 移除 Google 网页服务依赖的 Chromium。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ungoogled-chromium-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ungoogled-chromium-logo.png
  title:
    en_US: Ungoogled chromium (LinuxServer.io)
    zh_CN: Ungoogled chromium（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverungoogledchromium
  port_map: '3000'
  version: 153.0.8010
