name: linuxserver-ngircd
services:
  app:
    image: linuxserver/ngircd:version-27-r1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 6667
        published: 6667
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ngircd/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverngircd/assets/icon.png
  title:
    en_US: Ngircd (LinuxServer.io)
    ca_ES: Ngircd (LinuxServer.io)
    cs_CZ: Ngircd (LinuxServer.io)
    da_DK: Ngircd (LinuxServer.io)
    de_DE: Ngircd (LinuxServer.io)
    el_GR: Ngircd (LinuxServer.io)
    en_GB: Ngircd (LinuxServer.io)
    es_ES: Ngircd (LinuxServer.io)
    fr_FR: Ngircd (LinuxServer.io)
    ga_IE: Ngircd (LinuxServer.io)
    hr_HR: Ngircd (LinuxServer.io)
    hu_HU: Ngircd (LinuxServer.io)
    it_IT: Ngircd (LinuxServer.io)
    ja_JP: Ngircd (LinuxServer.io)
    ko_KR: Ngircd (LinuxServer.io)
    ml_IN: Ngircd (LinuxServer.io)
    nb_NO: Ngircd (LinuxServer.io)
    nl_NL: Ngircd (LinuxServer.io)
    pl_PL: Ngircd (LinuxServer.io)
    pt_BR: Ngircd (LinuxServer.io)
    ro_RO: Ngircd (LinuxServer.io)
    ru_RU: Ngircd (LinuxServer.io)
    sk_SK: Ngircd (LinuxServer.io)
    sv_SE: Ngircd (LinuxServer.io)
    tr_TR: Ngircd (LinuxServer.io)
    zh_CN: Ngircd（LinuxServer.io）
    zh_TW: Ngircd（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverngircd
  port_map: '6667'
  version: version-27-r1
