name: linuxserver-qemu-static
services:
  app:
    image: linuxserver/qemu-static:10.0.2@sha256:ff476ccd2d378b43cefa899c328f001b98eaa969cffe6bcb405792b662c73546
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/qemu-static/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverqemustatic/assets/icon.png
  title:
    en_US: Qemu static (LinuxServer.io)
    ca_ES: Qemu static (LinuxServer.io)
    cs_CZ: Qemu static (LinuxServer.io)
    da_DK: Qemu static (LinuxServer.io)
    de_DE: Qemu static (LinuxServer.io)
    el_GR: Qemu static (LinuxServer.io)
    en_GB: Qemu static (LinuxServer.io)
    es_ES: Qemu static (LinuxServer.io)
    fr_FR: Qemu static (LinuxServer.io)
    ga_IE: Qemu static (LinuxServer.io)
    hr_HR: Qemu static (LinuxServer.io)
    hu_HU: Qemu static (LinuxServer.io)
    it_IT: Qemu static (LinuxServer.io)
    ja_JP: Qemu static (LinuxServer.io)
    ko_KR: Qemu static (LinuxServer.io)
    ml_IN: Qemu static (LinuxServer.io)
    nb_NO: Qemu static (LinuxServer.io)
    nl_NL: Qemu static (LinuxServer.io)
    pl_PL: Qemu static (LinuxServer.io)
    pt_BR: Qemu static (LinuxServer.io)
    ro_RO: Qemu static (LinuxServer.io)
    ru_RU: Qemu static (LinuxServer.io)
    sk_SK: Qemu static (LinuxServer.io)
    sv_SE: Qemu static (LinuxServer.io)
    tr_TR: Qemu static (LinuxServer.io)
    zh_CN: Qemu static（LinuxServer.io）
    zh_TW: Qemu static（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverqemustatic
  port_map: '80'
  version: 10.0.2
