name: linuxserver-adguardhome-sync
services:
  app:
    image: linuxserver/adguardhome-sync:0.9.3@sha256:09860a3a4f0c4bd0c8df7c37cf6d8a006b2675d138401a39e06e5770c2db2c47
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONFIGFILE: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/adguardhome-sync/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveradguardhomesync/assets/icon.png
  title:
    en_US: Adguardhome sync (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserveradguardhomesync
  port_map: '8080'
  version: 0.9.3
