name: linuxserver-jellyfin
services:
  app:
    image: linuxserver/jellyfin:12.1ubu2604-ls50
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      JELLYFIN_PublishedServerUrl: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: JELLYFIN_PublishedServerUrl
          description:
            en_US: Set the autodiscovery response domain or IP address, include http(s)://. [OPTIONAL]
    ports:
      - target: 8096
        published: 8096
        protocol: tcp
      - target: 8920
        published: 8920
        protocol: tcp
      - target: 7359
        published: 7359
        protocol: udp
      - target: 1900
        published: 1900
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/jellyfin/config
        target: /config
      - type: bind
        source: /DATA/AppData/jellyfin/data/tvshows
        target: /data/tvshows
      - type: bind
        source: /DATA/AppData/jellyfin/data/movies
        target: /data/movies
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: 'Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media. It is an alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices via multiple apps. Jellyfin is descended from Emby''s 3.5.2 release and ported to the .NET Core framework to enable full cross-platform support. There are no strings attached, no premium licenses or features, and no hidden agendas: just a team who want to build something better and work together to achieve it.'
    ca_ES: 'Jellyfin és un sistema multimèdia de programari lliure que et permet controlar la gestió i la transmissió en temps real dels teus continguts multimèdia. És una alternativa als propietaris Emby i Plex, per proporcionar contingut multimèdia des d''un servidor dedicat als dispositius dels usuaris finals a través de múltiples aplicacions. Jellyfin descendeix de la versió 3.5.2 d''Emby i s''ha portat al framework .NET Core per permetre la compatibilitat completa entre plataformes. No hi ha condicions, ni llicències ni funcions premium, ni agendes ocultes: només un equip que vol construir alguna cosa millor i treballar junts per aconseguir-ho.'
    cs_CZ: 'Jellyfin je svobodný mediální systém, který vám dává kontrolu nad správou a streamováním médií. Jedná se o alternativu k proprietárním systémům Emby a Plex, která umožňuje poskytovat média z dedikovaného serveru koncovým zařízením prostřednictvím více aplikací. Jellyfin je potomkem verze 3.5.2 od Emby a je portován na framework .NET Core, aby umožnil plnou podporu napříč platformami. Nejsou zde žádné podmínky, žádné prémiové licence ani funkce a žádné skryté úmysly: pouze tým, který chce vytvořit něco lepšího a spolupracuje na dosažení tohoto cíle.'
    da_DK: 'Jellyfin er et gratis softwaremediesystem, der giver dig kontrol over at administrere og streame dine medier. Det er et alternativ til de proprietære Emby og Plex, der leverer medier fra en dedikeret server til slutbrugerenheder via flere apps. Jellyfin er en efterkommer af Embys 3.5.2-udgivelse og porteret til .NET Core-frameworket for at muliggøre fuld understøttelse på tværs af platforme. Der er ingen forpligtelser, ingen premium-licenser eller -funktioner og ingen skjulte dagsordener: bare et team, der ønsker at bygge noget bedre og arbejde sammen for at opnå det.'
    de_DE: 'Jellyfin ist ein kostenloses Mediensystem, mit dem Sie Ihre Medien verwalten und streamen können. Es ist eine Alternative zu den proprietären Systemen Emby und Plex und ermöglicht die Bereitstellung von Medien von einem dedizierten Server auf Endgeräten über verschiedene Apps. Jellyfin basiert auf Emby Version 3.5.2 und wurde auf das .NET Core Framework portiert, um volle plattformübergreifende Unterstützung zu gewährleisten. Es gibt keine versteckten Kosten, keine Premium-Lizenzen oder -Funktionen und keine Hintergedanken: nur ein Team, das gemeinsam etwas Besseres entwickeln und dieses Ziel erreichen möchte.'
    el_GR: 'Το Jellyfin είναι ένα Σύστημα Πολυμέσων Ελεύθερου Λογισμικού που σας δίνει τον έλεγχο της διαχείρισης και της ροής των πολυμέσων σας. Είναι μια εναλλακτική λύση στα ιδιόκτητα Emby και Plex, για την παροχή πολυμέσων από έναν αποκλειστικό διακομιστή σε συσκευές τελικών χρηστών μέσω πολλαπλών εφαρμογών. Το Jellyfin προέρχεται από την έκδοση 3.5.2 του Emby και μεταφέρθηκε στο .NET Core framework για να επιτρέψει την πλήρη υποστήριξη μεταξύ πλατφορμών. Δεν υπάρχουν δεσμεύσεις, δεν υπάρχουν premium άδειες χρήσης ή λειτουργίες και δεν υπάρχουν κρυφές ατζέντες: απλώς μια ομάδα που θέλει να δημιουργήσει κάτι καλύτερο και να συνεργαστεί για να το πετύχει.'
    en_GB: 'Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media. It is an alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices via multiple apps. Jellyfin is descended from Emby''s 3.5.2 release and ported to the .Net Core framework to enable full cross-platform support. There are no strings attached, no premium licences or features, and no hidden agendas: just a team who want to build something better and work together to achieve it.'
    es_ES: 'Jellyfin es un sistema multimedia de software libre que te permite gestionar y reproducir tus contenidos multimedia. Es una alternativa a los sistemas propietarios Emby y Plex, que ofrece contenido multimedia desde un servidor dedicado a los dispositivos de los usuarios finales mediante diversas aplicaciones. Jellyfin deriva de la versión 3.5.2 de Emby y se ha adaptado al framework .NET Core para ofrecer compatibilidad multiplataforma completa. No hay condiciones ocultas, ni licencias ni funciones premium, ni intereses ocultos: solo un equipo que quiere crear algo mejor y trabajar en conjunto para lograrlo.'
    fr_FR: "Jellyfin est un système multimédia libre qui vous permet de gérer et de diffuser vos contenus. Alternative aux solutions propriétaires Emby et Plex, il permet de diffuser des contenus depuis un serveur dédié vers les appareils des utilisateurs via plusieurs applications. Dérivé de la version 3.5.2 d'Emby, Jellyfin a été porté sur le framework .NET Core pour une compatibilité multiplateforme optimale. Sans engagement, sans licences ni fonctionnalités payantes, et sans arrière-pensées\_: une équipe qui souhaite créer un système meilleur et travaille ensemble pour y parvenir."
    ga_IE: 'Is Córas Meán Bogearraí Saor in Aisce é Jellyfin a chuireann smacht ort ar bhainistiú agus ar shruthú do chuid meán. Is rogha eile é seachas Emby agus Plex dílseánaigh, chun meáin a sholáthar ó fhreastalaí tiomnaithe do ghléasanna úsáideora deiridh trí aipeanna iolracha. Is as scaoileadh 3.5.2 Emby a tháinig Jellyfin agus aistríodh é chuig creat .NET Core chun tacaíocht iomlán tras-ardáin a chumasú. Níl aon srianta ceangailte leis, níl aon cheadúnais ná gnéithe préimhe ann, agus níl aon chláir oibre i bhfolach: ach foireann ar mian leo rud éigin níos fearr a thógáil agus oibriú le chéile chun é sin a bhaint amach.'
    hr_HR: 'Jellyfin je besplatni medijski sustav koji vam daje kontrolu nad upravljanjem i streamingom vaših medija. To je alternativa vlasničkim Emby i Plex sustavima, za pružanje medija s namjenskog poslužitelja na uređaje krajnjih korisnika putem više aplikacija. Jellyfin je potomak Embyjeve verzije 3.5.2 i prenesen je na .NET Core framework kako bi se omogućila potpuna podrška za više platformi. Nema nikakvih uvjeta, premium licenci ili značajki, niti skrivenih namjera: samo tim koji želi izgraditi nešto bolje i surađivati kako bi to postigao.'
    hu_HU: 'A Jellyfin egy szabad szoftveres médiarendszer, amellyel a felhasználó kezelheti és streamelheti médiatartalmait. Alternatívát kínál a saját fejlesztésű Emby és Plex rendszerekhez képest, lehetővé téve, hogy egy dedikált szerverről több alkalmazáson keresztül biztosítson médiát a végfelhasználói eszközökhöz. A Jellyfin az Emby 3.5.2-es kiadásából származik, és a .NET Core keretrendszerre portolták a teljes platformfüggetlen támogatás érdekében. Nincsenek kötelezettségek, nincsenek prémium licencek vagy funkciók, és nincsenek rejtett szándékok: csak egy csapat, amely valami jobbat akar építeni, és együtt dolgoznak a megvalósításán.'
    it_IT: 'Jellyfin è un sistema multimediale open source che ti permette di gestire e riprodurre in streaming i tuoi contenuti. Rappresenta un''alternativa ai sistemi proprietari Emby e Plex, offrendo la possibilità di distribuire contenuti multimediali da un server dedicato ai dispositivi degli utenti finali tramite diverse app. Jellyfin deriva dalla versione 3.5.2 di Emby ed è stato adattato al framework .NET Core per garantire la piena compatibilità multipiattaforma. Non ci sono vincoli, licenze o funzionalità premium, né secondi fini: solo un team che desidera creare qualcosa di migliore e collabora per raggiungere questo obiettivo.'
    ja_JP: Jellyfinは、メディアの管理とストリーミングをユーザーが自由に行えるフリーソフトウェアのメディアシステムです。EmbyやPlexといった商用メディアシステムに代わるもので、専用サーバーから複数のアプリを介してエンドユーザーデバイスにメディアを提供します。JellyfinはEmbyの3.5.2リリースをベースに、.NET Coreフレームワークに移植することで、完全なクロスプラットフォーム対応を実現しています。制約やプレミアムライセンス、特別な機能、隠された意図は一切ありません。より良いものを作り、それを実現するために協力し合うチームがここにあります。
    ko_KR: Jellyfin은 미디어 관리 및 스트리밍을 완벽하게 제어할 수 있도록 해주는 무료 소프트웨어 미디어 시스템입니다. 독점 소프트웨어인 Emby와 Plex의 대안으로, 전용 서버에서 다양한 앱을 통해 최종 사용자 기기로 미디어를 제공합니다. Jellyfin은 Emby 3.5.2 버전을 기반으로 개발되었으며, 완벽한 크로스 플랫폼 지원을 위해 .NET Core 프레임워크로 포팅되었습니다. 어떠한 제약이나 유료 라이선스, 숨겨진 의도도 없습니다. 그저 더 나은 것을 만들고 싶어 하는 팀이 함께 협력하여 개발했을 뿐입니다.
    ml_IN: 'നിങ്ങളുടെ മീഡിയ കൈകാര്യം ചെയ്യുന്നതിലും സ്ട്രീം ചെയ്യുന്നതിലും നിങ്ങൾക്ക് നിയന്ത്രണം നൽകുന്ന ഒരു സ്വതന്ത്ര സോഫ്റ്റ്‌വെയർ മീഡിയ സിസ്റ്റമാണ് ജെല്ലിഫിൻ. ഒന്നിലധികം ആപ്പുകൾ വഴി ഒരു സമർപ്പിത സെർവറിൽ നിന്ന് അന്തിമ ഉപയോക്തൃ ഉപകരണങ്ങളിലേക്ക് മീഡിയ നൽകുന്നതിനുള്ള പ്രൊപ്രൈറ്ററി എംബി, പ്ലെക്സ് എന്നിവയ്ക്ക് പകരമാണിത്. എംബിയുടെ 3.5.2 റിലീസിൽ നിന്ന് ഉരുത്തിരിഞ്ഞതും പൂർണ്ണ ക്രോസ്-പ്ലാറ്റ്‌ഫോം പിന്തുണ പ്രാപ്തമാക്കുന്നതിനായി .NET കോർ ഫ്രെയിംവർക്കിലേക്ക് പോർട്ട് ചെയ്തതുമാണ് ജെല്ലിഫിൻ. യാതൊരു സ്ട്രിംഗുകളും ഘടിപ്പിച്ചിട്ടില്ല, പ്രീമിയം ലൈസൻസുകളോ സവിശേഷതകളോ ഇല്ല, മറഞ്ഞിരിക്കുന്ന അജണ്ടകളുമില്ല: മികച്ച എന്തെങ്കിലും നിർമ്മിക്കാനും അത് നേടുന്നതിന് ഒരുമിച്ച് പ്രവർത്തിക്കാനും ആഗ്രഹിക്കുന്ന ഒരു ടീം മാത്രം.'
    nb_NO: 'Jellyfin er et gratis mediesystem som gir deg kontroll over administrasjon og strømming av media. Det er et alternativ til de proprietære Emby og Plex, for å levere media fra en dedikert server til sluttbrukerenheter via flere apper. Jellyfin er en etterkommer av Embys 3.5.2-utgivelse og portet til .NET Core-rammeverket for å muliggjøre full plattformuavhengig støtte. Det er ingen betingelser, ingen premiumlisenser eller -funksjoner, og ingen skjulte agendaer: bare et team som ønsker å bygge noe bedre og jobbe sammen for å oppnå det.'
    nl_NL: 'Jellyfin is een gratis mediasysteem waarmee u zelf de controle hebt over het beheren en streamen van uw media. Het is een alternatief voor de propriëtaire systemen Emby en Plex en biedt media vanaf een dedicated server aan eindgebruikersapparaten via verschillende apps. Jellyfin is gebaseerd op Emby versie 3.5.2 en is geporteerd naar het .NET Core framework voor volledige platformonafhankelijke ondersteuning. Er zijn geen verborgen kosten, geen premium licenties of functies en geen agenda''s: gewoon een team dat iets beters wil bouwen en samenwerkt om dat te bereiken.'
    pl_PL: 'Jellyfin to darmowy system multimedialny, który pozwala zarządzać multimediami i przesyłać je strumieniowo. Stanowi alternatywę dla zastrzeżonych systemów Emby i Plex, umożliwiając dostarczanie multimediów z dedykowanego serwera do urządzeń użytkowników końcowych za pośrednictwem wielu aplikacji. Jellyfin jest następcą wersji Emby 3.5.2 i przeniesiony na platformę .NET Core, aby zapewnić pełną obsługę wielu platform. Nie ma żadnych zobowiązań, licencji premium ani funkcji, ani ukrytych celów: po prostu zespół, który chce stworzyć coś lepszego i wspólnie dążyć do jego osiągnięcia.'
    pt_BR: 'Jellyfin é um sistema de mídia de software livre que coloca você no controle do gerenciamento e streaming de suas mídias. É uma alternativa aos softwares proprietários Emby e Plex, fornecendo conteúdo de um servidor dedicado para dispositivos do usuário final por meio de múltiplos aplicativos. O Jellyfin é derivado da versão 3.5.2 do Emby e foi portado para o framework .NET Core para permitir suporte multiplataforma completo. Não há pegadinhas, licenças ou recursos premium, nem segundas intenções: apenas uma equipe que quer construir algo melhor e trabalhar em conjunto para alcançar esse objetivo.'
    ro_RO: 'Jellyfin este un sistem media software liber care vă oferă controlul asupra gestionării și redării în flux a conținutului media. Este o alternativă la Emby și Plex, care oferă conținut media de pe un server dedicat către dispozitivele utilizatorilor finali prin intermediul mai multor aplicații. Jellyfin este o versiune derivată din versiunea 3.5.2 a Emby și portată pe framework-ul .NET Core pentru a permite suport complet multi-platformă. Nu există obligații, licențe sau funcții premium și nicio agendă ascunsă: doar o echipă care dorește să construiască ceva mai bun și lucrează împreună pentru a realiza acest lucru.'
    ru_RU: 'Jellyfin — это бесплатная система управления медиаконтентом, которая позволяет вам контролировать и транслировать ваши медиафайлы. Это альтернатива проприетарным системам Emby и Plex, предоставляющая доступ к медиафайлам с выделенного сервера на устройства конечных пользователей через различные приложения. Jellyfin является потомком Emby версии 3.5.2 и портирован на платформу .NET Core для обеспечения полной кроссплатформенной поддержки. Никаких скрытых условий, никаких платных лицензий или функций, никаких тайных планов: просто команда, которая хочет создать нечто лучшее и работает вместе для достижения этой цели.'
    sk_SK: 'Jellyfin je mediálny systém s voľným softvérom, ktorý vám dáva kontrolu nad správou a streamovaním vašich médií. Je to alternatíva k proprietárnym systémom Emby a Plex, ktorá poskytuje médiá z dedikovaného servera do zariadení koncových používateľov prostredníctvom viacerých aplikácií. Jellyfin je potomkom verzie Emby 3.5.2 a je portovaný do frameworku .NET Core, aby umožnil plnú podporu naprieč platformami. Nie sú s ním žiadne záväzky, žiadne prémiové licencie ani funkcie a žiadne skryté zámery: len tím, ktorý chce vytvoriť niečo lepšie a spolupracuje na jeho dosiahnutí.'
    sv_SE: 'Jellyfin är ett fritt programvarubaserad mediesystem som ger dig kontroll över att hantera och strömma dina media. Det är ett alternativ till de proprietära Emby och Plex, för att tillhandahålla media från en dedikerad server till slutanvändarenheter via flera appar. Jellyfin härstammar från Embys 3.5.2-version och portas till .NET Core-ramverket för att möjliggöra fullt plattformsoberoende stöd. Det finns inga villkor, inga premiumlicenser eller funktioner och inga dolda agendor: bara ett team som vill bygga något bättre och arbeta tillsammans för att uppnå det.'
    tr_TR: 'Jellyfin, medyanızı yönetme ve yayınlama konusunda size kontrol imkanı sağlayan ücretsiz bir yazılım medya sistemidir. Özel bir sunucudan son kullanıcı cihazlarına birden fazla uygulama aracılığıyla medya sağlamak için tescilli Emby ve Plex''e bir alternatiftir. Jellyfin, Emby''nin 3.5.2 sürümünden türetilmiş ve tam platformlar arası destek sağlamak için .NET Core çerçevesine taşınmıştır. Hiçbir şart, premium lisans veya özellik yok, gizli gündemler de yok: sadece daha iyi bir şey inşa etmek ve bunu başarmak için birlikte çalışan bir ekip var.'
    zh_CN: Jellyfin 是一套自由软件媒体系统，让你自主掌控媒体管理和串流。它是专有软件 Emby 和 Plex 的替代方案，可通过多种客户端将专用服务器上的媒体提供给终端设备。Jellyfin 源自 Emby 3.5.2，并移植到 .NET Core 框架以实现完整的跨平台支持。它没有附加条件、付费高级许可证或隐藏功能限制，也没有隐藏目的，只有一个希望共同打造更好软件的团队。
    zh_TW: Jellyfin 是一套自由軟體媒體系統，讓你自主掌控媒體管理和串流。它是專有軟體 Emby 和 Plex 的替代方案，可透過多種客戶端將專用伺服器上的媒體提供給終端裝置。Jellyfin 源自 Emby 3.5.2，並移植到 .NET Core 框架以實現完整的跨平臺支援。它沒有附加條件、付費高階許可證或隱藏功能限制，也沒有隱藏目的，只有一個希望共同打造更好軟體的團隊。
  tagline:
    en_US: 'A Free Software Media System that puts you in control of managing and streaming your media. It is an alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices via multiple apps. Jellyfin is descended from Emby''s 3. 5. 2 release and ported to the. NET Core framework to enable full cross-platform support. There are no strings attached, no premium licenses or features, and no hidden agendas: just a team who want to build something better and work together to achieve it.'
    ca_ES: 'Un sistema multimèdia de programari lliure que us permet controlar la gestió i la transmissió en temps real dels vostres continguts multimèdia. És una alternativa als propietaris Emby i Plex, per proporcionar contingut multimèdia des d''un servidor dedicat als dispositius de l''usuari final a través de múltiples aplicacions. Jellyfin descendeix de la versió 3.5.2 d''Emby i s''ha portat al framework .NET Core per permetre la compatibilitat completa entre plataformes. No hi ha condicions, ni llicències ni funcions premium, ni agendes ocultes: només un equip que vol construir alguna cosa millor i treballar junts per aconseguir-ho.'
    cs_CZ: 'Mediální systém s volným softwarem, který vám dává kontrolu nad správou a streamováním médií. Jedná se o alternativu k proprietárním systémům Emby a Plex, která umožňuje poskytovat média z dedikovaného serveru koncovým zařízením prostřednictvím více aplikací. Jellyfin je potomkem verze 3.5.2 od Emby a je portován na framework .NET Core, aby umožnil plnou podporu napříč platformami. Nejsou zde žádné podmínky, žádné prémiové licence ani funkce a žádné skryté úmysly: pouze tým, který chce vytvořit něco lepšího a spolupracuje na dosažení tohoto cíle.'
    da_DK: 'Et gratis softwaremediesystem, der giver dig kontrol over at administrere og streame dine medier. Det er et alternativ til de proprietære Emby og Plex, der leverer medier fra en dedikeret server til slutbrugerenheder via flere apps. Jellyfin er en efterkommer af Embys 3.5.2-udgivelse og porteret til .NET Core-frameworket for at muliggøre fuld understøttelse på tværs af platforme. Der er ingen forpligtelser, ingen premium-licenser eller -funktioner og ingen skjulte dagsordener: bare et team, der ønsker at bygge noget bedre og arbejde sammen for at opnå det.'
    de_DE: 'Jellyfin ist ein kostenloses Mediensystem, mit dem Sie Ihre Medien verwalten und streamen können. Es ist eine Alternative zu den proprietären Systemen Emby und Plex und ermöglicht die Bereitstellung von Medien von einem dedizierten Server auf Endgeräten über verschiedene Apps. Jellyfin basiert auf Emby Version 3.5.2 und wurde auf das .NET Core Framework portiert, um volle plattformübergreifende Unterstützung zu gewährleisten. Es gibt keine versteckten Kosten, keine Premium-Lizenzen oder -Funktionen und keine Hintergedanken: nur ein Team, das gemeinsam etwas Besseres entwickeln und dieses Ziel erreichen möchte.'
    el_GR: 'Ένα Σύστημα Πολυμέσων Ελεύθερου Λογισμικού που σας δίνει τον έλεγχο της διαχείρισης και της ροής των πολυμέσων σας. Είναι μια εναλλακτική λύση στα ιδιόκτητα Emby και Plex, για την παροχή πολυμέσων από έναν αποκλειστικό διακομιστή σε συσκευές τελικών χρηστών μέσω πολλαπλών εφαρμογών. Το Jellyfin προέρχεται από την έκδοση 3.5.2 του Emby και μεταφέρθηκε στο .NET Core framework για να επιτρέψει την πλήρη υποστήριξη μεταξύ πλατφορμών. Δεν υπάρχουν δεσμεύσεις, δεν υπάρχουν premium άδειες χρήσης ή λειτουργίες και δεν υπάρχουν κρυφές ατζέντες: απλώς μια ομάδα που θέλει να δημιουργήσει κάτι καλύτερο και να συνεργαστεί για να το πετύχει.'
    en_GB: 'A Free Software Media System that puts you in control of managing and streaming your media. It is an alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices via multiple apps. Jellyfin is descended from Emby''s 3. 5. 2 release and ported to the. Net Core framework to enable full cross-platform support. There are no strings attached, no premium licences or features, and no hidden agendas: just a team who want to build something better and work together to achieve it.'
    es_ES: 'Jellyfin es un sistema de software libre que te permite gestionar y reproducir tus contenidos multimedia. Es una alternativa a los sistemas propietarios Emby y Plex, que ofrece contenido desde un servidor dedicado a los dispositivos de los usuarios finales mediante diversas aplicaciones. Jellyfin deriva de la versión 3.5.2 de Emby y se ha adaptado al framework .NET Core para ofrecer compatibilidad multiplataforma completa. No hay condiciones ocultas, ni licencias ni funciones premium, ni intereses ocultos: solo un equipo que quiere crear algo mejor y trabajar en conjunto para lograrlo.'
    fr_FR: "Jellyfin est un système multimédia libre qui vous permet de gérer et de diffuser vos contenus. Alternative aux solutions propriétaires Emby et Plex, il permet de diffuser des médias depuis un serveur dédié vers les appareils des utilisateurs via plusieurs applications. Dérivé de la version 3.5.2 d'Emby, Jellyfin a été porté sur le framework .NET Core pour une compatibilité multiplateforme optimale. Sans engagement, sans licences ni fonctionnalités payantes, et sans arrière-pensées\_: une équipe qui souhaite créer un système meilleur et travaille ensemble pour y parvenir."
    ga_IE: 'Córas Meán Bogearraí Saor in Aisce a chuireann smacht ort ar bhainistiú agus ar shruthú do chuid meán. Is rogha eile é seachas Emby agus Plex dílseánaigh, chun meáin a sholáthar ó fhreastalaí tiomnaithe do ghléasanna úsáideora deiridh trí aipeanna iolracha. Is as scaoileadh 3.5.2 Emby a tháinig Jellyfin agus aistríodh é chuig creat .NET Core chun tacaíocht iomlán tras-ardáin a chumasú. Níl aon srianta ceangailte, gan aon cheadúnais ná gnéithe préimhe, agus gan aon chláir oibre i bhfolach: ach foireann ar mian leo rud éigin níos fearr a thógáil agus oibriú le chéile chun é a bhaint amach.'
    hr_HR: 'Besplatni softverski medijski sustav koji vam daje kontrolu nad upravljanjem i streamingom vaših medija. To je alternativa vlasničkim Emby i Plex platformama, koja omogućuje prijenos medija s namjenskog poslužitelja na uređaje krajnjih korisnika putem više aplikacija. Jellyfin je potomak Embyjeve verzije 3.5.2 i prenesen je na .NET Core framework kako bi se omogućila potpuna podrška za više platformi. Nema nikakvih uvjeta, premium licenci ili značajki, niti skrivenih namjera: samo tim koji želi izgraditi nešto bolje i surađivati kako bi to postigao.'
    hu_HU: 'Egy szabad szoftveres médiarendszer, amellyel a te kezedbe veheted a médiatartalmaid kezelését és streamelését. Alternatívát kínál a saját fejlesztésű Emby és Plex rendszerekhez, lehetővé téve, hogy egy dedikált szerverről több alkalmazáson keresztül biztosítson médiát a végfelhasználói eszközökhöz. A Jellyfin az Emby 3.5.2-es kiadásából származik, és a .NET Core keretrendszerre portolták a teljes platformfüggetlen támogatás érdekében. Nincsenek kötelezettségek, nincsenek prémium licencek vagy funkciók, és nincsenek rejtett szándékok: csak egy csapat, akik valami jobbat akarnak építeni, és együtt dolgoznak a megvalósításán.'
    it_IT: 'Un sistema multimediale gratuito che ti permette di gestire e riprodurre in streaming i tuoi contenuti. Rappresenta un''alternativa ai sistemi proprietari Emby e Plex, offrendo la possibilità di distribuire contenuti multimediali da un server dedicato ai dispositivi degli utenti finali tramite diverse app. Jellyfin deriva dalla versione 3.5.2 di Emby ed è stato adattato al framework .NET Core per garantire la piena compatibilità multipiattaforma. Non ci sono vincoli, licenze o funzionalità premium a pagamento, né secondi fini: solo un team che desidera creare qualcosa di migliore e lavorare insieme per raggiungere questo obiettivo.'
    ja_JP: メディアの管理とストリーミングをユーザーが自由にコントロールできるフリーソフトウェアメディアシステムです。EmbyやPlexといった商用ソフトウェアに代わる選択肢として、専用サーバーから複数のアプリを介してエンドユーザーデバイスにメディアを提供します。JellyfinはEmbyの3.5.2リリースをベースに、.NET Coreフレームワークに移植することで、完全なクロスプラットフォーム対応を実現しました。制約やプレミアムライセンス、特別な機能、隠された意図は一切ありません。より良いものを作り、それを実現するために協力し合うチームがここにあります。
    ko_KR: Jellyfin은 사용자가 미디어를 관리하고 스트리밍할 수 있도록 해주는 무료 소프트웨어 미디어 시스템입니다. 독점 소프트웨어인 Emby와 Plex의 대안으로, 전용 서버에서 여러 앱을 통해 최종 사용자 기기로 미디어를 제공합니다. Jellyfin은 Emby 3.5.2 버전을 기반으로 개발되었으며, .NET Core 프레임워크로 포팅되어 완벽한 크로스 플랫폼을 지원합니다. 어떠한 제약이나 유료 라이선스, 숨겨진 의도도 없습니다. 그저 더 나은 것을 만들고 싶어 하는 팀이 함께 노력하는 것뿐입니다.
    ml_IN: 'നിങ്ങളുടെ മീഡിയ കൈകാര്യം ചെയ്യുന്നതിലും സ്ട്രീം ചെയ്യുന്നതിലും നിങ്ങൾക്ക് നിയന്ത്രണം നൽകുന്ന ഒരു സ്വതന്ത്ര സോഫ്റ്റ്‌വെയർ മീഡിയ സിസ്റ്റം. ഒന്നിലധികം ആപ്പുകൾ വഴി ഒരു സമർപ്പിത സെർവറിൽ നിന്ന് അന്തിമ ഉപയോക്തൃ ഉപകരണങ്ങളിലേക്ക് മീഡിയ നൽകുന്നതിനുള്ള പ്രൊപ്രൈറ്ററി എംബി, പ്ലെക്സ് എന്നിവയ്ക്ക് പകരമാണിത്. ജെല്ലിഫിൻ എംബിയുടെ 3. 5. 2 റിലീസിൽ നിന്ന് ഉരുത്തിരിഞ്ഞതാണ്, കൂടാതെ പൂർണ്ണ ക്രോസ്-പ്ലാറ്റ്‌ഫോം പിന്തുണ പ്രാപ്തമാക്കുന്നതിനായി നെറ്റ് കോർ ഫ്രെയിംവർക്കിലേക്ക് പോർട്ട് ചെയ്‌തിരിക്കുന്നു. യാതൊരു സ്ട്രിംഗുകളും ഘടിപ്പിച്ചിട്ടില്ല, പ്രീമിയം ലൈസൻസുകളോ സവിശേഷതകളോ ഇല്ല, മറഞ്ഞിരിക്കുന്ന അജണ്ടകളുമില്ല: മികച്ച എന്തെങ്കിലും നിർമ്മിക്കാനും അത് നേടുന്നതിന് ഒരുമിച്ച് പ്രവർത്തിക്കാനും ആഗ്രഹിക്കുന്ന ഒരു ടീം മാത്രം.'
    nb_NO: 'Et gratis programvarebasert mediesystem som gir deg kontroll over administrasjon og strømming av media. Det er et alternativ til de proprietære Emby og Plex, for å levere media fra en dedikert server til sluttbrukerenheter via flere apper. Jellyfin er en etterkommer av Embys 3.5.2-utgivelse og portert til .NET Core-rammeverket for å muliggjøre full plattformuavhengig støtte. Det er ingen betingelser, ingen premiumlisenser eller -funksjoner, og ingen skjulte agendaer: bare et team som ønsker å bygge noe bedre og jobbe sammen for å oppnå det.'
    nl_NL: 'Een gratis mediasysteem waarmee u zelf de controle hebt over het beheren en streamen van uw media. Het is een alternatief voor de propriëtaire systemen Emby en Plex, en biedt media vanaf een dedicated server aan eindgebruikersapparaten via verschillende apps. Jellyfin is gebaseerd op Emby''s versie 3.5.2 en is geporteerd naar het .NET Core-framework voor volledige platformonafhankelijke ondersteuning. Er zijn geen addertjes onder het gras, geen premium licenties of functies, en geen verborgen agenda''s: gewoon een team dat iets beters wil bouwen en samenwerkt om dat te bereiken.'
    pl_PL: 'Wolny System Multimedialny, który daje Ci kontrolę nad zarządzaniem i strumieniowaniem multimediów. Stanowi alternatywę dla zastrzeżonych systemów Emby i Plex, umożliwiając dostarczanie multimediów z dedykowanego serwera do urządzeń użytkowników końcowych za pośrednictwem wielu aplikacji. Jellyfin jest następcą wersji Emby 3.5.2 i przeniesiony na platformę .NET Core, aby zapewnić pełną obsługę wielu platform. Nie ma żadnych zobowiązań, licencji premium ani funkcji, ani ukrytych celów: po prostu zespół, który chce stworzyć coś lepszego i wspólnie dążyć do jego osiągnięcia.'
    pt_BR: 'Um sistema de mídia de software livre que coloca você no controle do gerenciamento e streaming de suas mídias. É uma alternativa aos softwares proprietários Emby e Plex, fornecendo conteúdo de um servidor dedicado para dispositivos do usuário final por meio de múltiplos aplicativos. O Jellyfin descende da versão 3.5.2 do Emby e foi portado para o framework .NET Core para permitir suporte multiplataforma completo. Não há pegadinhas, licenças ou recursos premium, nem segundas intenções: apenas uma equipe que quer construir algo melhor e trabalhar em conjunto para alcançar esse objetivo.'
    ro_RO: 'Un sistem media software liber care vă oferă controlul asupra gestionării și redării în flux a conținutului media. Este o alternativă la Emby și Plex, care oferă conținut media de pe un server dedicat către dispozitivele utilizatorilor finali prin intermediul mai multor aplicații. Jellyfin este o versiune derivată din versiunea 3.5.2 a Emby și portată la framework-ul .NET Core pentru a permite suport complet multi-platformă. Nu există obligații, licențe sau funcții premium și nicio agendă ascunsă: doar o echipă care dorește să construiască ceva mai bun și lucrează împreună pentru a realiza acest lucru.'
    ru_RU: 'Бесплатная система управления медиаконтентом, позволяющая контролировать воспроизведение и потоковую передачу ваших медиафайлов. Это альтернатива проприетарным системам Emby и Plex, предоставляющая доступ к медиафайлам с выделенного сервера на устройства конечных пользователей через различные приложения. Jellyfin является производной от Emby версии 3.5.2 и портирована на платформу .NET Core для обеспечения полной кроссплатформенной поддержки. Никаких скрытых условий, никаких платных лицензий или функций, никаких тайных планов: просто команда, которая хочет создать нечто лучшее и работает вместе для достижения этой цели.'
    sk_SK: 'Mediálny systém s voľným softvérom, ktorý vám dáva kontrolu nad správou a streamovaním vašich médií. Je to alternatíva k proprietárnym systémom Emby a Plex, ktorá poskytuje médiá z dedikovaného servera do zariadení koncových používateľov prostredníctvom viacerých aplikácií. Jellyfin je potomkom verzie 3.5.2 od Emby a je portovaný do frameworku .NET Core, aby umožnil plnú podporu naprieč platformami. Nie sú s ním spojené žiadne podmienky, žiadne prémiové licencie ani funkcie a žiadne skryté zámery: len tím, ktorý chce vytvoriť niečo lepšie a spolupracuje na tom, aby to dosiahol.'
    sv_SE: 'Ett fritt programvarusystem för media som ger dig kontroll över att hantera och strömma dina media. Det är ett alternativ till de proprietära Emby och Plex, för att tillhandahålla media från en dedikerad server till slutanvändarenheter via flera appar. Jellyfin härstammar från Embys 3.5.2-utgåva och portas till .NET Core-ramverket för att möjliggöra fullt plattformsoberoende stöd. Det finns inga villkor, inga premiumlicenser eller funktioner och inga dolda agendor: bara ett team som vill bygga något bättre och arbeta tillsammans för att uppnå det.'
    tr_TR: 'Medya dosyalarınızı yönetmenizi ve yayınlamanızı kontrol etmenizi sağlayan ücretsiz bir yazılım medya sistemi. Özel bir sunucudan son kullanıcı cihazlarına birden fazla uygulama aracılığıyla medya sağlamak için tescilli Emby ve Plex''e bir alternatiftir. Jellyfin, Emby''nin 3.5.2 sürümünden türetilmiş ve tam platformlar arası destek sağlamak için .NET Core çerçevesine taşınmıştır. Hiçbir koşul, premium lisans veya özellik yok, gizli gündem yok: sadece daha iyi bir şey inşa etmek ve bunu başarmak için birlikte çalışmak isteyen bir ekip var.'
    zh_CN: 自由、开源的个人媒体管理与串流系统。
    zh_TW: 自由、開源的個人媒體管理與串流系統。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jellyfin-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jellyfin-logo.png
  title:
    en_US: Jellyfin (LinuxServer.io)
    ca_ES: Jellyfin (LinuxServer.io)
    cs_CZ: Jellyfin (LinuxServer.io)
    da_DK: Jellyfin (LinuxServer.io)
    de_DE: Jellyfin (LinuxServer.io)
    el_GR: Jellyfin (LinuxServer.io)
    en_GB: Jellyfin (LinuxServer.io)
    es_ES: Jellyfin (LinuxServer.io)
    fr_FR: Jellyfin (LinuxServer.io)
    ga_IE: Jellyfin (LinuxServer.io)
    hr_HR: Jellyfin (LinuxServer.io)
    hu_HU: Jellyfin (LinuxServer.io)
    it_IT: Jellyfin (LinuxServer.io)
    ja_JP: Jellyfin (LinuxServer.io)
    ko_KR: Jellyfin (LinuxServer.io)
    ml_IN: Jellyfin (LinuxServer.io)
    nb_NO: Jellyfin (LinuxServer.io)
    nl_NL: Jellyfin (LinuxServer.io)
    pl_PL: Jellyfin (LinuxServer.io)
    pt_BR: Jellyfin (LinuxServer.io)
    ro_RO: Jellyfin (LinuxServer.io)
    ru_RU: Jellyfin (LinuxServer.io)
    sk_SK: Jellyfin (LinuxServer.io)
    sv_SE: Jellyfin (LinuxServer.io)
    tr_TR: Jellyfin (LinuxServer.io)
    zh_CN: Jellyfin（LinuxServer.io）
    zh_TW: Jellyfin（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverjellyfin
  version: 12.1ubu2604-ls50
