name: linuxserver-melonds
services:
  app:
    image: linuxserver/melonds:1.1.20260907@sha256:90aa2297c916d2313b83b5fd0ce4ed774ce6c371d4631e2f742d291b114f09c6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/melonds/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermelonds/assets/icon.png
  title:
    en_US: Melonds (LinuxServer.io)
    ca_ES: Melonds (LinuxServer.io)
    cs_CZ: Melonds (LinuxServer.io)
    da_DK: Melonds (LinuxServer.io)
    de_DE: Melonds (LinuxServer.io)
    el_GR: Melonds (LinuxServer.io)
    en_GB: Melonds (LinuxServer.io)
    es_ES: Melonds (LinuxServer.io)
    fr_FR: Melonds (LinuxServer.io)
    ga_IE: Melonds (LinuxServer.io)
    hr_HR: Melonds (LinuxServer.io)
    hu_HU: Melonds (LinuxServer.io)
    it_IT: Melonds (LinuxServer.io)
    ja_JP: Melonds (LinuxServer.io)
    ko_KR: Melonds (LinuxServer.io)
    ml_IN: Melonds (LinuxServer.io)
    nb_NO: Melonds (LinuxServer.io)
    nl_NL: Melonds (LinuxServer.io)
    pl_PL: Melonds (LinuxServer.io)
    pt_BR: Melonds (LinuxServer.io)
    ro_RO: Melonds (LinuxServer.io)
    ru_RU: Melonds (LinuxServer.io)
    sk_SK: Melonds (LinuxServer.io)
    sv_SE: Melonds (LinuxServer.io)
    tr_TR: Melonds (LinuxServer.io)
    zh_CN: Melonds（LinuxServer.io）
    zh_TW: Melonds（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservermelonds
  port_map: '3000'
  version: 1.1.20260907
