name: linuxserver-calibre
services:
  app:
    image: linuxserver/calibre:9.15.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
      CLI_ARGS: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 8181
        published: 8181
        protocol: tcp
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/calibre/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservercalibre/assets/icon.png
  title:
    en_US: Calibre (LinuxServer.io)
    ca_ES: Calibre (LinuxServer.io)
    cs_CZ: Calibre (LinuxServer.io)
    da_DK: Calibre (LinuxServer.io)
    de_DE: Calibre (LinuxServer.io)
    el_GR: Calibre (LinuxServer.io)
    en_GB: Calibre (LinuxServer.io)
    es_ES: Calibre (LinuxServer.io)
    fr_FR: Calibre (LinuxServer.io)
    ga_IE: Calibre (LinuxServer.io)
    hr_HR: Calibre (LinuxServer.io)
    hu_HU: Calibre (LinuxServer.io)
    it_IT: Calibre (LinuxServer.io)
    ja_JP: Calibre (LinuxServer.io)
    ko_KR: Calibre (LinuxServer.io)
    ml_IN: Calibre (LinuxServer.io)
    nb_NO: Calibre (LinuxServer.io)
    nl_NL: Calibre (LinuxServer.io)
    pl_PL: Calibre (LinuxServer.io)
    pt_BR: Calibre (LinuxServer.io)
    ro_RO: Calibre (LinuxServer.io)
    ru_RU: Calibre (LinuxServer.io)
    sk_SK: Calibre (LinuxServer.io)
    sv_SE: Calibre (LinuxServer.io)
    tr_TR: Calibre (LinuxServer.io)
    zh_CN: Calibre（LinuxServer.io）
    zh_TW: Calibre（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservercalibre
  port_map: '8080'
  version: 9.15.0
