name: linuxserver-bambustudio
services:
  app:
    image: linuxserver/bambustudio:02.08.03@sha256:efce15e81c4a3ae8ff09329bcb2c95bafdce32bebc20679ee21559a751a7e4f4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DARK_MODE: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bambustudio/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverbambustudio/assets/icon.png
  title:
    en_US: Bambustudio (LinuxServer.io)
    ca_ES: Bambustudio (LinuxServer.io)
    cs_CZ: Bambustudio (LinuxServer.io)
    da_DK: Bambustudio (LinuxServer.io)
    de_DE: Bambustudio (LinuxServer.io)
    el_GR: Bambustudio (LinuxServer.io)
    en_GB: Bambustudio (LinuxServer.io)
    es_ES: Bambustudio (LinuxServer.io)
    fr_FR: Bambustudio (LinuxServer.io)
    ga_IE: Bambustudio (LinuxServer.io)
    hr_HR: Bambustudio (LinuxServer.io)
    hu_HU: Bambustudio (LinuxServer.io)
    it_IT: Bambustudio (LinuxServer.io)
    ja_JP: Bambustudio (LinuxServer.io)
    ko_KR: Bambustudio (LinuxServer.io)
    ml_IN: Bambustudio (LinuxServer.io)
    nb_NO: Bambustudio (LinuxServer.io)
    nl_NL: Bambustudio (LinuxServer.io)
    pl_PL: Bambustudio (LinuxServer.io)
    pt_BR: Bambustudio (LinuxServer.io)
    ro_RO: Bambustudio (LinuxServer.io)
    ru_RU: Bambustudio (LinuxServer.io)
    sk_SK: Bambustudio (LinuxServer.io)
    sv_SE: Bambustudio (LinuxServer.io)
    tr_TR: Bambustudio (LinuxServer.io)
    zh_CN: Bambustudio（LinuxServer.io）
    zh_TW: Bambustudio（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverbambustudio
  port_map: '3000'
  version: 02.08.03
