name: linuxserver-bambustudio
services:
  app:
    image: linuxserver/bambustudio:02.08.02
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DARK_MODE: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bambustudio/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverbambustudio/assets/icon.png
  title:
    en_US: Bambustudio (LinuxServer.io)
    zh_CN: Bambustudio（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverbambustudio
  port_map: '3000'
  version: 02.08.02
