name: linuxserver-rpcs3
services:
  app:
    image: linuxserver/rpcs3:version-build-92721aedfe9dda00caae25a7aaf7e6b7d07213d0@sha256:708ec78e083991b1ba0ec0e5812f65801a3522440b8a5fb4025118e88499f70e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rpcs3/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverrpcs3/assets/icon.png
  title:
    en_US: Rpcs3 (LinuxServer.io)
    zh_CN: Rpcs3（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverrpcs3
  port_map: '3000'
  version: version-build-92721aedfe9dda00caae25a7aaf7e6b7d07213d0
