name: linuxserver-rpcs3
services:
  app:
    image: linuxserver/rpcs3:version-build-9e86f165d1711b9429d48b0487e7bc5ba0cc9c6c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rpcs3/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverrpcs3/assets/icon.png
  title:
    en_US: Rpcs3 (LinuxServer.io)
    ca_ES: Rpcs3 (LinuxServer.io)
    cs_CZ: Rpcs3 (LinuxServer.io)
    da_DK: Rpcs3 (LinuxServer.io)
    de_DE: Rpcs3 (LinuxServer.io)
    el_GR: Rpcs3 (LinuxServer.io)
    en_GB: Rpcs3 (LinuxServer.io)
    es_ES: Rpcs3 (LinuxServer.io)
    fr_FR: Rpcs3 (LinuxServer.io)
    ga_IE: Rpcs3 (LinuxServer.io)
    hr_HR: Rpcs3 (LinuxServer.io)
    hu_HU: Rpcs3 (LinuxServer.io)
    it_IT: Rpcs3 (LinuxServer.io)
    ja_JP: Rpcs3 (LinuxServer.io)
    ko_KR: Rpcs3 (LinuxServer.io)
    ml_IN: Rpcs3 (LinuxServer.io)
    nb_NO: Rpcs3 (LinuxServer.io)
    nl_NL: Rpcs3 (LinuxServer.io)
    pl_PL: Rpcs3 (LinuxServer.io)
    pt_BR: Rpcs3 (LinuxServer.io)
    ro_RO: Rpcs3 (LinuxServer.io)
    ru_RU: Rpcs3 (LinuxServer.io)
    sk_SK: Rpcs3 (LinuxServer.io)
    sv_SE: Rpcs3 (LinuxServer.io)
    tr_TR: Rpcs3 (LinuxServer.io)
    zh_CN: Rpcs3（LinuxServer.io）
    zh_TW: Rpcs3（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverrpcs3
  port_map: '3000'
  version: version-build-9e86f165d1711b9429d48b0487e7bc5ba0cc9c6c
