name: linuxserver-sonarr
services:
  app:
    image: linuxserver/sonarr:4.0.20@sha256:b19949ea2977d2f11ec955b3ce4dbba36cb5318c4a666caa6adfeca58f8a993f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8989
        published: 8989
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sonarr/config
        target: /config
      - type: bind
        source: /DATA/AppData/sonarr/tv
        target: /tv
      - type: bind
        source: /DATA/AppData/sonarr/downloads
        target: /downloads
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserversonarr/assets/icon.png
  title:
    en_US: Sonarr (LinuxServer.io)
    ca_ES: Sonarr (LinuxServer.io)
    cs_CZ: Sonarr (LinuxServer.io)
    da_DK: Sonarr (LinuxServer.io)
    de_DE: Sonarr (LinuxServer.io)
    el_GR: Sonarr (LinuxServer.io)
    en_GB: Sonarr (LinuxServer.io)
    es_ES: Sonarr (LinuxServer.io)
    fr_FR: Sonarr (LinuxServer.io)
    ga_IE: Sonarr (LinuxServer.io)
    hr_HR: Sonarr (LinuxServer.io)
    hu_HU: Sonarr (LinuxServer.io)
    it_IT: Sonarr (LinuxServer.io)
    ja_JP: Sonarr (LinuxServer.io)
    ko_KR: Sonarr (LinuxServer.io)
    ml_IN: Sonarr (LinuxServer.io)
    nb_NO: Sonarr (LinuxServer.io)
    nl_NL: Sonarr (LinuxServer.io)
    pl_PL: Sonarr (LinuxServer.io)
    pt_BR: Sonarr (LinuxServer.io)
    ro_RO: Sonarr (LinuxServer.io)
    ru_RU: Sonarr (LinuxServer.io)
    sk_SK: Sonarr (LinuxServer.io)
    sv_SE: Sonarr (LinuxServer.io)
    tr_TR: Sonarr (LinuxServer.io)
    zh_CN: Sonarr（LinuxServer.io）
    zh_TW: Sonarr（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserversonarr
  port_map: '8989'
  version: 4.0.20
