name: linuxserver-helium
services:
  app:
    image: linuxserver/helium:0.17.2@sha256:73472236b53790bb551e4d66b644d2f7e7fef40b0cf98753c9fd86b2b4016da8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HELIUM_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/helium/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverhelium/assets/icon.png
  title:
    en_US: Helium (LinuxServer.io)
    ca_ES: Helium (LinuxServer.io)
    cs_CZ: Helium (LinuxServer.io)
    da_DK: Helium (LinuxServer.io)
    de_DE: Helium (LinuxServer.io)
    el_GR: Helium (LinuxServer.io)
    en_GB: Helium (LinuxServer.io)
    es_ES: Helium (LinuxServer.io)
    fr_FR: Helium (LinuxServer.io)
    ga_IE: Helium (LinuxServer.io)
    hr_HR: Helium (LinuxServer.io)
    hu_HU: Helium (LinuxServer.io)
    it_IT: Helium (LinuxServer.io)
    ja_JP: Helium (LinuxServer.io)
    ko_KR: Helium (LinuxServer.io)
    ml_IN: Helium (LinuxServer.io)
    nb_NO: Helium (LinuxServer.io)
    nl_NL: Helium (LinuxServer.io)
    pl_PL: Helium (LinuxServer.io)
    pt_BR: Helium (LinuxServer.io)
    ro_RO: Helium (LinuxServer.io)
    ru_RU: Helium (LinuxServer.io)
    sk_SK: Helium (LinuxServer.io)
    sv_SE: Helium (LinuxServer.io)
    tr_TR: Helium (LinuxServer.io)
    zh_CN: Helium（LinuxServer.io）
    zh_TW: Helium（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverhelium
  port_map: '3000'
  version: 0.17.2
