name: linuxserver-github-desktop
services:
  app:
    image: linuxserver/github-desktop:3.4.13@sha256:a269c3a339370df045d34efed25687712debe4c16cb5587ee6a4e77741e406dc
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/github-desktop/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservergithubdesktop/assets/icon.png
  title:
    en_US: Github desktop (LinuxServer.io)
    ca_ES: Github desktop (LinuxServer.io)
    cs_CZ: Github desktop (LinuxServer.io)
    da_DK: Github desktop (LinuxServer.io)
    de_DE: Github desktop (LinuxServer.io)
    el_GR: Github desktop (LinuxServer.io)
    en_GB: Github desktop (LinuxServer.io)
    es_ES: Github desktop (LinuxServer.io)
    fr_FR: Github desktop (LinuxServer.io)
    ga_IE: Github desktop (LinuxServer.io)
    hr_HR: Github desktop (LinuxServer.io)
    hu_HU: Github desktop (LinuxServer.io)
    it_IT: Github desktop (LinuxServer.io)
    ja_JP: Github desktop (LinuxServer.io)
    ko_KR: Github desktop (LinuxServer.io)
    ml_IN: Github desktop (LinuxServer.io)
    nb_NO: Github desktop (LinuxServer.io)
    nl_NL: Github desktop (LinuxServer.io)
    pl_PL: Github desktop (LinuxServer.io)
    pt_BR: Github desktop (LinuxServer.io)
    ro_RO: Github desktop (LinuxServer.io)
    ru_RU: Github desktop (LinuxServer.io)
    sk_SK: Github desktop (LinuxServer.io)
    sv_SE: Github desktop (LinuxServer.io)
    tr_TR: Github desktop (LinuxServer.io)
    zh_CN: Github desktop（LinuxServer.io）
    zh_TW: Github desktop（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservergithubdesktop
  port_map: '3000'
  version: 3.4.13
