name: linuxserver-prowlarr
services:
  app:
    image: linuxserver/prowlarr:2.6.5@sha256:875fb7ea5b884dad37cb9587cf0dba62286c84a4acf1fb2dfd82ac6f23eb9661
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 9696
        published: 9696
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/prowlarr/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverprowlarr/assets/icon.png
  title:
    en_US: Prowlarr (LinuxServer.io)
    ca_ES: Prowlarr (LinuxServer.io)
    cs_CZ: Prowlarr (LinuxServer.io)
    da_DK: Prowlarr (LinuxServer.io)
    de_DE: Prowlarr (LinuxServer.io)
    el_GR: Prowlarr (LinuxServer.io)
    en_GB: Prowlarr (LinuxServer.io)
    es_ES: Prowlarr (LinuxServer.io)
    fr_FR: Prowlarr (LinuxServer.io)
    ga_IE: Prowlarr (LinuxServer.io)
    hr_HR: Prowlarr (LinuxServer.io)
    hu_HU: Prowlarr (LinuxServer.io)
    it_IT: Prowlarr (LinuxServer.io)
    ja_JP: Prowlarr (LinuxServer.io)
    ko_KR: Prowlarr (LinuxServer.io)
    ml_IN: Prowlarr (LinuxServer.io)
    nb_NO: Prowlarr (LinuxServer.io)
    nl_NL: Prowlarr (LinuxServer.io)
    pl_PL: Prowlarr (LinuxServer.io)
    pt_BR: Prowlarr (LinuxServer.io)
    ro_RO: Prowlarr (LinuxServer.io)
    ru_RU: Prowlarr (LinuxServer.io)
    sk_SK: Prowlarr (LinuxServer.io)
    sv_SE: Prowlarr (LinuxServer.io)
    tr_TR: Prowlarr (LinuxServer.io)
    zh_CN: Prowlarr（LinuxServer.io）
    zh_TW: Prowlarr（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverprowlarr
  port_map: '9696'
  version: 2.6.5
