name: linuxserver-webcord
services:
  app:
    image: linuxserver/webcord:4.14.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webcord/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: WebCord can be summarized as a pack of security and privacy hardenings, Discord features reimplementations, Electron / Chromium / Discord bugs workarounds, stylesheets, internal pages and wrapped https://discord.com page, designed to conform with ToS as much as it is possible (or hide the changes that might violate it from Discord's eyes).
    ca_ES: WebCord es pot resumir com un paquet de reforços de seguretat i privadesa, reimplementacions de funcions de Discord, solucions alternatives per a errors d'Electron/Chromium/Discord, fulls d'estil, pàgines internes i una pàgina https://discord.com ajustada, dissenyada per complir amb les Condicions del servei tant com sigui possible (o ocultar els canvis que podrien violar-les als ulls de Discord).
    cs_CZ: WebCord lze shrnout jako balíček vylepšení zabezpečení a ochrany soukromí, reimplementace funkcí Discordu, řešení chyb Electron / Chromium / Discord, styly, interní stránky a zabalenou stránku https://discord.com, navržené tak, aby co nejvíce odpovídaly Podmínkám služby (nebo skryly změny, které by je mohly porušovat, před očima Discordu).
    da_DK: WebCord kan opsummeres som en pakke af sikkerheds- og privatlivsopdateringer. Discord har genimplementeringer, Electron / Chromium / Discord-fejlløsninger, stylesheets, interne sider og en indpakket https://discord.com-side, der er designet til at overholde brugsbetingelserne så meget som muligt (eller skjule ændringer, der måtte overtræde dem, for Discords øjne).
    de_DE: WebCord lässt sich zusammenfassen als ein Paket aus Sicherheits- und Datenschutzverbesserungen, Neuimplementierungen von Discord-Funktionen, Workarounds für Electron-/Chromium-/Discord-Bugs, Stylesheets, internen Seiten und einer umschlossenen https://discord.com-Seite, das so weit wie möglich den Nutzungsbedingungen entspricht (oder die Änderungen, die gegen diese verstoßen könnten, vor Discord verbirgt).
    el_GR: Το WebCord μπορεί να συνοψιστεί ως ένα πακέτο βελτιώσεων ασφαλείας και απορρήτου, επαναεφαρμογών χαρακτηριστικών του Discord, λύσεις για σφάλματα Electron / Chromium / Discord, φύλλα στυλ, εσωτερικές σελίδες και μια τυλιγμένη σελίδα https://discord.com, σχεδιασμένη να συμμορφώνεται με τους Όρους Παροχής Υπηρεσιών όσο το δυνατόν περισσότερο (ή να αποκρύπτει τις αλλαγές που ενδέχεται να τους παραβιάζουν από τα μάτια του Discord).
    en_GB: Webcord can be summarized as a pack of security and privacy hardenings, Discord features reimplementations, Electron / Chromium / Discord bugs workarounds, stylesheets, internal pages and wrapped https://discord.com page, designed to conform with Tos as much as it is possible (or hide the changes that might violate it from Discord's eyes).
    es_ES: WebCord se puede resumir como un conjunto de mejoras de seguridad y privacidad, reimplementaciones de funciones de Discord, soluciones alternativas para errores de Electron/Chromium/Discord, hojas de estilo, páginas internas y una página https://discord.com encapsulada, diseñadas para cumplir con los Términos de Servicio en la medida de lo posible (o para ocultar a Discord los cambios que podrían infringirlos).
    fr_FR: WebCord peut se résumer à un ensemble de mesures de sécurité et de confidentialité renforcées, de réimplémentations des fonctionnalités de Discord, de solutions de contournement aux bugs d'Electron/Chromium/Discord, de feuilles de style, de pages internes et d'une page https://discord.com encapsulée, conçue pour se conformer autant que possible aux conditions d'utilisation (ou masquer aux yeux de Discord les modifications susceptibles de les enfreindre).
    ga_IE: Is féidir achoimre a dhéanamh ar WebCord mar phacáiste de chruasuithe slándála agus príobháideachta, ina bhfuil ath-chur i bhfeidhm, réitigh sheachbhóthair ar fhabhtanna Electron / Chromium / Discord, bileoga stíle, leathanaigh inmheánacha agus leathanach fillte https://discord.com, atá deartha chun cloí le Téarmaí Seirbhíse a oiread agus is féidir (nó na hathruithe a d'fhéadfadh a bheith ina sárú a cheilt ó shúile Discord).
    hr_HR: WebCord se može sažeti kao paket sigurnosnih i privatnih poboljšanja, reimplementacija Discordovih značajki, rješenja za greške Electron / Chromium / Discord, stilske listove, interne stranice i omotanu https://discord.com stranicu, dizajniranu da bude što je više moguće u skladu s Uvjetima pružanja usluge (ili da sakrije promjene koje bi ih mogle kršiti od Discordovih očiju).
    hu_HU: A WebCord biztonsági és adatvédelmi erősítések csomagjaként foglalható össze, beleértve a Discord funkciók újraimplementációit, az Electron / Chromium / Discord hibák megkerülő megoldásait, a stíluslapokat, a belső oldalakat és a becsomagolt https://discord.com oldalt, amelyeket úgy terveztek, hogy a lehető legnagyobb mértékben megfeleljenek a Felhasználási Feltételeknek (TosS) (vagy elrejtsék a Discord elől az azokat esetleg sértő változtatásokat).
    it_IT: WebCord può essere riassunto come un pacchetto di misure di sicurezza e privacy rafforzate, re-implementazioni di funzionalità di Discord, soluzioni alternative per bug di Electron/Chromium/Discord, fogli di stile, pagine interne e una pagina https://discord.com "avvolta", progettate per essere conformi ai Termini di Servizio il più possibile (o per nascondere a Discord le modifiche che potrebbero violarli).
    ja_JP: WebCordは、セキュリティとプライバシーの強化、Discord機能の再実装、Electron/Chromium/Discordのバグの回避策、スタイルシート、内部ページ、ラップされたhttps://discord.comページなどのパッケージとして要約でき、可能な限り利用規約に準拠するように設計されている（または、違反する可能性のある変更をDiscordの目から隠すように設計されている）。
    ko_KR: WebCord는 보안 및 개인정보 보호 강화, Discord 기능 재구현, Electron/Chromium/Discord 버그 해결, 스타일시트, 내부 페이지 및 Discord.com 페이지를 래핑한 패키지로 요약할 수 있으며, 가능한 한 Discord 이용약관을 준수하도록 설계되었거나(Discord 측에서 위반 가능성이 있는 변경 사항을 숨기도록 설계됨) 합니다.
    ml_IN: വെബ്‌കോർഡിനെ സുരക്ഷയുടെയും സ്വകാര്യതയുടെയും ഒരു കൂട്ടമായി സംഗ്രഹിക്കാം, ഡിസ്‌കോർഡ് സവിശേഷതകൾ റീഇംപ്ലിമെന്റേഷനുകൾ, ഇലക്ട്രോൺ / ക്രോമിയം / ഡിസ്‌കോർഡ് ബഗുകൾക്കുള്ള പരിഹാരങ്ങൾ, സ്റ്റൈൽഷീറ്റുകൾ, ഇന്റേണൽ പേജുകൾ, റാപ്പ് ചെയ്ത https://discord.com പേജ് എന്നിവ, കഴിയുന്നത്ര ToS-മായി പൊരുത്തപ്പെടാൻ (അല്ലെങ്കിൽ ഡിസ്‌കോർഡിന്റെ കണ്ണിൽ നിന്ന് അതിനെ ലംഘിക്കുന്ന മാറ്റങ്ങൾ മറയ്ക്കാൻ) രൂപകൽപ്പന ചെയ്‌തിരിക്കുന്നു.
    nb_NO: WebCord kan oppsummeres som en pakke med sikkerhets- og personvernforbedringer. Discord har reimplementeringer, løsninger for feil i Electron/Chromium/Discord, stilark, interne sider og en innpakket https://discord.com-side, designet for å overholde tjenestevilkårene så mye som mulig (eller skjule endringer som kan bryte dem fra Discords øyne).
    nl_NL: WebCord kan worden samengevat als een pakket met beveiligings- en privacyverbeteringen, herimplementaties van Discord-functies, oplossingen voor bugs in Electron/Chromium/Discord, stylesheets, interne pagina's en een aangepaste https://discord.com-pagina, ontworpen om zoveel mogelijk te voldoen aan de gebruiksvoorwaarden (of om wijzigingen die deze mogelijk schenden, te verbergen voor Discord).
    pl_PL: WebCord można podsumować jako pakiet wzmocnień zabezpieczeń i prywatności, implementacji funkcji Discord, obejść błędów Electron/Chromium/Discord, arkuszy stylów, stron wewnętrznych i opakowanej strony https://discord.com, zaprojektowanych tak, aby były w jak największym stopniu zgodne z Warunkami korzystania z usługi (lub ukrywały przed Discordem zmiany, które mogłyby je naruszać).
    pt_BR: O WebCord pode ser resumido como um pacote de reforços de segurança e privacidade, reimplementações de recursos do Discord, soluções alternativas para bugs do Electron/Chromium/Discord, folhas de estilo, páginas internas e uma página https://discord.com encapsulada, projetada para estar em conformidade com os Termos de Serviço o máximo possível (ou ocultar dos olhos do Discord as alterações que possam violá-los).
    ro_RO: WebCord poate fi rezumat ca un pachet de îmbunătățiri ale securității și confidențialității, reimplementări de funcționalități Discord, soluții alternative pentru erorile Electron / Chromium / Discord, foi de stil, pagini interne și o pagină https://discord.com încapsulată, concepută pentru a se conforma cât mai mult posibil cu Termenii și condițiile de utilizare (sau pentru a ascunde modificările care ar putea încălca termenii și condițiile de utilizare de ochii Discord).
    ru_RU: WebCord можно кратко охарактеризовать как набор мер по повышению безопасности и конфиденциальности, переработанные версии функций Discord, обходные пути для исправления ошибок в Electron/Chromium/Discord, таблицы стилей, внутренние страницы и обернутую страницу https://discord.com, разработанные таким образом, чтобы максимально соответствовать условиям использования (или скрывать от Discord изменения, которые могут их нарушать).
    sk_SK: WebCord možno zhrnúť ako balík vylepšení zabezpečenia a ochrany súkromia, reimplementácie funkcií Discordu, riešenia chýb Electron / Chromium / Discord, štýly, interné stránky a zabalenú stránku https://discord.com, navrhnuté tak, aby čo najviac vyhovovali podmienkam používania (alebo skryli zmeny, ktoré by ich mohli porušovať, pred očami Discordu).
    sv_SE: WebCord kan sammanfattas som ett paket med säkerhets- och integritetshärdningar. Discord har omimplementeringar, lösningar för buggar i Electron/Chromium/Discord, stilmallar, interna sidor och en inlindad https://discord.com-sida, utformad för att följa användarvillkoren så mycket som möjligt (eller dölja ändringar som kan bryta mot dem för Discord).
    tr_TR: WebCord, güvenlik ve gizlilik iyileştirmeleri, Discord özelliklerinin yeniden uygulanması, Electron/Chromium/Discord hatalarına yönelik geçici çözümler, stil sayfaları, dahili sayfalar ve sarmalanmış https://discord.com sayfası gibi unsurları içeren ve mümkün olduğunca Hizmet Şartlarına uygun olacak şekilde (veya ihlal edebilecek değişiklikleri Discord'un gözünden gizleyecek şekilde) tasarlanmış bir paket olarak özetlenebilir.
    zh_CN: WebCord 封装 https://discord.com 页面，集成安全与隐私加固、Discord 功能的重新实现、Electron、Chromium 和 Discord 问题的绕过方案、样式表及内部页面。其设计尽可能遵循服务条款，或避免让 Discord 察觉可能违反条款的修改。
    zh_TW: WebCord 封裝 https://discord.com 頁面，整合安全與隱私加固、Discord 功能的重新實現、Electron、Chromium 和 Discord 問題的繞過方案、樣式表及內部頁面。其設計儘可能遵循服務條款，或避免讓 Discord 察覺可能違反條款的修改。
  tagline:
    en_US: Can be summarized as a pack of security and privacy hardenings, Discord features reimplementations, Electron / Chromium / Discord bugs workarounds, stylesheets, internal pages and wrapped https://discord. Com page, designed to conform with ToS as much as it is possible (or hide the changes that might violate it from Discord's eyes).
    ca_ES: Es pot resumir com un paquet de reforços de seguretat i privadesa, reimplementacions de funcions de Discord, solucions alternatives per a errors d'Electron/Chromium/Discord, fulls d'estil, pàgines internes i una pàgina https://discord.com embolicada, dissenyada per complir amb les Condicions del servei tant com sigui possible (o ocultar els canvis que podrien violar-les als ulls de Discord).
    cs_CZ: Lze to shrnout jako balíček vylepšení zabezpečení a ochrany soukromí, Discord obsahuje reimplementace funkcí, řešení chyb Electron / Chromium / Discord, styly, interní stránky a zabalenou stránku https://discord.com, navrženou tak, aby co nejvíce odpovídala Podmínkám služby (nebo skryla změny, které by je mohly porušovat, před očima Discordu).
    da_DK: Discord, der kan opsummeres som en pakke af sikkerheds- og privatlivshærdninger, har reimplementeringsmuligheder, Electron / Chromium / Discord-fejlløsninger, stylesheets, interne sider og en indpakket https://discord.com-side, der er designet til at overholde brugsbetingelserne så meget som muligt (eller skjule de ændringer, der måtte overtræde dem, fra Discords øjne).
    de_DE: Zusammengefasst handelt es sich um ein Paket aus Sicherheits- und Datenschutzverbesserungen, Neuimplementierungen von Discord-Funktionen, Workarounds für Electron-/Chromium-/Discord-Bugs, Stylesheets, internen Seiten und einer umschlossenen https://discord.com-Seite, das so weit wie möglich den Nutzungsbedingungen entspricht (oder Änderungen, die gegen diese verstoßen könnten, vor Discord verbirgt).
    el_GR: Μπορεί να συνοψιστεί ως ένα πακέτο βελτιώσεων ασφαλείας και απορρήτου, με επαναεφαρμογές χαρακτηριστικών του Discord, λύσεις για σφάλματα Electron / Chromium / Discord, φύλλα στυλ, εσωτερικές σελίδες και μια τυλιγμένη σελίδα https://discord.com, σχεδιασμένη να συμμορφώνεται με τους Όρους Παροχής Υπηρεσιών όσο το δυνατόν περισσότερο (ή να αποκρύπτει τις αλλαγές που ενδέχεται να τους παραβιάζουν από τα μάτια του Discord).
    en_GB: Can be summarized as a pack of security and privacy hardenings, Discord features reimplementations, Electron / Chromium / Discord bugs workarounds, stylesheets, internal pages and wrapped https://discord. Com page, designed to conform with Tos as much as it is possible (or hide the changes that might violate it from Discord's eyes).
    es_ES: Se puede resumir como un conjunto de mejoras de seguridad y privacidad, reimplementaciones de funciones de Discord, soluciones alternativas para errores de Electron/Chromium/Discord, hojas de estilo, páginas internas y una página https://discord.com encapsulada, diseñada para cumplir con los Términos de Servicio en la medida de lo posible (o para ocultar a Discord los cambios que podrían infringirlos).
    fr_FR: Ce pack peut se résumer à un ensemble de mesures de sécurité et de confidentialité renforcées, de réimplémentations des fonctionnalités de Discord, de solutions de contournement pour les bugs d'Electron/Chromium/Discord, de feuilles de style, de pages internes et d'une page https://discord.com encapsulée, conçue pour se conformer autant que possible aux conditions d'utilisation (ou masquer aux yeux de Discord les modifications susceptibles de les enfreindre).
    ga_IE: Is féidir achoimre a dhéanamh air mar phacáiste cruaite slándála agus príobháideachta, tá ath-chur i bhfeidhm, réitigh sheachbhóthair ar fhabhtanna Electron / Chromium / Discord, bileoga stíle, leathanaigh inmheánacha agus leathanach fillte https://discord.com, atá deartha chun cloí le Téarmaí Seirbhíse a oiread agus is féidir (nó na hathruithe a d'fhéadfadh a bheith ina sárú a cheilt ó shúile Discord).
    hr_HR: Može se sažeti kao paket sigurnosnih i privatnostnih poboljšanja, Discord sadrži reimplementacije, rješenja za greške Electron / Chromium / Discord, stilske listove, interne stranice i omotanu https://discord.com stranicu, dizajniranu da bude što je više moguće u skladu s Uvjetima pružanja usluge (ili da sakrije promjene koje bi ih mogle kršiti od Discorda).
    hu_HU: Összefoglalva egy csomag biztonsági és adatvédelmi fejlesztést tartalmaz, beleértve a Discord funkciók újraimplementációit, az Electron / Chromium / Discord hibák megkerülő megoldásait, a stíluslapokat, a belső oldalakat és a becsomagolt https://discord.com oldalt, amelyeket úgy terveztek, hogy a lehető legnagyobb mértékben megfeleljenek a Felhasználási Feltételeknek (vagy elrejtsék a Discord elől az azokat esetleg sértő változtatásokat).
    it_IT: Può essere riassunto come un pacchetto di misure di sicurezza e privacy rafforzate, re-implementazioni di funzionalità di Discord, soluzioni alternative per bug di Electron/Chromium/Discord, fogli di stile, pagine interne e una pagina https://discord.com protetta, progettata per essere conforme ai Termini di Servizio il più possibile (o per nascondere a Discord le modifiche che potrebbero violarli).
    ja_JP: セキュリティとプライバシーの強化、Discord 機能の再実装、Electron / Chromium / Discord のバグの回避策、スタイルシート、内部ページ、ラップされた https://discord.com ページなど、利用規約にできる限り準拠するように設計された（または、違反する可能性のある変更を Discord の目から隠す）パッケージとして要約できます。
    ko_KR: 요약하자면, 이 패키지는 보안 및 개인정보 보호 강화, Discord 기능 재구현, Electron/Chromium/Discord 버그 해결, 스타일시트, 내부 페이지 및 Discord 이용약관을 최대한 준수하도록 설계된 래핑된 https://discord.com 페이지 등을 포함합니다(Discord 측에서 이용약관을 위반할 수 있는 변경 사항을 숨기도록 설계됨).
    ml_IN: സുരക്ഷയുടെയും സ്വകാര്യതയുടെയും ഒരു കൂട്ടമായി സംഗ്രഹിക്കാം, ഡിസ്കോർഡിൽ റീഇംപ്ലിമെന്റേഷനുകൾ, ഇലക്ട്രോൺ / ക്രോമിയം / ഡിസ്കോർഡ് ബഗുകൾക്കുള്ള പരിഹാരങ്ങൾ, സ്റ്റൈൽഷീറ്റുകൾ, ഇന്റേണൽ പേജുകൾ, റാപ്പ് ചെയ്ത https://discord.com പേജ് എന്നിവ ഉൾപ്പെടുന്നു, ഇത് കഴിയുന്നത്ര ToS-ന് അനുസൃതമായി രൂപകൽപ്പന ചെയ്‌തിരിക്കുന്നു (അല്ലെങ്കിൽ ഡിസ്കോർഡിന്റെ കണ്ണിൽ നിന്ന് അതിനെ ലംഘിക്കുന്ന മാറ്റങ്ങൾ മറയ്ക്കുന്നു).
    nb_NO: Discord kan oppsummeres som en pakke med sikkerhets- og personvernforbedringer, og har reimplementeringer, løsninger for Electron / Chromium / Discord-feil, stilark, interne sider og en innpakket https://discord.com-side, designet for å overholde tjenestevilkårene så mye som mulig (eller skjule endringer som kan bryte dem fra Discords øyne).
    nl_NL: Het kan worden samengevat als een pakket met verbeteringen op het gebied van beveiliging en privacy, herimplementaties van Discord-functies, oplossingen voor bugs in Electron/Chromium/Discord, stylesheets, interne pagina's en een aangepaste https://discord.com-pagina, ontworpen om zoveel mogelijk te voldoen aan de gebruiksvoorwaarden (of om wijzigingen die deze mogelijk schenden, te verbergen voor Discord).
    pl_PL: Można to podsumować jako pakiet wzmocnień bezpieczeństwa i prywatności, ponownych implementacji funkcji Discorda, obejść błędów Electron/Chromium/Discord, arkuszy stylów, stron wewnętrznych i opakowanej strony https://discord.com, zaprojektowanej tak, aby w jak największym stopniu była zgodna z Warunkami korzystania z usługi (lub ukryć przed Discordem zmiany, które mogłyby je naruszać).
    pt_BR: Em resumo, trata-se de um pacote de melhorias de segurança e privacidade, reimplementações de recursos do Discord, correções de bugs do Electron/Chromium/Discord, folhas de estilo, páginas internas e uma página https://discord.com encapsulada, projetada para estar em conformidade com os Termos de Serviço o máximo possível (ou ocultar dos olhos do Discord as alterações que possam violá-los).
    ro_RO: Poate fi rezumat ca un pachet de îmbunătățiri ale securității și confidențialității, reimplementări ale caracteristicilor Discord, soluții alternative pentru erorile Electron / Chromium / Discord, foi de stil, pagini interne și o pagină https://discord.com încapsulată, concepută pentru a se conforma cât mai mult posibil cu Termenii și condițiile de utilizare (sau pentru a ascunde modificările care ar putea să le încalce de ochii Discord).
    ru_RU: 'Вкратце, это набор мер по повышению безопасности и конфиденциальности: переработанные версии интерфейса Discord, обходные пути для исправления ошибок в Electron/Chromium/Discord, таблицы стилей, внутренние страницы и обернутая страница https://discord.com, разработанные таким образом, чтобы максимально соответствовать условиям использования (или скрывать от Discord изменения, которые могут их нарушать).'
    sk_SK: Dá sa to zhrnúť ako balík vylepšení zabezpečenia a ochrany súkromia, Discord obsahuje reimplementácie funkcií, riešenia chýb Electron / Chromium / Discord, štýly, interné stránky a obalenú stránku https://discord.com, ktoré sú navrhnuté tak, aby čo najviac vyhovovali podmienkam používania (alebo skryli zmeny, ktoré by ich mohli porušovať, pred očami Discordu).
    sv_SE: Discord kan sammanfattas som ett paket med säkerhets- och integritetshärdningar. Det har omimplementeringar, lösningar för buggar kring Electron/Chromium/Discord, stilmallar, interna sidor och en inlindad https://discord.com-sida, utformad för att följa användarvillkoren så mycket som möjligt (eller dölja ändringar som kan bryta mot dem för Discord).
    tr_TR: Özetle, güvenlik ve gizlilik iyileştirmeleri, Discord özelliklerinin yeniden uygulanması, Electron/Chromium/Discord hatalarına yönelik geçici çözümler, stil sayfaları, dahili sayfalar ve sarmalanmış https://discord.com sayfası içeren bir paket olarak tanımlanabilir; bu paket, Hizmet Şartlarına mümkün olduğunca uygun olacak şekilde (veya ihlal edebilecek değişiklikleri Discord'un gözünden gizleyecek şekilde) tasarlanmıştır.
    zh_CN: 为 Discord 网页提供安全和隐私增强的客户端。
    zh_TW: 為 Discord 網頁提供安全和隱私增強的客戶端。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/webcord-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/webcord-icon.png
  title:
    en_US: Webcord (LinuxServer.io)
    ca_ES: Webcord (LinuxServer.io)
    cs_CZ: Webcord (LinuxServer.io)
    da_DK: Webcord (LinuxServer.io)
    de_DE: Webcord (LinuxServer.io)
    el_GR: Webcord (LinuxServer.io)
    en_GB: Webcord (LinuxServer.io)
    es_ES: Webcord (LinuxServer.io)
    fr_FR: Webcord (LinuxServer.io)
    ga_IE: Webcord (LinuxServer.io)
    hr_HR: Webcord (LinuxServer.io)
    hu_HU: Webcord (LinuxServer.io)
    it_IT: Webcord (LinuxServer.io)
    ja_JP: Webcord (LinuxServer.io)
    ko_KR: Webcord (LinuxServer.io)
    ml_IN: Webcord (LinuxServer.io)
    nb_NO: Webcord (LinuxServer.io)
    nl_NL: Webcord (LinuxServer.io)
    pl_PL: Webcord (LinuxServer.io)
    pt_BR: Webcord (LinuxServer.io)
    ro_RO: Webcord (LinuxServer.io)
    ru_RU: Webcord (LinuxServer.io)
    sk_SK: Webcord (LinuxServer.io)
    sv_SE: Webcord (LinuxServer.io)
    tr_TR: Webcord (LinuxServer.io)
    zh_CN: Webcord（LinuxServer.io）
    zh_TW: Webcord（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverwebcord
  port_map: '3000'
  version: 4.14.0
