name: linuxserver-cura
services:
  app:
    image: linuxserver/cura:5.13.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/cura/config
        target: /config
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_US: UltiMaker Cura is free, easy-to-use 3D printing software trusted by millions of users. Fine-tune your 3D model with 400+ settings for the best slicing and printing results.
    ca_ES: UltiMaker Cura és un programari d'impressió 3D gratuït i fàcil d'utilitzar en què milions d'usuaris confien. Ajusta el teu model 3D amb més de 400 configuracions per obtenir els millors resultats de tall i impressió.
    cs_CZ: UltiMaker Cura je bezplatný a snadno použitelný software pro 3D tisk, kterému důvěřují miliony uživatelů. Vylaďte si svůj 3D model pomocí více než 400 nastavení pro dosažení nejlepších výsledků řezání a tisku.
    da_DK: UltiMaker Cura er gratis og brugervenlig 3D-printsoftware, som millioner af brugere har tillid til. Finjuster din 3D-model med over 400 indstillinger for at opnå de bedste resultater inden for udskæring og print.
    de_DE: UltiMaker Cura ist eine kostenlose, benutzerfreundliche 3D-Drucksoftware, der Millionen von Anwendern vertrauen. Optimieren Sie Ihr 3D-Modell mit über 400 Einstellungen für beste Slicing- und Druckergebnisse.
    el_GR: Το UltiMaker Cura είναι ένα δωρεάν, εύχρηστο λογισμικό τρισδιάστατης εκτύπωσης που εμπιστεύονται εκατομμύρια χρήστες. Βελτιστοποιήστε το τρισδιάστατο μοντέλο σας με πάνω από 400 ρυθμίσεις για τα καλύτερα αποτελέσματα κοπής και εκτύπωσης.
    en_GB: Ultimaker Cura is free, easy-to-use 3D printing software trusted by millions of users. Fine-tune your 3D model with 400+ settings for the best slicing and printing results.
    es_ES: UltiMaker Cura es un software de impresión 3D gratuito y fácil de usar, en el que confían millones de usuarios. Optimiza tu modelo 3D con más de 400 ajustes para obtener los mejores resultados de laminado e impresión.
    fr_FR: UltiMaker Cura est un logiciel d'impression 3D gratuit et facile à utiliser, plébiscité par des millions d'utilisateurs. Optimisez votre modèle 3D grâce à plus de 400 paramètres pour des résultats de découpe et d'impression optimaux.
    ga_IE: Is bogearraí priontála 3D saor in aisce, éasca le húsáid é UltiMaker Cura a bhfuil muinín ag na milliúin úsáideoirí as. Déan do mhúnla 3D a choigeartú go mín le breis is 400 socrú chun na torthaí gearrtha agus priontála is fearr a fháil.
    hr_HR: UltiMaker Cura je besplatan, jednostavan softver za 3D ispis kojem vjeruju milijuni korisnika. Podesite svoj 3D model s više od 400 postavki za najbolje rezultate rezanja i ispisa.
    hu_HU: Az UltiMaker Cura egy ingyenes, könnyen használható 3D nyomtatószoftver, amelyben több millió felhasználó bízik. Finomhangolja 3D modelljét több mint 400 beállítással a legjobb szeletelési és nyomtatási eredmények elérése érdekében.
    it_IT: UltiMaker Cura è un software di stampa 3D gratuito e facile da usare, utilizzato da milioni di utenti. Perfeziona il tuo modello 3D con oltre 400 impostazioni per ottenere i migliori risultati di slicing e stampa.
    ja_JP: UltiMaker Curaは、何百万人ものユーザーに信頼されている、無料で使いやすい3Dプリントソフトウェアです。400以上の設定項目で3Dモデルを微調整し、最適なスライスとプリント結果を実現できます。
    ko_KR: UltiMaker Cura는 수백만 명의 사용자가 신뢰하는 무료의 사용하기 쉬운 3D 프린팅 소프트웨어입니다. 400개 이상의 설정을 통해 3D 모델을 세밀하게 조정하여 최상의 슬라이싱 및 프린팅 결과를 얻으세요.
    ml_IN: ദശലക്ഷക്കണക്കിന് ഉപയോക്താക്കൾ വിശ്വസിക്കുന്ന സൗജന്യവും ഉപയോഗിക്കാൻ എളുപ്പമുള്ളതുമായ 3D പ്രിന്റിംഗ് സോഫ്റ്റ്‌വെയറാണ് അൾട്ടിമേക്കർ ക്യൂറ. മികച്ച സ്ലൈസിംഗ്, പ്രിന്റിംഗ് ഫലങ്ങൾക്കായി 400+ ക്രമീകരണങ്ങൾ ഉപയോഗിച്ച് നിങ്ങളുടെ 3D മോഡലിനെ ഫൈൻ-ട്യൂൺ ചെയ്യുക.
    nb_NO: UltiMaker Cura er gratis og brukervennlig 3D-utskriftsprogramvare som millioner av brukere stoler på. Finjuster 3D-modellen din med over 400 innstillinger for best mulig skjære- og utskriftsresultat.
    nl_NL: UltiMaker Cura is gratis, gebruiksvriendelijke 3D-printsoftware die door miljoenen gebruikers wordt vertrouwd. Optimaliseer je 3D-model met meer dan 400 instellingen voor de beste slice- en printresultaten.
    pl_PL: UltiMaker Cura to darmowe i łatwe w obsłudze oprogramowanie do druku 3D, któremu zaufały miliony użytkowników. Dopracuj swój model 3D dzięki ponad 400 ustawieniom, aby uzyskać najlepsze rezultaty cięcia i drukowania.
    pt_BR: O UltiMaker Cura é um software de impressão 3D gratuito e fácil de usar, confiável por milhões de usuários. Ajuste seu modelo 3D com mais de 400 configurações para obter os melhores resultados de fatiamento e impressão.
    ro_RO: UltiMaker Cura este un software de imprimare 3D gratuit și ușor de utilizat, în care milioane de utilizatori au încredere. Configurați-vă modelul 3D cu peste 400 de setări pentru cele mai bune rezultate de tăiere și imprimare.
    ru_RU: UltiMaker Cura — это бесплатное и простое в использовании программное обеспечение для 3D-печати, которому доверяют миллионы пользователей. Настройте свою 3D-модель с помощью более чем 400 параметров для достижения наилучших результатов нарезки и печати.
    sk_SK: UltiMaker Cura je bezplatný a ľahko použiteľný softvér na 3D tlač, ktorému dôverujú milióny používateľov. Dolaďte si svoj 3D model pomocou viac ako 400 nastavení pre dosiahnutie najlepších výsledkov pri krájaní a tlači.
    sv_SE: UltiMaker Cura är en gratis och lättanvänd 3D-utskriftsprogramvara som miljontals användare litar på. Finjustera din 3D-modell med fler än 400 inställningar för bästa möjliga resultat inom skärning och utskrift.
    tr_TR: UltiMaker Cura, milyonlarca kullanıcı tarafından güvenilen, ücretsiz ve kullanımı kolay bir 3D baskı yazılımıdır. En iyi dilimleme ve baskı sonuçları için 400'den fazla ayarla 3D modelinizi hassas bir şekilde ayarlayın.
    zh_CN: UltiMaker Cura 是一款免费、易用的 3D 打印软件，受到数百万用户信赖。你可以使用 400 多项设置精细调整 3D 模型，获得更好的切片和打印效果。
    zh_TW: UltiMaker Cura 是一款免費、易用的 3D 列印軟體，受到數百萬使用者信賴。你可以使用 400 多項設定精細調整 3D 模型，獲得更好的切片和列印效果。
  tagline:
    en_US: Free, easy-to-use 3D printing software trusted by millions of users. Fine-tune your 3D model with 400+ settings for the best slicing and printing results.
    ca_ES: Programari d'impressió 3D gratuït i fàcil d'utilitzar en què confien milions d'usuaris. Ajusta el teu model 3D amb més de 400 configuracions per obtenir els millors resultats de tall i impressió.
    cs_CZ: Bezplatný a snadno použitelný software pro 3D tisk, kterému důvěřují miliony uživatelů. Vylaďte si svůj 3D model pomocí více než 400 nastavení pro nejlepší výsledky řezání a tisku.
    da_DK: Gratis og brugervenlig 3D-printsoftware, som millioner af brugere har tillid til. Finjuster din 3D-model med over 400 indstillinger for at opnå de bedste udskærings- og printresultater.
    de_DE: Kostenlose, benutzerfreundliche 3D-Drucksoftware, der Millionen von Anwendern vertrauen. Optimieren Sie Ihr 3D-Modell mit über 400 Einstellungen für beste Ergebnisse beim Slicing und Drucken.
    el_GR: Δωρεάν, εύχρηστο λογισμικό τρισδιάστατης εκτύπωσης που εμπιστεύονται εκατομμύρια χρήστες. Βελτιστοποιήστε το τρισδιάστατο μοντέλο σας με περισσότερες από 400 ρυθμίσεις για τα καλύτερα αποτελέσματα κοπής και εκτύπωσης.
    en_GB: Free, easy-to-use 3D printing software trusted by millions of users. Fine-tune your 3D model with 400+ settings for the best slicing and printing results.
    es_ES: Software de impresión 3D gratuito y fácil de usar, en el que confían millones de usuarios. Optimiza tu modelo 3D con más de 400 ajustes para obtener los mejores resultados de laminado e impresión.
    fr_FR: Logiciel d'impression 3D gratuit et facile d'utilisation, plébiscité par des millions d'utilisateurs. Optimisez votre modèle 3D grâce à plus de 400 paramètres pour des résultats de découpe et d'impression exceptionnels.
    ga_IE: Bogearraí priontála 3D saor in aisce, éasca le húsáid a bhfuil muinín ag na milliúin úsáideoirí astu. Déan do mhúnla 3D a choigeartú go mín le breis is 400 socrú chun na torthaí gearrtha agus priontála is fearr a fháil.
    hr_HR: Besplatan i jednostavan softver za 3D ispis kojem vjeruju milijuni korisnika. Podesite svoj 3D model s više od 400 postavki za najbolje rezultate rezanja i ispisa.
    hu_HU: Ingyenes, könnyen használható 3D nyomtatószoftver, amelyben több millió felhasználó bízik. Finomhangolja 3D modelljét több mint 400 beállítással a legjobb szeletelési és nyomtatási eredmények elérése érdekében.
    it_IT: Software di stampa 3D gratuito e facile da usare, scelto da milioni di utenti. Perfeziona il tuo modello 3D con oltre 400 impostazioni per ottenere i migliori risultati di slicing e stampa.
    ja_JP: 数百万人のユーザーに信頼されている、無料で使いやすい3Dプリントソフトウェア。400以上の設定項目で3Dモデルを微調整し、最適なスライスとプリント結果を実現できます。
    ko_KR: 수백만 명의 사용자가 신뢰하는 무료의 사용하기 쉬운 3D 프린팅 소프트웨어입니다. 400개 이상의 설정으로 3D 모델을 세밀하게 조정하여 최상의 슬라이싱 및 프린팅 결과를 얻으세요.
    ml_IN: ദശലക്ഷക്കണക്കിന് ഉപയോക്താക്കൾ വിശ്വസിക്കുന്ന സൗജന്യവും ഉപയോഗിക്കാൻ എളുപ്പമുള്ളതുമായ 3D പ്രിന്റിംഗ് സോഫ്റ്റ്‌വെയർ. മികച്ച സ്ലൈസിംഗ്, പ്രിന്റിംഗ് ഫലങ്ങൾക്കായി 400+ ക്രമീകരണങ്ങൾ ഉപയോഗിച്ച് നിങ്ങളുടെ 3D മോഡലിനെ ഫൈൻ-ട്യൂൺ ചെയ്യുക.
    nb_NO: Gratis og brukervennlig 3D-utskriftsprogramvare som millioner av brukere stoler på. Finjuster 3D-modellen din med over 400 innstillinger for best mulig skjære- og utskriftsresultat.
    nl_NL: Gratis, gebruiksvriendelijke 3D-printsoftware die door miljoenen gebruikers wordt vertrouwd. Optimaliseer je 3D-model met meer dan 400 instellingen voor de beste slice- en printresultaten.
    pl_PL: Darmowe, łatwe w obsłudze oprogramowanie do druku 3D, któremu zaufały miliony użytkowników. Dopracuj swój model 3D dzięki ponad 400 ustawieniom, aby uzyskać najlepsze rezultaty cięcia i drukowania.
    pt_BR: Software de impressão 3D gratuito e fácil de usar, confiável por milhões de usuários. Ajuste seu modelo 3D com mais de 400 configurações para obter os melhores resultados de fatiamento e impressão.
    ro_RO: Software de imprimare 3D gratuit și ușor de utilizat, în care milioane de utilizatori au încredere. Configurați-vă modelul 3D cu peste 400 de setări pentru cele mai bune rezultate de tăiere și imprimare.
    ru_RU: Бесплатное и простое в использовании программное обеспечение для 3D-печати, которому доверяют миллионы пользователей. Настройте свою 3D-модель с помощью более чем 400 параметров для достижения наилучших результатов нарезки и печати.
    sk_SK: Bezplatný a ľahko použiteľný softvér na 3D tlač, ktorému dôverujú milióny používateľov. Dolaďte si svoj 3D model pomocou viac ako 400 nastavení pre dosiahnutie najlepších výsledkov pri krájaní a tlači.
    sv_SE: Gratis och lättanvänd 3D-utskriftsprogramvara som miljontals användare litar på. Finjustera din 3D-modell med över 400 inställningar för bästa möjliga resultat vid skärning och utskrift.
    tr_TR: Milyonlarca kullanıcının güvendiği, ücretsiz ve kullanımı kolay 3D baskı yazılımı. En iyi dilimleme ve baskı sonuçları için 400'den fazla ayarla 3D modelinizi hassas bir şekilde ayarlayın.
    zh_CN: 提供 400 多项设置的易用 3D 打印切片软件。
    zh_TW: 提供 400 多項設定的易用 3D 列印切片軟體。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/cura-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/cura-logo.png
  title:
    en_US: Cura (LinuxServer.io)
    ca_ES: Cura (LinuxServer.io)
    cs_CZ: Cura (LinuxServer.io)
    da_DK: Cura (LinuxServer.io)
    de_DE: Cura (LinuxServer.io)
    el_GR: Cura (LinuxServer.io)
    en_GB: Cura (LinuxServer.io)
    es_ES: Cura (LinuxServer.io)
    fr_FR: Cura (LinuxServer.io)
    ga_IE: Cura (LinuxServer.io)
    hr_HR: Cura (LinuxServer.io)
    hu_HU: Cura (LinuxServer.io)
    it_IT: Cura (LinuxServer.io)
    ja_JP: Cura (LinuxServer.io)
    ko_KR: Cura (LinuxServer.io)
    ml_IN: Cura (LinuxServer.io)
    nb_NO: Cura (LinuxServer.io)
    nl_NL: Cura (LinuxServer.io)
    pl_PL: Cura (LinuxServer.io)
    pt_BR: Cura (LinuxServer.io)
    ro_RO: Cura (LinuxServer.io)
    ru_RU: Cura (LinuxServer.io)
    sk_SK: Cura (LinuxServer.io)
    sv_SE: Cura (LinuxServer.io)
    tr_TR: Cura (LinuxServer.io)
    zh_CN: Cura（LinuxServer.io）
    zh_TW: Cura（LinuxServer.io）
  category: Productivity
  id: wisdomsky.linuxserver.linuxservercura
  port_map: '3000'
  version: 5.13.0
