name: linuxserver-winegui
services:
  app:
    image: linuxserver/winegui:4.4.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/winegui/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverwinegui/assets/icon.png
  title:
    en_US: Winegui (LinuxServer.io)
    ca_ES: Winegui (LinuxServer.io)
    cs_CZ: Winegui (LinuxServer.io)
    da_DK: Winegui (LinuxServer.io)
    de_DE: Winegui (LinuxServer.io)
    el_GR: Winegui (LinuxServer.io)
    en_GB: Winegui (LinuxServer.io)
    es_ES: Winegui (LinuxServer.io)
    fr_FR: Winegui (LinuxServer.io)
    ga_IE: Winegui (LinuxServer.io)
    hr_HR: Winegui (LinuxServer.io)
    hu_HU: Winegui (LinuxServer.io)
    it_IT: Winegui (LinuxServer.io)
    ja_JP: Winegui (LinuxServer.io)
    ko_KR: Winegui (LinuxServer.io)
    ml_IN: Winegui (LinuxServer.io)
    nb_NO: Winegui (LinuxServer.io)
    nl_NL: Winegui (LinuxServer.io)
    pl_PL: Winegui (LinuxServer.io)
    pt_BR: Winegui (LinuxServer.io)
    ro_RO: Winegui (LinuxServer.io)
    ru_RU: Winegui (LinuxServer.io)
    sk_SK: Winegui (LinuxServer.io)
    sv_SE: Winegui (LinuxServer.io)
    tr_TR: Winegui (LinuxServer.io)
    zh_CN: Winegui（LinuxServer.io）
    zh_TW: Winegui（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverwinegui
  port_map: '3000'
  version: 4.4.0
