name: linuxserver-swag
services:
  app:
    image: linuxserver/swag:5.8.0@sha256:9652efe2cfd9ee5566c9e7dfe445266eb7af4853ce7a1273be9532193d14a4b9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      URL: ''
      VALIDATION: ''
      SUBDOMAINS: ''
      CERTPROVIDER: ''
      CERT_PROFILE: ''
      DNSPLUGIN: ''
      PROPAGATION: ''
      EMAIL: ''
      ONLY_SUBDOMAINS: ''
      EXTRA_DOMAINS: ''
      STAGING: ''
      DISABLE_F2B: ''
      SWAG_AUTORELOAD: ''
      SWAG_AUTORELOAD_WATCHLIST: ''
    ports:
      - target: 443
        published: 443
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/swag/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverswag/assets/icon.gif
  title:
    en_US: Swag (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverswag
  port_map: '80'
  version: 5.8.0
