name: linuxserver-luanti
services:
  app:
    image: linuxserver/luanti:5.17.0@sha256:27aac7373e802c335c1e70e782482fd5782a92baa2b5fdcb97f0e7ab01d07e3c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CLI_ARGS: ''
    ports:
      - target: 30000
        published: 30000
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/luanti/config/.minetest
        target: /config/.minetest
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverluanti/assets/icon.png
  title:
    en_US: Luanti (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverluanti
  port_map: '30000'
  version: 5.17.0
