name: linuxserver-weixin
services:
  app:
    image: linuxserver/weixin:version-f1376de7@sha256:6dcb5b57e774d61e20f6c82294af1e904d0585145fe74b09db91ec38654aa59b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/weixin/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverweixin/assets/icon.png
  title:
    en_US: Weixin (LinuxServer.io)
    zh_CN: 微信（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverweixin
  port_map: '3000'
  version: version-f1376de7
