name: linuxserver-weixin
services:
  app:
    image: linuxserver/weixin:version-f1376de7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/weixin/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverweixin/assets/icon.png
  title:
    en_US: Weixin (LinuxServer.io)
    ca_ES: Weixin (LinuxServer.io)
    cs_CZ: Weixin (LinuxServer.io)
    da_DK: Weixin (LinuxServer.io)
    de_DE: Weixin (LinuxServer.io)
    el_GR: Weixin (LinuxServer.io)
    en_GB: Weixin (LinuxServer.io)
    es_ES: Weixin (LinuxServer.io)
    fr_FR: Weixin (LinuxServer.io)
    ga_IE: Weixin (LinuxServer.io)
    hr_HR: Weixin (LinuxServer.io)
    hu_HU: Weixin (LinuxServer.io)
    it_IT: Weixin (LinuxServer.io)
    ja_JP: Weixin (LinuxServer.io)
    ko_KR: Weixin (LinuxServer.io)
    ml_IN: Weixin (LinuxServer.io)
    nb_NO: Weixin (LinuxServer.io)
    nl_NL: Weixin (LinuxServer.io)
    pl_PL: Weixin (LinuxServer.io)
    pt_BR: Weixin (LinuxServer.io)
    ro_RO: Weixin (LinuxServer.io)
    ru_RU: Weixin (LinuxServer.io)
    sk_SK: Weixin (LinuxServer.io)
    sv_SE: Weixin (LinuxServer.io)
    tr_TR: Weixin (LinuxServer.io)
    zh_CN: 微信（LinuxServer.io）
    zh_TW: 微信（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverweixin
  port_map: '3000'
  version: version-f1376de7
