name: linuxserver-pylon
services:
  app:
    image: linuxserver/pylon:2.10.0@sha256:be84d92b6c99659aeef60398763d240cd89927e6dda6f3d193573bb47bd367ae
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      GITURL: ''
      PYUSER: ''
      PYPASS: ''
    ports:
      - target: 3131
        published: 3131
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pylon/config
        target: /config
      - type: bind
        source: /DATA/AppData/pylon/code
        target: /code
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverpylon/assets/icon.png
  title:
    en_US: Pylon
    zh_CN: Pylon
    ca_ES: Pylon
    cs_CZ: Pylon
    da_DK: Pylon
    de_DE: Pylon
    el_GR: Pylon
    en_GB: Pylon
    es_ES: Pylon
    fr_FR: Pylon
    ga_IE: Pylon
    hr_HR: Pylon
    hu_HU: Pylon
    it_IT: Pylon
    ja_JP: Pylon
    ko_KR: Pylon
    ml_IN: Pylon
    nb_NO: Pylon
    nl_NL: Pylon
    pl_PL: Pylon
    pt_BR: Pylon
    ro_RO: Pylon
    ru_RU: Pylon
    sk_SK: Pylon
    sv_SE: Pylon
    tr_TR: Pylon
    zh_TW: Pylon
  port_map: '3131'
  id: wisdomsky.linuxserver.linuxserverpylon
  version: 2.10.0
