name: linuxserver-socket-proxy
services:
  app:
    image: linuxserver/socket-proxy:3.4.4@sha256:7f932344a3a66a2a54a34001e8e78e60ec14dcd9c522e74a5b6420ac9db18afd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/socket-proxy/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserversocketproxy/assets/icon.png
  title:
    en_US: Socket proxy (LinuxServer.io)
    zh_CN: Socket proxy（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserversocketproxy
  port_map: '80'
  version: 3.4.4
