name: linuxserver-audacity
services:
  app:
    image: linuxserver/audacity:4.0.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/audacity/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveraudacity/assets/icon.png
  title:
    en_US: Audacity (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserveraudacity
  port_map: '3000'
  version: 4.0.0
