name: linuxserver-audacity
services:
  app:
    image: linuxserver/audacity:4.0.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/audacity/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveraudacity/assets/icon.png
  title:
    en_US: Audacity (LinuxServer.io)
    ca_ES: Audacity (LinuxServer.io)
    cs_CZ: Audacity (LinuxServer.io)
    da_DK: Audacity (LinuxServer.io)
    de_DE: Audacity (LinuxServer.io)
    el_GR: Audacity (LinuxServer.io)
    en_GB: Audacity (LinuxServer.io)
    es_ES: Audacity (LinuxServer.io)
    fr_FR: Audacity (LinuxServer.io)
    ga_IE: Audacity (LinuxServer.io)
    hr_HR: Audacity (LinuxServer.io)
    hu_HU: Audacity (LinuxServer.io)
    it_IT: Audacity (LinuxServer.io)
    ja_JP: Audacity (LinuxServer.io)
    ko_KR: Audacity (LinuxServer.io)
    ml_IN: Audacity (LinuxServer.io)
    nb_NO: Audacity (LinuxServer.io)
    nl_NL: Audacity (LinuxServer.io)
    pl_PL: Audacity (LinuxServer.io)
    pt_BR: Audacity (LinuxServer.io)
    ro_RO: Audacity (LinuxServer.io)
    ru_RU: Audacity (LinuxServer.io)
    sk_SK: Audacity (LinuxServer.io)
    sv_SE: Audacity (LinuxServer.io)
    tr_TR: Audacity (LinuxServer.io)
    zh_CN: Audacity（LinuxServer.io）
    zh_TW: Audacity（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserveraudacity
  port_map: '3000'
  version: 4.0.0
