name: linuxserver-ungoogled-chromium
services:
  app:
    image: linuxserver/ungoogled-chromium:153.0.8010@sha256:004facf73e08a6c2180b87aff529b349902e9cf82ed922bc9343671d42a59da2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ungoogled-chromium/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverungoogledchromium/assets/icon.png
  title:
    en_US: Ungoogled chromium (LinuxServer.io)
    ca_ES: Ungoogled chromium (LinuxServer.io)
    cs_CZ: Ungoogled chromium (LinuxServer.io)
    da_DK: Ungoogled chromium (LinuxServer.io)
    de_DE: Ungoogled chromium (LinuxServer.io)
    el_GR: Ungoogled chromium (LinuxServer.io)
    en_GB: Ungoogled chromium (LinuxServer.io)
    es_ES: Ungoogled chromium (LinuxServer.io)
    fr_FR: Ungoogled chromium (LinuxServer.io)
    ga_IE: Ungoogled chromium (LinuxServer.io)
    hr_HR: Ungoogled chromium (LinuxServer.io)
    hu_HU: Ungoogled chromium (LinuxServer.io)
    it_IT: Ungoogled chromium (LinuxServer.io)
    ja_JP: Ungoogled chromium (LinuxServer.io)
    ko_KR: Ungoogled chromium (LinuxServer.io)
    ml_IN: Ungoogled chromium (LinuxServer.io)
    nb_NO: Ungoogled chromium (LinuxServer.io)
    nl_NL: Ungoogled chromium (LinuxServer.io)
    pl_PL: Ungoogled chromium (LinuxServer.io)
    pt_BR: Ungoogled chromium (LinuxServer.io)
    ro_RO: Ungoogled chromium (LinuxServer.io)
    ru_RU: Ungoogled chromium (LinuxServer.io)
    sk_SK: Ungoogled chromium (LinuxServer.io)
    sv_SE: Ungoogled chromium (LinuxServer.io)
    tr_TR: Ungoogled chromium (LinuxServer.io)
    zh_CN: Ungoogled chromium（LinuxServer.io）
    zh_TW: Ungoogled chromium（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverungoogledchromium
  port_map: '3000'
  version: 153.0.8010
