name: linuxserver-ungoogled-chromium
services:
  app:
    image: linuxserver/ungoogled-chromium:153.0.8010
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ungoogled-chromium/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverungoogledchromium/assets/icon.png
  title:
    en_US: Ungoogled chromium (LinuxServer.io)
    zh_CN: Ungoogled chromium（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverungoogledchromium
  port_map: '3000'
  version: 153.0.8010
