name: linuxserver-onlyoffice
services:
  app:
    image: linuxserver/onlyoffice:9.4.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/onlyoffice/config
        target: /config
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_US: ONLYOFFICE provides a full range of tools to create, edit and collaborate on text documents, spreadsheets, presentations, PDF forms and regular PDF files on web, desktop and mobile platforms.
    ca_ES: ONLYOFFICE ofereix una gamma completa d'eines per crear, editar i col·laborar en documents de text, fulls de càlcul, presentacions, formularis PDF i fitxers PDF normals en plataformes web, d'escriptori i mòbils.
    cs_CZ: ONLYOFFICE nabízí kompletní škálu nástrojů pro vytváření, úpravy a spolupráci na textových dokumentech, tabulkách, prezentacích, PDF formulářích a běžných PDF souborech na webových, stolních i mobilních platformách.
    da_DK: ONLYOFFICE tilbyder et komplet udvalg af værktøjer til at oprette, redigere og samarbejde om tekstdokumenter, regneark, præsentationer, PDF-formularer og almindelige PDF-filer på web-, desktop- og mobilplatforme.
    de_DE: ONLYOFFICE bietet eine vollständige Palette von Tools zum Erstellen, Bearbeiten und gemeinsamen Bearbeiten von Textdokumenten, Tabellenkalkulationen, Präsentationen, PDF-Formularen und regulären PDF-Dateien auf Web-, Desktop- und mobilen Plattformen.
    el_GR: Το ONLYOFFICE παρέχει μια πλήρη γκάμα εργαλείων για τη δημιουργία, την επεξεργασία και τη συνεργασία σε έγγραφα κειμένου, υπολογιστικά φύλλα, παρουσιάσεις, φόρμες PDF και κανονικά αρχεία PDF σε διαδικτυακές, επιτραπέζιες και κινητές πλατφόρμες.
    en_GB: Onlyoffice provides a full range of tools to create, edit and collaborate on text documents, spreadsheets, presentations, Pdf forms and regular Pdf files on web, desktop and mobile platforms.
    es_ES: ONLYOFFICE proporciona una gama completa de herramientas para crear, editar y colaborar en documentos de texto, hojas de cálculo, presentaciones, formularios PDF y archivos PDF normales en plataformas web, de escritorio y móviles.
    fr_FR: ONLYOFFICE propose une gamme complète d'outils pour créer, modifier et collaborer sur des documents texte, des feuilles de calcul, des présentations, des formulaires PDF et des fichiers PDF classiques sur les plateformes web, de bureau et mobiles.
    ga_IE: Cuireann ONLYOFFICE réimse iomlán uirlisí ar fáil chun doiciméid téacs, scarbhileoga, cur i láthair, foirmeacha PDF agus comhaid PDF rialta a chruthú, a chur in eagar agus comhoibriú orthu ar ardáin ghréasáin, deisce agus soghluaiste.
    hr_HR: ONLYOFFICE nudi cijeli niz alata za izradu, uređivanje i suradnju na tekstualnim dokumentima, proračunskim tablicama, prezentacijama, PDF obrascima i običnim PDF datotekama na webu, stolnim računalima i mobilnim platformama.
    hu_HU: Az ONLYOFFICE eszközök teljes skáláját kínálja szöveges dokumentumok, táblázatok, prezentációk, PDF űrlapok és hagyományos PDF fájlok létrehozásához, szerkesztéséhez és közös használatához webes, asztali és mobil platformokon.
    it_IT: ONLYOFFICE offre una gamma completa di strumenti per creare, modificare e collaborare su documenti di testo, fogli di calcolo, presentazioni, moduli PDF e normali file PDF su piattaforme web, desktop e mobili.
    ja_JP: ONLYOFFICEは、Web、デスクトップ、モバイルプラットフォーム上で、テキスト文書、スプレッドシート、プレゼンテーション、PDFフォーム、通常のPDFファイルを作成、編集、共同作業するためのあらゆるツールを提供します。
    ko_KR: ONLYOFFICE는 웹, 데스크톱 및 모바일 플랫폼에서 텍스트 문서, 스프레드시트, 프레젠테이션, PDF 양식 및 일반 PDF 파일을 생성, 편집 및 공동 작업할 수 있는 모든 도구를 제공합니다.
    ml_IN: വെബ്, ഡെസ്ക്ടോപ്പ്, മൊബൈൽ പ്ലാറ്റ്‌ഫോമുകളിൽ ടെക്സ്റ്റ് ഡോക്യുമെന്റുകൾ, സ്‌പ്രെഡ്‌ഷീറ്റുകൾ, പ്രസന്റേഷനുകൾ, PDF ഫോമുകൾ, സാധാരണ PDF ഫയലുകൾ എന്നിവ സൃഷ്‌ടിക്കാനും എഡിറ്റ് ചെയ്യാനും സഹകരിക്കാനുമുള്ള പൂർണ്ണമായ ഉപകരണങ്ങൾ ONLYOFFICE നൽകുന്നു.
    nb_NO: ONLYOFFICE tilbyr et komplett utvalg av verktøy for å opprette, redigere og samarbeide om tekstdokumenter, regneark, presentasjoner, PDF-skjemaer og vanlige PDF-filer på nett, datamaskin og mobilplattformer.
    nl_NL: ONLYOFFICE biedt een volledig scala aan tools voor het maken, bewerken en samenwerken aan tekstdocumenten, spreadsheets, presentaties, PDF-formulieren en gewone PDF-bestanden op web-, desktop- en mobiele platformen.
    pl_PL: ONLYOFFICE udostępnia pełną gamę narzędzi do tworzenia, edytowania i wspólnej pracy nad dokumentami tekstowymi, arkuszami kalkulacyjnymi, prezentacjami, formularzami PDF i zwykłymi plikami PDF na platformach internetowych, stacjonarnych i mobilnych.
    pt_BR: O ONLYOFFICE oferece uma gama completa de ferramentas para criar, editar e colaborar em documentos de texto, planilhas, apresentações, formulários PDF e arquivos PDF comuns em plataformas web, desktop e móveis.
    ro_RO: ONLYOFFICE oferă o gamă completă de instrumente pentru a crea, edita și colabora la documente text, foi de calcul, prezentări, formulare PDF și fișiere PDF obișnuite pe platforme web, desktop și mobile.
    ru_RU: ONLYOFFICE предоставляет полный набор инструментов для создания, редактирования и совместной работы над текстовыми документами, электронными таблицами, презентациями, PDF-формами и обычными PDF-файлами на веб-, настольных и мобильных платформах.
    sk_SK: ONLYOFFICE poskytuje kompletný sortiment nástrojov na vytváranie, úpravu a spoluprácu na textových dokumentoch, tabuľkách, prezentáciách, PDF formulároch a bežných PDF súboroch na webových, desktopových a mobilných platformách.
    sv_SE: ONLYOFFICE erbjuder ett komplett utbud av verktyg för att skapa, redigera och samarbeta kring textdokument, kalkylblad, presentationer, PDF-formulär och vanliga PDF-filer på webben, datorer och mobila plattformar.
    tr_TR: ONLYOFFICE, web, masaüstü ve mobil platformlarda metin belgeleri, elektronik tablolar, sunumlar, PDF formları ve normal PDF dosyaları oluşturmak, düzenlemek ve bunlar üzerinde iş birliği yapmak için eksiksiz bir araç yelpazesi sunar.
    zh_CN: ONLYOFFICE 提供完整的工具，可在网页、桌面和移动平台上创建、编辑和协作处理文字文档、电子表格、演示文稿、PDF 表单和普通 PDF 文件。
    zh_TW: ONLYOFFICE 提供完整的工具，可在網頁、桌面和移動平臺上建立、編輯和協作處理文字文件、電子表格、簡報、PDF 表單和普通 PDF 檔案。
  tagline:
    en_US: Provides a full range of tools to create, edit and collaborate on text documents, spreadsheets, presentations, PDF forms and regular PDF files on web, desktop and mobile platforms.
    ca_ES: Ofereix una gamma completa d'eines per crear, editar i col·laborar en documents de text, fulls de càlcul, presentacions, formularis PDF i fitxers PDF normals en plataformes web, d'escriptori i mòbils.
    cs_CZ: Poskytuje kompletní škálu nástrojů pro vytváření, úpravy a spolupráci na textových dokumentech, tabulkách, prezentacích, PDF formulářích a běžných PDF souborech na webových, stolních a mobilních platformách.
    da_DK: Indeholder et komplet udvalg af værktøjer til at oprette, redigere og samarbejde om tekstdokumenter, regneark, præsentationer, PDF-formularer og almindelige PDF-filer på web-, desktop- og mobilplatforme.
    de_DE: Bietet eine umfassende Palette an Werkzeugen zum Erstellen, Bearbeiten und gemeinsamen Bearbeiten von Textdokumenten, Tabellenkalkulationen, Präsentationen, PDF-Formularen und regulären PDF-Dateien auf Web-, Desktop- und mobilen Plattformen.
    el_GR: Παρέχει μια πλήρη γκάμα εργαλείων για τη δημιουργία, την επεξεργασία και τη συνεργασία σε έγγραφα κειμένου, υπολογιστικά φύλλα, παρουσιάσεις, φόρμες PDF και κανονικά αρχεία PDF σε διαδικτυακές, επιτραπέζιες και κινητές πλατφόρμες.
    en_GB: Provides a full range of tools to create, edit and collaborate on text documents, spreadsheets, presentations, Pdf forms and regular Pdf files on web, desktop and mobile platforms.
    es_ES: Proporciona una gama completa de herramientas para crear, editar y colaborar en documentos de texto, hojas de cálculo, presentaciones, formularios PDF y archivos PDF normales en plataformas web, de escritorio y móviles.
    fr_FR: Offre une gamme complète d'outils pour créer, modifier et collaborer sur des documents texte, des feuilles de calcul, des présentations, des formulaires PDF et des fichiers PDF classiques sur les plateformes web, de bureau et mobiles.
    ga_IE: Cuireann sé réimse iomlán uirlisí ar fáil chun doiciméid téacs, scarbhileoga, cur i láthair, foirmeacha PDF agus comhaid PDF rialta a chruthú, a chur in eagar agus comhoibriú orthu ar ardáin ghréasáin, deisce agus soghluaiste.
    hr_HR: Pruža cijeli niz alata za izradu, uređivanje i suradnju na tekstualnim dokumentima, proračunskim tablicama, prezentacijama, PDF obrascima i običnim PDF datotekama na webu, stolnim računalima i mobilnim platformama.
    hu_HU: Eszközök teljes skáláját kínálja szöveges dokumentumok, táblázatok, prezentációk, PDF űrlapok és hagyományos PDF fájlok létrehozásához, szerkesztéséhez és közös szerkesztéséhez webes, asztali és mobil platformokon.
    it_IT: Offre una gamma completa di strumenti per creare, modificare e collaborare su documenti di testo, fogli di calcolo, presentazioni, moduli PDF e normali file PDF su piattaforme web, desktop e mobili.
    ja_JP: ウェブ、デスクトップ、モバイルプラットフォーム上で、テキスト文書、スプレッドシート、プレゼンテーション、PDFフォーム、通常のPDFファイルを作成、編集、共同作業するためのあらゆるツールを提供します。
    ko_KR: 웹, 데스크톱 및 모바일 플랫폼에서 텍스트 문서, 스프레드시트, 프레젠테이션, PDF 양식 및 일반 PDF 파일을 생성, 편집 및 공동 작업할 수 있는 모든 도구를 제공합니다.
    ml_IN: വെബ്, ഡെസ്ക്ടോപ്പ്, മൊബൈൽ പ്ലാറ്റ്‌ഫോമുകളിൽ ടെക്സ്റ്റ് ഡോക്യുമെന്റുകൾ, സ്‌പ്രെഡ്‌ഷീറ്റുകൾ, അവതരണങ്ങൾ, PDF ഫോമുകൾ, സാധാരണ PDF ഫയലുകൾ എന്നിവ സൃഷ്‌ടിക്കാനും എഡിറ്റ് ചെയ്യാനും സഹകരിക്കാനുമുള്ള പൂർണ്ണമായ ഉപകരണങ്ങൾ ഇത് നൽകുന്നു.
    nb_NO: Tilbyr et komplett utvalg av verktøy for å opprette, redigere og samarbeide om tekstdokumenter, regneark, presentasjoner, PDF-skjemaer og vanlige PDF-filer på nett, datamaskin og mobilplattformer.
    nl_NL: Biedt een volledig scala aan tools voor het maken, bewerken en samenwerken aan tekstdocumenten, spreadsheets, presentaties, PDF-formulieren en gewone PDF-bestanden op web-, desktop- en mobiele platformen.
    pl_PL: Zapewnia pełną gamę narzędzi do tworzenia, edytowania i współpracy nad dokumentami tekstowymi, arkuszami kalkulacyjnymi, prezentacjami, formularzami PDF i zwykłymi plikami PDF na platformach internetowych, stacjonarnych i mobilnych.
    pt_BR: Oferece um conjunto completo de ferramentas para criar, editar e colaborar em documentos de texto, planilhas, apresentações, formulários PDF e arquivos PDF comuns em plataformas web, desktop e móveis.
    ro_RO: Oferă o gamă completă de instrumente pentru crearea, editarea și colaborarea la documente text, foi de calcul, prezentări, formulare PDF și fișiere PDF obișnuite pe platforme web, desktop și mobile.
    ru_RU: Предоставляет полный набор инструментов для создания, редактирования и совместной работы над текстовыми документами, электронными таблицами, презентациями, PDF-формами и обычными PDF-файлами на веб-, настольных и мобильных платформах.
    sk_SK: Poskytuje kompletný sortiment nástrojov na vytváranie, úpravu a spoluprácu na textových dokumentoch, tabuľkách, prezentáciách, PDF formulároch a bežných PDF súboroch na webových, desktopových a mobilných platformách.
    sv_SE: Erbjuder ett komplett utbud av verktyg för att skapa, redigera och samarbeta kring textdokument, kalkylblad, presentationer, PDF-formulär och vanliga PDF-filer på webben, datorer och mobila plattformar.
    tr_TR: Web, masaüstü ve mobil platformlarda metin belgeleri, elektronik tablolar, sunumlar, PDF formları ve normal PDF dosyaları oluşturmak, düzenlemek ve bunlar üzerinde iş birliği yapmak için eksiksiz bir araç yelpazesi sunar.
    zh_CN: 跨网页、桌面和移动端协作编辑办公文档与 PDF。
    zh_TW: 跨網頁、桌面和移動端協作編輯辦公文件與 PDF。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/onlyoffice-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/onlyoffice-logo.png
  title:
    en_US: Onlyoffice (LinuxServer.io)
    ca_ES: Onlyoffice (LinuxServer.io)
    cs_CZ: Onlyoffice (LinuxServer.io)
    da_DK: Onlyoffice (LinuxServer.io)
    de_DE: Onlyoffice (LinuxServer.io)
    el_GR: Onlyoffice (LinuxServer.io)
    en_GB: Onlyoffice (LinuxServer.io)
    es_ES: Onlyoffice (LinuxServer.io)
    fr_FR: Onlyoffice (LinuxServer.io)
    ga_IE: Onlyoffice (LinuxServer.io)
    hr_HR: Onlyoffice (LinuxServer.io)
    hu_HU: Onlyoffice (LinuxServer.io)
    it_IT: Onlyoffice (LinuxServer.io)
    ja_JP: Onlyoffice (LinuxServer.io)
    ko_KR: Onlyoffice (LinuxServer.io)
    ml_IN: Onlyoffice (LinuxServer.io)
    nb_NO: Onlyoffice (LinuxServer.io)
    nl_NL: Onlyoffice (LinuxServer.io)
    pl_PL: Onlyoffice (LinuxServer.io)
    pt_BR: Onlyoffice (LinuxServer.io)
    ro_RO: Onlyoffice (LinuxServer.io)
    ru_RU: Onlyoffice (LinuxServer.io)
    sk_SK: Onlyoffice (LinuxServer.io)
    sv_SE: Onlyoffice (LinuxServer.io)
    tr_TR: Onlyoffice (LinuxServer.io)
    zh_CN: Onlyoffice（LinuxServer.io）
    zh_TW: Onlyoffice（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserveronlyoffice
  port_map: '3000'
  version: 9.4.0
