name: linuxserver-kali-linux
services:
  app:
    image: linuxserver/kali-linux:version-aa96051d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SUBFOLDER: ''
      TITLE: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: SUBFOLDER
          description:
            en_us: Specify a subfolder to use with reverse proxies, IE /subfolder/ [OPTIONAL]
        - container: TITLE
          description:
            en_us: String which will be used as page/tab title in the web browser. [OPTIONAL]
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /srv/lsio/kali-linux/config
        target: /config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Kali-linux - is an Advanced Penetration Testing Linux distribution used for Penetration Testing, Ethical Hacking and network security assessments. KALI LINUX ™ is a trademark of OffSec.
  tagline:
    en_us: is an Advanced Penetration Testing Linux distribution used for Penetration Testing, Ethical Hacking and network security assessments. KALI LINUX ™ is a trademark of OffSec.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/kali-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/kali-logo.png
  title:
    en_us: Kali linux
  category: LinuxServer.io
