name: linuxserver-calibre-web
services:
  app:
    image: linuxserver/calibre-web:0.6.27
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DOCKER_MODS: ''
      OAUTHLIB_RELAX_TOKEN_SCOPE: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: DOCKER_MODS
          description:
            en_US: '#optional & x86-64 only Adds the ability to perform ebook conversion [OPTIONAL]'
        - container: OAUTHLIB_RELAX_TOKEN_SCOPE
          description:
            en_US: Optionally set this to allow Google OAUTH to work [OPTIONAL]
    ports:
      - target: 8083
        published: 8083
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/calibre-web/config
        target: /config
      - type: bind
        source: /DATA/AppData/calibre-web/books
        target: /books
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Calibre-web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database. It is also possible to integrate google drive and edit metadata and your calibre library through the app itself. This software is a fork of library and licensed under the GPL v3 License.
    ca_ES: Calibre-web és una aplicació web que ofereix una interfície neta per navegar, llegir i descarregar llibres electrònics utilitzant una base de dades de Calibre existent. També és possible integrar Google Drive i editar metadades i la biblioteca de Calibre a través de la mateixa aplicació. Aquest programari és una bifurcació de la biblioteca i té llicència GPL v3.
    cs_CZ: Calibre-web je webová aplikace poskytující přehledné rozhraní pro prohlížení, čtení a stahování elektronických knih pomocí existující databáze Calibre. Je také možné integrovat Disk Google a upravovat metadata a vaši knihovnu Calibre prostřednictvím samotné aplikace. Tento software je odvozen od knihovny a je licencován pod licencí GPL v3.
    da_DK: Calibre-web er en webapp, der tilbyder en overskuelig brugerflade til at browse, læse og downloade e-bøger ved hjælp af en eksisterende Calibre-database. Det er også muligt at integrere Google Drive og redigere metadata og dit Calibre-bibliotek gennem selve appen. Denne software er en forgrening af et bibliotek og licenseret under GPL v3-licensen.
    de_DE: Calibre-web ist eine Webanwendung mit einer übersichtlichen Benutzeroberfläche zum Durchsuchen, Lesen und Herunterladen von eBooks aus einer bestehenden Calibre-Datenbank. Die Anwendung ermöglicht außerdem die Integration von Google Drive sowie die Bearbeitung von Metadaten und der eigenen Calibre-Bibliothek. Diese Software ist eine Weiterentwicklung der Calibre-Bibliothek und unter der GPL v3-Lizenz lizenziert.
    el_GR: Το Calibre-web είναι μια διαδικτυακή εφαρμογή που παρέχει μια καθαρή διεπαφή για περιήγηση, ανάγνωση και λήψη ηλεκτρονικών βιβλίων χρησιμοποιώντας μια υπάρχουσα βάση δεδομένων Calibre. Είναι επίσης δυνατή η ενσωμάτωση του Google Drive και η επεξεργασία μεταδεδομένων και της βιβλιοθήκης calibre σας μέσω της ίδιας της εφαρμογής. Αυτό το λογισμικό είναι μια διακλάδωση βιβλιοθήκης και διατίθεται με την άδεια GPL v3.
    en_GB: Calibre-web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database. It is also possible to integrate google drive and edit metadata and your calibre library through the app itself. This software is a fork of library and licensed under the Gpl v3 Licence.
    es_ES: Calibre-web es una aplicación web que proporciona una interfaz limpia para explorar, leer y descargar libros electrónicos utilizando una base de datos Calibre existente. También permite integrar Google Drive y editar los metadatos y la biblioteca Calibre directamente desde la aplicación. Este software es una bifurcación de la biblioteca y está licenciado bajo la Licencia Pública General (GPL) v3.
    fr_FR: Calibre-web est une application web offrant une interface claire pour la navigation, la lecture et le téléchargement d'eBooks à partir d'une base de données Calibre existante. Il est également possible d'intégrer Google Drive et de modifier les métadonnées et votre bibliothèque Calibre directement depuis l'application. Ce logiciel est une version dérivée de la bibliothèque et est distribué sous licence GPL v3.
    ga_IE: Is aip ghréasáin é Calibre-web a sholáthraíonn comhéadan glan chun ríomhleabhair a bhrabhsáil, a léamh agus a íoslódáil ag baint úsáide as bunachar sonraí Calibre atá ann cheana féin. Is féidir freisin Google Drive a chomhtháthú agus meiteashonraí agus do leabharlann Calibre a chur in eagar tríd an aip féin. Is forc de leabharlann an bogearra seo agus tá sé ceadúnaithe faoin gCeadúnas GPL v3.
    hr_HR: Calibre-web je web aplikacija koja pruža čisto sučelje za pregledavanje, čitanje i preuzimanje e-knjiga pomoću postojeće Calibre baze podataka. Također je moguće integrirati Google disk i uređivati metapodatke i vašu Calibre biblioteku putem same aplikacije. Ovaj softver je fork biblioteke i licenciran je pod GPL v3 licencom.
    hu_HU: A Calibre-web egy webes alkalmazás, amely letisztult felületet biztosít e-könyvek böngészéséhez, olvasásához és letöltéséhez egy meglévő Calibre adatbázis használatával. Lehetőség van a Google Drive integrálására, valamint a metaadatok és a Calibre könyvtár szerkesztésére is magán az alkalmazáson keresztül. Ez a szoftver egy könyvtár-elágazás, és a GPL v3 licenc alatt áll.
    it_IT: Calibre-web è un'applicazione web che offre un'interfaccia intuitiva per navigare, leggere e scaricare eBook utilizzando un database Calibre esistente. È inoltre possibile integrare Google Drive e modificare i metadati e la propria libreria Calibre direttamente dall'applicazione. Questo software è un fork di una libreria ed è rilasciato sotto licenza GPL v3.
    ja_JP: Calibre-webは、既存のCalibreデータベースを使用して電子書籍を閲覧、閲覧、ダウンロードするためのクリーンなインターフェースを提供するWebアプリケーションです。Googleドライブとの連携や、アプリ自体からメタデータやCalibreライブラリを編集することも可能です。このソフトウェアはライブラリのフォークであり、GPL v3ライセンスの下でライセンスされています。
    ko_KR: Calibre-web은 기존 Calibre 데이터베이스를 활용하여 전자책을 검색, 읽기 및 다운로드할 수 있는 깔끔한 인터페이스를 제공하는 웹 애플리케이션입니다. Google Drive 연동은 물론, 앱 자체에서 메타데이터와 Calibre 라이브러리를 편집할 수도 있습니다. 이 소프트웨어는 library를 기반으로 개발되었으며 GPL v3 라이선스에 따라 배포됩니다.
    ml_IN: നിലവിലുള്ള കാലിബർ ഡാറ്റാബേസ് ഉപയോഗിച്ച് ഇ-ബുക്കുകൾ ബ്രൗസ് ചെയ്യുന്നതിനും വായിക്കുന്നതിനും ഡൗൺലോഡ് ചെയ്യുന്നതിനും വൃത്തിയുള്ള ഒരു ഇന്റർഫേസ് നൽകുന്ന ഒരു വെബ് ആപ്ലിക്കേഷനാണ് കാലിബർ-വെബ്. ആപ്പ് വഴി തന്നെ ഗൂഗിൾ ഡ്രൈവ്, എഡിറ്റ് മെറ്റാഡാറ്റ, നിങ്ങളുടെ കാലിബർ ലൈബ്രറി എന്നിവ സംയോജിപ്പിക്കാനും കഴിയും. ഈ സോഫ്റ്റ്‌വെയർ ഒരു ലൈബ്രറി ഫോർക്ക് ആണ്, കൂടാതെ GPL v3 ലൈസൻസിന് കീഴിൽ ലൈസൻസ് ചെയ്തിട്ടുമുണ്ട്.
    nb_NO: Calibre-web er en nettapp som tilbyr et rent grensesnitt for å bla gjennom, lese og laste ned e-bøker ved hjelp av en eksisterende Calibre-database. Det er også mulig å integrere Google Drive og redigere metadata og Calibre-biblioteket ditt gjennom selve appen. Denne programvaren er en forgrening av bibliotek og lisensiert under GPL v3-lisensen.
    nl_NL: Calibre-web is een webapplicatie met een overzichtelijke interface voor het bladeren, lezen en downloaden van e-books met behulp van een bestaande Calibre-database. Het is ook mogelijk om Google Drive te integreren en metadata en je Calibre-bibliotheek rechtstreeks via de app te bewerken. Deze software is een fork van de bibliotheek en valt onder de GPL v3-licentie.
    pl_PL: Calibre-web to aplikacja internetowa oferująca przejrzysty interfejs do przeglądania, czytania i pobierania e-booków z wykorzystaniem istniejącej bazy danych Calibre. Możliwa jest również integracja z Dyskiem Google oraz edycja metadanych i biblioteki Calibre za pośrednictwem samej aplikacji. To oprogramowanie jest rozwidleniem biblioteki i jest licencjonowane na podstawie licencji GPL v3.
    pt_BR: Calibre-web é um aplicativo web que oferece uma interface limpa para navegar, ler e baixar eBooks usando um banco de dados Calibre existente. Também é possível integrar o Google Drive e editar metadados e sua biblioteca Calibre diretamente pelo aplicativo. Este software é um fork da biblioteca Calibre e licenciado sob a licença GPL v3.
    ro_RO: Calibre-web este o aplicație web care oferă o interfață curată pentru navigarea, citirea și descărcarea cărților electronice folosind o bază de date Calibre existentă. De asemenea, este posibil să integrați Google Drive și să editați metadatele și biblioteca Calibre prin intermediul aplicației în sine. Acest software este o ramură a bibliotecii și este licențiat sub licența GPL v3.
    ru_RU: Calibre-web — это веб-приложение, предоставляющее удобный интерфейс для просмотра, чтения и загрузки электронных книг с использованием существующей базы данных Calibre. Также возможна интеграция с Google Drive и редактирование метаданных и вашей библиотеки Calibre через само приложение. Это программное обеспечение является форком библиотеки и распространяется под лицензией GPL v3.
    sk_SK: Calibre-web je webová aplikácia poskytujúca prehľadné rozhranie na prehliadanie, čítanie a sťahovanie elektronických kníh pomocou existujúcej databázy Calibre. Je tiež možné integrovať Disk Google a upravovať metadáta a vašu knižnicu Calibre prostredníctvom samotnej aplikácie. Tento softvér je fork knižnice a je licencovaný pod licenciou GPL v3.
    sv_SE: Calibre-web är en webbapp som erbjuder ett rent gränssnitt för att bläddra, läsa och ladda ner e-böcker med hjälp av en befintlig Calibre-databas. Det är också möjligt att integrera Google Drive och redigera metadata och ditt Calibre-bibliotek via själva appen. Denna programvara är en förgrening av bibliotek och licensierad under GPL v3-licensen.
    tr_TR: Calibre-web, mevcut bir Calibre veritabanını kullanarak e-kitaplara göz atma, okuma ve indirme işlemlerini kolaylaştıran temiz bir arayüz sunan bir web uygulamasıdır. Ayrıca, Google Drive entegrasyonu, meta verilerin düzenlenmesi ve Calibre kütüphanenizin yönetimi de uygulama üzerinden gerçekleştirilebilir. Bu yazılım, library yazılımının bir türevidir ve GPL v3 Lisansı altında lisanslanmıştır.
    zh_CN: Calibre-web 是一款网页应用，使用现有的 Calibre 数据库，为浏览、阅读和下载电子书提供简洁界面。它还支持集成 Google Drive，并可直接在应用中编辑元数据和 Calibre 书库。该软件是 library 项目的分支，采用 GPL v3 许可证。
    zh_TW: Calibre-web 是一款網頁應用，使用現有的 Calibre 資料庫，為瀏覽、閱讀和下載電子書提供簡潔介面。它還支援整合 Google Drive，並可直接在應用中編輯後設資料和 Calibre 書庫。該軟體是 library 專案的分支，採用 GPL v3 許可證。
  tagline:
    en_US: A web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database. It is also possible to integrate google drive and edit metadata and your calibre library through the app itself. This software is a fork of library and licensed under the GPL v3 License.
    ca_ES: Una aplicació web que proporciona una interfície neta per navegar, llegir i descarregar llibres electrònics utilitzant una base de dades de Calibre existent. També és possible integrar Google Drive i editar metadades i la biblioteca de Calibre a través de la mateixa aplicació. Aquest programari és una bifurcació de la biblioteca i té llicència GPL v3.
    cs_CZ: Webová aplikace poskytující přehledné rozhraní pro prohlížení, čtení a stahování elektronických knih pomocí existující databáze Calibre. Je také možné integrovat Disk Google a upravovat metadata a knihovnu Calibre prostřednictvím samotné aplikace. Tento software je odvozen od knihovny a je licencován pod licencí GPL v3.
    da_DK: En webapp, der tilbyder en overskuelig brugerflade til at browse, læse og downloade e-bøger ved hjælp af en eksisterende Calibre-database. Det er også muligt at integrere Google Drive og redigere metadata og dit Calibre-bibliotek via selve appen. Denne software er en forgrening af et bibliotek og er licenseret under GPL v3-licensen.
    de_DE: Eine Webanwendung mit einer übersichtlichen Benutzeroberfläche zum Durchsuchen, Lesen und Herunterladen von eBooks mithilfe einer bestehenden Calibre-Datenbank. Die Integration von Google Drive sowie die Bearbeitung von Metadaten und Ihrer Calibre-Bibliothek sind direkt in der Anwendung möglich. Diese Software ist eine Weiterentwicklung der bestehenden Bibliothek und unter der GPL v3-Lizenz lizenziert.
    el_GR: Μια εφαρμογή ιστού που παρέχει μια καθαρή διεπαφή για περιήγηση, ανάγνωση και λήψη ηλεκτρονικών βιβλίων χρησιμοποιώντας μια υπάρχουσα βάση δεδομένων Calibre. Είναι επίσης δυνατή η ενσωμάτωση του Google Drive και η επεξεργασία μεταδεδομένων και της βιβλιοθήκης calibre σας μέσω της ίδιας της εφαρμογής. Αυτό το λογισμικό είναι μια διακλάδωση βιβλιοθήκης και διατίθεται με άδεια χρήσης GPL v3.
    en_GB: A web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database. It is also possible to integrate google drive and edit metadata and your calibre library through the app itself. This software is a fork of library and licensed under the Gpl v3 Licence.
    es_ES: Aplicación web con una interfaz limpia para explorar, leer y descargar libros electrónicos utilizando una base de datos Calibre existente. También permite integrar Google Drive y editar los metadatos y la biblioteca Calibre directamente desde la aplicación. Este software es una bifurcación de la biblioteca y está licenciado bajo la Licencia Pública General (GPL) v3.
    fr_FR: Une application web offrant une interface claire pour la navigation, la lecture et le téléchargement d'eBooks à partir d'une base de données Calibre existante. Il est également possible d'intégrer Google Drive et de modifier les métadonnées et votre bibliothèque Calibre directement depuis l'application. Ce logiciel est une version dérivée de la bibliothèque et est distribué sous licence GPL v3.
    ga_IE: Aip ghréasáin a sholáthraíonn comhéadan glan chun ríomhleabhair a bhrabhsáil, a léamh agus a íoslódáil ag baint úsáide as bunachar sonraí Calibre atá ann cheana féin. Is féidir freisin Google Drive a chomhtháthú agus meiteashonraí agus do leabharlann Calibre a chur in eagar tríd an aip féin. Is forc de leabharlann an bogearra seo agus tá sé ceadúnaithe faoin gCeadúnas GPL v3.
    hr_HR: Web aplikacija koja pruža čisto sučelje za pregledavanje, čitanje i preuzimanje e-knjiga pomoću postojeće Calibre baze podataka. Također je moguće integrirati Google disk i uređivati metapodatke i vašu Calibre biblioteku putem same aplikacije. Ovaj softver je ogranak biblioteke i licenciran je pod GPL v3 licencom.
    hu_HU: Egy webes alkalmazás, amely letisztult felületet biztosít e-könyvek böngészéséhez, olvasásához és letöltéséhez egy meglévő Calibre adatbázis használatával. Lehetőség van a Google Drive integrálására, valamint a metaadatok és a Calibre könyvtár szerkesztésére magán az alkalmazáson keresztül. Ez a szoftver egy könyvtár-elágazás, és a GPL v3 licenc alatt áll.
    it_IT: Un'applicazione web che offre un'interfaccia intuitiva per navigare, leggere e scaricare eBook utilizzando un database Calibre esistente. È inoltre possibile integrare Google Drive e modificare i metadati e la propria libreria Calibre direttamente dall'applicazione. Questo software è un fork di una libreria ed è rilasciato sotto licenza GPL v3.
    ja_JP: 既存のCalibreデータベースを使用して電子書籍を閲覧、閲覧、ダウンロードするための、すっきりとしたインターフェースを提供するWebアプリです。Googleドライブとの連携や、アプリ自体からメタデータやCalibreライブラリを編集することも可能です。このソフトウェアはライブラリのフォークであり、GPL v3ライセンスの下でライセンスされています。
    ko_KR: 기존 Calibre 데이터베이스를 활용하여 전자책을 검색, 읽기, 다운로드할 수 있는 깔끔한 인터페이스를 제공하는 웹 애플리케이션입니다. Google Drive 연동 및 메타데이터 편집, Calibre 라이브러리 관리도 가능합니다. 이 소프트웨어는 Library를 기반으로 개발되었으며 GPL v3 라이선스에 따라 배포됩니다.
    ml_IN: നിലവിലുള്ള കാലിബർ ഡാറ്റാബേസ് ഉപയോഗിച്ച് ഇ-ബുക്കുകൾ ബ്രൗസ് ചെയ്യുന്നതിനും വായിക്കുന്നതിനും ഡൗൺലോഡ് ചെയ്യുന്നതിനും വൃത്തിയുള്ള ഒരു ഇന്റർഫേസ് നൽകുന്ന ഒരു വെബ് ആപ്പ്. ആപ്പ് വഴി തന്നെ ഗൂഗിൾ ഡ്രൈവ്, എഡിറ്റ് മെറ്റാഡാറ്റ, നിങ്ങളുടെ കാലിബർ ലൈബ്രറി എന്നിവ സംയോജിപ്പിക്കാനും കഴിയും. ഈ സോഫ്റ്റ്‌വെയർ ഒരു ലൈബ്രറി ഫോർക്ക് ആണ്, കൂടാതെ GPL v3 ലൈസൻസിന് കീഴിൽ ലൈസൻസ് ചെയ്തിരിക്കുന്നു.
    nb_NO: En nettapp som tilbyr et rent grensesnitt for å bla gjennom, lese og laste ned e-bøker ved hjelp av en eksisterende Calibre-database. Det er også mulig å integrere Google Drive og redigere metadata og Calibre-biblioteket ditt gjennom selve appen. Denne programvaren er en forgrening av bibliotek og lisensiert under GPL v3-lisensen.
    nl_NL: Een webapplicatie met een overzichtelijke interface voor het bladeren, lezen en downloaden van e-books met behulp van een bestaande Calibre-database. Integratie met Google Drive en het bewerken van metadata en je Calibre-bibliotheek is ook mogelijk via de app zelf. Deze software is een fork van de bibliotheek en valt onder de GPL v3-licentie.
    pl_PL: Aplikacja internetowa oferująca przejrzysty interfejs do przeglądania, czytania i pobierania e-booków z wykorzystaniem istniejącej bazy danych Calibre. Możliwa jest również integracja z Dyskiem Google oraz edycja metadanych i biblioteki Calibre za pośrednictwem samej aplikacji. To oprogramowanie jest rozwidleniem biblioteki i jest licencjonowane na podstawie licencji GPL v3.
    pt_BR: Um aplicativo web que oferece uma interface limpa para navegar, ler e baixar eBooks usando um banco de dados Calibre existente. Também é possível integrar o Google Drive e editar metadados e sua biblioteca Calibre diretamente pelo aplicativo. Este software é um fork da biblioteca Calibre e licenciado sob a licença GPL v3.
    ro_RO: O aplicație web care oferă o interfață curată pentru navigarea, citirea și descărcarea cărților electronice folosind o bază de date Calibre existentă. De asemenea, este posibilă integrarea Google Drive și editarea metadatelor și a bibliotecii Calibre prin intermediul aplicației în sine. Acest software este o ramură a bibliotecii și este licențiat sub licența GPL v3.
    ru_RU: Веб-приложение, предоставляющее удобный интерфейс для просмотра, чтения и загрузки электронных книг с использованием существующей базы данных Calibre. Также возможна интеграция с Google Drive и редактирование метаданных и вашей библиотеки Calibre через само приложение. Это программное обеспечение является форком библиотеки и распространяется под лицензией GPL v3.
    sk_SK: Webová aplikácia poskytujúca prehľadné rozhranie na prehliadanie, čítanie a sťahovanie elektronických kníh pomocou existujúcej databázy Calibre. Je tiež možné integrovať Disk Google a upravovať metadáta a vašu knižnicu Calibre prostredníctvom samotnej aplikácie. Tento softvér je fork knižnice a je licencovaný pod licenciou GPL v3.
    sv_SE: En webbapp som erbjuder ett rent gränssnitt för att bläddra, läsa och ladda ner e-böcker med hjälp av en befintlig Calibre-databas. Det är också möjligt att integrera Google Drive och redigera metadata och ditt Calibre-bibliotek via själva appen. Denna programvara är en förgrening av bibliotek och licensierad under GPL v3-licensen.
    tr_TR: Mevcut bir Calibre veritabanını kullanarak e-kitaplara göz atma, okuma ve indirme işlemlerini kolaylaştıran, sade bir arayüze sahip bir web uygulaması. Ayrıca Google Drive entegrasyonu, meta verilerin düzenlenmesi ve Calibre kütüphanenizin doğrudan uygulama üzerinden yönetilmesi de mümkün. Bu yazılım, Library'nin bir türevidir ve GPL v3 Lisansı altında lisanslanmıştır.
    zh_CN: 通过网页浏览、阅读和下载 Calibre 书库中的电子书。
    zh_TW: 透過網頁瀏覽、閱讀和下載 Calibre 書庫中的電子書。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/calibre-web-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/calibre-web-icon.png
  title:
    en_US: Calibre web (LinuxServer.io)
    ca_ES: Calibre web (LinuxServer.io)
    cs_CZ: Calibre web (LinuxServer.io)
    da_DK: Calibre web (LinuxServer.io)
    de_DE: Calibre web (LinuxServer.io)
    el_GR: Calibre web (LinuxServer.io)
    en_GB: Calibre web (LinuxServer.io)
    es_ES: Calibre web (LinuxServer.io)
    fr_FR: Calibre web (LinuxServer.io)
    ga_IE: Calibre web (LinuxServer.io)
    hr_HR: Calibre web (LinuxServer.io)
    hu_HU: Calibre web (LinuxServer.io)
    it_IT: Calibre web (LinuxServer.io)
    ja_JP: Calibre web (LinuxServer.io)
    ko_KR: Calibre web (LinuxServer.io)
    ml_IN: Calibre web (LinuxServer.io)
    nb_NO: Calibre web (LinuxServer.io)
    nl_NL: Calibre web (LinuxServer.io)
    pl_PL: Calibre web (LinuxServer.io)
    pt_BR: Calibre web (LinuxServer.io)
    ro_RO: Calibre web (LinuxServer.io)
    ru_RU: Calibre web (LinuxServer.io)
    sk_SK: Calibre web (LinuxServer.io)
    sv_SE: Calibre web (LinuxServer.io)
    tr_TR: Calibre web (LinuxServer.io)
    zh_CN: Calibre web（LinuxServer.io）
    zh_TW: Calibre web（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxservercalibreweb
  port_map: '8083'
  version: 0.6.27
