name: linuxserver-htpcmanager
services:
  app:
    image: linuxserver/htpcmanager:version-26a641bf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/htpcmanager/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverhtpcmanager/assets/icon.png
  title:
    en_US: Htpcmanager (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverhtpcmanager
  port_map: '8085'
  version: version-26a641bf
