name: linuxserver-htpcmanager
services:
  app:
    image: linuxserver/htpcmanager:version-26a641bf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/htpcmanager/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverhtpcmanager/assets/icon.png
  title:
    en_US: Htpcmanager (LinuxServer.io)
    ca_ES: Htpcmanager (LinuxServer.io)
    cs_CZ: Htpcmanager (LinuxServer.io)
    da_DK: Htpcmanager (LinuxServer.io)
    de_DE: Htpcmanager (LinuxServer.io)
    el_GR: Htpcmanager (LinuxServer.io)
    en_GB: Htpcmanager (LinuxServer.io)
    es_ES: Htpcmanager (LinuxServer.io)
    fr_FR: Htpcmanager (LinuxServer.io)
    ga_IE: Htpcmanager (LinuxServer.io)
    hr_HR: Htpcmanager (LinuxServer.io)
    hu_HU: Htpcmanager (LinuxServer.io)
    it_IT: Htpcmanager (LinuxServer.io)
    ja_JP: Htpcmanager (LinuxServer.io)
    ko_KR: Htpcmanager (LinuxServer.io)
    ml_IN: Htpcmanager (LinuxServer.io)
    nb_NO: Htpcmanager (LinuxServer.io)
    nl_NL: Htpcmanager (LinuxServer.io)
    pl_PL: Htpcmanager (LinuxServer.io)
    pt_BR: Htpcmanager (LinuxServer.io)
    ro_RO: Htpcmanager (LinuxServer.io)
    ru_RU: Htpcmanager (LinuxServer.io)
    sk_SK: Htpcmanager (LinuxServer.io)
    sv_SE: Htpcmanager (LinuxServer.io)
    tr_TR: Htpcmanager (LinuxServer.io)
    zh_CN: Htpcmanager（LinuxServer.io）
    zh_TW: Htpcmanager（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverhtpcmanager
  port_map: '8085'
  version: version-26a641bf
