name: linuxserver-vlc
services:
  app:
    image: linuxserver/vlc:3.0.23
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VLC_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vlc/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservervlc/assets/icon.png
  title:
    en_US: Vlc (LinuxServer.io)
    ca_ES: Vlc (LinuxServer.io)
    cs_CZ: Vlc (LinuxServer.io)
    da_DK: Vlc (LinuxServer.io)
    de_DE: Vlc (LinuxServer.io)
    el_GR: Vlc (LinuxServer.io)
    en_GB: Vlc (LinuxServer.io)
    es_ES: Vlc (LinuxServer.io)
    fr_FR: Vlc (LinuxServer.io)
    ga_IE: Vlc (LinuxServer.io)
    hr_HR: Vlc (LinuxServer.io)
    hu_HU: Vlc (LinuxServer.io)
    it_IT: Vlc (LinuxServer.io)
    ja_JP: Vlc (LinuxServer.io)
    ko_KR: Vlc (LinuxServer.io)
    ml_IN: Vlc (LinuxServer.io)
    nb_NO: Vlc (LinuxServer.io)
    nl_NL: Vlc (LinuxServer.io)
    pl_PL: Vlc (LinuxServer.io)
    pt_BR: Vlc (LinuxServer.io)
    ro_RO: Vlc (LinuxServer.io)
    ru_RU: Vlc (LinuxServer.io)
    sk_SK: Vlc (LinuxServer.io)
    sv_SE: Vlc (LinuxServer.io)
    tr_TR: Vlc (LinuxServer.io)
    zh_CN: Vlc（LinuxServer.io）
    zh_TW: Vlc（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservervlc
  port_map: '3000'
  version: 3.0.23
