name: linuxserver-nntp2nntp
services:
  app:
    image: linuxserver/nntp2nntp:0.3.20230704@sha256:a435223dc52180b97b2977b5bb2b2fceb566ac45bb4b2d49d9eae7637924fa64
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 1563
        published: 1563
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nntp2nntp/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservernntp2nntp/assets/icon.png
  title:
    en_US: Nntp2nntp
  id: wisdomsky.linuxserver.linuxservernntp2nntp
  version: 0.3.20230704
