name: linuxserver-freetube
services:
  app:
    image: linuxserver/freetube:version-190523148
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/freetube/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfreetube/assets/icon.png
  title:
    en_US: Freetube
    zh_CN: Freetube
    ca_ES: Freetube
    cs_CZ: Freetube
    da_DK: Freetube
    de_DE: Freetube
    el_GR: Freetube
    en_GB: Freetube
    es_ES: Freetube
    fr_FR: Freetube
    ga_IE: Freetube
    hr_HR: Freetube
    hu_HU: Freetube
    it_IT: Freetube
    ja_JP: Freetube
    ko_KR: Freetube
    ml_IN: Freetube
    nb_NO: Freetube
    nl_NL: Freetube
    pl_PL: Freetube
    pt_BR: Freetube
    ro_RO: Freetube
    ru_RU: Freetube
    sk_SK: Freetube
    sv_SE: Freetube
    tr_TR: Freetube
    zh_TW: Freetube
  id: wisdomsky.linuxserver.linuxserverfreetube
  version: version-190523148
