name: linuxserver-blade-of-agony
services:
  app:
    image: linuxserver/blade-of-agony:3.1.20260910
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/blade-of-agony/config
        target: /config
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_US: 'Wolfenstein: Blade of Agony is a story-driven WWII shooter inspired by Wolfenstein and Doom.'
    zh_CN: 'Wolfenstein: Blade of Agony 是一款以剧情为核心的二战射击游戏，灵感来自《德军总部》和《毁灭战士》。'
  tagline:
    en_US: A story-driven WWII shooter inspired by Wolfenstein and Doom.
    zh_CN: 受《德军总部》和《毁灭战士》启发的二战射击游戏。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/boa-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/boa-logo.png
  title:
    en_US: Blade of-agony (LinuxServer.io)
    zh_CN: Blade of-agony（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverbladeofagony
  port_map: '3000'
  version: 3.1.20260910
