name: linuxserver-code-server
services:
  app:
    image: linuxserver/code-server:4.137.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
      HASHED_PASSWORD: ''
      SUDO_PASSWORD: ''
      SUDO_PASSWORD_HASH: ''
      PROXY_DOMAIN: ''
      DEFAULT_WORKSPACE: ''
      PWA_APPNAME: ''
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/code-server/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservercodeserver/assets/icon.png
  title:
    en_US: Code server (LinuxServer.io)
    ca_ES: Code server (LinuxServer.io)
    cs_CZ: Code server (LinuxServer.io)
    da_DK: Code server (LinuxServer.io)
    de_DE: Code server (LinuxServer.io)
    el_GR: Code server (LinuxServer.io)
    en_GB: Code server (LinuxServer.io)
    es_ES: Code server (LinuxServer.io)
    fr_FR: Code server (LinuxServer.io)
    ga_IE: Code server (LinuxServer.io)
    hr_HR: Code server (LinuxServer.io)
    hu_HU: Code server (LinuxServer.io)
    it_IT: Code server (LinuxServer.io)
    ja_JP: Code server (LinuxServer.io)
    ko_KR: Code server (LinuxServer.io)
    ml_IN: Code server (LinuxServer.io)
    nb_NO: Code server (LinuxServer.io)
    nl_NL: Code server (LinuxServer.io)
    pl_PL: Code server (LinuxServer.io)
    pt_BR: Code server (LinuxServer.io)
    ro_RO: Code server (LinuxServer.io)
    ru_RU: Code server (LinuxServer.io)
    sk_SK: Code server (LinuxServer.io)
    sv_SE: Code server (LinuxServer.io)
    tr_TR: Code server (LinuxServer.io)
    zh_CN: Code server（LinuxServer.io）
    zh_TW: Code server（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservercodeserver
  port_map: '8443'
  version: 4.137.0
