name: linuxserver-kdenlive
services:
  app:
    image: linuxserver/kdenlive:26.08.1@sha256:cea4e05b0d53947cf560c8988d6f5ffbbc22a884327bc3d1ddb1de9727272547
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kdenlive/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverkdenlive/assets/icon.png
  title:
    en_US: Kdenlive (LinuxServer.io)
    ca_ES: Kdenlive (LinuxServer.io)
    cs_CZ: Kdenlive (LinuxServer.io)
    da_DK: Kdenlive (LinuxServer.io)
    de_DE: Kdenlive (LinuxServer.io)
    el_GR: Kdenlive (LinuxServer.io)
    en_GB: Kdenlive (LinuxServer.io)
    es_ES: Kdenlive (LinuxServer.io)
    fr_FR: Kdenlive (LinuxServer.io)
    ga_IE: Kdenlive (LinuxServer.io)
    hr_HR: Kdenlive (LinuxServer.io)
    hu_HU: Kdenlive (LinuxServer.io)
    it_IT: Kdenlive (LinuxServer.io)
    ja_JP: Kdenlive (LinuxServer.io)
    ko_KR: Kdenlive (LinuxServer.io)
    ml_IN: Kdenlive (LinuxServer.io)
    nb_NO: Kdenlive (LinuxServer.io)
    nl_NL: Kdenlive (LinuxServer.io)
    pl_PL: Kdenlive (LinuxServer.io)
    pt_BR: Kdenlive (LinuxServer.io)
    ro_RO: Kdenlive (LinuxServer.io)
    ru_RU: Kdenlive (LinuxServer.io)
    sk_SK: Kdenlive (LinuxServer.io)
    sv_SE: Kdenlive (LinuxServer.io)
    tr_TR: Kdenlive (LinuxServer.io)
    zh_CN: Kdenlive（LinuxServer.io）
    zh_TW: Kdenlive（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverkdenlive
  port_map: '3000'
  version: 26.08.1
