name: linuxserver-openssh-server
services:
  app:
    image: linuxserver/openssh-server:version-10.3_p1-r1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PUBLIC_KEY: ''
      PUBLIC_KEY_FILE: ''
      PUBLIC_KEY_DIR: ''
      PUBLIC_KEY_URL: ''
      SUDO_ACCESS: ''
      PASSWORD_ACCESS: ''
      USER_PASSWORD: ''
      USER_PASSWORD_FILE: ''
      USER_NAME: ''
      LOG_STDOUT: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: PUBLIC_KEY
          description:
            en_US: Optional ssh public key, which will automatically be added to authorized_keys. [OPTIONAL]
        - container: PUBLIC_KEY_FILE
          description:
            en_US: Optionally specify a file containing the public key (works with docker secrets). [OPTIONAL]
        - container: PUBLIC_KEY_DIR
          description:
            en_US: Optionally specify a directory containing the public keys (works with docker secrets). [OPTIONAL]
        - container: PUBLIC_KEY_URL
          description:
            en_US: Optionally specify a URL containing the public key. [OPTIONAL]
        - container: SUDO_ACCESS
          description:
            en_US: Set to true to allow linuxserver.io, the ssh user, sudo access. Without USER_PASSWORD set, this will allow passwordless sudo access. [OPTIONAL]
        - container: PASSWORD_ACCESS
          description:
            en_US: Set to true to allow user/password ssh access. You will want to set USER_PASSWORD or USER_PASSWORD_FILE as well. [OPTIONAL]
        - container: USER_PASSWORD
          description:
            en_US: Optionally set a sudo password for linuxserver.io, the ssh user. If this or USER_PASSWORD_FILE are not set but SUDO_ACCESS is set to true, the user will have passwordless sudo access. [OPTIONAL]
        - container: USER_PASSWORD_FILE
          description:
            en_US: Optionally specify a file that contains the password. This setting supersedes the USER_PASSWORD option (works with docker secrets). [OPTIONAL]
        - container: USER_NAME
          description:
            en_US: Optionally specify a user name (Default:linuxserver.io) [OPTIONAL]
        - container: LOG_STDOUT
          description:
            en_US: Set to true to log to stdout instead of file. [OPTIONAL]
    ports:
      - target: 2222
        published: 2222
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/openssh-server/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Openssh-server is a sandboxed environment that allows ssh access without giving keys to the entire server. Giving ssh access via private key often means giving full access to the server. This container creates a limited and sandboxed environment that others can ssh into. The users only have access to the folders mapped and the processes running inside this container.
    ca_ES: OpenSSH-server és un entorn de sandbox que permet l'accés SSH sense donar claus a tot el servidor. Donar accés SSH mitjançant una clau privada sovint significa donar accés complet al servidor. Aquest contenidor crea un entorn limitat i de sandbox al qual altres persones poden accedir per SSH. Els usuaris només tenen accés a les carpetes mapades i als processos que s'executen dins d'aquest contenidor.
    cs_CZ: Openssh-server je sandboxové prostředí, které umožňuje přístup přes ssh bez nutnosti udělovat klíče celému serveru. Udělení přístupu přes ssh pomocí soukromého klíče často znamená udělení plného přístupu k serveru. Tento kontejner vytváří omezené a sandboxové prostředí, do kterého se ostatní mohou připojit přes ssh. Uživatelé mají přístup pouze k namapovaným složkám a procesům spuštěným uvnitř tohoto kontejneru.
    da_DK: Opensh-server er et sandkassemiljø, der tillader ssh-adgang uden at give nøgler til hele serveren. At give ssh-adgang via en privat nøgle betyder ofte at give fuld adgang til serveren. Denne container opretter et begrænset sandkassemiljø, som andre kan bruge ssh til. Brugerne har kun adgang til de mapper, der er tilknyttet, og de processer, der kører i denne container.
    de_DE: Openssh-server ist eine Sandbox-Umgebung, die SSH-Zugriff ermöglicht, ohne die Schlüssel für den gesamten Server preiszugeben. Die Vergabe von SSH-Zugriff über einen privaten Schlüssel bedeutet üblicherweise vollen Zugriff auf den Server. Dieser Container erstellt eine eingeschränkte Sandbox-Umgebung, auf die andere Benutzer per SSH zugreifen können. Die Benutzer haben lediglich Zugriff auf die eingebundenen Ordner und die im Container laufenden Prozesse.
    el_GR: Το Openssh-server είναι ένα περιβάλλον sandboxed που επιτρέπει την πρόσβαση ssh χωρίς να δίνει κλειδιά σε ολόκληρο τον διακομιστή. Η παροχή πρόσβασης ssh μέσω ιδιωτικού κλειδιού συχνά σημαίνει πλήρη πρόσβαση στον διακομιστή. Αυτό το κοντέινερ δημιουργεί ένα περιορισμένο και sandboxed περιβάλλον στο οποίο μπορούν να συνδεθούν και άλλοι χρήστες με ssh. Οι χρήστες έχουν πρόσβαση μόνο στους φακέλους που έχουν αντιστοιχιστεί και στις διεργασίες που εκτελούνται μέσα σε αυτό το κοντέινερ.
    en_GB: Openssh-server is a sandboxed environment that allows ssh access without giving keys to the entire server. Giving ssh access via private key often means giving full access to the server. This container creates a limited and sandboxed environment that others can ssh into. The users only have access to the folders mapped and the processes running inside this container.
    es_ES: Openssh-server es un entorno aislado que permite el acceso SSH sin necesidad de proporcionar las claves de acceso a todo el servidor. Otorgar acceso SSH mediante clave privada suele implicar dar acceso completo al servidor. Este contenedor crea un entorno limitado y aislado al que otros usuarios pueden acceder mediante SSH. Los usuarios solo tienen acceso a las carpetas mapeadas y a los procesos que se ejecutan dentro de este contenedor.
    fr_FR: Openssh-server est un environnement isolé permettant l'accès SSH sans avoir à fournir les clés d'accès à l'ensemble du serveur. Accorder un accès SSH via une clé privée revient généralement à donner un accès complet au serveur. Ce conteneur crée un environnement limité et isolé auquel d'autres utilisateurs peuvent se connecter via SSH. Les utilisateurs ont uniquement accès aux dossiers mappés et aux processus exécutés à l'intérieur de ce conteneur.
    ga_IE: Is timpeallacht bosca gainimh í Opensh-server a ligeann rochtain ssh gan eochracha a thabhairt don fhreastalaí ar fad. Is minic a chiallaíonn rochtain ssh a thabhairt trí eochair phríobháideach rochtain iomlán a thabhairt ar an bhfreastalaí. Cruthaíonn an coimeádán seo timpeallacht theoranta bosca gainimh ar féidir le daoine eile ssh a chur isteach inti. Níl rochtain ag na húsáideoirí ach ar na fillteáin atá mapáilte agus na próisis atá ag rith laistigh den choimeádán seo.
    hr_HR: Openssh-server je sandbox okruženje koje omogućuje ssh pristup bez davanja ključeva cijelom poslužitelju. Davanje ssh pristupa putem privatnog ključa često znači davanje punog pristupa poslužitelju. Ovaj kontejner stvara ograničeno i sandbox okruženje u koje drugi mogu ući putem ssh-a. Korisnici imaju pristup samo mapiranim mapama i procesima koji se izvode unutar ovog kontejnera.
    hu_HU: Az Openssh-server egy sandbox környezet, amely lehetővé teszi az SSH-hozzáférést anélkül, hogy kulcsokat adna a teljes szerverhez. Az SSH-hozzáférés privát kulcson keresztüli megadása gyakran azt jelenti, hogy teljes hozzáférést biztosít a szerverhez. Ez a konténer egy korlátozott és sandbox környezetet hoz létre, amelybe mások SSH-n keresztül beléphetnek. A felhasználók csak a konténerben leképezett mappákhoz és futó folyamatokhoz férhetnek hozzá.
    it_IT: Openssh-server è un ambiente sandbox che consente l'accesso SSH senza dover fornire le chiavi di accesso all'intero server. Concedere l'accesso SSH tramite chiave privata spesso significa concedere l'accesso completo al server. Questo container crea un ambiente limitato e isolato a cui altri utenti possono accedere tramite SSH. Gli utenti hanno accesso solo alle cartelle mappate e ai processi in esecuzione all'interno di questo container.
    ja_JP: Openssh-serverは、サーバー全体に鍵を渡すことなくSSHアクセスを可能にするサンドボックス環境です。秘密鍵を介してSSHアクセスを許可すると、多くの場合、サーバーへの完全なアクセス権を与えることになります。このコンテナは、他のユーザーがSSH接続できる、制限されたサンドボックス環境を作成します。ユーザーは、マッピングされたフォルダと、このコンテナ内で実行されているプロセスにのみアクセスできます。
    ko_KR: OpenSSH 서버는 서버 전체에 개인 키를 제공하지 않고도 SSH 접속을 허용하는 샌드박스 환경입니다. 개인 키를 통해 SSH 접속 권한을 부여한다는 것은 일반적으로 서버에 대한 모든 접근 권한을 부여하는 것을 의미합니다. 이 컨테이너는 제한된 샌드박스 환경을 생성하여 다른 사용자가 SSH로 접속할 수 있도록 합니다. 사용자는 이 컨테이너 내부에 매핑된 폴더와 실행 중인 프로세스에만 접근할 수 있습니다.
    ml_IN: Openssh-server എന്നത് മുഴുവൻ സെർവറിനും കീകൾ നൽകാതെ ssh ആക്‌സസ് അനുവദിക്കുന്ന ഒരു സാൻഡ്‌ബോക്‌സ്ഡ് എൻവയോൺമെന്റാണ്. സ്വകാര്യ കീ വഴി ssh ആക്‌സസ് നൽകുന്നത് പലപ്പോഴും സെർവറിലേക്ക് പൂർണ്ണ ആക്‌സസ് നൽകുക എന്നതാണ്. മറ്റുള്ളവർക്ക് ssh ചെയ്യാൻ കഴിയുന്ന പരിമിതവും സാൻഡ്‌ബോക്‌സ്ഡ് എൻവയോൺമെന്റും ഈ കണ്ടെയ്‌നർ സൃഷ്ടിക്കുന്നു. മാപ്പ് ചെയ്‌ത ഫോൾഡറുകളിലേക്കും ഈ കണ്ടെയ്‌നറിനുള്ളിൽ പ്രവർത്തിക്കുന്ന പ്രക്രിയകളിലേക്കും മാത്രമേ ഉപയോക്താക്കൾക്ക് ആക്‌സസ് ഉണ്ടാകൂ.
    nb_NO: Opensh-server er et sandkassemiljø som tillater SSH-tilgang uten å gi nøkler til hele serveren. Å gi SSH-tilgang via privat nøkkel betyr ofte å gi full tilgang til serveren. Denne containeren oppretter et begrenset og sandkassemiljø som andre kan bruke SSH til. Brukerne har bare tilgang til mappene som er tilordnet og prosessene som kjører i denne containeren.
    nl_NL: Openssh-server is een afgeschermde omgeving die SSH-toegang mogelijk maakt zonder de sleutels van de hele server te hoeven delen. Het verlenen van SSH-toegang via een privésleutel betekent vaak dat je volledige toegang tot de server krijgt. Deze container creëert een beperkte, afgeschermde omgeving waartoe anderen via SSH toegang kunnen krijgen. Gebruikers hebben alleen toegang tot de mappen die in deze container zijn gekoppeld en de processen die erin draaien.
    pl_PL: Openssh-server to środowisko sandboxowe, które umożliwia dostęp SSH bez konieczności podawania kluczy do całego serwera. Udzielenie dostępu SSH za pomocą klucza prywatnego często oznacza udzielenie pełnego dostępu do serwera. Ten kontener tworzy ograniczone i sandboxowe środowisko, do którego inni mogą się zalogować przez SSH. Użytkownicy mają dostęp tylko do mapowanych folderów i procesów uruchomionych w tym kontenerze.
    pt_BR: O OpenSSH Server é um ambiente isolado (sandbox) que permite acesso SSH sem fornecer as chaves de acesso ao servidor inteiro. Conceder acesso SSH por meio de uma chave privada geralmente significa conceder acesso total ao servidor. Este contêiner cria um ambiente limitado e isolado ao qual outros usuários podem acessar via SSH. Os usuários têm acesso apenas às pastas mapeadas e aos processos em execução dentro deste contêiner.
    ro_RO: Serverul OpenSSH este un mediu sandbox care permite accesul SSH fără a oferi chei întregului server. Acordarea accesului SSH prin cheie privată înseamnă adesea acordarea accesului complet la server. Acest container creează un mediu limitat și sandbox în care alții se pot conecta prin SSH. Utilizatorii au acces doar la folderele mapate și la procesele care rulează în interiorul acestui container.
    ru_RU: Openssh-server — это изолированная среда, которая позволяет получить доступ по SSH без предоставления ключей всему серверу. Предоставление доступа по SSH через закрытый ключ часто означает предоставление полного доступа к серверу. Этот контейнер создает ограниченную и изолированную среду, к которой другие могут подключаться по SSH. Пользователи имеют доступ только к сопоставленным папкам и процессам, запущенным внутри этого контейнера.
    sk_SK: Openssh-server je izolované prostredie, ktoré umožňuje prístup cez ssh bez poskytnutia kľúčov k celému serveru. Poskytnutie prístupu cez ssh prostredníctvom súkromného kľúča často znamená poskytnutie úplného prístupu k serveru. Tento kontajner vytvára obmedzené a izolované prostredie, do ktorého sa ostatní môžu pripojiť cez ssh. Používatelia majú prístup iba k namapovaným priečinkom a procesom spusteným v tomto kontajneri.
    sv_SE: Opensh-server är en sandlådemiljö som tillåter ssh-åtkomst utan att ge nycklar till hela servern. Att ge ssh-åtkomst via privat nyckel innebär ofta att ge fullständig åtkomst till servern. Denna container skapar en begränsad och sandlådemiljö som andra kan använda ssh till. Användarna har bara åtkomst till de mappar som är mappade och de processer som körs inuti denna container.
    tr_TR: OpenSSH sunucusu, sunucunun tamamına anahtar vermeden SSH erişimine olanak tanıyan, izole edilmiş bir ortamdır. Özel anahtar aracılığıyla SSH erişimi vermek genellikle sunucuya tam erişim vermek anlamına gelir. Bu konteyner, başkalarının SSH ile bağlanabileceği sınırlı ve izole edilmiş bir ortam oluşturur. Kullanıcılar yalnızca eşlenmiş klasörlere ve bu konteyner içinde çalışan işlemlere erişebilir.
    zh_CN: Openssh-server 提供沙盒环境，让他人通过 SSH 访问，而无需授予整台服务器的权限。通常，提供私钥 SSH 访问可能意味着开放完整服务器权限；此容器则创建受限的隔离环境，用户只能访问映射到容器中的文件夹，以及容器内运行的进程。
    zh_TW: Openssh-server 提供沙盒環境，讓他人透過 SSH 訪問，而無需授予整臺伺服器的許可權。通常，提供私鑰 SSH 訪問可能意味著開放完整伺服器許可權；此容器則建立受限的隔離環境，使用者只能訪問對映到容器中的資料夾，以及容器內執行的程序。
  tagline:
    en_US: A sandboxed environment that allows ssh access without giving keys to the entire server. Giving ssh access via private key often means giving full access to the server. This container creates a limited and sandboxed environment that others can ssh into. The users only have access to the folders mapped and the processes running inside this container.
    ca_ES: Un entorn de zona de proves que permet l'accés SSH sense donar claus a tot el servidor. Donar accés SSH mitjançant una clau privada sovint significa donar accés complet al servidor. Aquest contenidor crea un entorn limitat i de zona de proves al qual altres persones poden accedir per SSH. Els usuaris només tenen accés a les carpetes assignades i als processos que s'executen dins d'aquest contenidor.
    cs_CZ: Sandboxové prostředí, které umožňuje přístup přes SSH bez nutnosti udělovat klíče celému serveru. Udělení přístupu přes SSH prostřednictvím soukromého klíče často znamená udělení plného přístupu k serveru. Tento kontejner vytváří omezené a sandboxové prostředí, do kterého se ostatní mohou připojit přes SSH. Uživatelé mají přístup pouze k namapovaným složkám a procesům spuštěným uvnitř tohoto kontejneru.
    da_DK: Et sandkassemiljø, der tillader SSH-adgang uden at give nøgler til hele serveren. At give SSH-adgang via en privat nøgle betyder ofte at give fuld adgang til serveren. Denne container opretter et begrænset sandkassemiljø, som andre kan SSH-adgang til. Brugerne har kun adgang til de mapper, der er tilknyttet, og de processer, der kører i denne container.
    de_DE: Eine Sandbox-Umgebung ermöglicht SSH-Zugriff, ohne die Schlüssel für den gesamten Server preiszugeben. Die Bereitstellung von SSH-Zugriff über einen privaten Schlüssel bedeutet oft vollen Zugriff auf den Server. Dieser Container erstellt eine eingeschränkte Sandbox-Umgebung, auf die andere Benutzer per SSH zugreifen können. Die Benutzer haben lediglich Zugriff auf die eingebundenen Ordner und die im Container laufenden Prozesse.
    el_GR: Ένα περιβάλλον sandboxed που επιτρέπει την πρόσβαση ssh χωρίς να δίνονται κλειδιά σε ολόκληρο τον διακομιστή. Η παροχή πρόσβασης ssh μέσω ιδιωτικού κλειδιού συχνά σημαίνει πλήρη πρόσβαση στον διακομιστή. Αυτό το κοντέινερ δημιουργεί ένα περιορισμένο και sandboxed περιβάλλον στο οποίο μπορούν να συνδεθούν και άλλοι χρήστες με ssh. Οι χρήστες έχουν πρόσβαση μόνο στους φακέλους που έχουν αντιστοιχιστεί και στις διεργασίες που εκτελούνται μέσα σε αυτό το κοντέινερ.
    en_GB: A sandboxed environment that allows ssh access without giving keys to the entire server. Giving ssh access via private key often means giving full access to the server. This container creates a limited and sandboxed environment that others can ssh into. The users only have access to the folders mapped and the processes running inside this container.
    es_ES: Un entorno aislado que permite el acceso SSH sin proporcionar las claves de acceso a todo el servidor. Otorgar acceso SSH mediante clave privada suele implicar dar acceso completo al servidor. Este contenedor crea un entorno limitado y aislado al que otros usuarios pueden acceder mediante SSH. Los usuarios solo tienen acceso a las carpetas mapeadas y a los procesos que se ejecutan dentro de este contenedor.
    fr_FR: Un environnement isolé (sandbox) qui permet l'accès SSH sans fournir de clés pour l'ensemble du serveur. Accorder un accès SSH via une clé privée revient généralement à donner un accès complet au serveur. Ce conteneur crée un environnement limité et isolé auquel d'autres utilisateurs peuvent se connecter via SSH. Les utilisateurs ont uniquement accès aux dossiers mappés et aux processus exécutés à l'intérieur de ce conteneur.
    ga_IE: Timpeallacht bosca gainimh a cheadaíonn rochtain ssh gan eochracha a thabhairt don fhreastalaí ar fad. Is minic a chiallaíonn rochtain ssh a thabhairt trí eochair phríobháideach rochtain iomlán a thabhairt ar an bhfreastalaí. Cruthaíonn an coimeádán seo timpeallacht theoranta bosca gainimh ar féidir le daoine eile ssh a chur isteach inti. Níl rochtain ag na húsáideoirí ach ar na fillteáin atá mapáilte agus na próisis atá ag rith taobh istigh den choimeádán seo.
    hr_HR: Sandbox okruženje koje omogućuje SSH pristup bez davanja ključeva cijelom poslužitelju. Davanje SSH pristupa putem privatnog ključa često znači davanje punog pristupa poslužitelju. Ovaj kontejner stvara ograničeno i sandbox okruženje u koje drugi mogu ući putem SSH-a. Korisnici imaju pristup samo mapiranim mapama i procesima koji se izvode unutar ovog kontejnera.
    hu_HU: Egy sandboxos környezet, amely lehetővé teszi az SSH-hozzáférést anélkül, hogy kulcsokat adna a teljes szerverhez. Az SSH-hozzáférés privát kulcson keresztüli megadása gyakran azt jelenti, hogy teljes hozzáférést biztosít a szerverhez. Ez a konténer egy korlátozott és sandboxos környezetet hoz létre, amelybe mások SSH-n keresztül beléphetnek. A felhasználók csak a konténerben leképezett mappákhoz és futó folyamatokhoz férhetnek hozzá.
    it_IT: Un ambiente sandbox che consente l'accesso SSH senza dover fornire le chiavi di accesso all'intero server. Concedere l'accesso SSH tramite chiave privata spesso significa concedere l'accesso completo al server. Questo container crea un ambiente limitato e isolato a cui altri utenti possono accedere tramite SSH. Gli utenti hanno accesso solo alle cartelle mappate e ai processi in esecuzione all'interno di questo container.
    ja_JP: サーバー全体に鍵を渡すことなくSSHアクセスを可能にするサンドボックス環境。秘密鍵を介してSSHアクセスを許可すると、多くの場合、サーバーへの完全なアクセス権を与えることになります。このコンテナは、他のユーザーがSSH接続できる、制限されたサンドボックス環境を作成します。ユーザーは、マッピングされたフォルダと、このコンテナ内で実行されているプロセスにのみアクセスできます。
    ko_KR: 전체 서버에 개인 키를 제공하지 않고도 SSH 접속을 허용하는 샌드박스 환경입니다. 개인 키를 통해 SSH 접속 권한을 부여하는 것은 일반적으로 서버에 대한 모든 접근 권한을 부여하는 것과 같습니다. 이 컨테이너는 제한된 샌드박스 환경을 생성하여 다른 사용자가 SSH로 접속할 수 있도록 합니다. 사용자는 이 컨테이너 내부에 매핑된 폴더와 실행 중인 프로세스에만 접근할 수 있습니다.
    ml_IN: മുഴുവൻ സെർവറിനും കീകൾ നൽകാതെ ssh ആക്‌സസ് അനുവദിക്കുന്ന ഒരു സാൻഡ്‌ബോക്‌സ്ഡ് എൻവയോൺമെന്റ്. സ്വകാര്യ കീ വഴി ssh ആക്‌സസ് നൽകുന്നത് പലപ്പോഴും സെർവറിലേക്ക് പൂർണ്ണ ആക്‌സസ് നൽകുക എന്നതാണ്. മറ്റുള്ളവർക്ക് ssh ചെയ്യാൻ കഴിയുന്ന പരിമിതവും സാൻഡ്‌ബോക്‌സ്ഡ് എൻവയോൺമെന്റും ഈ കണ്ടെയ്‌നർ സൃഷ്ടിക്കുന്നു. മാപ്പ് ചെയ്‌ത ഫോൾഡറുകളിലേക്കും ഈ കണ്ടെയ്‌നറിനുള്ളിൽ പ്രവർത്തിക്കുന്ന പ്രക്രിയകളിലേക്കും മാത്രമേ ഉപയോക്താക്കൾക്ക് ആക്‌സസ് ഉണ്ടാകൂ.
    nb_NO: Et sandkassemiljø som tillater SSH-tilgang uten å gi nøkler til hele serveren. Å gi SSH-tilgang via privat nøkkel betyr ofte å gi full tilgang til serveren. Denne containeren oppretter et begrenset og sandkassemiljø som andre kan bruke SSH til. Brukerne har bare tilgang til mappene som er tilordnet og prosessene som kjører i denne containeren.
    nl_NL: Een afgeschermde omgeving die SSH-toegang mogelijk maakt zonder de sleutels van de hele server te hoeven delen. SSH-toegang via een privésleutel betekent vaak dat je volledige toegang tot de server krijgt. Deze container creëert een beperkte, afgeschermde omgeving waar anderen via SSH toegang toe kunnen krijgen. De gebruikers hebben alleen toegang tot de mappen die in deze container zijn gekoppeld en de processen die erin draaien.
    pl_PL: Środowisko sandboxowe, które umożliwia dostęp SSH bez konieczności podawania kluczy do całego serwera. Udzielenie dostępu SSH za pomocą klucza prywatnego często oznacza udzielenie pełnego dostępu do serwera. Ten kontener tworzy ograniczone i sandboxowe środowisko, do którego inni mogą się zalogować przez SSH. Użytkownicy mają dostęp tylko do mapowanych folderów i procesów uruchomionych w tym kontenerze.
    pt_BR: Um ambiente isolado (sandbox) que permite acesso SSH sem fornecer as chaves de acesso a todo o servidor. Conceder acesso SSH por meio de uma chave privada geralmente significa conceder acesso total ao servidor. Este contêiner cria um ambiente limitado e isolado ao qual outros usuários podem acessar via SSH. Os usuários têm acesso apenas às pastas mapeadas e aos processos em execução dentro deste contêiner.
    ro_RO: Un mediu sandbox care permite accesul SSH fără a oferi chei către întregul server. Acordarea accesului SSH prin cheie privată înseamnă adesea acordarea accesului complet la server. Acest container creează un mediu limitat și sandbox în care alții se pot conecta prin SSH. Utilizatorii au acces doar la folderele mapate și la procesele care rulează în interiorul acestui container.
    ru_RU: Изолированная среда, позволяющая получать доступ по SSH без предоставления ключей всему серверу. Предоставление доступа по SSH через закрытый ключ часто означает предоставление полного доступа к серверу. Этот контейнер создает ограниченную и изолированную среду, к которой другие могут подключаться по SSH. Пользователи имеют доступ только к сопоставленным папкам и процессам, запущенным внутри этого контейнера.
    sk_SK: Sandboxové prostredie, ktoré umožňuje prístup cez ssh bez poskytnutia kľúčov k celému serveru. Poskytnutie prístupu cez ssh prostredníctvom súkromného kľúča často znamená poskytnutie úplného prístupu k serveru. Tento kontajner vytvára obmedzené a sandboxové prostredie, do ktorého sa ostatní môžu pripojiť cez ssh. Používatelia majú prístup iba k namapovaným priečinkom a procesom spusteným v tomto kontajneri.
    sv_SE: En sandlådemiljö som tillåter SSH-åtkomst utan att ge nycklar till hela servern. Att ge SSH-åtkomst via privat nyckel innebär ofta att ge fullständig åtkomst till servern. Denna container skapar en begränsad och sandlådemiljö som andra kan använda SSH till. Användarna har bara åtkomst till de mappar som är mappade och de processer som körs inuti denna container.
    tr_TR: Sunucuya tam erişim izni vermeden SSH erişimine olanak sağlayan, izole edilmiş bir ortam. Özel anahtar aracılığıyla SSH erişimi vermek genellikle sunucuya tam erişim izni vermek anlamına gelir. Bu konteyner, başkalarının SSH ile bağlanabileceği sınırlı ve izole edilmiş bir ortam oluşturur. Kullanıcılar yalnızca eşlenmiş klasörlere ve bu konteyner içinde çalışan işlemlere erişebilir.
    zh_CN: 通过 SSH 访问受限的容器环境。
    zh_TW: 透過 SSH 訪問受限的容器環境。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/openssh-server-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/openssh-server-logo.png
  title:
    en_US: Openssh server (LinuxServer.io)
    ca_ES: Openssh server (LinuxServer.io)
    cs_CZ: Openssh server (LinuxServer.io)
    da_DK: Openssh server (LinuxServer.io)
    de_DE: Openssh server (LinuxServer.io)
    el_GR: Openssh server (LinuxServer.io)
    en_GB: Openssh server (LinuxServer.io)
    es_ES: Openssh server (LinuxServer.io)
    fr_FR: Openssh server (LinuxServer.io)
    ga_IE: Openssh server (LinuxServer.io)
    hr_HR: Openssh server (LinuxServer.io)
    hu_HU: Openssh server (LinuxServer.io)
    it_IT: Openssh server (LinuxServer.io)
    ja_JP: Openssh server (LinuxServer.io)
    ko_KR: Openssh server (LinuxServer.io)
    ml_IN: Openssh server (LinuxServer.io)
    nb_NO: Openssh server (LinuxServer.io)
    nl_NL: Openssh server (LinuxServer.io)
    pl_PL: Openssh server (LinuxServer.io)
    pt_BR: Openssh server (LinuxServer.io)
    ro_RO: Openssh server (LinuxServer.io)
    ru_RU: Openssh server (LinuxServer.io)
    sk_SK: Openssh server (LinuxServer.io)
    sv_SE: Openssh server (LinuxServer.io)
    tr_TR: Openssh server (LinuxServer.io)
    zh_CN: Openssh server（LinuxServer.io）
    zh_TW: Openssh server（LinuxServer.io）
  category: Developer
  id: wisdomsky.linuxserver.linuxserveropensshserver
  port_map: '2222'
  version: version-10.3_p1-r1
