name: linuxserver-sickgear
services:
  app:
    image: linuxserver/sickgear:3.36.6@sha256:e50c1ea9a8949c4c12aee7e65edea7d0e3257a4313b6f13c6f8b7744f1a4103a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sickgear/config
        target: /config
      - type: bind
        source: /DATA/AppData/sickgear/tv
        target: /tv
      - type: bind
        source: /DATA/AppData/sickgear/downloads
        target: /downloads
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserversickgear/assets/icon.png
  title:
    en_US: Sickgear (LinuxServer.io)
    zh_CN: Sickgear（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserversickgear
  port_map: '8081'
  version: 3.36.6
