name: linuxserver-headphones
services:
  app:
    image: linuxserver/headphones:version-a78f38c1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/headphones/config
        target: /config
      - type: bind
        source: /DATA/AppData/headphones/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/headphones/music
        target: /music
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: 'Visit homepage: https://hub.docker.com/r/linuxserver/headphones/'
    zh_CN: |-
      Headphones 是用 Python 编写的自动音乐下载器，可使用 NZB 和 Torrent。它支持 SABnzbd、NZBget、Transmission、µTorrent 和 Blackhole。

      访问项目主页：https://hub.docker.com/r/linuxserver/headphones/
  tagline:
    en_US: An automated music downloader for NZB and Torrent, written in Python. It supports SABnzbd, NZBget, Transmission, µTorrent and Blackhole.
    zh_CN: 自动下载和管理来自 NZB 与 Torrent 的音乐。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/headphones-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/headphones-banner.png
  title:
    en_US: Headphones
    zh_CN: Headphones
  category: Others
  project_url: https://github.com/rembo10/headphones
  port_map: '8181'
  id: wisdomsky.linuxserver.linuxserverheadphones
  version: version-a78f38c1
  website: https://github.com/rembo10/headphones
