name: linuxserver-code-server
services:
  app:
    image: linuxserver/code-server:4.137.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
      HASHED_PASSWORD: ''
      SUDO_PASSWORD: ''
      SUDO_PASSWORD_HASH: ''
      PROXY_DOMAIN: ''
      DEFAULT_WORKSPACE: ''
      PWA_APPNAME: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: PASSWORD
          description:
            en_US: Optional web gui password, if PASSWORD or HASHED_PASSWORD is not provided, there will be no auth. [OPTIONAL]
        - container: HASHED_PASSWORD
          description:
            en_US: Optional web gui password, overrides PASSWORD, instructions on how to create it is below. [OPTIONAL]
        - container: SUDO_PASSWORD
          description:
            en_US: If this optional variable is set, user will have sudo access in the code-server terminal with the specified password. [OPTIONAL]
        - container: SUDO_PASSWORD_HASH
          description:
            en_US: Optionally set sudo password via hash (takes priority over SUDO_PASSWORD var). Format is $type$salt$hashed. [OPTIONAL]
        - container: PROXY_DOMAIN
          description:
            en_US: If this optional variable is set, this domain will be proxied for subdomain proxying. See Documentation [OPTIONAL]
        - container: DEFAULT_WORKSPACE
          description:
            en_US: If this optional variable is set, code-server will open this directory by default [OPTIONAL]
        - container: PWA_APPNAME
          description:
            en_US: If this optional variable is set, the PWA app will the specified name. [OPTIONAL]
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/code-server/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Code-server is VS Code running on a remote server, accessible through the browser. - Code on your Chromebook, tablet, and laptop with a consistent dev environment. - If you have a Windows or Mac workstation, more easily develop for Linux. - Take advantage of large cloud servers to speed up tests, compilations, downloads, and more. - Preserve battery life when you're on the go. - All intensive computation runs on your server. - You're no longer running excess instances of Chrome.
    ca_ES: El servidor de codi és VS Code que s'executa en un servidor remot, accessible a través del navegador. - Codi al vostre Chromebook, tauleta i portàtil amb un entorn de desenvolupament coherent. - Si teniu una estació de treball Windows o Mac, desenvolupeu més fàcilment per a Linux. - Aprofiteu els grans servidors al núvol per accelerar les proves, les compilacions, les descàrregues i molt més. - Preserveu la durada de la bateria quan esteu fora de casa. - Tot el càlcul intensiu s'executa al vostre servidor. - Ja no executeu instàncies addicionals de Chrome.
    cs_CZ: Code-server je VS Code běžící na vzdáleném serveru, přístupném přes prohlížeč. - Kódujte na Chromebooku, tabletu a notebooku s konzistentním vývojářským prostředím. - Pokud máte pracovní stanici s Windows nebo Mac, snáze vyvíjejte pro Linux. - Využijte velké cloudové servery k urychlení testů, kompilací, stahování a dalších činností. - Šetřete výdrž baterie, když jste na cestách. - Veškeré náročné výpočty běží na vašem serveru. - Již nespouštíte nadbytečné instance Chromu.
    da_DK: Kodeserver er VS-kode, der kører på en ekstern server, som er tilgængelig via browseren. - Kod på din Chromebook, tablet og bærbare computer med et ensartet udviklingsmiljø. - Hvis du har en Windows- eller Mac-arbejdsstation, kan du lettere udvikle til Linux. - Udnyt store cloud-servere til at fremskynde test, kompileringer, downloads og meget mere. - Spar på batteriet, når du er på farten. - Al intensiv beregning kører på din server. - Du kører ikke længere overskydende instanser af Chrome.
    de_DE: Code-Server ist VS Code, das auf einem Remote-Server läuft und über den Browser zugänglich ist. – Programmieren Sie auf Ihrem Chromebook, Tablet und Laptop mit einer einheitlichen Entwicklungsumgebung. – Wenn Sie eine Windows- oder Mac-Workstation besitzen, können Sie einfacher für Linux entwickeln. – Profitieren Sie von großen Cloud-Servern, um Tests, Kompilierungen, Downloads und mehr zu beschleunigen. – Sparen Sie Akku, wenn Sie unterwegs sind. – Alle rechenintensiven Vorgänge werden auf Ihrem Server ausgeführt. – Sie benötigen keine unnötigen Chrome-Instanzen mehr.
    el_GR: Το Code-server είναι ένα VS Code που εκτελείται σε έναν απομακρυσμένο διακομιστή, προσβάσιμο μέσω του προγράμματος περιήγησης. - Κωδικοποιήστε στο Chromebook, το tablet και τον φορητό υπολογιστή σας με ένα συνεπές περιβάλλον προγραμματιστή. - Εάν διαθέτετε σταθμό εργασίας Windows ή Mac, αναπτύξτε τον πιο εύκολα για Linux. - Επωφεληθείτε από τους μεγάλους διακομιστές cloud για να επιταχύνετε τις δοκιμές, τις μεταγλωττίσεις, τις λήψεις και πολλά άλλα. - Εξοικονομήστε χρόνο ζωής της μπαταρίας όταν βρίσκεστε εν κινήσει. - Όλοι οι εντατικοί υπολογισμοί εκτελούνται στον διακομιστή σας. - Δεν εκτελείτε πλέον υπερβολικές παρουσίες του Chrome.
    en_GB: Code-server is Vs Code running on a remote server, accessible through the browser. - Code on your Chromebook, tablet, and laptop with a consistent dev environment. - If you have a Windows or Mac workstation, more easily develop for Linux. - Take advantage of large cloud servers to speed up tests, compilations, downloads, and more. - Preserve battery life when you're on the go. - All intensive computation runs on your server. - You're no longer running excess instances of Chrome.
    es_ES: Code-server es VS Code ejecutándose en un servidor remoto, accesible a través del navegador. - Programa en tu Chromebook, tableta y portátil con un entorno de desarrollo consistente. - Si tienes una estación de trabajo Windows o Mac, desarrolla para Linux con mayor facilidad. - Aprovecha los grandes servidores en la nube para acelerar las pruebas, compilaciones, descargas y más. - Ahorra batería cuando estés fuera de casa. - Todos los cálculos intensivos se ejecutan en tu servidor. - Ya no ejecutas instancias innecesarias de Chrome.
    fr_FR: Code-server, c'est VS Code exécuté sur un serveur distant et accessible via votre navigateur. - Développez sur votre Chromebook, tablette et ordinateur portable avec un environnement de développement homogène. - Si vous possédez un poste de travail Windows ou Mac, développez plus facilement pour Linux. - Profitez de la puissance des serveurs cloud pour accélérer les tests, les compilations, les téléchargements et bien plus encore. - Préservez l'autonomie de votre batterie lors de vos déplacements. - Tous les calculs intensifs sont exécutés sur votre serveur. - Vous n'utilisez plus plusieurs instances de Chrome.
    ga_IE: Is éard atá i gceist le freastalaí cóid ná Cód VS a ritheann ar fhreastalaí cianda, atá inrochtana tríd an mbrabhsálaí. - Cód ar do Chromebook, taibléad, agus ríomhaire glúine le timpeallacht forbartha comhsheasmhach. - Má tá stáisiún oibre Windows nó Mac agat, forbair níos éasca do Linux. - Bain leas as freastalaithe scamall móra chun tástálacha, tiomsúcháin, íoslódálacha, agus níos mó a bhrostú. - Saol na ceallraí a chaomhnú nuair a bhíonn tú ag taisteal. - Ritheann an ríomhaireacht dhian go léir ar do fhreastalaí. - Níl tú ag rith aon chásanna breise de Chrome a thuilleadh.
    hr_HR: Code-server je VS Code koji se izvodi na udaljenom poslužitelju, dostupnom putem preglednika. - Kodirajte na svom Chromebooku, tabletu i prijenosnom računalu s konzistentnim razvojnim okruženjem. - Ako imate Windows ili Mac radnu stanicu, lakše razvijajte za Linux. - Iskoristite velike cloud poslužitelje za ubrzavanje testova, kompilacija, preuzimanja i još mnogo toga. - Očuvajte vijek trajanja baterije kada ste u pokretu. - Sva intenzivna izračunavanja izvode se na vašem poslužitelju. - Više ne pokrećete dodatne instance Chromea.
    hu_HU: A kódszerver egy távoli szerveren futó VS Code, amely böngészőn keresztül érhető el. – Kódolj Chromebookodon, táblagépeden és laptopodon konzisztens fejlesztői környezetben. – Ha Windows vagy Mac munkaállomásod van, könnyebben fejleszthetsz Linuxra. – Használd ki a nagy felhőszervereket a tesztek, fordítások, letöltések és egyebek felgyorsításához. – Környezetbarát akkumulátor-üzemidő útközben. – Minden intenzív számítás a szervereden fut. – Többé nem kell felesleges Chrome-példányokat futtatnod.
    it_IT: Code-server è VS Code in esecuzione su un server remoto, accessibile tramite browser. - Scrivi codice su Chromebook, tablet e laptop con un ambiente di sviluppo coerente. - Se hai una workstation Windows o Mac, sviluppa più facilmente per Linux. - Sfrutta i grandi server cloud per velocizzare test, compilazioni, download e altro ancora. - Risparmia la batteria quando sei in movimento. - Tutti i calcoli intensivi vengono eseguiti sul tuo server. - Non dovrai più eseguire istanze superflue di Chrome.
    ja_JP: Code-server は、ブラウザからアクセスできるリモート サーバー上で動作する VS Code です。 - Chromebook、タブレット、ノートパソコンで一貫した開発環境を使用してコーディングできます。 - Windows または Mac ワークステーションをお持ちの場合は、Linux 向けの開発がより簡単になります。 - 大規模なクラウド サーバーを活用して、テスト、コンパイル、ダウンロードなどを高速化できます。 - 外出先でもバッテリー寿命を節約できます。 - すべての負荷の高い計算はサーバー上で実行されます。 - Chrome の余分なインスタンスを実行する必要がなくなります。
    ko_KR: Code-server는 브라우저를 통해 접속할 수 있는 원격 서버에서 실행되는 VS Code입니다. - 크롬북, 태블릿, 노트북에서 일관된 개발 환경을 사용하여 코딩할 수 있습니다. - Windows 또는 Mac 워크스테이션을 사용하는 경우 Linux용 개발을 더욱 쉽게 할 수 있습니다. - 대용량 클라우드 서버를 활용하여 테스트, 컴파일, 다운로드 등의 속도를 향상시킬 수 있습니다. - 이동 중에도 배터리 수명을 절약할 수 있습니다. - 모든 고강도 연산은 서버에서 실행됩니다. - 더 이상 Chrome의 여러 인스턴스를 동시에 실행할 필요가 없습니다.
    ml_IN: കോഡ്-സെർവർ എന്നത് ഒരു റിമോട്ട് സെർവറിൽ പ്രവർത്തിക്കുന്ന VS കോഡാണ്, ബ്രൗസറിലൂടെ ആക്‌സസ് ചെയ്യാവുന്നതാണ്. - നിങ്ങളുടെ Chromebook, ടാബ്‌ലെറ്റ്, ലാപ്‌ടോപ്പ് എന്നിവയിലെ കോഡ് സ്ഥിരതയുള്ള ഡെവലപ്‌മെന്റ് പരിതസ്ഥിതിയിൽ പ്രവർത്തിക്കുന്നു. - നിങ്ങൾക്ക് ഒരു വിൻഡോസ് അല്ലെങ്കിൽ മാക് വർക്ക്‌സ്റ്റേഷൻ ഉണ്ടെങ്കിൽ, Linux-നായി കൂടുതൽ എളുപ്പത്തിൽ വികസിപ്പിക്കുക. - ടെസ്റ്റുകൾ, സമാഹാരങ്ങൾ, ഡൗൺലോഡുകൾ എന്നിവയും മറ്റും വേഗത്തിലാക്കാൻ വലിയ ക്ലൗഡ് സെർവറുകൾ പ്രയോജനപ്പെടുത്തുക. - നിങ്ങൾ യാത്രയിലായിരിക്കുമ്പോൾ ബാറ്ററി ലൈഫ് സംരക്ഷിക്കുക. - എല്ലാ തീവ്രമായ കമ്പ്യൂട്ടേഷനും നിങ്ങളുടെ സെർവറിൽ പ്രവർത്തിക്കുന്നു. - നിങ്ങൾ ഇനി Chrome-ന്റെ അധിക ഇൻസ്റ്റൻസുകൾ പ്രവർത്തിപ്പിക്കുന്നില്ല.
    nb_NO: Kodeserver er VS-kode som kjører på en ekstern server, tilgjengelig via nettleseren. - Kode på Chromebooken, nettbrettet og den bærbare datamaskinen med et konsistent utviklingsmiljø. - Hvis du har en Windows- eller Mac-arbeidsstasjon, kan du enklere utvikle for Linux. - Dra nytte av store skyservere for å få fart på tester, kompileringer, nedlastinger og mer. - Spar batterilevetid når du er på farten. - All intensiv beregning kjører på serveren din. - Du kjører ikke lenger overflødige forekomster av Chrome.
    nl_NL: Code-server is VS Code dat op een externe server draait en toegankelijk is via de browser. - Programmeer op je Chromebook, tablet en laptop met een consistente ontwikkelomgeving. - Als je een Windows- of Mac-werkstation hebt, kun je gemakkelijker ontwikkelen voor Linux. - Profiteer van grote cloudservers om tests, compilaties, downloads en meer te versnellen. - Bespaar batterijduur wanneer je onderweg bent. - Alle intensieve berekeningen worden op je eigen server uitgevoerd. - Je hoeft geen overbodige Chrome-instanties meer te draaien.
    pl_PL: Code-server to program VS Code działający na zdalnym serwerze, do którego można uzyskać dostęp za pośrednictwem przeglądarki. - Koduj na Chromebooku, tablecie i laptopie w spójnym środowisku programistycznym. - Jeśli masz stację roboczą z systemem Windows lub Mac, możesz łatwiej tworzyć aplikacje dla systemu Linux. - Korzystaj z dużych serwerów w chmurze, aby przyspieszyć testy, kompilacje, pobieranie i wiele więcej. - Wydłuż czas pracy baterii w podróży. - Wszystkie intensywne obliczenia są wykonywane na Twoim serwerze. - Nie musisz już uruchamiać wielu instancji przeglądarki Chrome.
    pt_BR: O Code-server é o VS Code executado em um servidor remoto, acessível pelo navegador. - Programe no seu Chromebook, tablet e laptop com um ambiente de desenvolvimento consistente. - Se você tiver uma estação de trabalho Windows ou Mac, desenvolva para Linux com mais facilidade. - Aproveite os grandes servidores em nuvem para acelerar testes, compilações, downloads e muito mais. - Economize bateria quando estiver em movimento. - Todos os cálculos intensivos são executados no seu servidor. - Você não precisa mais executar instâncias desnecessárias do Chrome.
    ro_RO: Code-server este VS Code care rulează pe un server la distanță, accesibil prin browser. - Codează pe Chromebook, tabletă și laptop cu un mediu de dezvoltare consistent. - Dacă ai o stație de lucru Windows sau Mac, dezvolți mai ușor pentru Linux. - Profită de serverele cloud mari pentru a accelera testele, compilările, descărcările și multe altele. - Menține durata de viață a bateriei atunci când ești în mișcare. - Toate calculele intensive se execută pe serverul tău. - Nu mai rulezi instanțe suplimentare de Chrome.
    ru_RU: Code-server — это VS Code, работающий на удалённом сервере и доступный через браузер. — Пишите код на Chromebook, планшете и ноутбуке в единой среде разработки. — Если у вас рабочая станция Windows или Mac, вам будет проще разрабатывать под Linux. — Воспользуйтесь преимуществами больших облачных серверов для ускорения тестирования, компиляции, загрузки и многого другого. — Экономьте заряд батареи в дороге. — Все ресурсоёмкие вычисления выполняются на вашем сервере. — Вам больше не нужно запускать лишние экземпляры Chrome.
    sk_SK: Code-server je VS Code bežiaci na vzdialenom serveri, prístupnom cez prehliadač. - Kódujte na Chromebooku, tablete a notebooku s konzistentným vývojovým prostredím. - Ak máte pracovnú stanicu so systémom Windows alebo Mac, jednoduchšie vyvíjajte pre Linux. - Využite výhody veľkých cloudových serverov na zrýchlenie testov, kompilácií, sťahovania a ďalších úloh. - Šetrite výdrž batérie, keď ste na cestách. - Všetky náročné výpočty bežia na vašom serveri. - Už nespúšťate nadmerné množstvo inštancií prehliadača Chrome.
    sv_SE: Kodserver är VS-kod som körs på en fjärrserver, åtkomlig via webbläsaren. - Koda på din Chromebook, surfplatta och bärbara dator med en konsekvent utvecklingsmiljö. - Om du har en Windows- eller Mac-arbetsstation kan du enklare utveckla för Linux. - Dra nytta av stora molnservrar för att snabba upp tester, kompileringar, nedladdningar med mera. - Spara batteritid när du är på språng. - All intensiv beräkning körs på din server. - Du kör inte längre överflödiga instanser av Chrome.
    tr_TR: Code-server, tarayıcı üzerinden erişilebilen, uzak bir sunucuda çalışan VS Code'dur. - Chromebook'unuzda, tabletinizde ve dizüstü bilgisayarınızda tutarlı bir geliştirme ortamıyla kod yazın. - Windows veya Mac iş istasyonunuz varsa, Linux için daha kolay geliştirme yapın. - Testleri, derlemeleri, indirmeleri ve daha fazlasını hızlandırmak için büyük bulut sunucularından yararlanın. - Hareket halindeyken pil ömrünü koruyun. - Tüm yoğun hesaplamalar sunucunuzda çalışır. - Artık Chrome'un gereksiz örneklerini çalıştırmanıza gerek yok.
    zh_CN: Code-server 让 VS Code 运行在远程服务器上，并通过浏览器访问。你可以在 Chromebook、平板电脑和笔记本电脑上使用一致的开发环境，也可在 Windows 或 Mac 工作站上更方便地为 Linux 开发。借助大型云服务器加速测试、编译和下载，并在外出时节省电池电量。所有密集计算都在服务器上完成，无需在本地运行多余的 Chrome 实例。
    zh_TW: Code-server 讓 VS Code 執行在遠端伺服器上，並透過瀏覽器訪問。你可以在 Chromebook、平板電腦和膝上型電腦上使用一致的開發環境，也可在 Windows 或 Mac 工作站上更方便地為 Linux 開發。藉助大型雲伺服器加速測試、編譯和下載，並在外出時節省電池電量。所有密集計算都在伺服器上完成，無需在本地執行多餘的 Chrome 例項。
  tagline:
    en_US: VS Code running on a remote server, accessible through the browser. - Code on your Chromebook, tablet, and laptop with a consistent dev environment. - If you have a Windows or Mac workstation, more easily develop for Linux. - Take advantage of large cloud servers to speed up tests, compilations, downloads, and more. - Preserve battery life when you're on the go. - All intensive computation runs on your server. - You're no longer running excess instances of Chrome.
    ca_ES: VS Code que s'executa en un servidor remot, accessible a través del navegador. - Codi al vostre Chromebook, tauleta i portàtil amb un entorn de desenvolupament coherent. - Si teniu una estació de treball Windows o Mac, desenvolupeu més fàcilment per a Linux. - Aprofiteu els grans servidors al núvol per accelerar les proves, les compilacions, les descàrregues i molt més. - Preserveu la durada de la bateria quan esteu fora de casa. - Tot el càlcul intensiu s'executa al vostre servidor. - Ja no executeu instàncies addicionals de Chrome.
    cs_CZ: VS Code běžící na vzdáleném serveru, přístupném přes prohlížeč. - Kódujte na Chromebooku, tabletu a notebooku s konzistentním vývojářským prostředím. - Pokud máte pracovní stanici s Windows nebo Mac, snáze vyvíjejte pro Linux. - Využijte velké cloudové servery k urychlení testů, kompilací, stahování a dalších činností. - Šetřete výdrž baterie, když jste na cestách. - Veškeré náročné výpočty běží na vašem serveru. - Již nespouštíte nadbytečné instance Chromu.
    da_DK: VS-kode, der kører på en ekstern server, tilgængelig via browseren. - Kod på din Chromebook, tablet og bærbare computer med et ensartet udviklingsmiljø. - Hvis du har en Windows- eller Mac-arbejdsstation, kan du lettere udvikle til Linux. - Udnyt store cloud-servere til at fremskynde test, kompileringer, downloads og meget mere. - Spar på batteriet, når du er på farten. - Al intensiv beregning kører på din server. - Du kører ikke længere overskydende instanser af Chrome.
    de_DE: VS Code läuft auf einem Remote-Server und ist über den Browser zugänglich. – Programmieren Sie auf Ihrem Chromebook, Tablet und Laptop mit einer einheitlichen Entwicklungsumgebung. – Wenn Sie einen Windows- oder Mac-Arbeitsplatz haben, können Sie einfacher für Linux entwickeln. – Profitieren Sie von großen Cloud-Servern, um Tests, Kompilierungen, Downloads und mehr zu beschleunigen. – Sparen Sie Akku, wenn Sie unterwegs sind. – Alle rechenintensiven Vorgänge werden auf Ihrem Server ausgeführt. – Sie benötigen keine unnötigen Chrome-Instanzen mehr.
    el_GR: Κώδικας VS που εκτελείται σε απομακρυσμένο διακομιστή, προσβάσιμος μέσω του προγράμματος περιήγησης. - Κωδικοποιήστε στο Chromebook, το tablet και τον φορητό υπολογιστή σας με ένα συνεπές περιβάλλον προγραμματιστή. - Εάν διαθέτετε σταθμό εργασίας Windows ή Mac, αναπτύξτε τον πιο εύκολα για Linux. - Επωφεληθείτε από μεγάλους διακομιστές cloud για να επιταχύνετε τις δοκιμές, τις μεταγλωττίσεις, τις λήψεις και πολλά άλλα. - Εξοικονομήστε χρόνο ζωής της μπαταρίας όταν βρίσκεστε εν κινήσει. - Όλοι οι εντατικοί υπολογισμοί εκτελούνται στον διακομιστή σας. - Δεν εκτελείτε πλέον υπερβολικές παρουσίες του Chrome.
    en_GB: Vs Code running on a remote server, accessible through the browser. - Code on your Chromebook, tablet, and laptop with a consistent dev environment. - If you have a Windows or Mac workstation, more easily develop for Linux. - Take advantage of large cloud servers to speed up tests, compilations, downloads, and more. - Preserve battery life when you're on the go. - All intensive computation runs on your server. - You're no longer running excess instances of Chrome.
    es_ES: VS Code se ejecuta en un servidor remoto, accesible a través del navegador. - Programa en tu Chromebook, tableta y portátil con un entorno de desarrollo consistente. - Si tienes una estación de trabajo Windows o Mac, desarrolla para Linux con mayor facilidad. - Aprovecha los grandes servidores en la nube para acelerar las pruebas, compilaciones, descargas y más. - Conserva la duración de la batería cuando estás fuera de casa. - Todos los cálculos intensivos se ejecutan en tu servidor. - Ya no ejecutas instancias innecesarias de Chrome.
    fr_FR: VS Code s'exécute sur un serveur distant et est accessible via le navigateur. - Développez sur votre Chromebook, tablette et ordinateur portable avec un environnement de développement homogène. - Si vous possédez un poste de travail Windows ou Mac, développez plus facilement pour Linux. - Profitez de la puissance des serveurs cloud pour accélérer les tests, les compilations, les téléchargements et bien plus encore. - Préservez l'autonomie de votre batterie lors de vos déplacements. - Tous les calculs intensifs sont exécutés sur votre serveur. - Vous n'exécutez plus d'instances supplémentaires de Chrome.
    ga_IE: Cód VS ag rith ar fhreastalaí cianda, inrochtana tríd an mbrabhsálaí. - Cód ar do Chromebook, taibléad, agus ríomhaire glúine le timpeallacht forbartha comhsheasmhach. - Má tá stáisiún oibre Windows nó Mac agat, forbair níos éasca do Linux. - Bain leas as freastalaithe scamall móra chun tástálacha, tiomsúcháin, íoslódálacha, agus níos mó a bhrostú. - Caomhnaigh saol na ceallraí nuair a bhíonn tú ag taisteal. - Ritheann an ríomhaireacht dhian go léir ar do fhreastalaí. - Níl tú ag rith cásanna breise de Chrome a thuilleadh.
    hr_HR: VS Code koji se izvodi na udaljenom poslužitelju, dostupnom putem preglednika. - Kodirajte na svom Chromebooku, tabletu i prijenosnom računalu s konzistentnim razvojnim okruženjem. - Ako imate Windows ili Mac radnu stanicu, lakše razvijajte za Linux. - Iskoristite velike cloud poslužitelje za ubrzavanje testova, kompilacija, preuzimanja i još mnogo toga. - Očuvajte vijek trajanja baterije kada ste u pokretu. - Sva intenzivna izračunavanja izvode se na vašem poslužitelju. - Više ne pokrećete dodatne instance Chromea.
    hu_HU: VS Code távoli szerveren fut, böngészőn keresztül elérhető. – Kódolj Chromebookodon, táblagépeden és laptopodon konzisztens fejlesztői környezetben. – Ha Windows vagy Mac munkaállomásod van, könnyebben fejleszthetsz Linuxra. – Használd ki a nagy felhőszervereket a tesztek, fordítások, letöltések és egyebek felgyorsításához. – Környezetbarát akkumulátor-üzemidő útközben. – Minden intenzív számítás a szervereden fut. – Többé nem kell felesleges Chrome-példányokat futtatnod.
    it_IT: VS Code in esecuzione su un server remoto, accessibile tramite browser. - Scrivi codice su Chromebook, tablet e laptop con un ambiente di sviluppo coerente. - Se possiedi una workstation Windows o Mac, sviluppa più facilmente per Linux. - Sfrutta i grandi server cloud per velocizzare test, compilazioni, download e altro ancora. - Risparmia la batteria quando sei in movimento. - Tutti i calcoli intensivi vengono eseguiti sul tuo server. - Non dovrai più eseguire istanze superflue di Chrome.
    ja_JP: VS Code はリモート サーバー上で動作し、ブラウザからアクセスできます。 - Chromebook、タブレット、ノートパソコンで一貫した開発環境を使用してコーディングできます。 - Windows または Mac ワークステーションをお持ちの場合は、Linux 向けの開発がより簡単になります。 - 大規模なクラウド サーバーを活用して、テスト、コンパイル、ダウンロードなどを高速化できます。 - 外出先でもバッテリー寿命を節約できます。 - すべての負荷の高い計算はサーバー上で実行されます。 - Chrome の余分なインスタンスを実行する必要がなくなります。
    ko_KR: VS Code는 원격 서버에서 실행되며 브라우저를 통해 접속할 수 있습니다. - 크롬북, 태블릿, 노트북에서 일관된 개발 환경을 구축할 수 있습니다. - Windows 또는 Mac 워크스테이션을 사용하는 경우 Linux용 개발을 더욱 쉽게 수행할 수 있습니다. - 대규모 클라우드 서버를 활용하여 테스트, 컴파일, 다운로드 등의 속도를 향상시킬 수 있습니다. - 이동 중에도 배터리 수명을 절약할 수 있습니다. - 모든 고강도 연산은 서버에서 실행됩니다. - 더 이상 Chrome의 여러 인스턴스를 동시에 실행할 필요가 없습니다.
    ml_IN: ബ്രൗസറിലൂടെ ആക്‌സസ് ചെയ്യാവുന്ന ഒരു റിമോട്ട് സെർവറിൽ പ്രവർത്തിക്കുന്ന VS കോഡ്. - നിങ്ങളുടെ Chromebook, ടാബ്‌ലെറ്റ്, ലാപ്‌ടോപ്പ് എന്നിവയിൽ സ്ഥിരമായ ഒരു ഡെവലപ്‌മെന്റ് പരിതസ്ഥിതിയിൽ കോഡ് ചെയ്യുക. - നിങ്ങൾക്ക് ഒരു Windows അല്ലെങ്കിൽ Mac വർക്ക്‌സ്റ്റേഷൻ ഉണ്ടെങ്കിൽ, Linux-നായി കൂടുതൽ എളുപ്പത്തിൽ വികസിപ്പിക്കുക. - ടെസ്റ്റുകൾ, സമാഹാരങ്ങൾ, ഡൗൺലോഡുകൾ എന്നിവയും മറ്റും വേഗത്തിലാക്കാൻ വലിയ ക്ലൗഡ് സെർവറുകൾ പ്രയോജനപ്പെടുത്തുക. - നിങ്ങൾ യാത്രയിലായിരിക്കുമ്പോൾ ബാറ്ററി ലൈഫ് സംരക്ഷിക്കുക. - എല്ലാ തീവ്രമായ കമ്പ്യൂട്ടേഷനും നിങ്ങളുടെ സെർവറിൽ പ്രവർത്തിക്കുന്നു. - നിങ്ങൾ ഇനി Chrome-ന്റെ അധിക ഇൻസ്റ്റൻസുകൾ പ്രവർത്തിപ്പിക്കുന്നില്ല.
    nb_NO: VS-kode som kjører på en ekstern server, tilgjengelig via nettleseren. - Kode på Chromebooken, nettbrettet og den bærbare datamaskinen med et konsistent utviklingsmiljø. - Hvis du har en Windows- eller Mac-arbeidsstasjon, kan du enklere utvikle for Linux. - Dra nytte av store skyservere for å få fart på tester, kompileringer, nedlastinger og mer. - Spar batterilevetid når du er på farten. - All intensiv beregning kjører på serveren din. - Du kjører ikke lenger overflødige forekomster av Chrome.
    nl_NL: VS Code draait op een externe server en is toegankelijk via de browser. - Programmeer op je Chromebook, tablet en laptop met een consistente ontwikkelomgeving. - Ontwikkel eenvoudiger voor Linux als je een Windows- of Mac-werkstation hebt. - Profiteer van grote cloudservers om tests, compilaties, downloads en meer te versnellen. - Bespaar batterijduur wanneer je onderweg bent. - Alle intensieve berekeningen worden op je eigen server uitgevoerd. - Je hebt geen overbodige Chrome-instanties meer nodig.
    pl_PL: VS Code działa na serwerze zdalnym i jest dostępny przez przeglądarkę. - Koduj na Chromebooku, tablecie i laptopie w spójnym środowisku programistycznym. - Jeśli masz stację roboczą z systemem Windows lub Mac, możesz łatwiej tworzyć aplikacje dla systemu Linux. - Korzystaj z dużych serwerów w chmurze, aby przyspieszyć testy, kompilacje, pobieranie i wiele więcej. - Wydłuż czas pracy baterii w podróży. - Wszystkie intensywne obliczenia są wykonywane na Twoim serwerze. - Nie musisz już uruchamiać wielu instancji przeglądarki Chrome.
    pt_BR: O VS Code roda em um servidor remoto, acessível pelo navegador. - Programe no seu Chromebook, tablet e laptop com um ambiente de desenvolvimento consistente. - Se você tiver uma estação de trabalho Windows ou Mac, desenvolva para Linux com mais facilidade. - Aproveite os grandes servidores em nuvem para acelerar testes, compilações, downloads e muito mais. - Economize bateria quando estiver em movimento. - Todos os cálculos intensivos são executados no seu servidor. - Você não precisa mais executar instâncias desnecessárias do Chrome.
    ro_RO: VS Code rulează pe un server la distanță, accesibil prin browser. - Codează pe Chromebook, tabletă și laptop cu un mediu de dezvoltare consistent. - Dacă ai o stație de lucru Windows sau Mac, dezvoltă mai ușor pentru Linux. - Profită de serverele cloud mari pentru a accelera testele, compilările, descărcările și multe altele. - Menține durata de viață a bateriei atunci când ești în mișcare. - Toate calculele intensive se execută pe serverul tău. - Nu mai rulezi instanțe suplimentare de Chrome.
    ru_RU: VS Code работает на удалённом сервере и доступен через браузер. - Пишите код на Chromebook, планшете и ноутбуке в единой среде разработки. - Если у вас рабочая станция Windows или Mac, разработка для Linux становится проще. - Воспользуйтесь преимуществами больших облачных серверов для ускорения тестирования, компиляции, загрузки и многого другого. - Экономьте заряд батареи в дороге. - Все ресурсоёмкие вычисления выполняются на вашем сервере. - Вам больше не нужно запускать лишние экземпляры Chrome.
    sk_SK: VS Code bežiaci na vzdialenom serveri, prístupnom cez prehliadač. - Kódujte na Chromebooku, tablete a notebooku s konzistentným vývojovým prostredím. - Ak máte pracovnú stanicu so systémom Windows alebo Mac, jednoduchšie vyvíjajte pre Linux. - Využite výhody veľkých cloudových serverov na zrýchlenie testov, kompilácií, sťahovania a ďalších úloh. - Šetrite výdrž batérie, keď ste na cestách. - Všetky náročné výpočty bežia na vašom serveri. - Už nespúšťate nadmerné množstvo inštancií prehliadača Chrome.
    sv_SE: VS-kod som körs på en fjärrserver, tillgänglig via webbläsaren. - Koda på din Chromebook, surfplatta och bärbara dator med en konsekvent utvecklingsmiljö. - Om du har en Windows- eller Mac-arbetsstation kan du enklare utveckla för Linux. - Dra nytta av stora molnservrar för att snabba upp tester, kompileringar, nedladdningar med mera. - Spara batteritid när du är på språng. - All intensiv beräkning körs på din server. - Du kör inte längre överflödiga instanser av Chrome.
    tr_TR: Uzak bir sunucuda çalışan ve tarayıcı üzerinden erişilebilen VS Code. - Chromebook'unuzda, tabletinizde ve dizüstü bilgisayarınızda tutarlı bir geliştirme ortamıyla kod yazın. - Windows veya Mac iş istasyonunuz varsa, Linux için daha kolay geliştirme yapın. - Testleri, derlemeleri, indirmeleri ve daha fazlasını hızlandırmak için büyük bulut sunucularından yararlanın. - Hareket halindeyken pil ömrünü koruyun. - Tüm yoğun hesaplamalar sunucunuzda çalışır. - Artık Chrome'un gereksiz örneklerini çalıştırmanıza gerek yok.
    zh_CN: 在浏览器中使用远程服务器上的 VS Code。
    zh_TW: 在瀏覽器中使用遠端伺服器上的 VS Code。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/code-server-banner.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/code-server-banner.png
  title:
    en_US: Code server (LinuxServer.io)
    ca_ES: Code server (LinuxServer.io)
    cs_CZ: Code server (LinuxServer.io)
    da_DK: Code server (LinuxServer.io)
    de_DE: Code server (LinuxServer.io)
    el_GR: Code server (LinuxServer.io)
    en_GB: Code server (LinuxServer.io)
    es_ES: Code server (LinuxServer.io)
    fr_FR: Code server (LinuxServer.io)
    ga_IE: Code server (LinuxServer.io)
    hr_HR: Code server (LinuxServer.io)
    hu_HU: Code server (LinuxServer.io)
    it_IT: Code server (LinuxServer.io)
    ja_JP: Code server (LinuxServer.io)
    ko_KR: Code server (LinuxServer.io)
    ml_IN: Code server (LinuxServer.io)
    nb_NO: Code server (LinuxServer.io)
    nl_NL: Code server (LinuxServer.io)
    pl_PL: Code server (LinuxServer.io)
    pt_BR: Code server (LinuxServer.io)
    ro_RO: Code server (LinuxServer.io)
    ru_RU: Code server (LinuxServer.io)
    sk_SK: Code server (LinuxServer.io)
    sv_SE: Code server (LinuxServer.io)
    tr_TR: Code server (LinuxServer.io)
    zh_CN: Code server（LinuxServer.io）
    zh_TW: Code server（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxservercodeserver
  port_map: '8443'
  version: 4.137.0
