name: linuxserver-nzbhydra2
services:
  app:
    image: linuxserver/nzbhydra2:9.0.1@sha256:96b458553d240bb58c172dab6dece54a796b6e3d653de727b68c09f12a9b9015
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 5076
        published: 5076
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nzbhydra2/config
        target: /config
      - type: bind
        source: /DATA/AppData/nzbhydra2/downloads
        target: /downloads
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservernzbhydra2/assets/icon.png
  title:
    en_US: Nzbhydra2 (LinuxServer.io)
    ca_ES: Nzbhydra2 (LinuxServer.io)
    cs_CZ: Nzbhydra2 (LinuxServer.io)
    da_DK: Nzbhydra2 (LinuxServer.io)
    de_DE: Nzbhydra2 (LinuxServer.io)
    el_GR: Nzbhydra2 (LinuxServer.io)
    en_GB: Nzbhydra2 (LinuxServer.io)
    es_ES: Nzbhydra2 (LinuxServer.io)
    fr_FR: Nzbhydra2 (LinuxServer.io)
    ga_IE: Nzbhydra2 (LinuxServer.io)
    hr_HR: Nzbhydra2 (LinuxServer.io)
    hu_HU: Nzbhydra2 (LinuxServer.io)
    it_IT: Nzbhydra2 (LinuxServer.io)
    ja_JP: Nzbhydra2 (LinuxServer.io)
    ko_KR: Nzbhydra2 (LinuxServer.io)
    ml_IN: Nzbhydra2 (LinuxServer.io)
    nb_NO: Nzbhydra2 (LinuxServer.io)
    nl_NL: Nzbhydra2 (LinuxServer.io)
    pl_PL: Nzbhydra2 (LinuxServer.io)
    pt_BR: Nzbhydra2 (LinuxServer.io)
    ro_RO: Nzbhydra2 (LinuxServer.io)
    ru_RU: Nzbhydra2 (LinuxServer.io)
    sk_SK: Nzbhydra2 (LinuxServer.io)
    sv_SE: Nzbhydra2 (LinuxServer.io)
    tr_TR: Nzbhydra2 (LinuxServer.io)
    zh_CN: Nzbhydra2（LinuxServer.io）
    zh_TW: Nzbhydra2（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservernzbhydra2
  port_map: '5076'
  version: 9.0.1
