name: linuxserver-ci
services:
  app:
    image: linuxserver/ci:b1ca9f98-ls65
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ci/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverci/assets/icon.svg
  title:
    en_US: Ci
    zh_CN: Ci
    ca_ES: Ci
    cs_CZ: Ci
    da_DK: Ci
    de_DE: Ci
    el_GR: Ci
    en_GB: Ci
    es_ES: Ci
    fr_FR: Ci
    ga_IE: Ci
    hr_HR: Ci
    hu_HU: Ci
    it_IT: Ci
    ja_JP: Ci
    ko_KR: Ci
    ml_IN: Ci
    nb_NO: Ci
    nl_NL: Ci
    pl_PL: Ci
    pt_BR: Ci
    ro_RO: Ci
    ru_RU: Ci
    sk_SK: Ci
    sv_SE: Ci
    tr_TR: Ci
    zh_TW: Ci
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserverci
  version: b1ca9f98-ls65
