name: linuxserver-onlyoffice
services:
  app:
    image: linuxserver/onlyoffice:9.4.0@sha256:65bc2cdf3934953e1d06e102ed5c9b5cb99b9bdaf360a7ec69cdfd563aeed36c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/onlyoffice/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveronlyoffice/assets/icon.png
  title:
    en_US: Onlyoffice (LinuxServer.io)
    ca_ES: Onlyoffice (LinuxServer.io)
    cs_CZ: Onlyoffice (LinuxServer.io)
    da_DK: Onlyoffice (LinuxServer.io)
    de_DE: Onlyoffice (LinuxServer.io)
    el_GR: Onlyoffice (LinuxServer.io)
    en_GB: Onlyoffice (LinuxServer.io)
    es_ES: Onlyoffice (LinuxServer.io)
    fr_FR: Onlyoffice (LinuxServer.io)
    ga_IE: Onlyoffice (LinuxServer.io)
    hr_HR: Onlyoffice (LinuxServer.io)
    hu_HU: Onlyoffice (LinuxServer.io)
    it_IT: Onlyoffice (LinuxServer.io)
    ja_JP: Onlyoffice (LinuxServer.io)
    ko_KR: Onlyoffice (LinuxServer.io)
    ml_IN: Onlyoffice (LinuxServer.io)
    nb_NO: Onlyoffice (LinuxServer.io)
    nl_NL: Onlyoffice (LinuxServer.io)
    pl_PL: Onlyoffice (LinuxServer.io)
    pt_BR: Onlyoffice (LinuxServer.io)
    ro_RO: Onlyoffice (LinuxServer.io)
    ru_RU: Onlyoffice (LinuxServer.io)
    sk_SK: Onlyoffice (LinuxServer.io)
    sv_SE: Onlyoffice (LinuxServer.io)
    tr_TR: Onlyoffice (LinuxServer.io)
    zh_CN: Onlyoffice（LinuxServer.io）
    zh_TW: Onlyoffice（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserveronlyoffice
  port_map: '3000'
  version: 9.4.0
