name: linuxserver-ngircd
services:
  app:
    image: linuxserver/ngircd:version-27-r1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 6667
        published: 6667
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ngircd/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Ngircd is a free, portable and lightweight Internet Relay Chat server for small or private networks, developed under the GNU General Public License (GPL). It is easy to configure, can cope with dynamic IP addresses, and supports IPv6, SSL-protected connections as well as PAM for authentication. It is written from scratch and not based on the original IRCd.
    ca_ES: Ngircd és un servidor de xat de retransmissió per Internet gratuït, portàtil i lleuger per a xarxes petites o privades, desenvolupat sota la Llicència Pública General de GNU (GPL). És fàcil de configurar, pot gestionar adreces IP dinàmiques i admet connexions IPv6 i protegides per SSL, així com PAM per a l'autenticació. Està escrit des de zero i no es basa en l'IRCd original.
    cs_CZ: Ngircd je bezplatný, přenosný a lehký server pro internetový chat (Internet Relay Chat) pro malé nebo soukromé sítě, vyvinutý pod licencí GNU General Public License (GPL). Je snadno konfigurovatelný, zvládá dynamické IP adresy a podporuje IPv6, připojení chráněná SSL a také PAM pro ověřování. Je napsán od nuly a není založen na původním IRCd.
    da_DK: Ngircd er en gratis, bærbar og let Internet Relay Chat-server til små eller private netværk, udviklet under GNU General Public License (GPL). Den er nem at konfigurere, kan håndtere dynamiske IP-adresser og understøtter IPv6, SSL-beskyttede forbindelser samt PAM til godkendelse. Den er skrevet fra bunden og er ikke baseret på den originale IRCd.
    de_DE: Ngircd ist ein kostenloser, portabler und ressourcenschonender IRCd-Server für kleine oder private Netzwerke, der unter der GNU General Public License (GPL) entwickelt wurde. Er ist einfach zu konfigurieren, kommt mit dynamischen IP-Adressen zurecht und unterstützt IPv6, SSL-geschützte Verbindungen sowie PAM zur Authentifizierung. Er wurde von Grund auf neu entwickelt und basiert nicht auf dem ursprünglichen IRCd.
    el_GR: Το Ngircd είναι ένας δωρεάν, φορητός και ελαφρύς διακομιστής Internet Relay Chat για μικρά ή ιδιωτικά δίκτυα, που αναπτύχθηκε υπό την Γενική Άδεια Δημόσιας Χρήσης GNU (GPL). Είναι εύκολος στη διαμόρφωση, μπορεί να διαχειριστεί δυναμικές διευθύνσεις IP και υποστηρίζει IPv6, συνδέσεις με προστασία SSL, καθώς και PAM για έλεγχο ταυτότητας. Είναι γραμμένος από την αρχή και δεν βασίζεται στο αρχικό IRCd.
    en_GB: Ngircd is a free, portable and lightweight Internet Relay Chat server for small or private networks, developed under the Gnu General Public Licence (Gpl). It is easy to configure, can cope with dynamic Ip addresses, and supports IPv6, Ssl-protected connections as well as Pam for authentication. It is written from scratch and not based on the original Ircd.
    es_ES: Ngircd es un servidor de chat por retransmisión de Internet (IRC) gratuito, portátil y ligero para redes pequeñas o privadas, desarrollado bajo la Licencia Pública General de GNU (GPL). Es fácil de configurar, admite direcciones IP dinámicas y es compatible con IPv6, conexiones protegidas por SSL y PAM para la autenticación. Ha sido desarrollado desde cero y no se basa en el IRCd original.
    fr_FR: Ngircd est un serveur IRC (Internet Relay Chat) gratuit, portable et léger, conçu pour les petits réseaux ou les réseaux privés. Développé sous licence GNU GPL, il est facile à configurer, compatible avec les adresses IP dynamiques et prend en charge IPv6, les connexions sécurisées SSL et l'authentification PAM. Il a été entièrement réécrit et n'est pas basé sur IRCd.
    ga_IE: Is freastalaí Idirlín Athsheolta Comhrá saor in aisce, iniompartha agus éadrom é Ngircd do líonraí beaga nó príobháideacha, arna fhorbairt faoin gCeadúnas Poiblí Ginearálta GNU (GPL). Tá sé éasca a chumrú, is féidir leis déileáil le seoltaí IP dinimiciúla, agus tacaíonn sé le IPv6, naisc atá faoi chosaint SSL chomh maith le PAM le haghaidh fíordheimhnithe. Scríobhadh é ón tús agus níl sé bunaithe ar an IRCd bunaidh.
    hr_HR: Ngircd je besplatni, prenosivi i lagani Internet Relay Chat poslužitelj za male ili privatne mreže, razvijen pod GNU General Public License (GPL). Jednostavan je za konfiguriranje, može se nositi s dinamičkim IP adresama i podržava IPv6, SSL-zaštićene veze kao i PAM za autentifikaciju. Napisan je od nule i nije temeljen na originalnom IRCd-u.
    hu_HU: Az Ngircd egy ingyenes, hordozható és könnyű Internet Relay Chat szerver kis vagy privát hálózatok számára, amelyet a GNU General Public License (GPL) alatt fejlesztettek ki. Könnyen konfigurálható, képes kezelni a dinamikus IP-címeket, és támogatja az IPv6-ot, az SSL-védett kapcsolatokat, valamint a PAM hitelesítést. A program a nulláról íródott, és nem az eredeti IRCd-n alapul.
    it_IT: Ngircd è un server IRCd gratuito, portatile e leggero per reti di piccole dimensioni o private, sviluppato sotto licenza GNU General Public License (GPL). È facile da configurare, gestisce indirizzi IP dinamici e supporta IPv6, connessioni protette da SSL e PAM per l'autenticazione. È stato scritto da zero e non si basa sull'originale IRCd.
    ja_JP: Ngircdは、GNU一般公衆利用許諾契約書（GPL）に基づいて開発された、小規模ネットワークやプライベートネットワーク向けの無料かつポータブルで軽量なインターネットリレーチャット（IRC）サーバーです。設定が簡単で、動的IPアドレスに対応し、IPv6、SSL保護接続、認証のためのPAMをサポートしています。オリジナルのIRCdをベースにしたものではなく、ゼロから開発されています。
    ko_KR: Ngircd는 GNU 일반 공중 라이선스(GPL)에 따라 개발된 소규모 또는 사설 네트워크를 위한 무료, 휴대용, 경량 인터넷 릴레이 채팅(IRC) 서버입니다. 설정이 간편하고, 동적 IP 주소를 지원하며, IPv6, SSL 보호 연결 및 PAM 인증을 지원합니다. 이 프로그램은 기존 IRCd를 기반으로 하지 않고 처음부터 새로 작성되었습니다.
    ml_IN: ചെറുതോ സ്വകാര്യമോ ആയ നെറ്റ്‌വർക്കുകൾക്കായി GNU ജനറൽ പബ്ലിക് ലൈസൻസ് (GPL) പ്രകാരം വികസിപ്പിച്ചെടുത്ത സൗജന്യവും പോർട്ടബിളും ഭാരം കുറഞ്ഞതുമായ ഇന്റർനെറ്റ് റിലേ ചാറ്റ് സെർവറാണ് Ngircd. ഇത് കോൺഫിഗർ ചെയ്യാൻ എളുപ്പമാണ്, ഡൈനാമിക് IP വിലാസങ്ങളെ നേരിടാൻ കഴിയും, കൂടാതെ IPv6, SSL- പരിരക്ഷിത കണക്ഷനുകളെയും പ്രാമാണീകരണത്തിനായി PAM-നെയും പിന്തുണയ്ക്കുന്നു. ഇത് ആദ്യം മുതൽ എഴുതിയതാണ്, യഥാർത്ഥ IRCd അടിസ്ഥാനമാക്കിയുള്ളതല്ല.
    nb_NO: Ngircd er en gratis, bærbar og lett Internet Relay Chat-server for små eller private nettverk, utviklet under GNU General Public License (GPL). Den er enkel å konfigurere, kan håndtere dynamiske IP-adresser og støtter IPv6, SSL-beskyttede tilkoblinger samt PAM for autentisering. Den er skrevet fra bunnen av og er ikke basert på den originale IRCd.
    nl_NL: Ngircd is een gratis, draagbare en lichtgewicht Internet Relay Chat-server voor kleine of privénetwerken, ontwikkeld onder de GNU General Public License (GPL). Het is eenvoudig te configureren, kan overweg met dynamische IP-adressen en ondersteunt IPv6, SSL-beveiligde verbindingen en PAM voor authenticatie. Het is volledig opnieuw geschreven en niet gebaseerd op de originele IRCd.
    pl_PL: Ngircd to darmowy, przenośny i lekki serwer IRCd dla małych lub prywatnych sieci, opracowany na licencji GNU General Public License (GPL). Jest łatwy w konfiguracji, obsługuje dynamiczne adresy IP i obsługuje połączenia IPv6, połączenia zabezpieczone protokołem SSL oraz uwierzytelnianie PAM. Został napisany od podstaw i nie jest oparty na oryginalnym IRCd.
    pt_BR: O Ngircd é um servidor IRC gratuito, portátil e leve para redes pequenas ou privadas, desenvolvido sob a Licença Pública Geral GNU (GPL). É fácil de configurar, suporta endereços IP dinâmicos e IPv6, conexões protegidas por SSL e PAM para autenticação. Foi escrito do zero e não é baseado no IRCd original.
    ro_RO: Ngircd este un server de chat prin internet (Internet Relay Chat) gratuit, portabil și ușor, pentru rețele mici sau private, dezvoltat sub licența GNU General Public License (GPL). Este ușor de configurat, poate gestiona adrese IP dinamice și acceptă IPv6, conexiuni protejate prin SSL, precum și PAM pentru autentificare. Este scris de la zero și nu se bazează pe IRCd-ul original.
    ru_RU: Ngircd — это бесплатный, портативный и легковесный сервер интернет-чата для небольших или частных сетей, разработанный под лицензией GNU General Public License (GPL). Он прост в настройке, может работать с динамическими IP-адресами и поддерживает IPv6, SSL-защищенные соединения, а также PAM для аутентификации. Он написан с нуля и не основан на оригинальном IRCd.
    sk_SK: Ngircd je bezplatný, prenosný a ľahký server Internet Relay Chat pre malé alebo súkromné siete, vyvinutý pod licenciou GNU General Public License (GPL). Je ľahko konfigurovateľný, dokáže pracovať s dynamickými IP adresami a podporuje IPv6, pripojenia chránené SSL, ako aj PAM na autentifikáciu. Je napísaný od základov a nie je založený na pôvodnom IRCd.
    sv_SE: Ngircd är en gratis, portabel och lätt Internet Relay Chat-server för små eller privata nätverk, utvecklad under GNU General Public License (GPL). Den är enkel att konfigurera, kan hantera dynamiska IP-adresser och stöder IPv6, SSL-skyddade anslutningar samt PAM för autentisering. Den är skriven från grunden och inte baserad på den ursprungliga IRCd.
    tr_TR: Ngircd, GNU Genel Kamu Lisansı (GPL) altında geliştirilen, küçük veya özel ağlar için ücretsiz, taşınabilir ve hafif bir İnternet Röle Sohbeti (IRC) sunucusudur. Yapılandırması kolaydır, dinamik IP adresleriyle başa çıkabilir ve IPv6, SSL korumalı bağlantılar ve kimlik doğrulama için PAM'ı destekler. Sıfırdan yazılmıştır ve orijinal IRCd'ye dayanmaz.
    zh_CN: ngIRCd 是一款免费、可移植、轻量的 IRC 服务器，适用于小型或私有网络，以 GNU 通用公共许可证（GPL）发布。它易于配置，能够处理动态 IP 地址，支持 IPv6、SSL 加密连接和 PAM 身份验证。它从零编写，不基于原始 IRCd。
    zh_TW: ngIRCd 是一款免費、可移植、輕量的 IRC 伺服器，適用於小型或私有網路，以 GNU 通用公共許可證（GPL）釋出。它易於配置，能夠處理動態 IP 地址，支援 IPv6、SSL 加密連線和 PAM 身份驗證。它從零編寫，不基於原始 IRCd。
  tagline:
    en_US: A free, portable and lightweight Internet Relay Chat server for small or private networks, developed under the GNU General Public License (GPL). It is easy to configure, can cope with dynamic IP addresses, and supports IPv6, SSL-protected connections as well as PAM for authentication. It is written from scratch and not based on the original IRCd.
    ca_ES: Un servidor de xat de retransmissió d'Internet gratuït, portàtil i lleuger per a xarxes petites o privades, desenvolupat sota la Llicència Pública General de GNU (GPL). És fàcil de configurar, pot gestionar adreces IP dinàmiques i admet IPv6, connexions protegides per SSL, així com PAM per a l'autenticació. Està escrit des de zero i no es basa en l'IRCd original.
    cs_CZ: Bezplatný, přenosný a lehký server Internet Relay Chat pro malé nebo soukromé sítě, vyvinutý pod licencí GNU General Public License (GPL). Je snadno konfigurovatelný, zvládá dynamické IP adresy a podporuje IPv6, připojení chráněná SSL a také PAM pro ověřování. Je napsán od nuly a není založen na původním IRCd.
    da_DK: En gratis, bærbar og let Internet Relay Chat-server til små eller private netværk, udviklet under GNU General Public License (GPL). Den er nem at konfigurere, kan håndtere dynamiske IP-adresser og understøtter IPv6, SSL-beskyttede forbindelser samt PAM til godkendelse. Den er skrevet fra bunden og er ikke baseret på den originale IRCd.
    de_DE: Ein kostenloser, portabler und ressourcenschonender IRC-Server für kleine oder private Netzwerke, entwickelt unter der GNU General Public License (GPL). Er ist einfach zu konfigurieren, unterstützt dynamische IP-Adressen und IPv6, SSL-geschützte Verbindungen sowie PAM zur Authentifizierung. Er wurde von Grund auf neu entwickelt und basiert nicht auf dem ursprünglichen IRCd.
    el_GR: Ένας δωρεάν, φορητός και ελαφρύς διακομιστής Internet Relay Chat για μικρά ή ιδιωτικά δίκτυα, που αναπτύχθηκε υπό την Γενική Άδεια Δημόσιας Χρήσης GNU (GPL). Είναι εύκολος στη διαμόρφωση, μπορεί να διαχειριστεί δυναμικές διευθύνσεις IP και υποστηρίζει IPv6, συνδέσεις με προστασία SSL, καθώς και PAM για έλεγχο ταυτότητας. Είναι γραμμένος από την αρχή και δεν βασίζεται στο αρχικό IRCd.
    en_GB: A free, portable and lightweight Internet Relay Chat server for small or private networks, developed under the Gnu General Public Licence (Gpl). It is easy to configure, can cope with dynamic Ip addresses, and supports IPv6, Ssl-protected connections as well as Pam for authentication. It is written from scratch and not based on the original Ircd.
    es_ES: Servidor de chat por retransmisión de Internet (IRCd) gratuito, portátil y ligero para redes pequeñas o privadas, desarrollado bajo la Licencia Pública General de GNU (GPL). Es fácil de configurar, admite direcciones IP dinámicas y es compatible con IPv6, conexiones protegidas por SSL y PAM para la autenticación. Ha sido desarrollado desde cero y no se basa en el IRCd original.
    fr_FR: Serveur IRC gratuit, portable et léger, idéal pour les petits réseaux ou les réseaux privés. Développé sous licence GNU GPL, il est facile à configurer, compatible avec les adresses IP dynamiques et prend en charge IPv6, les connexions SSL et l'authentification PAM. Développé de zéro, il n'est pas basé sur IRCd.
    ga_IE: Freastalaí Idirlín Athsheolta Comhrá saor in aisce, iniompartha agus éadrom do líonraí beaga nó príobháideacha, forbartha faoin gCeadúnas Poiblí Ginearálta GNU (GPL). Tá sé éasca a chumrú, is féidir leis déileáil le seoltaí IP dinimiciúla, agus tacaíonn sé le IPv6, naisc atá faoi chosaint SSL chomh maith le PAM le haghaidh fíordheimhnithe. Scríobhadh é ón tús agus níl sé bunaithe ar an IRCd bunaidh.
    hr_HR: Besplatni, prijenosni i lagani Internet Relay Chat poslužitelj za male ili privatne mreže, razvijen pod GNU General Public License (GPL). Jednostavan je za konfiguriranje, može se nositi s dinamičkim IP adresama i podržava IPv6, SSL-zaštićene veze kao i PAM za autentifikaciju. Napisan je od nule i nije temeljen na originalnom IRCd-u.
    hu_HU: Egy ingyenes, hordozható és pehelykönnyű Internet Relay Chat szerver kis vagy privát hálózatok számára, GNU General Public License (GPL) alatt fejlesztve. Könnyen konfigurálható, dinamikus IP-címeket kezel, és támogatja az IPv6-ot, az SSL-védett kapcsolatokat, valamint a PAM hitelesítést. A szerver teljesen új, és nem az eredeti IRCd-n alapul.
    it_IT: Un server IRCd gratuito, portatile e leggero per reti di piccole dimensioni o private, sviluppato sotto licenza GNU General Public License (GPL). È facile da configurare, gestisce indirizzi IP dinamici e supporta IPv6, connessioni protette da SSL e PAM per l'autenticazione. È stato scritto da zero e non si basa sull'IRCd originale.
    ja_JP: GNU一般公衆利用許諾契約書（GPL）に基づいて開発された、小規模ネットワークやプライベートネットワーク向けの、無料かつポータブルで軽量なインターネットリレーチャット（IRC）サーバーです。設定が簡単で、動的IPアドレスに対応し、IPv6、SSL保護接続、認証のためのPAMをサポートしています。オリジナルのIRCdをベースにしたものではなく、ゼロから開発されています。
    ko_KR: 소규모 또는 사설 네트워크를 위한 무료, 휴대용, 경량 인터넷 릴레이 채팅(IRC) 서버로, GNU 일반 공중 라이선스(GPL)에 따라 개발되었습니다. 설정이 간편하고, 동적 IP 주소를 지원하며, IPv6, SSL 보호 연결 및 PAM 인증을 지원합니다. 이 서버는 기존 IRCd를 기반으로 하지 않고 처음부터 새로 작성되었습니다.
    ml_IN: ചെറുതോ സ്വകാര്യമോ ആയ നെറ്റ്‌വർക്കുകൾക്കായി GNU ജനറൽ പബ്ലിക് ലൈസൻസ് (GPL) പ്രകാരം വികസിപ്പിച്ചെടുത്ത സൗജന്യവും പോർട്ടബിളും ഭാരം കുറഞ്ഞതുമായ ഇന്റർനെറ്റ് റിലേ ചാറ്റ് സെർവർ. ഇത് കോൺഫിഗർ ചെയ്യാൻ എളുപ്പമാണ്, ഡൈനാമിക് IP വിലാസങ്ങളെ നേരിടാൻ കഴിയും, കൂടാതെ IPv6, SSL- പരിരക്ഷിത കണക്ഷനുകളെയും പ്രാമാണീകരണത്തിനായി PAM-നെയും പിന്തുണയ്ക്കുന്നു. ഇത് ആദ്യം മുതൽ എഴുതിയതാണ്, യഥാർത്ഥ IRCd അടിസ്ഥാനമാക്കിയുള്ളതല്ല.
    nb_NO: En gratis, bærbar og lett Internet Relay Chat-server for små eller private nettverk, utviklet under GNU General Public License (GPL). Den er enkel å konfigurere, kan håndtere dynamiske IP-adresser og støtter IPv6, SSL-beskyttede tilkoblinger samt PAM for autentisering. Den er skrevet fra bunnen av og er ikke basert på den originale IRCd-en.
    nl_NL: Een gratis, draagbare en lichtgewicht Internet Relay Chat-server voor kleine of privénetwerken, ontwikkeld onder de GNU General Public License (GPL). De server is eenvoudig te configureren, kan overweg met dynamische IP-adressen en ondersteunt IPv6, SSL-beveiligde verbindingen en PAM voor authenticatie. De server is volledig opnieuw geschreven en niet gebaseerd op het originele IRCd.
    pl_PL: Darmowy, przenośny i lekki serwer Internet Relay Chat dla małych lub prywatnych sieci, opracowany na licencji GNU General Public License (GPL). Jest łatwy w konfiguracji, obsługuje dynamiczne adresy IP i obsługuje połączenia IPv6, połączenia zabezpieczone protokołem SSL oraz uwierzytelnianie PAM. Został napisany od podstaw i nie jest oparty na oryginalnym IRCd.
    pt_BR: Um servidor IRC gratuito, portátil e leve para redes pequenas ou privadas, desenvolvido sob a Licença Pública Geral GNU (GPL). É fácil de configurar, suporta endereços IP dinâmicos e IPv6, conexões protegidas por SSL e PAM para autenticação. Foi escrito do zero e não é baseado no IRCd original.
    ro_RO: Un server de chat prin internet gratuit, portabil și ușor pentru rețele mici sau private, dezvoltat sub licența GNU General Public License (GPL). Este ușor de configurat, poate gestiona adrese IP dinamice și acceptă IPv6, conexiuni protejate prin SSL, precum și PAM pentru autentificare. Este scris de la zero și nu se bazează pe IRCd-ul original.
    ru_RU: Бесплатный, портативный и легковесный сервер интернет-чата Internet Relay Chat для небольших или частных сетей, разработанный под лицензией GNU General Public License (GPL). Он прост в настройке, может работать с динамическими IP-адресами и поддерживает IPv6, SSL-защищенные соединения, а также PAM для аутентификации. Он написан с нуля и не основан на оригинальном IRCd.
    sk_SK: Bezplatný, prenosný a ľahký server Internet Relay Chat pre malé alebo súkromné siete, vyvinutý pod licenciou GNU General Public License (GPL). Je ľahko konfigurovateľný, dokáže pracovať s dynamickými IP adresami a podporuje IPv6, pripojenia chránené SSL, ako aj PAM na autentifikáciu. Je napísaný od základov a nie je založený na pôvodnom IRCd.
    sv_SE: En gratis, portabel och lätt Internet Relay Chat-server för små eller privata nätverk, utvecklad under GNU General Public License (GPL). Den är enkel att konfigurera, kan hantera dynamiska IP-adresser och stöder IPv6, SSL-skyddade anslutningar samt PAM för autentisering. Den är skriven från grunden och inte baserad på den ursprungliga IRCd.
    tr_TR: GNU Genel Kamu Lisansı (GPL) altında geliştirilen, küçük veya özel ağlar için ücretsiz, taşınabilir ve hafif bir İnternet Röle Sohbeti (IRC) sunucusudur. Yapılandırması kolaydır, dinamik IP adresleriyle başa çıkabilir ve IPv6, SSL korumalı bağlantılar ve kimlik doğrulama için PAM'ı destekler. Sıfırdan yazılmıştır ve orijinal IRCd'ye dayanmaz.
    zh_CN: 适用于小型或私有网络的轻量 IRC 服务器。
    zh_TW: 適用於小型或私有網路的輕量 IRC 伺服器。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ngircd-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ngircd-logo.png
  title:
    en_US: Ngircd (LinuxServer.io)
    ca_ES: Ngircd (LinuxServer.io)
    cs_CZ: Ngircd (LinuxServer.io)
    da_DK: Ngircd (LinuxServer.io)
    de_DE: Ngircd (LinuxServer.io)
    el_GR: Ngircd (LinuxServer.io)
    en_GB: Ngircd (LinuxServer.io)
    es_ES: Ngircd (LinuxServer.io)
    fr_FR: Ngircd (LinuxServer.io)
    ga_IE: Ngircd (LinuxServer.io)
    hr_HR: Ngircd (LinuxServer.io)
    hu_HU: Ngircd (LinuxServer.io)
    it_IT: Ngircd (LinuxServer.io)
    ja_JP: Ngircd (LinuxServer.io)
    ko_KR: Ngircd (LinuxServer.io)
    ml_IN: Ngircd (LinuxServer.io)
    nb_NO: Ngircd (LinuxServer.io)
    nl_NL: Ngircd (LinuxServer.io)
    pl_PL: Ngircd (LinuxServer.io)
    pt_BR: Ngircd (LinuxServer.io)
    ro_RO: Ngircd (LinuxServer.io)
    ru_RU: Ngircd (LinuxServer.io)
    sk_SK: Ngircd (LinuxServer.io)
    sv_SE: Ngircd (LinuxServer.io)
    tr_TR: Ngircd (LinuxServer.io)
    zh_CN: Ngircd（LinuxServer.io）
    zh_TW: Ngircd（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverngircd
  port_map: '6667'
  version: version-27-r1
