name: linuxserver-orcaslicer
services:
  app:
    image: linuxserver/orcaslicer:2.4.2@sha256:de24dc784bfbb2b0fca3976043c3d831a23697083d74333fd5c3f66e627686da
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/orcaslicer/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverorcaslicer/assets/icon.png
  title:
    en_US: Orcaslicer (LinuxServer.io)
    ca_ES: Orcaslicer (LinuxServer.io)
    cs_CZ: Orcaslicer (LinuxServer.io)
    da_DK: Orcaslicer (LinuxServer.io)
    de_DE: Orcaslicer (LinuxServer.io)
    el_GR: Orcaslicer (LinuxServer.io)
    en_GB: Orcaslicer (LinuxServer.io)
    es_ES: Orcaslicer (LinuxServer.io)
    fr_FR: Orcaslicer (LinuxServer.io)
    ga_IE: Orcaslicer (LinuxServer.io)
    hr_HR: Orcaslicer (LinuxServer.io)
    hu_HU: Orcaslicer (LinuxServer.io)
    it_IT: Orcaslicer (LinuxServer.io)
    ja_JP: Orcaslicer (LinuxServer.io)
    ko_KR: Orcaslicer (LinuxServer.io)
    ml_IN: Orcaslicer (LinuxServer.io)
    nb_NO: Orcaslicer (LinuxServer.io)
    nl_NL: Orcaslicer (LinuxServer.io)
    pl_PL: Orcaslicer (LinuxServer.io)
    pt_BR: Orcaslicer (LinuxServer.io)
    ro_RO: Orcaslicer (LinuxServer.io)
    ru_RU: Orcaslicer (LinuxServer.io)
    sk_SK: Orcaslicer (LinuxServer.io)
    sv_SE: Orcaslicer (LinuxServer.io)
    tr_TR: Orcaslicer (LinuxServer.io)
    zh_CN: Orcaslicer（LinuxServer.io）
    zh_TW: Orcaslicer（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverorcaslicer
  port_map: '3000'
  version: 2.4.2
