name: linuxserver-pyload-ng
services:
  app:
    image: linuxserver/pyload-ng:0.5.0@sha256:5d1e31737794449fd2012b47bba477805dc8e59194b2b95d3a104e849fb29c42
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 9666
        published: 9666
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pyload-ng/config
        target: /config
      - type: bind
        source: /DATA/AppData/pyload-ng/downloads
        target: /downloads
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverpyloadng/assets/icon.png
  title:
    en_US: Pyload ng (LinuxServer.io)
    ca_ES: Pyload ng (LinuxServer.io)
    cs_CZ: Pyload ng (LinuxServer.io)
    da_DK: Pyload ng (LinuxServer.io)
    de_DE: Pyload ng (LinuxServer.io)
    el_GR: Pyload ng (LinuxServer.io)
    en_GB: Pyload ng (LinuxServer.io)
    es_ES: Pyload ng (LinuxServer.io)
    fr_FR: Pyload ng (LinuxServer.io)
    ga_IE: Pyload ng (LinuxServer.io)
    hr_HR: Pyload ng (LinuxServer.io)
    hu_HU: Pyload ng (LinuxServer.io)
    it_IT: Pyload ng (LinuxServer.io)
    ja_JP: Pyload ng (LinuxServer.io)
    ko_KR: Pyload ng (LinuxServer.io)
    ml_IN: Pyload ng (LinuxServer.io)
    nb_NO: Pyload ng (LinuxServer.io)
    nl_NL: Pyload ng (LinuxServer.io)
    pl_PL: Pyload ng (LinuxServer.io)
    pt_BR: Pyload ng (LinuxServer.io)
    ro_RO: Pyload ng (LinuxServer.io)
    ru_RU: Pyload ng (LinuxServer.io)
    sk_SK: Pyload ng (LinuxServer.io)
    sv_SE: Pyload ng (LinuxServer.io)
    tr_TR: Pyload ng (LinuxServer.io)
    zh_CN: Pyload ng（LinuxServer.io）
    zh_TW: Pyload ng（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverpyloadng
  port_map: '8000'
  version: 0.5.0
