name: linuxserver-signal
services:
  app:
    image: linuxserver/signal:8.27.0@sha256:5c4b0d98b7463f75fe5a0e4e7d46931074cb26f0b4476e79ce532e4e186b4592
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/signal/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserversignal/assets/icon.png
  title:
    en_US: Signal (LinuxServer.io)
    ca_ES: Signal (LinuxServer.io)
    cs_CZ: Signal (LinuxServer.io)
    da_DK: Signal (LinuxServer.io)
    de_DE: Signal (LinuxServer.io)
    el_GR: Signal (LinuxServer.io)
    en_GB: Signal (LinuxServer.io)
    es_ES: Signal (LinuxServer.io)
    fr_FR: Signal (LinuxServer.io)
    ga_IE: Signal (LinuxServer.io)
    hr_HR: Signal (LinuxServer.io)
    hu_HU: Signal (LinuxServer.io)
    it_IT: Signal (LinuxServer.io)
    ja_JP: Signal (LinuxServer.io)
    ko_KR: Signal (LinuxServer.io)
    ml_IN: Signal (LinuxServer.io)
    nb_NO: Signal (LinuxServer.io)
    nl_NL: Signal (LinuxServer.io)
    pl_PL: Signal (LinuxServer.io)
    pt_BR: Signal (LinuxServer.io)
    ro_RO: Signal (LinuxServer.io)
    ru_RU: Signal (LinuxServer.io)
    sk_SK: Signal (LinuxServer.io)
    sv_SE: Signal (LinuxServer.io)
    tr_TR: Signal (LinuxServer.io)
    zh_CN: Signal（LinuxServer.io）
    zh_TW: Signal（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserversignal
  port_map: '3000'
  version: 8.27.0
