name: linuxserver-thunderbird
services:
  app:
    image: linuxserver/thunderbird:1140.16.0@sha256:947182067eb86bd2d99ac2e475183f239cbe7156e2c2ee76a1e5c7c86187a1f6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/thunderbird/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverthunderbird/assets/icon.png
  title:
    en_US: Thunderbird (LinuxServer.io)
    ca_ES: Thunderbird (LinuxServer.io)
    cs_CZ: Thunderbird (LinuxServer.io)
    da_DK: Thunderbird (LinuxServer.io)
    de_DE: Thunderbird (LinuxServer.io)
    el_GR: Thunderbird (LinuxServer.io)
    en_GB: Thunderbird (LinuxServer.io)
    es_ES: Thunderbird (LinuxServer.io)
    fr_FR: Thunderbird (LinuxServer.io)
    ga_IE: Thunderbird (LinuxServer.io)
    hr_HR: Thunderbird (LinuxServer.io)
    hu_HU: Thunderbird (LinuxServer.io)
    it_IT: Thunderbird (LinuxServer.io)
    ja_JP: Thunderbird (LinuxServer.io)
    ko_KR: Thunderbird (LinuxServer.io)
    ml_IN: Thunderbird (LinuxServer.io)
    nb_NO: Thunderbird (LinuxServer.io)
    nl_NL: Thunderbird (LinuxServer.io)
    pl_PL: Thunderbird (LinuxServer.io)
    pt_BR: Thunderbird (LinuxServer.io)
    ro_RO: Thunderbird (LinuxServer.io)
    ru_RU: Thunderbird (LinuxServer.io)
    sk_SK: Thunderbird (LinuxServer.io)
    sv_SE: Thunderbird (LinuxServer.io)
    tr_TR: Thunderbird (LinuxServer.io)
    zh_CN: Thunderbird（LinuxServer.io）
    zh_TW: Thunderbird（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverthunderbird
  port_map: '3000'
  version: 1140.16.0
