name: linuxserver-faster-whisper
services:
  app:
    image: linuxserver/faster-whisper:3.8.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DEBUG: ''
      LOCAL_ONLY: ''
      WHISPER_BEAM: ''
      WHISPER_LANG: ''
      WHISPER_MODEL: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: DEBUG
          description:
            en_US: If set to true, or any other value, the container will output debug logs. [OPTIONAL]
        - container: LOCAL_ONLY
          description:
            en_US: If set to true, or any other value, the container will not attempt to download models from HuggingFace and will only use locally-provided models. [OPTIONAL]
        - container: WHISPER_BEAM
          description:
            en_US: Number of candidates to consider simultaneously during transcription. [OPTIONAL]
        - container: WHISPER_LANG
          description:
            en_US: Two character code for the language that you will speak to the add-on. [OPTIONAL]
        - container: WHISPER_MODEL
          description:
            en_US: Whisper model that will be used for transcription. From here. [OPTIONAL]
    ports:
      - target: 10300
        published: 10300
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/faster-whisper/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Faster-whisper is a reimplementation of OpenAI's Whisper model using CTranslate2, which is a fast inference engine for Transformer models. This container provides a Wyoming protocol server for faster-whisper.
    zh_CN: Faster-whisper 使用 CTranslate2 重新实现 OpenAI 的 Whisper 模型；CTranslate2 是面向 Transformer 模型的快速推理引擎。此容器为 faster-whisper 提供 Wyoming 协议服务器。
  tagline:
    en_US: A reimplementation of OpenAI's Whisper model using CTranslate2, which is a fast inference engine for Transformer models. This container provides a Wyoming protocol server for faster-whisper.
    zh_CN: 通过 Wyoming 协议提供 Whisper 语音识别服务。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/WisdomSky/CasaOS-LinuxServer-AppStore/main/default-icon.svg
  thumbnail: ''
  title:
    en_US: Faster whisper (LinuxServer.io)
    zh_CN: Faster whisper（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverfasterwhisper
  port_map: '10300'
  version: 3.8.1
