name: linuxserver-wireshark
services:
  app:
    image: linuxserver/wireshark:4.6.6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/wireshark/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Wireshark is the world’s foremost and widely-used network protocol analyzer. It lets you see what’s happening on your network at a microscopic level and is the de facto (and often de jure) standard across many commercial and non-profit enterprises, government agencies, and educational institutions. Wireshark development thrives thanks to the volunteer contributions of networking experts around the globe and is the continuation of a project started by Gerald Combs in 1998.
    ca_ES: Wireshark és l'analitzador de protocols de xarxa més important i utilitzat del món. Us permet veure què passa a la vostra xarxa a nivell microscòpic i és l'estàndard de facto (i sovint de jure) en moltes empreses comercials i sense ànim de lucre, agències governamentals i institucions educatives. El desenvolupament de Wireshark prospera gràcies a les contribucions voluntàries d'experts en xarxes d'arreu del món i és la continuació d'un projecte iniciat per Gerald Combs el 1998.
    cs_CZ: Wireshark je přední a nejpoužívanější analyzátor síťových protokolů na světě. Umožňuje vám sledovat, co se děje ve vaší síti na mikroskopické úrovni, a je de facto (a často i de jure) standardem v mnoha komerčních a neziskových podnicích, vládních agenturách a vzdělávacích institucích. Vývoj Wiresharku vzkvétá díky dobrovolným příspěvkům síťových expertů z celého světa a je pokračováním projektu, který v roce 1998 zahájil Gerald Combs.
    da_DK: Wireshark er verdens førende og mest anvendte netværksprotokolanalysator. Den lader dig se, hvad der sker på dit netværk på et mikroskopisk niveau, og er de facto (og ofte de jure) standarden på tværs af mange kommercielle og nonprofitvirksomheder, offentlige myndigheder og uddannelsesinstitutioner. Wireshark-udviklingen trives takket være frivillige bidrag fra netværkseksperter over hele verden og er fortsættelsen af et projekt, der blev startet af Gerald Combs i 1998.
    de_DE: Wireshark ist der weltweit führende und am weitesten verbreitete Netzwerkprotokollanalysator. Er ermöglicht es, die Vorgänge in Ihrem Netzwerk bis ins kleinste Detail zu beobachten und gilt als De-facto-Standard (und oft auch als De-jure-Standard) in vielen kommerziellen und gemeinnützigen Unternehmen, Regierungsbehörden und Bildungseinrichtungen. Die Entwicklung von Wireshark wird durch die ehrenamtlichen Beiträge von Netzwerkexperten weltweit vorangetrieben und ist die Fortführung eines Projekts, das Gerald Combs 1998 ins Leben rief.
    el_GR: Το Wireshark είναι ο κορυφαίος και ευρέως χρησιμοποιούμενος αναλυτής πρωτοκόλλου δικτύου στον κόσμο. Σας επιτρέπει να βλέπετε τι συμβαίνει στο δίκτυό σας σε μικροσκοπικό επίπεδο και αποτελεί το de facto (και συχνά de jure) πρότυπο σε πολλές εμπορικές και μη κερδοσκοπικές επιχειρήσεις, κυβερνητικές υπηρεσίες και εκπαιδευτικά ιδρύματα. Η ανάπτυξη του Wireshark ευδοκιμεί χάρη στις εθελοντικές συνεισφορές ειδικών δικτύωσης σε όλο τον κόσμο και αποτελεί τη συνέχεια ενός έργου που ξεκίνησε ο Gerald Combs το 1998.
    en_GB: Wireshark is the world’s foremost and widely-used network protocol analyser. It lets you see what’s happening on your network at a microscopic level and is the de facto (and often de jure) standard across many commercial and non-profit enterprises, government agencies, and educational institutions. Wireshark development thrives thanks to the volunteer contributions of networking experts around the globe and is the continuation of a project started by Gerald Combs in 1998.
    es_ES: Wireshark es el analizador de protocolos de red más importante y utilizado del mundo. Permite visualizar el funcionamiento de la red a nivel microscópico y es el estándar de facto (y a menudo de jure) en numerosas empresas comerciales y sin ánimo de lucro, agencias gubernamentales e instituciones educativas. El desarrollo de Wireshark prospera gracias a las contribuciones voluntarias de expertos en redes de todo el mundo y es la continuación de un proyecto iniciado por Gerald Combs en 1998.
    fr_FR: Wireshark est l'analyseur de protocoles réseau le plus utilisé au monde. Il permet d'observer l'activité de votre réseau avec une précision extrême et constitue la norme de facto (et souvent de jure) pour de nombreuses entreprises commerciales et à but non lucratif, agences gouvernementales et établissements d'enseignement. Le développement de Wireshark repose sur la contribution bénévole d'experts en réseaux du monde entier et s'inscrit dans la continuité d'un projet initié par Gerald Combs en 1998.
    ga_IE: Is é Wireshark an anailíseoir prótacail líonra is mó le rá agus is mó a úsáidtear ar domhan. Ligeann sé duit a fheiceáil cad atá ag tarlú ar do líonra ag leibhéal micreascópach agus is é an caighdeán de facto (agus go minic de jure) i go leor fiontar tráchtála agus neamhbhrabúis, gníomhaireachtaí rialtais, agus institiúidí oideachais. Tá forbairt Wireshark ag fás go maith a bhuíochas le ranníocaíochtaí deonacha ó shaineolaithe líonraithe ar fud an domhain agus is leanúint é ar thionscadal a thosaigh Gerald Combs i 1998.
    hr_HR: Wireshark je vodeći i široko korišteni analizator mrežnih protokola na svijetu. Omogućuje vam da vidite što se događa na vašoj mreži na mikroskopskoj razini i de facto (a često i de jure) standard u mnogim komercijalnim i neprofitnim poduzećima, vladinim agencijama i obrazovnim ustanovama. Razvoj Wiresharka napreduje zahvaljujući volonterskim doprinosima stručnjaka za umrežavanje diljem svijeta i nastavak je projekta koji je Gerald Combs započeo 1998. godine.
    hu_HU: A Wireshark a világ legelterjedtebb és legszélesebb körben használt hálózati protokoll elemzője. Lehetővé teszi, hogy mikroszkopikus szinten lásd, mi történik a hálózatodon, és számos kereskedelmi és non-profit vállalat, kormányzati szerv és oktatási intézmény tényleges (és gyakran de jure) szabványa. A Wireshark fejlesztése a világ minden tájáról érkező hálózati szakértők önkéntes hozzájárulásainak köszönhetően virágzik, és Gerald Combs által 1998-ban indított projekt folytatása.
    it_IT: Wireshark è il software di analisi dei protocolli di rete più importante e diffuso al mondo. Permette di visualizzare in dettaglio ciò che accade sulla rete ed è lo standard di fatto (e spesso anche di diritto) in molte aziende, organizzazioni non profit, enti governativi e istituti scolastici. Lo sviluppo di Wireshark prospera grazie al contributo volontario di esperti di rete di tutto il mondo ed è la continuazione di un progetto avviato da Gerald Combs nel 1998.
    ja_JP: Wiresharkは、世界で最も有名で広く利用されているネットワークプロトコルアナライザーです。ネットワーク上で何が起こっているかをミクロレベルで把握でき、多くの営利企業、非営利団体、政府機関、教育機関において事実上の（そして多くの場合、法的な）標準となっています。Wiresharkの開発は、世界中のネットワーク専門家によるボランティアの貢献によって支えられており、1998年にジェラルド・コムズ氏が開始したプロジェクトの継続です。
    ko_KR: Wireshark는 세계에서 가장 널리 사용되는 네트워크 프로토콜 분석 도구입니다. 네트워크에서 일어나는 일을 미시적인 수준에서 확인할 수 있게 해주며, 수많은 상업 및 비영리 기업, 정부 기관, 교육 기관에서 사실상(그리고 종종 법적으로도) 표준으로 자리 잡고 있습니다. Wireshark는 전 세계 네트워크 전문가들의 자발적인 기여 덕분에 꾸준히 개발되고 있으며, 1998년 Gerald Combs가 시작한 프로젝트의 연장선상에 있습니다.
    ml_IN: ലോകത്തിലെ ഏറ്റവും മുൻനിരയിലുള്ളതും വ്യാപകമായി ഉപയോഗിക്കുന്നതുമായ നെറ്റ്‌വർക്ക് പ്രോട്ടോക്കോൾ അനലൈസറാണ് വയർഷാർക്ക്. നിങ്ങളുടെ നെറ്റ്‌വർക്കിൽ എന്താണ് സംഭവിക്കുന്നതെന്ന് സൂക്ഷ്മതലത്തിൽ കാണാൻ ഇത് നിങ്ങളെ അനുവദിക്കുന്നു, കൂടാതെ നിരവധി വാണിജ്യ, ലാഭേച്ഛയില്ലാത്ത സംരംഭങ്ങൾ, സർക്കാർ ഏജൻസികൾ, വിദ്യാഭ്യാസ സ്ഥാപനങ്ങൾ എന്നിവയിലുടനീളം ഇത് യഥാർത്ഥ (പലപ്പോഴും നിയമപരമായ) മാനദണ്ഡമാണ്. ലോകമെമ്പാടുമുള്ള നെറ്റ്‌വർക്കിംഗ് വിദഗ്ധരുടെ സന്നദ്ധസേവന സംഭാവനകൾക്ക് നന്ദി പറഞ്ഞുകൊണ്ട് വയർഷാർക്ക് വികസനം അഭിവൃദ്ധി പ്രാപിക്കുന്നു, 1998 ൽ ജെറാൾഡ് കോംബ്സ് ആരംഭിച്ച ഒരു പദ്ധതിയുടെ തുടർച്ചയാണിത്.
    nb_NO: Wireshark er verdens fremste og mest brukte nettverksprotokollanalysator. Den lar deg se hva som skjer på nettverket ditt på et mikroskopisk nivå, og er de facto (og ofte de jure) standarden på tvers av mange kommersielle og ideelle bedrifter, offentlige etater og utdanningsinstitusjoner. Wireshark-utviklingen blomstrer takket være frivillige bidrag fra nettverkseksperter over hele verden, og er en fortsettelse av et prosjekt startet av Gerald Combs i 1998.
    nl_NL: Wireshark is 's werelds meest vooraanstaande en meest gebruikte netwerkprotocolanalysator. Het laat je zien wat er op je netwerk gebeurt op microscopisch niveau en is de de facto (en vaak de de jure) standaard voor veel commerciële en non-profitorganisaties, overheidsinstanties en onderwijsinstellingen. De ontwikkeling van Wireshark floreert dankzij de vrijwillige bijdragen van netwerkexperts over de hele wereld en is een voortzetting van een project dat in 1998 door Gerald Combs werd gestart.
    pl_PL: Wireshark to czołowy i powszechnie używany na świecie analizator protokołów sieciowych. Pozwala on zobaczyć, co dzieje się w sieci na poziomie mikroskopowym i jest de facto (a często de jure) standardem w wielu przedsiębiorstwach komercyjnych i non-profit, agencjach rządowych i instytucjach edukacyjnych. Rozwój Wiresharka rozwija się dzięki wolontariatowi ekspertów sieciowych z całego świata i jest kontynuacją projektu rozpoczętego przez Geralda Combsa w 1998 roku.
    pt_BR: O Wireshark é o analisador de protocolos de rede mais importante e amplamente utilizado no mundo. Ele permite visualizar o que está acontecendo em sua rede em um nível microscópico e é o padrão de fato (e muitas vezes de direito) em diversas empresas comerciais e sem fins lucrativos, agências governamentais e instituições de ensino. O desenvolvimento do Wireshark prospera graças às contribuições voluntárias de especialistas em redes do mundo todo e é a continuação de um projeto iniciado por Gerald Combs em 1998.
    ro_RO: Wireshark este cel mai important și utilizat analizor de protocoale de rețea din lume. Acesta vă permite să vedeți ce se întâmplă în rețeaua dvs. la nivel microscopic și este standardul de facto (și adesea de jure) în multe întreprinderi comerciale și non-profit, agenții guvernamentale și instituții de învățământ. Dezvoltarea Wireshark prosperă datorită contribuțiilor voluntare ale experților în rețele din întreaga lume și este continuarea unui proiect început de Gerald Combs în 1998.
    ru_RU: Wireshark — это ведущий и широко используемый в мире анализатор сетевых протоколов. Он позволяет увидеть, что происходит в вашей сети на микроскопическом уровне, и является де-факто (а часто и де-юре) стандартом во многих коммерческих и некоммерческих предприятиях, государственных учреждениях и образовательных организациях. Разработка Wireshark процветает благодаря добровольному вкладу экспертов по сетям со всего мира и является продолжением проекта, начатого Джеральдом Комбсом в 1998 году.
    sk_SK: Wireshark je popredný a najpoužívanejší analyzátor sieťových protokolov na svete. Umožňuje vám vidieť, čo sa deje vo vašej sieti na mikroskopickej úrovni, a je de facto (a často de jure) štandardom v mnohých komerčných a neziskových podnikoch, vládnych agentúrach a vzdelávacích inštitúciách. Vývoj Wiresharku prosperuje vďaka dobrovoľníckym príspevkom sieťových expertov z celého sveta a je pokračovaním projektu, ktorý začal Gerald Combs v roku 1998.
    sv_SE: Wireshark är världens främsta och mest använda nätverksprotokollanalysator. Den låter dig se vad som händer i ditt nätverk på mikroskopisk nivå och är de facto (och ofta de jure) standarden i många kommersiella och ideella företag, myndigheter och utbildningsinstitutioner. Wiresharks utveckling blomstrar tack vare frivilliga bidrag från nätverksexperter runt om i världen och är en fortsättning på ett projekt som startades av Gerald Combs 1998.
    tr_TR: Wireshark, dünyanın önde gelen ve yaygın olarak kullanılan ağ protokolü analiz aracıdır. Ağınızda neler olup bittiğini mikroskobik düzeyde görmenizi sağlar ve birçok ticari ve kar amacı gütmeyen kuruluş, devlet kurumu ve eğitim kurumu tarafından fiili (ve genellikle yasal) standart olarak kabul edilir. Wireshark'ın geliştirilmesi, dünyanın dört bir yanındaki ağ uzmanlarının gönüllü katkıları sayesinde gelişmektedir ve Gerald Combs tarafından 1998'de başlatılan bir projenin devamıdır.
    zh_CN: Wireshark 是广泛使用的领先网络协议分析器，可帮助你细致观察网络中发生的情况。它是众多商业与非营利组织、政府机构和教育机构采用的事实标准，有时也是正式标准。其发展得益于全球网络专家的志愿贡献，并延续了 Gerald Combs 于 1998 年启动的项目。
    zh_TW: Wireshark 是廣泛使用的領先網路協議分析器，可幫助你細緻觀察網路中發生的情況。它是眾多商業與非營利組織、政府機構和教育機構採用的事實標準，有時也是正式標準。其發展得益於全球網路專家的志願貢獻，並延續了 Gerald Combs 於 1998 年啟動的專案。
  tagline:
    en_US: The world’s foremost and widely-used network protocol analyzer. It lets you see what’s happening on your network at a microscopic level and is the de facto (and often de jure) standard across many commercial and non-profit enterprises, government agencies, and educational institutions. Wireshark development thrives thanks to the volunteer contributions of networking experts around the globe and is the continuation of a project started by Gerald Combs in 1998.
    ca_ES: L'analitzador de protocols de xarxa més important i utilitzat del món. Us permet veure què passa a la vostra xarxa a nivell microscòpic i és l'estàndard de facto (i sovint de jure) en moltes empreses comercials i sense ànim de lucre, agències governamentals i institucions educatives. El desenvolupament de Wireshark prospera gràcies a les contribucions voluntàries d'experts en xarxes d'arreu del món i és la continuació d'un projecte iniciat per Gerald Combs el 1998.
    cs_CZ: Nejvýznamnější a nejpoužívanější analyzátor síťových protokolů na světě. Umožňuje vám sledovat, co se děje ve vaší síti na mikroskopické úrovni, a je de facto (a často i de jure) standardem v mnoha komerčních a neziskových podnicích, vládních agenturách a vzdělávacích institucích. Vývoj Wiresharku vzkvétá díky dobrovolnickým příspěvkům síťových expertů z celého světa a je pokračováním projektu, který v roce 1998 zahájil Gerald Combs.
    da_DK: Verdens førende og mest anvendte netværksprotokolanalysator. Den lader dig se, hvad der sker på dit netværk på et mikroskopisk niveau, og er de facto (og ofte de jure) standarden på tværs af mange kommercielle og nonprofitvirksomheder, offentlige myndigheder og uddannelsesinstitutioner. Wireshark-udviklingen trives takket være frivillige bidrag fra netværkseksperter over hele verden og er fortsættelsen af et projekt, der blev startet af Gerald Combs i 1998.
    de_DE: Wireshark ist der weltweit führende und am weitesten verbreitete Netzwerkprotokollanalysator. Er ermöglicht es Ihnen, die Vorgänge in Ihrem Netzwerk bis ins kleinste Detail zu beobachten und gilt als De-facto-Standard (und oft auch als De-jure-Standard) in zahlreichen Unternehmen, gemeinnützigen Organisationen, Behörden und Bildungseinrichtungen. Die Entwicklung von Wireshark verdankt sich dem ehrenamtlichen Engagement von Netzwerkexperten weltweit und ist die Fortführung eines Projekts, das Gerald Combs 1998 ins Leben rief.
    el_GR: Ο κορυφαίος και ευρέως χρησιμοποιούμενος αναλυτής πρωτοκόλλου δικτύου στον κόσμο. Σας επιτρέπει να βλέπετε τι συμβαίνει στο δίκτυό σας σε μικροσκοπικό επίπεδο και αποτελεί το de facto (και συχνά de jure) πρότυπο σε πολλές εμπορικές και μη κερδοσκοπικές επιχειρήσεις, κυβερνητικές υπηρεσίες και εκπαιδευτικά ιδρύματα. Η ανάπτυξη του Wireshark ευδοκιμεί χάρη στις εθελοντικές συνεισφορές ειδικών δικτύωσης σε όλο τον κόσμο και αποτελεί τη συνέχεια ενός έργου που ξεκίνησε ο Gerald Combs το 1998.
    en_GB: The world’s foremost and widely-used network protocol analyser. It lets you see what’s happening on your network at a microscopic level and is the de facto (and often de jure) standard across many commercial and non-profit enterprises, government agencies, and educational institutions. Wireshark development thrives thanks to the volunteer contributions of networking experts around the globe and is the continuation of a project started by Gerald Combs in 1998.
    es_ES: Wireshark es el analizador de protocolos de red más importante y utilizado del mundo. Permite visualizar el funcionamiento de la red a nivel microscópico y es el estándar de facto (y a menudo de jure) en numerosas empresas comerciales y sin ánimo de lucro, agencias gubernamentales e instituciones educativas. Su desarrollo se nutre de las contribuciones voluntarias de expertos en redes de todo el mundo y es la continuación de un proyecto iniciado por Gerald Combs en 1998.
    fr_FR: Wireshark est l'analyseur de protocoles réseau le plus utilisé au monde. Il permet d'observer l'activité de votre réseau avec une précision extrême et constitue la norme de facto (et souvent de jure) pour de nombreuses entreprises commerciales et à but non lucratif, agences gouvernementales et établissements d'enseignement. Son développement repose sur la contribution bénévole d'experts en réseaux du monde entier et s'inscrit dans la continuité d'un projet initié par Gerald Combs en 1998.
    ga_IE: An anailíseoir prótacail líonra is mó le rá agus is mó a úsáidtear ar domhan. Ligeann sé duit a fheiceáil cad atá ag tarlú ar do líonra ag leibhéal micreascópach agus is é an caighdeán de facto (agus go minic de jure) i go leor fiontar tráchtála agus neamhbhrabúis, gníomhaireachtaí rialtais, agus institiúidí oideachais. Tá forbairt Wireshark ag fás go maith a bhuíochas le ranníocaíochtaí deonacha ó shaineolaithe líonraithe ar fud an domhain agus is leanúint é ar thionscadal a thosaigh Gerald Combs i 1998.
    hr_HR: Vodeći i široko korišteni analizator mrežnih protokola na svijetu. Omogućuje vam da vidite što se događa na vašoj mreži na mikroskopskoj razini i de facto (a često i de jure) je standard u mnogim komercijalnim i neprofitnim poduzećima, vladinim agencijama i obrazovnim ustanovama. Razvoj Wiresharka napreduje zahvaljujući volonterskim doprinosima stručnjaka za umrežavanje diljem svijeta i nastavak je projekta koji je Gerald Combs započeo 1998. godine.
    hu_HU: A világ legelső és legszélesebb körben használt hálózati protokoll elemzője. Lehetővé teszi, hogy mikroszkopikus szinten lásd, mi történik a hálózatodon, és számos kereskedelmi és non-profit vállalat, kormányzati szerv és oktatási intézmény tényleges (és gyakran de jure) szabványa. A Wireshark fejlesztése a világ minden tájáról érkező hálózati szakértők önkéntes hozzájárulásainak köszönhetően virágzik, és Gerald Combs által 1998-ban indított projekt folytatása.
    it_IT: Il software di analisi dei protocolli di rete più importante e diffuso al mondo. Consente di visualizzare in dettaglio ciò che accade sulla rete ed è lo standard di fatto (e spesso anche di diritto) in molte aziende, organizzazioni non profit, enti governativi e istituti scolastici. Lo sviluppo di Wireshark prospera grazie al contributo volontario di esperti di rete di tutto il mondo ed è la continuazione di un progetto avviato da Gerald Combs nel 1998.
    ja_JP: 世界で最も広く利用されているネットワークプロトコルアナライザーです。ネットワーク上で何が起こっているかをミクロレベルで把握でき、多くの営利企業、非営利団体、政府機関、教育機関において事実上の（そして多くの場合、法的な）標準となっています。Wiresharkの開発は、世界中のネットワーク専門家によるボランティアの貢献によって支えられており、1998年にジェラルド・コムズ氏が開始したプロジェクトの継続です。
    ko_KR: 세계에서 가장 널리 사용되는 네트워크 프로토콜 분석 도구입니다. 네트워크에서 일어나는 일을 미시적인 수준에서 확인할 수 있게 해주며, 수많은 상업 및 비영리 기업, 정부 기관, 교육 기관에서 사실상(그리고 종종 법적으로도) 표준으로 자리 잡고 있습니다. Wireshark는 전 세계 네트워크 전문가들의 자발적인 기여 덕분에 꾸준히 개발되고 있으며, 1998년 Gerald Combs가 시작한 프로젝트를 계승하고 있습니다.
    ml_IN: ലോകത്തിലെ ഏറ്റവും മുൻനിരയിലുള്ളതും വ്യാപകമായി ഉപയോഗിക്കുന്നതുമായ നെറ്റ്‌വർക്ക് പ്രോട്ടോക്കോൾ അനലൈസർ. നിങ്ങളുടെ നെറ്റ്‌വർക്കിൽ എന്താണ് സംഭവിക്കുന്നതെന്ന് സൂക്ഷ്മതലത്തിൽ കാണാൻ ഇത് നിങ്ങളെ അനുവദിക്കുന്നു, കൂടാതെ നിരവധി വാണിജ്യ, ലാഭേച്ഛയില്ലാത്ത സംരംഭങ്ങൾ, സർക്കാർ ഏജൻസികൾ, വിദ്യാഭ്യാസ സ്ഥാപനങ്ങൾ എന്നിവയിലുടനീളം ഇത് യഥാർത്ഥ (പലപ്പോഴും നിയമപരമായ) മാനദണ്ഡമാണ്. ലോകമെമ്പാടുമുള്ള നെറ്റ്‌വർക്കിംഗ് വിദഗ്ധരുടെ സന്നദ്ധ സംഭാവനകൾക്ക് നന്ദി പറഞ്ഞുകൊണ്ട് വയർഷാർക്ക് വികസനം അഭിവൃദ്ധി പ്രാപിക്കുന്നു, 1998 ൽ ജെറാൾഡ് കോംബ്സ് ആരംഭിച്ച ഒരു പദ്ധതിയുടെ തുടർച്ചയാണിത്.
    nb_NO: Verdens fremste og mest brukte nettverksprotokollanalysator. Den lar deg se hva som skjer på nettverket ditt på et mikroskopisk nivå, og er de facto (og ofte de jure) standarden på tvers av mange kommersielle og ideelle bedrifter, offentlige etater og utdanningsinstitusjoner. Wireshark-utviklingen blomstrer takket være frivillige bidrag fra nettverkseksperter over hele verden, og er en fortsettelse av et prosjekt startet av Gerald Combs i 1998.
    nl_NL: Wireshark is 's werelds meest vooraanstaande en meest gebruikte netwerkprotocolanalysator. Het laat je zien wat er op je netwerk gebeurt op microscopisch niveau en is de de facto (en vaak de de jure) standaard voor veel commerciële en non-profitorganisaties, overheidsinstanties en onderwijsinstellingen. De ontwikkeling van Wireshark floreert dankzij de vrijwillige bijdragen van netwerkexperts over de hele wereld en is een voortzetting van een project dat in 1998 door Gerald Combs werd gestart.
    pl_PL: Wiodący i powszechnie używany na świecie analizator protokołów sieciowych. Pozwala zobaczyć, co dzieje się w sieci na poziomie mikroskopowym i jest de facto (a często de jure) standardem w wielu przedsiębiorstwach komercyjnych i non-profit, agencjach rządowych i instytucjach edukacyjnych. Rozwój Wiresharka rozwija się dzięki wolontariatowi ekspertów sieciowych z całego świata i jest kontynuacją projektu rozpoczętego przez Geralda Combsa w 1998 roku.
    pt_BR: O analisador de protocolos de rede mais importante e amplamente utilizado do mundo. Ele permite visualizar o que está acontecendo em sua rede em um nível microscópico e é o padrão de fato (e muitas vezes de direito) em diversas empresas comerciais e sem fins lucrativos, agências governamentais e instituições de ensino. O desenvolvimento do Wireshark prospera graças às contribuições voluntárias de especialistas em redes do mundo todo e é a continuação de um projeto iniciado por Gerald Combs em 1998.
    ro_RO: Cel mai important și utilizat analizor de protocoale de rețea din lume. Acesta vă permite să vedeți ce se întâmplă în rețeaua dvs. la nivel microscopic și este standardul de facto (și adesea de jure) în multe întreprinderi comerciale și non-profit, agenții guvernamentale și instituții de învățământ. Dezvoltarea Wireshark prosperă datorită contribuțiilor voluntare ale experților în rețele din întreaga lume și este continuarea unui proiect început de Gerald Combs în 1998.
    ru_RU: Wireshark — ведущий и широко используемый в мире анализатор сетевых протоколов. Он позволяет увидеть, что происходит в вашей сети на микроскопическом уровне, и является де-факто (а часто и де-юре) стандартом во многих коммерческих и некоммерческих предприятиях, государственных учреждениях и образовательных организациях. Разработка Wireshark процветает благодаря добровольному вкладу экспертов по сетям со всего мира и является продолжением проекта, начатого Джеральдом Комбсом в 1998 году.
    sk_SK: Najvýznamnejší a najpoužívanejší analyzátor sieťových protokolov na svete. Umožňuje vám vidieť, čo sa deje vo vašej sieti na mikroskopickej úrovni, a je de facto (a často de jure) štandardom v mnohých komerčných a neziskových podnikoch, vládnych agentúrach a vzdelávacích inštitúciách. Vývoj Wiresharku prosperuje vďaka dobrovoľníckym príspevkom sieťových expertov z celého sveta a je pokračovaním projektu, ktorý začal Gerald Combs v roku 1998.
    sv_SE: Världens främsta och mest använda nätverksprotokollanalysator. Den låter dig se vad som händer i ditt nätverk på mikroskopisk nivå och är de facto (och ofta de jure) standarden i många kommersiella och ideella företag, myndigheter och utbildningsinstitutioner. Wiresharks utveckling blomstrar tack vare frivilliga bidrag från nätverksexperter runt om i världen och är en fortsättning på ett projekt som startades av Gerald Combs 1998.
    tr_TR: Dünyanın önde gelen ve yaygın olarak kullanılan ağ protokolü analizcisi. Ağınızda neler olup bittiğini mikroskobik düzeyde görmenizi sağlar ve birçok ticari ve kar amacı gütmeyen kuruluş, devlet kurumu ve eğitim kurumu tarafından fiili (ve genellikle yasal) standart olarak kabul edilir. Wireshark geliştirme süreci, dünyanın dört bir yanındaki ağ uzmanlarının gönüllü katkıları sayesinde gelişmektedir ve Gerald Combs tarafından 1998'de başlatılan bir projenin devamıdır.
    zh_CN: 深入分析网络流量的协议分析器。
    zh_TW: 深入分析網路流量的協議分析器。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/wireshark-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/wireshark-icon.png
  title:
    en_US: Wireshark (LinuxServer.io)
    ca_ES: Wireshark (LinuxServer.io)
    cs_CZ: Wireshark (LinuxServer.io)
    da_DK: Wireshark (LinuxServer.io)
    de_DE: Wireshark (LinuxServer.io)
    el_GR: Wireshark (LinuxServer.io)
    en_GB: Wireshark (LinuxServer.io)
    es_ES: Wireshark (LinuxServer.io)
    fr_FR: Wireshark (LinuxServer.io)
    ga_IE: Wireshark (LinuxServer.io)
    hr_HR: Wireshark (LinuxServer.io)
    hu_HU: Wireshark (LinuxServer.io)
    it_IT: Wireshark (LinuxServer.io)
    ja_JP: Wireshark (LinuxServer.io)
    ko_KR: Wireshark (LinuxServer.io)
    ml_IN: Wireshark (LinuxServer.io)
    nb_NO: Wireshark (LinuxServer.io)
    nl_NL: Wireshark (LinuxServer.io)
    pl_PL: Wireshark (LinuxServer.io)
    pt_BR: Wireshark (LinuxServer.io)
    ro_RO: Wireshark (LinuxServer.io)
    ru_RU: Wireshark (LinuxServer.io)
    sk_SK: Wireshark (LinuxServer.io)
    sv_SE: Wireshark (LinuxServer.io)
    tr_TR: Wireshark (LinuxServer.io)
    zh_CN: Wireshark（LinuxServer.io）
    zh_TW: Wireshark（LinuxServer.io）
  category: Networking
  id: wisdomsky.linuxserver.linuxserverwireshark
  port_map: '80'
  version: 4.6.6
