name: linuxserver-mullvad-browser
services:
  app:
    image: linuxserver/mullvad-browser:15.0.21@sha256:2e53a2d02e60679097add505a2a54a992d6c8d55126d5bef111f2e3e36121b06
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      LOCAL_NET: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mullvad-browser/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /config/Downloads
    cap_add:
      - NET_ADMIN
    shm_size: 1gb
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermullvadbrowser/assets/icon.png
  title:
    en_US: Mullvad browser (LinuxServer.io)
    ca_ES: Mullvad browser (LinuxServer.io)
    cs_CZ: Mullvad browser (LinuxServer.io)
    da_DK: Mullvad browser (LinuxServer.io)
    de_DE: Mullvad browser (LinuxServer.io)
    el_GR: Mullvad browser (LinuxServer.io)
    en_GB: Mullvad browser (LinuxServer.io)
    es_ES: Mullvad browser (LinuxServer.io)
    fr_FR: Mullvad browser (LinuxServer.io)
    ga_IE: Mullvad browser (LinuxServer.io)
    hr_HR: Mullvad browser (LinuxServer.io)
    hu_HU: Mullvad browser (LinuxServer.io)
    it_IT: Mullvad browser (LinuxServer.io)
    ja_JP: Mullvad browser (LinuxServer.io)
    ko_KR: Mullvad browser (LinuxServer.io)
    ml_IN: Mullvad browser (LinuxServer.io)
    nb_NO: Mullvad browser (LinuxServer.io)
    nl_NL: Mullvad browser (LinuxServer.io)
    pl_PL: Mullvad browser (LinuxServer.io)
    pt_BR: Mullvad browser (LinuxServer.io)
    ro_RO: Mullvad browser (LinuxServer.io)
    ru_RU: Mullvad browser (LinuxServer.io)
    sk_SK: Mullvad browser (LinuxServer.io)
    sv_SE: Mullvad browser (LinuxServer.io)
    tr_TR: Mullvad browser (LinuxServer.io)
    zh_CN: Mullvad browser（LinuxServer.io）
    zh_TW: Mullvad browser（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservermullvadbrowser
  port_map: '3000'
  version: 15.0.21
