name: linuxserver-build-agent
services:
  app:
    image: linuxserver/build-agent:version-0296acb5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/build-agent/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: This container needs special attention. Please check https://hub.docker.com/r/linuxserver/build-agent for details.
    zh_CN: 此容器需要特别注意。使用前请阅读相关说明：https://hub.docker.com/r/linuxserver/build-agent
    ca_ES: Aquest contenidor necessita una atenció especial. Si us plau, consulteu https://hub.docker.com/r/linuxserver/build-agent per obtenir més informació.
    cs_CZ: Tento kontejner vyžaduje zvláštní pozornost. Podrobnosti naleznete na adrese https://hub.docker.com/r/linuxserver/build-agent.
    da_DK: Denne container kræver særlig opmærksomhed. Se venligst https://hub.docker.com/r/linuxserver/build-agent for yderligere oplysninger.
    de_DE: Dieser Container erfordert besondere Aufmerksamkeit. Weitere Informationen finden Sie unter https://hub.docker.com/r/linuxserver/build-agent.
    el_GR: Αυτό το κοντέινερ χρειάζεται ιδιαίτερη προσοχή. Δείτε τη διεύθυνση https://hub.docker.com/r/linuxserver/build-agent για λεπτομέρειες.
    en_GB: This container needs special attention. Please check https://hub.docker.com/r/linuxserver/build-agent for details.
    es_ES: Este contenedor requiere atención especial. Para obtener más detalles, consulte https://hub.docker.com/r/linuxserver/build-agent.
    fr_FR: Ce conteneur nécessite une attention particulière. Veuillez consulter https://hub.docker.com/r/linuxserver/build-agent pour plus de détails.
    ga_IE: Tá aird ar leith ag teastáil ón gcoimeádán seo. Féach ar https://hub.docker.com/r/linuxserver/build-agent le haghaidh tuilleadh sonraí.
    hr_HR: Ovaj kontejner zahtijeva posebnu pozornost. Za detalje posjetite https://hub.docker.com/r/linuxserver/build-agent.
    hu_HU: Ez a konténer különös figyelmet igényel. További részletekért kérjük, látogassa meg a https://hub.docker.com/r/linuxserver/build-agent oldalt.
    it_IT: Questo container richiede particolare attenzione. Per maggiori dettagli, consultare https://hub.docker.com/r/linuxserver/build-agent.
    ja_JP: このコンテナは特別な注意が必要です。詳細はhttps://hub.docker.com/r/linuxserver/build-agentをご確認ください。
    ko_KR: 이 컨테이너는 특별한 주의가 필요합니다. 자세한 내용은 https://hub.docker.com/r/linuxserver/build-agent 를 참조하십시오.
    ml_IN: ഈ കണ്ടെയ്‌നറിന് പ്രത്യേക ശ്രദ്ധ ആവശ്യമാണ്. വിശദാംശങ്ങൾക്ക് https://hub.docker.com/r/linuxserver/build-agent പരിശോധിക്കുക.
    nb_NO: Denne beholderen trenger spesiell oppmerksomhet. Se https://hub.docker.com/r/linuxserver/build-agent for mer informasjon.
    nl_NL: Deze container vereist speciale aandacht. Raadpleeg https://hub.docker.com/r/linuxserver/build-agent voor meer informatie.
    pl_PL: Ten kontener wymaga szczególnej uwagi. Szczegóły znajdziesz na stronie https://hub.docker.com/r/linuxserver/build-agent.
    pt_BR: Este contêiner requer atenção especial. Consulte https://hub.docker.com/r/linuxserver/build-agent para obter detalhes.
    ro_RO: Acest container necesită o atenție specială. Vă rugăm să consultați https://hub.docker.com/r/linuxserver/build-agent pentru detalii.
    ru_RU: Этот контейнер требует особого внимания. Подробности см. на странице https://hub.docker.com/r/linuxserver/build-agent.
    sk_SK: Tento kontajner si vyžaduje osobitnú pozornosť. Podrobnosti nájdete na stránke https://hub.docker.com/r/linuxserver/build-agent.
    sv_SE: Den här containern behöver särskild uppmärksamhet. Se https://hub.docker.com/r/linuxserver/build-agent för mer information.
    tr_TR: Bu konteyner özel ilgi gerektiriyor. Ayrıntılar için lütfen https://hub.docker.com/r/linuxserver/build-agent adresini kontrol edin.
    zh_TW: 此容器需要特別注意。使用前請閱讀相關說明：https://hub.docker.com/r/linuxserver/build-agent
  tagline:
    en_US: 'This container needs special attention. Please check https://hub. Docker. Com/r/linuxserver/build-agent for details. '
    zh_CN: 此容器需要特殊配置，请先阅读使用说明。
    ca_ES: Aquest contenidor necessita una atenció especial. Si us plau, consulteu https://hub.Docker.com/r/linuxserver/build-agent per obtenir més informació.
    cs_CZ: Tento kontejner vyžaduje zvláštní pozornost. Podrobnosti naleznete na https://hub.Docker.com/r/linuxserver/build-agent.
    da_DK: Denne container kræver særlig opmærksomhed. Se venligst https://hub.Docker.com/r/linuxserver/build-agent for yderligere oplysninger.
    de_DE: Dieser Container erfordert besondere Aufmerksamkeit. Weitere Informationen finden Sie unter https://hub.Docker.com/r/linuxserver/build-agent.
    el_GR: Αυτό το κοντέινερ χρειάζεται ιδιαίτερη προσοχή. Για λεπτομέρειες, ανατρέξτε στη διεύθυνση https://hub.Docker.com/r/linuxserver/build-agent.
    en_GB: 'This container needs special attention. Please check https://hub. Docker. Com/r/linuxserver/build-agent for details. '
    es_ES: Este contenedor requiere atención especial. Consulte https://hub.Docker.Com/r/linuxserver/build-agent para obtener más detalles.
    fr_FR: Ce conteneur nécessite une attention particulière. Veuillez consulter https://hub.docker.com/r/linuxserver/build-agent pour plus de détails.
    ga_IE: Tá aird ar leith ag teastáil ón gcoimeádán seo. Seiceáil https://hub.Docker.com/r/linuxserver/build-agent le haghaidh tuilleadh sonraí.
    hr_HR: Ovom kontejneru treba posvetiti posebnu pozornost. Za detalje posjetite https://hub.Docker.com/r/linuxserver/build-agent.
    hu_HU: Ez a konténer különös figyelmet igényel. További részletekért kérjük, látogassa meg a https://hub.Docker.Com/r/linuxserver/build-agent oldalt.
    it_IT: Questo container richiede particolare attenzione. Si prega di consultare https://hub.Docker.com/r/linuxserver/build-agent per i dettagli.
    ja_JP: このコンテナには特別な注意が必要です。詳細は https://hub.docker.com/r/linuxserver/build-agent をご確認ください。
    ko_KR: 이 컨테이너는 특별한 주의가 필요합니다. 자세한 내용은 https://hub.Docker.com/r/linuxserver/build-agent 를 참조하십시오.
    ml_IN: ഈ കണ്ടെയ്‌നറിന് പ്രത്യേക ശ്രദ്ധ ആവശ്യമാണ്. വിശദാംശങ്ങൾക്ക് https://hub. Docker. Com/r/linuxserver/build-agent പരിശോധിക്കുക.
    nb_NO: Denne containeren trenger spesiell oppmerksomhet. Se https://hub.Docker.com/r/linuxserver/build-agent for mer informasjon.
    nl_NL: Deze container vereist speciale aandacht. Raadpleeg https://hub.docker.com/r/linuxserver/build-agent voor meer informatie.
    pl_PL: Ten kontener wymaga szczególnej uwagi. Szczegóły można znaleźć na stronie https://hub.Docker.Com/r/linuxserver/build-agent.
    pt_BR: Este contêiner requer atenção especial. Consulte https://hub.docker.com/r/linuxserver/build-agent para obter detalhes.
    ro_RO: Acest container necesită o atenție specială. Vă rugăm să consultați https://hub.Docker.com/r/linuxserver/build-agent pentru detalii.
    ru_RU: Этот контейнер требует особого внимания. Пожалуйста, ознакомьтесь с подробной информацией по адресу https://hub.Docker.com/r/linuxserver/build-agent.
    sk_SK: Tento kontajner si vyžaduje osobitnú pozornosť. Podrobnosti nájdete na stránke https://hub.Docker.com/r/linuxserver/build-agent.
    sv_SE: Den här containern behöver särskild uppmärksamhet. Se https://hub.Docker.com/r/linuxserver/build-agent för mer information.
    tr_TR: Bu konteyner özel ilgi gerektiriyor. Ayrıntılar için lütfen https://hub.Docker.com/r/linuxserver/build-agent adresini kontrol edin.
    zh_TW: 此容器需要特殊配置，請先閱讀使用說明。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/WisdomSky/CasaOS-LinuxServer-AppStore/main/default-icon.svg
  thumbnail: ''
  title:
    en_US: Build agent
    zh_CN: Build agent
    ca_ES: Build agent
    cs_CZ: Build agent
    da_DK: Build agent
    de_DE: Build agent
    el_GR: Build agent
    en_GB: Build agent
    es_ES: Build agent
    fr_FR: Build agent
    ga_IE: Build agent
    hr_HR: Build agent
    hu_HU: Build agent
    it_IT: Build agent
    ja_JP: Build agent
    ko_KR: Build agent
    ml_IN: Build agent
    nb_NO: Build agent
    nl_NL: Build agent
    pl_PL: Build agent
    pt_BR: Build agent
    ro_RO: Build agent
    ru_RU: Build agent
    sk_SK: Build agent
    sv_SE: Build agent
    tr_TR: Build agent
    zh_TW: Build agent
  category: Others
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserverbuildagent
  version: version-0296acb5
