name: linuxserver-kometa
services:
  app:
    image: linuxserver/kometa:2.4.8@sha256:32fbf642e95c9a433c0efee762c7afaa3b6b014a2280aad06e576c9d28eb43a4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      KOMETA_CONFIG: ''
      KOMETA_TIMES: ''
      KOMETA_RUN: ''
      KOMETA_TESTS: ''
      KOMETA_NO_MISSING: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kometa/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverkometa/assets/icon.png
  title:
    en_US: Kometa (LinuxServer.io)
    ca_ES: Kometa (LinuxServer.io)
    cs_CZ: Kometa (LinuxServer.io)
    da_DK: Kometa (LinuxServer.io)
    de_DE: Kometa (LinuxServer.io)
    el_GR: Kometa (LinuxServer.io)
    en_GB: Kometa (LinuxServer.io)
    es_ES: Kometa (LinuxServer.io)
    fr_FR: Kometa (LinuxServer.io)
    ga_IE: Kometa (LinuxServer.io)
    hr_HR: Kometa (LinuxServer.io)
    hu_HU: Kometa (LinuxServer.io)
    it_IT: Kometa (LinuxServer.io)
    ja_JP: Kometa (LinuxServer.io)
    ko_KR: Kometa (LinuxServer.io)
    ml_IN: Kometa (LinuxServer.io)
    nb_NO: Kometa (LinuxServer.io)
    nl_NL: Kometa (LinuxServer.io)
    pl_PL: Kometa (LinuxServer.io)
    pt_BR: Kometa (LinuxServer.io)
    ro_RO: Kometa (LinuxServer.io)
    ru_RU: Kometa (LinuxServer.io)
    sk_SK: Kometa (LinuxServer.io)
    sv_SE: Kometa (LinuxServer.io)
    tr_TR: Kometa (LinuxServer.io)
    zh_CN: Kometa（LinuxServer.io）
    zh_TW: Kometa（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverkometa
  port_map: '80'
  version: 2.4.8
