name: linuxserver-kometa
services:
  app:
    image: linuxserver/kometa:2.4.8@sha256:e9ab6021a068c36b25461caa7480d4060566e35721a1e139bb31baffc6e22e6d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      KOMETA_CONFIG: ''
      KOMETA_TIMES: ''
      KOMETA_RUN: ''
      KOMETA_TESTS: ''
      KOMETA_NO_MISSING: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kometa/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverkometa/assets/icon.png
  title:
    en_US: Kometa (LinuxServer.io)
    zh_CN: Kometa（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverkometa
  port_map: '80'
  version: 2.4.8
