name: linuxserver-msedge
services:
  app:
    image: linuxserver/msedge:153.0.4234@sha256:7c89e6ca710b74c56e9c4e00c4549feef3c750d4eb3add152271d6d133efb5c1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EDGE_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/msedge/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermsedge/assets/icon.png
  title:
    en_US: Msedge (LinuxServer.io)
    ca_ES: Msedge (LinuxServer.io)
    cs_CZ: Msedge (LinuxServer.io)
    da_DK: Msedge (LinuxServer.io)
    de_DE: Msedge (LinuxServer.io)
    el_GR: Msedge (LinuxServer.io)
    en_GB: Msedge (LinuxServer.io)
    es_ES: Msedge (LinuxServer.io)
    fr_FR: Msedge (LinuxServer.io)
    ga_IE: Msedge (LinuxServer.io)
    hr_HR: Msedge (LinuxServer.io)
    hu_HU: Msedge (LinuxServer.io)
    it_IT: Msedge (LinuxServer.io)
    ja_JP: Msedge (LinuxServer.io)
    ko_KR: Msedge (LinuxServer.io)
    ml_IN: Msedge (LinuxServer.io)
    nb_NO: Msedge (LinuxServer.io)
    nl_NL: Msedge (LinuxServer.io)
    pl_PL: Msedge (LinuxServer.io)
    pt_BR: Msedge (LinuxServer.io)
    ro_RO: Msedge (LinuxServer.io)
    ru_RU: Msedge (LinuxServer.io)
    sk_SK: Msedge (LinuxServer.io)
    sv_SE: Msedge (LinuxServer.io)
    tr_TR: Msedge (LinuxServer.io)
    zh_CN: Msedge（LinuxServer.io）
    zh_TW: Msedge（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservermsedge
  port_map: '3000'
  version: 153.0.4234
