name: linuxserver-flexget
services:
  app:
    image: linuxserver/flexget:3.21.0@sha256:5b4b42671393954df26a158f860aa8bae9ef0279edcc898d63c6a589fa78f938
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FG_LOG_LEVEL: ''
      FG_LOG_FILE: ''
      FG_CONFIG_FILE: ''
      FG_WEBUI_PASSWORD: ''
    ports:
      - target: 5050
        published: 5050
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/flexget/config
        target: /config
      - type: bind
        source: /DATA/AppData/flexget/data
        target: /data
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverflexget/assets/icon.png
  title:
    en_US: Flexget (LinuxServer.io)
    ca_ES: Flexget (LinuxServer.io)
    cs_CZ: Flexget (LinuxServer.io)
    da_DK: Flexget (LinuxServer.io)
    de_DE: Flexget (LinuxServer.io)
    el_GR: Flexget (LinuxServer.io)
    en_GB: Flexget (LinuxServer.io)
    es_ES: Flexget (LinuxServer.io)
    fr_FR: Flexget (LinuxServer.io)
    ga_IE: Flexget (LinuxServer.io)
    hr_HR: Flexget (LinuxServer.io)
    hu_HU: Flexget (LinuxServer.io)
    it_IT: Flexget (LinuxServer.io)
    ja_JP: Flexget (LinuxServer.io)
    ko_KR: Flexget (LinuxServer.io)
    ml_IN: Flexget (LinuxServer.io)
    nb_NO: Flexget (LinuxServer.io)
    nl_NL: Flexget (LinuxServer.io)
    pl_PL: Flexget (LinuxServer.io)
    pt_BR: Flexget (LinuxServer.io)
    ro_RO: Flexget (LinuxServer.io)
    ru_RU: Flexget (LinuxServer.io)
    sk_SK: Flexget (LinuxServer.io)
    sv_SE: Flexget (LinuxServer.io)
    tr_TR: Flexget (LinuxServer.io)
    zh_CN: Flexget（LinuxServer.io）
    zh_TW: Flexget（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverflexget
  port_map: '5050'
  version: 3.21.0
