name: linuxserver-krita
services:
  app:
    image: linuxserver/krita:5.3.4@sha256:3ef7d9bbe85b905599cafba1b33438f86402a3173f3a6ced23b70c07c105291d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/krita/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverkrita/assets/icon.png
  title:
    en_US: Krita (LinuxServer.io)
    ca_ES: Krita (LinuxServer.io)
    cs_CZ: Krita (LinuxServer.io)
    da_DK: Krita (LinuxServer.io)
    de_DE: Krita (LinuxServer.io)
    el_GR: Krita (LinuxServer.io)
    en_GB: Krita (LinuxServer.io)
    es_ES: Krita (LinuxServer.io)
    fr_FR: Krita (LinuxServer.io)
    ga_IE: Krita (LinuxServer.io)
    hr_HR: Krita (LinuxServer.io)
    hu_HU: Krita (LinuxServer.io)
    it_IT: Krita (LinuxServer.io)
    ja_JP: Krita (LinuxServer.io)
    ko_KR: Krita (LinuxServer.io)
    ml_IN: Krita (LinuxServer.io)
    nb_NO: Krita (LinuxServer.io)
    nl_NL: Krita (LinuxServer.io)
    pl_PL: Krita (LinuxServer.io)
    pt_BR: Krita (LinuxServer.io)
    ro_RO: Krita (LinuxServer.io)
    ru_RU: Krita (LinuxServer.io)
    sk_SK: Krita (LinuxServer.io)
    sv_SE: Krita (LinuxServer.io)
    tr_TR: Krita (LinuxServer.io)
    zh_CN: Krita（LinuxServer.io）
    zh_TW: Krita（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverkrita
  port_map: '3000'
  version: 5.3.4
