name: linuxserver-telegram
services:
  app:
    image: linuxserver/telegram:7.2.8@sha256:3734b1c35d7073395363dfc3210300e82182b6de24abec805ca13a928b915989
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/telegram/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservertelegram/assets/icon.png
  title:
    en_US: Telegram (LinuxServer.io)
    ca_ES: Telegram (LinuxServer.io)
    cs_CZ: Telegram (LinuxServer.io)
    da_DK: Telegram (LinuxServer.io)
    de_DE: Telegram (LinuxServer.io)
    el_GR: Telegram (LinuxServer.io)
    en_GB: Telegram (LinuxServer.io)
    es_ES: Telegram (LinuxServer.io)
    fr_FR: Telegram (LinuxServer.io)
    ga_IE: Telegram (LinuxServer.io)
    hr_HR: Telegram (LinuxServer.io)
    hu_HU: Telegram (LinuxServer.io)
    it_IT: Telegram (LinuxServer.io)
    ja_JP: Telegram (LinuxServer.io)
    ko_KR: Telegram (LinuxServer.io)
    ml_IN: Telegram (LinuxServer.io)
    nb_NO: Telegram (LinuxServer.io)
    nl_NL: Telegram (LinuxServer.io)
    pl_PL: Telegram (LinuxServer.io)
    pt_BR: Telegram (LinuxServer.io)
    ro_RO: Telegram (LinuxServer.io)
    ru_RU: Telegram (LinuxServer.io)
    sk_SK: Telegram (LinuxServer.io)
    sv_SE: Telegram (LinuxServer.io)
    tr_TR: Telegram (LinuxServer.io)
    zh_CN: Telegram（LinuxServer.io）
    zh_TW: Telegram（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservertelegram
  port_map: '3000'
  version: 7.2.8
