name: linuxserver-altus
services:
  app:
    image: linuxserver/altus:5.8.1@sha256:96a13243c9cea98b8fdd1ac7ad5f7804ff517cc99f96847f5678c35e57f35719
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/altus/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveraltus/assets/icon.png
  title:
    en_US: Altus (LinuxServer.io)
    ca_ES: Altus (LinuxServer.io)
    cs_CZ: Altus (LinuxServer.io)
    da_DK: Altus (LinuxServer.io)
    de_DE: Altus (LinuxServer.io)
    el_GR: Altus (LinuxServer.io)
    en_GB: Altus (LinuxServer.io)
    es_ES: Altus (LinuxServer.io)
    fr_FR: Altus (LinuxServer.io)
    ga_IE: Altus (LinuxServer.io)
    hr_HR: Altus (LinuxServer.io)
    hu_HU: Altus (LinuxServer.io)
    it_IT: Altus (LinuxServer.io)
    ja_JP: Altus (LinuxServer.io)
    ko_KR: Altus (LinuxServer.io)
    ml_IN: Altus (LinuxServer.io)
    nb_NO: Altus (LinuxServer.io)
    nl_NL: Altus (LinuxServer.io)
    pl_PL: Altus (LinuxServer.io)
    pt_BR: Altus (LinuxServer.io)
    ro_RO: Altus (LinuxServer.io)
    ru_RU: Altus (LinuxServer.io)
    sk_SK: Altus (LinuxServer.io)
    sv_SE: Altus (LinuxServer.io)
    tr_TR: Altus (LinuxServer.io)
    zh_CN: Altus（LinuxServer.io）
    zh_TW: Altus（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserveraltus
  port_map: '3000'
  version: 5.8.1
