name: linuxserver-fail2ban
services:
  app:
    image: linuxserver/fail2ban:1.1.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VERBOSITY: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/fail2ban/config
        target: /config
      - type: bind
        source: /DATA/AppData/fail2ban/var/log:ro
        target: /var/log:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/airsonic:ro
        target: /remotelogs/airsonic:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/apache2:ro
        target: /remotelogs/apache2:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/authelia:ro
        target: /remotelogs/authelia:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/emby:ro
        target: /remotelogs/emby:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/filebrowser:ro
        target: /remotelogs/filebrowser:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/homeassistant:ro
        target: /remotelogs/homeassistant:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/lighttpd:ro
        target: /remotelogs/lighttpd:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/nextcloud:ro
        target: /remotelogs/nextcloud:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/nginx:ro
        target: /remotelogs/nginx:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/nzbget:ro
        target: /remotelogs/nzbget:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/overseerr:ro
        target: /remotelogs/overseerr:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/prowlarr:ro
        target: /remotelogs/prowlarr:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/radarr:ro
        target: /remotelogs/radarr:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/sabnzbd:ro
        target: /remotelogs/sabnzbd:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/sonarr:ro
        target: /remotelogs/sonarr:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/unificontroller:ro
        target: /remotelogs/unificontroller:ro
      - type: bind
        source: /DATA/AppData/fail2ban/remotelogs/vaultwarden:ro
        target: /remotelogs/vaultwarden:ro
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfail2ban/assets/icon.png
  title:
    en_US: Fail2ban (LinuxServer.io)
    ca_ES: Fail2ban (LinuxServer.io)
    cs_CZ: Fail2ban (LinuxServer.io)
    da_DK: Fail2ban (LinuxServer.io)
    de_DE: Fail2ban (LinuxServer.io)
    el_GR: Fail2ban (LinuxServer.io)
    en_GB: Fail2ban (LinuxServer.io)
    es_ES: Fail2ban (LinuxServer.io)
    fr_FR: Fail2ban (LinuxServer.io)
    ga_IE: Fail2ban (LinuxServer.io)
    hr_HR: Fail2ban (LinuxServer.io)
    hu_HU: Fail2ban (LinuxServer.io)
    it_IT: Fail2ban (LinuxServer.io)
    ja_JP: Fail2ban (LinuxServer.io)
    ko_KR: Fail2ban (LinuxServer.io)
    ml_IN: Fail2ban (LinuxServer.io)
    nb_NO: Fail2ban (LinuxServer.io)
    nl_NL: Fail2ban (LinuxServer.io)
    pl_PL: Fail2ban (LinuxServer.io)
    pt_BR: Fail2ban (LinuxServer.io)
    ro_RO: Fail2ban (LinuxServer.io)
    ru_RU: Fail2ban (LinuxServer.io)
    sk_SK: Fail2ban (LinuxServer.io)
    sv_SE: Fail2ban (LinuxServer.io)
    tr_TR: Fail2ban (LinuxServer.io)
    zh_CN: Fail2ban（LinuxServer.io）
    zh_TW: Fail2ban（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverfail2ban
  port_map: '80'
  version: 1.1.0
