name: linuxserver-piwigo
services:
  app:
    image: linuxserver/piwigo:16.4.0@sha256:ef81064952ed8ef289f18a3530bd1667c62ef1991624f92b475d91a46aae57e0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/piwigo/config
        target: /config
      - type: bind
        source: /DATA/AppData/piwigo/gallery
        target: /gallery
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverpiwigo/assets/icon.png
  title:
    en_US: Piwigo (LinuxServer.io)
    ca_ES: Piwigo (LinuxServer.io)
    cs_CZ: Piwigo (LinuxServer.io)
    da_DK: Piwigo (LinuxServer.io)
    de_DE: Piwigo (LinuxServer.io)
    el_GR: Piwigo (LinuxServer.io)
    en_GB: Piwigo (LinuxServer.io)
    es_ES: Piwigo (LinuxServer.io)
    fr_FR: Piwigo (LinuxServer.io)
    ga_IE: Piwigo (LinuxServer.io)
    hr_HR: Piwigo (LinuxServer.io)
    hu_HU: Piwigo (LinuxServer.io)
    it_IT: Piwigo (LinuxServer.io)
    ja_JP: Piwigo (LinuxServer.io)
    ko_KR: Piwigo (LinuxServer.io)
    ml_IN: Piwigo (LinuxServer.io)
    nb_NO: Piwigo (LinuxServer.io)
    nl_NL: Piwigo (LinuxServer.io)
    pl_PL: Piwigo (LinuxServer.io)
    pt_BR: Piwigo (LinuxServer.io)
    ro_RO: Piwigo (LinuxServer.io)
    ru_RU: Piwigo (LinuxServer.io)
    sk_SK: Piwigo (LinuxServer.io)
    sv_SE: Piwigo (LinuxServer.io)
    tr_TR: Piwigo (LinuxServer.io)
    zh_CN: Piwigo（LinuxServer.io）
    zh_TW: Piwigo（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverpiwigo
  port_map: '80'
  version: 16.4.0
