name: linuxserver-vivaldi
services:
  app:
    image: linuxserver/vivaldi:8.2.4133
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VIVALDI_CLI: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: VIVALDI_CLI
          description:
            en_US: Specify one or multiple Vivaldi CLI flags, this string will be passed to the application in full. [OPTIONAL]
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vivaldi/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Vivaldi is a Norwegian freeware, cross-platform web browser with a built-in email client developed by Vivaldi Technologies.
    ca_ES: Vivaldi és un navegador web noruec gratuït i multiplataforma amb un client de correu electrònic integrat desenvolupat per Vivaldi Technologies.
    cs_CZ: Vivaldi je norský freewarový multiplatformní webový prohlížeč s vestavěným e-mailovým klientem vyvinutý společností Vivaldi Technologies.
    da_DK: Vivaldi er en norsk freeware webbrowser til flere platforme med en indbygget e-mailklient udviklet af Vivaldi Technologies.
    de_DE: Vivaldi ist ein norwegischer Freeware-Webbrowser für verschiedene Plattformen mit integriertem E-Mail-Client, entwickelt von Vivaldi Technologies.
    el_GR: Το Vivaldi είναι ένα νορβηγικό δωρεάν, διαπλατφορμικό πρόγραμμα περιήγησης ιστού με ενσωματωμένο πρόγραμμα-πελάτη ηλεκτρονικού ταχυδρομείου, το οποίο αναπτύχθηκε από την Vivaldi Technologies.
    en_GB: Vivaldi is a Norwegian freeware, cross-platform web browser with a built-in email client developed by Vivaldi Technologies.
    es_ES: Vivaldi es un navegador web noruego gratuito y multiplataforma con un cliente de correo electrónico integrado, desarrollado por Vivaldi Technologies.
    fr_FR: Vivaldi est un navigateur web norvégien gratuit et multiplateforme doté d'un client de messagerie intégré, développé par Vivaldi Technologies.
    ga_IE: Is brabhsálaí gréasáin tras-ardáin saor in aisce Ioruach é Vivaldi le cliant ríomhphoist ionsuite arna fhorbairt ag Vivaldi Technologies.
    hr_HR: Vivaldi je norveški besplatni, višeplatformski web preglednik s ugrađenim klijentom e-pošte koji je razvila tvrtka Vivaldi Technologies.
    hu_HU: A Vivaldi egy norvég ingyenes, többplatformos webböngésző beépített e-mail klienssel, amelyet a Vivaldi Technologies fejlesztett ki.
    it_IT: Vivaldi è un browser web gratuito multipiattaforma norvegese con client di posta elettronica integrato, sviluppato da Vivaldi Technologies.
    ja_JP: Vivaldiは、Vivaldi Technologies社が開発した、ノルウェー製のフリーウェアでクロスプラットフォーム対応のウェブブラウザであり、メールクライアントが内蔵されています。
    ko_KR: Vivaldi는 Vivaldi Technologies에서 개발한 노르웨이산 무료 크로스 플랫폼 웹 브라우저로, 이메일 클라이언트가 내장되어 있습니다.
    ml_IN: വിവാൾഡി ടെക്നോളജീസ് വികസിപ്പിച്ചെടുത്ത ഒരു ബിൽറ്റ്-ഇൻ ഇമെയിൽ ക്ലയന്റുള്ള ഒരു നോർവീജിയൻ ഫ്രീവെയർ, ക്രോസ്-പ്ലാറ്റ്ഫോം വെബ് ബ്രൗസറാണ് വിവാൾഡി.
    nb_NO: Vivaldi er en norsk gratis, plattformuavhengig nettleser med innebygd e-postklient utviklet av Vivaldi Technologies.
    nl_NL: Vivaldi is een Noorse freeware, platformonafhankelijke webbrowser met een ingebouwde e-mailclient, ontwikkeld door Vivaldi Technologies.
    pl_PL: Vivaldi to norweska, darmowa, wieloplatformowa przeglądarka internetowa z wbudowanym klientem poczty e-mail, opracowana przez Vivaldi Technologies.
    pt_BR: O Vivaldi é um navegador web norueguês gratuito e multiplataforma com um cliente de e-mail integrado, desenvolvido pela Vivaldi Technologies.
    ro_RO: Vivaldi este un browser web norvegian gratuit, multiplatformă, cu un client de e-mail încorporat, dezvoltat de Vivaldi Technologies.
    ru_RU: Vivaldi — это норвежский бесплатный кроссплатформенный веб-браузер со встроенным почтовым клиентом, разработанный компанией Vivaldi Technologies.
    sk_SK: Vivaldi je nórsky freeware, multiplatformový webový prehliadač so vstavaným e-mailovým klientom, ktorý vyvinula spoločnosť Vivaldi Technologies.
    sv_SE: Vivaldi är en norsk gratis, plattformsoberoende webbläsare med en inbyggd e-postklient utvecklad av Vivaldi Technologies.
    tr_TR: Vivaldi, Vivaldi Technologies tarafından geliştirilen, Norveç menşeli, ücretsiz, platformlar arası bir web tarayıcısı ve entegre e-posta istemcisidir.
    zh_CN: Vivaldi 是由挪威公司 Vivaldi Technologies 开发的免费跨平台网页浏览器，内置电子邮件客户端。
    zh_TW: Vivaldi 是由挪威公司 Vivaldi Technologies 開發的免費跨平臺網頁瀏覽器，內建電子郵件客戶端。
  tagline:
    en_US: A Norwegian freeware, cross-platform web browser with a built-in email client developed by Vivaldi Technologies.
    ca_ES: Un navegador web noruec gratuït i multiplataforma amb un client de correu electrònic integrat desenvolupat per Vivaldi Technologies.
    cs_CZ: Norský freewarový multiplatformní webový prohlížeč s vestavěným e-mailovým klientem vyvinutý společností Vivaldi Technologies.
    da_DK: En norsk freeware, cross-platform webbrowser med en indbygget e-mail-klient udviklet af Vivaldi Technologies.
    de_DE: Ein norwegischer Freeware-Webbrowser für verschiedene Plattformen mit integriertem E-Mail-Client, entwickelt von Vivaldi Technologies.
    el_GR: Ένα νορβηγικό δωρεάν, διαπλατφορμικό πρόγραμμα περιήγησης ιστού με ενσωματωμένο πρόγραμμα-πελάτη ηλεκτρονικού ταχυδρομείου, που αναπτύχθηκε από την Vivaldi Technologies.
    en_GB: A Norwegian freeware, cross-platform web browser with a built-in email client developed by Vivaldi Technologies.
    es_ES: Un navegador web noruego gratuito y multiplataforma con cliente de correo electrónico integrado, desarrollado por Vivaldi Technologies.
    fr_FR: Un navigateur web norvégien gratuit et multiplateforme avec un client de messagerie intégré, développé par Vivaldi Technologies.
    ga_IE: Brabhsálaí gréasáin tras-ardáin saor in aisce Ioruach le cliant ríomhphoist ionsuite arna fhorbairt ag Vivaldi Technologies.
    hr_HR: Norveški besplatni web preglednik za više platformi s ugrađenim klijentom e-pošte koji je razvio Vivaldi Technologies.
    hu_HU: Egy norvég ingyenes, platformfüggetlen webböngésző beépített e-mail klienssel, amelyet a Vivaldi Technologies fejlesztett ki.
    it_IT: Un browser web gratuito multipiattaforma norvegese con client di posta elettronica integrato, sviluppato da Vivaldi Technologies.
    ja_JP: Vivaldi Technologies社が開発した、ノルウェー製のフリーウェアでクロスプラットフォーム対応のウェブブラウザ。メールクライアントが内蔵されている。
    ko_KR: 노르웨이의 Vivaldi Technologies에서 개발한 이메일 클라이언트가 내장된 무료 크로스 플랫폼 웹 브라우저입니다.
    ml_IN: വിവാൾഡി ടെക്നോളജീസ് വികസിപ്പിച്ചെടുത്ത ഒരു ബിൽറ്റ്-ഇൻ ഇമെയിൽ ക്ലയന്റുള്ള ഒരു നോർവീജിയൻ ഫ്രീവെയർ, ക്രോസ്-പ്ലാറ്റ്ഫോം വെബ് ബ്രൗസർ.
    nb_NO: En norsk gratis, plattformuavhengig nettleser med innebygd e-postklient utviklet av Vivaldi Technologies.
    nl_NL: Een Noorse freeware, platformonafhankelijke webbrowser met een ingebouwde e-mailclient, ontwikkeld door Vivaldi Technologies.
    pl_PL: Darmowa, wieloplatformowa norweska przeglądarka internetowa z wbudowanym klientem poczty e-mail, opracowana przez Vivaldi Technologies.
    pt_BR: Um navegador web norueguês gratuito e multiplataforma com cliente de e-mail integrado, desenvolvido pela Vivaldi Technologies.
    ro_RO: Un browser web norvegian gratuit, multiplatformă, cu un client de e-mail încorporat, dezvoltat de Vivaldi Technologies.
    ru_RU: Норвежский бесплатный кроссплатформенный веб-браузер со встроенным почтовым клиентом, разработанный компанией Vivaldi Technologies.
    sk_SK: Nórsky freeware, multiplatformový webový prehliadač so vstavaným e-mailovým klientom vyvinutý spoločnosťou Vivaldi Technologies.
    sv_SE: En norsk gratis, plattformsoberoende webbläsare med inbyggd e-postklient utvecklad av Vivaldi Technologies.
    tr_TR: Vivaldi Technologies tarafından geliştirilen, dahili e-posta istemcisine sahip, Norveç yapımı ücretsiz, platformlar arası bir web tarayıcısı.
    zh_CN: 内置邮件客户端的跨平台浏览器。
    zh_TW: 內建郵件客戶端的跨平臺瀏覽器。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/vivaldi-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/vivaldi-logo.png
  title:
    en_US: Vivaldi (LinuxServer.io)
    ca_ES: Vivaldi (LinuxServer.io)
    cs_CZ: Vivaldi (LinuxServer.io)
    da_DK: Vivaldi (LinuxServer.io)
    de_DE: Vivaldi (LinuxServer.io)
    el_GR: Vivaldi (LinuxServer.io)
    en_GB: Vivaldi (LinuxServer.io)
    es_ES: Vivaldi (LinuxServer.io)
    fr_FR: Vivaldi (LinuxServer.io)
    ga_IE: Vivaldi (LinuxServer.io)
    hr_HR: Vivaldi (LinuxServer.io)
    hu_HU: Vivaldi (LinuxServer.io)
    it_IT: Vivaldi (LinuxServer.io)
    ja_JP: Vivaldi (LinuxServer.io)
    ko_KR: Vivaldi (LinuxServer.io)
    ml_IN: Vivaldi (LinuxServer.io)
    nb_NO: Vivaldi (LinuxServer.io)
    nl_NL: Vivaldi (LinuxServer.io)
    pl_PL: Vivaldi (LinuxServer.io)
    pt_BR: Vivaldi (LinuxServer.io)
    ro_RO: Vivaldi (LinuxServer.io)
    ru_RU: Vivaldi (LinuxServer.io)
    sk_SK: Vivaldi (LinuxServer.io)
    sv_SE: Vivaldi (LinuxServer.io)
    tr_TR: Vivaldi (LinuxServer.io)
    zh_CN: Vivaldi（LinuxServer.io）
    zh_TW: Vivaldi（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxservervivaldi
  port_map: '3000'
  version: 8.2.4133
