name: linuxserver-ppsspp
services:
  app:
    image: linuxserver/ppsspp:1.20.4@sha256:cc7b9754b102e9901bfe858abc7d778b910d5dd3497ef5926461684df7012861
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ppsspp/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverppsspp/assets/icon.png
  title:
    en_US: Ppsspp (LinuxServer.io)
    ca_ES: Ppsspp (LinuxServer.io)
    cs_CZ: Ppsspp (LinuxServer.io)
    da_DK: Ppsspp (LinuxServer.io)
    de_DE: Ppsspp (LinuxServer.io)
    el_GR: Ppsspp (LinuxServer.io)
    en_GB: Ppsspp (LinuxServer.io)
    es_ES: Ppsspp (LinuxServer.io)
    fr_FR: Ppsspp (LinuxServer.io)
    ga_IE: Ppsspp (LinuxServer.io)
    hr_HR: Ppsspp (LinuxServer.io)
    hu_HU: Ppsspp (LinuxServer.io)
    it_IT: Ppsspp (LinuxServer.io)
    ja_JP: Ppsspp (LinuxServer.io)
    ko_KR: Ppsspp (LinuxServer.io)
    ml_IN: Ppsspp (LinuxServer.io)
    nb_NO: Ppsspp (LinuxServer.io)
    nl_NL: Ppsspp (LinuxServer.io)
    pl_PL: Ppsspp (LinuxServer.io)
    pt_BR: Ppsspp (LinuxServer.io)
    ro_RO: Ppsspp (LinuxServer.io)
    ru_RU: Ppsspp (LinuxServer.io)
    sk_SK: Ppsspp (LinuxServer.io)
    sv_SE: Ppsspp (LinuxServer.io)
    tr_TR: Ppsspp (LinuxServer.io)
    zh_CN: Ppsspp（LinuxServer.io）
    zh_TW: Ppsspp（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverppsspp
  port_map: '3000'
  version: 1.20.4
