name: linuxserver-zotero
services:
  app:
    image: linuxserver/zotero:10.0.2@sha256:357938d8f34bf1522429e111797312f1710d7f256b7cc196b2dc3d1992899ae5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/zotero/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverzotero/assets/icon.png
  title:
    en_US: Zotero (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverzotero
  port_map: '3000'
  version: 10.0.2
