name: linuxserver-transmission
services:
  app:
    image: linuxserver/transmission:4.1.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TRANSMISSION_WEB_HOME: ''
      USER: ''
      PASS: ''
      WHITELIST: ''
      PEERPORT: ''
      HOST_WHITELIST: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: TRANSMISSION_WEB_HOME
          description:
            en_US: Specify the path to an alternative UI folder. [OPTIONAL]
        - container: USER
          description:
            en_US: Specify an optional username for the interface [OPTIONAL]
        - container: PASS
          description:
            en_US: Specify an optional password for the interface [OPTIONAL]
        - container: WHITELIST
          description:
            en_US: Specify an optional list of comma separated ip whitelist. Fills rpc-whitelist setting. [OPTIONAL]
        - container: PEERPORT
          description:
            en_US: Specify an optional port for torrent TCP/UDP connections. Fills peer-port setting. [OPTIONAL]
        - container: HOST_WHITELIST
          description:
            en_US: Specify an optional list of comma separated dns name whitelist. Fills rpc-host-whitelist setting. [OPTIONAL]
    ports:
      - target: 9091
        published: 9091
        protocol: tcp
      - target: 51413
        published: 51413
        protocol: tcp
      - target: 51413
        published: 51413
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/transmission/config
        target: /config
      - type: bind
        source: /DATA/AppData/transmission/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/transmission/watch
        target: /watch
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: 'Transmission is designed for easy, powerful use. Transmission has the features you want from a BitTorrent client: encryption, a web interface, peer exchange, magnet links, DHT, µTP, UPnP and NAT-PMP port forwarding, webseed support, watch directories, tracker editing, global and per-torrent speed limits, and more.'
    ca_ES: 'Transmission està dissenyat per a un ús fàcil i potent. Transmission té les funcions que desitges d''un client BitTorrent: xifratge, una interfície web, intercanvi d''iguals, enllaços magnètics, DHT, µTP, reenviament de ports UPnP i NAT-PMP, compatibilitat amb webseed, directoris de vigilància, edició de rastrejadors, límits de velocitat globals i per torrent, i molt més.'
    cs_CZ: 'Transmission je navržen pro snadné a výkonné použití. Transmission nabízí funkce, které od BitTorrent klienta očekáváte: šifrování, webové rozhraní, výměnu peerů, magnetické odkazy, přesměrování portů DHT, µTP, UPnP a NAT-PMP, podporu webseed, sledovací adresáře, úpravu trackerů, globální a pro jednotlivé torrenty rychlostní limity a další.'
    da_DK: 'Transmission er designet til nem og effektiv brug. Transmission har de funktioner, du ønsker fra en BitTorrent-klient: kryptering, en webgrænseflade, peer-udveksling, magnetlinks, DHT, µTP, UPnP og NAT-PMP portvideresendelse, webseed-understøttelse, overvågningsmapper, tracker-redigering, globale og per-torrent hastighedsgrænser og meget mere.'
    de_DE: 'Transmission ist auf einfache und leistungsstarke Nutzung ausgelegt. Transmission bietet alle Funktionen, die Sie von einem BitTorrent-Client erwarten: Verschlüsselung, eine Weboberfläche, Peer-Austausch, Magnet-Links, DHT, µTP, UPnP- und NAT-PMP-Portweiterleitung, Webseed-Unterstützung, Überwachungsverzeichnisse, Tracker-Bearbeitung, globale und Torrent-spezifische Geschwindigkeitsbegrenzungen und vieles mehr.'
    el_GR: 'Η μετάδοση έχει σχεδιαστεί για εύκολη και ισχυρή χρήση. Η μετάδοση διαθέτει τα χαρακτηριστικά που θέλετε από έναν πελάτη BitTorrent: κρυπτογράφηση, διαδικτυακή διεπαφή, ανταλλαγή peer, μαγνητικούς συνδέσμους, προώθηση θυρών DHT, µTP, UPnP και NAT-PMP, υποστήριξη webseed, καταλόγους παρακολούθησης, επεξεργασία tracker, παγκόσμια και ανά torrent όρια ταχύτητας και πολλά άλλα.'
    en_GB: 'Transmission is designed for easy, powerful use. Transmission has the features you want from a Bittorrent client: encryption, a web interface, peer exchange, magnet links, Dht, µTP, Upnp and Nat-Pmp port forwarding, webseed support, watch directories, tracker editing, global and per-torrent speed limits, and more.'
    es_ES: 'Transmission está diseñado para un uso sencillo y potente. Transmission cuenta con las funciones que esperas de un cliente BitTorrent: cifrado, interfaz web, intercambio de pares, enlaces magnéticos, DHT, µTP, redireccionamiento de puertos UPnP y NAT-PMP, compatibilidad con webseed, directorios de vigilancia, edición de rastreadores, límites de velocidad globales y por torrent, y mucho más.'
    fr_FR: "Transmission est conçu pour une utilisation simple et performante. Il offre toutes les fonctionnalités attendues d'un client BitTorrent\_: chiffrement, interface web, échange de pairs, liens magnétiques, DHT, µTP, UPnP et redirection de ports NAT-PMP, prise en charge des webseeds, répertoires de surveillance, édition des trackers, limites de vitesse globales et par torrent, et bien plus encore."
    ga_IE: 'Tá Tarchur deartha le haghaidh úsáide éasca, cumhachtaí. Tá na gnéithe atá uait ó chliant BitTorrent ag Tarchur: criptiú, comhéadan gréasáin, malartú piaraí, naisc mhaighnéadacha, DHT, µTP, UPnP agus atreorú calafoirt NAT-PMP, tacaíocht síol gréasáin, eolairí faire, eagarthóireacht rianaithe, teorainneacha luais domhanda agus in aghaidh an torrent, agus tuilleadh.'
    hr_HR: 'Transmission je dizajniran za jednostavno i snažno korištenje. Transmission ima značajke koje želite od BitTorrent klijenta: enkripciju, web sučelje, razmjenu podataka među torrentima, magnet veze, DHT, µTP, UPnP i NAT-PMP prosljeđivanje portova, podršku za webseed, direktorije za praćenje, uređivanje trackera, globalna i ograničenja brzine po torrentu i još mnogo toga.'
    hu_HU: 'Az átvitelt az egyszerű és hatékony használatra tervezték. Az átvitel rendelkezik azokkal a funkciókkal, amelyeket egy BitTorrent klienstől elvárhatsz: titkosítás, webes felület, peer exchange, magnet linkek, DHT, µTP, UPnP és NAT-PMP porttovábbítás, webseed támogatás, figyelőkönyvtárak, nyomkövető szerkesztés, globális és torrentenkénti sebességkorlátozások és egyebek.'
    it_IT: 'Transmission è progettato per un utilizzo semplice e potente. Offre tutte le funzionalità che desideri da un client BitTorrent: crittografia, interfaccia web, scambio di peer, link magnet, DHT, µTP, inoltro di porte UPnP e NAT-PMP, supporto per webseed, directory di monitoraggio, modifica dei tracker, limiti di velocità globali e per singolo torrent e molto altro.'
    ja_JP: Transmissionは、簡単かつパワフルな使用を念頭に設計されています。Transmissionには、BitTorrentクライアントに求められる機能がすべて備わっています。暗号化、Webインターフェース、ピア交換、マグネットリンク、DHT、µTP、UPnP、NAT-PMPポートフォワーディング、Webシードサポート、ウォッチディレクトリ、トラッカー編集、グローバルおよびトレントごとの速度制限など、その他にも多くの機能があります。
    ko_KR: Transmission은 쉽고 강력한 사용을 위해 설계되었습니다. Transmission은 암호화, 웹 인터페이스, 피어 교환, 마그넷 링크, DHT, µTP, UPnP 및 NAT-PMP 포트 포워딩, 웹시드 지원, 감시 디렉토리, 트래커 편집, 전체 및 토렌트별 속도 제한 등 BitTorrent 클라이언트에서 원하는 모든 기능을 제공합니다.
    ml_IN: 'എളുപ്പത്തിലും ശക്തവുമായ ഉപയോഗത്തിനായി ട്രാൻസ്മിഷൻ രൂപകൽപ്പന ചെയ്‌തിരിക്കുന്നു. ഒരു ബിറ്റ്‌ടോറന്റ് ക്ലയന്റിൽ നിന്ന് നിങ്ങൾ ആഗ്രഹിക്കുന്ന സവിശേഷതകൾ ട്രാൻസ്മിഷനിൽ ഉണ്ട്: എൻക്രിപ്ഷൻ, ഒരു വെബ് ഇന്റർഫേസ്, പിയർ എക്സ്ചേഞ്ച്, മാഗ്നറ്റ് ലിങ്കുകൾ, DHT, µTP, UPnP, NAT-PMP പോർട്ട് ഫോർവേഡിംഗ്, വെബ്‌സീഡ് പിന്തുണ, വാച്ച് ഡയറക്ടറികൾ, ട്രാക്കർ എഡിറ്റിംഗ്, ഗ്ലോബൽ, പെർ-ടോറന്റ് വേഗത പരിധികൾ, കൂടാതെ മറ്റു പലതും.'
    nb_NO: 'Transmission er designet for enkel og kraftig bruk. Transmission har funksjonene du ønsker deg fra en BitTorrent-klient: kryptering, et webgrensesnitt, peer-utveksling, magnetlenker, DHT, µTP, UPnP og NAT-PMP portvideresending, webseed-støtte, overvåkingskataloger, redigering av sporingssporing, globale og per-torrent-fartsgrenser og mer.'
    nl_NL: 'Transmission is ontworpen voor eenvoudig en krachtig gebruik. Transmission beschikt over alle functies die je van een BitTorrent-client verwacht: encryptie, een webinterface, peer-uitwisseling, magnetlinks, DHT, µTP, UPnP en NAT-PMP port forwarding, webseed-ondersteuning, watch directories, trackerbewerking, globale en per-torrent snelheidslimieten en meer.'
    pl_PL: 'Transmission został zaprojektowany z myślą o łatwości i wydajności. Oferuje funkcje, których oczekujesz od klienta BitTorrent: szyfrowanie, interfejs webowy, wymianę peerów, łącza magnet, przekierowywanie portów DHT, µTP, UPnP i NAT-PMP, obsługę webseedów, katalogi obserwowane, edycję trackerów, globalne i indywidualne limity prędkości dla torrentów i wiele innych.'
    pt_BR: 'O Transmission foi projetado para ser usado de forma fácil e poderosa. Ele possui os recursos que você espera de um cliente BitTorrent: criptografia, interface web, troca de pares, links magnéticos, encaminhamento de portas DHT, µTP, UPnP e NAT-PMP, suporte a webseed, diretórios de monitoramento, edição de trackers, limites de velocidade globais e por torrent, e muito mais.'
    ro_RO: 'Transmission este conceput pentru o utilizare ușoară și puternică. Transmission are funcțiile pe care le doriți de la un client BitTorrent: criptare, interfață web, schimb de date peer-exchange, legături magnet, DHT, µTP, redirecționare de port UPnP și NAT-PMP, suport webseed, directoare de supraveghere, editare tracker, limite de viteză globale și per torrent și multe altele.'
    ru_RU: 'Transmission разработан для простого и эффективного использования. Transmission обладает всеми функциями, которые вы ожидаете от BitTorrent-клиента: шифрование, веб-интерфейс, обмен пирами, magnet-ссылки, DHT, µTP, UPnP и переадресация портов NAT-PMP, поддержка веб-сидов, каталоги наблюдения, редактирование трекеров, глобальные и индивидуальные ограничения скорости для каждого торрента и многое другое.'
    sk_SK: 'Transmission je navrhnutý pre jednoduché a výkonné používanie. Transmission má funkcie, ktoré od BitTorrent klienta očakávate: šifrovanie, webové rozhranie, výmenu peerov, magnetické odkazy, presmerovanie portov DHT, µTP, UPnP a NAT-PMP, podporu webseed, sledovacie adresáre, úpravu sledovača, globálne a pre každý torrent rýchlostné limity a ďalšie.'
    sv_SE: 'Transmission är utformad för enkel och kraftfull användning. Transmission har de funktioner du önskar av en BitTorrent-klient: kryptering, ett webbgränssnitt, peer-utbyte, magnetlänkar, DHT, µTP, UPnP och NAT-PMP portvidarebefordran, stöd för webbseed, bevakningskataloger, redigering av spårare, globala och per-torrent hastighetsgränser och mer.'
    tr_TR: 'Transmission, kolay ve güçlü kullanım için tasarlanmıştır. Transmission, bir BitTorrent istemcisinden istediğiniz özelliklere sahiptir: şifreleme, web arayüzü, eşler arası değişim, magnet bağlantıları, DHT, µTP, UPnP ve NAT-PMP port yönlendirme, webseed desteği, izleme dizinleri, izleyici düzenleme, genel ve torrent başına hız sınırları ve daha fazlası.'
    zh_CN: Transmission 兼顾易用性和强大功能，提供 BitTorrent 客户端所需的加密、网页界面、节点交换、磁力链接、DHT、µTP、UPnP 和 NAT-PMP 端口转发、Web 种子、监控目录、Tracker 编辑、全局及单个种子的限速等功能。
    zh_TW: Transmission 兼顧易用性和強大功能，提供 BitTorrent 客戶端所需的加密、網頁介面、節點交換、磁力連結、DHT、µTP、UPnP 和 NAT-PMP 埠轉發、Web 種子、監控目錄、Tracker 編輯、全域性及單個種子的限速等功能。
  tagline:
    en_US: 'Designed for easy, powerful use. Transmission has the features you want from a BitTorrent client: encryption, a web interface, peer exchange, magnet links, DHT, µTP, UPnP and NAT-PMP port forwarding, webseed support, watch directories, tracker editing, global and per-torrent speed limits, and more.'
    ca_ES: 'Dissenyat per a un ús fàcil i potent. Transmission té les funcions que desitges d''un client BitTorrent: xifratge, interfície web, intercanvi d''iguals, enllaços magnètics, DHT, µTP, reenviament de ports UPnP i NAT-PMP, compatibilitat amb webseed, directoris de vigilància, edició de rastrejadors, límits de velocitat globals i per torrent, i molt més.'
    cs_CZ: 'Navrženo pro snadné a výkonné použití. Transmission nabízí funkce, které od BitTorrent klienta očekáváte: šifrování, webové rozhraní, výměnu peerů, magnetické odkazy, přesměrování portů DHT, µTP, UPnP a NAT-PMP, podporu webseed, sledovací adresáře, úpravu trackerů, globální a pro jednotlivé torrenty rychlostní limity a další.'
    da_DK: 'Designet til nem og effektiv brug. Transmission har de funktioner, du ønsker fra en BitTorrent-klient: kryptering, en webgrænseflade, peer-udveksling, magnetlinks, DHT, µTP, UPnP og NAT-PMP portvideresendelse, webseed-understøttelse, overvågningsmapper, tracker-redigering, globale og per-torrent hastighedsgrænser og meget mere.'
    de_DE: 'Transmission wurde für eine einfache und leistungsstarke Nutzung entwickelt und bietet alle Funktionen, die Sie von einem BitTorrent-Client erwarten: Verschlüsselung, eine Weboberfläche, Peer-Austausch, Magnet-Links, DHT, µTP, UPnP- und NAT-PMP-Portweiterleitung, Webseed-Unterstützung, Überwachungsverzeichnisse, Tracker-Bearbeitung, globale und Torrent-spezifische Geschwindigkeitsbegrenzungen und vieles mehr.'
    el_GR: 'Σχεδιασμένο για εύκολη και ισχυρή χρήση. Η μετάδοση διαθέτει τα χαρακτηριστικά που θέλετε από έναν πελάτη BitTorrent: κρυπτογράφηση, διαδικτυακή διεπαφή, ανταλλαγή peer, μαγνητικούς συνδέσμους, προώθηση θυρών DHT, µTP, UPnP και NAT-PMP, υποστήριξη webseed, καταλόγους παρακολούθησης, επεξεργασία tracker, παγκόσμια και ανά torrent όρια ταχύτητας και πολλά άλλα.'
    en_GB: 'Designed for easy, powerful use. Transmission has the features you want from a Bittorrent client: encryption, a web interface, peer exchange, magnet links, Dht, µTP, Upnp and Nat-Pmp port forwarding, webseed support, watch directories, tracker editing, global and per-torrent speed limits, and more.'
    es_ES: 'Diseñado para un uso sencillo y potente. Transmission cuenta con las funciones que esperas de un cliente BitTorrent: cifrado, interfaz web, intercambio de pares, enlaces magnéticos, DHT, µTP, reenvío de puertos UPnP y NAT-PMP, compatibilidad con webseed, directorios de vigilancia, edición de rastreadores, límites de velocidad globales y por torrent, y mucho más.'
    fr_FR: "Conçu pour une utilisation simple et performante, Transmission possède toutes les fonctionnalités que vous attendez d'un client BitTorrent\_: chiffrement, interface web, échange de pairs, liens magnétiques, DHT, µTP, UPnP et redirection de ports NAT-PMP, prise en charge des webseeds, répertoires de surveillance, édition des trackers, limites de vitesse globales et par torrent, et bien plus encore."
    ga_IE: 'Deartha le haghaidh úsáide éasca, cumhachtaí. Tá na gnéithe atá uait ó chliant BitTorrent ag Tarchur: criptiú, comhéadan gréasáin, malartú piaraí, naisc mhaighnéadacha, DHT, µTP, UPnP agus atreorú calafoirt NAT-PMP, tacaíocht síol gréasáin, eolairí faire, eagarthóireacht rianaithe, teorainneacha luais domhanda agus in aghaidh an torrent, agus tuilleadh.'
    hr_HR: 'Dizajniran za jednostavno i snažno korištenje. Transmission ima značajke koje želite od BitTorrent klijenta: enkripciju, web sučelje, razmjenu podataka među vršnjacima, magnetske veze, DHT, µTP, UPnP i NAT-PMP prosljeđivanje portova, podršku za webseed, direktorije za praćenje, uređivanje trackera, globalna i ograničenja brzine po torrentu i još mnogo toga.'
    hu_HU: 'Könnyű és hatékony használatra tervezve. Az átvitel rendelkezik azokkal a funkciókkal, amelyeket egy BitTorrent klienstől elvárhatsz: titkosítás, webes felület, peer exchange, magnet linkek, DHT, µTP, UPnP és NAT-PMP porttovábbítás, webseed támogatás, figyelőkönyvtárak, nyomkövető szerkesztés, globális és torrentenkénti sebességkorlátozások és egyebek.'
    it_IT: 'Progettato per un utilizzo semplice e potente, Transmission offre tutte le funzionalità che desideri da un client BitTorrent: crittografia, interfaccia web, scambio di peer, link magnet, DHT, µTP, inoltro porte UPnP e NAT-PMP, supporto per webseed, directory di monitoraggio, modifica dei tracker, limiti di velocità globali e per singolo torrent e molto altro.'
    ja_JP: Transmissionは、簡単かつパワフルな使用のために設計されています。暗号化、Webインターフェース、ピア交換、マグネットリンク、DHT、µTP、UPnPおよびNAT-PMPポートフォワーディング、Webシードサポート、ウォッチディレクトリ、トラッカー編集、グローバルおよびトレントごとの速度制限など、BitTorrentクライアントに求められるすべての機能を備えています。
    ko_KR: 간편하고 강력한 사용을 위해 설계된 Transmission은 암호화, 웹 인터페이스, 피어 교환, 마그넷 링크, DHT, µTP, UPnP 및 NAT-PMP 포트 포워딩, 웹시드 지원, 감시 목록, 트래커 편집, 전체 및 토렌트별 속도 제한 등 BitTorrent 클라이언트에서 원하는 모든 기능을 제공합니다.
    ml_IN: 'എളുപ്പവും ശക്തവുമായ ഉപയോഗത്തിനായി രൂപകൽപ്പന ചെയ്‌തിരിക്കുന്നു. ഒരു ബിറ്റ്‌ടോറന്റ് ക്ലയന്റിൽ നിന്ന് നിങ്ങൾ ആഗ്രഹിക്കുന്ന സവിശേഷതകൾ ട്രാൻസ്മിഷനിൽ ഉണ്ട്: എൻക്രിപ്ഷൻ, ഒരു വെബ് ഇന്റർഫേസ്, പിയർ എക്സ്ചേഞ്ച്, മാഗ്നറ്റ് ലിങ്കുകൾ, DHT, µTP, UPnP, NAT-PMP പോർട്ട് ഫോർവേഡിംഗ്, വെബ്‌സീഡ് പിന്തുണ, വാച്ച് ഡയറക്ടറികൾ, ട്രാക്കർ എഡിറ്റിംഗ്, ഗ്ലോബൽ, പെർ-ടോറന്റ് വേഗത പരിധികൾ, കൂടാതെ മറ്റു പലതും.'
    nb_NO: 'Designet for enkel og kraftig bruk. Transmission har funksjonene du ønsker deg fra en BitTorrent-klient: kryptering, et webgrensesnitt, peer-utveksling, magnetlenker, DHT, µTP, UPnP og NAT-PMP portvideresending, webseed-støtte, overvåkingskataloger, redigering av sporing, globale og per-torrent-fartsgrenser og mer.'
    nl_NL: 'Ontworpen voor eenvoudig en krachtig gebruik. Transmission beschikt over alle functies die u van een BitTorrent-client verwacht: encryptie, een webinterface, peer-uitwisseling, magnetlinks, DHT, µTP, UPnP en NAT-PMP port forwarding, webseed-ondersteuning, watch directories, trackerbewerking, globale en per-torrent snelheidslimieten en meer.'
    pl_PL: 'Zaprojektowany z myślą o łatwości i wydajności. Transmission oferuje funkcje, których oczekujesz od klienta BitTorrent: szyfrowanie, interfejs webowy, wymianę peerów, łącza magnet, przekierowywanie portów DHT, µTP, UPnP i NAT-PMP, obsługę webseed, katalogi obserwowanych plików, edycję trackerów, globalne i indywidualne limity prędkości dla torrentów i wiele innych.'
    pt_BR: 'Projetado para uso fácil e poderoso, o Transmission possui os recursos que você espera de um cliente BitTorrent: criptografia, interface web, troca de pares, links magnéticos, encaminhamento de portas DHT, µTP, UPnP e NAT-PMP, suporte a webseed, diretórios de monitoramento, edição de trackers, limites de velocidade globais e por torrent, e muito mais.'
    ro_RO: 'Conceput pentru o utilizare ușoară și puternică. Transmission are funcțiile pe care le doriți de la un client BitTorrent: criptare, interfață web, schimb de date peer-exchange, legături magnet, DHT, µTP, redirecționare de port UPnP și NAT-PMP, suport webseed, directoare de supraveghere, editare tracker, limite de viteză globale și per torrent și multe altele.'
    ru_RU: 'Разработан для простого и эффективного использования. Transmission обладает всеми функциями, которые вы ожидаете от BitTorrent-клиента: шифрование, веб-интерфейс, обмен пирами, magnet-ссылки, DHT, µTP, UPnP и переадресация портов NAT-PMP, поддержка веб-сидов, каталоги наблюдения, редактирование трекеров, глобальные и индивидуальные ограничения скорости для каждого торрента и многое другое.'
    sk_SK: 'Navrhnuté pre jednoduché a výkonné používanie. Transmission má funkcie, ktoré od BitTorrent klienta očakávate: šifrovanie, webové rozhranie, výmenu peerov, magnetické odkazy, presmerovanie portov DHT, µTP, UPnP a NAT-PMP, podporu webseed, sledovacie adresáre, úpravu sledovača, globálne a pre každý torrent rýchlostné limity a ďalšie.'
    sv_SE: 'Utformad för enkel och kraftfull användning. Transmission har de funktioner du önskar av en BitTorrent-klient: kryptering, ett webbgränssnitt, peer-utbyte, magnetlänkar, DHT, µTP, UPnP och NAT-PMP portvidarebefordran, stöd för webbseed, bevakningskataloger, redigering av spårare, globala och per-torrent hastighetsgränser och mer.'
    tr_TR: 'Kolay ve güçlü kullanım için tasarlanmıştır. Transmission, bir BitTorrent istemcisinden istediğiniz özelliklere sahiptir: şifreleme, web arayüzü, eşler arası değişim, magnet bağlantıları, DHT, µTP, UPnP ve NAT-PMP port yönlendirme, webseed desteği, izleme dizinleri, izleyici düzenleme, genel ve torrent başına hız sınırları ve daha fazlası.'
    zh_CN: 易用且功能丰富的 BitTorrent 客户端。
    zh_TW: 易用且功能豐富的 BitTorrent 客戶端。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/transmission.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/transmission.png
  title:
    en_US: Transmission (LinuxServer.io)
    ca_ES: Transmission (LinuxServer.io)
    cs_CZ: Transmission (LinuxServer.io)
    da_DK: Transmission (LinuxServer.io)
    de_DE: Transmission (LinuxServer.io)
    el_GR: Transmission (LinuxServer.io)
    en_GB: Transmission (LinuxServer.io)
    es_ES: Transmission (LinuxServer.io)
    fr_FR: Transmission (LinuxServer.io)
    ga_IE: Transmission (LinuxServer.io)
    hr_HR: Transmission (LinuxServer.io)
    hu_HU: Transmission (LinuxServer.io)
    it_IT: Transmission (LinuxServer.io)
    ja_JP: Transmission (LinuxServer.io)
    ko_KR: Transmission (LinuxServer.io)
    ml_IN: Transmission (LinuxServer.io)
    nb_NO: Transmission (LinuxServer.io)
    nl_NL: Transmission (LinuxServer.io)
    pl_PL: Transmission (LinuxServer.io)
    pt_BR: Transmission (LinuxServer.io)
    ro_RO: Transmission (LinuxServer.io)
    ru_RU: Transmission (LinuxServer.io)
    sk_SK: Transmission (LinuxServer.io)
    sv_SE: Transmission (LinuxServer.io)
    tr_TR: Transmission (LinuxServer.io)
    zh_CN: Transmission（LinuxServer.io）
    zh_TW: Transmission（LinuxServer.io）
  category: Media
  id: wisdomsky.linuxserver.linuxservertransmission
  version: 4.1.3
