name: linuxserver-sqlitebrowser
services:
  app:
    image: linuxserver/sqlitebrowser:3.13.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sqlitebrowser/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserversqlitebrowser/assets/icon.png
  title:
    en_US: Sqlitebrowser (LinuxServer.io)
    zh_CN: Sqlitebrowser（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserversqlitebrowser
  port_map: '3000'
  version: 3.13.1
