name: linuxserver-sqlitebrowser
services:
  app:
    image: linuxserver/sqlitebrowser:3.13.1@sha256:4da032f384676ae11f0de849720c3445bad1bc885bfdb9a2b4c5f01d446830f0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sqlitebrowser/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserversqlitebrowser/assets/icon.png
  title:
    en_US: Sqlitebrowser (LinuxServer.io)
    ca_ES: Sqlitebrowser (LinuxServer.io)
    cs_CZ: Sqlitebrowser (LinuxServer.io)
    da_DK: Sqlitebrowser (LinuxServer.io)
    de_DE: Sqlitebrowser (LinuxServer.io)
    el_GR: Sqlitebrowser (LinuxServer.io)
    en_GB: Sqlitebrowser (LinuxServer.io)
    es_ES: Sqlitebrowser (LinuxServer.io)
    fr_FR: Sqlitebrowser (LinuxServer.io)
    ga_IE: Sqlitebrowser (LinuxServer.io)
    hr_HR: Sqlitebrowser (LinuxServer.io)
    hu_HU: Sqlitebrowser (LinuxServer.io)
    it_IT: Sqlitebrowser (LinuxServer.io)
    ja_JP: Sqlitebrowser (LinuxServer.io)
    ko_KR: Sqlitebrowser (LinuxServer.io)
    ml_IN: Sqlitebrowser (LinuxServer.io)
    nb_NO: Sqlitebrowser (LinuxServer.io)
    nl_NL: Sqlitebrowser (LinuxServer.io)
    pl_PL: Sqlitebrowser (LinuxServer.io)
    pt_BR: Sqlitebrowser (LinuxServer.io)
    ro_RO: Sqlitebrowser (LinuxServer.io)
    ru_RU: Sqlitebrowser (LinuxServer.io)
    sk_SK: Sqlitebrowser (LinuxServer.io)
    sv_SE: Sqlitebrowser (LinuxServer.io)
    tr_TR: Sqlitebrowser (LinuxServer.io)
    zh_CN: Sqlitebrowser（LinuxServer.io）
    zh_TW: Sqlitebrowser（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserversqlitebrowser
  port_map: '3000'
  version: 3.13.1
