name: linuxserver-overseerr
services:
  app:
    image: linuxserver/overseerr:1.33.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 5055
        published: 5055
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/overseerr/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveroverseerr/assets/icon.png
  title:
    en_US: Overseerr
    zh_CN: Overseerr
    ca_ES: Overseerr
    cs_CZ: Overseerr
    da_DK: Overseerr
    de_DE: Overseerr
    el_GR: Overseerr
    en_GB: Overseerr
    es_ES: Overseerr
    fr_FR: Overseerr
    ga_IE: Overseerr
    hr_HR: Overseerr
    hu_HU: Overseerr
    it_IT: Overseerr
    ja_JP: Overseerr
    ko_KR: Overseerr
    ml_IN: Overseerr
    nb_NO: Overseerr
    nl_NL: Overseerr
    pl_PL: Overseerr
    pt_BR: Overseerr
    ro_RO: Overseerr
    ru_RU: Overseerr
    sk_SK: Overseerr
    sv_SE: Overseerr
    tr_TR: Overseerr
    zh_TW: Overseerr
  port_map: '5055'
  id: wisdomsky.linuxserver.linuxserveroverseerr
  version: 1.33.2
