name: linuxserver-endlessh
services:
  app:
    image: linuxserver/endlessh:version-dfe44eb2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MSDELAY: ''
      MAXLINES: ''
      MAXCLIENTS: ''
      LOGFILE: ''
      BINDFAMILY: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: MSDELAY
          description:
            en_US: The endless banner is sent one line at a time. This is the delay in milliseconds between individual lines.
        - container: MAXLINES
          description:
            en_US: The length of each line is randomized. This controls the maximum length of each line. Shorter lines may keep clients on for longer if they give up after a certain number of bytes.
        - container: MAXCLIENTS
          description:
            en_US: Maximum number of connections to accept at a time. Connections beyond this are not immediately rejected, but will wait in the queue.
        - container: LOGFILE
          description:
            en_US: By default, the app logs to container log. If this is set to true, the log will be output to file under /config/logs/endlessh (/config needs to be mapped).
        - container: BINDFAMILY
          description:
            en_US: By default, the app binds to IPv4 and IPv6 addresses. Set it to 4 or 6 to bind to IPv4 only or IPv6 only, respectively. Leave blank to bind to both.
      volumes:
        - container: /config
          description:
            en_US: Required if `LOGFILE` is set to `true`.
        - container: /config
          description:
            en_US: Required if `LOGFILE` is set to `true`.
      ports:
        - container: '22'
          description:
            en_US: ssh port
    ports:
      - target: 22
        published: 2222
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/endlessh/config
        target: /config
      - type: bind
        source: /DATA/AppData/endlessh/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    zh_CN: |-
      Endlessh 是一个 SSH 陷阱，会极其缓慢地发送无穷无尽的随机 SSH 标识，将 SSH 客户端拖住数小时甚至数天。其用途是将真正的 SSH 服务放在其他端口，让自动扫描和攻击脚本陷入这个陷阱，而不是干扰真实服务器。

      访问项目主页：https://github.com/orgs/linuxserver/packages/container/package/endlessh
    ca_ES: 'Visita la pàgina principal: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    cs_CZ: 'Navštivte domovskou stránku: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    da_DK: 'Besøg hjemmesiden: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    de_DE: 'Besuchen Sie die Homepage: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    el_GR: 'Επισκεφθείτε την αρχική σελίδα: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    en_GB: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    es_ES: 'Visita la página principal: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    fr_FR: "Consultez la page d'accueil\_: https://github.com/orgs/linuxserver/packages/container/package/endlessh"
    ga_IE: 'Tabhair cuairt ar an leathanach baile: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    hr_HR: 'Posjetite početnu stranicu: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    hu_HU: 'Látogassa meg a honlapot: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    it_IT: 'Visita la homepage: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    ja_JP: 'ホームページをご覧ください: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    ko_KR: '홈페이지 방문: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    ml_IN: 'ഹോംപേജ് സന്ദർശിക്കുക: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    nb_NO: 'Besøk hjemmesiden: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    nl_NL: 'Bezoek de homepage: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    pl_PL: 'Odwiedź stronę główną: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    pt_BR: 'Visite a página inicial: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    ro_RO: 'Vizitați pagina principală: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    ru_RU: 'Перейдите на главную страницу: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    sk_SK: 'Navštívte domovskú stránku: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    sv_SE: 'Besök hemsidan: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    tr_TR: 'Ana sayfayı ziyaret edin: https://github.com/orgs/linuxserver/packages/container/package/endlessh'
    zh_TW: |-
      Endlessh 是一個 SSH 陷阱，會極其緩慢地傳送無窮無盡的隨機 SSH 標識，將 SSH 客戶端拖住數小時甚至數天。其用途是將真正的 SSH 服務放在其他埠，讓自動掃描和攻擊指令碼陷入這個陷阱，而不是干擾真實伺服器。

      訪問專案主頁：https://github.com/orgs/linuxserver/packages/container/package/endlessh
  tagline:
    en_US: An SSH tarpit that very slowly sends an endless, random SSH banner. It keeps SSH clients locked up for hours or even days at a time. The purpose is to put your real SSH server on another port and then let the script kiddies get stuck in this tarpit instead of bothering a real server.
    zh_CN: 通过缓慢发送 SSH 标识拖住扫描客户端。
    ca_ES: Un port tarpit SSH que envia molt lentament un bàner SSH aleatori i interminable. Manté els clients SSH bloquejats durant hores o fins i tot dies. L'objectiu és posar el servidor SSH real en un altre port i deixar que els script kiddies es quedin encallats en aquest port tarpit en comptes de molestar un servidor real.
    cs_CZ: SSH tarpit, který velmi pomalu odesílá nekonečný, náhodný SSH banner. Udržuje SSH klienty uzamčené na hodiny nebo i dny. Účelem je přepnout váš skutečný SSH server na jiný port a nechat skriptovací dělníky uvíznout v tomto tarpitu, místo aby obtěžovali skutečný server.
    da_DK: En SSH-port, der meget langsomt sender et uendeligt, tilfældigt SSH-banner. Den holder SSH-klienter låst i timevis eller endda dage ad gangen. Formålet er at placere din rigtige SSH-server på en anden port og derefter lade scriptkiddies sidde fast i denne port i stedet for at genere en rigtig server.
    de_DE: Eine SSH-Falle, die in sehr langsamer Zeit ein endloses, zufälliges SSH-Banner sendet. Dadurch werden SSH-Clients stunden- oder sogar tagelang blockiert. Der Zweck ist, den eigentlichen SSH-Server auf einem anderen Port zu betreiben und Scriptkiddies in dieser Falle gefangen zu halten, anstatt den echten Server zu stören.
    el_GR: Ένα SSH tarpit που στέλνει πολύ αργά ένα ατελείωτο, τυχαίο banner SSH. Κρατά τους πελάτες SSH κλειδωμένους για ώρες ή και μέρες κάθε φορά. Ο σκοπός είναι να τοποθετήσετε τον πραγματικό σας διακομιστή SSH σε μια άλλη θύρα και στη συνέχεια να αφήσετε τα script kiddies να κολλήσουν σε αυτό το tarpit αντί να ενοχλήσουν έναν πραγματικό διακομιστή.
    en_GB: An Ssh tarpit that very slowly sends an endless, random Ssh banner. It keeps Ssh clients locked up for hours or even days at a time. The purpose is to put your real Ssh server on another port and then let the script kiddies get stuck in this tarpit instead of bothering a real server.
    es_ES: Un servidor SSH bloqueado que envía muy lentamente un banner aleatorio e interminable. Mantiene a los clientes SSH bloqueados durante horas o incluso días. El objetivo es conectar tu servidor SSH real a otro puerto y dejar que los hackers novatos se queden atrapados en este servidor bloqueado en lugar de molestar a un servidor legítimo.
    fr_FR: Un piège SSH qui envoie très lentement une bannière SSH aléatoire et infinie. Il bloque les clients SSH pendant des heures, voire des jours. Le but est de déplacer votre véritable serveur SSH sur un autre port et de piéger les script kiddies dans ce piège plutôt que de s'attaquer à un serveur légitime.
    ga_IE: Calafort SSH a sheolann meirge SSH randamach gan teorainn go han-mhall. Coinníonn sé cliaint SSH faoi ghlas ar feadh uaireanta nó fiú laethanta ag an am. Is é an cuspóir ná do fhreastalaí SSH fíor a chur ar phort eile agus ansin ligean do na páistí scripte dul i bhfostú sa chalafort seo in ionad cur isteach ar fhreastalaí fíor.
    hr_HR: SSH tarpit koji vrlo sporo šalje beskonačan, nasumičan SSH banner. Drži SSH klijente zaključane satima ili čak danima. Svrha je staviti vaš pravi SSH poslužitelj na drugi port, a zatim pustiti skriptne klince da se zaglave u ovom tarpitu umjesto da gnjave pravi poslužitelj.
    hu_HU: Egy SSH kártya, ami nagyon lassan küld végtelen, véletlenszerű SSH bannereket. Órákra, vagy akár napokra is zárolva tartja az SSH klienseket. A célja, hogy az igazi SSH szerveredet egy másik portra tedd, majd hagyd, hogy a script kiddies ezen a kártyán ragadjon ahelyett, hogy egy igazi szervert zavarna.
    it_IT: Un "tarpit" SSH che invia molto lentamente un banner SSH casuale e infinito. Blocca i client SSH per ore o addirittura giorni. Lo scopo è quello di spostare il server SSH reale su un'altra porta e lasciare che gli script kiddies rimangano intrappolati in questo "tarpit" invece di attaccare un server legittimo.
    ja_JP: 非常にゆっくりと、無限にランダムなSSHバナーを送信するSSHターピットです。SSHクライアントを数時間、場合によっては数日間もロックダウン状態にします。目的は、実際のSSHサーバーを別のポートに切り替え、スクリプトキディが実際のサーバーを妨害する代わりに、このターピットに閉じ込められるようにすることです。
    ko_KR: 매우 느린 속도로 무작위 SSH 배너 메시지를 끊임없이 전송하는 SSH 타르핏입니다. 이로 인해 SSH 클라이언트가 몇 시간 또는 며칠 동안 접속이 차단됩니다. 목적은 실제 SSH 서버를 다른 포트에 두고, 스크립트 키디들이 실제 서버를 공격하는 대신 이 타르핏에 갇히도록 유도하는 것입니다.
    ml_IN: വളരെ സാവധാനത്തിൽ അനന്തമായ, ക്രമരഹിതമായ SSH ബാനർ അയയ്ക്കുന്ന ഒരു SSH ടാർപിറ്റ്. ഇത് SSH ക്ലയന്റുകളെ മണിക്കൂറുകളോ ദിവസങ്ങളോ തുടർച്ചയായി പൂട്ടിയിടുന്നു. നിങ്ങളുടെ യഥാർത്ഥ SSH സെർവറിനെ മറ്റൊരു പോർട്ടിൽ സ്ഥാപിക്കുകയും പിന്നീട് ഒരു യഥാർത്ഥ സെർവറിനെ ശല്യപ്പെടുത്തുന്നതിനുപകരം സ്ക്രിപ്റ്റ് കുട്ടികളെ ഈ ടാർപിറ്റിൽ കുടുങ്ങാൻ അനുവദിക്കുകയും ചെയ്യുക എന്നതാണ് ഇതിന്റെ ഉദ്ദേശ്യം.
    nb_NO: En SSH-port som veldig sakte sender et endeløst, tilfeldig SSH-banner. Den holder SSH-klienter låst i timevis eller til og med dager av gangen. Hensikten er å sette den virkelige SSH-serveren din på en annen port, og deretter la skriptkiddiene bli sittende fast i denne porten i stedet for å plage en ekte server.
    nl_NL: Een SSH-valstrik die heel langzaam een eindeloze, willekeurige SSH-banner verstuurt. Hierdoor worden SSH-clients uren of zelfs dagenlang geblokkeerd. Het doel is om je echte SSH-server op een andere poort te zetten en de scriptkiddies in deze valstrik te laten vastlopen in plaats van een echte server lastig te vallen.
    pl_PL: Tarpit SSH, który bardzo powoli wysyła niekończący się, losowy baner SSH. Utrzymuje klientów SSH zablokowanych na godziny, a nawet dni. Celem jest przeniesienie prawdziwego serwera SSH na inny port, a następnie umożliwienie skryptowym dzieciakom utknięcia w tym tarpicie zamiast przeszkadzania prawdziwemu serwerowi.
    pt_BR: Um "tarpit" SSH que envia, muito lentamente, um banner SSH aleatório e interminável. Ele mantém os clientes SSH bloqueados por horas ou até mesmo dias. O objetivo é colocar seu servidor SSH real em outra porta e, em seguida, deixar que os script kiddies fiquem presos nesse "tarpit" em vez de sobrecarregar um servidor de verdade.
    ro_RO: Un port tarpit SSH care trimite foarte lent un banner SSH aleatoriu și nesfârșit. Menține clienții SSH blocați ore întregi sau chiar zile întregi. Scopul este de a plasa serverul SSH real pe un alt port și apoi de a lăsa script kiddies-ii să rămână blocați în acest port tarpit în loc să deranjeze un server real.
    ru_RU: Это SSH-ловушка, которая очень медленно отправляет бесконечный случайный SSH-баннер. Она держит SSH-клиентов в ловушке часами или даже днями. Цель состоит в том, чтобы перевести ваш настоящий SSH-сервер на другой порт, а затем позволить начинающим скрипт-программистам застрять в этой ловушке вместо того, чтобы беспокоить настоящий сервер.
    sk_SK: SSH tarpit, ktorý veľmi pomaly posiela nekonečný, náhodný SSH banner. Udržiava SSH klientov uzamknutých na hodiny alebo dokonca dni. Účelom je prepojiť váš skutočný SSH server s iným portom a nechať skriptovacie deti uviaznuť v tomto tarpite namiesto toho, aby obťažovali skutočný server.
    sv_SE: En SSH-port som mycket långsamt skickar en oändlig, slumpmässig SSH-banner. Den håller SSH-klienter inlåsta i timmar eller till och med dagar i sträck. Syftet är att placera din riktiga SSH-server på en annan port och sedan låta script kiddies fastna i denna port istället för att störa en riktig server.
    tr_TR: Sonsuz ve rastgele bir SSH banner'ı çok yavaş bir şekilde gönderen bir SSH tuzak yazılımı. SSH istemcilerini saatlerce hatta günlerce kilitli tutar. Amacı, gerçek SSH sunucunuzu başka bir porta taşımak ve ardından bilgisayar korsanlarının gerçek bir sunucuyu rahatsız etmek yerine bu tuzak yazılımına takılıp kalmasını sağlamaktır.
    zh_TW: 透過緩慢傳送 SSH 標識拖住掃描客戶端。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/openssh-server-logo.png
  thumbnail: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/openssh-server-logo.png
  title:
    en_US: Endlessh
    zh_CN: Endlessh
    ca_ES: Endlessh
    cs_CZ: Endlessh
    da_DK: Endlessh
    de_DE: Endlessh
    el_GR: Endlessh
    en_GB: Endlessh
    es_ES: Endlessh
    fr_FR: Endlessh
    ga_IE: Endlessh
    hr_HR: Endlessh
    hu_HU: Endlessh
    it_IT: Endlessh
    ja_JP: Endlessh
    ko_KR: Endlessh
    ml_IN: Endlessh
    nb_NO: Endlessh
    nl_NL: Endlessh
    pl_PL: Endlessh
    pt_BR: Endlessh
    ro_RO: Endlessh
    ru_RU: Endlessh
    sk_SK: Endlessh
    sv_SE: Endlessh
    tr_TR: Endlessh
    zh_TW: Endlessh
  category: Others
  project_url: https://github.com/skeeto/endlessh
  port_map: '8080'
  id: wisdomsky.linuxserver.linuxserverendlessh
  version: version-dfe44eb2
  website: https://github.com/skeeto/endlessh
