name: linuxserver-diskover
services:
  app:
    image: linuxserver/diskover:2.3.5@sha256:9d19e97c59f2381028f3bb35549acb2b4301a9e1dc730c267b54403a4ad2a2a8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ES_HOST: ''
      ES_PORT: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/diskover/config
        target: /config
      - type: bind
        source: /DATA/AppData/diskover/data
        target: /data
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverdiskover/assets/icon.png
  title:
    en_US: Diskover (LinuxServer.io)
    ca_ES: Diskover (LinuxServer.io)
    cs_CZ: Diskover (LinuxServer.io)
    da_DK: Diskover (LinuxServer.io)
    de_DE: Diskover (LinuxServer.io)
    el_GR: Diskover (LinuxServer.io)
    en_GB: Diskover (LinuxServer.io)
    es_ES: Diskover (LinuxServer.io)
    fr_FR: Diskover (LinuxServer.io)
    ga_IE: Diskover (LinuxServer.io)
    hr_HR: Diskover (LinuxServer.io)
    hu_HU: Diskover (LinuxServer.io)
    it_IT: Diskover (LinuxServer.io)
    ja_JP: Diskover (LinuxServer.io)
    ko_KR: Diskover (LinuxServer.io)
    ml_IN: Diskover (LinuxServer.io)
    nb_NO: Diskover (LinuxServer.io)
    nl_NL: Diskover (LinuxServer.io)
    pl_PL: Diskover (LinuxServer.io)
    pt_BR: Diskover (LinuxServer.io)
    ro_RO: Diskover (LinuxServer.io)
    ru_RU: Diskover (LinuxServer.io)
    sk_SK: Diskover (LinuxServer.io)
    sv_SE: Diskover (LinuxServer.io)
    tr_TR: Diskover (LinuxServer.io)
    zh_CN: Diskover（LinuxServer.io）
    zh_TW: Diskover（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverdiskover
  port_map: '80'
  version: 2.3.5
