name: linuxserver-scummvm
services:
  app:
    image: linuxserver/scummvm:2026.3.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/scummvm/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverscummvm/assets/icon.png
  title:
    en_US: Scummvm (LinuxServer.io)
    ca_ES: Scummvm (LinuxServer.io)
    cs_CZ: Scummvm (LinuxServer.io)
    da_DK: Scummvm (LinuxServer.io)
    de_DE: Scummvm (LinuxServer.io)
    el_GR: Scummvm (LinuxServer.io)
    en_GB: Scummvm (LinuxServer.io)
    es_ES: Scummvm (LinuxServer.io)
    fr_FR: Scummvm (LinuxServer.io)
    ga_IE: Scummvm (LinuxServer.io)
    hr_HR: Scummvm (LinuxServer.io)
    hu_HU: Scummvm (LinuxServer.io)
    it_IT: Scummvm (LinuxServer.io)
    ja_JP: Scummvm (LinuxServer.io)
    ko_KR: Scummvm (LinuxServer.io)
    ml_IN: Scummvm (LinuxServer.io)
    nb_NO: Scummvm (LinuxServer.io)
    nl_NL: Scummvm (LinuxServer.io)
    pl_PL: Scummvm (LinuxServer.io)
    pt_BR: Scummvm (LinuxServer.io)
    ro_RO: Scummvm (LinuxServer.io)
    ru_RU: Scummvm (LinuxServer.io)
    sk_SK: Scummvm (LinuxServer.io)
    sv_SE: Scummvm (LinuxServer.io)
    tr_TR: Scummvm (LinuxServer.io)
    zh_CN: Scummvm（LinuxServer.io）
    zh_TW: Scummvm（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverscummvm
  port_map: '3000'
  version: 2026.3.0
