name: linuxserver-emulatorjs
services:
  app:
    image: linuxserver/emulatorjs:1.9.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SUBFOLDER: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: SUBFOLDER
          description:
            en_US: Specify a subfolder for reverse proxies IE '/FOLDER/'
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
      - target: 4001
        published: 4001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/emulatorjs/config
        target: /config
      - type: bind
        source: /DATA/AppData/emulatorjs/data
        target: /data
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Emulatorjs - In browser web based emulation portable to nearly any device for many retro consoles. A mix of emulators is used between Libretro and EmulatorJS.
    zh_CN: EmulatorJS 提供基于浏览器的网页模拟功能，几乎可在任何设备上运行多种复古游戏主机。它混合使用 Libretro 和 EmulatorJS 的模拟器。
    ca_ES: 'Emulatorjs: emulació basada en web per a navegadors, portable a gairebé qualsevol dispositiu per a moltes consoles retro. S''utilitza una barreja d''emuladors entre Libretro i EmulatorJS.'
    cs_CZ: Emulatorjs - Emulace v prohlížeči, přenositelná na téměř jakékoli zařízení pro mnoho retro konzolí. Používá se kombinace emulátorů Libretro a EmulatorJS.
    da_DK: Emulatorjs - Webbaseret emulering i browseren, der kan overføres til næsten enhver enhed til mange retro-konsoller. Der bruges en blanding af emulatorer, herunder Libretro og EmulatorJS.
    de_DE: EmulatorJS – Eine browserbasierte, portable Emulation für viele Retro-Konsolen, die auf nahezu jedem Gerät läuft. Dabei kommt eine Kombination aus Libretro und EmulatorJS zum Einsatz.
    el_GR: Emulatorjs - Σε πρόγραμμα περιήγησης ιστού, εξομοίωση που είναι φορητή σχεδόν σε οποιαδήποτε συσκευή για πολλές ρετρό κονσόλες. Χρησιμοποιείται ένας συνδυασμός εξομοιωτών, μεταξύ του Libretro και του EmulatorJS.
    en_GB: Emulatorjs - In browser web based emulation portable to nearly any device for many retro consoles. A mix of emulators is used between Libretro and Emulatorjs.
    es_ES: 'Emulatorjs: emulación web en navegador, portátil para casi cualquier dispositivo, para numerosas consolas retro. Se utiliza una combinación de emuladores, entre Libretro y EmulatorJS.'
    fr_FR: Emulatorjs est une émulation web fonctionnant dans un navigateur et compatible avec la quasi-totalité des appareils pour de nombreuses consoles rétro. Elle utilise une combinaison d'émulateurs, notamment Libretro et EmulatorJS.
    ga_IE: Emulatorjs - Aithris gréasáin sa bhrabhsálaí atá iniompartha chuig beagnach aon fheiste le haghaidh go leor consól seanré. Úsáidtear meascán d'aithriseoirí idir Libretro agus EmulatorJS.
    hr_HR: Emulatorjs - Emulacija u web pregledniku, prenosiva na gotovo svaki uređaj za mnoge retro konzole. Koristi se kombinacija emulatora između Libretra i EmulatorJS-a.
    hu_HU: Emulatorjs - Böngészőalapú, webes emuláció, amely szinte bármilyen eszközön hordozható, sok retró konzolhoz. A Libretro és az EmulatorJS emulátorok keverékét használják.
    it_IT: Emulatorjs - Emulazione web basata su browser, portatile su quasi tutti i dispositivi, per numerose console retrò. Viene utilizzato un mix di emulatori, tra cui Libretro ed EmulatorJS.
    ja_JP: EmulatorJSは、多くのレトロゲーム機に対応した、ブラウザベースのウェブベースエミュレーションソフトウェアで、ほぼすべてのデバイスで利用可能です。LibretroとEmulatorJSという2つのエミュレータが併用されています。
    ko_KR: EmulatorJS는 웹 기반 브라우저 에뮬레이션으로, 다양한 레트로 콘솔을 거의 모든 기기에서 에뮬레이션할 수 있습니다. Libretro와 EmulatorJS는 여러 에뮬레이터를 혼합하여 사용합니다.
    ml_IN: എമുലേറ്റർജെഎസ് - പല റെട്രോ കൺസോളുകൾക്കും ഏതാണ്ട് ഏത് ഉപകരണത്തിലേക്കും പോർട്ടബിൾ ചെയ്യാവുന്ന ബ്രൗസർ വെബ് അധിഷ്ഠിത എമുലേഷനിൽ. ലിബ്രെട്രോയ്ക്കും എമുലേറ്റർജെഎസിനും ഇടയിൽ എമുലേറ്ററുകളുടെ ഒരു മിശ്രിതം ഉപയോഗിക്കുന്നു.
    nb_NO: Emulatorjs – Nettbasert emulering i nettleseren som kan brukes til nesten alle enheter for mange retrokonsoller. En blanding av emulatorer brukes, Libretro og EmulatorJS.
    nl_NL: Emulatorjs - Webgebaseerde emulatie in de browser, overdraagbaar naar vrijwel elk apparaat voor veel retroconsoles. Er wordt gebruik gemaakt van een mix van emulators, waaronder Libretro en EmulatorJS.
    pl_PL: Emulatorjs – emulacja w przeglądarce, przenośna na niemal każde urządzenie dla wielu konsol retro. Libretro i EmulatorJS wykorzystują mieszankę emulatorów.
    pt_BR: EmulatorJS - Emulação baseada na web e executada diretamente no navegador, portátil para praticamente qualquer dispositivo, para diversos consoles retrô. Utiliza uma combinação de emuladores, incluindo Libretro e EmulatorJS.
    ro_RO: Emulatorjs - Emulare web în browser, portabilă pe aproape orice dispozitiv pentru multe console retro. Se folosește un mix de emulatoare între Libretro și EmulatorJS.
    ru_RU: Emulatorjs — это веб-эмуляция в браузере, переносимая практически на любое устройство, для многих ретро-консолей. Используется комбинация эмуляторов Libretro и EmulatorJS.
    sk_SK: Emulatorjs – Emulácia v prehliadači, prenosná na takmer akékoľvek zariadenie pre mnoho retro konzol. Používa sa kombinácia emulátorov Libretro a EmulatorJS.
    sv_SE: Emulatorjs - Webbaserad emulering i webbläsaren som kan användas på nästan vilken enhet som helst för många retrokonsoler. En blandning av emulatorer används, Libretro och EmulatorJS.
    tr_TR: Emulatorjs - Birçok retro oyun konsolu için neredeyse her cihaza taşınabilir, tarayıcı tabanlı web öykünmesi. Libretro ve EmulatorJS arasında bir karışım öykünme aracı kullanılır.
    zh_TW: EmulatorJS 提供基於瀏覽器的網頁模擬功能，幾乎可在任何裝置上執行多種復古遊戲主機。它混合使用 Libretro 和 EmulatorJS 的模擬器。
  tagline:
    en_US: 'In browser web based emulation portable to nearly any device for many retro consoles. A mix of emulators is used between Libretro and EmulatorJS. '
    zh_CN: 在浏览器中模拟多种复古游戏主机。
    ca_ES: Emulació basada en web en navegador, portable a gairebé qualsevol dispositiu per a moltes consoles retro. S'utilitza una barreja d'emuladors entre Libretro i EmulatorJS.
    cs_CZ: V prohlížeči je webová emulace přenosná na téměř jakékoli zařízení pro mnoho retro konzolí. Používá se kombinace emulátorů Libretro a EmulatorJS.
    da_DK: Webbaseret emulering i browseren, der kan bruges til næsten alle enheder til mange retro-konsoller. Der bruges en blanding af emulatorer, herunder Libretro og EmulatorJS.
    de_DE: Die webbasierte Emulation im Browser ist portabel und auf nahezu jedem Gerät für viele Retro-Konsolen nutzbar. Dabei kommt eine Kombination der Emulatoren Libretro und EmulatorJS zum Einsatz.
    el_GR: Σε πρόγραμμα περιήγησης ιστού, η εξομοίωση είναι φορητή σχεδόν σε οποιαδήποτε συσκευή για πολλές ρετρό κονσόλες. Χρησιμοποιείται ένας συνδυασμός εξομοιωτών, μεταξύ του Libretro και του EmulatorJS.
    en_GB: 'In browser web based emulation portable to nearly any device for many retro consoles. A mix of emulators is used between Libretro and Emulatorjs. '
    es_ES: La emulación basada en navegador web es portable a casi cualquier dispositivo para muchas consolas retro. Se utiliza una combinación de emuladores, entre ellos Libretro y EmulatorJS.
    fr_FR: Émulation web portable, accessible via navigateur, pour de nombreuses consoles rétro. Elle utilise une combinaison d'émulateurs, notamment Libretro et EmulatorJS.
    ga_IE: In aithris ghréasánbhunaithe i mbrabhsálaí atá iniompartha chuig beagnach aon fheiste le haghaidh go leor consól seanré. Úsáidtear meascán d'aithriseoirí idir Libretro agus EmulatorJS.
    hr_HR: U web-baziranoj emulaciji preglednika, prenosivoj na gotovo svaki uređaj za mnoge retro konzole. Koristi se kombinacija emulatora između Libretra i EmulatorJS-a.
    hu_HU: Böngésző alapú webes emuláció, amely szinte bármilyen eszközön hordozható, sok retró konzolhoz. A Libretro és az EmulatorJS emulátorok keverékét használják.
    it_IT: Emulazione web basata su browser, portatile su quasi tutti i dispositivi, per numerose console retrò. Viene utilizzato un mix di emulatori, tra cui Libretro ed EmulatorJS.
    ja_JP: ブラウザベースのウェブエミュレーションにより、多くのレトロゲーム機をほぼすべてのデバイスでプレイ可能です。LibretroとEmulatorJSという2種類のエミュレータが併用されています。
    ko_KR: 브라우저 기반 웹 에뮬레이션으로, 다양한 레트로 콘솔을 거의 모든 기기에서 실행할 수 있습니다. Libretro와 EmulatorJS를 비롯한 여러 에뮬레이터가 혼합되어 사용됩니다.
    ml_IN: ബ്രൗസർ വെബ് അധിഷ്ഠിത എമുലേഷനിൽ, പല റെട്രോ കൺസോളുകൾക്കും ഏതാണ്ട് ഏത് ഉപകരണത്തിലേക്കും പോർട്ടബിൾ ചെയ്യാം. ലിബ്രെട്രോയ്ക്കും എമുലേറ്റർജെഎസിനും ഇടയിൽ എമുലേറ്ററുകളുടെ ഒരു മിശ്രിതം ഉപയോഗിക്കുന്നു.
    nb_NO: Nettbasert emulering i nettlesere som er bærbar til nesten alle enheter for mange retrokonsoller. En blanding av emulatorer brukes, Libretro og EmulatorJS.
    nl_NL: In-browser webgebaseerde emulatie, draagbaar naar vrijwel elk apparaat voor veel retroconsoles. Er wordt gebruik gemaakt van een mix van emulators, waaronder Libretro en EmulatorJS.
    pl_PL: Emulacja oparta na przeglądarce, przenośna na niemal każde urządzenie dla wielu konsol retro. Libretro i EmulatorJS wykorzystują mieszankę emulatorów.
    pt_BR: Emulação baseada na web e portátil para praticamente qualquer dispositivo, compatível com diversos consoles retrô. Uma combinação de emuladores, incluindo Libretro e EmulatorJS, é utilizada.
    ro_RO: Emulare bazată pe web în browser, portabilă pe aproape orice dispozitiv pentru multe console retro. Se folosește un mix de emulatoare între Libretro și EmulatorJS.
    ru_RU: 'Веб-эмуляция в браузере, переносимая практически на любое устройство, для многих ретро-консолей. Используется комбинация эмуляторов: Libretro и EmulatorJS.'
    sk_SK: Emulácia webového prehliadača prenosná na takmer akékoľvek zariadenie pre mnoho retro konzol. Používa sa kombinácia emulátorov Libretro a EmulatorJS.
    sv_SE: Webbaserad emulering i webbläsare som är portabel till nästan vilken enhet som helst för många retrokonsoler. En blandning av emulatorer används, Libretro och EmulatorJS.
    tr_TR: Birçok retro oyun konsolu için, neredeyse her cihaza taşınabilir, tarayıcı tabanlı web öykünmesi. Libretro ve EmulatorJS arasında bir öykünme yazılımı karışımı kullanılır.
    zh_TW: 在瀏覽器中模擬多種復古遊戲主機。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/emulatorjs-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/emulatorjs-logo.png
  title:
    en_US: Emulatorjs
    zh_CN: Emulatorjs
    ca_ES: Emulatorjs
    cs_CZ: Emulatorjs
    da_DK: Emulatorjs
    de_DE: Emulatorjs
    el_GR: Emulatorjs
    en_GB: Emulatorjs
    es_ES: Emulatorjs
    fr_FR: Emulatorjs
    ga_IE: Emulatorjs
    hr_HR: Emulatorjs
    hu_HU: Emulatorjs
    it_IT: Emulatorjs
    ja_JP: Emulatorjs
    ko_KR: Emulatorjs
    ml_IN: Emulatorjs
    nb_NO: Emulatorjs
    nl_NL: Emulatorjs
    pl_PL: Emulatorjs
    pt_BR: Emulatorjs
    ro_RO: Emulatorjs
    ru_RU: Emulatorjs
    sk_SK: Emulatorjs
    sv_SE: Emulatorjs
    tr_TR: Emulatorjs
    zh_TW: Emulatorjs
  category: Others
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserveremulatorjs
  version: 1.9.2
