name: linuxserver-qemu-static
services:
  app:
    image: linuxserver/qemu-static:9.2.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/qemu-static/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: This container needs special attention. Please check https://hub.docker.com/r/linuxserver/qemu-static for details.
  tagline:
    en_us: This container needs special attention. Please check https://hub. Docker. Com/r/linuxserver/qemu-static for details.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qemu-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qemu-logo.png
  title:
    en_us: Qemu static
  category: LinuxServer.io
  port_map: '80'
