name: linuxserver-qemu-static
services:
  app:
    image: linuxserver/qemu-static:10.0.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /srv/lsio/qemu-static/config
        target: /config
x-casaos:
  architectures: []
  main: app
  description:
    en_us: This container needs special attention. Please check https://hub.docker.com/r/linuxserver/qemu-static for details.
  tagline:
    en_us: This container needs special attention. Please check https://hub. Docker. Com/r/linuxserver/qemu-static for details.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qemu-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qemu-logo.png
  title:
    en_us: Qemu static
  category: LinuxServer.io
  port_map: '80'
