name: linuxserver-feed2toot
services:
  app:
    image: linuxserver/feed2toot:0.17.20250110
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FEED_LIMIT: ''
    volumes:
      - type: bind
        source: /DATA/AppData/feed2toot/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfeed2toot/assets/icon.svg
  title:
    en_US: Feed2toot
    zh_CN: Feed2toot
    ca_ES: Feed2toot
    cs_CZ: Feed2toot
    da_DK: Feed2toot
    de_DE: Feed2toot
    el_GR: Feed2toot
    en_GB: Feed2toot
    es_ES: Feed2toot
    fr_FR: Feed2toot
    ga_IE: Feed2toot
    hr_HR: Feed2toot
    hu_HU: Feed2toot
    it_IT: Feed2toot
    ja_JP: Feed2toot
    ko_KR: Feed2toot
    ml_IN: Feed2toot
    nb_NO: Feed2toot
    nl_NL: Feed2toot
    pl_PL: Feed2toot
    pt_BR: Feed2toot
    ro_RO: Feed2toot
    ru_RU: Feed2toot
    sk_SK: Feed2toot
    sv_SE: Feed2toot
    tr_TR: Feed2toot
    zh_TW: Feed2toot
  id: wisdomsky.linuxserver.linuxserverfeed2toot
  version: 0.17.20250110
