name: linuxserver-feed2toot
services:
  app:
    image: linuxserver/feed2toot:0.17.20250110
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FEED_LIMIT: ''
    volumes:
      - type: bind
        source: /DATA/AppData/feed2toot/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfeed2toot/assets/icon.svg
  title:
    en_US: Feed2toot
    zh_CN: Feed2toot
  id: wisdomsky.linuxserver.linuxserverfeed2toot
  version: 0.17.20250110
