name: linuxserver-davos
services:
  app:
    image: linuxserver/davos:2.2.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/davos/config
        target: /config
      - type: bind
        source: /DATA/AppData/davos/download
        target: /download
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverdavos/assets/icon.png
  title:
    en_US: Davos (LinuxServer.io)
    ca_ES: Davos (LinuxServer.io)
    cs_CZ: Davos (LinuxServer.io)
    da_DK: Davos (LinuxServer.io)
    de_DE: Davos (LinuxServer.io)
    el_GR: Davos (LinuxServer.io)
    en_GB: Davos (LinuxServer.io)
    es_ES: Davos (LinuxServer.io)
    fr_FR: Davos (LinuxServer.io)
    ga_IE: Davos (LinuxServer.io)
    hr_HR: Davos (LinuxServer.io)
    hu_HU: Davos (LinuxServer.io)
    it_IT: Davos (LinuxServer.io)
    ja_JP: Davos (LinuxServer.io)
    ko_KR: Davos (LinuxServer.io)
    ml_IN: Davos (LinuxServer.io)
    nb_NO: Davos (LinuxServer.io)
    nl_NL: Davos (LinuxServer.io)
    pl_PL: Davos (LinuxServer.io)
    pt_BR: Davos (LinuxServer.io)
    ro_RO: Davos (LinuxServer.io)
    ru_RU: Davos (LinuxServer.io)
    sk_SK: Davos (LinuxServer.io)
    sv_SE: Davos (LinuxServer.io)
    tr_TR: Davos (LinuxServer.io)
    zh_CN: Davos（LinuxServer.io）
    zh_TW: Davos（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverdavos
  port_map: '8080'
  version: 2.2.2
