name: linuxserver-jackett
services:
  app:
    image: linuxserver/jackett:0.24.2605@sha256:61cfa7e07116e56b789b40adaf9b01dc5b80f5b47cbb290d7e5cd6f3030daa79
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      AUTO_UPDATE: ''
      RUN_OPTS: ''
    ports:
      - target: 9117
        published: 9117
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/jackett/config
        target: /config
      - type: bind
        source: /DATA/AppData/jackett/downloads
        target: /downloads
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverjackett/assets/icon.png
  title:
    en_US: Jackett (LinuxServer.io)
    ca_ES: Jackett (LinuxServer.io)
    cs_CZ: Jackett (LinuxServer.io)
    da_DK: Jackett (LinuxServer.io)
    de_DE: Jackett (LinuxServer.io)
    el_GR: Jackett (LinuxServer.io)
    en_GB: Jackett (LinuxServer.io)
    es_ES: Jackett (LinuxServer.io)
    fr_FR: Jackett (LinuxServer.io)
    ga_IE: Jackett (LinuxServer.io)
    hr_HR: Jackett (LinuxServer.io)
    hu_HU: Jackett (LinuxServer.io)
    it_IT: Jackett (LinuxServer.io)
    ja_JP: Jackett (LinuxServer.io)
    ko_KR: Jackett (LinuxServer.io)
    ml_IN: Jackett (LinuxServer.io)
    nb_NO: Jackett (LinuxServer.io)
    nl_NL: Jackett (LinuxServer.io)
    pl_PL: Jackett (LinuxServer.io)
    pt_BR: Jackett (LinuxServer.io)
    ro_RO: Jackett (LinuxServer.io)
    ru_RU: Jackett (LinuxServer.io)
    sk_SK: Jackett (LinuxServer.io)
    sv_SE: Jackett (LinuxServer.io)
    tr_TR: Jackett (LinuxServer.io)
    zh_CN: Jackett（LinuxServer.io）
    zh_TW: Jackett（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverjackett
  port_map: '9117'
  version: 0.24.2605
