name: linuxserver-kali-linux
services:
  app:
    image: linuxserver/kali-linux:version-45f3494e@sha256:622e2075f96477344ee4b71ac00922c43cf91b35c90797a81e85c1b04f881428
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kali-linux/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverkalilinux/assets/icon.png
  title:
    en_US: Kali linux (LinuxServer.io)
    ca_ES: Kali linux (LinuxServer.io)
    cs_CZ: Kali linux (LinuxServer.io)
    da_DK: Kali linux (LinuxServer.io)
    de_DE: Kali linux (LinuxServer.io)
    el_GR: Kali linux (LinuxServer.io)
    en_GB: Kali linux (LinuxServer.io)
    es_ES: Kali linux (LinuxServer.io)
    fr_FR: Kali linux (LinuxServer.io)
    ga_IE: Kali linux (LinuxServer.io)
    hr_HR: Kali linux (LinuxServer.io)
    hu_HU: Kali linux (LinuxServer.io)
    it_IT: Kali linux (LinuxServer.io)
    ja_JP: Kali linux (LinuxServer.io)
    ko_KR: Kali linux (LinuxServer.io)
    ml_IN: Kali linux (LinuxServer.io)
    nb_NO: Kali linux (LinuxServer.io)
    nl_NL: Kali linux (LinuxServer.io)
    pl_PL: Kali linux (LinuxServer.io)
    pt_BR: Kali linux (LinuxServer.io)
    ro_RO: Kali linux (LinuxServer.io)
    ru_RU: Kali linux (LinuxServer.io)
    sk_SK: Kali linux (LinuxServer.io)
    sv_SE: Kali linux (LinuxServer.io)
    tr_TR: Kali linux (LinuxServer.io)
    zh_CN: Kali linux（LinuxServer.io）
    zh_TW: Kali linux（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverkalilinux
  port_map: '3000'
  version: version-45f3494e
