name: linuxserver-oscam
services:
  app:
    image: linuxserver/oscam:version-11966@sha256:c64c772731470c316f4ae9eebe65ae6ac81c10f8a9b3d5d68df253f78305c822
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/oscam/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveroscam/assets/icon.png
  title:
    en_US: Oscam (LinuxServer.io)
    ca_ES: Oscam (LinuxServer.io)
    cs_CZ: Oscam (LinuxServer.io)
    da_DK: Oscam (LinuxServer.io)
    de_DE: Oscam (LinuxServer.io)
    el_GR: Oscam (LinuxServer.io)
    en_GB: Oscam (LinuxServer.io)
    es_ES: Oscam (LinuxServer.io)
    fr_FR: Oscam (LinuxServer.io)
    ga_IE: Oscam (LinuxServer.io)
    hr_HR: Oscam (LinuxServer.io)
    hu_HU: Oscam (LinuxServer.io)
    it_IT: Oscam (LinuxServer.io)
    ja_JP: Oscam (LinuxServer.io)
    ko_KR: Oscam (LinuxServer.io)
    ml_IN: Oscam (LinuxServer.io)
    nb_NO: Oscam (LinuxServer.io)
    nl_NL: Oscam (LinuxServer.io)
    pl_PL: Oscam (LinuxServer.io)
    pt_BR: Oscam (LinuxServer.io)
    ro_RO: Oscam (LinuxServer.io)
    ru_RU: Oscam (LinuxServer.io)
    sk_SK: Oscam (LinuxServer.io)
    sv_SE: Oscam (LinuxServer.io)
    tr_TR: Oscam (LinuxServer.io)
    zh_CN: Oscam（LinuxServer.io）
    zh_TW: Oscam（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserveroscam
  port_map: '8888'
  version: version-11966
