name: linuxserver-steamos
services:
  app:
    image: linuxserver/steamos:version-2024-12-20
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DRINODE: ''
      HOST_IP: ''
      STARTUP: ''
      RESOLUTION: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: DRINODE
          description:
            en_US: Specify the render device (GPU) for the contianer to use.
        - container: HOST_IP
          description:
            en_US: Specify the IP of the host, needed for LAN Remote Play.
        - container: STARTUP
          description:
            en_US: KDE to boot into desktop mode, BIGPICTURE to boot into gamescope.
        - container: RESOLUTION
          description:
            en_US: When booting into BIGPICTURE mode the screen resolution will be bound to this value.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/steamos/config
        target: /config
      - type: bind
        source: /dev/input
        target: /dev/input
      - type: bind
        source: /run/udev/data
        target: /run/udev/data
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_US: SteamOS is an Arch based Linux distribution made by Valve Software. This container is a vanilla Arch install with Steam repositories added for software support. This container will only work with modern AMD/Intel GPUs on a real Linux Host
    zh_CN: SteamOS 是 Valve Software 开发的基于 Arch 的 Linux 发行版。此容器提供原生 Arch 安装，并加入 Steam 软件仓库以支持相关软件。它仅能在配备现代 AMD 或 Intel GPU 的真实 Linux 主机上运行。
  tagline:
    en_US: An Arch based Linux distribution made by Valve Software. This container is a vanilla Arch install with Steam repositories added for software support. This container will only work with modern AMD/Intel GPUs on a real Linux Host
    zh_CN: 带有 Steam 软件仓库的 Arch Linux 容器。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/steamos-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/steamos-logo.png
  title:
    en_US: Steamos
    zh_CN: Steamos
  category: Others
  id: wisdomsky.linuxserver.linuxserversteamos
  version: version-2024-12-20
