name: linuxserver-daapd
services:
  app:
    image: linuxserver/daapd:28.10.20250108@sha256:af8db55aa52f5fc46f3364883a3b9d11b2314be8020811e01c8d6cd035a722e3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/daapd/config
        target: /config
      - type: bind
        source: /DATA/AppData/daapd/music
        target: /music
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverdaapd/assets/icon.png
  title:
    en_US: Daapd
    zh_CN: Daapd
  port_map: '3689'
  id: wisdomsky.linuxserver.linuxserverdaapd
  version: 28.10.20250108
