name: linuxserver-kasm
services:
  app:
    image: linuxserver/kasm:1.19.0
    restart: unless-stopped
    environment:
      KASM_PORT: ''
      DOCKER_HUB_USERNAME: ''
      DOCKER_HUB_PASSWORD: ''
      DOCKER_MTU: ''
    x-casaos:
      envs:
        - container: KASM_PORT
          description:
            en_US: Specify the port you bind to the outside for Kasm Workspaces.
        - container: DOCKER_HUB_USERNAME
          description:
            en_US: Optionally specify a DockerHub Username to pull private images. [OPTIONAL]
        - container: DOCKER_HUB_PASSWORD
          description:
            en_US: Optionally specify a DockerHub password to pull private images. [OPTIONAL]
        - container: DOCKER_MTU
          description:
            en_US: Optionally specify the mtu options passed to dockerd. [OPTIONAL]
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kasm/opt
        target: /opt
      - type: bind
        source: /DATA/AppData/kasm/profiles
        target: /profiles
      - type: bind
        source: /dev/input
        target: /dev/input
      - type: bind
        source: /run/udev/data
        target: /run/udev/data
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Kasm Workspaces is a docker container streaming platform for delivering browser-based access to desktops, applications, and web services. Kasm uses devops-enabled Containerized Desktop Infrastructure (CDI) to create on-demand, disposable, docker containers that are accessible via web browser. Example use-cases include Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS), and Open Source Intelligence (OSINT) collections. The rendering of the graphical-based containers is powered by the open-source project KasmVNC.
    ca_ES: Kasm Workspaces és una plataforma de streaming de contenidors Docker per oferir accés basat en navegador a escriptoris, aplicacions i serveis web. Kasm utilitza una infraestructura d'escriptori en contenidors (CDI) habilitada per Devops per crear contenidors Docker d'un sol ús i a demanda accessibles mitjançant un navegador web. Alguns exemples de casos d'ús inclouen l'aïllament remot del navegador (RBI), la prevenció de pèrdua de dades (DLP), l'escriptori com a servei (DaaS), els serveis d'accés remot segur (RAS) i les col·leccions d'intel·ligència de codi obert (OSINT). La renderització dels contenidors basats en gràfics funciona amb el projecte de codi obert KasmVNC.
    cs_CZ: Kasm Workspaces je platforma pro streamování kontejnerů Docker, která poskytuje přístup k desktopům, aplikacím a webovým službám z prohlížeče. Kasm využívá infrastrukturu kontejnerizovaných desktopů (CDI) s podporou devops k vytváření kontejnerů Docker na vyžádání, které jsou přístupné prostřednictvím webového prohlížeče. Mezi příklady použití patří vzdálená izolace prohlížeče (RBI), prevence ztráty dat (DLP), desktop jako služba (DaaS), zabezpečené služby vzdáleného přístupu (RAS) a kolekce Open Source Intelligence (OSINT). Vykreslování grafických kontejnerů je poháněno open-source projektem KasmVNC.
    da_DK: Kasm Workspaces er en docker-container-streamingplatform til levering af browserbaseret adgang til desktops, applikationer og webtjenester. Kasm bruger devops-aktiveret Containerized Desktop Infrastructure (CDI) til at oprette on-demand, engangs-docker-containere, der er tilgængelige via webbrowser. Eksempler på use-cases inkluderer Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) og Open Source Intelligence (OSINT) samlinger. Renderingen af de grafisk baserede containere drives af open source-projektet KasmVNC.
    de_DE: Kasm Workspaces ist eine Docker-Container-Streaming-Plattform für den browserbasierten Zugriff auf Desktops, Anwendungen und Webdienste. Kasm nutzt DevOps-fähige Containerized Desktop Infrastructure (CDI), um bedarfsgesteuerte, temporäre Docker-Container zu erstellen, die über einen Webbrowser zugänglich sind. Anwendungsbeispiele sind Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) und Open Source Intelligence (OSINT). Die Darstellung der grafischen Container basiert auf dem Open-Source-Projekt KasmVNC.
    el_GR: Το Kasm Workspaces είναι μια πλατφόρμα ροής docker container για την παροχή πρόσβασης μέσω προγράμματος περιήγησης σε επιτραπέζιους υπολογιστές, εφαρμογές και υπηρεσίες ιστού. Το Kasm χρησιμοποιεί Containerized Desktop Infrastructure (CDI) με δυνατότητα devops για τη δημιουργία docker containers κατ' απαίτηση, μιας χρήσης, τα οποία είναι προσβάσιμα μέσω προγράμματος περιήγησης ιστού. Παραδείγματα περιπτώσεων χρήσης περιλαμβάνουν την Απομόνωση Απομακρυσμένου Περιηγητή (RBI), την Πρόληψη Απώλειας Δεδομένων (DLP), την Επιφάνεια Εργασίας ως Υπηρεσία (DaaS), τις Υπηρεσίες Ασφαλούς Απομακρυσμένης Πρόσβασης (RAS) και τις συλλογές Ανοικτού Κώδικα Ευφυΐας (OSINT). Η απόδοση των γραφικών containers υποστηρίζεται από το έργο ανοιχτού κώδικα KasmVNC.
    en_GB: Kasm Workspaces is a docker container streaming platform for delivering browser-based access to desktops, applications, and web services. Kasm uses devops-enabled Containerized Desktop Infrastructure (Cdi) to create on-demand, disposable, docker containers that are accessible via web browser. Example use-cases include Remote Browser Isolation (Rbi), Data Loss Prevention (Dlp), Desktop as a Service (Daas), Secure Remote Access Services (Ras), and Open Source Intelligence (Osint) collections. The rendering of the graphical-based containers is powered by the open-source project Kasmvnc.
    es_ES: Kasm Workspaces es una plataforma de transmisión de contenedores Docker que ofrece acceso basado en navegador a escritorios, aplicaciones y servicios web. Kasm utiliza la infraestructura de escritorio en contenedores (CDI) con soporte para DevOps para crear contenedores Docker desechables bajo demanda, accesibles a través del navegador web. Algunos ejemplos de casos de uso incluyen el aislamiento remoto del navegador (RBI), la prevención de pérdida de datos (DLP), el escritorio como servicio (DaaS), los servicios de acceso remoto seguro (RAS) y la recopilación de inteligencia de fuentes abiertas (OSINT). La representación gráfica de los contenedores se realiza mediante el proyecto de código abierto KasmVNC.
    fr_FR: Kasm Workspaces est une plateforme de streaming de conteneurs Docker permettant d'accéder, via un navigateur, à des bureaux, des applications et des services web. Kasm utilise une infrastructure de bureau conteneurisée (CDI) compatible DevOps pour créer des conteneurs Docker éphémères et à la demande, accessibles par navigateur web. Parmi les cas d'utilisation, citons l'isolation du navigateur à distance (RBI), la prévention des pertes de données (DLP), le bureau en tant que service (DaaS), les services d'accès distant sécurisés (RAS) et la collecte de renseignements en sources ouvertes (OSINT). L'affichage des conteneurs graphiques est assuré par le projet open source KasmVNC.
    ga_IE: Is ardán sruthú coimeádán docker é Kasm Workspaces chun rochtain bhrabhsálaí-bhunaithe a sholáthar ar dheasca, feidhmchláir agus seirbhísí gréasáin. Úsáideann Kasm Bonneagar Deisce Coimeádánaithe (CDI) atá cumasaithe ag devops chun coimeádáin docker indiúscartha ar éileamh a chruthú atá inrochtana trí bhrabhsálaí gréasáin. I measc na gcásanna úsáide samplacha tá Leithlisiú Brabhsálaí Cianda (RBI), Cosc ar Chaillteanas Sonraí (DLP), Deasc mar Sheirbhís (DaaS), Seirbhísí Rochtana Cianda Slán (RAS), agus bailiúcháin Faisnéise Foinse Oscailte (OSINT). Tá rindreáil na gcoimeádán grafach-bhunaithe faoi thiomáint ag an tionscadal foinse oscailte KasmVNC.
    hr_HR: Kasm Workspaces je platforma za streaming docker kontejnera za pružanje pristupa radnim površinama, aplikacijama i web uslugama putem preglednika. Kasm koristi infrastrukturu kontejneriziranih radnih površina (CDI) s omogućenim devopsom za stvaranje docker kontejnera na zahtjev, dostupnih putem web preglednika. Primjeri upotrebe uključuju izolaciju udaljenog preglednika (RBI), sprječavanje gubitka podataka (DLP), radnu površinu kao uslugu (DaaS), sigurne usluge udaljenog pristupa (RAS) i kolekcije obavještajnih podataka otvorenog koda (OSINT). Renderiranje grafički temeljenih kontejnera pokreće projekt otvorenog koda KasmVNC.
    hu_HU: A Kasm Workspaces egy docker konténer streamelési platform, amely böngészőalapú hozzáférést biztosít asztali számítógépekhez, alkalmazásokhoz és webszolgáltatásokhoz. A Kasm devops-kompatibilis konténerizált asztali infrastruktúrát (CDI) használ igény szerinti, eldobható, webböngészőn keresztül elérhető docker konténerek létrehozásához. Példaként említhetők a távoli böngészőizoláció (RBI), az adatvesztés-megelőzés (DLP), a szolgáltatásként nyújtott asztali környezet (DaaS), a biztonságos távoli hozzáférési szolgáltatások (RAS) és a nyílt forráskódú intelligencia (OSINT) gyűjtemények. A grafikus alapú konténerek renderelését a KasmVNC nyílt forráskódú projekt biztosítja.
    it_IT: Kasm Workspaces è una piattaforma di streaming di container Docker che offre accesso tramite browser a desktop, applicazioni e servizi web. Kasm utilizza l'infrastruttura desktop containerizzata (CDI) abilitata per il DevOps per creare container Docker on-demand e temporanei, accessibili tramite browser web. Esempi di casi d'uso includono l'isolamento remoto del browser (RBI), la prevenzione della perdita di dati (DLP), il Desktop as a Service (DaaS), i servizi di accesso remoto sicuro (RAS) e la raccolta di informazioni da fonti aperte (OSINT). Il rendering dei container grafici è gestito dal progetto open source KasmVNC.
    ja_JP: Kasm Workspacesは、デスクトップ、アプリケーション、Webサービスへのブラウザベースのアクセスを提供するDockerコンテナストリーミングプラットフォームです。Kasmは、DevOps対応のコンテナ化デスクトップインフラストラクチャ（CDI）を使用して、Webブラウザ経由でアクセス可能なオンデマンドの使い捨てDockerコンテナを作成します。使用例としては、リモートブラウザ分離（RBI）、データ損失防止（DLP）、デスクトップ・アズ・ア・サービス（DaaS）、セキュアリモートアクセスサービス（RAS）、オープンソースインテリジェンス（OSINT）の収集などが挙げられます。グラフィカルコンテナのレンダリングは、オープンソースプロジェクトKasmVNCによって実現されています。
    ko_KR: Kasm Workspaces는 데스크톱, 애플리케이션 및 웹 서비스에 브라우저 기반으로 접근할 수 있도록 지원하는 Docker 컨테이너 스트리밍 플랫폼입니다. Kasm은 DevOps 기반의 컨테이너화된 데스크톱 인프라(CDI)를 사용하여 웹 브라우저를 통해 접근 가능한 온디맨드 방식의 일회용 Docker 컨테이너를 생성합니다. 활용 사례로는 원격 브라우저 격리(RBI), 데이터 손실 방지(DLP), 서비스형 데스크톱(DaaS), 보안 원격 접근 서비스(RAS), 오픈 소스 인텔리전스(OSINT) 수집 등이 있습니다. 그래픽 기반 컨테이너의 렌더링은 오픈 소스 프로젝트인 KasmVNC를 통해 구현됩니다.
    ml_IN: ഡെസ്‌ക്‌ടോപ്പുകൾ, ആപ്ലിക്കേഷനുകൾ, വെബ് സേവനങ്ങൾ എന്നിവയിലേക്ക് ബ്രൗസർ അധിഷ്ഠിത ആക്‌സസ് നൽകുന്നതിനുള്ള ഒരു ഡോക്കർ കണ്ടെയ്‌നർ സ്ട്രീമിംഗ് പ്ലാറ്റ്‌ഫോമാണ് കാസ്മ് വർക്ക്‌സ്‌പെയ്‌സസ്. വെബ് ബ്രൗസർ വഴി ആക്‌സസ് ചെയ്യാവുന്ന ഓൺ-ഡിമാൻഡ്, ഡിസ്‌പോസിബിൾ, ഡോക്കർ കണ്ടെയ്‌നറുകൾ സൃഷ്ടിക്കാൻ കാസ്മ് ഡെവോപ്‌സ്-എനേബിൾഡ് കണ്ടെയ്‌നറൈസ്ഡ് ഡെസ്‌ക്‌ടോപ്പ് ഇൻഫ്രാസ്ട്രക്ചർ (സിഡിഐ) ഉപയോഗിക്കുന്നു. റിമോട്ട് ബ്രൗസർ ഐസൊലേഷൻ (ആർ‌ബി‌ഐ), ഡാറ്റ ലോസ് പ്രിവൻഷൻ (ഡി‌എൽ‌പി), ഡെസ്‌ക്‌ടോപ്പ് ആസ് എ സർവീസ് (ഡി‌എ‌എ‌എസ്), സെക്യുർ റിമോട്ട് ആക്‌സസ് സർവീസസ് (ആർ‌എ‌എസ്), ഓപ്പൺ സോഴ്‌സ് ഇന്റലിജൻസ് (ഒ‌എസ്‌ഐ‌എൻ‌ടി) ശേഖരണങ്ങൾ എന്നിവ ഉദാഹരണ ഉപയോഗ കേസുകളിൽ ഉൾപ്പെടുന്നു. ഗ്രാഫിക്കൽ അധിഷ്ഠിത കണ്ടെയ്‌നറുകളുടെ റെൻഡറിംഗ് ഓപ്പൺ സോഴ്‌സ് പ്രോജക്റ്റ് കാസ്മ്‌വി‌എൻ‌സി ഉപയോഗിച്ചാണ് നടത്തുന്നത്.
    nb_NO: Kasm Workspaces er en plattform for strømming av docker-containere for å levere nettleserbasert tilgang til skrivebord, applikasjoner og webtjenester. Kasm bruker devops-aktivert Containerized Desktop Infrastructure (CDI) for å lage engangs-docker-containere på forespørsel som er tilgjengelige via nettleser. Eksempler på brukstilfeller inkluderer Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) og Open Source Intelligence (OSINT)-samlinger. Gjengivelsen av de grafikkbaserte containerne drives av åpen kildekode-prosjektet KasmVNC.
    nl_NL: Kasm Workspaces is een platform voor het streamen van Docker-containers waarmee via de browser toegang kan worden verkregen tot desktops, applicaties en webdiensten. Kasm maakt gebruik van de DevOps-compatibele Containerized Desktop Infrastructure (CDI) om on-demand, tijdelijke Docker-containers te creëren die toegankelijk zijn via een webbrowser. Voorbeelden van toepassingen zijn Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) en Open Source Intelligence (OSINT)-verzamelingen. De grafische weergave van de containers wordt mogelijk gemaakt door het open-sourceproject KasmVNC.
    pl_PL: Kasm Workspaces to platforma strumieniowego przesyłania kontenerów Docker, która zapewnia dostęp do pulpitów, aplikacji i usług sieciowych za pośrednictwem przeglądarki. Kasm wykorzystuje infrastrukturę CDI (Containerized Desktop Infrastructure) z obsługą DevOps do tworzenia kontenerów Docker na żądanie i do jednorazowego użytku, dostępnych za pośrednictwem przeglądarki internetowej. Przykładowe zastosowania obejmują izolację przeglądarki zdalnej (RBI), zapobieganie utracie danych (DLP), pulpit jako usługę (DaaS), usługi bezpiecznego dostępu zdalnego (RAS) oraz kolekcje Open Source Intelligence (OSINT). Renderowanie graficznych kontenerów jest obsługiwane przez projekt open source KasmVNC.
    pt_BR: O Kasm Workspaces é uma plataforma de streaming de contêineres Docker para fornecer acesso baseado em navegador a desktops, aplicativos e serviços web. O Kasm utiliza Infraestrutura de Desktop Contêinerizada (CDI) habilitada para DevOps para criar contêineres Docker descartáveis e sob demanda, acessíveis via navegador web. Exemplos de casos de uso incluem Isolamento Remoto de Navegador (RBI), Prevenção de Perda de Dados (DLP), Desktop como Serviço (DaaS), Serviços de Acesso Remoto Seguro (RAS) e coleta de Inteligência de Fontes Abertas (OSINT). A renderização dos contêineres com interface gráfica é feita pelo projeto de código aberto KasmVNC.
    ro_RO: Kasm Workspaces este o platformă de streaming pentru containere docker, care oferă acces bazat pe browser la desktopuri, aplicații și servicii web. Kasm utilizează Containerized Desktop Infrastructure (CDI) activată pentru Devops pentru a crea containere docker la cerere, de unică folosință, accesibile prin browser web. Exemple de cazuri de utilizare includ Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) și colecții Open Source Intelligence (OSINT). Randarea containerelor bazate pe grafică este susținută de proiectul open-source KasmVNC.
    ru_RU: Kasm Workspaces — это платформа потоковой передачи контейнеров Docker, обеспечивающая доступ к рабочим столам, приложениям и веб-сервисам через браузер. Kasm использует инфраструктуру контейнеризированных рабочих столов (CDI) с поддержкой DevOps для создания по запросу одноразовых контейнеров Docker, доступных через веб-браузер. Примеры использования включают изоляцию удаленного браузера (RBI), предотвращение потери данных (DLP), рабочий стол как услуга (DaaS), безопасные службы удаленного доступа (RAS) и сбор разведывательной информации из открытых источников (OSINT). Рендеринг графических контейнеров осуществляется с помощью проекта с открытым исходным кодом KasmVNC.
    sk_SK: Kasm Workspaces je platforma na streamovanie docker kontajnerov, ktorá poskytuje prístup k desktopom, aplikáciám a webovým službám prostredníctvom prehliadača. Kasm využíva infraštruktúru kontajnerizovaných desktopov (CDI) s podporou devops na vytváranie jednorazových docker kontajnerov na požiadanie, ktoré sú prístupné prostredníctvom webového prehliadača. Medzi príklady použitia patrí izolácia vzdialeného prehliadača (RBI), prevencia straty údajov (DLP), desktop ako služba (DaaS), služby zabezpečeného vzdialeného prístupu (RAS) a kolekcie open source inteligencie (OSINT). Vykresľovanie grafických kontajnerov je poháňané open source projektom KasmVNC.
    sv_SE: Kasm Workspaces är en plattform för streaming av dockercontainrar för att leverera webbläsarbaserad åtkomst till skrivbord, applikationer och webbtjänster. Kasm använder devops-aktiverad Containerized Desktop Infrastructure (CDI) för att skapa on-demand, engångs-, dockercontainrar som är åtkomliga via webbläsare. Exempel på användningsfall inkluderar Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) och Open Source Intelligence (OSINT)-samlingar. Renderingen av de grafikbaserade containrarna drivs av öppen källkodsprojektet KasmVNC.
    tr_TR: Kasm Workspaces, masaüstlerine, uygulamalara ve web hizmetlerine tarayıcı tabanlı erişim sağlayan bir Docker konteyner akış platformudur. Kasm, isteğe bağlı, tek kullanımlık ve web tarayıcısı üzerinden erişilebilen Docker konteynerleri oluşturmak için DevOps özellikli Konteynerleştirilmiş Masaüstü Altyapısı (CDI) kullanır. Örnek kullanım alanları arasında Uzaktan Tarayıcı İzolasyonu (RBI), Veri Kaybı Önleme (DLP), Hizmet Olarak Masaüstü (DaaS), Güvenli Uzaktan Erişim Hizmetleri (RAS) ve Açık Kaynak İstihbaratı (OSINT) toplama yer almaktadır. Grafik tabanlı konteynerlerin görüntülenmesi, açık kaynak kodlu KasmVNC projesi tarafından desteklenmektedir.
    zh_CN: Kasm Workspaces 是一个 Docker 容器串流平台，可通过浏览器访问桌面、应用和网页服务。它使用支持 DevOps 的容器化桌面基础设施（CDI），按需创建可通过浏览器访问的一次性 Docker 容器。使用场景包括远程浏览器隔离（RBI）、数据防泄漏（DLP）、桌面即服务（DaaS）、安全远程访问服务（RAS）以及开源情报（OSINT）收集。图形容器的渲染由开源项目 KasmVNC 提供支持。
    zh_TW: Kasm Workspaces 是一個 Docker 容器串流平臺，可透過瀏覽器訪問桌面、應用和網頁服務。它使用支援 DevOps 的容器化桌面基礎設施（CDI），按需建立可透過瀏覽器訪問的一次性 Docker 容器。使用場景包括遠端瀏覽器隔離（RBI）、資料防洩漏（DLP）、桌面即服務（DaaS）、安全遠端訪問服務（RAS）以及開源情報（OSINT）收集。圖形容器的渲染由開源專案 KasmVNC 提供支援。
  tagline:
    en_US: Workspaces is a docker container streaming platform for delivering browser-based access to desktops, applications, and web services. Kasm uses devops-enabled Containerized Desktop Infrastructure (CDI) to create on-demand, disposable, docker containers that are accessible via web browser. Example use-cases include Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS), and Open Source Intelligence (OSINT) collections. The rendering of the graphical-based containers is powered by the open-source project KasmVNC.
    ca_ES: Workspaces és una plataforma de streaming de contenidors Docker per oferir accés basat en navegador a escriptoris, aplicacions i serveis web. Kasm utilitza Containerized Desktop Infrastructure (CDI) habilitada per Devops per crear contenidors Docker d'un sol ús i a demanda accessibles mitjançant un navegador web. Exemples de casos d'ús inclouen Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) i col·leccions Open Source Intelligence (OSINT). La renderització dels contenidors basats en gràfics funciona amb el projecte de codi obert KasmVNC.
    cs_CZ: Workspaces je platforma pro streamování kontejnerů Docker, která poskytuje přístup k desktopům, aplikacím a webovým službám z prohlížeče. Kasm využívá infrastrukturu kontejnerizovaných desktopů (CDI) s podporou devops k vytváření kontejnerů Docker na vyžádání, které jsou přístupné prostřednictvím webového prohlížeče. Mezi příklady použití patří vzdálená izolace prohlížeče (RBI), prevence ztráty dat (DLP), desktop jako služba (DaaS), zabezpečené služby vzdáleného přístupu (RAS) a kolekce Open Source Intelligence (OSINT). Vykreslování grafických kontejnerů je poháněno open-source projektem KasmVNC.
    da_DK: Workspaces er en docker-container-streamingplatform til levering af browserbaseret adgang til desktops, applikationer og webtjenester. Kasm bruger devops-aktiveret Containerized Desktop Infrastructure (CDI) til at oprette on-demand, engangs-docker-containere, der er tilgængelige via webbrowser. Eksempler på use-cases inkluderer Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) og Open Source Intelligence (OSINT) samlinger. Renderingen af de grafisk baserede containere drives af open source-projektet KasmVNC.
    de_DE: Workspaces ist eine Docker-Container-Streaming-Plattform für den browserbasierten Zugriff auf Desktops, Anwendungen und Webdienste. Kasm nutzt DevOps-fähige Containerized Desktop Infrastructure (CDI), um bedarfsgesteuerte, temporäre Docker-Container zu erstellen, die über einen Webbrowser zugänglich sind. Anwendungsbeispiele sind Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) und Open Source Intelligence (OSINT). Die Darstellung der grafischen Container basiert auf dem Open-Source-Projekt KasmVNC.
    el_GR: Το Workspaces είναι μια πλατφόρμα ροής docker container για την παροχή πρόσβασης μέσω προγράμματος περιήγησης σε επιτραπέζιους υπολογιστές, εφαρμογές και υπηρεσίες ιστού. Το Kasm χρησιμοποιεί Containerized Desktop Infrastructure (CDI) με δυνατότητα devops για τη δημιουργία docker containers κατ' απαίτηση, μιας χρήσης, τα οποία είναι προσβάσιμα μέσω προγράμματος περιήγησης ιστού. Παραδείγματα περιπτώσεων χρήσης περιλαμβάνουν την Απομόνωση Απομακρυσμένου Περιηγητή (RBI), την Πρόληψη Απώλειας Δεδομένων (DLP), την Επιφάνεια Εργασίας ως Υπηρεσία (DaaS), τις Υπηρεσίες Ασφαλούς Απομακρυσμένης Πρόσβασης (RAS) και τις συλλογές Ανοικτού Κώδικα Ευφυΐας (OSINT). Η απόδοση των γραφικών containers υποστηρίζεται από το έργο ανοιχτού κώδικα KasmVNC.
    en_GB: Workspaces is a docker container streaming platform for delivering browser-based access to desktops, applications, and web services. Kasm uses devops-enabled Containerized Desktop Infrastructure (Cdi) to create on-demand, disposable, docker containers that are accessible via web browser. Example use-cases include Remote Browser Isolation (Rbi), Data Loss Prevention (Dlp), Desktop as a Service (Daas), Secure Remote Access Services (Ras), and Open Source Intelligence (Osint) collections. The rendering of the graphical-based containers is powered by the open-source project Kasmvnc.
    es_ES: Workspaces es una plataforma de transmisión de contenedores Docker que ofrece acceso basado en navegador a escritorios, aplicaciones y servicios web. Kasm utiliza la infraestructura de escritorio en contenedores (CDI) con soporte para DevOps para crear contenedores Docker desechables bajo demanda, accesibles a través del navegador web. Algunos ejemplos de casos de uso incluyen el aislamiento remoto del navegador (RBI), la prevención de pérdida de datos (DLP), el escritorio como servicio (DaaS), los servicios de acceso remoto seguro (RAS) y la recopilación de inteligencia de fuentes abiertas (OSINT). La representación gráfica de los contenedores se realiza mediante el proyecto de código abierto KasmVNC.
    fr_FR: Workspaces est une plateforme de streaming de conteneurs Docker permettant d'accéder, via un navigateur, à des bureaux, des applications et des services web. Kasm utilise une infrastructure de bureau conteneurisée (CDI) compatible DevOps pour créer des conteneurs Docker éphémères et à la demande, accessibles par navigateur web. Parmi les cas d'utilisation, citons l'isolation du navigateur distant (RBI), la prévention des pertes de données (DLP), le bureau en tant que service (DaaS), les services d'accès distant sécurisés (RAS) et la collecte de renseignements en sources ouvertes (OSINT). L'affichage des conteneurs graphiques est assuré par le projet open source KasmVNC.
    ga_IE: Is ardán sruthú coimeádán docker é Workspaces chun rochtain bhrabhsálaí-bhunaithe a sholáthar ar dheasca, feidhmchláir agus seirbhísí gréasáin. Úsáideann Kasm Bonneagar Deisce Coimeádánaithe (CDI) atá cumasaithe ag devops chun coimeádáin docker indiúscartha ar éileamh a chruthú atá inrochtana trí bhrabhsálaí gréasáin. I measc na gcásanna úsáide samplacha tá Leithlisiú Brabhsálaí Cianda (RBI), Cosc ar Chaillteanas Sonraí (DLP), Deasc mar Sheirbhís (DaaS), Seirbhísí Rochtana Cianda Slán (RAS), agus bailiúcháin Faisnéise Foinse Oscailte (OSINT). Tá rindreáil na gcoimeádán grafach-bhunaithe faoi thiomáint ag an tionscadal foinse oscailte KasmVNC.
    hr_HR: Workspaces je platforma za streaming Docker kontejnera za pružanje pristupa radnim površinama, aplikacijama i web uslugama putem preglednika. Kasm koristi infrastrukturu kontejneriziranih radnih površina (CDI) s omogućenim devopsom za stvaranje Docker kontejnera na zahtjev, dostupnih putem web preglednika. Primjeri upotrebe uključuju izolaciju udaljenog preglednika (RBI), sprječavanje gubitka podataka (DLP), radnu površinu kao uslugu (DaaS), sigurne usluge udaljenog pristupa (RAS) i kolekcije obavještajnih podataka otvorenog koda (OSINT). Renderiranje grafički temeljenih kontejnera pokreće projekt otvorenog koda KasmVNC.
    hu_HU: A Workspaces egy docker konténer streamelési platform, amely böngészőalapú hozzáférést biztosít asztali számítógépekhez, alkalmazásokhoz és webszolgáltatásokhoz. A Kasm devops-kompatibilis konténerizált asztali infrastruktúrát (CDI) használ igény szerinti, eldobható, webböngészőn keresztül elérhető docker konténerek létrehozásához. Példaként említhetők a távoli böngészőizoláció (RBI), az adatvesztés-megelőzés (DLP), a szolgáltatásként nyújtott asztal (DaaS), a biztonságos távoli hozzáférési szolgáltatások (RAS) és a nyílt forráskódú intelligencia (OSINT) gyűjtemények. A grafikus alapú konténerek renderelését a KasmVNC nyílt forráskódú projekt biztosítja.
    it_IT: Workspaces è una piattaforma di streaming di container Docker che offre accesso tramite browser a desktop, applicazioni e servizi web. Kasm utilizza l'infrastruttura desktop containerizzata (CDI) abilitata per il DevOps per creare container Docker on-demand e temporanei, accessibili tramite browser web. Esempi di casi d'uso includono l'isolamento remoto del browser (RBI), la prevenzione della perdita di dati (DLP), il Desktop as a Service (DaaS), i servizi di accesso remoto sicuro (RAS) e la raccolta di informazioni da fonti aperte (OSINT). Il rendering dei container grafici è gestito dal progetto open source KasmVNC.
    ja_JP: Workspacesは、デスクトップ、アプリケーション、Webサービスへのブラウザベースのアクセスを提供するDockerコンテナストリーミングプラットフォームです。Kasmは、DevOps対応のコンテナ化デスクトップインフラストラクチャ（CDI）を使用して、Webブラウザ経由でアクセス可能なオンデマンドの使い捨てDockerコンテナを作成します。使用例としては、リモートブラウザ分離（RBI）、データ損失防止（DLP）、デスクトップ・アズ・ア・サービス（DaaS）、セキュアリモートアクセスサービス（RAS）、オープンソースインテリジェンス（OSINT）の収集などが挙げられます。グラフィカルコンテナのレンダリングは、オープンソースプロジェクトKasmVNCによって実現されています。
    ko_KR: Workspaces는 데스크톱, 애플리케이션 및 웹 서비스에 브라우저 기반으로 액세스할 수 있도록 지원하는 Docker 컨테이너 스트리밍 플랫폼입니다. Kasm은 DevOps 기반의 컨테이너화된 데스크톱 인프라(CDI)를 사용하여 웹 브라우저를 통해 액세스 가능한 온디맨드 방식의 일회용 Docker 컨테이너를 생성합니다. 활용 사례로는 원격 브라우저 격리(RBI), 데이터 손실 방지(DLP), 서비스형 데스크톱(DaaS), 보안 원격 액세스 서비스(RAS) 및 오픈 소스 인텔리전스(OSINT) 수집 등이 있습니다. 그래픽 기반 컨테이너 렌더링은 오픈 소스 프로젝트인 KasmVNC를 통해 구현됩니다.
    ml_IN: ഡെസ്‌ക്‌ടോപ്പുകൾ, ആപ്ലിക്കേഷനുകൾ, വെബ് സേവനങ്ങൾ എന്നിവയിലേക്ക് ബ്രൗസർ അധിഷ്ഠിത ആക്‌സസ് നൽകുന്നതിനുള്ള ഒരു ഡോക്കർ കണ്ടെയ്‌നർ സ്ട്രീമിംഗ് പ്ലാറ്റ്‌ഫോമാണ് വർക്ക്‌സ്‌പെയ്‌സസ്. വെബ് ബ്രൗസർ വഴി ആക്‌സസ് ചെയ്യാവുന്ന ഓൺ-ഡിമാൻഡ്, ഡിസ്‌പോസിബിൾ, ഡോക്കർ കണ്ടെയ്‌നറുകൾ സൃഷ്ടിക്കാൻ കാസ്മിൽ ഡെവോപ്‌സ്-എനേബിൾഡ് കണ്ടെയ്‌നറൈസ്ഡ് ഡെസ്‌ക്‌ടോപ്പ് ഇൻഫ്രാസ്ട്രക്ചർ (സിഡിഐ) ഉപയോഗിക്കുന്നു. റിമോട്ട് ബ്രൗസർ ഐസൊലേഷൻ (ആർ‌ബി‌ഐ), ഡാറ്റ ലോസ് പ്രിവൻഷൻ (ഡി‌എൽ‌പി), ഡെസ്‌ക്‌ടോപ്പ് ആസ് എ സർവീസ് (ഡി‌എ‌എ‌എസ്), സെക്യുർ റിമോട്ട് ആക്‌സസ് സർവീസസ് (ആർ‌എ‌എസ്), ഓപ്പൺ സോഴ്‌സ് ഇന്റലിജൻസ് (ഒ‌എസ്‌ഐ‌എൻ‌ടി) ശേഖരണങ്ങൾ എന്നിവ ഉദാഹരണ ഉപയോഗ കേസുകളിൽ ഉൾപ്പെടുന്നു. ഗ്രാഫിക്കൽ അധിഷ്ഠിത കണ്ടെയ്‌നറുകളുടെ റെൻഡറിംഗ് ഓപ്പൺ സോഴ്‌സ് പ്രോജക്റ്റ് കാസ്മ്‌വി‌എൻ‌സി ഉപയോഗിച്ചാണ് നടത്തുന്നത്.
    nb_NO: Workspaces er en plattform for strømming av docker-containere for å levere nettleserbasert tilgang til skrivebord, applikasjoner og webtjenester. Kasm bruker devops-aktivert Containerized Desktop Infrastructure (CDI) for å lage engangs-docker-containere på forespørsel som er tilgjengelige via nettleser. Eksempler på brukstilfeller inkluderer Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) og Open Source Intelligence (OSINT)-samlinger. Gjengivelsen av de grafikkbaserte containerne drives av åpen kildekode-prosjektet KasmVNC.
    nl_NL: Workspaces is een platform voor het streamen van Docker-containers waarmee via de browser toegang kan worden verkregen tot desktops, applicaties en webdiensten. Kasm maakt gebruik van de DevOps-compatibele Containerized Desktop Infrastructure (CDI) om on-demand, tijdelijke Docker-containers te creëren die toegankelijk zijn via een webbrowser. Voorbeelden van toepassingen zijn Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) en Open Source Intelligence (OSINT)-verzamelingen. De grafische weergave van de containers wordt mogelijk gemaakt door het open-sourceproject KasmVNC.
    pl_PL: Workspaces to platforma strumieniowego przesyłania kontenerów Docker, która zapewnia dostęp do pulpitów, aplikacji i usług sieciowych za pośrednictwem przeglądarki. Kasm wykorzystuje infrastrukturę CDI (Containerized Desktop Infrastructure) z obsługą DevOps do tworzenia kontenerów Docker na żądanie i do jednorazowego użytku, dostępnych za pośrednictwem przeglądarki internetowej. Przykładowe zastosowania obejmują izolację przeglądarki zdalnej (RBI), zapobieganie utracie danych (DLP), pulpit jako usługę (DaaS), usługi bezpiecznego dostępu zdalnego (RAS) oraz kolekcje Open Source Intelligence (OSINT). Renderowanie graficznych kontenerów jest obsługiwane przez projekt open source KasmVNC.
    pt_BR: O Workspaces é uma plataforma de streaming de contêineres Docker para fornecer acesso baseado em navegador a desktops, aplicativos e serviços web. O Kasm utiliza Infraestrutura de Desktop Contêinerizada (CDI) habilitada para DevOps para criar contêineres Docker descartáveis e sob demanda, acessíveis via navegador web. Exemplos de casos de uso incluem Isolamento Remoto de Navegador (RBI), Prevenção de Perda de Dados (DLP), Desktop como Serviço (DaaS), Serviços de Acesso Remoto Seguro (RAS) e coleta de Inteligência de Código Aberto (OSINT). A renderização dos contêineres com interface gráfica é feita pelo projeto de código aberto KasmVNC.
    ro_RO: Workspaces este o platformă de streaming pentru containere Docker, care oferă acces prin browser la desktopuri, aplicații și servicii web. Kasm utilizează Containerized Desktop Infrastructure (CDI) activată pentru Devops pentru a crea containere Docker la cerere, de unică folosință, accesibile prin browser web. Exemple de cazuri de utilizare includ Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) și colecții Open Source Intelligence (OSINT). Randarea containerelor grafice este susținută de proiectul open-source KasmVNC.
    ru_RU: Workspaces — это платформа потоковой передачи контейнеров Docker, обеспечивающая доступ к рабочим столам, приложениям и веб-сервисам через браузер. Kasm использует инфраструктуру контейнеризированных рабочих столов (CDI) с поддержкой DevOps для создания по запросу одноразовых контейнеров Docker, доступных через веб-браузер. Примеры использования включают изоляцию удаленного браузера (RBI), предотвращение потери данных (DLP), рабочий стол как услуга (DaaS), безопасные службы удаленного доступа (RAS) и сбор разведывательной информации из открытых источников (OSINT). Рендеринг графических контейнеров осуществляется с помощью проекта с открытым исходным кодом KasmVNC.
    sk_SK: Workspaces je platforma na streamovanie docker kontajnerov, ktorá poskytuje prístup k desktopom, aplikáciám a webovým službám prostredníctvom prehliadača. Kasm využíva infraštruktúru kontajnerizovaných desktopov (CDI) s podporou devops na vytváranie jednorazových docker kontajnerov na požiadanie, ktoré sú prístupné prostredníctvom webového prehliadača. Medzi príklady použitia patrí izolácia vzdialeného prehliadača (RBI), prevencia straty údajov (DLP), desktop ako služba (DaaS), služby zabezpečeného vzdialeného prístupu (RAS) a kolekcie open source inteligencie (OSINT). Vykresľovanie grafických kontajnerov je poháňané open source projektom KasmVNC.
    sv_SE: Workspaces är en plattform för strömning av dockercontainrar för att leverera webbläsarbaserad åtkomst till skrivbord, applikationer och webbtjänster. Kasm använder devops-aktiverad Containerized Desktop Infrastructure (CDI) för att skapa on-demand, engångs-, dockercontainrar som är åtkomliga via webbläsare. Exempel på användningsfall inkluderar Remote Browser Isolation (RBI), Data Loss Prevention (DLP), Desktop as a Service (DaaS), Secure Remote Access Services (RAS) och Open Source Intelligence (OSINT)-samlingar. Renderingen av de grafikbaserade containrarna drivs av öppen källkodsprojektet KasmVNC.
    tr_TR: Workspaces, masaüstlerine, uygulamalara ve web hizmetlerine tarayıcı tabanlı erişim sağlamak için kullanılan bir Docker konteyner akış platformudur. Kasm, isteğe bağlı, tek kullanımlık ve web tarayıcısı üzerinden erişilebilen Docker konteynerleri oluşturmak için DevOps özellikli Konteynerleştirilmiş Masaüstü Altyapısı (CDI) kullanır. Örnek kullanım durumları arasında Uzaktan Tarayıcı İzolasyonu (RBI), Veri Kaybı Önleme (DLP), Hizmet Olarak Masaüstü (DaaS), Güvenli Uzaktan Erişim Hizmetleri (RAS) ve Açık Kaynak İstihbaratı (OSINT) toplama yer almaktadır. Grafik tabanlı konteynerlerin görüntülenmesi, açık kaynak kodlu KasmVNC projesi tarafından desteklenmektedir.
    zh_CN: 通过浏览器访问容器化桌面、应用和网页服务。
    zh_TW: 透過瀏覽器訪問容器化桌面、應用和網頁服務。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://kasm-ci.s3.amazonaws.com/kasm_wide.png
  thumbnail: https://kasm-ci.s3.amazonaws.com/kasm_wide.png
  title:
    en_US: Kasm (LinuxServer.io)
    ca_ES: Kasm (LinuxServer.io)
    cs_CZ: Kasm (LinuxServer.io)
    da_DK: Kasm (LinuxServer.io)
    de_DE: Kasm (LinuxServer.io)
    el_GR: Kasm (LinuxServer.io)
    en_GB: Kasm (LinuxServer.io)
    es_ES: Kasm (LinuxServer.io)
    fr_FR: Kasm (LinuxServer.io)
    ga_IE: Kasm (LinuxServer.io)
    hr_HR: Kasm (LinuxServer.io)
    hu_HU: Kasm (LinuxServer.io)
    it_IT: Kasm (LinuxServer.io)
    ja_JP: Kasm (LinuxServer.io)
    ko_KR: Kasm (LinuxServer.io)
    ml_IN: Kasm (LinuxServer.io)
    nb_NO: Kasm (LinuxServer.io)
    nl_NL: Kasm (LinuxServer.io)
    pl_PL: Kasm (LinuxServer.io)
    pt_BR: Kasm (LinuxServer.io)
    ro_RO: Kasm (LinuxServer.io)
    ru_RU: Kasm (LinuxServer.io)
    sk_SK: Kasm (LinuxServer.io)
    sv_SE: Kasm (LinuxServer.io)
    tr_TR: Kasm (LinuxServer.io)
    zh_CN: Kasm（LinuxServer.io）
    zh_TW: Kasm（LinuxServer.io）
  category: Others
  id: wisdomsky.linuxserver.linuxserverkasm
  port_map: '3000'
  version: 1.19.0
