name: linuxserver-ddclient
services:
  app:
    image: linuxserver/ddclient:4.0.0@sha256:20b4431cb97cee343a21b0339e5d0add3ebd5b3545a9f8f351f05844be54b25c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ddclient/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverddclient/assets/icon.png
  title:
    en_US: Ddclient (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverddclient
  port_map: '80'
  version: 4.0.0
