name: linuxserver-davos
services:
  app:
    image: linuxserver/davos:2.2.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/davos/config
        target: /config
      - type: bind
        source: /DATA/AppData/davos/download
        target: /download
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Davos is an FTP automation tool that periodically scans given host locations for new files. It can be configured for various purposes, including listening for specific files to appear in the host location, ready for it to download and then move, if required. It also supports completion notifications as well as downstream API calls, to further the workflow.
    ca_ES: Davos és una eina d'automatització FTP que escaneja periòdicament les ubicacions de l'amfitrió determinades per buscar fitxers nous. Es pot configurar per a diversos propòsits, com ara escoltar fitxers específics que apareguin a la ubicació de l'amfitrió, preparats per descarregar-los i després moure'ls, si cal. També admet notificacions de finalització, així com crides a l'API posteriors, per millorar el flux de treball.
    cs_CZ: Davos je nástroj pro automatizaci FTP, který pravidelně prohledává dané hostitelské umístění a hledá nové soubory. Lze jej konfigurovat pro různé účely, včetně naslouchání konkrétním souborům, které se v hostitelském umístění objevují a jsou připraveny ke stažení a následnému přesunutí, pokud je to nutné. Podporuje také oznámení o dokončení a volání API pro další usnadnění pracovního postupu.
    da_DK: Davos er et FTP-automatiseringsværktøj, der periodisk scanner givne værtsplaceringer for nye filer. Det kan konfigureres til forskellige formål, herunder at lytte efter specifikke filer, der vises på værtsplaceringen, klar til download og derefter flytning, hvis det er nødvendigt. Det understøtter også fuldførelsesmeddelelser samt downstream API-kald for at fremme arbejdsgangen.
    de_DE: Davos ist ein FTP-Automatisierungstool, das regelmäßig die angegebenen Host-Speicherorte nach neuen Dateien durchsucht. Es lässt sich für verschiedene Zwecke konfigurieren, beispielsweise um auf das Erscheinen bestimmter Dateien am Host-Speicherort zu warten, diese herunterzuladen und bei Bedarf zu verschieben. Darüber hinaus unterstützt es Benachrichtigungen über abgeschlossene Downloads sowie API-Aufrufe, um den Workflow weiter zu optimieren.
    el_GR: Το Davos είναι ένα εργαλείο αυτοματισμού FTP που σαρώνει περιοδικά συγκεκριμένες τοποθεσίες κεντρικού υπολογιστή για νέα αρχεία. Μπορεί να ρυθμιστεί για διάφορους σκοπούς, όπως η ακρόαση για την εμφάνιση συγκεκριμένων αρχείων στην τοποθεσία κεντρικού υπολογιστή, ώστε να είναι έτοιμα για λήψη και στη συνέχεια να μετακινηθούν, εάν απαιτείται. Υποστηρίζει επίσης ειδοποιήσεις ολοκλήρωσης καθώς και κλήσεις API κατάντη, για την προώθηση της ροής εργασίας.
    en_GB: Davos is an Ftp automation tool that periodically scans given host locations for new files. It can be configured for various purposes, including listening for specific files to appear in the host location, ready for it to download and then move, if required. It also supports completion notifications as well as downstream Api calls, to further the workflow.
    es_ES: Davos es una herramienta de automatización FTP que escanea periódicamente ubicaciones de host específicas en busca de nuevos archivos. Se puede configurar para diversos fines, como detectar la aparición de archivos específicos en la ubicación del host para descargarlos y, si es necesario, transferirlos. También admite notificaciones de finalización y llamadas a la API, para optimizar el flujo de trabajo.
    fr_FR: Davos est un outil d'automatisation FTP qui analyse périodiquement les emplacements hôtes spécifiés à la recherche de nouveaux fichiers. Il peut être configuré pour diverses applications, notamment la détection de fichiers spécifiques sur un emplacement hôte, leur téléchargement et leur transfert si nécessaire. Il prend également en charge les notifications de fin de traitement et les appels d'API en aval, afin d'optimiser le flux de travail.
    ga_IE: Is uirlis uathoibrithe FTP é Davos a dhéanann scanadh tréimhsiúil ar shuíomhanna óstacha áirithe le haghaidh comhad nua. Is féidir é a chumrú chun críocha éagsúla, lena n-áirítear éisteacht le comhaid shonracha le feiceáil sa suíomh óstach, réidh le híoslódáil agus ansin bogadh, más gá. Tacaíonn sé freisin le fógraí críochnaithe chomh maith le glaonna API iartheachtach, chun an sreabhadh oibre a chur chun cinn.
    hr_HR: Davos je alat za automatizaciju FTP-a koji periodički skenira određene lokacije hosta u potrazi za novim datotekama. Može se konfigurirati za različite svrhe, uključujući osluškivanje određenih datoteka koje se pojavljuju na lokaciji hosta, spremne za preuzimanje i zatim premještanje, ako je potrebno. Također podržava obavijesti o dovršetku kao i nizvodne API pozive za unapređenje tijeka rada.
    hu_HU: A Davos egy FTP automatizáló eszköz, amely rendszeresen beolvassa a megadott host helyeket új fájlok után kutatva. Különböző célokra konfigurálható, beleértve a bizonyos fájlok megjelenésének figyelését a host helyen, készen a letöltésre és szükség esetén áthelyezésre. Támogatja a befejezési értesítéseket, valamint a downstream API-hívásokat is a munkafolyamat elősegítése érdekében.
    it_IT: Davos è uno strumento di automazione FTP che esegue periodicamente la scansione di posizioni host specificate alla ricerca di nuovi file. Può essere configurato per diversi scopi, tra cui l'ascolto di file specifici che compaiono nella posizione host, pronti per essere scaricati e, se necessario, spostati. Supporta inoltre le notifiche di completamento e le chiamate API a valle, per ottimizzare il flusso di lavoro.
    ja_JP: Davosは、指定されたホストの場所を定期的にスキャンして新しいファイルを検出するFTP自動化ツールです。特定のファイルがホストの場所に現れるのを待ち受け、必要に応じてダウンロードして移動するなど、さまざまな目的に合わせて設定できます。また、完了通知や下流のAPI呼び出しにも対応しており、ワークフローをさらに効率化できます。
    ko_KR: Davos는 지정된 호스트 위치를 주기적으로 스캔하여 새 파일을 감지하는 FTP 자동화 도구입니다. 특정 파일이 호스트 위치에 나타나면 자동으로 다운로드하고 필요한 경우 이동하도록 설정하는 등 다양한 용도로 구성할 수 있습니다. 또한 작업 완료 알림 및 하위 API 호출을 지원하여 워크플로우를 효율적으로 관리할 수 있습니다.
    ml_IN: പുതിയ ഫയലുകൾക്കായി നൽകിയിരിക്കുന്ന ഹോസ്റ്റ് ലൊക്കേഷനുകൾ ഇടയ്ക്കിടെ സ്കാൻ ചെയ്യുന്ന ഒരു FTP ഓട്ടോമേഷൻ ഉപകരണമാണ് ഡാവോസ്. ഹോസ്റ്റ് ലൊക്കേഷനിൽ നിർദ്ദിഷ്ട ഫയലുകൾ ദൃശ്യമാകുന്നത് കേൾക്കൽ, ആവശ്യമെങ്കിൽ ഡൗൺലോഡ് ചെയ്യാനും തുടർന്ന് നീക്കാനും തയ്യാറായി നിൽക്കുന്നത് എന്നിവയുൾപ്പെടെ വിവിധ ആവശ്യങ്ങൾക്കായി ഇത് കോൺഫിഗർ ചെയ്യാവുന്നതാണ്. വർക്ക്ഫ്ലോ കൂടുതൽ മെച്ചപ്പെടുത്തുന്നതിന്, ഡൗൺസ്ട്രീം API കോളുകൾക്കൊപ്പം പൂർത്തീകരണ അറിയിപ്പുകളും ഇത് പിന്തുണയ്ക്കുന്നു.
    nb_NO: Davos er et FTP-automatiseringsverktøy som regelmessig skanner gitte vertslokasjoner etter nye filer. Det kan konfigureres for ulike formål, inkludert å lytte etter spesifikke filer som skal vises på vertslokasjonen, klare til nedlasting og deretter flytting, om nødvendig. Det støtter også fullføringsvarsler samt nedstrøms API-kall, for å fremme arbeidsflyten.
    nl_NL: Davos is een FTP-automatiseringstool die periodiek opgegeven hostlocaties scant op nieuwe bestanden. Het kan voor verschillende doeleinden worden geconfigureerd, waaronder het luisteren naar specifieke bestanden die op de hostlocatie verschijnen, zodat deze kunnen worden gedownload en, indien nodig, verplaatst. Het ondersteunt ook voltooiingsmeldingen en downstream API-aanroepen om de workflow verder te optimaliseren.
    pl_PL: Davos to narzędzie do automatyzacji FTP, które okresowo skanuje określone lokalizacje hostów w poszukiwaniu nowych plików. Można je skonfigurować do różnych celów, w tym do nasłuchiwania pojawiania się określonych plików w danej lokalizacji hosta, gotowych do pobrania, a następnie przeniesienia, jeśli zajdzie taka potrzeba. Obsługuje również powiadomienia o zakończeniu, a także wywołania API, co usprawnia przepływ pracy.
    pt_BR: O Davos é uma ferramenta de automação de FTP que verifica periodicamente locais de hospedagem específicos em busca de novos arquivos. Ele pode ser configurado para diversas finalidades, incluindo a detecção de arquivos específicos que aparecem no local de hospedagem, para que possa ser baixado e, se necessário, movido. Também oferece suporte a notificações de conclusão e chamadas de API subsequentes para otimizar o fluxo de trabalho.
    ro_RO: Davos este un instrument de automatizare FTP care scanează periodic locațiile gazdă date pentru fișiere noi. Poate fi configurat pentru diverse scopuri, inclusiv pentru a aștepta apariția anumitor fișiere în locația gazdă, gata pentru descărcare și apoi mutare, dacă este necesar. De asemenea, acceptă notificări de finalizare, precum și apeluri API downstream, pentru a îmbunătăți fluxul de lucru.
    ru_RU: Davos — это инструмент автоматизации FTP, который периодически сканирует указанные расположения файлов на хосте на наличие новых файлов. Его можно настроить для различных целей, включая отслеживание появления определенных файлов в расположении на хосте, готовых к загрузке и последующему перемещению при необходимости. Он также поддерживает уведомления о завершении процесса, а также вызовы API для дальнейшего оптимизации рабочего процесса.
    sk_SK: Davos je nástroj na automatizáciu FTP, ktorý pravidelne prehľadáva dané hostiteľské umiestnenia a hľadá nové súbory. Dá sa nakonfigurovať na rôzne účely vrátane počúvania konkrétnych súborov, ktoré sa majú objaviť na hostiteľskom umiestnení, pripravené na stiahnutie a následné presunutie, ak je to potrebné. Podporuje tiež upozornenia na dokončenie, ako aj volania API pre ďalšie spracovanie pracovných postupov.
    sv_SE: Davos är ett FTP-automatiseringsverktyg som regelbundet skannar givna värdplatser efter nya filer. Det kan konfigureras för olika ändamål, inklusive att lyssna efter specifika filer som visas på värdplatsen, redo att laddas ner och sedan flyttas, om det behövs. Det stöder även aviseringar om slutförande samt nedströms API-anrop för att främja arbetsflödet.
    tr_TR: Davos, belirli sunucu konumlarını periyodik olarak yeni dosyalar için tarayan bir FTP otomasyon aracıdır. Sunucu konumunda belirli dosyaların görünmesini dinlemek, indirmek ve gerekirse taşımak da dahil olmak üzere çeşitli amaçlar için yapılandırılabilir. Ayrıca, iş akışını daha da geliştirmek için tamamlanma bildirimlerini ve alt düzey API çağrılarını da destekler.
    zh_CN: Davos 是一个 FTP 自动化工具，可定期扫描指定主机位置中的新文件。它可配置为等待指定文件出现后自动下载，并按需移动文件。它还支持完成通知和后续 API 调用，以继续执行工作流程。
    zh_TW: Davos 是一個 FTP 自動化工具，可定期掃描指定主機位置中的新檔案。它可配置為等待指定檔案出現後自動下載，並按需移動檔案。它還支援完成通知和後續 API 呼叫，以繼續執行工作流程。
  tagline:
    en_US: An FTP automation tool that periodically scans given host locations for new files. It can be configured for various purposes, including listening for specific files to appear in the host location, ready for it to download and then move, if required. It also supports completion notifications as well as downstream API calls, to further the workflow.
    ca_ES: Una eina d'automatització FTP que escaneja periòdicament les ubicacions de l'amfitrió determinades per buscar fitxers nous. Es pot configurar per a diversos propòsits, com ara escoltar fitxers específics que apareguin a la ubicació de l'amfitrió, preparats per descarregar-los i després moure'ls, si cal. També admet notificacions de finalització, així com crides a l'API descendents, per millorar el flux de treball.
    cs_CZ: Nástroj pro automatizaci FTP, který pravidelně prohledává daná umístění hostitelů a hledá nové soubory. Lze jej konfigurovat pro různé účely, včetně naslouchání konkrétním souborům, které se v umístění hostitele objevují a jsou připraveny ke stažení a následnému přesunutí, pokud je to nutné. Podporuje také oznámení o dokončení a volání API pro další workflow.
    da_DK: Et FTP-automatiseringsværktøj, der periodisk scanner givne værtsplaceringer for nye filer. Det kan konfigureres til forskellige formål, herunder at lytte efter specifikke filer, der vises på værtsplaceringen, klar til download og derefter flytning, hvis det er nødvendigt. Det understøtter også fuldførelsesmeddelelser samt downstream API-kald for at fremme arbejdsgangen.
    de_DE: Ein FTP-Automatisierungstool, das regelmäßig die angegebenen Host-Speicherorte nach neuen Dateien durchsucht. Es lässt sich für verschiedene Zwecke konfigurieren, beispielsweise um auf das Erscheinen bestimmter Dateien im Host-Speicherort zu warten, diese herunterzuladen und bei Bedarf zu verschieben. Es unterstützt außerdem Abschlussbenachrichtigungen sowie nachgelagerte API-Aufrufe zur Optimierung des Workflows.
    el_GR: Ένα εργαλείο αυτοματισμού FTP που σαρώνει περιοδικά συγκεκριμένες τοποθεσίες κεντρικού υπολογιστή για νέα αρχεία. Μπορεί να ρυθμιστεί για διάφορους σκοπούς, όπως η ακρόαση για την εμφάνιση συγκεκριμένων αρχείων στην τοποθεσία κεντρικού υπολογιστή, η ετοιμότητά τους για λήψη και η μετακίνησή τους, εάν απαιτείται. Υποστηρίζει επίσης ειδοποιήσεις ολοκλήρωσης καθώς και κλήσεις API κατάντη, για την προώθηση της ροής εργασίας.
    en_GB: An Ftp automation tool that periodically scans given host locations for new files. It can be configured for various purposes, including listening for specific files to appear in the host location, ready for it to download and then move, if required. It also supports completion notifications as well as downstream Api calls, to further the workflow.
    es_ES: Una herramienta de automatización FTP que escanea periódicamente ubicaciones de host específicas en busca de nuevos archivos. Se puede configurar para diversos fines, como detectar la aparición de archivos específicos en la ubicación del host para su descarga y posterior transferencia, si fuera necesario. También admite notificaciones de finalización y llamadas a API posteriores para optimizar el flujo de trabajo.
    fr_FR: Un outil d'automatisation FTP qui analyse périodiquement les emplacements hôtes spécifiés à la recherche de nouveaux fichiers. Il est configurable pour diverses applications, notamment la détection de fichiers spécifiques présents sur l'hôte, leur téléchargement et leur transfert si nécessaire. Il prend également en charge les notifications de fin de traitement et les appels d'API en aval, afin d'optimiser le flux de travail.
    ga_IE: Uirlis uathoibrithe FTP a dhéanann scanadh tréimhsiúil ar shuíomhanna óstacha áirithe le haghaidh comhad nua. Is féidir é a chumrú chun críocha éagsúla, lena n-áirítear éisteacht le comhaid shonracha le feiceáil sa suíomh óstach, réidh le híoslódáil agus ansin bogadh, más gá. Tacaíonn sé freisin le fógraí críochnaithe chomh maith le glaonna API iartheachtach, chun an sreabhadh oibre a chur chun cinn.
    hr_HR: Alat za automatizaciju FTP-a koji periodički skenira određene lokacije hosta u potrazi za novim datotekama. Može se konfigurirati za različite svrhe, uključujući osluškivanje određenih datoteka koje će se pojaviti na lokaciji hosta, spremne za preuzimanje, a zatim premještanje, ako je potrebno. Također podržava obavijesti o dovršetku, kao i nizvodne API pozive, za unapređenje tijeka rada.
    hu_HU: Egy FTP automatizáló eszköz, amely rendszeresen beolvassa a megadott host helyeket új fájlok után kutatva. Különböző célokra konfigurálható, beleértve a bizonyos fájlok megjelenésének figyelését a host helyen, készen a letöltésre és áthelyezésre, ha szükséges. Támogatja a befejezési értesítéseket, valamint a downstream API-hívásokat is a munkafolyamat elősegítése érdekében.
    it_IT: Uno strumento di automazione FTP che esegue periodicamente la scansione di posizioni host specificate alla ricerca di nuovi file. Può essere configurato per diversi scopi, tra cui l'ascolto di file specifici che compaiono nella posizione host, pronti per essere scaricati e, se necessario, spostati. Supporta inoltre le notifiche di completamento e le chiamate API a valle, per ottimizzare il flusso di lavoro.
    ja_JP: 指定されたホストの場所を定期的にスキャンして新しいファイルを検出するFTP自動化ツールです。特定のファイルがホストの場所に現れるのを待ち受け、必要に応じてダウンロードして移動するなど、さまざまな目的に合わせて設定できます。また、完了通知や下流のAPI呼び出しにも対応しており、ワークフローをさらに効率化できます。
    ko_KR: 지정된 호스트 위치를 주기적으로 스캔하여 새 파일을 감지하는 FTP 자동화 도구입니다. 특정 파일이 호스트 위치에 나타나면 자동으로 다운로드하고 필요한 경우 이동하는 등 다양한 용도로 설정할 수 있습니다. 또한 완료 알림 기능과 하위 API 호출을 지원하여 워크플로우를 효율적으로 관리할 수 있습니다.
    ml_IN: പുതിയ ഫയലുകൾക്കായി നൽകിയിരിക്കുന്ന ഹോസ്റ്റ് ലൊക്കേഷനുകൾ ഇടയ്ക്കിടെ സ്കാൻ ചെയ്യുന്ന ഒരു FTP ഓട്ടോമേഷൻ ഉപകരണം. ഹോസ്റ്റ് ലൊക്കേഷനിൽ നിർദ്ദിഷ്ട ഫയലുകൾ ദൃശ്യമാകുന്നത് കേൾക്കുന്നത്, ആവശ്യമെങ്കിൽ ഡൗൺലോഡ് ചെയ്യാനും തുടർന്ന് നീക്കാനും തയ്യാറായിരിക്കുന്നത് ഉൾപ്പെടെ വിവിധ ആവശ്യങ്ങൾക്കായി ഇത് കോൺഫിഗർ ചെയ്യാൻ കഴിയും. വർക്ക്ഫ്ലോ കൂടുതൽ മെച്ചപ്പെടുത്തുന്നതിന്, ഡൗൺസ്ട്രീം API കോളുകൾക്കൊപ്പം പൂർത്തീകരണ അറിയിപ്പുകളും ഇത് പിന്തുണയ്ക്കുന്നു.
    nb_NO: Et FTP-automatiseringsverktøy som regelmessig skanner gitte vertslokasjoner etter nye filer. Det kan konfigureres for ulike formål, inkludert å lytte etter bestemte filer som skal vises på vertslokasjonen, klare til nedlasting og deretter flytting, om nødvendig. Det støtter også fullføringsvarsler samt nedstrøms API-kall for å fremme arbeidsflyten.
    nl_NL: Een FTP-automatiseringstool die periodiek opgegeven hostlocaties scant op nieuwe bestanden. De tool kan voor diverse doeleinden worden geconfigureerd, waaronder het detecteren van specifieke bestanden op de hostlocatie, zodat deze gedownload en indien nodig verplaatst kunnen worden. Daarnaast ondersteunt de tool meldingen bij voltooiing en API-aanroepen om de workflow verder te optimaliseren.
    pl_PL: Narzędzie do automatyzacji FTP, które okresowo skanuje określone lokalizacje hostów w poszukiwaniu nowych plików. Można je skonfigurować do różnych celów, w tym do nasłuchiwania pojawiania się określonych plików w lokalizacji hosta, gotowych do pobrania, a następnie przeniesienia, jeśli zajdzie taka potrzeba. Obsługuje również powiadomienia o zakończeniu, a także wywołania API, co usprawnia przepływ pracy.
    pt_BR: Uma ferramenta de automação FTP que verifica periodicamente locais de hospedagem específicos em busca de novos arquivos. Ela pode ser configurada para diversas finalidades, incluindo a detecção de arquivos específicos no local de hospedagem, para que possa ser baixada e movida, se necessário. Também oferece suporte a notificações de conclusão e chamadas de API subsequentes para otimizar o fluxo de trabalho.
    ro_RO: Un instrument de automatizare FTP care scanează periodic locațiile gazdă date pentru fișiere noi. Poate fi configurat pentru diverse scopuri, inclusiv așteptarea apariției anumitor fișiere în locația gazdă, gata de descărcare și apoi mutare, dacă este necesar. De asemenea, acceptă notificări de finalizare, precum și apeluri API downstream, pentru a îmbunătăți fluxul de lucru.
    ru_RU: Инструмент автоматизации FTP, который периодически сканирует указанные расположения файлов на хосте на наличие новых файлов. Его можно настроить для различных целей, включая отслеживание появления определенных файлов в указанном расположении на хосте, готовых к загрузке и последующему перемещению при необходимости. Он также поддерживает уведомления о завершении процесса, а также вызовы API для дальнейшего оптимизации рабочего процесса.
    sk_SK: Nástroj na automatizáciu FTP, ktorý pravidelne prehľadáva dané hostiteľské umiestnenia a hľadá nové súbory. Dá sa nakonfigurovať na rôzne účely vrátane počúvania konkrétnych súborov, ktoré sa majú objaviť na hostiteľskom umiestnení, pripravené na stiahnutie a následné presunutie, ak je to potrebné. Podporuje tiež upozornenia na dokončenie, ako aj volania API pre následné spracovanie, čo podporuje pracovný postup.
    sv_SE: Ett FTP-automatiseringsverktyg som regelbundet skannar givna värdplatser efter nya filer. Det kan konfigureras för olika ändamål, inklusive att lyssna efter specifika filer som visas på värdplatsen, redo att laddas ner och sedan flyttas, om det behövs. Det stöder även aviseringar om slutförande samt nedströms API-anrop för att främja arbetsflödet.
    tr_TR: Belirtilen sunucu konumlarını periyodik olarak tarayarak yeni dosyaları tespit eden bir FTP otomasyon aracıdır. Çeşitli amaçlar için yapılandırılabilir; örneğin, sunucu konumunda belirli dosyaların görünmesini bekleyebilir, bunları indirip gerekirse taşıyabilir. Ayrıca, iş akışını daha da geliştirmek için tamamlanma bildirimlerini ve alt API çağrılarını da destekler.
    zh_CN: 自动扫描 FTP 服务器并下载新文件。
    zh_TW: 自動掃描 FTP 伺服器並下載新檔案。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/davos/master/docs/list.PNG
  thumbnail: https://raw.githubusercontent.com/linuxserver/davos/master/docs/list.PNG
  title:
    en_US: Davos (LinuxServer.io)
    ca_ES: Davos (LinuxServer.io)
    cs_CZ: Davos (LinuxServer.io)
    da_DK: Davos (LinuxServer.io)
    de_DE: Davos (LinuxServer.io)
    el_GR: Davos (LinuxServer.io)
    en_GB: Davos (LinuxServer.io)
    es_ES: Davos (LinuxServer.io)
    fr_FR: Davos (LinuxServer.io)
    ga_IE: Davos (LinuxServer.io)
    hr_HR: Davos (LinuxServer.io)
    hu_HU: Davos (LinuxServer.io)
    it_IT: Davos (LinuxServer.io)
    ja_JP: Davos (LinuxServer.io)
    ko_KR: Davos (LinuxServer.io)
    ml_IN: Davos (LinuxServer.io)
    nb_NO: Davos (LinuxServer.io)
    nl_NL: Davos (LinuxServer.io)
    pl_PL: Davos (LinuxServer.io)
    pt_BR: Davos (LinuxServer.io)
    ro_RO: Davos (LinuxServer.io)
    ru_RU: Davos (LinuxServer.io)
    sk_SK: Davos (LinuxServer.io)
    sv_SE: Davos (LinuxServer.io)
    tr_TR: Davos (LinuxServer.io)
    zh_CN: Davos（LinuxServer.io）
    zh_TW: Davos（LinuxServer.io）
  category: Media
  id: wisdomsky.linuxserver.linuxserverdavos
  port_map: '8080'
  version: 2.2.2
