name: linuxserver-steamos
services:
  app:
    image: linuxserver/steamos:version-2024-12-20
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DRINODE: ''
      HOST_IP: ''
      STARTUP: ''
      RESOLUTION: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/steamos/config
        target: /config
      - type: bind
        source: /dev/input
        target: /dev/input
      - type: bind
        source: /run/udev/data
        target: /run/udev/data
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserversteamos/assets/icon.png
  title:
    en_US: Steamos
    zh_CN: Steamos
    ca_ES: Steamos
    cs_CZ: Steamos
    da_DK: Steamos
    de_DE: Steamos
    el_GR: Steamos
    en_GB: Steamos
    es_ES: Steamos
    fr_FR: Steamos
    ga_IE: Steamos
    hr_HR: Steamos
    hu_HU: Steamos
    it_IT: Steamos
    ja_JP: Steamos
    ko_KR: Steamos
    ml_IN: Steamos
    nb_NO: Steamos
    nl_NL: Steamos
    pl_PL: Steamos
    pt_BR: Steamos
    ro_RO: Steamos
    ru_RU: Steamos
    sk_SK: Steamos
    sv_SE: Steamos
    tr_TR: Steamos
    zh_TW: Steamos
  id: wisdomsky.linuxserver.linuxserversteamos
  version: version-2024-12-20
