name: linuxserver-digikam
services:
  app:
    image: linuxserver/digikam:9.1.0@sha256:3f684eb381fdd77d8d229552980cb8223c30a3109eca0e268e69b4d50de88af8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/digikam/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverdigikam/assets/icon.png
  title:
    en_US: Digikam (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverdigikam
  port_map: '3000'
  version: 9.1.0
