name: linuxserver-digikam
services:
  app:
    image: linuxserver/digikam:9.1.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/digikam/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverdigikam/assets/icon.png
  title:
    en_US: Digikam (LinuxServer.io)
    ca_ES: Digikam (LinuxServer.io)
    cs_CZ: Digikam (LinuxServer.io)
    da_DK: Digikam (LinuxServer.io)
    de_DE: Digikam (LinuxServer.io)
    el_GR: Digikam (LinuxServer.io)
    en_GB: Digikam (LinuxServer.io)
    es_ES: Digikam (LinuxServer.io)
    fr_FR: Digikam (LinuxServer.io)
    ga_IE: Digikam (LinuxServer.io)
    hr_HR: Digikam (LinuxServer.io)
    hu_HU: Digikam (LinuxServer.io)
    it_IT: Digikam (LinuxServer.io)
    ja_JP: Digikam (LinuxServer.io)
    ko_KR: Digikam (LinuxServer.io)
    ml_IN: Digikam (LinuxServer.io)
    nb_NO: Digikam (LinuxServer.io)
    nl_NL: Digikam (LinuxServer.io)
    pl_PL: Digikam (LinuxServer.io)
    pt_BR: Digikam (LinuxServer.io)
    ro_RO: Digikam (LinuxServer.io)
    ru_RU: Digikam (LinuxServer.io)
    sk_SK: Digikam (LinuxServer.io)
    sv_SE: Digikam (LinuxServer.io)
    tr_TR: Digikam (LinuxServer.io)
    zh_CN: Digikam（LinuxServer.io）
    zh_TW: Digikam（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverdigikam
  port_map: '3000'
  version: 9.1.0
