name: linuxserver-headphones
services:
  app:
    image: linuxserver/headphones:version-a78f38c1@sha256:738be7eefa1ead8a869bdf6393b0ee5008149a1c4dc9faa8720467d2dc21c6ec
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/headphones/config
        target: /config
      - type: bind
        source: /DATA/AppData/headphones/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/headphones/music
        target: /music
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverheadphones/assets/icon.png
  title:
    en_US: Headphones
  port_map: '8181'
  id: wisdomsky.linuxserver.linuxserverheadphones
  version: version-a78f38c1
