name: linuxserver-blender
services:
  app:
    image: linuxserver/blender:5.2.2@sha256:83382d822520ff24981c9e13eebcd94742d9d72f04bf7c79c89ea0a2cf1b44d8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/blender/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverblender/assets/icon.png
  title:
    en_US: Blender (LinuxServer.io)
    ca_ES: Blender (LinuxServer.io)
    cs_CZ: Blender (LinuxServer.io)
    da_DK: Blender (LinuxServer.io)
    de_DE: Blender (LinuxServer.io)
    el_GR: Blender (LinuxServer.io)
    en_GB: Blender (LinuxServer.io)
    es_ES: Blender (LinuxServer.io)
    fr_FR: Blender (LinuxServer.io)
    ga_IE: Blender (LinuxServer.io)
    hr_HR: Blender (LinuxServer.io)
    hu_HU: Blender (LinuxServer.io)
    it_IT: Blender (LinuxServer.io)
    ja_JP: Blender (LinuxServer.io)
    ko_KR: Blender (LinuxServer.io)
    ml_IN: Blender (LinuxServer.io)
    nb_NO: Blender (LinuxServer.io)
    nl_NL: Blender (LinuxServer.io)
    pl_PL: Blender (LinuxServer.io)
    pt_BR: Blender (LinuxServer.io)
    ro_RO: Blender (LinuxServer.io)
    ru_RU: Blender (LinuxServer.io)
    sk_SK: Blender (LinuxServer.io)
    sv_SE: Blender (LinuxServer.io)
    tr_TR: Blender (LinuxServer.io)
    zh_CN: Blender（LinuxServer.io）
    zh_TW: Blender（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverblender
  port_map: '3000'
  version: 5.2.2
