name: linuxserver-inkscape
services:
  app:
    image: linuxserver/inkscape:1.4.2@sha256:ee16bf20bc5c9618f15bea2865c1af52101ea6c81f148466bd5232838505bf13
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/inkscape/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverinkscape/assets/icon.png
  title:
    en_US: Inkscape (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverinkscape
  port_map: '3000'
  version: 1.4.2
