name: linuxserver-bookstack
services:
  app:
    image: linuxserver/bookstack:26.05.5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APP_URL: ''
      APP_KEY: ''
      DB_HOST: ''
      DB_PORT: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_DATABASE: ''
      QUEUE_CONNECTION: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: APP_URL
          description:
            en_US: The protocol, IP/URL, and port that your application will be accessed on (ie. http://192.168.1.1:6875 or https://bookstack.mydomain.com
        - container: APP_KEY
          description:
            en_US: Session encryption key. You will need to generate this with docker run -it --rm --entrypoint /bin/bash lscr.io/linuxserver/bookstack:latest appkey
        - container: DB_HOST
          description:
            en_US: The database instance hostname
        - container: DB_PORT
          description:
            en_US: Database port
        - container: DB_USERNAME
          description:
            en_US: Database user
        - container: DB_PASSWORD
          description:
            en_US: Database password (minimum 4 characters & non-alphanumeric passwords must be properly escaped.)
        - container: DB_DATABASE
          description:
            en_US: Database name
        - container: QUEUE_CONNECTION
          description:
            en_US: Set to database to enable async actions like sending email or triggering webhooks. See documentation. [OPTIONAL]
    ports:
      - target: 6875
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bookstack/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: 'Bookstack is a free and open source Wiki designed for creating beautiful documentation. Featuring a simple, but powerful WYSIWYG editor it allows for teams to create detailed and useful documentation with ease. Powered by SQL and including a Markdown editor for those who prefer it, BookStack is geared towards making documentation more of a pleasure than a chore. For more information on BookStack visit their website and check it out: https://www.bookstackapp.com'
    ca_ES: 'Bookstack és un Wiki gratuït i de codi obert dissenyat per crear documentació atractiva. Amb un editor WYSIWYG senzill però potent, permet als equips crear documentació detallada i útil amb facilitat. Amb la tecnologia de SQL i un editor Markdown per a aquells que el prefereixen, BookStack està orientat a fer que la documentació sigui més un plaer que una feina. Per a més informació sobre BookStack, visiteu el seu lloc web: https://www.bookstackapp.com'
    cs_CZ: 'Bookstack je bezplatná Wiki platforma s otevřeným zdrojovým kódem určená pro tvorbu krásné dokumentace. Díky jednoduchému, ale výkonnému WYSIWYG editoru umožňuje týmům snadno vytvářet podrobnou a užitečnou dokumentaci. BookStack, poháněný SQL a včetně editoru Markdown pro ty, kteří ho preferují, je zaměřen na to, aby se dokumentace stala spíše potěšením než povinností. Více informací o BookStacku naleznete na jeho webových stránkách: https://www.bookstackapp.com'
    da_DK: 'Bookstack er en gratis og open source-wiki designet til at skabe smuk dokumentation. Med en simpel, men kraftfuld WYSIWYG-editor kan teams nemt oprette detaljeret og nyttig dokumentation. BookStack er drevet af SQL og inkluderer en Markdown-editor for dem, der foretrækker det, og er gearet til at gøre dokumentation til en mere fornøjelse end en sur pligt. For mere information om BookStack, besøg deres hjemmeside og tjek den ud: https://www.bookstackapp.com'
    de_DE: 'Bookstack ist ein kostenloses Open-Source-Wiki, das speziell für die Erstellung ansprechender Dokumentationen entwickelt wurde. Mit seinem einfachen, aber leistungsstarken WYSIWYG-Editor ermöglicht es Teams, mühelos detaillierte und nützliche Dokumentationen zu erstellen. Bookstack basiert auf SQL und bietet einen Markdown-Editor für alle, die diese Sprache bevorzugen. Ziel von Bookstack ist es, die Dokumentation zum Vergnügen zu machen. Weitere Informationen zu Bookstack finden Sie auf der Website: https://www.bookstackapp.com'
    el_GR: 'Το Bookstack είναι ένα δωρεάν και ανοιχτού κώδικα Wiki σχεδιασμένο για τη δημιουργία όμορφης τεκμηρίωσης. Διαθέτοντας έναν απλό, αλλά ισχυρό επεξεργαστή WYSIWYG, επιτρέπει στις ομάδες να δημιουργούν εύκολα λεπτομερή και χρήσιμη τεκμηρίωση. Με την υποστήριξη της SQL και συμπεριλαμβανομένου ενός επεξεργαστή Markdown για όσους το προτιμούν, το BookStack έχει ως στόχο να κάνει την τεκμηρίωση περισσότερο μια ευχαρίστηση παρά μια αγγαρεία. Για περισσότερες πληροφορίες σχετικά με το BookStack, επισκεφθείτε την ιστοσελίδα τους και δείτε την: https://www.bookstackapp.com'
    en_GB: 'Bookstack is a free and open source Wiki designed for creating beautiful documentation. Featuring a simple, but powerful Wysiwyg editor it allows for teams to create detailed and useful documentation with ease. Powered by Sql and including a Markdown editor for those who prefer it, Bookstack is geared towards making documentation more of a pleasure than a chore. For more information on Bookstack visit their website and check it out: https://www.bookstackapp.com'
    es_ES: 'Bookstack es una wiki gratuita y de código abierto diseñada para crear documentación atractiva. Con un editor WYSIWYG sencillo pero potente, permite a los equipos crear documentación detallada y útil con facilidad. Impulsada por SQL e incluyendo un editor Markdown para quienes lo prefieran, BookStack busca que la creación de documentación sea un placer en lugar de una tarea tediosa. Para obtener más información sobre BookStack, visite su sitio web: https://www.bookstackapp.com'
    fr_FR: "Bookstack est un wiki libre et gratuit conçu pour créer une documentation de qualité. Doté d'un éditeur WYSIWYG simple et performant, il permet aux équipes de créer facilement une documentation détaillée et utile. Basé sur SQL et incluant un éditeur Markdown pour ceux qui le préfèrent, Bookstack a pour objectif de rendre la documentation plus agréable que contraignante. Pour en savoir plus sur Bookstack, rendez-vous sur leur site web\_: https://www.bookstackapp.com"
    ga_IE: 'Is Vicí foinse oscailte saor in aisce é Bookstack atá deartha chun doiciméadú álainn a chruthú. Le heagarthóir WYSIWYG simplí ach cumhachtach, tugann sé deis do fhoirne doiciméadú mionsonraithe agus úsáideach a chruthú go héasca. Cumhachtaithe ag SQL agus eagarthóir Markdown san áireamh dóibh siúd ar fearr leo é, tá BookStack dírithe ar dhoiciméadú a dhéanamh níos pléisiúir ná mar thasc. Le haghaidh tuilleadh eolais faoi BookStack, tabhair cuairt ar a suíomh Gréasáin agus féach air: https://www.bookstackapp.com'
    hr_HR: 'Bookstack je besplatni Wiki otvorenog koda osmišljen za izradu prekrasne dokumentacije. S jednostavnim, ali moćnim WYSIWYG uređivačem, omogućuje timovima jednostavno stvaranje detaljne i korisne dokumentacije. Pokretan SQL-om i uključujući Markdown uređivač za one koji ga preferiraju, BookStack je usmjeren na to da dokumentiranje učini više zadovoljstvom nego mukom. Za više informacija o BookStacku posjetite njihovu web stranicu: https://www.bookstackapp.com'
    hu_HU: 'A Bookstack egy ingyenes és nyílt forráskódú wiki, amelyet gyönyörű dokumentációk készítésére terveztek. Egy egyszerű, de hatékony WYSIWYG szerkesztővel a csapatok könnyedén készíthetnek részletes és hasznos dokumentációkat. Az SQL-alapú és Markdown szerkesztővel rendelkező BookStack célja, hogy a dokumentációt inkább élvezet, mint teher legyen. További információkért a BookStackről látogassa meg weboldalukat: https://www.bookstackapp.com'
    it_IT: 'Bookstack è una wiki gratuita e open source progettata per creare documentazione di grande impatto visivo. Grazie a un editor WYSIWYG semplice ma potente, permette ai team di creare documentazione dettagliata e utile con facilità. Basato su SQL e con un editor Markdown incluso per chi lo preferisce, BookStack è pensato per rendere la creazione di documentazione un''esperienza piacevole anziché un compito gravoso. Per maggiori informazioni su BookStack, visita il sito web ufficiale: https://www.bookstackapp.com'
    ja_JP: Bookstackは、美しいドキュメントを作成するために設計された、無料のオープンソースWikiです。シンプルながら強力なWYSIWYGエディタを搭載しており、チームが詳細かつ有用なドキュメントを簡単に作成できます。SQLを基盤とし、Markdownエディタも備えているため、ドキュメント作成を面倒な作業ではなく、より楽しいものにすることを目指しています。BookStackの詳細については、ウェブサイト（https://www.bookstackapp.com）をご覧ください。
    ko_KR: BookStack은 아름다운 문서를 만들 수 있도록 설계된 무료 오픈 소스 위키입니다. 간단하면서도 강력한 WYSIWYG 편집기를 통해 팀 구성원들이 상세하고 유용한 문서를 손쉽게 작성할 수 있습니다. SQL 기반으로 작동하며, 마크다운 편집기도 제공하여 문서 작성을 단순한 작업이 아닌 즐거운 경험으로 만들어 줍니다. BookStack에 대한 자세한 정보는 웹사이트(https://www.bookstackapp.com)에서 확인하세요.
    ml_IN: 'മനോഹരമായ ഡോക്യുമെന്റേഷൻ സൃഷ്ടിക്കുന്നതിനായി രൂപകൽപ്പന ചെയ്തിട്ടുള്ള ഒരു സ്വതന്ത്രവും ഓപ്പൺ സോഴ്‌സ് വിക്കിയാണ് ബുക്ക്‌സ്റ്റാക്ക്. ലളിതവും എന്നാൽ ശക്തവുമായ ഒരു WYSIWYG എഡിറ്റർ ഉള്ള ഇത് ടീമുകൾക്ക് വിശദവും ഉപയോഗപ്രദവുമായ ഡോക്യുമെന്റേഷൻ എളുപ്പത്തിൽ സൃഷ്ടിക്കാൻ അനുവദിക്കുന്നു. SQL നൽകുന്നതും അത് ഇഷ്ടപ്പെടുന്നവർക്ക് ഒരു മാർക്ക്ഡൗൺ എഡിറ്റർ ഉൾപ്പെടുത്തിയിരിക്കുന്നതുമായ ബുക്ക്‌സ്റ്റാക്ക്, ഡോക്യുമെന്റേഷനെ ഒരു ജോലിയേക്കാൾ കൂടുതൽ ആനന്ദകരമാക്കുന്നതിനാണ് ലക്ഷ്യമിടുന്നത്. ബുക്ക്‌സ്റ്റാക്കിനെക്കുറിച്ചുള്ള കൂടുതൽ വിവരങ്ങൾക്ക് അവരുടെ വെബ്‌സൈറ്റ് സന്ദർശിച്ച് ഇത് പരിശോധിക്കുക: https://www.bookstackapp.com'
    nb_NO: 'Bookstack er en gratis og åpen kildekode-wiki designet for å lage vakker dokumentasjon. Med en enkel, men kraftig WYSIWYG-editor kan team enkelt lage detaljert og nyttig dokumentasjon. BookStack er drevet av SQL og inkluderer en Markdown-editor for de som foretrekker det, og er rettet mot å gjøre dokumentasjon mer til en glede enn et ork. For mer informasjon om BookStack, besøk nettstedet deres og sjekk det ut: https://www.bookstackapp.com'
    nl_NL: 'Bookstack is een gratis en open source wiki, ontworpen voor het maken van prachtige documentatie. Met een eenvoudige maar krachtige WYSIWYG-editor kunnen teams gemakkelijk gedetailleerde en nuttige documentatie creëren. Bookstack draait op SQL en bevat een Markdown-editor voor wie daar de voorkeur aan geeft. Het doel van documentatie maken is om van een last een plezier te maken. Ga voor meer informatie over Bookstack naar hun website: https://www.bookstackapp.com'
    pl_PL: 'BookStack to darmowa i otwarta wiki przeznaczona do tworzenia pięknej dokumentacji. Dzięki prostemu, ale potężnemu edytorowi WYSIWYG, pozwala zespołom z łatwością tworzyć szczegółową i użyteczną dokumentację. Oparty na SQL i wyposażony w edytor Markdown dla tych, którzy preferują ten język, BookStack ma na celu sprawić, by dokumentacja była przyjemnością, a nie przykrym obowiązkiem. Aby uzyskać więcej informacji o BookStack, odwiedź ich stronę internetową: https://www.bookstackapp.com'
    pt_BR: 'O BookStack é um wiki gratuito e de código aberto projetado para criar documentação visualmente atraente. Com um editor WYSIWYG simples, porém poderoso, ele permite que equipes criem documentação detalhada e útil com facilidade. Baseado em SQL e incluindo um editor Markdown para quem preferir, o BookStack visa tornar a documentação mais prazerosa do que árdua. Para mais informações sobre o BookStack, visite o site: https://www.bookstackapp.com'
    ro_RO: 'Bookstack este un Wiki gratuit și open source, conceput pentru crearea de documentație atractivă. Dispunând de un editor WYSIWYG simplu, dar puternic, permite echipelor să creeze cu ușurință documentație detaliată și utilă. Bazat pe SQL și incluzând un editor Markdown pentru cei care îl preferă, BookStack este conceput pentru a face documentația mai mult o plăcere decât o corvoadă. Pentru mai multe informații despre BookStack, vizitați site-ul lor web și consultați-l: https://www.bookstackapp.com'
    ru_RU: 'Bookstack — это бесплатная вики-система с открытым исходным кодом, предназначенная для создания красивой документации. Благодаря простому, но мощному WYSIWYG-редактору, она позволяет командам с легкостью создавать подробную и полезную документацию. Работая на основе SQL и включая редактор Markdown для тех, кто предпочитает его, Bookstack стремится сделать создание документации удовольствием, а не рутиной. Для получения дополнительной информации о Bookstack посетите их веб-сайт и ознакомьтесь с ним: https://www.bookstackapp.com'
    sk_SK: 'Bookstack je bezplatná Wiki stránka s otvoreným zdrojovým kódom určená na vytváranie krásnej dokumentácie. Vďaka jednoduchému, ale výkonnému WYSIWYG editoru umožňuje tímom ľahko vytvárať podrobnú a užitočnú dokumentáciu. BookStack, ktorý je poháňaný jazykom SQL a obsahuje aj editor Markdown pre tých, ktorí ho uprednostňujú, je zameraný na to, aby bola dokumentácia skôr potešením ako povinnosťou. Viac informácií o BookStacku nájdete na ich webovej stránke: https://www.bookstackapp.com'
    sv_SE: 'Bookstack är en gratis och öppen källkodswiki utformad för att skapa vacker dokumentation. Med en enkel men kraftfull WYSIWYG-editor kan team enkelt skapa detaljerad och användbar dokumentation. BookStack drivs av SQL och inkluderar en Markdown-editor för de som föredrar det, och är inriktad på att göra dokumentation mer till ett nöje än ett besvär. För mer information om BookStack, besök deras webbplats och kolla in den: https://www.bookstackapp.com'
    tr_TR: 'Bookstack, güzel dokümantasyon oluşturmak için tasarlanmış ücretsiz ve açık kaynaklı bir Wiki''dir. Basit ama güçlü bir WYSIWYG editörüne sahip olan bu platform, ekiplerin detaylı ve kullanışlı dokümanları kolaylıkla oluşturmasına olanak tanır. SQL ile çalışan ve tercih edenler için Markdown editörü de içeren BookStack, dokümantasyonu bir angarya olmaktan ziyade bir zevk haline getirmeyi amaçlamaktadır. BookStack hakkında daha fazla bilgi için web sitelerini ziyaret edin ve inceleyin: https://www.bookstackapp.com'
    zh_CN: BookStack 是一款免费的开源 Wiki，专为创建美观的文档而设计。它提供简单而强大的所见即所得编辑器，让团队轻松编写详细实用的文档。BookStack 基于 SQL，并为有需要的用户提供 Markdown 编辑器，旨在让文档编写更轻松愉快。更多信息请访问：https://www.bookstackapp.com
    zh_TW: BookStack 是一款免費的開源 Wiki，專為建立美觀的文件而設計。它提供簡單而強大的所見即所得編輯器，讓團隊輕鬆編寫詳細實用的文件。BookStack 基於 SQL，併為有需要的使用者提供 Markdown 編輯器，旨在讓文件編寫更輕鬆愉快。更多資訊請訪問：https://www.bookstackapp.com
  tagline:
    en_US: 'A free and open source Wiki designed for creating beautiful documentation. Featuring a simple, but powerful WYSIWYG editor it allows for teams to create detailed and useful documentation with ease. Powered by SQL and including a Markdown editor for those who prefer it, BookStack is geared towards making documentation more of a pleasure than a chore. For more information on BookStack visit their website and check it out: https://www. Bookstackapp. Com'
    ca_ES: 'Un Wiki gratuït i de codi obert dissenyat per crear documentació atractiva. Amb un editor WYSIWYG senzill però potent, permet als equips crear documentació detallada i útil amb facilitat. Amb tecnologia SQL i un editor Markdown per a aquells que el prefereixen, BookStack està orientat a fer que la documentació sigui més un plaer que una feina. Per obtenir més informació sobre BookStack, visiteu el seu lloc web: https://www.Bookstackapp.Com'
    cs_CZ: 'Bezplatná a open source Wiki stránka určená pro tvorbu krásné dokumentace. Díky jednoduchému, ale výkonnému WYSIWYG editoru umožňuje týmům snadno vytvářet podrobnou a užitečnou dokumentaci. BookStack, poháněný SQL a včetně editoru Markdown pro ty, kteří ho preferují, je zaměřen na to, aby se dokumentace stala spíše potěšením než povinností. Více informací o BookStacku naleznete na jeho webových stránkách: https://www.Bookstackapp.com'
    da_DK: 'En gratis og open source-wiki designet til at skabe smuk dokumentation. Med en simpel, men kraftfuld WYSIWYG-editor kan teams nemt oprette detaljeret og nyttig dokumentation. BookStack er drevet af SQL og inkluderer en Markdown-editor for dem, der foretrækker det, og er gearet til at gøre dokumentation til en mere fornøjelse end en sur pligt. For mere information om BookStack, besøg deres hjemmeside og tjek den ud: https://www.Bookstackapp.com'
    de_DE: 'BookStack ist ein kostenloses Open-Source-Wiki, das speziell für die Erstellung ansprechender Dokumentationen entwickelt wurde. Mit seinem einfachen, aber leistungsstarken WYSIWYG-Editor ermöglicht es Teams, mühelos detaillierte und nützliche Dokumentationen zu erstellen. BookStack basiert auf SQL und bietet einen Markdown-Editor für alle, die diese Sprache bevorzugen. Ziel von BookStack ist es, die Dokumentation zum Vergnügen zu machen. Weitere Informationen zu BookStack finden Sie auf der Website: https://www.bookstackapp.com'
    el_GR: 'Ένα δωρεάν και ανοιχτού κώδικα Wiki σχεδιασμένο για τη δημιουργία όμορφης τεκμηρίωσης. Διαθέτοντας έναν απλό, αλλά ισχυρό επεξεργαστή WYSIWYG, επιτρέπει στις ομάδες να δημιουργούν εύκολα λεπτομερή και χρήσιμη τεκμηρίωση. Με την υποστήριξη της SQL και συμπεριλαμβανομένου ενός επεξεργαστή Markdown για όσους το προτιμούν, το BookStack έχει ως στόχο να κάνει την τεκμηρίωση περισσότερο μια ευχαρίστηση παρά μια αγγαρεία. Για περισσότερες πληροφορίες σχετικά με το BookStack, επισκεφθείτε την ιστοσελίδα τους και δείτε την: https://www.Bookstackapp.com'
    en_GB: 'A free and open source Wiki designed for creating beautiful documentation. Featuring a simple, but powerful Wysiwyg editor it allows for teams to create detailed and useful documentation with ease. Powered by Sql and including a Markdown editor for those who prefer it, Bookstack is geared towards making documentation more of a pleasure than a chore. For more information on Bookstack visit their website and check it out: https://www. Bookstackapp. Com'
    es_ES: 'Una wiki gratuita y de código abierto diseñada para crear documentación atractiva. Con un editor WYSIWYG sencillo pero potente, permite a los equipos crear documentación detallada y útil con facilidad. Impulsada por SQL e incluyendo un editor Markdown para quienes lo prefieran, BookStack está diseñada para que la creación de documentación sea un placer en lugar de una tarea tediosa. Para obtener más información sobre BookStack, visite su sitio web: https://www.bookstackapp.com'
    fr_FR: "BookStack est un wiki libre et open source conçu pour créer une documentation de qualité. Doté d'un éditeur WYSIWYG simple et puissant, il permet aux équipes de créer facilement une documentation détaillée et utile. Basé sur SQL et incluant un éditeur Markdown pour ceux qui le préfèrent, BookStack a pour objectif de rendre la documentation plus agréable que contraignante. Pour en savoir plus sur BookStack, rendez-vous sur leur site web\_: https://www.bookstackapp.com"
    ga_IE: 'Vicí foinse oscailte saor in aisce atá deartha chun doiciméadú álainn a chruthú. Le heagarthóir WYSIWYG simplí ach cumhachtach, tugann sé deis do fhoirne doiciméadú mionsonraithe agus úsáideach a chruthú go héasca. Cumhachtaithe ag SQL agus eagarthóir Markdown san áireamh dóibh siúd ar fearr leo é, tá BookStack dírithe ar dhoiciméadú a dhéanamh níos pléisiúir ná mar thasc. Le haghaidh tuilleadh eolais faoi BookStack, tabhair cuairt ar a suíomh Gréasáin agus féach air: https://www.Bookstackapp.com'
    hr_HR: 'Besplatni Wiki otvorenog koda dizajniran za izradu prekrasne dokumentacije. S jednostavnim, ali moćnim WYSIWYG uređivačem, omogućuje timovima jednostavno stvaranje detaljne i korisne dokumentacije. Pokretan SQL-om i uključujući Markdown uređivač za one koji ga preferiraju, BookStack je usmjeren na to da dokumentiranje učini više zadovoljstvom nego mukom. Za više informacija o BookStacku posjetite njihovu web stranicu: https://www.Bookstackapp.com'
    hu_HU: 'Egy ingyenes és nyílt forráskódú wiki, amelyet gyönyörű dokumentációk készítésére terveztek. Egy egyszerű, de hatékony WYSIWYG szerkesztővel a csapatok könnyedén készíthetnek részletes és hasznos dokumentációkat. Az SQL-alapú és Markdown szerkesztővel rendelkező BookStack célja, hogy a dokumentációt inkább élvezet, mint teher legyen. További információkért a BookStackről látogassa meg weboldalukat: https://www.Bookstackapp.Com'
    it_IT: 'Una wiki gratuita e open source progettata per creare documentazione di grande impatto visivo. Dotata di un editor WYSIWYG semplice ma potente, permette ai team di creare documentazione dettagliata e utile con facilità. Basata su SQL e con un editor Markdown incluso per chi lo preferisce, BookStack è pensata per rendere la creazione di documentazione un piacere anziché un compito gravoso. Per maggiori informazioni su BookStack, visita il sito web: https://www.Bookstackapp.com'
    ja_JP: BookStackは、美しいドキュメントを作成するために設計された、無料のオープンソースWikiです。シンプルながら強力なWYSIWYGエディタを搭載しており、チームが詳細で役立つドキュメントを簡単に作成できます。SQLを基盤とし、Markdownエディタも備えているため、ドキュメント作成を面倒な作業ではなく、楽しい作業にすることを目指しています。BookStackの詳細については、ウェブサイト（https://www.Bookstackapp.com）をご覧ください。
    ko_KR: BookStack은 아름다운 문서를 만들기 위해 설계된 무료 오픈 소스 위키입니다. 간단하지만 강력한 WYSIWYG 편집기를 통해 팀에서 상세하고 유용한 문서를 손쉽게 작성할 수 있습니다. SQL 기반으로 작동하며, 마크다운 편집기를 선호하는 사용자를 위해 Markdown 편집기도 제공하는 BookStack은 문서 작성을 단순한 작업이 아닌 즐거운 경험으로 만들어 줍니다. BookStack에 대한 자세한 정보는 웹사이트(https://www.Bookstackapp.com)에서 확인하세요.
    ml_IN: 'മനോഹരമായ ഡോക്യുമെന്റേഷൻ സൃഷ്ടിക്കുന്നതിനായി രൂപകൽപ്പന ചെയ്‌തിരിക്കുന്ന ഒരു സ്വതന്ത്രവും ഓപ്പൺ സോഴ്‌സ് വിക്കി. ലളിതവും എന്നാൽ ശക്തവുമായ WYSIWYG എഡിറ്റർ ഉള്ള ഇത് ടീമുകൾക്ക് വിശദവും ഉപയോഗപ്രദവുമായ ഡോക്യുമെന്റേഷൻ എളുപ്പത്തിൽ സൃഷ്ടിക്കാൻ അനുവദിക്കുന്നു. SQL നൽകുന്നതും അത് ഇഷ്ടപ്പെടുന്നവർക്ക് ഒരു മാർക്ക്ഡൗൺ എഡിറ്റർ ഉൾപ്പെടുത്തിയിരിക്കുന്നതുമായ ബുക്ക്‌സ്റ്റാക്ക്, ഡോക്യുമെന്റേഷനെ ഒരു ജോലിയേക്കാൾ കൂടുതൽ ആനന്ദകരമാക്കുന്നതിനാണ് ലക്ഷ്യമിടുന്നത്. ബുക്ക്‌സ്റ്റാക്കിനെക്കുറിച്ചുള്ള കൂടുതൽ വിവരങ്ങൾക്ക് അവരുടെ വെബ്‌സൈറ്റ് സന്ദർശിച്ച് ഇത് പരിശോധിക്കുക: https://www. Bookstackapp. Com'
    nb_NO: 'En gratis og åpen kildekode-wiki designet for å lage vakker dokumentasjon. Med en enkel, men kraftig WYSIWYG-editor kan team enkelt lage detaljert og nyttig dokumentasjon. BookStack er drevet av SQL og inkluderer en Markdown-editor for de som foretrekker det, og er rettet mot å gjøre dokumentasjon mer til en glede enn et ork. For mer informasjon om BookStack, besøk nettstedet deres og sjekk det ut: https://www.Bookstackapp.com'
    nl_NL: 'Een gratis en open source wiki, ontworpen voor het maken van prachtige documentatie. Met een eenvoudige maar krachtige WYSIWYG-editor kunnen teams gemakkelijk gedetailleerde en nuttige documentatie creëren. BookStack, aangedreven door SQL en inclusief een Markdown-editor voor wie daar de voorkeur aan geeft, is erop gericht om documentatie maken leuker te maken dan een vervelende klus. Ga voor meer informatie over BookStack naar hun website: https://www.Bookstackapp.com'
    pl_PL: 'Darmowa i otwarta wiki przeznaczona do tworzenia pięknej dokumentacji. Dzięki prostemu, ale potężnemu edytorowi WYSIWYG, BookStack pozwala zespołom z łatwością tworzyć szczegółową i użyteczną dokumentację. Oparty na SQL i wyposażony w edytor Markdown dla tych, którzy preferują ten język, BookStack ma na celu sprawić, by dokumentacja była przyjemnością, a nie przykrym obowiązkiem. Aby uzyskać więcej informacji o BookStack, odwiedź ich stronę internetową: https://www.Bookstackapp.com'
    pt_BR: 'Uma Wiki gratuita e de código aberto, projetada para criar documentação visualmente atraente. Com um editor WYSIWYG simples, porém poderoso, permite que equipes criem documentação detalhada e útil com facilidade. Baseada em SQL e incluindo um editor Markdown para quem preferir, a BookStack visa tornar a documentação mais prazerosa do que árdua. Para mais informações sobre a BookStack, visite o site: https://www.bookstackapp.com'
    ro_RO: 'Un Wiki gratuit și open source conceput pentru crearea de documentație frumoasă. Dispunând de un editor WYSIWYG simplu, dar puternic, permite echipelor să creeze cu ușurință documentație detaliată și utilă. Susținut de SQL și incluzând un editor Markdown pentru cei care îl preferă, BookStack este conceput pentru a face documentația mai mult o plăcere decât o corvoadă. Pentru mai multe informații despre BookStack, vizitați site-ul lor web și consultați-l: https://www.Bookstackapp.Com'
    ru_RU: 'Бесплатная вики-система с открытым исходным кодом, предназначенная для создания красивой документации. Благодаря простому, но мощному WYSIWYG-редактору, она позволяет командам с легкостью создавать подробную и полезную документацию. Работая на основе SQL и включая редактор Markdown для тех, кто предпочитает его, BookStack стремится сделать создание документации удовольствием, а не рутиной. Для получения дополнительной информации о BookStack посетите их веб-сайт: https://www.Bookstackapp.com'
    sk_SK: 'Bezplatná a open source Wiki stránka navrhnutá na vytváranie krásnej dokumentácie. Vďaka jednoduchému, ale výkonnému WYSIWYG editoru umožňuje tímom ľahko vytvárať podrobnú a užitočnú dokumentáciu. BookStack, ktorý je poháňaný jazykom SQL a obsahuje aj editor Markdown pre tých, ktorí ho uprednostňujú, je zameraný na to, aby bola dokumentácia skôr potešením ako povinnosťou. Viac informácií o BookStacku nájdete na ich webovej stránke: https://www.Bookstackapp.com'
    sv_SE: 'En gratis och öppen källkodswiki utformad för att skapa vacker dokumentation. Med en enkel men kraftfull WYSIWYG-editor kan team enkelt skapa detaljerad och användbar dokumentation. BookStack drivs av SQL och inkluderar en Markdown-editor för de som föredrar det, och är inriktad på att göra dokumentation mer till ett nöje än ett besvär. För mer information om BookStack, besök deras webbplats och kolla in den: https://www.Bookstackapp.com'
    tr_TR: 'Güzel dokümantasyon oluşturmak için tasarlanmış ücretsiz ve açık kaynaklı bir Wiki. Basit ama güçlü bir WYSIWYG editörüne sahip olan bu platform, ekiplerin detaylı ve kullanışlı dokümanları kolaylıkla oluşturmasına olanak tanır. SQL ile çalışan ve tercih edenler için Markdown editörü de içeren BookStack, dokümantasyonu bir angarya olmaktan ziyade bir zevk haline getirmeyi amaçlamaktadır. BookStack hakkında daha fazla bilgi için web sitelerini ziyaret edin ve inceleyin: https://www.Bookstackapp.com'
    zh_CN: 使用所见即所得或 Markdown 编辑器编写 Wiki 文档。
    zh_TW: 使用所見即所得或 Markdown 編輯器編寫 Wiki 文件。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bookstack-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bookstack-logo.png
  title:
    en_US: Bookstack (LinuxServer.io)
    ca_ES: Bookstack (LinuxServer.io)
    cs_CZ: Bookstack (LinuxServer.io)
    da_DK: Bookstack (LinuxServer.io)
    de_DE: Bookstack (LinuxServer.io)
    el_GR: Bookstack (LinuxServer.io)
    en_GB: Bookstack (LinuxServer.io)
    es_ES: Bookstack (LinuxServer.io)
    fr_FR: Bookstack (LinuxServer.io)
    ga_IE: Bookstack (LinuxServer.io)
    hr_HR: Bookstack (LinuxServer.io)
    hu_HU: Bookstack (LinuxServer.io)
    it_IT: Bookstack (LinuxServer.io)
    ja_JP: Bookstack (LinuxServer.io)
    ko_KR: Bookstack (LinuxServer.io)
    ml_IN: Bookstack (LinuxServer.io)
    nb_NO: Bookstack (LinuxServer.io)
    nl_NL: Bookstack (LinuxServer.io)
    pl_PL: Bookstack (LinuxServer.io)
    pt_BR: Bookstack (LinuxServer.io)
    ro_RO: Bookstack (LinuxServer.io)
    ru_RU: Bookstack (LinuxServer.io)
    sk_SK: Bookstack (LinuxServer.io)
    sv_SE: Bookstack (LinuxServer.io)
    tr_TR: Bookstack (LinuxServer.io)
    zh_CN: Bookstack（LinuxServer.io）
    zh_TW: Bookstack（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverbookstack
  port_map: '80'
  version: 26.05.5
