name: linuxserver-yq
services:
  app:
    image: linuxserver/yq:3.4.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/yq/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveryq/assets/icon.svg
  title:
    en_US: Yq
    zh_CN: Yq
    ca_ES: Yq
    cs_CZ: Yq
    da_DK: Yq
    de_DE: Yq
    el_GR: Yq
    en_GB: Yq
    es_ES: Yq
    fr_FR: Yq
    ga_IE: Yq
    hr_HR: Yq
    hu_HU: Yq
    it_IT: Yq
    ja_JP: Yq
    ko_KR: Yq
    ml_IN: Yq
    nb_NO: Yq
    nl_NL: Yq
    pl_PL: Yq
    pt_BR: Yq
    ro_RO: Yq
    ru_RU: Yq
    sk_SK: Yq
    sv_SE: Yq
    tr_TR: Yq
    zh_TW: Yq
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserveryq
  version: 3.4.3
