name: linuxserver-yq
services:
  app:
    image: linuxserver/yq:3.4.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/yq/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveryq/assets/icon.svg
  title:
    en_US: Yq
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserveryq
  version: 3.4.3
