name: linuxserver-pelorus
services:
  app:
    image: linuxserver/pelorus:0.2.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pelorus/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverpelorus/assets/icon.png
  title:
    en_US: Pelorus (LinuxServer.io)
    ca_ES: Pelorus (LinuxServer.io)
    cs_CZ: Pelorus (LinuxServer.io)
    da_DK: Pelorus (LinuxServer.io)
    de_DE: Pelorus (LinuxServer.io)
    el_GR: Pelorus (LinuxServer.io)
    en_GB: Pelorus (LinuxServer.io)
    es_ES: Pelorus (LinuxServer.io)
    fr_FR: Pelorus (LinuxServer.io)
    ga_IE: Pelorus (LinuxServer.io)
    hr_HR: Pelorus (LinuxServer.io)
    hu_HU: Pelorus (LinuxServer.io)
    it_IT: Pelorus (LinuxServer.io)
    ja_JP: Pelorus (LinuxServer.io)
    ko_KR: Pelorus (LinuxServer.io)
    ml_IN: Pelorus (LinuxServer.io)
    nb_NO: Pelorus (LinuxServer.io)
    nl_NL: Pelorus (LinuxServer.io)
    pl_PL: Pelorus (LinuxServer.io)
    pt_BR: Pelorus (LinuxServer.io)
    ro_RO: Pelorus (LinuxServer.io)
    ru_RU: Pelorus (LinuxServer.io)
    sk_SK: Pelorus (LinuxServer.io)
    sv_SE: Pelorus (LinuxServer.io)
    tr_TR: Pelorus (LinuxServer.io)
    zh_CN: Pelorus（LinuxServer.io）
    zh_TW: Pelorus（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverpelorus
  port_map: '3001'
  version: 0.2.3
