name: linuxserver-webcord
services:
  app:
    image: linuxserver/webcord:4.14.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webcord/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverwebcord/assets/icon.png
  title:
    en_US: Webcord (LinuxServer.io)
    ca_ES: Webcord (LinuxServer.io)
    cs_CZ: Webcord (LinuxServer.io)
    da_DK: Webcord (LinuxServer.io)
    de_DE: Webcord (LinuxServer.io)
    el_GR: Webcord (LinuxServer.io)
    en_GB: Webcord (LinuxServer.io)
    es_ES: Webcord (LinuxServer.io)
    fr_FR: Webcord (LinuxServer.io)
    ga_IE: Webcord (LinuxServer.io)
    hr_HR: Webcord (LinuxServer.io)
    hu_HU: Webcord (LinuxServer.io)
    it_IT: Webcord (LinuxServer.io)
    ja_JP: Webcord (LinuxServer.io)
    ko_KR: Webcord (LinuxServer.io)
    ml_IN: Webcord (LinuxServer.io)
    nb_NO: Webcord (LinuxServer.io)
    nl_NL: Webcord (LinuxServer.io)
    pl_PL: Webcord (LinuxServer.io)
    pt_BR: Webcord (LinuxServer.io)
    ro_RO: Webcord (LinuxServer.io)
    ru_RU: Webcord (LinuxServer.io)
    sk_SK: Webcord (LinuxServer.io)
    sv_SE: Webcord (LinuxServer.io)
    tr_TR: Webcord (LinuxServer.io)
    zh_CN: Webcord（LinuxServer.io）
    zh_TW: Webcord（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverwebcord
  port_map: '3000'
  version: 4.14.0
