name: linuxserver-webcord
services:
  app:
    image: linuxserver/webcord:4.14.0@sha256:ea33e7011ef0497e716e238ae1d9103446071e3c4873ab66aa05ddcb30e0fde7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webcord/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverwebcord/assets/icon.png
  title:
    en_US: Webcord (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverwebcord
  port_map: '3000'
  version: 4.14.0
