name: linuxserver-azahar
services:
  app:
    image: linuxserver/azahar:12125.1.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/azahar/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverazahar/assets/icon.png
  title:
    en_US: Azahar (LinuxServer.io)
    ca_ES: Azahar (LinuxServer.io)
    cs_CZ: Azahar (LinuxServer.io)
    da_DK: Azahar (LinuxServer.io)
    de_DE: Azahar (LinuxServer.io)
    el_GR: Azahar (LinuxServer.io)
    en_GB: Azahar (LinuxServer.io)
    es_ES: Azahar (LinuxServer.io)
    fr_FR: Azahar (LinuxServer.io)
    ga_IE: Azahar (LinuxServer.io)
    hr_HR: Azahar (LinuxServer.io)
    hu_HU: Azahar (LinuxServer.io)
    it_IT: Azahar (LinuxServer.io)
    ja_JP: Azahar (LinuxServer.io)
    ko_KR: Azahar (LinuxServer.io)
    ml_IN: Azahar (LinuxServer.io)
    nb_NO: Azahar (LinuxServer.io)
    nl_NL: Azahar (LinuxServer.io)
    pl_PL: Azahar (LinuxServer.io)
    pt_BR: Azahar (LinuxServer.io)
    ro_RO: Azahar (LinuxServer.io)
    ru_RU: Azahar (LinuxServer.io)
    sk_SK: Azahar (LinuxServer.io)
    sv_SE: Azahar (LinuxServer.io)
    tr_TR: Azahar (LinuxServer.io)
    zh_CN: Azahar（LinuxServer.io）
    zh_TW: Azahar（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverazahar
  port_map: '3000'
  version: 12125.1.3
