name: linuxserver-budge
services:
  app:
    image: linuxserver/budge:0.0.9@sha256:e4b88a2b3b262ea9187f451505afb85b3fd1c5ac19e7186d71bca236d986b743
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/budge/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverbudge/assets/icon.svg
  title:
    en_US: Budge (LinuxServer.io)
    ca_ES: Budge (LinuxServer.io)
    cs_CZ: Budge (LinuxServer.io)
    da_DK: Budge (LinuxServer.io)
    de_DE: Budge (LinuxServer.io)
    el_GR: Budge (LinuxServer.io)
    en_GB: Budge (LinuxServer.io)
    es_ES: Budge (LinuxServer.io)
    fr_FR: Budge (LinuxServer.io)
    ga_IE: Budge (LinuxServer.io)
    hr_HR: Budge (LinuxServer.io)
    hu_HU: Budge (LinuxServer.io)
    it_IT: Budge (LinuxServer.io)
    ja_JP: Budge (LinuxServer.io)
    ko_KR: Budge (LinuxServer.io)
    ml_IN: Budge (LinuxServer.io)
    nb_NO: Budge (LinuxServer.io)
    nl_NL: Budge (LinuxServer.io)
    pl_PL: Budge (LinuxServer.io)
    pt_BR: Budge (LinuxServer.io)
    ro_RO: Budge (LinuxServer.io)
    ru_RU: Budge (LinuxServer.io)
    sk_SK: Budge (LinuxServer.io)
    sv_SE: Budge (LinuxServer.io)
    tr_TR: Budge (LinuxServer.io)
    zh_CN: Budge（LinuxServer.io）
    zh_TW: Budge（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverbudge
  port_map: '80'
  version: 0.0.9
