name: linuxserver-airsonic-advanced
services:
  app:
    image: linuxserver/airsonic-advanced:11.1.4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONTEXT_PATH: ''
      JAVA_OPTS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: CONTEXT_PATH
          description:
            en_us: For setting url-base in reverse proxy setups. [OPTIONAL]
        - container: JAVA_OPTS
          description:
            en_us: For passing additional java options. [OPTIONAL]
    ports:
      - target: 4040
        published: 4040
        protocol: tcp
    volumes:
      - type: bind
        source: /srv/lsio/airsonic-advanced/config
        target: /config
      - type: bind
        source: /srv/lsio/airsonic-advanced/music
        target: /music
      - type: bind
        source: /srv/lsio/airsonic-advanced/playlists
        target: /playlists
      - type: bind
        source: /srv/lsio/airsonic-advanced/podcasts
        target: /podcasts
      - type: bind
        source: /srv/lsio/airsonic-advanced/media
        target: /media
x-casaos:
  architectures: []
  main: app
  description:
    en_us: Airsonic-advanced is a free, web-based media streamer, providing ubiquitious access to your music. Use it to share your music with friends, or to listen to your own music while at work. You can stream to multiple players simultaneously, for instance to one player in your kitchen and another in your living room.
  tagline:
    en_us: A free, web-based media streamer, providing ubiquitious access to your music. Use it to share your music with friends, or to listen to your own music while at work. You can stream to multiple players simultaneously, for instance to one player in your kitchen and another in your living room.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/airsonic-banner.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/airsonic-banner.png
  title:
    en_us: Airsonic advanced
  category: LinuxServer.io
