name: linuxserver-rawtherapee
services:
  app:
    image: linuxserver/rawtherapee:5.13.20260913@sha256:aff0919b9542f275a2179fe5fa31bf05e5c4e6095a57056ba25583829af42caf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rawtherapee/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverrawtherapee/assets/icon.png
  title:
    en_US: Rawtherapee (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverrawtherapee
  port_map: '3000'
  version: 5.13.20260913
