name: linuxserver-pycharm
services:
  app:
    image: linuxserver/pycharm:2026.2.1@sha256:97d071b4b8d39af81cff30da913f3e9943afd8f697db86c5018cd163cd0aa075
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pycharm/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverpycharm/assets/icon.png
  title:
    en_US: Pycharm (LinuxServer.io)
    ca_ES: Pycharm (LinuxServer.io)
    cs_CZ: Pycharm (LinuxServer.io)
    da_DK: Pycharm (LinuxServer.io)
    de_DE: Pycharm (LinuxServer.io)
    el_GR: Pycharm (LinuxServer.io)
    en_GB: Pycharm (LinuxServer.io)
    es_ES: Pycharm (LinuxServer.io)
    fr_FR: Pycharm (LinuxServer.io)
    ga_IE: Pycharm (LinuxServer.io)
    hr_HR: Pycharm (LinuxServer.io)
    hu_HU: Pycharm (LinuxServer.io)
    it_IT: Pycharm (LinuxServer.io)
    ja_JP: Pycharm (LinuxServer.io)
    ko_KR: Pycharm (LinuxServer.io)
    ml_IN: Pycharm (LinuxServer.io)
    nb_NO: Pycharm (LinuxServer.io)
    nl_NL: Pycharm (LinuxServer.io)
    pl_PL: Pycharm (LinuxServer.io)
    pt_BR: Pycharm (LinuxServer.io)
    ro_RO: Pycharm (LinuxServer.io)
    ru_RU: Pycharm (LinuxServer.io)
    sk_SK: Pycharm (LinuxServer.io)
    sv_SE: Pycharm (LinuxServer.io)
    tr_TR: Pycharm (LinuxServer.io)
    zh_CN: Pycharm（LinuxServer.io）
    zh_TW: Pycharm（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverpycharm
  port_map: '3000'
  version: 2026.2.1
