name: linuxserver-mediaelch
services:
  app:
    image: linuxserver/mediaelch:2.12.0@sha256:44f8fa57dfb43062a7e85ba32ac73e258e73e99fb194cea8eb1e70d81d7c87da
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mediaelch/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermediaelch/assets/icon.png
  title:
    en_US: Mediaelch (LinuxServer.io)
    ca_ES: Mediaelch (LinuxServer.io)
    cs_CZ: Mediaelch (LinuxServer.io)
    da_DK: Mediaelch (LinuxServer.io)
    de_DE: Mediaelch (LinuxServer.io)
    el_GR: Mediaelch (LinuxServer.io)
    en_GB: Mediaelch (LinuxServer.io)
    es_ES: Mediaelch (LinuxServer.io)
    fr_FR: Mediaelch (LinuxServer.io)
    ga_IE: Mediaelch (LinuxServer.io)
    hr_HR: Mediaelch (LinuxServer.io)
    hu_HU: Mediaelch (LinuxServer.io)
    it_IT: Mediaelch (LinuxServer.io)
    ja_JP: Mediaelch (LinuxServer.io)
    ko_KR: Mediaelch (LinuxServer.io)
    ml_IN: Mediaelch (LinuxServer.io)
    nb_NO: Mediaelch (LinuxServer.io)
    nl_NL: Mediaelch (LinuxServer.io)
    pl_PL: Mediaelch (LinuxServer.io)
    pt_BR: Mediaelch (LinuxServer.io)
    ro_RO: Mediaelch (LinuxServer.io)
    ru_RU: Mediaelch (LinuxServer.io)
    sk_SK: Mediaelch (LinuxServer.io)
    sv_SE: Mediaelch (LinuxServer.io)
    tr_TR: Mediaelch (LinuxServer.io)
    zh_CN: Mediaelch（LinuxServer.io）
    zh_TW: Mediaelch（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservermediaelch
  port_map: '3000'
  version: 2.12.0
