name: linuxserver-emulatorjs
services:
  app:
    image: linuxserver/emulatorjs:1.9.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SUBFOLDER: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
      - target: 4001
        published: 4001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/emulatorjs/config
        target: /config
      - type: bind
        source: /DATA/AppData/emulatorjs/data
        target: /data
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveremulatorjs/assets/icon.png
  title:
    en_US: Emulatorjs
    zh_CN: Emulatorjs
    ca_ES: Emulatorjs
    cs_CZ: Emulatorjs
    da_DK: Emulatorjs
    de_DE: Emulatorjs
    el_GR: Emulatorjs
    en_GB: Emulatorjs
    es_ES: Emulatorjs
    fr_FR: Emulatorjs
    ga_IE: Emulatorjs
    hr_HR: Emulatorjs
    hu_HU: Emulatorjs
    it_IT: Emulatorjs
    ja_JP: Emulatorjs
    ko_KR: Emulatorjs
    ml_IN: Emulatorjs
    nb_NO: Emulatorjs
    nl_NL: Emulatorjs
    pl_PL: Emulatorjs
    pt_BR: Emulatorjs
    ro_RO: Emulatorjs
    ru_RU: Emulatorjs
    sk_SK: Emulatorjs
    sv_SE: Emulatorjs
    tr_TR: Emulatorjs
    zh_TW: Emulatorjs
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserveremulatorjs
  version: 1.9.2
