name: linuxserver-brave
services:
  app:
    image: linuxserver/brave:1.95.102@sha256:d2f1e302122ab4fdb6fbb032570574161ea5996235193f8cfa20b5e81c0c1721
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/brave/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverbrave/assets/icon.png
  title:
    en_US: Brave (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverbrave
  port_map: '3000'
  version: 1.95.102
