name: linuxserver-ferdium
services:
  app:
    image: linuxserver/ferdium:7.2.3@sha256:10268610b78e0c259e107a14ede0f61e7d4e7ef9c9d1d4e2d20a1285446679cf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ferdium/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverferdium/assets/icon.png
  title:
    en_US: Ferdium (LinuxServer.io)
    zh_CN: Ferdium（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverferdium
  port_map: '3000'
  version: 7.2.3
