name: linuxserver-hedgedoc
services:
  app:
    image: linuxserver/hedgedoc:1.12.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_HOST: ''
      DB_PORT: ''
      DB_USER: ''
      DB_PASS: ''
      DB_NAME: ''
      CMD_DOMAIN: ''
      CMD_URL_ADDPORT: ''
      CMD_PROTOCOL_USESSL: ''
      CMD_PORT: ''
      CMD_ALLOW_ORIGIN: ''
      CMD_DB_DIALECT: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: DB_HOST
          description:
            en_US: Host address of mariadb database
        - container: DB_PORT
          description:
            en_US: Port to access mariadb database default is 3306
        - container: DB_USER
          description:
            en_US: Database user
        - container: DB_PASS
          description:
            en_US: Database password
        - container: DB_NAME
          description:
            en_US: Database name
        - container: CMD_DOMAIN
          description:
            en_US: The address the gui will be accessed at (ie. 192.168.1.1 or hedgedoc.domain.com).
        - container: CMD_URL_ADDPORT
          description:
            en_US: Set to true if using a port other than 80 or 443. [OPTIONAL]
        - container: CMD_PROTOCOL_USESSL
          description:
            en_US: Set to true if accessing over https via reverse proxy. [OPTIONAL]
        - container: CMD_PORT
          description:
            en_US: If you wish to access hedgedoc at a port different than 80, 443 or 3000, you need to set this to that port (ie. CMD_PORT=5000) and change the port mapping accordingly (5000:5000). [OPTIONAL]
        - container: CMD_ALLOW_ORIGIN
          description:
            en_US: Comma-separated list of allowed hostnames [OPTIONAL]
        - container: CMD_DB_DIALECT
          description:
            en_US: 'This variable allows selecting a database engine (if DB_HOST not set up). Available options are: mariadb, mysql, postgres, sqlite. [OPTIONAL]'
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/hedgedoc/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: HedgeDoc gives you access to all your files wherever you are. HedgeDoc is a real-time, multi-platform collaborative markdown note editor. This means that you can write notes with other people on your desktop, tablet or even on the phone. You can sign-in via multiple auth providers like Facebook, Twitter, GitHub and many more on the homepage.
    ca_ES: HedgeDoc et dóna accés a tots els teus fitxers allà on siguis. HedgeDoc és un editor de notes de markdown col·laboratiu en temps real i multiplataforma. Això vol dir que pots escriure notes amb altres persones a l'escriptori, la tauleta o fins i tot al telèfon. Pots iniciar sessió a través de diversos proveïdors d'autenticació com ara Facebook, Twitter, GitHub i molts més a la pàgina d'inici.
    cs_CZ: HedgeDoc vám poskytuje přístup ke všem vašim souborům, ať jste kdekoli. HedgeDoc je multiplatformní editor poznámek s možností spolupráce v reálném čase. To znamená, že si můžete psát poznámky s ostatními lidmi na počítači, tabletu nebo dokonce i na telefonu. Na domovské stránce se můžete přihlásit prostřednictvím více poskytovatelů ověřování, jako je Facebook, Twitter, GitHub a mnoho dalších.
    da_DK: HedgeDoc giver dig adgang til alle dine filer, uanset hvor du er. HedgeDoc er en realtids, multiplatform, samarbejdsbaseret editor til markdown-noter. Det betyder, at du kan skrive noter med andre personer på din computer, tablet eller endda på telefonen. Du kan logge ind via flere godkendelsesudbydere som Facebook, Twitter, GitHub og mange flere på hjemmesiden.
    de_DE: Mit HedgeDoc haben Sie jederzeit und überall Zugriff auf all Ihre Dateien. HedgeDoc ist ein plattformübergreifender Markdown-Notizeditor für die Zusammenarbeit in Echtzeit. So können Sie gemeinsam mit anderen auf Ihrem Desktop, Tablet oder Smartphone Notizen erstellen. Auf der Startseite können Sie sich über verschiedene Authentifizierungsanbieter wie Facebook, Twitter, GitHub und viele mehr anmelden.
    el_GR: Το HedgeDoc σάς παρέχει πρόσβαση σε όλα τα αρχεία σας όπου κι αν βρίσκεστε. Το HedgeDoc είναι ένα πρόγραμμα επεξεργασίας σημειώσεων σε πραγματικό χρόνο, πολλαπλών πλατφορμών. Αυτό σημαίνει ότι μπορείτε να γράφετε σημειώσεις με άλλα άτομα στον υπολογιστή σας, στο tablet ή ακόμα και στο τηλέφωνο. Μπορείτε να συνδεθείτε μέσω πολλαπλών παρόχων εξουσιοδότησης όπως το Facebook, το Twitter, το GitHub και πολλά άλλα στην αρχική σελίδα.
    en_GB: Hedgedoc gives you access to all your files wherever you are. Hedgedoc is a real-time, multi-platform collaborative markdown note editor. This means that you can write notes with other people on your desktop, tablet or even on the phone. You can sign-in via multiple auth providers like Facebook, Twitter, Github and many more on the homepage.
    es_ES: HedgeDoc te da acceso a todos tus archivos estés donde estés. HedgeDoc es un editor de notas Markdown colaborativo, multiplataforma y en tiempo real. Esto significa que puedes escribir notas con otras personas desde tu ordenador, tableta o incluso tu teléfono. Puedes iniciar sesión a través de múltiples proveedores de autenticación como Facebook, Twitter, GitHub y muchos más en la página principal.
    fr_FR: HedgeDoc vous permet d'accéder à tous vos fichiers où que vous soyez. HedgeDoc est un éditeur de notes Markdown collaboratif multiplateforme et en temps réel. Vous pouvez ainsi rédiger des notes avec d'autres personnes sur votre ordinateur, votre tablette ou même votre téléphone. Connectez-vous via différents fournisseurs d'authentification comme Facebook, Twitter, GitHub et bien d'autres, directement depuis la page d'accueil.
    ga_IE: Tugann HedgeDoc rochtain duit ar do chuid comhad go léir cibé áit a bhfuil tú. Is eagarthóir nótaí marcála síos comhoibríoch fíor-ama, il-ardáin é HedgeDoc. Ciallaíonn sé seo gur féidir leat nótaí a scríobh le daoine eile ar do dheasc, taibléad nó fiú ar an bhfón. Is féidir leat síniú isteach trí sholáthraithe údaraithe iolracha cosúil le Facebook, Twitter, GitHub agus go leor eile ar an leathanach baile.
    hr_HR: HedgeDoc vam omogućuje pristup svim vašim datotekama gdje god se nalazili. HedgeDoc je višeplatformski alat za uređivanje bilješki u stvarnom vremenu. To znači da možete pisati bilješke s drugim ljudima na računalu, tabletu ili čak na telefonu. Možete se prijaviti putem više pružatelja autorizacije poput Facebooka, Twittera, GitHuba i mnogih drugih na početnoj stranici.
    hu_HU: A HedgeDoc segítségével bárhonnan hozzáférhetsz az összes fájlodhoz. A HedgeDoc egy valós idejű, többplatformos, együttműködésen alapuló Markdown jegyzetszerkesztő. Ez azt jelenti, hogy jegyzeteket írhatsz másokkal együtt asztali számítógépeden, táblagépeden vagy akár telefonon is. A kezdőlapon több hitelesítési szolgáltatón, például Facebookon, Twitteren, GitHubon és sok máson keresztül is bejelentkezhetsz.
    it_IT: HedgeDoc ti dà accesso a tutti i tuoi file ovunque ti trovi. HedgeDoc è un editor di note collaborativo in Markdown, multipiattaforma e in tempo reale. Questo significa che puoi scrivere note con altre persone sul tuo computer, tablet o persino sul telefono. Puoi accedere tramite diversi provider di autenticazione come Facebook, Twitter, GitHub e molti altri direttamente dalla homepage.
    ja_JP: HedgeDocを使えば、どこにいてもすべてのファイルにアクセスできます。HedgeDocは、リアルタイムでマルチプラットフォームに対応した共同編集型マークダウンノートエディタです。つまり、デスクトップ、タブレット、スマートフォンなど、あらゆるデバイスで他のユーザーと共同でノートを作成できます。ホームページでは、Facebook、Twitter、GitHubなど、複数の認証プロバイダーからサインインできます。
    ko_KR: HedgeDoc을 사용하면 어디에 있든 모든 파일에 액세스할 수 있습니다. HedgeDoc은 실시간으로 여러 플랫폼에서 협업할 수 있는 마크다운 노트 편집기입니다. 즉, 데스크톱, 태블릿, 심지어 스마트폰에서도 다른 사람들과 함께 노트를 작성할 수 있습니다. 홈페이지에서 Facebook, Twitter, GitHub 등 다양한 인증 제공업체를 통해 로그인할 수 있습니다.
    ml_IN: നിങ്ങൾ എവിടെയായിരുന്നാലും നിങ്ങളുടെ എല്ലാ ഫയലുകളിലേക്കും HedgeDoc ആക്‌സസ് നൽകുന്നു. HedgeDoc ഒരു തത്സമയ, മൾട്ടി-പ്ലാറ്റ്‌ഫോം സഹകരണ മാർക്ക്ഡൗൺ നോട്ട് എഡിറ്ററാണ്. അതായത് നിങ്ങളുടെ ഡെസ്‌ക്‌ടോപ്പിലോ, ടാബ്‌ലെറ്റിലോ അല്ലെങ്കിൽ ഫോണിലോ പോലും മറ്റുള്ളവരുമായി കുറിപ്പുകൾ എഴുതാൻ കഴിയും. Facebook, Twitter, GitHub തുടങ്ങിയ ഒന്നിലധികം ഓത്ത് ദാതാക്കൾ വഴിയും ഹോംപേജിലെ മറ്റു പലതും വഴിയും നിങ്ങൾക്ക് സൈൻ-ഇൻ ചെയ്യാൻ കഴിയും.
    nb_NO: HedgeDoc gir deg tilgang til alle filene dine uansett hvor du er. HedgeDoc er en sanntids, samarbeidende redigeringsfunksjon for markdown-notater på flere plattformer. Dette betyr at du kan skrive notater med andre personer på datamaskinen, nettbrettet eller til og med på telefonen. Du kan logge på via flere autentiseringsleverandører som Facebook, Twitter, GitHub og mange flere på hjemmesiden.
    nl_NL: Met HedgeDoc heb je overal toegang tot al je bestanden. HedgeDoc is een realtime, platformonafhankelijke, samenwerkingsgerichte Markdown-notitie-editor. Dit betekent dat je samen met anderen notities kunt schrijven op je desktop, tablet of zelfs op je telefoon. Je kunt inloggen via verschillende authenticatieproviders zoals Facebook, Twitter, GitHub en nog veel meer op de homepage.
    pl_PL: HedgeDoc zapewnia dostęp do wszystkich plików, gdziekolwiek jesteś. HedgeDoc to wieloplatformowy, współpracujący w czasie rzeczywistym edytor notatek Markdown. Oznacza to, że możesz tworzyć notatki z innymi osobami na komputerze stacjonarnym, tablecie, a nawet telefonie. Możesz zalogować się za pośrednictwem wielu dostawców uwierzytelniania, takich jak Facebook, Twitter, GitHub i wielu innych, na stronie głównej.
    pt_BR: O HedgeDoc permite que você acesse todos os seus arquivos onde quer que esteja. O HedgeDoc é um editor de notas Markdown colaborativo e multiplataforma em tempo real. Isso significa que você pode escrever notas com outras pessoas no seu computador, tablet ou até mesmo no celular. Você pode fazer login usando diversos provedores de autenticação, como Facebook, Twitter, GitHub e muitos outros, na página inicial.
    ro_RO: HedgeDoc vă oferă acces la toate fișierele dvs. oriunde v-ați afla. HedgeDoc este un editor de notițe markdown colaborativ, multi-platformă, în timp real. Aceasta înseamnă că puteți scrie notițe împreună cu alte persoane pe desktop, tabletă sau chiar pe telefon. Vă puteți conecta prin intermediul mai multor furnizori de autentificare, cum ar fi Facebook, Twitter, GitHub și mulți alții, pe pagina principală.
    ru_RU: HedgeDoc предоставляет вам доступ ко всем вашим файлам, где бы вы ни находились. HedgeDoc — это редактор заметок Markdown для совместной работы в режиме реального времени на нескольких платформах. Это означает, что вы можете писать заметки с другими людьми на своем компьютере, планшете или даже телефоне. Вы можете войти в систему через различные системы аутентификации, такие как Facebook, Twitter, GitHub и многие другие, на главной странице.
    sk_SK: HedgeDoc vám poskytuje prístup ku všetkým vašim súborom, nech ste kdekoľvek. HedgeDoc je multiplatformový editor poznámok v reálnom čase, ktorý umožňuje spoluprácu pri písaní poznámok. To znamená, že si môžete písať poznámky s ostatnými ľuďmi na počítači, tablete alebo dokonca na telefóne. Na domovskej stránke sa môžete prihlásiť prostredníctvom viacerých poskytovateľov autorizácie, ako sú Facebook, Twitter, GitHub a mnoho ďalších.
    sv_SE: HedgeDoc ger dig tillgång till alla dina filer var du än är. HedgeDoc är en realtidsredigerare för flera plattformar och samarbetsinriktad anteckningshantering. Det betyder att du kan skriva anteckningar med andra personer på din dator, surfplatta eller till och med på telefonen. Du kan logga in via flera autentiseringsleverantörer som Facebook, Twitter, GitHub och många fler på startsidan.
    tr_TR: HedgeDoc, nerede olursanız olun tüm dosyalarınıza erişmenizi sağlar. HedgeDoc, gerçek zamanlı, çok platformlu, işbirlikçi bir Markdown not düzenleyicisidir. Bu, masaüstünüzde, tabletinizde veya hatta telefonunuzda diğer kişilerle birlikte not yazabileceğiniz anlamına gelir. Ana sayfada Facebook, Twitter, GitHub ve daha birçok kimlik doğrulama sağlayıcısı aracılığıyla oturum açabilirsiniz.
    zh_CN: HedgeDoc 让你随时随地访问文件，是一款实时、跨平台协作 Markdown 笔记编辑器。你可以与他人在桌面电脑、平板电脑或手机上共同编写笔记，并通过 Facebook、Twitter、GitHub 等多种身份验证服务登录。
    zh_TW: HedgeDoc 讓你隨時隨地訪問檔案，是一款實時、跨平臺協作 Markdown 筆記編輯器。你可以與他人在桌面電腦、平板電腦或手機上共同編寫筆記，並透過 Facebook、Twitter、GitHub 等多種身份驗證服務登入。
  tagline:
    en_US: Gives you access to all your files wherever you are. HedgeDoc is a real-time, multi-platform collaborative markdown note editor. This means that you can write notes with other people on your desktop, tablet or even on the phone. You can sign-in via multiple auth providers like Facebook, Twitter, GitHub and many more on the homepage.
    ca_ES: Et dóna accés a tots els teus fitxers allà on siguis. HedgeDoc és un editor de notes de markdown col·laboratiu en temps real i multiplataforma. Això vol dir que pots escriure notes amb altres persones a l'escriptori, la tauleta o fins i tot al telèfon. Pots iniciar sessió a través de diversos proveïdors d'autenticació com ara Facebook, Twitter, GitHub i molts més a la pàgina d'inici.
    cs_CZ: Umožňuje vám přístup ke všem vašim souborům, ať jste kdekoli. HedgeDoc je multiplatformní editor poznámek s možností spolupráce v reálném čase. To znamená, že si můžete psát poznámky s ostatními lidmi na počítači, tabletu nebo dokonce i na telefonu. Na domovské stránce se můžete přihlásit prostřednictvím více poskytovatelů ověřování, jako je Facebook, Twitter, GitHub a mnoho dalších.
    da_DK: Giver dig adgang til alle dine filer, uanset hvor du er. HedgeDoc er en realtids, multiplatform samarbejdsbaseret note-editor til markdowns. Det betyder, at du kan skrive noter med andre personer på din computer, tablet eller endda på telefonen. Du kan logge ind via flere godkendelsesudbydere som Facebook, Twitter, GitHub og mange flere på hjemmesiden.
    de_DE: Mit HedgeDoc haben Sie jederzeit und überall Zugriff auf all Ihre Dateien. HedgeDoc ist ein plattformübergreifender Markdown-Notizeditor für die Zusammenarbeit in Echtzeit. So können Sie gemeinsam mit anderen auf Ihrem Desktop, Tablet oder Smartphone Notizen erstellen. Auf der Startseite können Sie sich über verschiedene Authentifizierungsanbieter wie Facebook, Twitter, GitHub und viele mehr anmelden.
    el_GR: Σας δίνει πρόσβαση σε όλα τα αρχεία σας όπου κι αν βρίσκεστε. Το HedgeDoc είναι ένα πρόγραμμα επεξεργασίας σημειώσεων σε πραγματικό χρόνο, πολλαπλών πλατφορμών. Αυτό σημαίνει ότι μπορείτε να γράφετε σημειώσεις με άλλα άτομα στον υπολογιστή σας, στο tablet ή ακόμα και στο τηλέφωνο. Μπορείτε να συνδεθείτε μέσω πολλαπλών παρόχων εξουσιοδότησης όπως το Facebook, το Twitter, το GitHub και πολλά άλλα στην αρχική σελίδα.
    en_GB: Gives you access to all your files wherever you are. Hedgedoc is a real-time, multi-platform collaborative markdown note editor. This means that you can write notes with other people on your desktop, tablet or even on the phone. You can sign-in via multiple auth providers like Facebook, Twitter, Github and many more on the homepage.
    es_ES: Te da acceso a todos tus archivos estés donde estés. HedgeDoc es un editor de notas Markdown colaborativo, multiplataforma y en tiempo real. Esto significa que puedes escribir notas con otras personas desde tu ordenador, tableta o incluso tu teléfono. Puedes iniciar sesión a través de múltiples proveedores de autenticación como Facebook, Twitter, GitHub y muchos más en la página principal.
    fr_FR: Accédez à tous vos fichiers où que vous soyez. HedgeDoc est un éditeur de notes Markdown collaboratif multiplateforme et en temps réel. Vous pouvez ainsi rédiger des notes avec d'autres personnes sur votre ordinateur, votre tablette ou même votre téléphone. Connectez-vous via différents fournisseurs d'authentification comme Facebook, Twitter, GitHub et bien d'autres, directement depuis la page d'accueil.
    ga_IE: Tugann sé rochtain duit ar do chuid comhad go léir cibé áit a bhfuil tú. Is eagarthóir nótaí marcála síos comhoibríoch fíor-ama, il-ardáin é HedgeDoc. Ciallaíonn sé seo gur féidir leat nótaí a scríobh le daoine eile ar do dheasc, taibléad nó fiú ar an bhfón. Is féidir leat síniú isteach trí sholáthraithe údaraithe iolracha cosúil le Facebook, Twitter, GitHub agus go leor eile ar an leathanach baile.
    hr_HR: Omogućuje vam pristup svim vašim datotekama gdje god se nalazili. HedgeDoc je višeplatformski alat za uređivanje bilješki u stvarnom vremenu. To znači da možete pisati bilješke s drugim ljudima na računalu, tabletu ili čak na telefonu. Možete se prijaviti putem više pružatelja autorizacije poput Facebooka, Twittera, GitHuba i mnogih drugih na početnoj stranici.
    hu_HU: Hozzáférést biztosít minden fájlodhoz, bárhonnan is legyél. A HedgeDoc egy valós idejű, több platformon futó, együttműködő Markdown jegyzetszerkesztő. Ez azt jelenti, hogy jegyzeteket írhatsz másokkal együtt asztali számítógépeden, táblagépeden vagy akár telefonon is. A kezdőlapon több hitelesítési szolgáltatón, például Facebookon, Twitteren, GitHubon és sok máson keresztül is bejelentkezhetsz.
    it_IT: Ti dà accesso a tutti i tuoi file ovunque tu sia. HedgeDoc è un editor di note collaborativo in Markdown, multipiattaforma e in tempo reale. Questo significa che puoi scrivere note con altre persone sul tuo computer, tablet o persino sul telefono. Puoi accedere tramite diversi provider di autenticazione come Facebook, Twitter, GitHub e molti altri direttamente dalla homepage.
    ja_JP: どこにいてもすべてのファイルにアクセスできます。HedgeDocは、リアルタイムでマルチプラットフォームに対応した共同編集型マークダウンノートエディタです。つまり、デスクトップ、タブレット、スマートフォンなど、あらゆるデバイスで他のユーザーと共同でノートを作成できます。ホームページでは、Facebook、Twitter、GitHubなど、複数の認証プロバイダーからサインインできます。
    ko_KR: 어디에 있든 모든 파일에 액세스할 수 있습니다. HedgeDoc은 실시간으로 여러 플랫폼에서 사용할 수 있는 공동 작업 마크다운 노트 편집기입니다. 데스크톱, 태블릿, 심지어 스마트폰에서도 다른 사람들과 함께 노트를 작성할 수 있습니다. 홈페이지에서 Facebook, Twitter, GitHub 등 다양한 인증 제공업체를 통해 로그인할 수 있습니다.
    ml_IN: നിങ്ങൾ എവിടെയായിരുന്നാലും നിങ്ങളുടെ എല്ലാ ഫയലുകളിലേക്കും ആക്‌സസ് നൽകുന്നു. ഹെഡ്ജ്ഡോക് ഒരു തത്സമയ, മൾട്ടി-പ്ലാറ്റ്‌ഫോം സഹകരണ മാർക്ക്ഡൗൺ നോട്ട് എഡിറ്ററാണ്. അതായത് നിങ്ങളുടെ ഡെസ്‌ക്‌ടോപ്പിലോ, ടാബ്‌ലെറ്റിലോ അല്ലെങ്കിൽ ഫോണിലോ പോലും മറ്റുള്ളവരുമായി കുറിപ്പുകൾ എഴുതാൻ കഴിയും. ഹോംപേജിലെ Facebook, Twitter, GitHub തുടങ്ങിയ ഒന്നിലധികം ഓത്ത് ദാതാക്കൾ വഴി നിങ്ങൾക്ക് സൈൻ-ഇൻ ചെയ്യാൻ കഴിയും.
    nb_NO: Gir deg tilgang til alle filene dine uansett hvor du er. HedgeDoc er en sanntids, samarbeidende redigeringsfunksjon for markdown-notater på flere plattformer. Dette betyr at du kan skrive notater med andre personer på datamaskinen, nettbrettet eller til og med på telefonen. Du kan logge på via flere autentiseringsleverandører som Facebook, Twitter, GitHub og mange flere på hjemmesiden.
    nl_NL: Met HedgeDoc heb je overal toegang tot al je bestanden. Het is een realtime, platformonafhankelijke, samenwerkingsgerichte Markdown-notitie-editor. Dit betekent dat je samen met anderen notities kunt schrijven op je desktop, tablet of zelfs op je telefoon. Je kunt inloggen via verschillende authenticatieproviders zoals Facebook, Twitter, GitHub en nog veel meer op de homepage.
    pl_PL: Zapewnia dostęp do wszystkich plików, gdziekolwiek jesteś. HedgeDoc to wieloplatformowy, współpracujący edytor notatek Markdown w czasie rzeczywistym. Oznacza to, że możesz tworzyć notatki z innymi osobami na komputerze stacjonarnym, tablecie, a nawet telefonie. Możesz zalogować się za pośrednictwem wielu dostawców uwierzytelniania, takich jak Facebook, Twitter, GitHub i wielu innych, na stronie głównej.
    pt_BR: Permite que você acesse todos os seus arquivos onde quer que esteja. O HedgeDoc é um editor de notas Markdown colaborativo, multiplataforma e em tempo real. Isso significa que você pode escrever notas com outras pessoas no seu computador, tablet ou até mesmo no celular. Você pode fazer login usando diversos provedores de autenticação, como Facebook, Twitter, GitHub e muitos outros, na página inicial.
    ro_RO: Îți oferă acces la toate fișierele tale oriunde te-ai afla. HedgeDoc este un editor de notițe markdown colaborativ, multi-platformă, în timp real. Aceasta înseamnă că poți scrie notițe împreună cu alte persoane pe desktop, tabletă sau chiar pe telefon. Te poți conecta prin intermediul mai multor furnizori de autentificare, cum ar fi Facebook, Twitter, GitHub și mulți alții, pe pagina principală.
    ru_RU: Предоставляет доступ ко всем вашим файлам, где бы вы ни находились. HedgeDoc — это редактор заметок Markdown для совместной работы в режиме реального времени на нескольких платформах. Это означает, что вы можете писать заметки с другими людьми на своем компьютере, планшете или даже телефоне. Вы можете войти в систему через различные системы аутентификации, такие как Facebook, Twitter, GitHub и многие другие, на главной странице.
    sk_SK: Poskytuje vám prístup ku všetkým vašim súborom, nech ste kdekoľvek. HedgeDoc je multiplatformový editor poznámok s možnosťou spolupráce v reálnom čase. To znamená, že si môžete písať poznámky s ostatnými ľuďmi na počítači, tablete alebo dokonca na telefóne. Na domovskej stránke sa môžete prihlásiť prostredníctvom viacerých poskytovateľov autorizácie, ako sú Facebook, Twitter, GitHub a mnoho ďalších.
    sv_SE: Ger dig tillgång till alla dina filer var du än är. HedgeDoc är en realtidsredigerare för flera plattformar och samarbetsinriktad anteckningshantering. Det betyder att du kan skriva anteckningar med andra personer på din dator, surfplatta eller till och med på telefonen. Du kan logga in via flera autentiseringsleverantörer som Facebook, Twitter, GitHub och många fler på startsidan.
    tr_TR: Nerede olursanız olun tüm dosyalarınıza erişmenizi sağlar. HedgeDoc, gerçek zamanlı, çok platformlu, işbirlikçi bir Markdown not düzenleyicisidir. Bu, masaüstünüzde, tabletinizde veya hatta telefonunuzda diğer kişilerle birlikte not yazabileceğiniz anlamına gelir. Ana sayfada Facebook, Twitter, GitHub ve daha birçok kimlik doğrulama sağlayıcısı aracılığıyla oturum açabilirsiniz.
    zh_CN: 跨设备实时协作编写 Markdown 笔记。
    zh_TW: 跨裝置實時協作編寫 Markdown 筆記。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hedgedoc-banner.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hedgedoc-banner.png
  title:
    en_US: Hedgedoc (LinuxServer.io)
    ca_ES: Hedgedoc (LinuxServer.io)
    cs_CZ: Hedgedoc (LinuxServer.io)
    da_DK: Hedgedoc (LinuxServer.io)
    de_DE: Hedgedoc (LinuxServer.io)
    el_GR: Hedgedoc (LinuxServer.io)
    en_GB: Hedgedoc (LinuxServer.io)
    es_ES: Hedgedoc (LinuxServer.io)
    fr_FR: Hedgedoc (LinuxServer.io)
    ga_IE: Hedgedoc (LinuxServer.io)
    hr_HR: Hedgedoc (LinuxServer.io)
    hu_HU: Hedgedoc (LinuxServer.io)
    it_IT: Hedgedoc (LinuxServer.io)
    ja_JP: Hedgedoc (LinuxServer.io)
    ko_KR: Hedgedoc (LinuxServer.io)
    ml_IN: Hedgedoc (LinuxServer.io)
    nb_NO: Hedgedoc (LinuxServer.io)
    nl_NL: Hedgedoc (LinuxServer.io)
    pl_PL: Hedgedoc (LinuxServer.io)
    pt_BR: Hedgedoc (LinuxServer.io)
    ro_RO: Hedgedoc (LinuxServer.io)
    ru_RU: Hedgedoc (LinuxServer.io)
    sk_SK: Hedgedoc (LinuxServer.io)
    sv_SE: Hedgedoc (LinuxServer.io)
    tr_TR: Hedgedoc (LinuxServer.io)
    zh_CN: Hedgedoc（LinuxServer.io）
    zh_TW: Hedgedoc（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverhedgedoc
  port_map: '3000'
  version: 1.12.0
