name: linuxserver-modmanager
services:
  app:
    image: linuxserver/modmanager:version-7dc8618e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/modmanager/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermodmanager/assets/icon.png
  title:
    en_US: Modmanager (LinuxServer.io)
    ca_ES: Modmanager (LinuxServer.io)
    cs_CZ: Modmanager (LinuxServer.io)
    da_DK: Modmanager (LinuxServer.io)
    de_DE: Modmanager (LinuxServer.io)
    el_GR: Modmanager (LinuxServer.io)
    en_GB: Modmanager (LinuxServer.io)
    es_ES: Modmanager (LinuxServer.io)
    fr_FR: Modmanager (LinuxServer.io)
    ga_IE: Modmanager (LinuxServer.io)
    hr_HR: Modmanager (LinuxServer.io)
    hu_HU: Modmanager (LinuxServer.io)
    it_IT: Modmanager (LinuxServer.io)
    ja_JP: Modmanager (LinuxServer.io)
    ko_KR: Modmanager (LinuxServer.io)
    ml_IN: Modmanager (LinuxServer.io)
    nb_NO: Modmanager (LinuxServer.io)
    nl_NL: Modmanager (LinuxServer.io)
    pl_PL: Modmanager (LinuxServer.io)
    pt_BR: Modmanager (LinuxServer.io)
    ro_RO: Modmanager (LinuxServer.io)
    ru_RU: Modmanager (LinuxServer.io)
    sk_SK: Modmanager (LinuxServer.io)
    sv_SE: Modmanager (LinuxServer.io)
    tr_TR: Modmanager (LinuxServer.io)
    zh_CN: Modmanager（LinuxServer.io）
    zh_TW: Modmanager（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservermodmanager
  port_map: '80'
  version: version-7dc8618e
