name: linuxserver-modmanager
services:
  app:
    image: linuxserver/modmanager:version-7dc8618e@sha256:de99e79b9f9234cb5ad8b7417a2addb3a8249399ce853fb61f9c7298354564bc
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/modmanager/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermodmanager/assets/icon.png
  title:
    en_US: Modmanager (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxservermodmanager
  port_map: '80'
  version: version-7dc8618e
