name: linuxserver-homeassistant
services:
  app:
    image: linuxserver/homeassistant:2026.9.2@sha256:5a192eb1f56914c9e1a84e2a790f630150b26b22dbc1a99184ad96e701b830e0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8123
        published: 8123
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/homeassistant/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverhomeassistant/assets/icon.png
  title:
    en_US: Homeassistant (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverhomeassistant
  port_map: '8123'
  version: 2026.9.2
