name: linuxserver-faster-whisper
services:
  app:
    image: linuxserver/faster-whisper:3.8.1@sha256:08dca98cc664dd5ccbd6e3f07b8d0937b6a17e1bd7d14a512a43813973ebf79e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DEBUG: ''
      LOCAL_ONLY: ''
      WHISPER_BEAM: ''
      WHISPER_LANG: ''
      WHISPER_MODEL: ''
    ports:
      - target: 10300
        published: 10300
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/faster-whisper/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfasterwhisper/assets/icon.svg
  title:
    en_US: Faster whisper (LinuxServer.io)
    zh_CN: Faster whisper（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverfasterwhisper
  port_map: '10300'
  version: 3.8.1
