name: linuxserver-faster-whisper
services:
  app:
    image: linuxserver/faster-whisper:3.8.1@sha256:bcfd75d43732ddde47d811e089d4d192bcd0196c41b66b5d0a68a7bda5efc67a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DEBUG: ''
      LOCAL_ONLY: ''
      WHISPER_BEAM: ''
      WHISPER_LANG: ''
      WHISPER_MODEL: ''
    ports:
      - target: 10300
        published: 10300
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/faster-whisper/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfasterwhisper/assets/icon.svg
  title:
    en_US: Faster whisper (LinuxServer.io)
    ca_ES: Faster whisper (LinuxServer.io)
    cs_CZ: Faster whisper (LinuxServer.io)
    da_DK: Faster whisper (LinuxServer.io)
    de_DE: Faster whisper (LinuxServer.io)
    el_GR: Faster whisper (LinuxServer.io)
    en_GB: Faster whisper (LinuxServer.io)
    es_ES: Faster whisper (LinuxServer.io)
    fr_FR: Faster whisper (LinuxServer.io)
    ga_IE: Faster whisper (LinuxServer.io)
    hr_HR: Faster whisper (LinuxServer.io)
    hu_HU: Faster whisper (LinuxServer.io)
    it_IT: Faster whisper (LinuxServer.io)
    ja_JP: Faster whisper (LinuxServer.io)
    ko_KR: Faster whisper (LinuxServer.io)
    ml_IN: Faster whisper (LinuxServer.io)
    nb_NO: Faster whisper (LinuxServer.io)
    nl_NL: Faster whisper (LinuxServer.io)
    pl_PL: Faster whisper (LinuxServer.io)
    pt_BR: Faster whisper (LinuxServer.io)
    ro_RO: Faster whisper (LinuxServer.io)
    ru_RU: Faster whisper (LinuxServer.io)
    sk_SK: Faster whisper (LinuxServer.io)
    sv_SE: Faster whisper (LinuxServer.io)
    tr_TR: Faster whisper (LinuxServer.io)
    zh_CN: Faster whisper（LinuxServer.io）
    zh_TW: Faster whisper（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverfasterwhisper
  port_map: '10300'
  version: 3.8.1
