name: linuxserver-intellij-idea
services:
  app:
    image: linuxserver/intellij-idea:42026.2.2@sha256:2e7732cfabbc01bb64aa54adba84561361b44a89b8ed652a64c7ce9e8d98f9a9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/intellij-idea/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverintellijidea/assets/icon.png
  title:
    en_US: Intellij idea (LinuxServer.io)
    zh_CN: Intellij idea（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverintellijidea
  port_map: '3000'
  version: 42026.2.2
