name: linuxserver-ffmpeg
services:
  app:
    image: linuxserver/ffmpeg:8.1.2@sha256:8e412a7a8bdbb65df95afced960f34ac1e7a8b90c17501b7c774053c08d18e25
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ffmpeg/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverffmpeg/assets/icon.png
  title:
    en_US: Ffmpeg (LinuxServer.io)
    zh_CN: Ffmpeg（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverffmpeg
  port_map: '80'
  version: 8.1.2
