name: linuxserver-tautulli
services:
  app:
    image: linuxserver/tautulli:2.18.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/tautulli/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Tautulli is a python based web application for monitoring, analytics and notifications for Plex Media Server.
    zh_CN: Tautulli 是基于 Python 的网页应用，为 Plex Media Server 提供监控、分析和通知功能。
  tagline:
    en_US: A python based web application for monitoring, analytics and notifications for Plex Media Server.
    zh_CN: 监控和分析 Plex Media Server，并发送通知。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/tautulli-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/tautulli-icon.png
  title:
    en_US: Tautulli (LinuxServer.io)
    zh_CN: Tautulli（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxservertautulli
  port_map: '8181'
  version: 2.18.1
