name: linuxserver-qdirstat
services:
  app:
    image: linuxserver/qdirstat:2.0.20260913
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/qdirstat/config
        target: /config
      - type: bind
        source: /DATA/AppData/qdirstat/data
        target: /data
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverqdirstat/assets/icon.png
  title:
    en_US: Qdirstat (LinuxServer.io)
    ca_ES: Qdirstat (LinuxServer.io)
    cs_CZ: Qdirstat (LinuxServer.io)
    da_DK: Qdirstat (LinuxServer.io)
    de_DE: Qdirstat (LinuxServer.io)
    el_GR: Qdirstat (LinuxServer.io)
    en_GB: Qdirstat (LinuxServer.io)
    es_ES: Qdirstat (LinuxServer.io)
    fr_FR: Qdirstat (LinuxServer.io)
    ga_IE: Qdirstat (LinuxServer.io)
    hr_HR: Qdirstat (LinuxServer.io)
    hu_HU: Qdirstat (LinuxServer.io)
    it_IT: Qdirstat (LinuxServer.io)
    ja_JP: Qdirstat (LinuxServer.io)
    ko_KR: Qdirstat (LinuxServer.io)
    ml_IN: Qdirstat (LinuxServer.io)
    nb_NO: Qdirstat (LinuxServer.io)
    nl_NL: Qdirstat (LinuxServer.io)
    pl_PL: Qdirstat (LinuxServer.io)
    pt_BR: Qdirstat (LinuxServer.io)
    ro_RO: Qdirstat (LinuxServer.io)
    ru_RU: Qdirstat (LinuxServer.io)
    sk_SK: Qdirstat (LinuxServer.io)
    sv_SE: Qdirstat (LinuxServer.io)
    tr_TR: Qdirstat (LinuxServer.io)
    zh_CN: Qdirstat（LinuxServer.io）
    zh_TW: Qdirstat（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverqdirstat
  port_map: '3000'
  version: 2.0.20260913
