name: linuxserver-calibre-web
services:
  app:
    image: linuxserver/calibre-web:0.6.27
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DOCKER_MODS: ''
      OAUTHLIB_RELAX_TOKEN_SCOPE: ''
    ports:
      - target: 8083
        published: 8083
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/calibre-web/config
        target: /config
      - type: bind
        source: /DATA/AppData/calibre-web/books
        target: /books
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservercalibreweb/assets/icon.png
  title:
    en_US: Calibre web (LinuxServer.io)
    ca_ES: Calibre web (LinuxServer.io)
    cs_CZ: Calibre web (LinuxServer.io)
    da_DK: Calibre web (LinuxServer.io)
    de_DE: Calibre web (LinuxServer.io)
    el_GR: Calibre web (LinuxServer.io)
    en_GB: Calibre web (LinuxServer.io)
    es_ES: Calibre web (LinuxServer.io)
    fr_FR: Calibre web (LinuxServer.io)
    ga_IE: Calibre web (LinuxServer.io)
    hr_HR: Calibre web (LinuxServer.io)
    hu_HU: Calibre web (LinuxServer.io)
    it_IT: Calibre web (LinuxServer.io)
    ja_JP: Calibre web (LinuxServer.io)
    ko_KR: Calibre web (LinuxServer.io)
    ml_IN: Calibre web (LinuxServer.io)
    nb_NO: Calibre web (LinuxServer.io)
    nl_NL: Calibre web (LinuxServer.io)
    pl_PL: Calibre web (LinuxServer.io)
    pt_BR: Calibre web (LinuxServer.io)
    ro_RO: Calibre web (LinuxServer.io)
    ru_RU: Calibre web (LinuxServer.io)
    sk_SK: Calibre web (LinuxServer.io)
    sv_SE: Calibre web (LinuxServer.io)
    tr_TR: Calibre web (LinuxServer.io)
    zh_CN: Calibre web（LinuxServer.io）
    zh_TW: Calibre web（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservercalibreweb
  port_map: '8083'
  version: 0.6.27
