name: linuxserver-habridge
services:
  app:
    image: linuxserver/habridge:5.4.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SEC_KEY: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 50000
        published: 50000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/habridge/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverhabridge/assets/icon.png
  title:
    en_US: Habridge (LinuxServer.io)
    ca_ES: Habridge (LinuxServer.io)
    cs_CZ: Habridge (LinuxServer.io)
    da_DK: Habridge (LinuxServer.io)
    de_DE: Habridge (LinuxServer.io)
    el_GR: Habridge (LinuxServer.io)
    en_GB: Habridge (LinuxServer.io)
    es_ES: Habridge (LinuxServer.io)
    fr_FR: Habridge (LinuxServer.io)
    ga_IE: Habridge (LinuxServer.io)
    hr_HR: Habridge (LinuxServer.io)
    hu_HU: Habridge (LinuxServer.io)
    it_IT: Habridge (LinuxServer.io)
    ja_JP: Habridge (LinuxServer.io)
    ko_KR: Habridge (LinuxServer.io)
    ml_IN: Habridge (LinuxServer.io)
    nb_NO: Habridge (LinuxServer.io)
    nl_NL: Habridge (LinuxServer.io)
    pl_PL: Habridge (LinuxServer.io)
    pt_BR: Habridge (LinuxServer.io)
    ro_RO: Habridge (LinuxServer.io)
    ru_RU: Habridge (LinuxServer.io)
    sk_SK: Habridge (LinuxServer.io)
    sv_SE: Habridge (LinuxServer.io)
    tr_TR: Habridge (LinuxServer.io)
    zh_CN: Habridge（LinuxServer.io）
    zh_TW: Habridge（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverhabridge
  port_map: '8080'
  version: 5.4.1
