name: linuxserver-thelounge
services:
  app:
    image: linuxserver/thelounge:4.5.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/thelounge/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Thelounge (a fork of shoutIRC) is a web IRC client that you host on your own server.
  tagline:
    en_US: (a fork of shoutIRC) is a web IRC client that you host on your own server.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@main/default-icon.svg
  thumbnail: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@main/default-icon.svg
  title:
    en_US: Thelounge (LinuxServer.io)
  category: Home
  id: wisdomsky.linuxserver.linuxserverthelounge
  version: "4.5.2"
  port_map: '9000'
