name: linuxserver-apprise-api
services:
  app:
    image: linuxserver/apprise-api:1.5.4@sha256:d639addc3ffb7d0020cd2aa992ac9d7042f263505fef0baa559d199cbb5526ff
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APPRISE_ATTACH_SIZE: ''
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/apprise-api/config
        target: /config
      - type: bind
        source: /DATA/AppData/apprise-api/attachments
        target: /attachments
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverappriseapi/assets/icon.png
  title:
    en_US: Apprise api (LinuxServer.io)
    ca_ES: Apprise api (LinuxServer.io)
    cs_CZ: Apprise api (LinuxServer.io)
    da_DK: Apprise api (LinuxServer.io)
    de_DE: Apprise api (LinuxServer.io)
    el_GR: Apprise api (LinuxServer.io)
    en_GB: Apprise api (LinuxServer.io)
    es_ES: Apprise api (LinuxServer.io)
    fr_FR: Apprise api (LinuxServer.io)
    ga_IE: Apprise api (LinuxServer.io)
    hr_HR: Apprise api (LinuxServer.io)
    hu_HU: Apprise api (LinuxServer.io)
    it_IT: Apprise api (LinuxServer.io)
    ja_JP: Apprise api (LinuxServer.io)
    ko_KR: Apprise api (LinuxServer.io)
    ml_IN: Apprise api (LinuxServer.io)
    nb_NO: Apprise api (LinuxServer.io)
    nl_NL: Apprise api (LinuxServer.io)
    pl_PL: Apprise api (LinuxServer.io)
    pt_BR: Apprise api (LinuxServer.io)
    ro_RO: Apprise api (LinuxServer.io)
    ru_RU: Apprise api (LinuxServer.io)
    sk_SK: Apprise api (LinuxServer.io)
    sv_SE: Apprise api (LinuxServer.io)
    tr_TR: Apprise api (LinuxServer.io)
    zh_CN: Apprise api（LinuxServer.io）
    zh_TW: Apprise api（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverappriseapi
  port_map: '8000'
  version: 1.5.4
