name: linuxserver-libreoffice
services:
  app:
    image: linuxserver/libreoffice:25.8.7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/libreoffice/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: LibreOffice is a free and powerful office suite, and a successor to OpenOffice.org (commonly known as OpenOffice). Its clean interface and feature-rich tools help you unleash your creativity and enhance your productivity.
    ca_ES: LibreOffice és un paquet ofimàtic gratuït i potent, i successor d'OpenOffice.org (conegut comunament com a OpenOffice). La seva interfície neta i les seves eines riques en funcions t'ajuden a donar curs a la teva creativitat i a millorar la teva productivitat.
    cs_CZ: LibreOffice je bezplatný a výkonný kancelářský balík, nástupce OpenOffice.org (běžně známého jako OpenOffice). Jeho přehledné rozhraní a nástroje bohaté na funkce vám pomohou uvolnit vaši kreativitu a zvýšit vaši produktivitu.
    da_DK: LibreOffice er en gratis og kraftfuld kontorpakke og en efterfølger til OpenOffice.org (almindeligvis kendt som OpenOffice). Dens rene brugerflade og funktionsrige værktøjer hjælper dig med at slippe din kreativitet løs og forbedre din produktivitet.
    de_DE: LibreOffice ist eine kostenlose und leistungsstarke Office-Suite und der Nachfolger von OpenOffice.org (allgemein bekannt als OpenOffice). Die übersichtliche Benutzeroberfläche und die vielfältigen Funktionen helfen Ihnen, Ihre Kreativität zu entfalten und Ihre Produktivität zu steigern.
    el_GR: Το LibreOffice είναι μια δωρεάν και ισχυρή σουίτα γραφείου και διάδοχος του OpenOffice.org (κοινώς γνωστό ως OpenOffice). Η καθαρή διεπαφή του και τα πλούσια σε λειτουργίες εργαλεία του σάς βοηθούν να απελευθερώσετε τη δημιουργικότητά σας και να βελτιώσετε την παραγωγικότητά σας.
    en_GB: Libreoffice is a free and powerful office suite, and a successor to Openoffice.org (commonly known as Openoffice). Its clean interface and feature-rich tools help you unleash your creativity and enhance your productivity.
    es_ES: LibreOffice es una potente suite ofimática gratuita, sucesora de OpenOffice.org (conocido comúnmente como OpenOffice). Su interfaz intuitiva y sus completas herramientas te ayudan a dar rienda suelta a tu creatividad y a aumentar tu productividad.
    fr_FR: LibreOffice est une suite bureautique gratuite et performante, successeur d'OpenOffice.org (communément appelé OpenOffice). Son interface épurée et ses nombreux outils vous aident à libérer votre créativité et à améliorer votre productivité.
    ga_IE: Is sraith oifige saor in aisce agus chumhachtach í LibreOffice, agus comharba ar OpenOffice.org (ar a dtugtar OpenOffice go coitianta). Cuidíonn a chomhéadan glan agus a uirlisí saibhre le do chruthaitheacht a scaoileadh saor agus do tháirgiúlacht a fheabhsú.
    hr_HR: LibreOffice je besplatan i moćan uredski paket i nasljednik OpenOffice.org-a (poznatijeg kao OpenOffice). Njegovo čisto sučelje i alati bogati značajkama pomažu vam osloboditi kreativnost i povećati produktivnost.
    hu_HU: A LibreOffice egy ingyenes és hatékony irodai programcsomag, az OpenOffice.org (közismert nevén OpenOffice) utódja. Letisztult felülete és funkciógazdag eszközei segítenek szabadjára engedni kreativitásodat és növelni a termelékenységedet.
    it_IT: LibreOffice è una suite per ufficio gratuita e potente, nonché successore di OpenOffice.org (comunemente noto come OpenOffice). La sua interfaccia intuitiva e i suoi strumenti ricchi di funzionalità ti aiutano a liberare la tua creatività e ad aumentare la tua produttività.
    ja_JP: LibreOfficeは、無料で強力なオフィススイートであり、OpenOffice.org（一般的にOpenOfficeとして知られています）の後継です。洗練されたインターフェースと豊富な機能を備えたツールは、あなたの創造性を解き放ち、生産性を向上させるのに役立ちます。
    ko_KR: LibreOffice는 무료이면서 강력한 오피스 제품군으로, OpenOffice.org(일반적으로 OpenOffice로 알려짐)의 후속 제품입니다. 깔끔한 인터페이스와 풍부한 기능을 갖춘 도구를 통해 창의력을 마음껏 발휘하고 생산성을 향상시킬 수 있습니다.
    ml_IN: ലിബ്രെ ഓഫീസ് ഒരു സൌജന്യവും ശക്തവുമായ ഓഫീസ് സ്യൂട്ടാണ്, കൂടാതെ OpenOffice.org ന്റെ (പൊതുവെ OpenOffice എന്നറിയപ്പെടുന്നു) പിൻഗാമിയുമാണ്. ഇതിന്റെ വൃത്തിയുള്ള ഇന്റർഫേസും സവിശേഷതകളാൽ സമ്പന്നമായ ഉപകരണങ്ങളും നിങ്ങളുടെ സർഗ്ഗാത്മകതയെ പുറത്തുവിടാനും ഉൽപ്പാദനക്ഷമത വർദ്ധിപ്പിക്കാനും സഹായിക്കുന്നു.
    nb_NO: LibreOffice er en gratis og kraftig kontorpakke, og en etterfølger til OpenOffice.org (vanligvis kjent som OpenOffice). Det rene grensesnittet og de funksjonsrike verktøyene hjelper deg med å slippe løs kreativiteten din og forbedre produktiviteten din.
    nl_NL: LibreOffice is een gratis en krachtig kantoorpakket en de opvolger van OpenOffice.org (ook wel bekend als OpenOffice). De overzichtelijke interface en de vele functies helpen je je creativiteit de vrije loop te laten en je productiviteit te verhogen.
    pl_PL: LibreOffice to darmowy i wydajny pakiet biurowy, następca OpenOffice.org (powszechnie znanego jako OpenOffice). Jego przejrzysty interfejs i bogate w funkcje narzędzia pomogą Ci uwolnić kreatywność i zwiększyć produktywność.
    pt_BR: O LibreOffice é um pacote de escritório gratuito e poderoso, sucessor do OpenOffice.org (comumente conhecido como OpenOffice). Sua interface intuitiva e ferramentas repletas de recursos ajudam você a liberar sua criatividade e aumentar sua produtividade.
    ro_RO: LibreOffice este o suită de birou gratuită și puternică, succesorul OpenOffice.org (cunoscut în mod obișnuit ca OpenOffice). Interfața sa curată și instrumentele bogate în funcții te ajută să-ți dezlănțui creativitatea și să-ți îmbunătățești productivitatea.
    ru_RU: LibreOffice — это бесплатный и мощный офисный пакет, являющийся преемником OpenOffice.org (широко известного как OpenOffice). Его понятный интерфейс и многофункциональные инструменты помогут вам раскрыть свой творческий потенциал и повысить производительность.
    sk_SK: LibreOffice je bezplatný a výkonný kancelársky balík a nástupca OpenOffice.org (bežne známeho ako OpenOffice). Jeho prehľadné rozhranie a nástroje bohaté na funkcie vám pomôžu uvoľniť vašu kreativitu a zvýšiť vašu produktivitu.
    sv_SE: LibreOffice är ett gratis och kraftfullt kontorspaket och en efterföljare till OpenOffice.org (allmänt känt som OpenOffice). Dess rena gränssnitt och funktionsrika verktyg hjälper dig att släppa lös din kreativitet och öka din produktivitet.
    tr_TR: LibreOffice, ücretsiz ve güçlü bir ofis yazılım paketidir ve OpenOffice.org'un (genellikle OpenOffice olarak bilinir) halefidir. Sade arayüzü ve zengin özellikli araçları, yaratıcılığınızı ortaya çıkarmanıza ve verimliliğinizi artırmanıza yardımcı olur.
    zh_CN: LibreOffice 是免费、功能强大的办公套件，也是 OpenOffice.org（通常称为 OpenOffice）的继承者。简洁的界面和丰富的工具有助于发挥创造力并提高工作效率。
    zh_TW: LibreOffice 是免費、功能強大的辦公套件，也是 OpenOffice.org（通常稱為 OpenOffice）的繼承者。簡潔的介面和豐富的工具有助於發揮創造力並提高工作效率。
  tagline:
    en_US: A free and powerful office suite, and a successor to OpenOffice. Org (commonly known as OpenOffice). Its clean interface and feature-rich tools help you unleash your creativity and enhance your productivity.
    ca_ES: Un paquet ofimàtic gratuït i potent, i successor d'OpenOffice.org (conegut comunament com a OpenOffice). La seva interfície neta i les seves eines riques en funcions t'ajuden a donar curs a la teva creativitat i a millorar la teva productivitat.
    cs_CZ: Bezplatný a výkonný kancelářský balík, nástupce OpenOffice.org (běžně známého jako OpenOffice). Jeho čisté rozhraní a nástroje bohaté na funkce vám pomohou uvolnit vaši kreativitu a zvýšit vaši produktivitu.
    da_DK: En gratis og kraftfuld kontorpakke og en efterfølger til OpenOffice.org (almindeligvis kendt som OpenOffice). Dens rene brugerflade og funktionsrige værktøjer hjælper dig med at slippe din kreativitet løs og forbedre din produktivitet.
    de_DE: Eine kostenlose und leistungsstarke Office-Suite und Nachfolger von OpenOffice.org (allgemein bekannt als OpenOffice). Die übersichtliche Benutzeroberfläche und die vielfältigen Funktionen helfen Ihnen, Ihre Kreativität zu entfalten und Ihre Produktivität zu steigern.
    el_GR: Μια δωρεάν και ισχυρή σουίτα γραφείου, διάδοχος του OpenOffice.Org (κοινώς γνωστό ως OpenOffice). Η καθαρή διεπαφή και τα πλούσια σε λειτουργίες εργαλεία του σάς βοηθούν να απελευθερώσετε τη δημιουργικότητά σας και να βελτιώσετε την παραγωγικότητά σας.
    en_GB: A free and powerful office suite, and a successor to Openoffice. Org (commonly known as Openoffice). Its clean interface and feature-rich tools help you unleash your creativity and enhance your productivity.
    es_ES: Una suite ofimática gratuita y potente, sucesora de OpenOffice.org (conocido comúnmente como OpenOffice). Su interfaz intuitiva y sus completas herramientas te ayudan a dar rienda suelta a tu creatividad y aumentar tu productividad.
    fr_FR: Suite bureautique gratuite et performante, successeur d'OpenOffice.org (communément appelé OpenOffice). Son interface épurée et ses outils riches en fonctionnalités vous aident à libérer votre créativité et à améliorer votre productivité.
    ga_IE: Sraith oifige saor in aisce agus chumhachtach, agus comharba ar OpenOffice.org (ar a dtugtar OpenOffice go coitianta). Cuidíonn a chomhéadan glan agus a uirlisí saibhre le do chruthaitheacht a scaoileadh saor agus do tháirgiúlacht a fheabhsú.
    hr_HR: Besplatan i moćan uredski paket, nasljednik OpenOffice.org (poznatijeg kao OpenOffice). Njegovo čisto sučelje i alati bogati značajkama pomažu vam osloboditi kreativnost i povećati produktivnost.
    hu_HU: Egy ingyenes és hatékony irodai csomag, az OpenOffice.org (közismert nevén OpenOffice) utódja. Letisztult felülete és funkciógazdag eszközei segítenek szabadjára engedni kreativitásodat és fokozni a termelékenységedet.
    it_IT: Una suite per ufficio gratuita e potente, successore di OpenOffice.org (comunemente noto come OpenOffice). La sua interfaccia intuitiva e i suoi strumenti ricchi di funzionalità ti aiutano a liberare la tua creatività e ad aumentare la tua produttività.
    ja_JP: 無料で強力なオフィススイートであり、OpenOffice.org（一般的にOpenOfficeとして知られています）の後継製品です。洗練されたインターフェースと豊富な機能を備えたツールで、創造性を解き放ち、生産性を向上させます。
    ko_KR: 무료이면서 강력한 오피스 제품군으로, OpenOffice.org(일반적으로 OpenOffice로 알려짐)의 후속 제품입니다. 깔끔한 인터페이스와 풍부한 기능을 갖춘 도구를 통해 창의력을 마음껏 발휘하고 생산성을 향상시킬 수 있습니다.
    ml_IN: സൌജന്യവും ശക്തവുമായ ഒരു ഓഫീസ് സ്യൂട്ട്, കൂടാതെ OpenOffice ന്റെ പിൻഗാമിയും. Org (സാധാരണയായി OpenOffice എന്നറിയപ്പെടുന്നു). ഇതിന്റെ വൃത്തിയുള്ള ഇന്റർഫേസും സവിശേഷതകളാൽ സമ്പന്നമായ ഉപകരണങ്ങളും നിങ്ങളുടെ സർഗ്ഗാത്മകതയെ പുറത്തുവിടാനും ഉൽപ്പാദനക്ഷമത വർദ്ധിപ്പിക്കാനും സഹായിക്കുന്നു.
    nb_NO: En gratis og kraftig kontorpakke, og en etterfølger til OpenOffice.org (vanligvis kjent som OpenOffice). Det rene grensesnittet og de funksjonsrike verktøyene hjelper deg med å slippe løs kreativiteten din og forbedre produktiviteten din.
    nl_NL: Een gratis en krachtig kantoorpakket, en de opvolger van OpenOffice.org (ook wel bekend als OpenOffice). De overzichtelijke interface en de vele functies helpen je je creativiteit de vrije loop te laten en je productiviteit te verhogen.
    pl_PL: Darmowy i wydajny pakiet biurowy, następca OpenOffice.Org (powszechnie znanego jako OpenOffice). Jego przejrzysty interfejs i bogate w funkcje narzędzia pomogą Ci uwolnić kreatywność i zwiększyć produktywność.
    pt_BR: Um pacote de escritório gratuito e poderoso, sucessor do OpenOffice.org (comumente conhecido como OpenOffice). Sua interface intuitiva e ferramentas repletas de recursos ajudam você a liberar sua criatividade e aumentar sua produtividade.
    ro_RO: O suită de birou gratuită și puternică, succesorul OpenOffice.org (cunoscut în mod obișnuit ca OpenOffice). Interfața sa curată și instrumentele bogate în funcții te ajută să-ți dezlănțui creativitatea și să-ți îmbunătățești productivitatea.
    ru_RU: Бесплатный и мощный офисный пакет, преемник OpenOffice.Org (широко известного как OpenOffice). Его понятный интерфейс и многофункциональные инструменты помогут вам раскрыть свой творческий потенциал и повысить производительность.
    sk_SK: Bezplatný a výkonný kancelársky balík, nástupca OpenOffice.org (bežne známeho ako OpenOffice). Jeho prehľadné rozhranie a nástroje bohaté na funkcie vám pomôžu uvoľniť vašu kreativitu a zvýšiť vašu produktivitu.
    sv_SE: En gratis och kraftfull kontorssvit, och en efterföljare till OpenOffice.org (allmänt känt som OpenOffice). Dess rena gränssnitt och funktionsrika verktyg hjälper dig att släppa lös din kreativitet och öka din produktivitet.
    tr_TR: Ücretsiz ve güçlü bir ofis yazılım paketi olup, OpenOffice.org'un (genellikle OpenOffice olarak bilinir) halefidir. Sade arayüzü ve zengin özellikli araçları, yaratıcılığınızı ortaya çıkarmanıza ve verimliliğinizi artırmanıza yardımcı olur.
    zh_CN: 免费且功能强大的开源办公套件。
    zh_TW: 免費且功能強大的開源辦公套件。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/libreoffice-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/libreoffice-logo.png
  title:
    en_US: Libreoffice (LinuxServer.io)
    ca_ES: Libreoffice (LinuxServer.io)
    cs_CZ: Libreoffice (LinuxServer.io)
    da_DK: Libreoffice (LinuxServer.io)
    de_DE: Libreoffice (LinuxServer.io)
    el_GR: Libreoffice (LinuxServer.io)
    en_GB: Libreoffice (LinuxServer.io)
    es_ES: Libreoffice (LinuxServer.io)
    fr_FR: Libreoffice (LinuxServer.io)
    ga_IE: Libreoffice (LinuxServer.io)
    hr_HR: Libreoffice (LinuxServer.io)
    hu_HU: Libreoffice (LinuxServer.io)
    it_IT: Libreoffice (LinuxServer.io)
    ja_JP: Libreoffice (LinuxServer.io)
    ko_KR: Libreoffice (LinuxServer.io)
    ml_IN: Libreoffice (LinuxServer.io)
    nb_NO: Libreoffice (LinuxServer.io)
    nl_NL: Libreoffice (LinuxServer.io)
    pl_PL: Libreoffice (LinuxServer.io)
    pt_BR: Libreoffice (LinuxServer.io)
    ro_RO: Libreoffice (LinuxServer.io)
    ru_RU: Libreoffice (LinuxServer.io)
    sk_SK: Libreoffice (LinuxServer.io)
    sv_SE: Libreoffice (LinuxServer.io)
    tr_TR: Libreoffice (LinuxServer.io)
    zh_CN: Libreoffice（LinuxServer.io）
    zh_TW: Libreoffice（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverlibreoffice
  port_map: '3000'
  version: 25.8.7
