name: linuxserver-mysql-workbench
services:
  app:
    image: linuxserver/mysql-workbench:8.0.47@sha256:1407c97177f347163e91909bfc4121301508800ba90225e390181140cef2ada0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mysql-workbench/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermysqlworkbench/assets/icon.png
  title:
    en_US: Mysql workbench (LinuxServer.io)
    ca_ES: Mysql workbench (LinuxServer.io)
    cs_CZ: Mysql workbench (LinuxServer.io)
    da_DK: Mysql workbench (LinuxServer.io)
    de_DE: Mysql workbench (LinuxServer.io)
    el_GR: Mysql workbench (LinuxServer.io)
    en_GB: Mysql workbench (LinuxServer.io)
    es_ES: Mysql workbench (LinuxServer.io)
    fr_FR: Mysql workbench (LinuxServer.io)
    ga_IE: Mysql workbench (LinuxServer.io)
    hr_HR: Mysql workbench (LinuxServer.io)
    hu_HU: Mysql workbench (LinuxServer.io)
    it_IT: Mysql workbench (LinuxServer.io)
    ja_JP: Mysql workbench (LinuxServer.io)
    ko_KR: Mysql workbench (LinuxServer.io)
    ml_IN: Mysql workbench (LinuxServer.io)
    nb_NO: Mysql workbench (LinuxServer.io)
    nl_NL: Mysql workbench (LinuxServer.io)
    pl_PL: Mysql workbench (LinuxServer.io)
    pt_BR: Mysql workbench (LinuxServer.io)
    ro_RO: Mysql workbench (LinuxServer.io)
    ru_RU: Mysql workbench (LinuxServer.io)
    sk_SK: Mysql workbench (LinuxServer.io)
    sv_SE: Mysql workbench (LinuxServer.io)
    tr_TR: Mysql workbench (LinuxServer.io)
    zh_CN: Mysql workbench（LinuxServer.io）
    zh_TW: Mysql workbench（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservermysqlworkbench
  port_map: '3000'
  version: 8.0.47
