name: linuxserver-bitcoin-knots
services:
  app:
    image: linuxserver/bitcoin-knots:version-29.4.knots20260508.1-noble1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
      - target: 8333
        published: 8333
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bitcoin-knots/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverbitcoinknots/assets/icon.png
  title:
    en_US: Bitcoin knots (LinuxServer.io)
    ca_ES: Bitcoin knots (LinuxServer.io)
    cs_CZ: Bitcoin knots (LinuxServer.io)
    da_DK: Bitcoin knots (LinuxServer.io)
    de_DE: Bitcoin knots (LinuxServer.io)
    el_GR: Bitcoin knots (LinuxServer.io)
    en_GB: Bitcoin knots (LinuxServer.io)
    es_ES: Bitcoin knots (LinuxServer.io)
    fr_FR: Bitcoin knots (LinuxServer.io)
    ga_IE: Bitcoin knots (LinuxServer.io)
    hr_HR: Bitcoin knots (LinuxServer.io)
    hu_HU: Bitcoin knots (LinuxServer.io)
    it_IT: Bitcoin knots (LinuxServer.io)
    ja_JP: Bitcoin knots (LinuxServer.io)
    ko_KR: Bitcoin knots (LinuxServer.io)
    ml_IN: Bitcoin knots (LinuxServer.io)
    nb_NO: Bitcoin knots (LinuxServer.io)
    nl_NL: Bitcoin knots (LinuxServer.io)
    pl_PL: Bitcoin knots (LinuxServer.io)
    pt_BR: Bitcoin knots (LinuxServer.io)
    ro_RO: Bitcoin knots (LinuxServer.io)
    ru_RU: Bitcoin knots (LinuxServer.io)
    sk_SK: Bitcoin knots (LinuxServer.io)
    sv_SE: Bitcoin knots (LinuxServer.io)
    tr_TR: Bitcoin knots (LinuxServer.io)
    zh_CN: Bitcoin knots（LinuxServer.io）
    zh_TW: Bitcoin knots（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverbitcoinknots
  port_map: '3000'
  version: version-29.4.knots20260508.1-noble1
