name: linuxserver-thelounge
services:
  app:
    image: linuxserver/thelounge:4.5.2@sha256:a386833205f189131abd423e26da1c5fc30c278a63f2cef25e828f93fbd2f72d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/thelounge/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverthelounge/assets/icon.svg
  title:
    en_US: Thelounge (LinuxServer.io)
    zh_CN: Thelounge（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverthelounge
  port_map: '9000'
  version: 4.5.2
