name: linuxserver-librewolf
services:
  app:
    image: linuxserver/librewolf:155.0.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      LIBREWOLF_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/librewolf/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverlibrewolf/assets/icon.png
  title:
    en_US: Librewolf (LinuxServer.io)
    ca_ES: Librewolf (LinuxServer.io)
    cs_CZ: Librewolf (LinuxServer.io)
    da_DK: Librewolf (LinuxServer.io)
    de_DE: Librewolf (LinuxServer.io)
    el_GR: Librewolf (LinuxServer.io)
    en_GB: Librewolf (LinuxServer.io)
    es_ES: Librewolf (LinuxServer.io)
    fr_FR: Librewolf (LinuxServer.io)
    ga_IE: Librewolf (LinuxServer.io)
    hr_HR: Librewolf (LinuxServer.io)
    hu_HU: Librewolf (LinuxServer.io)
    it_IT: Librewolf (LinuxServer.io)
    ja_JP: Librewolf (LinuxServer.io)
    ko_KR: Librewolf (LinuxServer.io)
    ml_IN: Librewolf (LinuxServer.io)
    nb_NO: Librewolf (LinuxServer.io)
    nl_NL: Librewolf (LinuxServer.io)
    pl_PL: Librewolf (LinuxServer.io)
    pt_BR: Librewolf (LinuxServer.io)
    ro_RO: Librewolf (LinuxServer.io)
    ru_RU: Librewolf (LinuxServer.io)
    sk_SK: Librewolf (LinuxServer.io)
    sv_SE: Librewolf (LinuxServer.io)
    tr_TR: Librewolf (LinuxServer.io)
    zh_CN: Librewolf（LinuxServer.io）
    zh_TW: Librewolf（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverlibrewolf
  port_map: '3000'
  version: 155.0.1
