name: linuxserver-dokuwiki
services:
  app:
    image: linuxserver/dokuwiki:version-2026-07-14c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dokuwiki/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Dokuwiki is a simple to use and highly versatile Open Source wiki software that doesn't require a database. It is loved by users for its clean and readable syntax. The ease of maintenance, backup and integration makes it an administrator's favorite. Built in access controls and authentication connectors make DokuWiki especially useful in the enterprise context and the large number of plugins contributed by its vibrant community allow for a broad range of use cases beyond a traditional wiki.
    ca_ES: Dokuwiki és un programari wiki de codi obert fàcil d'utilitzar i molt versàtil que no requereix una base de dades. És estimat pels usuaris per la seva sintaxi neta i llegible. La facilitat de manteniment, còpia de seguretat i integració el converteixen en el preferit dels administradors. Els controls d'accés i els connectors d'autenticació integrats fan que DokuWiki sigui especialment útil en el context empresarial i el gran nombre de complements aportats per la seva vibrant comunitat permeten una àmplia gamma de casos d'ús més enllà d'un wiki tradicional.
    cs_CZ: Dokuwiki je snadno použitelný a vysoce všestranný open source wiki software, který nevyžaduje databázi. Uživatelé ho milují pro jeho čistou a čitelnou syntaxi. Snadná údržba, zálohování a integrace z něj činí oblíbenou volbu administrátorů. Vestavěné kontroly přístupu a ověřovací konektory činí DokuWiki obzvláště užitečnou v podnikovém kontextu a velké množství pluginů, které poskytuje jeho dynamická komunita, umožňuje širokou škálu použití nad rámec tradiční wiki.
    da_DK: Dokuwiki er en brugervenlig og meget alsidig open source wiki-software, der ikke kræver en database. Den er elsket af brugerne for sin rene og læsbare syntaks. Den nemme vedligeholdelse, backup og integration gør den til en administrators favorit. Indbyggede adgangskontroller og godkendelsesforbindelser gør DokuWiki særligt nyttig i virksomhedssammenhæng, og det store antal plugins, der bidrager med dets dynamiske fællesskab, giver mulighed for en bred vifte af anvendelsesscenarier ud over en traditionel wiki.
    de_DE: DokuWiki ist eine benutzerfreundliche und äußerst vielseitige Open-Source-Wiki-Software, die keine Datenbank benötigt. Sie wird von Nutzern aufgrund ihrer klaren und lesbaren Syntax geschätzt. Die einfache Wartung, Datensicherung und Integration machen sie zur bevorzugten Lösung von Administratoren. Integrierte Zugriffskontrollen und Authentifizierungsschnittstellen machen DokuWiki besonders nützlich im Unternehmensumfeld, und die zahlreichen Plugins der aktiven Community ermöglichen vielfältige Anwendungsfälle, die weit über ein traditionelles Wiki hinausgehen.
    el_GR: Το Dokuwiki είναι ένα εύχρηστο και εξαιρετικά ευέλικτο λογισμικό wiki ανοιχτού κώδικα που δεν απαιτεί βάση δεδομένων. Είναι αγαπημένο στους χρήστες για την καθαρή και ευανάγνωστη σύνταξή του. Η ευκολία συντήρησης, δημιουργίας αντιγράφων ασφαλείας και ενσωμάτωσης το καθιστά αγαπημένο των διαχειριστών. Τα ενσωματωμένα στοιχεία ελέγχου πρόσβασης και οι σύνδεσμοι ελέγχου ταυτότητας καθιστούν το DokuWiki ιδιαίτερα χρήσιμο σε εταιρικό περιβάλλον και ο μεγάλος αριθμός πρόσθετων που συνεισφέρει η ζωντανή κοινότητά του επιτρέπει ένα ευρύ φάσμα περιπτώσεων χρήσης πέρα από ένα παραδοσιακό wiki.
    en_GB: Dokuwiki is a simple to use and highly versatile Open Source wiki software that doesn't require a database. It is loved by users for its clean and readable syntax. The ease of maintenance, backup and integration makes it an administrator's favourite. Built in access controls and authentication connectors make Dokuwiki especially useful in the enterprise context and the large number of plugins contributed by its vibrant community allow for a broad range of use cases beyond a traditional wiki.
    es_ES: Dokuwiki es un software wiki de código abierto, sencillo de usar y muy versátil, que no requiere base de datos. Es muy apreciado por los usuarios por su sintaxis clara y legible. Su facilidad de mantenimiento, copias de seguridad e integración lo convierten en el favorito de los administradores. Los controles de acceso y los conectores de autenticación integrados hacen que DokuWiki sea especialmente útil en el ámbito empresarial, y la gran cantidad de complementos aportados por su dinámica comunidad permite una amplia gama de casos de uso que van más allá de un wiki tradicional.
    fr_FR: DokuWiki est un logiciel wiki open source simple d'utilisation et très polyvalent, ne nécessitant aucune base de données. Apprécié pour sa syntaxe claire et lisible, il est plébiscité par les utilisateurs. Sa facilité de maintenance, de sauvegarde et d'intégration en fait un outil de prédilection pour les administrateurs. Grâce à ses contrôles d'accès intégrés et ses connecteurs d'authentification, DokuWiki est particulièrement utile en entreprise. De plus, le grand nombre d'extensions proposées par sa communauté dynamique permet une large gamme d'utilisations, bien au-delà d'un wiki traditionnel.
    ga_IE: Is bogearraí vicí foinse oscailte atá éasca le húsáid agus thar a bheith ilúsáideach é Dokuwiki nach dteastaíonn bunachar sonraí uaidh. Is breá le húsáideoirí é mar gheall ar a chomhréir ghlan agus inléite. Mar gheall ar an éascaíocht cothabhála, cúltaca agus comhtháthaithe, is fearr le riarthóirí é. Déanann rialuithe rochtana ionsuite agus nascóirí fíordheimhnithe DokuWiki thar a bheith úsáideach i gcomhthéacs fiontraíochta agus cuireann an líon mór breiseán a chuireann a phobal bríomhar ar fáil raon leathan cásanna úsáide ar fáil thar vicí traidisiúnta.
    hr_HR: Dokuwiki je jednostavan za korištenje i vrlo svestran wiki softver otvorenog koda koji ne zahtijeva bazu podataka. Korisnici ga vole zbog njegove čiste i čitljive sintakse. Jednostavnost održavanja, izrade sigurnosnih kopija i integracije čini ga omiljenim među administratorima. Ugrađene kontrole pristupa i konektori za autentifikaciju čine DokuWiki posebno korisnim u poslovnom kontekstu, a veliki broj dodataka koje doprinosi njegova živahna zajednica omogućuje širok raspon slučajeva upotrebe izvan tradicionalnog wikija.
    hu_HU: A Dokuwiki egy egyszerűen használható és rendkívül sokoldalú, nyílt forráskódú wiki szoftver, amely nem igényel adatbázist. A felhasználók letisztult és olvasható szintaxisa miatt szeretik. A könnyű karbantartás, biztonsági mentés és integráció a rendszergazdák kedvencévé teszi. A beépített hozzáférés-vezérlés és hitelesítési csatlakozók különösen hasznossá teszik a DokuWikit vállalati környezetben, és az élénk közösség által biztosított nagyszámú bővítmény széles körű felhasználási lehetőségeket tesz lehetővé a hagyományos wikin túl.
    it_IT: DokuWiki è un software wiki open source semplice da usare e altamente versatile, che non richiede un database. È apprezzato dagli utenti per la sua sintassi pulita e leggibile. La facilità di manutenzione, backup e integrazione lo rende uno dei preferiti dagli amministratori. I controlli di accesso integrati e i connettori di autenticazione rendono DokuWiki particolarmente utile in ambito aziendale, e l'ampio numero di plugin sviluppati dalla sua vivace community consente una vasta gamma di casi d'uso che vanno ben oltre un wiki tradizionale.
    ja_JP: Dokuwikiは、データベースを必要としない、使いやすく汎用性の高いオープンソースのWikiソフトウェアです。簡潔で読みやすい構文がユーザーに高く評価されています。メンテナンス、バックアップ、統合が容易なため、管理者にも人気があります。組み込みのアクセス制御機能と認証コネクタにより、Dokuwikiは特に企業環境で役立ちます。また、活発なコミュニティによって提供される多数のプラグインにより、従来のWikiの枠を超えた幅広い用途に対応できます。
    ko_KR: DokuWiki는 데이터베이스가 필요 없는 사용하기 쉽고 활용도가 매우 높은 오픈 소스 위키 소프트웨어입니다. 깔끔하고 가독성 좋은 구문 덕분에 사용자들에게 사랑받고 있습니다. 손쉬운 유지 관리, 백업 및 통합 기능으로 관리자들에게도 인기가 높습니다. 내장된 접근 제어 및 인증 커넥터는 기업 환경에서 특히 유용하며, 활발한 커뮤니티에서 제공하는 수많은 플러그인을 통해 기존 위키의 범위를 넘어 다양한 활용 사례를 구현할 수 있습니다.
    ml_IN: ഉപയോഗിക്കാൻ എളുപ്പവും വൈവിധ്യപൂർണ്ണവുമായ ഒരു ഓപ്പൺ സോഴ്‌സ് വിക്കി സോഫ്റ്റ്‌വെയറാണ് ഡോകുവിക്കി, ഇതിന് ഒരു ഡാറ്റാബേസ് ആവശ്യമില്ല. വൃത്തിയുള്ളതും വായിക്കാൻ കഴിയുന്നതുമായ വാക്യഘടന കാരണം ഉപയോക്താക്കൾ ഇത് ഇഷ്ടപ്പെടുന്നു. അറ്റകുറ്റപ്പണികളുടെ എളുപ്പവും ബാക്കപ്പും സംയോജനവും ഇതിനെ അഡ്മിനിസ്ട്രേറ്റർമാരുടെ പ്രിയങ്കരമാക്കുന്നു. അന്തർനിർമ്മിതമായ ആക്‌സസ് നിയന്ത്രണങ്ങളും പ്രാമാണീകരണ കണക്ടറുകളും ഡോകുവിക്കിയെ എന്റർപ്രൈസ് സന്ദർഭത്തിൽ പ്രത്യേകിച്ചും ഉപയോഗപ്രദമാക്കുന്നു, കൂടാതെ അതിന്റെ ഊർജ്ജസ്വലമായ കമ്മ്യൂണിറ്റി സംഭാവന ചെയ്യുന്ന ധാരാളം പ്ലഗിനുകൾ പരമ്പരാഗത വിക്കിയപ്പുറം വിശാലമായ ഉപയോഗ കേസുകൾ അനുവദിക്കുന്നു.
    nb_NO: Dokuwiki er en brukervennlig og svært allsidig wiki-programvare med åpen kildekode som ikke krever en database. Den er elsket av brukere for sin rene og lesbare syntaks. Enkel vedlikehold, sikkerhetskopiering og integrering gjør den til en administratorfavoritt. Innebygde tilgangskontroller og autentiseringskoblinger gjør DokuWiki spesielt nyttig i bedriftssammenheng, og det store antallet plugins som bidras av det pulserende fellesskapet, gir mulighet for et bredt spekter av bruksområder utover en tradisjonell wiki.
    nl_NL: Dokuwiki is gebruiksvriendelijke en zeer veelzijdige open-source wiki-software die geen database vereist. Gebruikers waarderen het vanwege de overzichtelijke en leesbare syntaxis. Het gemakkelijke onderhoud, de back-upmogelijkheden en de integratie maken het een favoriet bij beheerders. Ingebouwde toegangscontrole en authenticatieconnectoren maken DokuWiki bijzonder nuttig in een bedrijfsomgeving, en het grote aantal plugins dat door de actieve community wordt bijgedragen, maakt een breed scala aan toepassingen mogelijk die verder gaan dan een traditionele wiki.
    pl_PL: DokuWiki to proste w obsłudze i niezwykle wszechstronne oprogramowanie wiki typu open source, które nie wymaga bazy danych. Użytkownicy cenią je za przejrzystą i czytelną składnię. Łatwość konserwacji, tworzenia kopii zapasowych i integracji sprawia, że jest ono ulubionym narzędziem administratorów. Wbudowane mechanizmy kontroli dostępu i łączniki uwierzytelniania sprawiają, że DokuWiki jest szczególnie przydatne w przedsiębiorstwach, a duża liczba wtyczek udostępnianych przez aktywną społeczność pozwala na szeroki zakres zastosowań wykraczających poza tradycyjne wiki.
    pt_BR: DokuWiki é um software wiki de código aberto, simples de usar e altamente versátil, que não requer um banco de dados. É apreciado pelos usuários por sua sintaxe limpa e legível. A facilidade de manutenção, backup e integração o torna o favorito dos administradores. Os controles de acesso e conectores de autenticação integrados tornam o DokuWiki especialmente útil no contexto corporativo, e o grande número de plugins contribuídos por sua ativa comunidade permite uma ampla gama de casos de uso além de um wiki tradicional.
    ro_RO: Dokuwiki este un software wiki open source simplu de utilizat și extrem de versatil, care nu necesită o bază de date. Este îndrăgit de utilizatori pentru sintaxa sa curată și ușor de citit. Ușurința cu care se pot întreține, se pot face backup-uri și se pot integra îl face preferatul administratorilor. Controalele de acces și conectorii de autentificare încorporați fac DokuWiki deosebit de util în contextul întreprinderilor, iar numărul mare de plugin-uri oferite de comunitatea sa vibrantă permite o gamă largă de cazuri de utilizare dincolo de un wiki tradițional.
    ru_RU: DokuWiki — это простое в использовании и очень универсальное программное обеспечение для вики-систем с открытым исходным кодом, не требующее базы данных. Пользователи любят его за чистый и читаемый синтаксис. Простота обслуживания, резервного копирования и интеграции делает его фаворитом среди администраторов. Встроенные средства контроля доступа и коннекторы аутентификации делают DokuWiki особенно полезным в корпоративной среде, а большое количество плагинов, разработанных активным сообществом, позволяет использовать его в самых разных сценариях, выходящих за рамки традиционной вики.
    sk_SK: Dokuwiki je jednoducho použiteľný a vysoko všestranný open source wiki softvér, ktorý nevyžaduje databázu. Používatelia ho milujú pre jeho čistú a čitateľnú syntax. Jednoduchá údržba, zálohovanie a integrácia z neho robia obľúbenca administrátorov. Vstavané kontroly prístupu a autentifikačné konektory robia DokuWiki obzvlášť užitočným v podnikovom kontexte a veľké množstvo pluginov, ktoré prináša jeho dynamická komunita, umožňuje širokú škálu prípadov použitia nad rámec tradičnej wiki.
    sv_SE: Dokuwiki är en lättanvänd och mycket mångsidig wiki-programvara med öppen källkod som inte kräver någon databas. Den är älskad av användarna för sin rena och läsbara syntax. Det enkla underhållet, säkerhetskopieringen och integrationen gör den till en favorit bland administratörer. Inbyggda åtkomstkontroller och autentiseringskopplingar gör DokuWiki särskilt användbar i företagssammanhang och det stora antalet plugins som bidrar med från dess livliga community möjliggör ett brett spektrum av användningsområden utöver en traditionell wiki.
    tr_TR: Dokuwiki, veritabanı gerektirmeyen, kullanımı kolay ve son derece çok yönlü bir Açık Kaynak wiki yazılımıdır. Temiz ve okunabilir sözdizimi nedeniyle kullanıcılar tarafından sevilmektedir. Bakım, yedekleme ve entegrasyon kolaylığı, onu yöneticilerin favorisi yapmaktadır. Dahili erişim kontrolleri ve kimlik doğrulama bağlantıları, DokuWiki'yi özellikle kurumsal ortamda kullanışlı hale getirirken, canlı topluluğu tarafından katkıda bulunulan çok sayıda eklenti, geleneksel bir wiki'nin ötesinde geniş bir kullanım alanı yelpazesine olanak tanır.
    zh_CN: DokuWiki 是一款简单易用、用途广泛且无需数据库的开源 Wiki 软件。它以清晰易读的语法受到用户喜爱，维护、备份和集成都很方便。内置的访问控制和身份验证连接器使其尤其适合企业使用，而活跃社区提供的大量插件让它能够胜任传统 Wiki 之外的多种用途。
    zh_TW: DokuWiki 是一款簡單易用、用途廣泛且無需資料庫的開源 Wiki 軟體。它以清晰易讀的語法受到使用者喜愛，維護、備份和整合都很方便。內建的訪問控制和身份驗證聯結器使其尤其適合企業使用，而活躍社群提供的大量外掛讓它能夠勝任傳統 Wiki 之外的多種用途。
  tagline:
    en_US: A simple to use and highly versatile Open Source wiki software that doesn't require a database. It is loved by users for its clean and readable syntax. The ease of maintenance, backup and integration makes it an administrator's favorite. Built in access controls and authentication connectors make DokuWiki especially useful in the enterprise context and the large number of plugins contributed by its vibrant community allow for a broad range of use cases beyond a traditional wiki.
    ca_ES: Un programari wiki de codi obert fàcil d'utilitzar i molt versàtil que no requereix una base de dades. És estimat pels usuaris per la seva sintaxi neta i llegible. La facilitat de manteniment, còpia de seguretat i integració el converteix en el preferit dels administradors. Els controls d'accés i els connectors d'autenticació integrats fan que DokuWiki sigui especialment útil en el context empresarial i el gran nombre de complements aportats per la seva vibrant comunitat permeten una àmplia gamma de casos d'ús més enllà d'un wiki tradicional.
    cs_CZ: Jednoduchý a vysoce všestranný open source wiki software, který nevyžaduje databázi. Uživatelé ho milují pro jeho čistou a čitelnou syntaxi. Snadná údržba, zálohování a integrace z něj činí oblíbenou volbu administrátorů. Vestavěné kontroly přístupu a ověřovací konektory činí DokuWiki obzvláště užitečnou v podnikovém kontextu a velké množství pluginů, které poskytuje jeho dynamická komunita, umožňuje širokou škálu použití nad rámec tradiční wiki.
    da_DK: En brugervenlig og meget alsidig open source wiki-software, der ikke kræver en database. Den er elsket af brugerne for sin rene og læsbare syntaks. Den nemme vedligeholdelse, backup og integration gør den til en administrators favorit. Indbyggede adgangskontroller og godkendelsesforbindelser gør DokuWiki særligt nyttig i virksomhedssammenhæng, og det store antal plugins, der bidrager med dets dynamiske fællesskab, giver mulighed for en bred vifte af anvendelsesscenarier ud over en traditionel wiki.
    de_DE: DokuWiki ist eine benutzerfreundliche und äußerst vielseitige Open-Source-Wiki-Software, die keine Datenbank benötigt. Sie wird von Nutzern aufgrund ihrer klaren und lesbaren Syntax geschätzt. Die einfache Wartung, Datensicherung und Integration machen sie zur bevorzugten Lösung von Administratoren. Integrierte Zugriffskontrollen und Authentifizierungsschnittstellen machen DokuWiki besonders nützlich im Unternehmensumfeld, und die zahlreichen Plugins der aktiven Community ermöglichen vielfältige Anwendungsfälle, die weit über ein traditionelles Wiki hinausgehen.
    el_GR: Ένα εύχρηστο και εξαιρετικά ευέλικτο λογισμικό wiki ανοιχτού κώδικα που δεν απαιτεί βάση δεδομένων. Αγαπιέται από τους χρήστες για την καθαρή και ευανάγνωστη σύνταξή του. Η ευκολία συντήρησης, δημιουργίας αντιγράφων ασφαλείας και ενσωμάτωσης το καθιστά αγαπημένο των διαχειριστών. Τα ενσωματωμένα στοιχεία ελέγχου πρόσβασης και οι σύνδεσμοι ελέγχου ταυτότητας καθιστούν το DokuWiki ιδιαίτερα χρήσιμο σε εταιρικό περιβάλλον και ο μεγάλος αριθμός πρόσθετων που συνεισφέρει η ζωντανή κοινότητά του επιτρέπει ένα ευρύ φάσμα περιπτώσεων χρήσης πέρα από ένα παραδοσιακό wiki.
    en_GB: A simple to use and highly versatile Open Source wiki software that doesn't require a database. It is loved by users for its clean and readable syntax. The ease of maintenance, backup and integration makes it an administrator's favourite. Built in access controls and authentication connectors make Dokuwiki especially useful in the enterprise context and the large number of plugins contributed by its vibrant community allow for a broad range of use cases beyond a traditional wiki.
    es_ES: Un software wiki de código abierto, sencillo de usar y muy versátil, que no requiere base de datos. Es muy apreciado por los usuarios por su sintaxis clara y legible. Su facilidad de mantenimiento, copia de seguridad e integración lo convierten en el favorito de los administradores. Los controles de acceso y los conectores de autenticación integrados hacen que DokuWiki sea especialmente útil en el ámbito empresarial, y la gran cantidad de complementos aportados por su dinámica comunidad permite una amplia gama de casos de uso que van más allá de un wiki tradicional.
    fr_FR: DokuWiki est un logiciel wiki open source simple d'utilisation et extrêmement polyvalent, ne nécessitant aucune base de données. Apprécié pour sa syntaxe claire et lisible, il est plébiscité par les utilisateurs. Sa facilité de maintenance, de sauvegarde et d'intégration en fait un outil de prédilection pour les administrateurs. Grâce à ses contrôles d'accès intégrés et ses connecteurs d'authentification, DokuWiki est particulièrement utile en entreprise. De plus, le grand nombre d'extensions proposées par sa communauté dynamique permet une large gamme d'utilisations, bien au-delà d'un wiki traditionnel.
    ga_IE: Bogearraí vicí foinse oscailte atá simplí le húsáid agus thar a bheith ilúsáideach nach dteastaíonn bunachar sonraí uaidh. Is breá le húsáideoirí é mar gheall ar a chomhréir ghlan agus inléite. Mar gheall ar an éascaíocht cothabhála, cúltaca agus comhtháthaithe, is fearr le riarthóirí é. Déanann rialuithe rochtana agus nascóirí fíordheimhnithe ionsuite DokuWiki thar a bheith úsáideach i gcomhthéacs fiontraíochta agus cuireann an líon mór breiseán a chuireann a phobal bríomhar ar fáil raon leathan cásanna úsáide ar fáil thar vicí traidisiúnta.
    hr_HR: Jednostavan za korištenje i vrlo svestran softver otvorenog koda za wiki koji ne zahtijeva bazu podataka. Korisnici ga vole zbog njegove čiste i čitljive sintakse. Jednostavnost održavanja, izrade sigurnosnih kopija i integracije čini ga omiljenim među administratorima. Ugrađene kontrole pristupa i konektori za autentifikaciju čine DokuWiki posebno korisnim u poslovnom kontekstu, a veliki broj dodataka koje doprinosi njegova živahna zajednica omogućuje širok raspon slučajeva upotrebe izvan tradicionalnog wikija.
    hu_HU: Egy egyszerűen használható és rendkívül sokoldalú, nyílt forráskódú wiki szoftver, amely nem igényel adatbázist. A felhasználók szeretik a tiszta és olvasható szintaxisáért. A könnyű karbantartás, biztonsági mentés és integráció a rendszergazdák kedvencévé teszi. A beépített hozzáférés-vezérlés és hitelesítési csatlakozók különösen hasznossá teszik a DokuWikit vállalati környezetben, és a pezsgő közösség által biztosított nagyszámú bővítmény széles körű felhasználási lehetőségeket tesz lehetővé a hagyományos wikin túl.
    it_IT: Un software wiki open source semplice da usare e altamente versatile che non richiede un database. È apprezzato dagli utenti per la sua sintassi pulita e leggibile. La facilità di manutenzione, backup e integrazione lo rende uno dei preferiti dagli amministratori. I controlli di accesso e i connettori di autenticazione integrati rendono DokuWiki particolarmente utile in ambito aziendale, e l'ampio numero di plugin sviluppati dalla sua vivace community consente una vasta gamma di casi d'uso che vanno ben oltre un wiki tradizionale.
    ja_JP: 使いやすく汎用性の高いオープンソースのWikiソフトウェアで、データベースは不要です。簡潔で読みやすい構文がユーザーに高く評価されています。メンテナンス、バックアップ、統合が容易なため、管理者にも人気があります。組み込みのアクセス制御と認証コネクタにより、DokuWikiは特に企業環境で役立ちます。また、活発なコミュニティによって提供される多数のプラグインにより、従来のWikiの枠を超えた幅広い用途に対応できます。
    ko_KR: 데이터베이스가 필요 없는 사용하기 쉽고 활용도가 매우 높은 오픈 소스 위키 소프트웨어입니다. 깔끔하고 가독성 좋은 구문으로 사용자들에게 사랑받고 있으며, 손쉬운 유지 관리, 백업 및 통합 기능으로 관리자들에게도 인기가 높습니다. 내장된 접근 제어 및 인증 커넥터를 통해 기업 환경에서 특히 유용하며, 활발한 커뮤니티에서 제공하는 수많은 플러그인을 통해 기존 위키의 틀을 넘어 다양한 활용 사례를 구현할 수 있습니다.
    ml_IN: ഉപയോഗിക്കാൻ എളുപ്പവും വൈവിധ്യപൂർണ്ണവുമായ ഒരു ഓപ്പൺ സോഴ്‌സ് വിക്കി സോഫ്റ്റ്‌വെയറാണ് ഇതിന്, ഒരു ഡാറ്റാബേസ് ആവശ്യമില്ല. വൃത്തിയുള്ളതും വായിക്കാൻ കഴിയുന്നതുമായ വാക്യഘടന കാരണം ഉപയോക്താക്കൾ ഇത് ഇഷ്ടപ്പെടുന്നു. അറ്റകുറ്റപ്പണികളുടെയും ബാക്കപ്പിന്റെയും സംയോജനത്തിന്റെയും എളുപ്പം ഇതിനെ അഡ്മിനിസ്ട്രേറ്റർമാരുടെ പ്രിയങ്കരമാക്കുന്നു. അന്തർനിർമ്മിതമായ ആക്‌സസ് നിയന്ത്രണങ്ങളും പ്രാമാണീകരണ കണക്ടറുകളും ഡോകുവിക്കിയെ എന്റർപ്രൈസ് സന്ദർഭത്തിൽ പ്രത്യേകിച്ചും ഉപയോഗപ്രദമാക്കുന്നു, കൂടാതെ അതിന്റെ ഊർജ്ജസ്വലമായ കമ്മ്യൂണിറ്റി സംഭാവന ചെയ്യുന്ന ധാരാളം പ്ലഗിനുകൾ പരമ്പരാഗത വിക്കിയപ്പുറം വിശാലമായ ഉപയോഗ കേസുകൾ അനുവദിക്കുന്നു.
    nb_NO: En brukervennlig og svært allsidig wiki-programvare med åpen kildekode som ikke krever en database. Den er elsket av brukere for sin rene og lesbare syntaks. Enkel vedlikehold, sikkerhetskopiering og integrering gjør den til en administrators favoritt. Innebygde tilgangskontroller og autentiseringskoblinger gjør DokuWiki spesielt nyttig i bedriftssammenheng, og det store antallet plugins som bidras av det pulserende fellesskapet, gir mulighet for et bredt spekter av brukstilfeller utover en tradisjonell wiki.
    nl_NL: DokuWiki is een gebruiksvriendelijke en zeer veelzijdige open-source wiki-software die geen database vereist. Gebruikers waarderen de heldere en leesbare syntaxis. Het gemakkelijke onderhoud, de back-upmogelijkheden en de integratie maken het een favoriet bij beheerders. De ingebouwde toegangscontrollen en authenticatieconnectoren maken DokuWiki bijzonder nuttig in een bedrijfsomgeving, en het grote aantal plugins dat door de actieve community is ontwikkeld, maakt een breed scala aan toepassingen mogelijk, die verder gaan dan een traditionele wiki.
    pl_PL: Proste w obsłudze i niezwykle wszechstronne oprogramowanie wiki typu open source, które nie wymaga bazy danych. Użytkownicy cenią je za przejrzystą i czytelną składnię. Łatwość konserwacji, tworzenia kopii zapasowych i integracji sprawia, że jest ono ulubionym narzędziem administratorów. Wbudowane mechanizmy kontroli dostępu i łączniki uwierzytelniania sprawiają, że DokuWiki jest szczególnie przydatne w przedsiębiorstwach, a duża liczba wtyczek udostępnianych przez aktywną społeczność pozwala na szeroki zakres zastosowań wykraczających poza tradycyjne wiki.
    pt_BR: Um software wiki de código aberto, simples de usar e altamente versátil, que não requer um banco de dados. É adorado pelos usuários por sua sintaxe limpa e legível. A facilidade de manutenção, backup e integração o torna o favorito dos administradores. Os controles de acesso e conectores de autenticação integrados tornam o DokuWiki especialmente útil no contexto corporativo, e o grande número de plugins contribuídos por sua ativa comunidade permite uma ampla gama de casos de uso além de uma wiki tradicional.
    ro_RO: Un software wiki open source simplu de utilizat și extrem de versatil, care nu necesită o bază de date. Este îndrăgit de utilizatori pentru sintaxa sa curată și lizibilă. Ușurința cu care se pot întreține, face backup și integrează îl face preferatul administratorilor. Controalele de acces și conectorii de autentificare încorporați fac DokuWiki deosebit de util în contextul întreprinderilor, iar numărul mare de plugin-uri oferite de comunitatea sa vibrantă permite o gamă largă de cazuri de utilizare dincolo de un wiki tradițional.
    ru_RU: Простое в использовании и очень универсальное программное обеспечение для вики-систем с открытым исходным кодом, не требующее базы данных. Пользователи любят его за чистый и читаемый синтаксис. Простота обслуживания, резервного копирования и интеграции делает его фаворитом среди администраторов. Встроенные средства контроля доступа и коннекторы аутентификации делают DokuWiki особенно полезным в корпоративной среде, а большое количество плагинов, разработанных активным сообществом, позволяет использовать его в самых разных сценариях, выходящих за рамки традиционной вики.
    sk_SK: Jednoduchý a vysoko všestranný open source wiki softvér, ktorý nevyžaduje databázu. Používatelia ho milujú pre jeho čistú a čitateľnú syntax. Jednoduchá údržba, zálohovanie a integrácia z neho robia obľúbenca administrátorov. Vstavané kontroly prístupu a autentifikačné konektory robia DokuWiki obzvlášť užitočným v podnikovom kontexte a veľké množstvo pluginov, ktoré prináša jeho dynamická komunita, umožňuje širokú škálu prípadov použitia nad rámec tradičnej wiki.
    sv_SE: En lättanvänd och mycket mångsidig wiki-programvara med öppen källkod som inte kräver någon databas. Den är älskad av användarna för sin rena och läsbara syntax. Det enkla underhållet, säkerhetskopieringen och integrationen gör den till en favorit bland administratörer. Inbyggda åtkomstkontroller och autentiseringskopplingar gör DokuWiki särskilt användbar i företagssammanhang och det stora antalet plugins som bidrar med från dess livliga community möjliggör ett brett spektrum av användningsområden utöver en traditionell wiki.
    tr_TR: Veritabanı gerektirmeyen, kullanımı kolay ve son derece çok yönlü bir açık kaynak kodlu wiki yazılımıdır. Temiz ve okunabilir sözdizimi nedeniyle kullanıcılar tarafından sevilmektedir. Bakım, yedekleme ve entegrasyon kolaylığı, onu yöneticilerin favorisi yapmaktadır. Dahili erişim kontrolleri ve kimlik doğrulama bağlantıları, DokuWiki'yi özellikle kurumsal ortamda kullanışlı hale getirirken, canlı topluluğu tarafından katkıda bulunulan çok sayıda eklenti, geleneksel bir wiki'nin ötesinde geniş bir kullanım alanı yelpazesine olanak tanır.
    zh_CN: 无需数据库、易于维护的开源 Wiki。
    zh_TW: 無需資料庫、易於維護的開源 Wiki。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/dokuwiki-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/dokuwiki-icon.png
  title:
    en_US: Dokuwiki (LinuxServer.io)
    ca_ES: Dokuwiki (LinuxServer.io)
    cs_CZ: Dokuwiki (LinuxServer.io)
    da_DK: Dokuwiki (LinuxServer.io)
    de_DE: Dokuwiki (LinuxServer.io)
    el_GR: Dokuwiki (LinuxServer.io)
    en_GB: Dokuwiki (LinuxServer.io)
    es_ES: Dokuwiki (LinuxServer.io)
    fr_FR: Dokuwiki (LinuxServer.io)
    ga_IE: Dokuwiki (LinuxServer.io)
    hr_HR: Dokuwiki (LinuxServer.io)
    hu_HU: Dokuwiki (LinuxServer.io)
    it_IT: Dokuwiki (LinuxServer.io)
    ja_JP: Dokuwiki (LinuxServer.io)
    ko_KR: Dokuwiki (LinuxServer.io)
    ml_IN: Dokuwiki (LinuxServer.io)
    nb_NO: Dokuwiki (LinuxServer.io)
    nl_NL: Dokuwiki (LinuxServer.io)
    pl_PL: Dokuwiki (LinuxServer.io)
    pt_BR: Dokuwiki (LinuxServer.io)
    ro_RO: Dokuwiki (LinuxServer.io)
    ru_RU: Dokuwiki (LinuxServer.io)
    sk_SK: Dokuwiki (LinuxServer.io)
    sv_SE: Dokuwiki (LinuxServer.io)
    tr_TR: Dokuwiki (LinuxServer.io)
    zh_CN: Dokuwiki（LinuxServer.io）
    zh_TW: Dokuwiki（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverdokuwiki
  port_map: '80'
  version: version-2026-07-14c
