name: linuxserver-airsonic-advanced
services:
  app:
    image: linuxserver/airsonic-advanced:11.1.4@sha256:4f7b0ae70513f432c9ec273d075c372fc539198191ed2e0f363bd614573faa57
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONTEXT_PATH: ''
      JAVA_OPTS: ''
    ports:
      - target: 4040
        published: 4040
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/airsonic-advanced/config
        target: /config
      - type: bind
        source: /DATA/AppData/airsonic-advanced/music
        target: /music
      - type: bind
        source: /DATA/AppData/airsonic-advanced/playlists
        target: /playlists
      - type: bind
        source: /DATA/AppData/airsonic-advanced/podcasts
        target: /podcasts
      - type: bind
        source: /DATA/AppData/airsonic-advanced/media
        target: /media
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverairsonicadvanced/assets/icon.png
  title:
    en_US: Airsonic advanced (LinuxServer.io)
    ca_ES: Airsonic advanced (LinuxServer.io)
    cs_CZ: Airsonic advanced (LinuxServer.io)
    da_DK: Airsonic advanced (LinuxServer.io)
    de_DE: Airsonic advanced (LinuxServer.io)
    el_GR: Airsonic advanced (LinuxServer.io)
    en_GB: Airsonic advanced (LinuxServer.io)
    es_ES: Airsonic advanced (LinuxServer.io)
    fr_FR: Airsonic advanced (LinuxServer.io)
    ga_IE: Airsonic advanced (LinuxServer.io)
    hr_HR: Airsonic advanced (LinuxServer.io)
    hu_HU: Airsonic advanced (LinuxServer.io)
    it_IT: Airsonic advanced (LinuxServer.io)
    ja_JP: Airsonic advanced (LinuxServer.io)
    ko_KR: Airsonic advanced (LinuxServer.io)
    ml_IN: Airsonic advanced (LinuxServer.io)
    nb_NO: Airsonic advanced (LinuxServer.io)
    nl_NL: Airsonic advanced (LinuxServer.io)
    pl_PL: Airsonic advanced (LinuxServer.io)
    pt_BR: Airsonic advanced (LinuxServer.io)
    ro_RO: Airsonic advanced (LinuxServer.io)
    ru_RU: Airsonic advanced (LinuxServer.io)
    sk_SK: Airsonic advanced (LinuxServer.io)
    sv_SE: Airsonic advanced (LinuxServer.io)
    tr_TR: Airsonic advanced (LinuxServer.io)
    zh_CN: Airsonic advanced（LinuxServer.io）
    zh_TW: Airsonic advanced（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverairsonicadvanced
  port_map: '4040'
  version: 11.1.4
