name: linuxserver-sqlitebrowser
services:
  app:
    image: linuxserver/sqlitebrowser:3.13.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sqlitebrowser/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: DB Browser for SQLite is a high quality, visual, open source tool to create, design, and edit database files compatible with SQLite.
    ca_ES: DB Browser per a SQLite és una eina visual, de codi obert i d'alta qualitat per crear, dissenyar i editar fitxers de bases de dades compatibles amb SQLite.
    cs_CZ: DB Browser pro SQLite je vysoce kvalitní, vizuální nástroj s otevřeným zdrojovým kódem pro vytváření, návrh a úpravu databázových souborů kompatibilních se SQLite.
    da_DK: DB Browser til SQLite er et visuelt open source-værktøj af høj kvalitet til at oprette, designe og redigere databasefiler, der er kompatible med SQLite.
    de_DE: DB Browser for SQLite ist ein hochwertiges, visuelles Open-Source-Tool zum Erstellen, Entwerfen und Bearbeiten von mit SQLite kompatiblen Datenbankdateien.
    el_GR: Το DB Browser για SQLite είναι ένα υψηλής ποιότητας, οπτικό, ανοιχτού κώδικα εργαλείο για τη δημιουργία, το σχεδιασμό και την επεξεργασία αρχείων βάσης δεδομένων συμβατών με το SQLite.
    en_GB: Db Browser for Sqlite is a high quality, visual, open source tool to create, design, and edit database files compatible with Sqlite.
    es_ES: DB Browser for SQLite es una herramienta visual de código abierto y de alta calidad para crear, diseñar y editar archivos de bases de datos compatibles con SQLite.
    fr_FR: DB Browser for SQLite est un outil visuel open source de haute qualité permettant de créer, concevoir et modifier des fichiers de base de données compatibles avec SQLite.
    ga_IE: Is uirlis foinse oscailte, amhairc, ardchaighdeáin é Brabhsálaí DB do SQLite chun comhaid bunachar sonraí atá comhoiriúnach le SQLite a chruthú, a dhearadh agus a chur in eagar.
    hr_HR: DB Browser za SQLite je visokokvalitetan, vizualni alat otvorenog koda za stvaranje, dizajniranje i uređivanje datoteka baza podataka kompatibilnih sa SQLiteom.
    hu_HU: A DB Browser for SQLite egy kiváló minőségű, vizuális, nyílt forráskódú eszköz, amellyel SQLite-kompatibilis adatbázisfájlokat hozhat létre, tervezhet és szerkeszthet.
    it_IT: DB Browser for SQLite è uno strumento open source di alta qualità, intuitivo e visivo, per creare, progettare e modificare file di database compatibili con SQLite.
    ja_JP: DB Browser for SQLiteは、SQLiteと互換性のあるデータベースファイルを作成、設計、編集するための、高品質で視覚的なオープンソースツールです。
    ko_KR: DB Browser for SQLite는 SQLite와 호환되는 데이터베이스 파일을 생성, 설계 및 편집할 수 있는 고품질의 시각적 오픈 소스 도구입니다.
    ml_IN: SQLite-നുള്ള DB ബ്രൗസർ, SQLite-ന് അനുയോജ്യമായ ഡാറ്റാബേസ് ഫയലുകൾ സൃഷ്ടിക്കാനും രൂപകൽപ്പന ചെയ്യാനും എഡിറ്റ് ചെയ്യാനുമുള്ള ഉയർന്ന നിലവാരമുള്ള, ദൃശ്യ, ഓപ്പൺ സോഴ്‌സ് ഉപകരണമാണ്.
    nb_NO: DB Browser for SQLite er et visuelt verktøy av høy kvalitet med åpen kildekode for å opprette, designe og redigere databasefiler som er kompatible med SQLite.
    nl_NL: DB Browser for SQLite is een hoogwaardige, visuele, open source tool voor het maken, ontwerpen en bewerken van databasebestanden die compatibel zijn met SQLite.
    pl_PL: DB Browser for SQLite to wysokiej jakości, wizualne narzędzie typu open source do tworzenia, projektowania i edytowania plików baz danych zgodnych z SQLite.
    pt_BR: O DB Browser for SQLite é uma ferramenta visual de código aberto de alta qualidade para criar, projetar e editar arquivos de banco de dados compatíveis com SQLite.
    ro_RO: DB Browser pentru SQLite este un instrument vizual, open source și de înaltă calitate pentru crearea, proiectarea și editarea fișierelor de baze de date compatibile cu SQLite.
    ru_RU: DB Browser for SQLite — это высококачественный визуальный инструмент с открытым исходным кодом для создания, проектирования и редактирования файлов баз данных, совместимых с SQLite.
    sk_SK: DB Browser pre SQLite je vysoko kvalitný, vizuálny nástroj s otvoreným zdrojovým kódom na vytváranie, návrh a úpravu databázových súborov kompatibilných so SQLite.
    sv_SE: DB Browser för SQLite är ett högkvalitativt, visuellt verktyg med öppen källkod för att skapa, designa och redigera databasfiler som är kompatibla med SQLite.
    tr_TR: DB Browser for SQLite, SQLite ile uyumlu veritabanı dosyaları oluşturmak, tasarlamak ve düzenlemek için kullanılan yüksek kaliteli, görsel, açık kaynaklı bir araçtır.
    zh_CN: DB Browser for SQLite 是一款高质量、开源的可视化工具，用于创建、设计和编辑与 SQLite 兼容的数据库文件。
    zh_TW: DB Browser for SQLite 是一款高質量、開源的視覺化工具，用於建立、設計和編輯與 SQLite 相容的資料庫檔案。
  tagline:
    en_US: A high quality, visual, open source tool to create, design, and edit database files compatible with SQLite.
    ca_ES: Una eina visual de codi obert d'alta qualitat per crear, dissenyar i editar fitxers de bases de dades compatibles amb SQLite.
    cs_CZ: Vysoce kvalitní, vizuální nástroj s otevřeným zdrojovým kódem pro vytváření, návrh a úpravu databázových souborů kompatibilní se SQLite.
    da_DK: Et visuelt open source-værktøj af høj kvalitet til at oprette, designe og redigere databasefiler, der er kompatible med SQLite.
    de_DE: Ein hochwertiges, visuelles Open-Source-Tool zum Erstellen, Entwerfen und Bearbeiten von mit SQLite kompatiblen Datenbankdateien.
    el_GR: Ένα υψηλής ποιότητας, οπτικό, ανοιχτού κώδικα εργαλείο για τη δημιουργία, το σχεδιασμό και την επεξεργασία αρχείων βάσης δεδομένων συμβατών με SQLite.
    en_GB: A high quality, visual, open source tool to create, design, and edit database files compatible with Sqlite.
    es_ES: Una herramienta visual de código abierto y de alta calidad para crear, diseñar y editar archivos de bases de datos compatibles con SQLite.
    fr_FR: Un outil visuel de haute qualité et open source pour créer, concevoir et modifier des fichiers de base de données compatibles avec SQLite.
    ga_IE: Uirlis foinse oscailte amhairc ardchaighdeáin chun comhaid bunachar sonraí atá comhoiriúnach le SQLite a chruthú, a dhearadh agus a chur in eagar.
    hr_HR: Visokokvalitetan, vizualni alat otvorenog koda za stvaranje, dizajniranje i uređivanje datoteka baza podataka kompatibilan sa SQLiteom.
    hu_HU: Egy kiváló minőségű, vizuális, nyílt forráskódú eszköz SQLite-kompatibilis adatbázisfájlok létrehozásához, tervezéséhez és szerkesztéséhez.
    it_IT: Uno strumento open source di alta qualità, intuitivo e con interfaccia grafica, per creare, progettare e modificare file di database compatibili con SQLite.
    ja_JP: SQLiteと互換性のあるデータベースファイルを作成、設計、編集するための、高品質で視覚的なオープンソースツール。
    ko_KR: SQLite와 호환되는 데이터베이스 파일을 생성, 디자인 및 편집할 수 있는 고품질의 시각적 오픈 소스 도구입니다.
    ml_IN: SQLite-ന് അനുയോജ്യമായ ഡാറ്റാബേസ് ഫയലുകൾ സൃഷ്ടിക്കാനും രൂപകൽപ്പന ചെയ്യാനും എഡിറ്റ് ചെയ്യാനുമുള്ള ഉയർന്ന നിലവാരമുള്ള, ദൃശ്യ, ഓപ്പൺ സോഴ്‌സ് ഉപകരണം.
    nb_NO: Et visuelt verktøy av høy kvalitet med åpen kildekode for å opprette, designe og redigere databasefiler som er kompatible med SQLite.
    nl_NL: Een hoogwaardige, visuele, open source tool voor het maken, ontwerpen en bewerken van databasebestanden die compatibel zijn met SQLite.
    pl_PL: Wysokiej jakości, wizualne narzędzie typu open source do tworzenia, projektowania i edytowania plików baz danych zgodnych z SQLite.
    pt_BR: Uma ferramenta visual de código aberto e de alta qualidade para criar, projetar e editar arquivos de banco de dados compatíveis com SQLite.
    ro_RO: Un instrument vizual, open source, de înaltă calitate, pentru crearea, proiectarea și editarea fișierelor de baze de date compatibile cu SQLite.
    ru_RU: Высококачественный визуальный инструмент с открытым исходным кодом для создания, проектирования и редактирования файлов баз данных, совместимых с SQLite.
    sk_SK: Vysokokvalitný, vizuálny nástroj s otvoreným zdrojovým kódom na vytváranie, návrh a úpravu databázových súborov kompatibilný so SQLite.
    sv_SE: Ett högkvalitativt, visuellt verktyg med öppen källkod för att skapa, designa och redigera databasfiler kompatibla med SQLite.
    tr_TR: SQLite ile uyumlu veritabanı dosyaları oluşturmak, tasarlamak ve düzenlemek için yüksek kaliteli, görsel, açık kaynaklı bir araç.
    zh_CN: 以可视化方式创建和编辑 SQLite 数据库。
    zh_TW: 以視覺化方式建立和編輯 SQLite 資料庫。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sqlitebrowser-banner.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sqlitebrowser-banner.png
  title:
    en_US: Sqlitebrowser (LinuxServer.io)
    ca_ES: Sqlitebrowser (LinuxServer.io)
    cs_CZ: Sqlitebrowser (LinuxServer.io)
    da_DK: Sqlitebrowser (LinuxServer.io)
    de_DE: Sqlitebrowser (LinuxServer.io)
    el_GR: Sqlitebrowser (LinuxServer.io)
    en_GB: Sqlitebrowser (LinuxServer.io)
    es_ES: Sqlitebrowser (LinuxServer.io)
    fr_FR: Sqlitebrowser (LinuxServer.io)
    ga_IE: Sqlitebrowser (LinuxServer.io)
    hr_HR: Sqlitebrowser (LinuxServer.io)
    hu_HU: Sqlitebrowser (LinuxServer.io)
    it_IT: Sqlitebrowser (LinuxServer.io)
    ja_JP: Sqlitebrowser (LinuxServer.io)
    ko_KR: Sqlitebrowser (LinuxServer.io)
    ml_IN: Sqlitebrowser (LinuxServer.io)
    nb_NO: Sqlitebrowser (LinuxServer.io)
    nl_NL: Sqlitebrowser (LinuxServer.io)
    pl_PL: Sqlitebrowser (LinuxServer.io)
    pt_BR: Sqlitebrowser (LinuxServer.io)
    ro_RO: Sqlitebrowser (LinuxServer.io)
    ru_RU: Sqlitebrowser (LinuxServer.io)
    sk_SK: Sqlitebrowser (LinuxServer.io)
    sv_SE: Sqlitebrowser (LinuxServer.io)
    tr_TR: Sqlitebrowser (LinuxServer.io)
    zh_CN: Sqlitebrowser（LinuxServer.io）
    zh_TW: Sqlitebrowser（LinuxServer.io）
  category: Developer
  id: wisdomsky.linuxserver.linuxserversqlitebrowser
  port_map: '3000'
  version: 3.13.1
