name: linuxserver-retroarch
services:
  app:
    image: linuxserver/retroarch:1.22.2@sha256:80117ad65043a4ac3fe9f221c0be2373dfd5ddf57f0b4663da54f135f3924c69
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/retroarch/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverretroarch/assets/icon.png
  title:
    en_US: Retroarch (LinuxServer.io)
    ca_ES: Retroarch (LinuxServer.io)
    cs_CZ: Retroarch (LinuxServer.io)
    da_DK: Retroarch (LinuxServer.io)
    de_DE: Retroarch (LinuxServer.io)
    el_GR: Retroarch (LinuxServer.io)
    en_GB: Retroarch (LinuxServer.io)
    es_ES: Retroarch (LinuxServer.io)
    fr_FR: Retroarch (LinuxServer.io)
    ga_IE: Retroarch (LinuxServer.io)
    hr_HR: Retroarch (LinuxServer.io)
    hu_HU: Retroarch (LinuxServer.io)
    it_IT: Retroarch (LinuxServer.io)
    ja_JP: Retroarch (LinuxServer.io)
    ko_KR: Retroarch (LinuxServer.io)
    ml_IN: Retroarch (LinuxServer.io)
    nb_NO: Retroarch (LinuxServer.io)
    nl_NL: Retroarch (LinuxServer.io)
    pl_PL: Retroarch (LinuxServer.io)
    pt_BR: Retroarch (LinuxServer.io)
    ro_RO: Retroarch (LinuxServer.io)
    ru_RU: Retroarch (LinuxServer.io)
    sk_SK: Retroarch (LinuxServer.io)
    sv_SE: Retroarch (LinuxServer.io)
    tr_TR: Retroarch (LinuxServer.io)
    zh_CN: Retroarch（LinuxServer.io）
    zh_TW: Retroarch（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverretroarch
  port_map: '3000'
  version: 1.22.2
