name: linuxserver-resilio-sync
services:
  app:
    image: linuxserver/resilio-sync:3.1.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 55555
        published: 55555
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/resilio-sync/config
        target: /config
      - type: bind
        source: /DATA/AppData/resilio-sync/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/resilio-sync/sync
        target: /sync
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverresiliosync/assets/icon.png
  title:
    en_US: Resilio sync (LinuxServer.io)
    ca_ES: Resilio sync (LinuxServer.io)
    cs_CZ: Resilio sync (LinuxServer.io)
    da_DK: Resilio sync (LinuxServer.io)
    de_DE: Resilio sync (LinuxServer.io)
    el_GR: Resilio sync (LinuxServer.io)
    en_GB: Resilio sync (LinuxServer.io)
    es_ES: Resilio sync (LinuxServer.io)
    fr_FR: Resilio sync (LinuxServer.io)
    ga_IE: Resilio sync (LinuxServer.io)
    hr_HR: Resilio sync (LinuxServer.io)
    hu_HU: Resilio sync (LinuxServer.io)
    it_IT: Resilio sync (LinuxServer.io)
    ja_JP: Resilio sync (LinuxServer.io)
    ko_KR: Resilio sync (LinuxServer.io)
    ml_IN: Resilio sync (LinuxServer.io)
    nb_NO: Resilio sync (LinuxServer.io)
    nl_NL: Resilio sync (LinuxServer.io)
    pl_PL: Resilio sync (LinuxServer.io)
    pt_BR: Resilio sync (LinuxServer.io)
    ro_RO: Resilio sync (LinuxServer.io)
    ru_RU: Resilio sync (LinuxServer.io)
    sk_SK: Resilio sync (LinuxServer.io)
    sv_SE: Resilio sync (LinuxServer.io)
    tr_TR: Resilio sync (LinuxServer.io)
    zh_CN: Resilio sync（LinuxServer.io）
    zh_TW: Resilio sync（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverresiliosync
  version: 3.1.2
