name: linuxserver-blender
services:
  app:
    image: linuxserver/blender:5.2.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/blender/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Blender is a free and open-source 3D computer graphics software toolset used for creating animated films, visual effects, art, 3D printed models, motion graphics, interactive 3D applications, virtual reality, and computer games. This image does not support GPU rendering out of the box only accelerated workspace experience
    ca_ES: Blender és un conjunt d'eines de programari de gràfics 3D per ordinador gratuït i de codi obert que s'utilitza per crear pel·lícules d'animació, efectes visuals, art, models impresos en 3D, gràfics en moviment, aplicacions 3D interactives, realitat virtual i jocs d'ordinador. Aquesta imatge no admet la renderització GPU, només una experiència d'espai de treball accelerada.
    cs_CZ: Blender je bezplatná sada nástrojů pro 3D počítačovou grafiku s otevřeným zdrojovým kódem, která se používá k vytváření animovaných filmů, vizuálních efektů, umění, 3D tištěných modelů, pohyblivé grafiky, interaktivních 3D aplikací, virtuální reality a počítačových her. Tento obrázek nepodporuje vykreslování pomocí GPU, pouze akcelerované pracovní prostředí.
    da_DK: Blender er et gratis og open source-værktøjssæt til 3D-computergrafik, der bruges til at skabe animerede film, visuelle effekter, kunst, 3D-printede modeller, bevægelsesgrafik, interaktive 3D-applikationer, virtual reality og computerspil. Dette billede understøtter ikke GPU-rendering, kun en accelereret arbejdspladsoplevelse.
    de_DE: Blender ist eine kostenlose Open-Source-Software für 3D-Computergrafik, die zur Erstellung von Animationsfilmen, visuellen Effekten, Kunstwerken, 3D-gedruckten Modellen, Motion Graphics, interaktiven 3D-Anwendungen, Virtual Reality und Computerspielen verwendet wird. Dieses Bild unterstützt standardmäßig kein GPU-Rendering, sondern nur eine beschleunigte Arbeitsumgebung.
    el_GR: Το Blender είναι ένα δωρεάν και ανοιχτού κώδικα λογισμικό τρισδιάστατων γραφικών υπολογιστών που χρησιμοποιείται για τη δημιουργία κινούμενων ταινιών, οπτικών εφέ, τέχνης, τρισδιάστατα εκτυπωμένων μοντέλων, κινούμενων γραφικών, διαδραστικών εφαρμογών 3D, εικονικής πραγματικότητας και παιχνιδιών υπολογιστή. Αυτή η εικόνα δεν υποστηρίζει απόδοση GPU αμέσως μόλις ολοκληρωθεί η συσκευασία, αλλά μόνο επιταχυνόμενη εμπειρία χώρου εργασίας.
    en_GB: Blender is a free and open-source 3D computer graphics software toolset used for creating animated films, visual effects, art, 3D printed models, motion graphics, interactive 3D applications, virtual reality, and computer games. This image does not support Gpu rendering out of the box only accelerated workspace experience
    es_ES: Blender es un conjunto de herramientas de software de gráficos 3D gratuito y de código abierto que se utiliza para crear películas de animación, efectos visuales, arte, modelos impresos en 3D, gráficos en movimiento, aplicaciones 3D interactivas, realidad virtual y videojuegos. Esta imagen no admite la renderización por GPU de forma predeterminada, solo la experiencia acelerada del espacio de trabajo.
    fr_FR: "Blender est un logiciel libre et gratuit de graphisme 3D utilisé pour créer des films d'animation, des effets visuels, des œuvres d'art, des modèles pour impression 3D, des animations graphiques, des applications 3D interactives, de la réalité virtuelle et des jeux vidéo. Cette image ne prend pas en charge le rendu GPU nativement\_; seule l'accélération de l'espace de travail est disponible."
    ga_IE: Is sraith uirlisí bogearraí grafaicí ríomhaire 3T saor in aisce agus foinse oscailte é Blender a úsáidtear chun scannáin bheochana, éifeachtaí amhairc, ealaín, samhlacha priontáilte 3T, grafaicí gluaisne, feidhmchláir idirghníomhacha 3T, réaltacht fhíorúil, agus cluichí ríomhaire a chruthú. Ní thacaíonn an íomhá seo le rindreáil GPU díreach as an mbosca, ach le taithí spáis oibre luathaithe amháin.
    hr_HR: Blender je besplatni i otvorenog koda skup alata za 3D računalnu grafiku koji se koristi za izradu animiranih filmova, vizualnih efekata, umjetnosti, 3D ispisanih modela, pokretne grafike, interaktivnih 3D aplikacija, virtualne stvarnosti i računalnih igara. Ova slika ne podržava GPU renderiranje odmah po instalaciji, već samo ubrzano radno okruženje.
    hu_HU: A Blender egy ingyenes és nyílt forráskódú 3D számítógépes grafikai szoftvereszközkészlet, amelyet animációs filmek, vizuális effektek, művészeti alkotások, 3D nyomtatott modellek, mozgóképes grafika, interaktív 3D alkalmazások, virtuális valóság és számítógépes játékok készítésére használnak. Ez a kép nem támogatja a GPU-s renderelést a dobozból kivéve, csak a gyorsított munkaterület élményét.
    it_IT: Blender è un software di grafica 3D gratuito e open-source utilizzato per creare film d'animazione, effetti visivi, opere d'arte, modelli per la stampa 3D, motion graphics, applicazioni 3D interattive, realtà virtuale e videogiochi. Questa immagine non supporta il rendering GPU di default, ma solo un'esperienza di lavoro accelerata.
    ja_JP: Blenderは、アニメーション映画、視覚効果、アート、3Dプリントモデル、モーショングラフィックス、インタラクティブな3Dアプリケーション、仮想現実、コンピュータゲームの作成に使用される、無料のオープンソース3Dコンピュータグラフィックスソフトウェアツールセットです。このイメージは、そのままではGPUレンダリングをサポートしておらず、高速ワークスペースエクスペリエンスのみをサポートしています。
    ko_KR: Blender는 애니메이션 영화, 시각 효과, 미술 작품, 3D 프린팅 모델, 모션 그래픽, 대화형 3D 애플리케이션, 가상 현실 및 컴퓨터 게임 제작에 사용되는 무료 오픈 소스 3D 컴퓨터 그래픽 소프트웨어 도구 모음입니다. 이 이미지는 기본적으로 GPU 렌더링을 지원하지 않으며, 가속 작업 공간 환경만 제공합니다.
    ml_IN: ആനിമേറ്റഡ് ഫിലിമുകൾ, വിഷ്വൽ ഇഫക്റ്റുകൾ, ആർട്ട്, 3D പ്രിന്റഡ് മോഡലുകൾ, മോഷൻ ഗ്രാഫിക്സ്, ഇന്ററാക്ടീവ് 3D ആപ്ലിക്കേഷനുകൾ, വെർച്വൽ റിയാലിറ്റി, കമ്പ്യൂട്ടർ ഗെയിമുകൾ എന്നിവ സൃഷ്ടിക്കാൻ ഉപയോഗിക്കുന്ന ഒരു സ്വതന്ത്രവും ഓപ്പൺ സോഴ്‌സ് 3D കമ്പ്യൂട്ടർ ഗ്രാഫിക്സ് സോഫ്റ്റ്‌വെയർ ടൂൾസെറ്റാണ് ബ്ലെൻഡർ. ഈ ചിത്രം GPU റെൻഡറിംഗിനെ ബോക്സിന് പുറത്ത് നിന്ന് പിന്തുണയ്ക്കുന്നില്ല, ത്വരിതപ്പെടുത്തിയ വർക്ക്‌സ്‌പേസ് അനുഭവം മാത്രം.
    nb_NO: Blender er et gratis og åpen kildekode-programvaresett for 3D-datagrafikk som brukes til å lage animerte filmer, visuelle effekter, kunst, 3D-printede modeller, bevegelig grafikk, interaktive 3D-applikasjoner, virtuell virkelighet og dataspill. Dette bildet støtter ikke GPU-gjengivelse, bare akselerert arbeidsområdeopplevelse.
    nl_NL: Blender is een gratis en open-source 3D-computerprogramma dat gebruikt wordt voor het maken van animatiefilms, visuele effecten, kunst, 3D-geprinte modellen, motion graphics, interactieve 3D-applicaties, virtual reality en computerspellen. Deze afbeelding ondersteunt standaard geen GPU-rendering, alleen een versnelde werkruimte.
    pl_PL: Blender to darmowy i otwarty zestaw narzędzi do grafiki komputerowej 3D, służący do tworzenia filmów animowanych, efektów wizualnych, grafiki, modeli drukowanych w 3D, grafiki ruchomej, interaktywnych aplikacji 3D, rzeczywistości wirtualnej i gier komputerowych. Ten obraz nie obsługuje renderowania GPU w trybie domyślnym, a jedynie przyspieszonego środowiska roboczego.
    pt_BR: O Blender é um conjunto de ferramentas de software gráfico 3D gratuito e de código aberto usado para criar filmes de animação, efeitos visuais, arte, modelos para impressão 3D, motion graphics, aplicativos 3D interativos, realidade virtual e jogos de computador. Esta imagem não oferece suporte à renderização por GPU nativamente, apenas à experiência de espaço de trabalho acelerado.
    ro_RO: Blender este un set de instrumente software gratuit și open-source pentru grafică 3D pe calculator, utilizat pentru crearea de filme animate, efecte vizuale, artă, modele imprimate 3D, grafică animată, aplicații 3D interactive, realitate virtuală și jocuri pe calculator. Această imagine nu acceptă randarea GPU direct din cutie, ci doar o experiență de lucru accelerată.
    ru_RU: Blender — это бесплатный набор инструментов с открытым исходным кодом для 3D-компьютерной графики, используемый для создания анимационных фильмов, визуальных эффектов, произведений искусства, 3D-моделей для печати, моушн-графики, интерактивных 3D-приложений, виртуальной реальности и компьютерных игр. Данный образ не поддерживает рендеринг на графическом процессоре (GPU) по умолчанию, только ускоренное рабочее пространство.
    sk_SK: Blender je bezplatná sada nástrojov s otvoreným zdrojovým kódom pre 3D počítačovú grafiku, ktorá sa používa na vytváranie animovaných filmov, vizuálnych efektov, umenia, 3D tlačených modelov, pohyblivej grafiky, interaktívnych 3D aplikácií, virtuálnej reality a počítačových hier. Tento obrázok nepodporuje vykresľovanie pomocou GPU, iba zrýchlené prostredie pracovného priestoru.
    sv_SE: Blender är en gratis och öppen källkodsbaserad programvara för 3D-datorgrafik som används för att skapa animerade filmer, visuella effekter, konst, 3D-utskrivna modeller, rörlig grafik, interaktiva 3D-applikationer, virtuell verklighet och datorspel. Den här bilden stöder inte GPU-rendering direkt ur lådan, endast accelererad arbetsyta.
    tr_TR: Blender, animasyon filmler, görsel efektler, sanat eserleri, 3 boyutlu yazdırılabilir modeller, hareketli grafikler, etkileşimli 3 boyutlu uygulamalar, sanal gerçeklik ve bilgisayar oyunları oluşturmak için kullanılan ücretsiz ve açık kaynaklı bir 3 boyutlu bilgisayar grafik yazılım araç setidir. Bu görüntü, varsayılan olarak GPU işlemeyi desteklemez, yalnızca hızlandırılmış çalışma alanı deneyimini destekler.
    zh_CN: Blender 是一套免费的开源 3D 图形软件，可用于制作动画电影、视觉特效、艺术作品、3D 打印模型、动态图形、交互式 3D 应用、虚拟现实和电脑游戏。此镜像默认仅提供工作区图形加速，不支持开箱即用的 GPU 渲染。
    zh_TW: Blender 是一套免費的開源 3D 圖形軟體，可用於製作動畫電影、視覺特效、藝術作品、3D 列印模型、動態圖形、互動式 3D 應用、虛擬現實和電腦遊戲。此映象預設僅提供工作區圖形加速，不支援開箱即用的 GPU 渲染。
  tagline:
    en_US: A free and open-source 3D computer graphics software toolset used for creating animated films, visual effects, art, 3D printed models, motion graphics, interactive 3D applications, virtual reality, and computer games. This image does not support GPU rendering out of the box only accelerated workspace experience
    ca_ES: Un conjunt d'eines de programari de gràfics per ordinador 3D gratuït i de codi obert que s'utilitza per crear pel·lícules d'animació, efectes visuals, art, models impresos en 3D, gràfics en moviment, aplicacions 3D interactives, realitat virtual i jocs d'ordinador. Aquesta imatge no admet la renderització GPU des del primer moment, només una experiència d'espai de treball accelerada.
    cs_CZ: Sada nástrojů pro 3D počítačovou grafiku s otevřeným zdrojovým kódem, která se používá k vytváření animovaných filmů, vizuálních efektů, umění, 3D tištěných modelů, pohyblivé grafiky, interaktivních 3D aplikací, virtuální reality a počítačových her. Tento obraz nepodporuje vykreslování pomocí GPU, pouze akcelerované pracovní prostředí.
    da_DK: Et gratis og open source-værktøjssæt til 3D-computergrafik, der bruges til at skabe animerede film, visuelle effekter, kunst, 3D-printede modeller, bevægelsesgrafik, interaktive 3D-applikationer, virtual reality og computerspil. Dette billede understøtter ikke GPU-rendering, kun en accelereret arbejdspladsoplevelse.
    de_DE: Ein kostenloses Open-Source-3D-Computergrafik-Software-Toolset zur Erstellung von Animationsfilmen, visuellen Effekten, Kunstwerken, 3D-gedruckten Modellen, Motion Graphics, interaktiven 3D-Anwendungen, Virtual Reality und Computerspielen. Dieses Image unterstützt standardmäßig kein GPU-Rendering, sondern nur eine beschleunigte Arbeitsumgebung.
    el_GR: Ένα δωρεάν και ανοιχτού κώδικα σύνολο εργαλείων λογισμικού τρισδιάστατων γραφικών υπολογιστών που χρησιμοποιείται για τη δημιουργία κινούμενων ταινιών, οπτικών εφέ, τέχνης, τρισδιάστατα εκτυπωμένων μοντέλων, κινούμενων γραφικών, διαδραστικών εφαρμογών 3D, εικονικής πραγματικότητας και παιχνιδιών υπολογιστή. Αυτή η εικόνα δεν υποστηρίζει απόδοση GPU αμέσως μόλις ολοκληρωθεί η συσκευασία, αλλά μόνο επιταχυνόμενη εμπειρία χώρου εργασίας.
    en_GB: A free and open-source 3D computer graphics software toolset used for creating animated films, visual effects, art, 3D printed models, motion graphics, interactive 3D applications, virtual reality, and computer games. This image does not support Gpu rendering out of the box only accelerated workspace experience
    es_ES: Un conjunto de herramientas de software de gráficos 3D gratuito y de código abierto utilizado para crear películas de animación, efectos visuales, arte, modelos impresos en 3D, gráficos en movimiento, aplicaciones 3D interactivas, realidad virtual y videojuegos. Esta imagen no admite renderizado por GPU de forma predeterminada, solo una experiencia de espacio de trabajo acelerada.
    fr_FR: "Suite logicielle libre et gratuite de graphisme 3D permettant de créer des films d'animation, des effets visuels, des œuvres d'art, des modèles imprimés en 3D, des animations graphiques, des applications 3D interactives, de la réalité virtuelle et des jeux vidéo. Cette image ne prend pas en charge le rendu GPU nativement\_; seule l'accélération matérielle est disponible."
    ga_IE: Tacar uirlisí bogearraí grafaicí ríomhaire 3T saor in aisce agus foinse oscailte a úsáidtear chun scannáin bheochana, éifeachtaí amhairc, ealaín, samhlacha priontáilte 3T, grafaicí gluaisne, feidhmchláir idirghníomhacha 3T, réaltacht fhíorúil, agus cluichí ríomhaire a chruthú. Ní thacaíonn an íomhá seo le rindreáil GPU díreach as an mbosca, ach le taithí spáis oibre luathaithe amháin.
    hr_HR: Besplatni i otvoreni skup alata za 3D računalnu grafiku koji se koristi za izradu animiranih filmova, vizualnih efekata, umjetnosti, 3D ispisanih modela, pokretne grafike, interaktivnih 3D aplikacija, virtualne stvarnosti i računalnih igara. Ova slika ne podržava GPU renderiranje odmah po instalaciji, već samo ubrzano radno okruženje.
    hu_HU: Ingyenes és nyílt forráskódú 3D számítógépes grafikai szoftvereszközkészlet animációs filmek, vizuális effektek, művészeti alkotások, 3D nyomtatott modellek, mozgóképes grafika, interaktív 3D alkalmazások, virtuális valóság és számítógépes játékok készítésére. Ez a kép nem támogatja a GPU-s renderelést az alapértelmezés szerint, csak a gyorsított munkaterület élményét.
    it_IT: Un set di strumenti software per la grafica 3D, gratuito e open-source, utilizzato per la creazione di film d'animazione, effetti visivi, opere d'arte, modelli stampati in 3D, motion graphics, applicazioni 3D interattive, realtà virtuale e videogiochi. Questa immagine non supporta il rendering GPU in modo nativo, ma solo un'esperienza di accelerazione tramite workspace.
    ja_JP: アニメーション映画、視覚効果、アート、3Dプリントモデル、モーショングラフィックス、インタラクティブ3Dアプリケーション、仮想現実、コンピュータゲームの作成に使用される、無料のオープンソース3Dコンピュータグラフィックスソフトウェアツールセットです。このイメージは、そのままではGPUレンダリングをサポートしておらず、高速ワークスペースエクスペリエンスのみをサポートしています。
    ko_KR: 애니메이션 영화, 시각 효과, 미술 작품, 3D 프린팅 모델, 모션 그래픽, 대화형 3D 애플리케이션, 가상 현실 및 컴퓨터 게임 제작에 사용되는 무료 오픈 소스 3D 컴퓨터 그래픽 소프트웨어 도구 모음입니다. 이 이미지는 기본적으로 GPU 렌더링을 지원하지 않으며, 가속 작업 공간 환경만 제공합니다.
    ml_IN: ആനിമേറ്റഡ് ഫിലിമുകൾ, വിഷ്വൽ ഇഫക്റ്റുകൾ, ആർട്ട്, 3D പ്രിന്റഡ് മോഡലുകൾ, മോഷൻ ഗ്രാഫിക്സ്, ഇന്ററാക്ടീവ് 3D ആപ്ലിക്കേഷനുകൾ, വെർച്വൽ റിയാലിറ്റി, കമ്പ്യൂട്ടർ ഗെയിമുകൾ എന്നിവ സൃഷ്ടിക്കാൻ ഉപയോഗിക്കുന്ന ഒരു സ്വതന്ത്രവും ഓപ്പൺ സോഴ്‌സ് 3D കമ്പ്യൂട്ടർ ഗ്രാഫിക്സ് സോഫ്റ്റ്‌വെയർ ടൂൾസെറ്റ്. ഈ ചിത്രം GPU റെൻഡറിംഗിനെ പിന്തുണയ്ക്കുന്നില്ല, ത്വരിതപ്പെടുത്തിയ വർക്ക്‌സ്‌പേസ് അനുഭവം മാത്രം.
    nb_NO: Et gratis og åpen kildekode-programvaresett for 3D-datagrafikk som brukes til å lage animerte filmer, visuelle effekter, kunst, 3D-printede modeller, bevegelig grafikk, interaktive 3D-applikasjoner, virtuell virkelighet og dataspill. Dette bildet støtter ikke GPU-gjengivelse, bare akselerert arbeidsområdeopplevelse.
    nl_NL: Een gratis en open-source 3D-computerprogramma voor grafische toepassingen, gebruikt voor het maken van animatiefilms, visuele effecten, kunst, 3D-geprinte modellen, motion graphics, interactieve 3D-applicaties, virtual reality en computerspellen. Deze afbeelding ondersteunt standaard geen GPU-rendering, alleen een versnelde werkruimte.
    pl_PL: Darmowy i otwarty zestaw narzędzi do grafiki komputerowej 3D, służący do tworzenia filmów animowanych, efektów wizualnych, grafiki, modeli drukowanych w 3D, grafiki ruchomej, interaktywnych aplikacji 3D, rzeczywistości wirtualnej i gier komputerowych. Ten obraz nie obsługuje renderowania GPU w trybie „out of the box” – obsługuje jedynie akcelerowany obszar roboczy.
    pt_BR: Um conjunto de ferramentas de software gráfico 3D gratuito e de código aberto usado para criar filmes de animação, efeitos visuais, arte, modelos impressos em 3D, motion graphics, aplicativos 3D interativos, realidade virtual e jogos de computador. Esta imagem não oferece suporte à renderização por GPU nativamente, apenas à experiência de espaço de trabalho acelerado.
    ro_RO: Un set de instrumente software de grafică 3D pe calculator, gratuit și open-source, utilizat pentru crearea de filme animate, efecte vizuale, artă, modele imprimate 3D, grafică animată, aplicații 3D interactive, realitate virtuală și jocuri pe calculator. Această imagine nu acceptă randarea GPU direct din cutie, ci oferă doar o experiență accelerată în spațiul de lucru.
    ru_RU: Бесплатный набор инструментов с открытым исходным кодом для 3D-компьютерной графики, используемый для создания анимационных фильмов, визуальных эффектов, произведений искусства, 3D-моделей для печати, моушн-графики, интерактивных 3D-приложений, виртуальной реальности и компьютерных игр. Данный образ не поддерживает рендеринг на графическом процессоре (GPU) по умолчанию, только ускоренное отображение в рабочей области.
    sk_SK: Bezplatná sada nástrojov pre 3D počítačovú grafiku s otvoreným zdrojovým kódom, ktorá sa používa na vytváranie animovaných filmov, vizuálnych efektov, umenia, 3D tlačených modelov, pohyblivej grafiky, interaktívnych 3D aplikácií, virtuálnej reality a počítačových hier. Tento obrázok nepodporuje vykresľovanie pomocou GPU, iba zrýchlené prostredie pracovného priestoru.
    sv_SE: En gratis och öppen källkodsbaserad 3D-datorgrafikprogramvara som används för att skapa animerade filmer, visuella effekter, konst, 3D-utskrivna modeller, rörlig grafik, interaktiva 3D-applikationer, virtuell verklighet och datorspel. Den här bilden stöder inte GPU-rendering direkt ur lådan, endast accelererad arbetsyta.
    tr_TR: Animasyon filmler, görsel efektler, sanat eserleri, 3 boyutlu yazdırılabilir modeller, hareketli grafikler, etkileşimli 3 boyutlu uygulamalar, sanal gerçeklik ve bilgisayar oyunları oluşturmak için kullanılan ücretsiz ve açık kaynaklı bir 3 boyutlu bilgisayar grafik yazılım araç seti. Bu görüntü, varsayılan olarak GPU işlemeyi desteklemez, yalnızca hızlandırılmış çalışma alanı deneyimini destekler.
    zh_CN: 免费的开源 3D 创作工具集。
    zh_TW: 免費的開源 3D 創作工具集。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/blender-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/blender-logo.png
  title:
    en_US: Blender (LinuxServer.io)
    ca_ES: Blender (LinuxServer.io)
    cs_CZ: Blender (LinuxServer.io)
    da_DK: Blender (LinuxServer.io)
    de_DE: Blender (LinuxServer.io)
    el_GR: Blender (LinuxServer.io)
    en_GB: Blender (LinuxServer.io)
    es_ES: Blender (LinuxServer.io)
    fr_FR: Blender (LinuxServer.io)
    ga_IE: Blender (LinuxServer.io)
    hr_HR: Blender (LinuxServer.io)
    hu_HU: Blender (LinuxServer.io)
    it_IT: Blender (LinuxServer.io)
    ja_JP: Blender (LinuxServer.io)
    ko_KR: Blender (LinuxServer.io)
    ml_IN: Blender (LinuxServer.io)
    nb_NO: Blender (LinuxServer.io)
    nl_NL: Blender (LinuxServer.io)
    pl_PL: Blender (LinuxServer.io)
    pt_BR: Blender (LinuxServer.io)
    ro_RO: Blender (LinuxServer.io)
    ru_RU: Blender (LinuxServer.io)
    sk_SK: Blender (LinuxServer.io)
    sv_SE: Blender (LinuxServer.io)
    tr_TR: Blender (LinuxServer.io)
    zh_CN: Blender（LinuxServer.io）
    zh_TW: Blender（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverblender
  port_map: '3000'
  version: 5.2.2
