name: linuxserver-duckdns
services:
  app:
    image: linuxserver/duckdns:version-73f1bc7d@sha256:9daa778abcb2c96d15e9de1aed697f9a8175109d167d16c5f99be675811cb103
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SUBDOMAINS: ''
      TOKEN: ''
      UPDATE_IP: ''
      LOG_FILE: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/duckdns/config
        target: /config
      - type: bind
        source: /DATA/AppData/duckdns/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverduckdns/assets/icon.png
  title:
    en_US: Duckdns (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverduckdns
  port_map: '80'
  version: version-73f1bc7d
