name: linuxserver-hedgedoc
services:
  app:
    image: linuxserver/hedgedoc:1.12.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_HOST: ''
      DB_PORT: ''
      DB_USER: ''
      DB_PASS: ''
      DB_NAME: ''
      CMD_DOMAIN: ''
      CMD_URL_ADDPORT: ''
      CMD_PROTOCOL_USESSL: ''
      CMD_PORT: ''
      CMD_ALLOW_ORIGIN: ''
      CMD_DB_DIALECT: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/hedgedoc/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverhedgedoc/assets/icon.png
  title:
    en_US: Hedgedoc (LinuxServer.io)
    ca_ES: Hedgedoc (LinuxServer.io)
    cs_CZ: Hedgedoc (LinuxServer.io)
    da_DK: Hedgedoc (LinuxServer.io)
    de_DE: Hedgedoc (LinuxServer.io)
    el_GR: Hedgedoc (LinuxServer.io)
    en_GB: Hedgedoc (LinuxServer.io)
    es_ES: Hedgedoc (LinuxServer.io)
    fr_FR: Hedgedoc (LinuxServer.io)
    ga_IE: Hedgedoc (LinuxServer.io)
    hr_HR: Hedgedoc (LinuxServer.io)
    hu_HU: Hedgedoc (LinuxServer.io)
    it_IT: Hedgedoc (LinuxServer.io)
    ja_JP: Hedgedoc (LinuxServer.io)
    ko_KR: Hedgedoc (LinuxServer.io)
    ml_IN: Hedgedoc (LinuxServer.io)
    nb_NO: Hedgedoc (LinuxServer.io)
    nl_NL: Hedgedoc (LinuxServer.io)
    pl_PL: Hedgedoc (LinuxServer.io)
    pt_BR: Hedgedoc (LinuxServer.io)
    ro_RO: Hedgedoc (LinuxServer.io)
    ru_RU: Hedgedoc (LinuxServer.io)
    sk_SK: Hedgedoc (LinuxServer.io)
    sv_SE: Hedgedoc (LinuxServer.io)
    tr_TR: Hedgedoc (LinuxServer.io)
    zh_CN: Hedgedoc（LinuxServer.io）
    zh_TW: Hedgedoc（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverhedgedoc
  port_map: '3000'
  version: 1.12.0
