name: linuxserver-jenkins-builder
services:
  app:
    image: linuxserver/jenkins-builder:version-4f81ddbe@sha256:513af1de5573bd744ec30da6a7c3ccf79b04ae748d137f11cfc3331061d06637
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/jenkins-builder/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverjenkinsbuilder/assets/icon.svg
  title:
    en_US: Jenkins builder
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserverjenkinsbuilder
  version: version-4f81ddbe
