name: linuxserver-jenkins-builder
services:
  app:
    image: linuxserver/jenkins-builder:version-4f81ddbe
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/jenkins-builder/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverjenkinsbuilder/assets/icon.svg
  title:
    en_US: Jenkins builder
    zh_CN: Jenkins builder
    ca_ES: Jenkins builder
    cs_CZ: Jenkins builder
    da_DK: Jenkins builder
    de_DE: Jenkins builder
    el_GR: Jenkins builder
    en_GB: Jenkins builder
    es_ES: Jenkins builder
    fr_FR: Jenkins builder
    ga_IE: Jenkins builder
    hr_HR: Jenkins builder
    hu_HU: Jenkins builder
    it_IT: Jenkins builder
    ja_JP: Jenkins builder
    ko_KR: Jenkins builder
    ml_IN: Jenkins builder
    nb_NO: Jenkins builder
    nl_NL: Jenkins builder
    pl_PL: Jenkins builder
    pt_BR: Jenkins builder
    ro_RO: Jenkins builder
    ru_RU: Jenkins builder
    sk_SK: Jenkins builder
    sv_SE: Jenkins builder
    tr_TR: Jenkins builder
    zh_TW: Jenkins builder
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserverjenkinsbuilder
  version: version-4f81ddbe
