name: linuxserver-darktable
services:
  app:
    image: linuxserver/darktable:25.6.1@sha256:b127be6fe936cb28ad8b32ac3da3bc24ac39489b60556dcb2c4be5a0813cdb44
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/darktable/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverdarktable/assets/icon.png
  title:
    en_US: Darktable (LinuxServer.io)
    ca_ES: Darktable (LinuxServer.io)
    cs_CZ: Darktable (LinuxServer.io)
    da_DK: Darktable (LinuxServer.io)
    de_DE: Darktable (LinuxServer.io)
    el_GR: Darktable (LinuxServer.io)
    en_GB: Darktable (LinuxServer.io)
    es_ES: Darktable (LinuxServer.io)
    fr_FR: Darktable (LinuxServer.io)
    ga_IE: Darktable (LinuxServer.io)
    hr_HR: Darktable (LinuxServer.io)
    hu_HU: Darktable (LinuxServer.io)
    it_IT: Darktable (LinuxServer.io)
    ja_JP: Darktable (LinuxServer.io)
    ko_KR: Darktable (LinuxServer.io)
    ml_IN: Darktable (LinuxServer.io)
    nb_NO: Darktable (LinuxServer.io)
    nl_NL: Darktable (LinuxServer.io)
    pl_PL: Darktable (LinuxServer.io)
    pt_BR: Darktable (LinuxServer.io)
    ro_RO: Darktable (LinuxServer.io)
    ru_RU: Darktable (LinuxServer.io)
    sk_SK: Darktable (LinuxServer.io)
    sv_SE: Darktable (LinuxServer.io)
    tr_TR: Darktable (LinuxServer.io)
    zh_CN: Darktable（LinuxServer.io）
    zh_TW: Darktable（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverdarktable
  port_map: '3000'
  version: 25.6.1
