name: linuxserver-ombi
services:
  app:
    image: linuxserver/ombi:4.53.10@sha256:c994b6700575d852faed07729f1302a2250181feb91f775bc7b34a8388cd545d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
    ports:
      - target: 3579
        published: 3579
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ombi/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverombi/assets/icon.png
  title:
    en_US: Ombi (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverombi
  port_map: '3579'
  version: 4.53.10
