name: linuxserver-ombi
services:
  app:
    image: linuxserver/ombi:4.53.10@sha256:c994b6700575d852faed07729f1302a2250181feb91f775bc7b34a8388cd545d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
    ports:
      - target: 3579
        published: 3579
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ombi/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverombi/assets/icon.png
  title:
    en_US: Ombi (LinuxServer.io)
    ca_ES: Ombi (LinuxServer.io)
    cs_CZ: Ombi (LinuxServer.io)
    da_DK: Ombi (LinuxServer.io)
    de_DE: Ombi (LinuxServer.io)
    el_GR: Ombi (LinuxServer.io)
    en_GB: Ombi (LinuxServer.io)
    es_ES: Ombi (LinuxServer.io)
    fr_FR: Ombi (LinuxServer.io)
    ga_IE: Ombi (LinuxServer.io)
    hr_HR: Ombi (LinuxServer.io)
    hu_HU: Ombi (LinuxServer.io)
    it_IT: Ombi (LinuxServer.io)
    ja_JP: Ombi (LinuxServer.io)
    ko_KR: Ombi (LinuxServer.io)
    ml_IN: Ombi (LinuxServer.io)
    nb_NO: Ombi (LinuxServer.io)
    nl_NL: Ombi (LinuxServer.io)
    pl_PL: Ombi (LinuxServer.io)
    pt_BR: Ombi (LinuxServer.io)
    ro_RO: Ombi (LinuxServer.io)
    ru_RU: Ombi (LinuxServer.io)
    sk_SK: Ombi (LinuxServer.io)
    sv_SE: Ombi (LinuxServer.io)
    tr_TR: Ombi (LinuxServer.io)
    zh_CN: Ombi（LinuxServer.io）
    zh_TW: Ombi（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverombi
  port_map: '3579'
  version: 4.53.10
