name: linuxserver-openssh-server
services:
  app:
    image: linuxserver/openssh-server:version-10.3_p1-r1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PUBLIC_KEY: ''
      PUBLIC_KEY_FILE: ''
      PUBLIC_KEY_DIR: ''
      PUBLIC_KEY_URL: ''
      SUDO_ACCESS: ''
      PASSWORD_ACCESS: ''
      USER_PASSWORD: ''
      USER_PASSWORD_FILE: ''
      USER_NAME: ''
      LOG_STDOUT: ''
    ports:
      - target: 2222
        published: 2222
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/openssh-server/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveropensshserver/assets/icon.png
  title:
    en_US: Openssh server (LinuxServer.io)
    ca_ES: Openssh server (LinuxServer.io)
    cs_CZ: Openssh server (LinuxServer.io)
    da_DK: Openssh server (LinuxServer.io)
    de_DE: Openssh server (LinuxServer.io)
    el_GR: Openssh server (LinuxServer.io)
    en_GB: Openssh server (LinuxServer.io)
    es_ES: Openssh server (LinuxServer.io)
    fr_FR: Openssh server (LinuxServer.io)
    ga_IE: Openssh server (LinuxServer.io)
    hr_HR: Openssh server (LinuxServer.io)
    hu_HU: Openssh server (LinuxServer.io)
    it_IT: Openssh server (LinuxServer.io)
    ja_JP: Openssh server (LinuxServer.io)
    ko_KR: Openssh server (LinuxServer.io)
    ml_IN: Openssh server (LinuxServer.io)
    nb_NO: Openssh server (LinuxServer.io)
    nl_NL: Openssh server (LinuxServer.io)
    pl_PL: Openssh server (LinuxServer.io)
    pt_BR: Openssh server (LinuxServer.io)
    ro_RO: Openssh server (LinuxServer.io)
    ru_RU: Openssh server (LinuxServer.io)
    sk_SK: Openssh server (LinuxServer.io)
    sv_SE: Openssh server (LinuxServer.io)
    tr_TR: Openssh server (LinuxServer.io)
    zh_CN: Openssh server（LinuxServer.io）
    zh_TW: Openssh server（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserveropensshserver
  port_map: '2222'
  version: version-10.3_p1-r1
