name: linuxserver-flycast
services:
  app:
    image: linuxserver/flycast:2.7.20260913
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/flycast/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverflycast/assets/icon.png
  title:
    en_US: Flycast (LinuxServer.io)
    ca_ES: Flycast (LinuxServer.io)
    cs_CZ: Flycast (LinuxServer.io)
    da_DK: Flycast (LinuxServer.io)
    de_DE: Flycast (LinuxServer.io)
    el_GR: Flycast (LinuxServer.io)
    en_GB: Flycast (LinuxServer.io)
    es_ES: Flycast (LinuxServer.io)
    fr_FR: Flycast (LinuxServer.io)
    ga_IE: Flycast (LinuxServer.io)
    hr_HR: Flycast (LinuxServer.io)
    hu_HU: Flycast (LinuxServer.io)
    it_IT: Flycast (LinuxServer.io)
    ja_JP: Flycast (LinuxServer.io)
    ko_KR: Flycast (LinuxServer.io)
    ml_IN: Flycast (LinuxServer.io)
    nb_NO: Flycast (LinuxServer.io)
    nl_NL: Flycast (LinuxServer.io)
    pl_PL: Flycast (LinuxServer.io)
    pt_BR: Flycast (LinuxServer.io)
    ro_RO: Flycast (LinuxServer.io)
    ru_RU: Flycast (LinuxServer.io)
    sk_SK: Flycast (LinuxServer.io)
    sv_SE: Flycast (LinuxServer.io)
    tr_TR: Flycast (LinuxServer.io)
    zh_CN: Flycast（LinuxServer.io）
    zh_TW: Flycast（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverflycast
  port_map: '3000'
  version: 2.7.20260913
