name: linuxserver-gimp
services:
  app:
    image: linuxserver/gimp:version-284e0208@sha256:bb205a6fe8db8395842e16053eebe8950ac8a177dc5e242e2dbb18968d6c31d7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gimp/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservergimp/assets/icon.png
  title:
    en_US: Gimp (LinuxServer.io)
    ca_ES: Gimp (LinuxServer.io)
    cs_CZ: Gimp (LinuxServer.io)
    da_DK: Gimp (LinuxServer.io)
    de_DE: Gimp (LinuxServer.io)
    el_GR: Gimp (LinuxServer.io)
    en_GB: Gimp (LinuxServer.io)
    es_ES: Gimp (LinuxServer.io)
    fr_FR: Gimp (LinuxServer.io)
    ga_IE: Gimp (LinuxServer.io)
    hr_HR: Gimp (LinuxServer.io)
    hu_HU: Gimp (LinuxServer.io)
    it_IT: Gimp (LinuxServer.io)
    ja_JP: Gimp (LinuxServer.io)
    ko_KR: Gimp (LinuxServer.io)
    ml_IN: Gimp (LinuxServer.io)
    nb_NO: Gimp (LinuxServer.io)
    nl_NL: Gimp (LinuxServer.io)
    pl_PL: Gimp (LinuxServer.io)
    pt_BR: Gimp (LinuxServer.io)
    ro_RO: Gimp (LinuxServer.io)
    ru_RU: Gimp (LinuxServer.io)
    sk_SK: Gimp (LinuxServer.io)
    sv_SE: Gimp (LinuxServer.io)
    tr_TR: Gimp (LinuxServer.io)
    zh_CN: Gimp（LinuxServer.io）
    zh_TW: Gimp（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservergimp
  port_map: '3000'
  version: version-284e0208
