name: linuxserver-lychee
services:
  app:
    image: linuxserver/lychee:7.8.4@sha256:f8647bc6eafc61bfa990af08c109b7202673ed9176a34fc64681b61193800e61
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_CONNECTION: ''
      DB_HOST: ''
      DB_PORT: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_DATABASE: ''
      APP_NAME: ''
      APP_URL: ''
      TRUSTED_PROXIES: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lychee/config
        target: /config
      - type: bind
        source: /DATA/AppData/lychee/pictures
        target: /pictures
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverlychee/assets/icon.png
  title:
    en_US: Lychee (LinuxServer.io)
    ca_ES: Lychee (LinuxServer.io)
    cs_CZ: Lychee (LinuxServer.io)
    da_DK: Lychee (LinuxServer.io)
    de_DE: Lychee (LinuxServer.io)
    el_GR: Lychee (LinuxServer.io)
    en_GB: Lychee (LinuxServer.io)
    es_ES: Lychee (LinuxServer.io)
    fr_FR: Lychee (LinuxServer.io)
    ga_IE: Lychee (LinuxServer.io)
    hr_HR: Lychee (LinuxServer.io)
    hu_HU: Lychee (LinuxServer.io)
    it_IT: Lychee (LinuxServer.io)
    ja_JP: Lychee (LinuxServer.io)
    ko_KR: Lychee (LinuxServer.io)
    ml_IN: Lychee (LinuxServer.io)
    nb_NO: Lychee (LinuxServer.io)
    nl_NL: Lychee (LinuxServer.io)
    pl_PL: Lychee (LinuxServer.io)
    pt_BR: Lychee (LinuxServer.io)
    ro_RO: Lychee (LinuxServer.io)
    ru_RU: Lychee (LinuxServer.io)
    sk_SK: Lychee (LinuxServer.io)
    sv_SE: Lychee (LinuxServer.io)
    tr_TR: Lychee (LinuxServer.io)
    zh_CN: Lychee（LinuxServer.io）
    zh_TW: Lychee（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverlychee
  port_map: '80'
  version: 7.8.4
