name: linuxserver-adguardhome-sync
services:
  app:
    image: linuxserver/adguardhome-sync:0.9.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONFIGFILE: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: CONFIGFILE
          description:
            en_US: Set a custom config file. [OPTIONAL]
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/adguardhome-sync/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Adguardhome-sync is a tool to synchronize AdGuardHome config to replica instances.
    zh_CN: Adguardhome-sync 是一个将 AdGuard Home 配置同步到副本实例的工具。
  tagline:
    en_US: A tool to synchronize AdGuardHome config to replica instances.
    zh_CN: 在多个实例之间同步 AdGuard Home 配置。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/adguardhomesync-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/adguardhomesync-icon.png
  title:
    en_US: Adguardhome sync (LinuxServer.io)
    zh_CN: Adguardhome sync（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserveradguardhomesync
  port_map: '8080'
  version: 0.9.3
