name: linuxserver-xvfb
services:
  app:
    image: linuxserver/xvfb:kali-version-9d327c0f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /srv/lsio/xvfb/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: This container needs special attention. Please check https://hub.docker.com/r/linuxserver/xvfb for details.
  tagline:
    en_us: This container needs special attention. Please check https://hub. Docker. Com/r/linuxserver/xvfb for details.
  developer: LinuxServer.io
  author: WisdomSky
  icon: ''
  thumbnail: ''
  title:
    en_us: Xvfb
  category: LinuxServer.io
  port_map: '80'
