name: linuxserver-xvfb
services:
  app:
    image: linuxserver/xvfb:debiantrixie-version-9d327c0f@sha256:2a3668f29ee8ffdadac0e54731cdc0d6a5e46b309c6738824fbcee9fed3ddebf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /srv/lsio/xvfb/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverxvfb/assets/icon.svg
  title:
    en_US: Xvfb
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserverxvfb
  version: debiantrixie-version-9d327c0f
