name: linuxserver-librespeed
services:
  app:
    image: linuxserver/librespeed:6.3.0@sha256:c39fd9b8279fcc7be3d280aa4bf8e10c889982bbe83049cd0c5283db8e49fc57
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
      CUSTOM_RESULTS: ''
      DB_TYPE: ''
      DB_NAME: ''
      DB_HOSTNAME: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_PORT: ''
      IPINFO_APIKEY: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/librespeed/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverlibrespeed/assets/icon.png
  title:
    en_US: Librespeed (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverlibrespeed
  port_map: '80'
  version: 6.3.0
