name: linuxserver-nginx
services:
  app:
    image: linuxserver/nginx:1.30.4@sha256:0e58414a4dc132084f9071c27e40e6e656563a84194fe29069e0452163450c49
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      NGINX_AUTORELOAD: ''
      NGINX_AUTORELOAD_WATCHLIST: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nginx/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservernginx/assets/icon.png
  title:
    en_US: Nginx (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxservernginx
  port_map: '80'
  version: 1.30.4
