name: linuxserver-unrar
services:
  app:
    image: linuxserver/unrar:7.0.9@sha256:2fcc57717766e4fa7db4b19d5d34462f991a34b187c72c245d7114f4d8430837
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/unrar/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverunrar/assets/icon.svg
  title:
    en_US: Unrar
    zh_CN: Unrar
    ca_ES: Unrar
    cs_CZ: Unrar
    da_DK: Unrar
    de_DE: Unrar
    el_GR: Unrar
    en_GB: Unrar
    es_ES: Unrar
    fr_FR: Unrar
    ga_IE: Unrar
    hr_HR: Unrar
    hu_HU: Unrar
    it_IT: Unrar
    ja_JP: Unrar
    ko_KR: Unrar
    ml_IN: Unrar
    nb_NO: Unrar
    nl_NL: Unrar
    pl_PL: Unrar
    pt_BR: Unrar
    ro_RO: Unrar
    ru_RU: Unrar
    sk_SK: Unrar
    sv_SE: Unrar
    tr_TR: Unrar
    zh_TW: Unrar
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserverunrar
  version: 7.0.9
