name: linuxserver-unrar
services:
  app:
    image: linuxserver/unrar:7.0.9@sha256:260d0c7493f287ce31903a06d0b1e77fe0f39fb21f9af70c3744e119ae2840c6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/unrar/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverunrar/assets/icon.svg
  title:
    en_US: Unrar
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserverunrar
  version: 7.0.9
