name: linuxserver-raneto
services:
  app:
    image: linuxserver/raneto:0.18.1@sha256:33db4b0b1b761d010aeda04e06795a8615bc3ae9773a746321bb6051acdb3c58
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/raneto/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverraneto/assets/icon.png
  title:
    en_US: Raneto (LinuxServer.io)
    ca_ES: Raneto (LinuxServer.io)
    cs_CZ: Raneto (LinuxServer.io)
    da_DK: Raneto (LinuxServer.io)
    de_DE: Raneto (LinuxServer.io)
    el_GR: Raneto (LinuxServer.io)
    en_GB: Raneto (LinuxServer.io)
    es_ES: Raneto (LinuxServer.io)
    fr_FR: Raneto (LinuxServer.io)
    ga_IE: Raneto (LinuxServer.io)
    hr_HR: Raneto (LinuxServer.io)
    hu_HU: Raneto (LinuxServer.io)
    it_IT: Raneto (LinuxServer.io)
    ja_JP: Raneto (LinuxServer.io)
    ko_KR: Raneto (LinuxServer.io)
    ml_IN: Raneto (LinuxServer.io)
    nb_NO: Raneto (LinuxServer.io)
    nl_NL: Raneto (LinuxServer.io)
    pl_PL: Raneto (LinuxServer.io)
    pt_BR: Raneto (LinuxServer.io)
    ro_RO: Raneto (LinuxServer.io)
    ru_RU: Raneto (LinuxServer.io)
    sk_SK: Raneto (LinuxServer.io)
    sv_SE: Raneto (LinuxServer.io)
    tr_TR: Raneto (LinuxServer.io)
    zh_CN: Raneto（LinuxServer.io）
    zh_TW: Raneto（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverraneto
  port_map: '3000'
  version: 0.18.1
