name: linuxserver-vscode
services:
  app:
    image: linuxserver/vscode:1.137.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vscode/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservervscode/assets/icon.png
  title:
    en_US: Vscode (LinuxServer.io)
    ca_ES: Vscode (LinuxServer.io)
    cs_CZ: Vscode (LinuxServer.io)
    da_DK: Vscode (LinuxServer.io)
    de_DE: Vscode (LinuxServer.io)
    el_GR: Vscode (LinuxServer.io)
    en_GB: Vscode (LinuxServer.io)
    es_ES: Vscode (LinuxServer.io)
    fr_FR: Vscode (LinuxServer.io)
    ga_IE: Vscode (LinuxServer.io)
    hr_HR: Vscode (LinuxServer.io)
    hu_HU: Vscode (LinuxServer.io)
    it_IT: Vscode (LinuxServer.io)
    ja_JP: Vscode (LinuxServer.io)
    ko_KR: Vscode (LinuxServer.io)
    ml_IN: Vscode (LinuxServer.io)
    nb_NO: Vscode (LinuxServer.io)
    nl_NL: Vscode (LinuxServer.io)
    pl_PL: Vscode (LinuxServer.io)
    pt_BR: Vscode (LinuxServer.io)
    ro_RO: Vscode (LinuxServer.io)
    ru_RU: Vscode (LinuxServer.io)
    sk_SK: Vscode (LinuxServer.io)
    sv_SE: Vscode (LinuxServer.io)
    tr_TR: Vscode (LinuxServer.io)
    zh_CN: Vscode（LinuxServer.io）
    zh_TW: Vscode（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservervscode
  port_map: '3000'
  version: 1.137.0
