name: linuxserver-jenkins-builder
services:
  app:
    image: linuxserver/jenkins-builder:version-4f81ddbe
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/jenkins-builder/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: This container needs special attention. Please check https://hub.docker.com/r/linuxserver/jenkins-builder for details.
    zh_CN: 此容器需要特别注意。使用前请阅读相关说明：https://hub.docker.com/r/linuxserver/jenkins-builder
  tagline:
    en_US: 'This container needs special attention. Please check https://hub. Docker. Com/r/linuxserver/jenkins-builder for details. '
    zh_CN: 此容器需要特殊配置，请先阅读使用说明。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/WisdomSky/CasaOS-LinuxServer-AppStore/main/default-icon.svg
  thumbnail: ''
  title:
    en_US: Jenkins builder
    zh_CN: Jenkins builder
  category: Others
  port_map: '80'
  id: wisdomsky.linuxserver.linuxserverjenkinsbuilder
  version: version-4f81ddbe
