name: linuxserver-vscodium-web
services:
  app:
    image: linuxserver/vscodium-web:1.135.06055
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONNECTION_TOKEN: ''
      CONNECTION_TOKEN_FILE: ''
      SUDO_PASSWORD: ''
      SUDO_PASSWORD_HASH: ''
      CODE_ARGS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: CONNECTION_TOKEN
          description:
            en_US: Optional security token for accessing the Web UI (ie. supersecrettoken). [OPTIONAL]
        - container: CONNECTION_TOKEN_FILE
          description:
            en_US: Optional path to a file inside the container that contains the security token for accessing the Web UI (ie. /path/to/file). Overrides CONNECTION_TOKEN. [OPTIONAL]
        - container: SUDO_PASSWORD
          description:
            en_US: If this optional variable is set, user will have sudo access in the vscodium-web terminal with the specified password. [OPTIONAL]
        - container: SUDO_PASSWORD_HASH
          description:
            en_US: Optionally set sudo password via hash (takes priority over SUDO_PASSWORD var). Format is $type$salt$hashed. [OPTIONAL]
        - container: CODE_ARGS
          description:
            en_US: Optionally add cli parameters to vscodium binary. [OPTIONAL]
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vscodium-web/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Vscodium-web is a community-driven, freely-licensed binary distribution of the remote host web component of Microsoft's editor VS Code.
    zh_CN: Vscodium-web 是由社区推动、采用自由许可证的微软 VS Code 远程主机网页组件二进制发行版。
  tagline:
    en_US: A community-driven, freely-licensed binary distribution of the remote host web component of Microsoft's editor VS Code.
    zh_CN: 社区维护的 VS Code 远程网页组件。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/vscodium-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/vscodium-icon.png
  title:
    en_US: Vscodium web (LinuxServer.io)
    zh_CN: Vscodium web（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxservervscodiumweb
  port_map: '8000'
  version: 1.135.06055
