name: linuxserver-series-troxide
services:
  app:
    image: linuxserver/series-troxide:0.5.1@sha256:74d3abff0d0ddc3c84b15f563271701bafd58b9aa3a62947d5e65417706d9b59
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/series-troxide/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverseriestroxide/assets/icon.png
  title:
    en_US: Series troxide
    zh_CN: Series troxide
    ca_ES: Series troxide
    cs_CZ: Series troxide
    da_DK: Series troxide
    de_DE: Series troxide
    el_GR: Series troxide
    en_GB: Series troxide
    es_ES: Series troxide
    fr_FR: Series troxide
    ga_IE: Series troxide
    hr_HR: Series troxide
    hu_HU: Series troxide
    it_IT: Series troxide
    ja_JP: Series troxide
    ko_KR: Series troxide
    ml_IN: Series troxide
    nb_NO: Series troxide
    nl_NL: Series troxide
    pl_PL: Series troxide
    pt_BR: Series troxide
    ro_RO: Series troxide
    ru_RU: Series troxide
    sk_SK: Series troxide
    sv_SE: Series troxide
    tr_TR: Series troxide
    zh_TW: Series troxide
  id: wisdomsky.linuxserver.linuxserverseriestroxide
  version: 0.5.1
