name: linuxserver-beets
services:
  app:
    image: linuxserver/beets:2.14.1@sha256:4d9cef3fccd84bee86ef3fdae288d0ecd594815a46e269f9dd40f0ab63f4ec37
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8337
        published: 8337
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/beets/config
        target: /config
      - type: bind
        source: /DATA/AppData/beets/music
        target: /music
      - type: bind
        source: /DATA/AppData/beets/downloads
        target: /downloads
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverbeets/assets/icon.png
  title:
    en_US: Beets (LinuxServer.io)
    ca_ES: Beets (LinuxServer.io)
    cs_CZ: Beets (LinuxServer.io)
    da_DK: Beets (LinuxServer.io)
    de_DE: Beets (LinuxServer.io)
    el_GR: Beets (LinuxServer.io)
    en_GB: Beets (LinuxServer.io)
    es_ES: Beets (LinuxServer.io)
    fr_FR: Beets (LinuxServer.io)
    ga_IE: Beets (LinuxServer.io)
    hr_HR: Beets (LinuxServer.io)
    hu_HU: Beets (LinuxServer.io)
    it_IT: Beets (LinuxServer.io)
    ja_JP: Beets (LinuxServer.io)
    ko_KR: Beets (LinuxServer.io)
    ml_IN: Beets (LinuxServer.io)
    nb_NO: Beets (LinuxServer.io)
    nl_NL: Beets (LinuxServer.io)
    pl_PL: Beets (LinuxServer.io)
    pt_BR: Beets (LinuxServer.io)
    ro_RO: Beets (LinuxServer.io)
    ru_RU: Beets (LinuxServer.io)
    sk_SK: Beets (LinuxServer.io)
    sv_SE: Beets (LinuxServer.io)
    tr_TR: Beets (LinuxServer.io)
    zh_CN: Beets（LinuxServer.io）
    zh_TW: Beets（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverbeets
  port_map: '8337'
  version: 2.14.1
