name: linuxserver-lollypop
services:
  app:
    image: linuxserver/lollypop:1.4.45@sha256:d719cf9d3f019e3671845a34f1c1edb307cbd2c40d5e4ba08c8a09198ccb5f34
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lollypop/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverlollypop/assets/icon.png
  title:
    en_US: Lollypop (LinuxServer.io)
    ca_ES: Lollypop (LinuxServer.io)
    cs_CZ: Lollypop (LinuxServer.io)
    da_DK: Lollypop (LinuxServer.io)
    de_DE: Lollypop (LinuxServer.io)
    el_GR: Lollypop (LinuxServer.io)
    en_GB: Lollypop (LinuxServer.io)
    es_ES: Lollypop (LinuxServer.io)
    fr_FR: Lollypop (LinuxServer.io)
    ga_IE: Lollypop (LinuxServer.io)
    hr_HR: Lollypop (LinuxServer.io)
    hu_HU: Lollypop (LinuxServer.io)
    it_IT: Lollypop (LinuxServer.io)
    ja_JP: Lollypop (LinuxServer.io)
    ko_KR: Lollypop (LinuxServer.io)
    ml_IN: Lollypop (LinuxServer.io)
    nb_NO: Lollypop (LinuxServer.io)
    nl_NL: Lollypop (LinuxServer.io)
    pl_PL: Lollypop (LinuxServer.io)
    pt_BR: Lollypop (LinuxServer.io)
    ro_RO: Lollypop (LinuxServer.io)
    ru_RU: Lollypop (LinuxServer.io)
    sk_SK: Lollypop (LinuxServer.io)
    sv_SE: Lollypop (LinuxServer.io)
    tr_TR: Lollypop (LinuxServer.io)
    zh_CN: Lollypop（LinuxServer.io）
    zh_TW: Lollypop（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverlollypop
  port_map: '3000'
  version: 1.4.45
