name: linuxserver-shadps4
services:
  app:
    image: linuxserver/shadps4:version-shadPS4QtLauncher-2026-09-12-864dc30bc5372d7ad95ef609188942ecd77bf6f4@sha256:833518084c397ceb99e8d9334d513852b65899c65e715317058555c72c2f18e6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/shadps4/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservershadps4/assets/icon.png
  title:
    en_US: Shadps4 (LinuxServer.io)
    ca_ES: Shadps4 (LinuxServer.io)
    cs_CZ: Shadps4 (LinuxServer.io)
    da_DK: Shadps4 (LinuxServer.io)
    de_DE: Shadps4 (LinuxServer.io)
    el_GR: Shadps4 (LinuxServer.io)
    en_GB: Shadps4 (LinuxServer.io)
    es_ES: Shadps4 (LinuxServer.io)
    fr_FR: Shadps4 (LinuxServer.io)
    ga_IE: Shadps4 (LinuxServer.io)
    hr_HR: Shadps4 (LinuxServer.io)
    hu_HU: Shadps4 (LinuxServer.io)
    it_IT: Shadps4 (LinuxServer.io)
    ja_JP: Shadps4 (LinuxServer.io)
    ko_KR: Shadps4 (LinuxServer.io)
    ml_IN: Shadps4 (LinuxServer.io)
    nb_NO: Shadps4 (LinuxServer.io)
    nl_NL: Shadps4 (LinuxServer.io)
    pl_PL: Shadps4 (LinuxServer.io)
    pt_BR: Shadps4 (LinuxServer.io)
    ro_RO: Shadps4 (LinuxServer.io)
    ru_RU: Shadps4 (LinuxServer.io)
    sk_SK: Shadps4 (LinuxServer.io)
    sv_SE: Shadps4 (LinuxServer.io)
    tr_TR: Shadps4 (LinuxServer.io)
    zh_CN: Shadps4（LinuxServer.io）
    zh_TW: Shadps4（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservershadps4
  port_map: '3000'
  version: version-shadPS4QtLauncher-2026-09-12-864dc30bc5372d7ad95ef609188942ecd77bf6f4
