name: linuxserver-tvheadend
services:
  app:
    image: linuxserver/tvheadend:version-5ce3ff63
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RUN_OPTS: ''
    ports:
      - target: 9981
        published: 9981
        protocol: tcp
      - target: 9982
        published: 9982
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/tvheadend/config
        target: /config
      - type: bind
        source: /DATA/AppData/tvheadend/recordings
        target: /recordings
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservertvheadend/assets/icon.png
  title:
    en_US: Tvheadend (LinuxServer.io)
    ca_ES: Tvheadend (LinuxServer.io)
    cs_CZ: Tvheadend (LinuxServer.io)
    da_DK: Tvheadend (LinuxServer.io)
    de_DE: Tvheadend (LinuxServer.io)
    el_GR: Tvheadend (LinuxServer.io)
    en_GB: Tvheadend (LinuxServer.io)
    es_ES: Tvheadend (LinuxServer.io)
    fr_FR: Tvheadend (LinuxServer.io)
    ga_IE: Tvheadend (LinuxServer.io)
    hr_HR: Tvheadend (LinuxServer.io)
    hu_HU: Tvheadend (LinuxServer.io)
    it_IT: Tvheadend (LinuxServer.io)
    ja_JP: Tvheadend (LinuxServer.io)
    ko_KR: Tvheadend (LinuxServer.io)
    ml_IN: Tvheadend (LinuxServer.io)
    nb_NO: Tvheadend (LinuxServer.io)
    nl_NL: Tvheadend (LinuxServer.io)
    pl_PL: Tvheadend (LinuxServer.io)
    pt_BR: Tvheadend (LinuxServer.io)
    ro_RO: Tvheadend (LinuxServer.io)
    ru_RU: Tvheadend (LinuxServer.io)
    sk_SK: Tvheadend (LinuxServer.io)
    sv_SE: Tvheadend (LinuxServer.io)
    tr_TR: Tvheadend (LinuxServer.io)
    zh_CN: Tvheadend（LinuxServer.io）
    zh_TW: Tvheadend（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservertvheadend
  version: version-5ce3ff63
