name: linuxserver-xbackbone
services:
  app:
    image: linuxserver/xbackbone:3.8.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/xbackbone/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Xbackbone is a simple, self-hosted, lightweight PHP file manager that support the instant sharing tool ShareX and *NIX systems. It supports uploading and displaying images, GIF, video, code, formatted text, and file downloading and uploading. Also have a web UI with multi user management, past uploads history and search support.
    ca_ES: Xbackbone és un gestor de fitxers PHP senzill, autoallotjat i lleuger que admet l'eina de compartició instantània ShareX i els sistemes *NIX. Admet la càrrega i visualització d'imatges, GIF, vídeo, codi, text formatat i la descàrrega i càrrega de fitxers. També té una interfície d'usuari web amb gestió multiusuari, historial de càrregues anteriors i compatibilitat amb la cerca.
    cs_CZ: Xbackbone je jednoduchý, samostatně hostovaný a lehký správce souborů v PHP, který podporuje nástroj pro okamžité sdílení ShareX a systémy *NIX. Podporuje nahrávání a zobrazování obrázků, GIFů, videa, kódu, formátovaného textu a stahování a nahrávání souborů. Má také webové uživatelské rozhraní se správou pro více uživatelů, historií předchozích nahrávání a podporou vyhledávání.
    da_DK: Xbackbone er en simpel, selvhostet og let PHP-filhåndtering, der understøtter delingsværktøjerne ShareX og *NIX. Den understøtter upload og visning af billeder, GIF'er, videoer, kode, formateret tekst samt download og upload af filer. Den har også en webgrænseflade med administration af flere brugere, historik over tidligere uploads og søgeunderstøttelse.
    de_DE: Xbackbone ist ein einfacher, selbstgehosteter und ressourcenschonender PHP-Dateimanager, der das Instant-Sharing-Tool ShareX und *NIX-Systeme unterstützt. Er ermöglicht das Hochladen und Anzeigen von Bildern, GIFs, Videos, Code und formatiertem Text sowie das Herunterladen und Hochladen von Dateien. Zudem bietet er eine Web-Oberfläche mit Mehrbenutzerverwaltung, Upload-Historie und Suchfunktion.
    el_GR: Το Xbackbone είναι ένας απλός, αυτοφιλοξενούμενος, ελαφρύς διαχειριστής αρχείων PHP που υποστηρίζει τα εργαλεία άμεσης κοινής χρήσης ShareX και τα συστήματα *NIX. Υποστηρίζει τη μεταφόρτωση και προβολή εικόνων, GIF, βίντεο, κώδικα, μορφοποιημένου κειμένου και λήψης και μεταφόρτωσης αρχείων. Διαθέτει επίσης ένα περιβάλλον εργασίας χρήστη ιστού με διαχείριση πολλαπλών χρηστών, ιστορικό προηγούμενων μεταφορτώσεων και υποστήριξη αναζήτησης.
    en_GB: Xbackbone is a simple, self-hosted, lightweight Php file manager that support the instant sharing tool Sharex and *Nix systems. It supports uploading and displaying images, Gif, video, code, formatted text, and file downloading and uploading. Also have a web Ui with multi user management, past uploads history and search support.
    es_ES: Xbackbone es un gestor de archivos PHP sencillo, autoalojado y ligero que admite la herramienta de intercambio instantáneo ShareX y sistemas *NIX. Permite subir y visualizar imágenes, GIF, vídeos, código y texto formateado, así como descargar y subir archivos. También cuenta con una interfaz web con gestión multiusuario, historial de subidas y función de búsqueda.
    fr_FR: Xbackbone est un gestionnaire de fichiers PHP simple, auto-hébergé et léger, compatible avec l'outil de partage instantané ShareX et les systèmes *NIX. Il permet d'afficher et de télécharger des images, des GIF, des vidéos, du code, du texte formaté, ainsi que de télécharger et d'envoyer des fichiers. Il dispose également d'une interface web avec gestion multi-utilisateurs, historique des téléchargements et fonction de recherche.
    ga_IE: Is bainisteoir comhad PHP simplí, féinóstáilte, éadrom é Xbackbone a thacaíonn leis an uirlis chomhroinnte meandrach ShareX agus córais *NIX. Tacaíonn sé le híomhánna, GIFanna, físeáin, cód, téacs formáidithe, agus íoslódáil agus uaslódáil comhad a uaslódáil agus a thaispeáint. Tá comhéadan úsáideora gréasáin aige freisin le bainistíocht ilúsáideoirí, stair uaslódálacha roimhe seo agus tacaíocht chuardaigh.
    hr_HR: Xbackbone je jednostavan, samostalno hostan, lagan PHP upravitelj datoteka koji podržava alat za trenutno dijeljenje ShareX i *NIX sustave. Podržava prijenos i prikaz slika, GIF-ova, videa, koda, formatiranog teksta te preuzimanje i prijenos datoteka. Također ima web korisničko sučelje s upravljanjem za više korisnika, poviješću prošlih prijenosa i podrškom za pretraživanje.
    hu_HU: Az Xbackbone egy egyszerű, saját tárhelyen futó, könnyű PHP fájlkezelő, amely támogatja a ShareX és a *NIX azonnali megosztó eszközt. Támogatja a képek, GIF-ek, videók, kód, formázott szöveg feltöltését és megjelenítését, valamint a fájlok letöltését és feltöltését. Emellett webes felhasználói felülettel rendelkezik több felhasználó kezelésével, korábbi feltöltési előzményekkel és keresési támogatással.
    it_IT: Xbackbone è un semplice file manager PHP, auto-ospitato e leggero, che supporta lo strumento di condivisione istantanea ShareX e i sistemi *NIX. Consente di caricare e visualizzare immagini, GIF, video, codice, testo formattato, nonché di scaricare e caricare file. Dispone inoltre di un'interfaccia web con gestione multiutente, cronologia dei caricamenti e funzione di ricerca.
    ja_JP: Xbackboneは、ShareXなどのインスタントファイル共有ツールと*NIXシステムをサポートする、シンプルで自己ホスト型の軽量PHPファイルマネージャーです。画像、GIF、動画、コード、書式付きテキストのアップロードと表示、ファイルのダウンロードとアップロードに対応しています。また、マルチユーザー管理、過去のアップロード履歴、検索機能を備えたWeb UIも搭載しています。
    ko_KR: Xbackbone은 ShareX와 같은 인스턴트 공유 도구 및 *NIX 시스템을 지원하는 간단하고 자체 호스팅이 가능한 경량 PHP 파일 관리자입니다. 이미지, GIF, 비디오, 코드, 서식이 지정된 텍스트의 업로드 및 표시를 지원하며, 파일 다운로드 및 업로드 기능도 제공합니다. 또한 다중 사용자 관리, 이전 업로드 내역 및 검색 기능을 지원하는 웹 UI를 갖추고 있습니다.
    ml_IN: Xbackbone എന്നത് ലളിതവും സ്വയം ഹോസ്റ്റ് ചെയ്തതും ഭാരം കുറഞ്ഞതുമായ ഒരു PHP ഫയൽ മാനേജറാണ്, ഇത് തൽക്ഷണ പങ്കിടൽ ഉപകരണമായ ShareX, *NIX സിസ്റ്റങ്ങളെ പിന്തുണയ്ക്കുന്നു. ഇമേജുകൾ, GIF, വീഡിയോ, കോഡ്, ഫോർമാറ്റ് ചെയ്ത ടെക്സ്റ്റ്, ഫയൽ ഡൗൺലോഡ്, അപ്‌ലോഡിംഗ് എന്നിവ അപ്‌ലോഡ് ചെയ്യുന്നതിനും പ്രദർശിപ്പിക്കുന്നതിനും ഇത് പിന്തുണയ്ക്കുന്നു. മൾട്ടി യൂസർ മാനേജ്‌മെന്റ്, മുൻ അപ്‌ലോഡ് ചരിത്രം, തിരയൽ പിന്തുണ എന്നിവയുള്ള ഒരു വെബ് UI കൂടി ഇതിനുണ്ട്.
    nb_NO: Xbackbone er en enkel, selvhostet og lett PHP-filbehandler som støtter delingsverktøyene ShareX og *NIX. Den støtter opplasting og visning av bilder, GIF-er, videoer, kode, formatert tekst og nedlasting og opplasting av filer. Den har også et webgrensesnitt med flerbrukeradministrasjon, tidligere opplastingshistorikk og søkestøtte.
    nl_NL: Xbackbone is een eenvoudige, zelfgehoste, lichtgewicht PHP-bestandsbeheerder die de tool voor direct delen ShareX en *NIX-systemen ondersteunt. Het ondersteunt het uploaden en weergeven van afbeeldingen, GIF's, video's, code, opgemaakte tekst en het downloaden en uploaden van bestanden. Het beschikt ook over een webinterface met beheer voor meerdere gebruikers, een uploadgeschiedenis en zoekfunctionaliteit.
    pl_PL: Xbackbone to prosty, samodzielnie hostowany i lekki menedżer plików PHP, który obsługuje narzędzie do natychmiastowego udostępniania ShareX oraz systemy *NIX. Obsługuje przesyłanie i wyświetlanie obrazów, plików GIF, wideo, kodu, tekstu sformatowanego oraz pobieranie i przesyłanie plików. Posiada również interfejs webowy z obsługą wielu użytkowników, historią przesyłania i wyszukiwaniem.
    pt_BR: Xbackbone é um gerenciador de arquivos PHP simples, auto-hospedado e leve, compatível com a ferramenta de compartilhamento instantâneo ShareX e sistemas *NIX. Ele permite o upload e a exibição de imagens, GIFs, vídeos, código, texto formatado, além de download e upload de arquivos. Possui também uma interface web com gerenciamento de múltiplos usuários, histórico de uploads e suporte a busca.
    ro_RO: Xbackbone este un manager de fișiere PHP simplu, auto-găzduit și ușor, compatibil cu instrumentul de partajare instantanee ShareX și sistemele *NIX. Acceptă încărcarea și afișarea de imagini, GIF-uri, videoclipuri, cod, text formatat, precum și descărcarea și încărcarea de fișiere. De asemenea, are o interfață web cu gestionare multi-utilizator, istoricul încărcărilor anterioare și suport pentru căutare.
    ru_RU: Xbackbone — это простой, саморазмещаемый, легковесный файловый менеджер на PHP, поддерживающий инструмент мгновенного обмена файлами ShareX и системы *NIX. Он поддерживает загрузку и отображение изображений, GIF-файлов, видео, кода, форматированного текста, а также скачивание и выгрузку файлов. Также имеется веб-интерфейс с многопользовательским управлением, историей загрузок и поддержкой поиска.
    sk_SK: Xbackbone je jednoduchý, samostatne hostovaný a ľahký správca súborov PHP, ktorý podporuje nástroj na okamžité zdieľanie ShareX a systémy *NIX. Podporuje nahrávanie a zobrazovanie obrázkov, GIF, videa, kódu, formátovaného textu a sťahovanie a nahrávanie súborov. Má tiež webové rozhranie so správou pre viacerých používateľov, históriou predchádzajúcich nahrávaní a podporou vyhľadávania.
    sv_SE: Xbackbone är en enkel, självhostad och lätt PHP-filhanterare som stöder de direkta delningsverktygen ShareX och *NIX-systemen. Den stöder uppladdning och visning av bilder, GIF, video, kod, formaterad text samt nedladdning och uppladdning av filer. Den har även ett webbgränssnitt med hantering av flera användare, tidigare uppladdningshistorik och sökstöd.
    tr_TR: Xbackbone, ShareX anlık paylaşım aracını ve *NIX sistemlerini destekleyen, basit, kendi sunucunuzda barındırılan, hafif bir PHP dosya yöneticisidir. Görüntü, GIF, video, kod, biçimlendirilmiş metin yükleme ve görüntüleme, dosya indirme ve yükleme işlemlerini destekler. Ayrıca çoklu kullanıcı yönetimi, geçmiş yükleme geçmişi ve arama desteği sunan bir web arayüzüne de sahiptir.
    zh_CN: XBackBone 是简单、轻量、可自行托管的 PHP 文件管理器，支持即时分享工具 ShareX 和类 Unix 系统。它可上传和显示图片、GIF、视频、代码和格式化文本，并支持文件上传下载。网页界面还提供多用户管理、上传历史和搜索功能。
    zh_TW: XBackBone 是簡單、輕量、可自行託管的 PHP 檔案管理器，支援即時分享工具 ShareX 和類 Unix 系統。它可上傳和顯示圖片、GIF、影片、程式碼和格式化文字，並支援檔案上傳下載。網頁介面還提供多使用者管理、上傳歷史和搜尋功能。
  tagline:
    en_US: A simple, self-hosted, lightweight PHP file manager that support the instant sharing tool ShareX and *NIX systems. It supports uploading and displaying images, GIF, video, code, formatted text, and file downloading and uploading. Also have a web UI with multi user management, past uploads history and search support.
    ca_ES: Un gestor de fitxers PHP senzill, autoallotjat i lleuger que admet l'eina de compartició instantània ShareX i els sistemes *NIX. Admet la càrrega i visualització d'imatges, GIF, vídeo, codi, text formatat i la descàrrega i càrrega de fitxers. També té una interfície d'usuari web amb gestió multiusuari, historial de càrregues anteriors i compatibilitat amb la cerca.
    cs_CZ: Jednoduchý, samostatně hostovaný a lehký správce souborů v PHP, který podporuje nástroj pro okamžité sdílení ShareX a systémy *NIX. Podporuje nahrávání a zobrazování obrázků, GIFů, videa, kódu, formátovaného textu a stahování a nahrávání souborů. Má také webové uživatelské rozhraní se správou pro více uživatelů, historií nahraných souborů a podporou vyhledávání.
    da_DK: En simpel, selvhostet og let PHP-filhåndtering, der understøtter delingsværktøjerne ShareX og *NIX. Den understøtter upload og visning af billeder, GIF'er, videoer, kode, formateret tekst samt download og upload af filer. Den har også en webgrænseflade med administration af flere brugere, historik over tidligere uploads og søgeunderstøttelse.
    de_DE: Ein einfacher, selbstgehosteter und ressourcenschonender PHP-Dateimanager, der das Instant-Sharing-Tool ShareX und *NIX-Systeme unterstützt. Er ermöglicht das Hochladen und Anzeigen von Bildern, GIFs, Videos, Code und formatiertem Text sowie das Herunterladen und Hochladen von Dateien. Zusätzlich bietet er eine Web-Oberfläche mit Mehrbenutzerverwaltung, Upload-Historie und Suchfunktion.
    el_GR: Ένας απλός, αυτοφιλοξενούμενος, ελαφρύς διαχειριστής αρχείων PHP που υποστηρίζει τα συστήματα ShareX και *NIX για εργαλεία άμεσης κοινής χρήσης. Υποστηρίζει τη μεταφόρτωση και προβολή εικόνων, GIF, βίντεο, κώδικα, μορφοποιημένου κειμένου και λήψης και μεταφόρτωσης αρχείων. Διαθέτει επίσης ένα περιβάλλον εργασίας χρήστη ιστού με διαχείριση πολλαπλών χρηστών, ιστορικό προηγούμενων μεταφορτώσεων και υποστήριξη αναζήτησης.
    en_GB: A simple, self-hosted, lightweight Php file manager that support the instant sharing tool Sharex and *Nix systems. It supports uploading and displaying images, Gif, video, code, formatted text, and file downloading and uploading. Also have a web Ui with multi user management, past uploads history and search support.
    es_ES: Un gestor de archivos PHP sencillo, autoalojado y ligero que admite la herramienta de intercambio instantáneo ShareX y sistemas *NIX. Permite subir y visualizar imágenes, GIF, vídeos, código y texto formateado, así como descargar y subir archivos. También cuenta con una interfaz web con gestión multiusuario, historial de subidas y función de búsqueda.
    fr_FR: Un gestionnaire de fichiers PHP simple, auto-hébergé et léger, compatible avec l'outil de partage instantané ShareX et les systèmes *NIX. Il permet d'afficher et de télécharger des images, des GIF, des vidéos, du code, du texte formaté, ainsi que de télécharger et d'envoyer des fichiers. Il dispose également d'une interface web avec gestion multi-utilisateurs, historique des téléchargements et fonction de recherche.
    ga_IE: Bainisteoir comhad PHP simplí, féinóstáilte, éadrom a thacaíonn leis an uirlis chomhroinnte meandrach ShareX agus córais *NIX. Tacaíonn sé le híomhánna, GIFanna, físeáin, cód, téacs formáidithe, agus íoslódáil agus uaslódáil comhad a uaslódáil agus a thaispeáint. Tá comhéadan úsáideora gréasáin aige freisin le bainistíocht ilúsáideoirí, stair uaslódálacha san am atá thart agus tacaíocht chuardaigh.
    hr_HR: Jednostavan, samostalno hostan, lagan PHP upravitelj datoteka koji podržava alat za trenutno dijeljenje ShareX i *NIX sustave. Podržava prijenos i prikaz slika, GIF-ova, videa, koda, formatiranog teksta te preuzimanje i prijenos datoteka. Također ima web sučelje s upravljanjem za više korisnika, poviješću prošlih prijenosa i podrškom za pretraživanje.
    hu_HU: Egy egyszerű, saját tárhelyen futó, könnyű PHP fájlkezelő, amely támogatja a ShareX és a *NIX azonnali megosztó eszközt. Támogatja a képek, GIF-ek, videók, kód, formázott szöveg feltöltését és megjelenítését, valamint a fájlok letöltését és feltöltését. Emellett webes felhasználói felülettel rendelkezik több felhasználó kezelésével, korábbi feltöltési előzményekkel és keresési támogatással.
    it_IT: Un semplice file manager PHP, auto-ospitato e leggero, che supporta lo strumento di condivisione istantanea ShareX e i sistemi *NIX. Consente di caricare e visualizzare immagini, GIF, video, codice, testo formattato, nonché di scaricare e caricare file. Dispone inoltre di un'interfaccia web con gestione multiutente, cronologia dei caricamenti precedenti e funzione di ricerca.
    ja_JP: ShareXなどのインスタントファイル共有ツールと*NIXシステムに対応した、シンプルで自己ホスト型の軽量PHPファイルマネージャーです。画像、GIF、動画、コード、書式付きテキストのアップロードと表示、ファイルのダウンロードとアップロードをサポートしています。また、マルチユーザー管理、過去のアップロード履歴、検索機能を備えたWeb UIも搭載しています。
    ko_KR: ShareX와 같은 즉시 공유 도구 및 *NIX 시스템을 지원하는 간단하고 가벼운 PHP 기반 파일 관리자입니다. 이미지, GIF, 비디오, 코드, 서식이 지정된 텍스트 업로드 및 표시, 파일 다운로드 및 업로드를 지원합니다. 또한 다중 사용자 관리, 이전 업로드 내역 및 검색 기능을 갖춘 웹 UI를 제공합니다.
    ml_IN: തൽക്ഷണ പങ്കിടൽ ഉപകരണമായ ShareX, *NIX സിസ്റ്റങ്ങളെ പിന്തുണയ്ക്കുന്ന ലളിതവും സ്വയം ഹോസ്റ്റ് ചെയ്തതും ഭാരം കുറഞ്ഞതുമായ PHP ഫയൽ മാനേജർ. ഇമേജുകൾ, GIF, വീഡിയോ, കോഡ്, ഫോർമാറ്റ് ചെയ്ത ടെക്സ്റ്റ്, ഫയൽ ഡൗൺലോഡ്, അപ്‌ലോഡിംഗ് എന്നിവ അപ്‌ലോഡ് ചെയ്യുന്നതിനും പ്രദർശിപ്പിക്കുന്നതിനും ഇത് പിന്തുണയ്ക്കുന്നു. മൾട്ടി യൂസർ മാനേജ്‌മെന്റ്, മുൻകാല അപ്‌ലോഡ് ചരിത്രം, തിരയൽ പിന്തുണ എന്നിവയുള്ള ഒരു വെബ് UI കൂടിയുണ്ട്.
    nb_NO: En enkel, selvhostet og lett PHP-filbehandler som støtter delingsverktøyene ShareX og *NIX. Den støtter opplasting og visning av bilder, GIF-er, videoer, kode, formatert tekst og nedlasting og opplasting av filer. Den har også et webgrensesnitt med flerbrukeradministrasjon, tidligere opplastingshistorikk og søkestøtte.
    nl_NL: Een eenvoudige, zelfgehoste, lichtgewicht PHP-bestandsbeheerder die de tool voor direct delen ShareX en *NIX-systemen ondersteunt. Het ondersteunt het uploaden en weergeven van afbeeldingen, GIF's, video's, code, opgemaakte tekst en het downloaden en uploaden van bestanden. Het beschikt ook over een webinterface met beheer voor meerdere gebruikers, een uploadgeschiedenis en zoekfunctionaliteit.
    pl_PL: Prosty, samodzielnie hostowany, lekki menedżer plików PHP, obsługujący narzędzie do natychmiastowego udostępniania ShareX i systemy *NIX. Obsługuje przesyłanie i wyświetlanie obrazów, plików GIF, wideo, kodu, tekstu sformatowanego oraz pobieranie i przesyłanie plików. Posiada również interfejs webowy z obsługą wielu użytkowników, historią przesyłania i wyszukiwaniem.
    pt_BR: Um gerenciador de arquivos PHP simples, auto-hospedado e leve, compatível com a ferramenta de compartilhamento instantâneo ShareX e sistemas *NIX. Ele permite o upload e a exibição de imagens, GIFs, vídeos, código, texto formatado, além de download e upload de arquivos. Possui também uma interface web com gerenciamento multiusuário, histórico de uploads e suporte a busca.
    ro_RO: Un manager de fișiere PHP simplu, auto-găzduit și ușor, compatibil cu instrumentul de partajare instantanee ShareX și sistemele *NIX. Acceptă încărcarea și afișarea de imagini, GIF-uri, videoclipuri, cod, text formatat, precum și descărcarea și încărcarea de fișiere. De asemenea, are o interfață web cu gestionare pentru mai mulți utilizatori, istoricul încărcărilor anterioare și suport pentru căutare.
    ru_RU: Простой, саморазмещаемый, легковесный PHP-файловый менеджер, поддерживающий инструмент мгновенного обмена файлами ShareX и системы *NIX. Он поддерживает загрузку и отображение изображений, GIF-файлов, видео, кода, форматированного текста, а также скачивание и выгрузку файлов. Также имеет веб-интерфейс с многопользовательским управлением, историей загрузок и поддержкой поиска.
    sk_SK: Jednoduchý, samostatne hostovaný a ľahký správca súborov PHP, ktorý podporuje nástroj na okamžité zdieľanie ShareX a systémy *NIX. Podporuje nahrávanie a zobrazovanie obrázkov, GIFov, videa, kódu, formátovaného textu a sťahovanie a nahrávanie súborov. Má tiež webové rozhranie so správou pre viacerých používateľov, históriou predchádzajúcich nahrávaní a podporou vyhľadávania.
    sv_SE: En enkel, självhostad och lätt PHP-filhanterare som stöder de direkta delningsverktygen ShareX och *NIX-systemen. Den stöder uppladdning och visning av bilder, GIF, video, kod, formaterad text samt nedladdning och uppladdning av filer. Har även ett webbgränssnitt med hantering av flera användare, tidigare uppladdningshistorik och sökstöd.
    tr_TR: ShareX anlık paylaşım aracını ve *NIX sistemlerini destekleyen, basit, kendi sunucunuzda barındırabileceğiniz, hafif bir PHP dosya yöneticisi. Görüntü, GIF, video, kod, biçimlendirilmiş metin yükleme ve görüntüleme, dosya indirme ve yükleme işlemlerini destekler. Ayrıca çoklu kullanıcı yönetimi, geçmiş yükleme geçmişi ve arama desteği sunan bir web arayüzüne de sahiptir.
    zh_CN: 支持 ShareX 的轻量自托管文件管理器。
    zh_TW: 支援 ShareX 的輕量自託管檔案管理器。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/xbackbone-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/xbackbone-logo.png
  title:
    en_US: Xbackbone (LinuxServer.io)
    ca_ES: Xbackbone (LinuxServer.io)
    cs_CZ: Xbackbone (LinuxServer.io)
    da_DK: Xbackbone (LinuxServer.io)
    de_DE: Xbackbone (LinuxServer.io)
    el_GR: Xbackbone (LinuxServer.io)
    en_GB: Xbackbone (LinuxServer.io)
    es_ES: Xbackbone (LinuxServer.io)
    fr_FR: Xbackbone (LinuxServer.io)
    ga_IE: Xbackbone (LinuxServer.io)
    hr_HR: Xbackbone (LinuxServer.io)
    hu_HU: Xbackbone (LinuxServer.io)
    it_IT: Xbackbone (LinuxServer.io)
    ja_JP: Xbackbone (LinuxServer.io)
    ko_KR: Xbackbone (LinuxServer.io)
    ml_IN: Xbackbone (LinuxServer.io)
    nb_NO: Xbackbone (LinuxServer.io)
    nl_NL: Xbackbone (LinuxServer.io)
    pl_PL: Xbackbone (LinuxServer.io)
    pt_BR: Xbackbone (LinuxServer.io)
    ro_RO: Xbackbone (LinuxServer.io)
    ru_RU: Xbackbone (LinuxServer.io)
    sk_SK: Xbackbone (LinuxServer.io)
    sv_SE: Xbackbone (LinuxServer.io)
    tr_TR: Xbackbone (LinuxServer.io)
    zh_CN: Xbackbone（LinuxServer.io）
    zh_TW: Xbackbone（LinuxServer.io）
  category: Productivity
  id: wisdomsky.linuxserver.linuxserverxbackbone
  port_map: '80'
  version: 3.8.2
