name: linuxserver-dillinger
services:
  app:
    image: linuxserver/dillinger:3.39.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_US: Appdata
      ports:
        - container: '8080'
          description:
            en_US: Webui - Default port 8080
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dillinger/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: 'Visit homepage: https://hub.docker.com/r/linuxserver/dillinger/'
    zh_CN: |-
      Dillinger 是基于 AngularJS 和 HTML5 的 Markdown 编辑器，支持云端功能、移动设备和离线存储。

      访问项目主页：https://hub.docker.com/r/linuxserver/dillinger/
    ca_ES: 'Visita la pàgina principal: https://hub.docker.com/r/linuxserver/dillinger/'
    cs_CZ: 'Navštivte domovskou stránku: https://hub.docker.com/r/linuxserver/dillinger/'
    da_DK: 'Besøg hjemmesiden: https://hub.docker.com/r/linuxserver/dillinger/'
    de_DE: 'Besuchen Sie die Homepage: https://hub.docker.com/r/linuxserver/dillinger/'
    el_GR: 'Επισκεφθείτε την αρχική σελίδα: https://hub.docker.com/r/linuxserver/dillinger/'
    en_GB: 'Visit homepage: https://hub.docker.com/r/linuxserver/dillinger/'
    es_ES: 'Visita la página principal: https://hub.docker.com/r/linuxserver/dillinger/'
    fr_FR: "Visitez la page d'accueil\_: https://hub.docker.com/r/linuxserver/dillinger/"
    ga_IE: 'Tabhair cuairt ar an leathanach baile: https://hub.docker.com/r/linuxserver/dillinger/'
    hr_HR: 'Posjetite početnu stranicu: https://hub.docker.com/r/linuxserver/dillinger/'
    hu_HU: 'Látogassa meg a honlapot: https://hub.docker.com/r/linuxserver/dillinger/'
    it_IT: 'Visita la homepage: https://hub.docker.com/r/linuxserver/dillinger/'
    ja_JP: ホームページをご覧ください：https://hub.docker.com/r/linuxserver/dillinger/
    ko_KR: '홈페이지 방문: https://hub.docker.com/r/linuxserver/dillinger/'
    ml_IN: 'ഹോംപേജ് സന്ദർശിക്കുക: https://hub.docker.com/r/linuxserver/dillinger/'
    nb_NO: 'Besøk hjemmesiden: https://hub.docker.com/r/linuxserver/dillinger/'
    nl_NL: 'Bezoek de homepage: https://hub.docker.com/r/linuxserver/dillinger/'
    pl_PL: 'Odwiedź stronę główną: https://hub.docker.com/r/linuxserver/dillinger/'
    pt_BR: 'Visite a página inicial: https://hub.docker.com/r/linuxserver/dillinger/'
    ro_RO: 'Vizitați pagina principală: https://hub.docker.com/r/linuxserver/dillinger/'
    ru_RU: 'Перейдите на главную страницу: https://hub.docker.com/r/linuxserver/dillinger/'
    sk_SK: 'Navštívte domovskú stránku: https://hub.docker.com/r/linuxserver/dillinger/'
    sv_SE: 'Besök hemsidan: https://hub.docker.com/r/linuxserver/dillinger/'
    tr_TR: 'Ana sayfayı ziyaret edin: https://hub.docker.com/r/linuxserver/dillinger/'
    zh_TW: |-
      Dillinger 是基於 AngularJS 和 HTML5 的 Markdown 編輯器，支援雲端功能、移動裝置和離線儲存。

      訪問專案主頁：https://hub.docker.com/r/linuxserver/dillinger/
  tagline:
    en_US: A cloud-enabled, mobile-ready, offline-storage, AngularJS powered HTML5 Markdown editor.
    zh_CN: 支持云端与离线存储的 Markdown 编辑器。
    ca_ES: Un editor Markdown HTML5 habilitat per al núvol, preparat per a mòbils, amb emmagatzematge fora de línia i amb tecnologia AngularJS.
    cs_CZ: Cloudový editor HTML5 Markdown s podporou AngularJS, připravený pro mobilní zařízení a offline úložiště.
    da_DK: En cloud-aktiveret, mobilklar, offline-lagring, AngularJS-drevet HTML5 Markdown-editor.
    de_DE: Ein Cloud-fähiger, mobiloptimierter HTML5-Markdown-Editor mit Offline-Speicherung und AngularJS-Unterstützung.
    el_GR: Ένας επεξεργαστής HTML5 Markdown με δυνατότητα cloud, έτοιμος για κινητά, αποθηκευτικός χώρος εκτός σύνδεσης και υποστήριξη AngularJS.
    en_GB: A cloud-enabled, mobile-ready, offline-storage, Angularjs powered HTML5 Markdown editor.
    es_ES: Un editor de HTML5 Markdown con tecnología AngularJS, compatible con la nube, dispositivos móviles, almacenamiento sin conexión y acceso desde la nube.
    fr_FR: Un éditeur HTML5 Markdown basé sur AngularJS, compatible avec le cloud, les appareils mobiles et offrant un stockage hors ligne.
    ga_IE: Eagarthóir HTML5 Markdown atá cumasaithe don scamall, réidh le haghaidh soghluaiste, le haghaidh stórála as líne, faoi thiomáint AngularJS.
    hr_HR: HTML5 Markdown uređivač, pokretan AngularJS-om, omogućen u oblaku, spreman za mobilne uređaje, s izvanmrežnom pohranom.
    hu_HU: Egy felhőalapú, mobilbarát, offline tárhelyre alkalmas, AngularJS-alapú HTML5 Markdown szerkesztő.
    it_IT: Un editor HTML5 Markdown basato su AngularJS, con supporto cloud, ottimizzato per dispositivi mobili e con archiviazione offline.
    ja_JP: クラウド対応、モバイル対応、オフラインストレージ機能を備えた、AngularJS搭載のHTML5 Markdownエディタ。
    ko_KR: 클라우드 기반, 모바일 지원, 오프라인 저장 기능을 갖춘 AngularJS 기반 HTML5 마크다운 편집기입니다.
    ml_IN: ക്ലൗഡ്-പ്രാപ്‌തമാക്കിയ, മൊബൈൽ-റെഡി, ഓഫ്‌ലൈൻ-സ്റ്റോറേജ്, ആംഗുലർജെഎസ് പവർഡ് HTML5 മാർക്ക്ഡൗൺ എഡിറ്റർ.
    nb_NO: En skyaktivert, mobilklar, offline lagring, AngularJS-drevet HTML5 Markdown-editor.
    nl_NL: Een cloudgebaseerde, mobielvriendelijke HTML5 Markdown-editor met offline opslag, aangedreven door AngularJS.
    pl_PL: Edytor HTML5 Markdown oparty na AngularJS, działający w chmurze, gotowy do pracy na urządzeniach mobilnych, z pamięcią masową w trybie offline.
    pt_BR: Um editor HTML5 Markdown baseado em AngularJS, habilitado para nuvem, compatível com dispositivos móveis e com armazenamento offline.
    ro_RO: Un editor HTML5 Markdown bazat pe AngularJS, compatibil cu cloud, compatibil cu dispozitive mobile, cu stocare offline.
    ru_RU: Облачный, адаптированный для мобильных устройств, работающий в автономном режиме редактор HTML5 Markdown на базе AngularJS.
    sk_SK: Cloudový editor HTML5 Markdown s podporou AngularJS, pripravený na použitie v mobilných zariadeniach a s offline úložiskom.
    sv_SE: En molnaktiverad, mobilklar, offline-lagringsbaserad AngularJS-driven HTML5 Markdown-editor.
    tr_TR: Bulut tabanlı, mobil uyumlu, çevrimdışı depolama özelliğine sahip, AngularJS destekli bir HTML5 Markdown editörü.
    zh_TW: 支援雲端與離線儲存的 Markdown 編輯器。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/dillinger.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/dillinger.png
  title:
    en_US: Dillinger
    zh_CN: Dillinger
    ca_ES: Dillinger
    cs_CZ: Dillinger
    da_DK: Dillinger
    de_DE: Dillinger
    el_GR: Dillinger
    en_GB: Dillinger
    es_ES: Dillinger
    fr_FR: Dillinger
    ga_IE: Dillinger
    hr_HR: Dillinger
    hu_HU: Dillinger
    it_IT: Dillinger
    ja_JP: Dillinger
    ko_KR: Dillinger
    ml_IN: Dillinger
    nb_NO: Dillinger
    nl_NL: Dillinger
    pl_PL: Dillinger
    pt_BR: Dillinger
    ro_RO: Dillinger
    ru_RU: Dillinger
    sk_SK: Dillinger
    sv_SE: Dillinger
    tr_TR: Dillinger
    zh_TW: Dillinger
  category: Others
  project_url: https://dillinger.io/
  port_map: '8080'
  id: wisdomsky.linuxserver.linuxserverdillinger
  version: 3.39.1
  website: https://dillinger.io/
