name: linuxserver-tester
services:
  app:
    image: linuxserver/tester:version-66f677b0
    restart: unless-stopped
    environment:
      URL: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservertester/assets/icon
  title:
    en_US: Tester
    zh_CN: Tester
    ca_ES: Tester
    cs_CZ: Tester
    da_DK: Tester
    de_DE: Tester
    el_GR: Tester
    en_GB: Tester
    es_ES: Tester
    fr_FR: Tester
    ga_IE: Tester
    hr_HR: Tester
    hu_HU: Tester
    it_IT: Tester
    ja_JP: Tester
    ko_KR: Tester
    ml_IN: Tester
    nb_NO: Tester
    nl_NL: Tester
    pl_PL: Tester
    pt_BR: Tester
    ro_RO: Tester
    ru_RU: Tester
    sk_SK: Tester
    sv_SE: Tester
    tr_TR: Tester
    zh_TW: Tester
  id: wisdomsky.linuxserver.linuxservertester
  version: version-66f677b0
