name: linuxserver-tester
services:
  app:
    image: linuxserver/tester:version-66f677b0
    restart: unless-stopped
    environment:
      URL: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservertester/assets/icon
  title:
    en_US: Tester
  id: wisdomsky.linuxserver.linuxservertester
  version: version-66f677b0
