name: linuxserver-yaak
services:
  app:
    image: linuxserver/yaak:2026.7.1@sha256:e05741dce044893640c8f34a3720825ac11cde596c145acdb481ac08145fb075
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/yaak/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveryaak/assets/icon.png
  title:
    en_US: Yaak (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserveryaak
  port_map: '3000'
  version: 2026.7.1
