name: linuxserver-zen
services:
  app:
    image: linuxserver/zen:1.22.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/zen/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverzen/assets/icon.png
  title:
    en_US: Zen (LinuxServer.io)
    zh_CN: Zen（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverzen
  port_map: '3000'
  version: 1.22.2
