name: linuxserver-lidarr
services:
  app:
    image: linuxserver/lidarr:3.1.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8686
        published: 8686
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lidarr/config
        target: /config
      - type: bind
        source: /DATA/AppData/lidarr/music
        target: /music
      - type: bind
        source: /DATA/AppData/lidarr/downloads
        target: /downloads
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverlidarr/assets/icon.png
  title:
    en_US: Lidarr (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverlidarr
  port_map: '8686'
  version: 3.1.0
