name: linuxserver-spotube
services:
  app:
    image: linuxserver/spotube:5.1.2@sha256:f314a0d8a268cd6041f13eae6e26dd2a33d973382945fc82aa34380e72c616c6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/spotube/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverspotube/assets/icon.png
  title:
    en_US: Spotube (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverspotube
  port_map: '3000'
  version: 5.1.2
