name: linuxserver-altus
services:
  app:
    image: linuxserver/altus:5.7.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /srv/lsio/altus/config
        target: /config
x-casaos:
  architectures:
    - arm64
    - amd64
  main: app
  description:
    en_us: Altus is an Electron-based WhatsApp client with themes and multiple account support.
  tagline:
    en_us: An Electron-based WhatsApp client with themes and multiple account support.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/altus-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/altus-logo.png
  title:
    en_us: Altus
  category: LinuxServer.io
