name: linuxserver-quassel-core
services:
  app:
    image: linuxserver/quassel-core:0.14.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RUN_OPTS: ''
    ports:
      - target: 4242
        published: 4242
        protocol: tcp
      - target: 113
        published: 10113
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/quassel-core/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverquasselcore/assets/icon.png
  title:
    en_US: Quassel core
    zh_CN: Quassel core
  id: wisdomsky.linuxserver.linuxserverquasselcore
  version: 0.14.0
