name: linuxserver-ldap-auth
services:
  app:
    image: linuxserver/ldap-auth:3.4.8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FERNETKEY: ''
      CERTFILE: ''
      KEYFILE: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: FERNETKEY
          description:
            en_US: Optionally define a custom valid fernet key (only needed if container is frequently recreated, or if using multi-node setups, invalidating previous authentications) [OPTIONAL]
        - container: CERTFILE
          description:
            en_US: Optionally point this to a certificate file to enable HTTP over SSL (HTTPS) for the ldap auth daemon [OPTIONAL]
        - container: KEYFILE
          description:
            en_US: Optionally point this to the private key file, matching the certificate file referred to in CERTFILE [OPTIONAL]
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 9000
        published: 9000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ldap-auth/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Ldap-auth software is for authenticating users who request protected resources from servers proxied by nginx. It includes a daemon (ldap-auth) that communicates with an authentication server, and a webserver daemon that generates an authentication cookie based on the user’s credentials. The daemons are written in Python for use with a Lightweight Directory Access Protocol (LDAP) authentication server (OpenLDAP or Microsoft Windows Active Directory 2003 and 2012).
    ca_ES: El programari Ldap-auth serveix per autenticar usuaris que sol·liciten recursos protegits de servidors proxyats per nginx. Inclou un daemon (ldap-auth) que es comunica amb un servidor d'autenticació i un daemon de servidor web que genera una galeta d'autenticació basada en les credencials de l'usuari. Els daemons estan escrits en Python per utilitzar-se amb un servidor d'autenticació Lightweight Directory Access Protocol (LDAP) (OpenLDAP o Microsoft Windows Active Directory 2003 i 2012).
    cs_CZ: Software LDAP-auth slouží k ověřování uživatelů, kteří požadují chráněné zdroje ze serverů proxyovaných nginx. Obsahuje démona (ldap-auth), který komunikuje s ověřovacím serverem, a démona webového serveru, který generuje ověřovací soubor cookie na základě přihlašovacích údajů uživatele. Démony jsou napsány v Pythonu pro použití s ověřovacím serverem LDAP (Lightweight Directory Access Protocol) (OpenLDAP nebo Microsoft Windows Active Directory 2003 a 2012).
    da_DK: LDAP-auth-software bruges til at godkende brugere, der anmoder om beskyttede ressourcer fra servere, der drives af nginx. Den indeholder en daemon (ldap-auth), der kommunikerer med en godkendelsesserver, og en webserver-daemon, der genererer en godkendelsescookie baseret på brugerens legitimationsoplysninger. Daemonerne er skrevet i Python til brug med en Lightweight Directory Access Protocol (LDAP)-godkendelsesserver (OpenLDAP eller Microsoft Windows Active Directory 2003 og 2012).
    de_DE: Die Software LDAP-Authentifizierung dient der Authentifizierung von Benutzern, die geschützte Ressourcen von Servern anfordern, die über einen Nginx-Proxy geleitet werden. Sie umfasst einen Daemon (ldap-auth), der mit einem Authentifizierungsserver kommuniziert, und einen Webserver-Daemon, der anhand der Benutzerdaten ein Authentifizierungs-Cookie generiert. Die Daemons sind in Python geschrieben und für die Verwendung mit einem LDAP-Authentifizierungsserver (Lightweight Directory Access Protocol) wie OpenLDAP oder Microsoft Windows Active Directory 2003 und 2012 vorgesehen.
    el_GR: Το λογισμικό Ldap-auth προορίζεται για τον έλεγχο ταυτότητας χρηστών που ζητούν προστατευμένους πόρους από διακομιστές που διαχειρίζονται μεσολάβηση από το nginx. Περιλαμβάνει έναν δαίμονα (ldap-auth) που επικοινωνεί με έναν διακομιστή ελέγχου ταυτότητας και έναν δαίμονα διακομιστή ιστού που δημιουργεί ένα cookie ελέγχου ταυτότητας με βάση τα διαπιστευτήρια του χρήστη. Οι δαίμονες είναι γραμμένοι σε Python για χρήση με έναν διακομιστή ελέγχου ταυτότητας Lightweight Directory Access Protocol (LDAP) (OpenLDAP ή Microsoft Windows Active Directory 2003 και 2012).
    en_GB: Ldap-auth software is for authenticating users who request protected resources from servers proxied by nginx. It includes a daemon (ldap-auth) that communicates with an authentication server, and a webserver daemon that generates an authentication cookie based on the user’s credentials. The daemons are written in Python for use with a Lightweight Directory Access Protocol (Ldap) authentication server (Openldap or Microsoft Windows Active Directory 2003 and 2012).
    es_ES: El software Ldap-auth se utiliza para autenticar a los usuarios que solicitan recursos protegidos a servidores gestionados por nginx. Incluye un demonio (ldap-auth) que se comunica con un servidor de autenticación y un demonio de servidor web que genera una cookie de autenticación basada en las credenciales del usuario. Los demonios están escritos en Python para su uso con un servidor de autenticación LDAP (Protocolo ligero de acceso a directorios) (OpenLDAP o Microsoft Windows Active Directory 2003 y 2012).
    fr_FR: Le logiciel d'authentification LDAP permet d'authentifier les utilisateurs qui demandent des ressources protégées à des serveurs faisant intervenir un proxy Nginx. Il comprend un démon (ldap-auth) qui communique avec un serveur d'authentification, et un démon côté serveur web qui génère un cookie d'authentification à partir des informations d'identification de l'utilisateur. Ces démons sont écrits en Python et conçus pour fonctionner avec un serveur d'authentification LDAP (OpenLDAP ou Microsoft Windows Active Directory 2003 et 2012).
    ga_IE: Is chun úsáideoirí a fhíordheimhniú a iarrann acmhainní cosanta ó fhreastalaithe arna n-oibriú ag nginx atá bogearraí ldap-auth. Cuimsíonn sé daemon (ldap-auth) a dhéanann cumarsáid le freastalaí fíordheimhnithe, agus daemon freastalaí gréasáin a ghineann fianán fíordheimhnithe bunaithe ar dhintiúir an úsáideora. Scríobhtar na daemon i Python lena n-úsáid le freastalaí fíordheimhnithe Lightweight Directory Access Protocol (LDAP) (OpenLDAP nó Microsoft Windows Active Directory 2003 agus 2012).
    hr_HR: LDAP-auth softver namijenjen je autentifikaciji korisnika koji zahtijevaju zaštićene resurse s poslužitelja koje proxyira nginx. Uključuje daemon (ldap-auth) koji komunicira s poslužiteljem za autentifikaciju i daemon web poslužitelja koji generira kolačić za autentifikaciju na temelju korisničkih vjerodajnica. Daemoni su napisani u Pythonu za korištenje s poslužiteljem za autentifikaciju Lightweight Directory Access Protocol (LDAP) (OpenLDAP ili Microsoft Windows Active Directory 2003 i 2012).
    hu_HU: Az Ldap-auth szoftver olyan felhasználók hitelesítésére szolgál, akik védett erőforrásokat kérnek nginx által proxyzott szerverekről. Tartalmaz egy démont (ldap-auth), amely kommunikál egy hitelesítési szerverrel, és egy webszerver démont, amely hitelesítési sütit generál a felhasználó hitelesítő adatai alapján. A démonok Python nyelven íródtak, és egy Lightweight Directory Access Protocol (LDAP) hitelesítési szerverrel (OpenLDAP vagy Microsoft Windows Active Directory 2003 és 2012) használhatók.
    it_IT: Il software Ldap-auth serve per autenticare gli utenti che richiedono risorse protette da server proxy gestiti da nginx. Include un demone (ldap-auth) che comunica con un server di autenticazione e un demone web server che genera un cookie di autenticazione basato sulle credenziali dell'utente. I demoni sono scritti in Python per l'utilizzo con un server di autenticazione LDAP (Lightweight Directory Access Protocol) (OpenLDAP o Microsoft Windows Active Directory 2003 e 2012).
    ja_JP: ldap-authソフトウェアは、nginxによってプロキシされたサーバーから保護されたリソースを要求するユーザーを認証するためのものです。認証サーバーと通信するデーモン（ldap-auth）と、ユーザーの認証情報に基づいて認証クッキーを生成するWebサーバーデーモンが含まれています。これらのデーモンは、軽量ディレクトリアクセスプロトコル（LDAP）認証サーバー（OpenLDAPまたはMicrosoft Windows Active Directory 2003および2012）で使用するためにPythonで記述されています。
    ko_KR: LDAP 인증 소프트웨어는 Nginx를 통해 프록시된 서버에서 보호된 리소스를 요청하는 사용자를 인증하기 위한 것입니다. 이 소프트웨어는 인증 서버와 통신하는 데몬(ldap-auth)과 사용자의 자격 증명을 기반으로 인증 쿠키를 생성하는 웹 서버 데몬으로 구성됩니다. 이 데몬들은 LDAP(Lightweight Directory Access Protocol) 인증 서버(OpenLDAP 또는 Microsoft Windows Active Directory 2003 및 2012)와 함께 사용하도록 Python으로 작성되었습니다.
    ml_IN: nginx പ്രോക്സി ചെയ്ത സെർവറുകളിൽ നിന്ന് പരിരക്ഷിത ഉറവിടങ്ങൾ അഭ്യർത്ഥിക്കുന്ന ഉപയോക്താക്കളെ പ്രാമാണീകരിക്കുന്നതിനാണ് Ldap-auth സോഫ്റ്റ്‌വെയർ. ഒരു പ്രാമാണീകരണ സെർവറുമായി ആശയവിനിമയം നടത്തുന്ന ഒരു ഡെമണും (ldap-auth) ഉപയോക്താവിന്റെ ക്രെഡൻഷ്യലുകളെ അടിസ്ഥാനമാക്കി ഒരു പ്രാമാണീകരണ കുക്കി സൃഷ്ടിക്കുന്ന ഒരു വെബ്‌സെർവർ ഡെമണും ഇതിൽ ഉൾപ്പെടുന്നു. ലൈറ്റ്‌വെയ്റ്റ് ഡയറക്‌ടറി ആക്‌സസ് പ്രോട്ടോക്കോൾ (LDAP) പ്രാമാണീകരണ സെർവറിൽ (OpenLDAP അല്ലെങ്കിൽ Microsoft Windows Active Directory 2003, 2012) ഉപയോഗിക്കുന്നതിനായി ഡെമണുകൾ പൈത്തണിൽ എഴുതിയിരിക്കുന്നു.
    nb_NO: LDAP-auth-programvare er for autentisering av brukere som ber om beskyttede ressurser fra servere proxystyrt av nginx. Den inkluderer en daemon (ldap-auth) som kommuniserer med en autentiseringsserver, og en webserver-daemon som genererer en autentiseringsinformasjonskapsel basert på brukerens påloggingsinformasjonskapsler. Daemonene er skrevet i Python for bruk med en Lightweight Directory Access Protocol (LDAP)-autentiseringsserver (OpenLDAP eller Microsoft Windows Active Directory 2003 og 2012).
    nl_NL: De Ldap-auth-software is bedoeld voor het authenticeren van gebruikers die beveiligde resources opvragen van servers die via Nginx worden geproxyd. Het omvat een daemon (ldap-auth) die communiceert met een authenticatieserver en een webserverdaemon die een authenticatiecookie genereert op basis van de gebruikersgegevens. De daemons zijn geschreven in Python voor gebruik met een Lightweight Directory Access Protocol (LDAP)-authenticatieserver (OpenLDAP of Microsoft Windows Active Directory 2003 en 2012).
    pl_PL: Oprogramowanie LDAP-auth służy do uwierzytelniania użytkowników, którzy żądają dostępu do chronionych zasobów z serwerów proxy nginx. Zawiera ono demona (LDAP-auth), który komunikuje się z serwerem uwierzytelniania, oraz demona serwera WWW, który generuje plik cookie uwierzytelniania na podstawie danych uwierzytelniających użytkownika. Demony są napisane w Pythonie i przeznaczone do współpracy z serwerem uwierzytelniania LDAP (Lightweight Directory Access Protocol) (OpenLDAP lub Microsoft Windows Active Directory 2003 i 2012).
    pt_BR: O software Ldap-auth serve para autenticar usuários que solicitam recursos protegidos de servidores proxyados pelo nginx. Ele inclui um daemon (ldap-auth) que se comunica com um servidor de autenticação e um daemon de servidor web que gera um cookie de autenticação com base nas credenciais do usuário. Os daemons são escritos em Python para uso com um servidor de autenticação LDAP (Lightweight Directory Access Protocol) (OpenLDAP ou Microsoft Windows Active Directory 2003 e 2012).
    ro_RO: Software-ul LDAP-auth este destinat autentificării utilizatorilor care solicită resurse protejate de la servere proxyate de nginx. Acesta include un daemon (ldap-auth) care comunică cu un server de autentificare și un daemon de server web care generează un cookie de autentificare pe baza acreditărilor utilizatorului. Daemon-urile sunt scrise în Python pentru a fi utilizate cu un server de autentificare Lightweight Directory Access Protocol (LDAP) (OpenLDAP sau Microsoft Windows Active Directory 2003 și 2012).
    ru_RU: Программное обеспечение LDAP-Auth предназначено для аутентификации пользователей, запрашивающих защищенные ресурсы с серверов, работающих через прокси-сервер nginx. Оно включает в себя демон (ldap-auth), взаимодействующий с сервером аутентификации, и демон веб-сервера, генерирующий аутентификационный cookie на основе учетных данных пользователя. Демоны написаны на Python и предназначены для использования с сервером аутентификации LDAP (OpenLDAP или Microsoft Windows Active Directory 2003 и 2012).
    sk_SK: Softvér LDAP-auth slúži na autentifikáciu používateľov, ktorí požadujú chránené zdroje zo serverov proxyovaných nginx. Obsahuje démona (ldap-auth), ktorý komunikuje s autentifikačným serverom, a démona webového servera, ktorý generuje autentifikačný súbor cookie na základe prihlasovacích údajov používateľa. Démóny sú napísané v jazyku Python na použitie s autentifikačným serverom LDAP (Lightweight Directory Access Protocol) (OpenLDAP alebo Microsoft Windows Active Directory 2003 a 2012).
    sv_SE: LDAP-auth-programvara är avsedd för att autentisera användare som begär skyddade resurser från servrar som hanteras av nginx via proxy. Den inkluderar en daemon (ldap-auth) som kommunicerar med en autentiseringsserver och en webbserverdaemon som genererar en autentiseringscookie baserat på användarens inloggningsuppgifter. Daemonerna är skrivna i Python för användning med en LDAP-autentiseringsserver (Lightweight Directory Access Protocol) (OpenLDAP eller Microsoft Windows Active Directory 2003 och 2012).
    tr_TR: Ldap-auth yazılımı, nginx tarafından proxy edilen sunuculardan korumalı kaynaklara erişim isteyen kullanıcıların kimlik doğrulaması için kullanılır. Bir kimlik doğrulama sunucusuyla iletişim kuran bir arka plan programı (ldap-auth) ve kullanıcının kimlik bilgilerine dayalı olarak bir kimlik doğrulama çerezi oluşturan bir web sunucusu arka plan programı içerir. Arka plan programları, Hafif Dizin Erişim Protokolü (LDAP) kimlik doğrulama sunucusu (OpenLDAP veya Microsoft Windows Active Directory 2003 ve 2012) ile kullanılmak üzere Python dilinde yazılmıştır.
    zh_CN: Ldap-auth 用于验证请求访问 Nginx 代理服务器上受保护资源的用户。它包含与身份验证服务器通信的 ldap-auth 守护进程，以及根据用户凭据生成身份验证 Cookie 的网页服务器守护进程。这些进程使用 Python 编写，适用于 LDAP 身份验证服务器，包括 OpenLDAP 和 Microsoft Windows Active Directory 2003、2012。
    zh_TW: Ldap-auth 用於驗證請求訪問 Nginx 代理伺服器上受保護資源的使用者。它包含與身份驗證伺服器通訊的 ldap-auth 守護程序，以及根據使用者憑據生成身份驗證 Cookie 的網頁伺服器守護程序。這些程序使用 Python 編寫，適用於 LDAP 身份驗證伺服器，包括 OpenLDAP 和 Microsoft Windows Active Directory 2003、2012。
  tagline:
    en_US: Software is for authenticating users who request protected resources from servers proxied by nginx. It includes a daemon (ldap-auth) that communicates with an authentication server, and a webserver daemon that generates an authentication cookie based on the user’s credentials. The daemons are written in Python for use with a Lightweight Directory Access Protocol (LDAP) authentication server (OpenLDAP or Microsoft Windows Active Directory 2003 and 2012).
    ca_ES: El programari serveix per autenticar usuaris que sol·liciten recursos protegits de servidors proxyats per nginx. Inclou un daemon (ldap-auth) que es comunica amb un servidor d'autenticació i un daemon de servidor web que genera una galeta d'autenticació basada en les credencials de l'usuari. Els daemons estan escrits en Python per al seu ús amb un servidor d'autenticació Lightweight Directory Access Protocol (LDAP) (OpenLDAP o Microsoft Windows Active Directory 2003 i 2012).
    cs_CZ: Software je určen pro ověřování uživatelů, kteří požadují chráněné zdroje ze serverů proxyovaných nginx. Obsahuje démona (ldap-auth), který komunikuje s ověřovacím serverem, a démona webového serveru, který generuje ověřovací soubor cookie na základě přihlašovacích údajů uživatele. Démony jsou napsány v Pythonu pro použití s ověřovacím serverem LDAP (Lightweight Directory Access Protocol) (OpenLDAP nebo Microsoft Windows Active Directory 2003 a 2012).
    da_DK: Softwaren er til godkendelse af brugere, der anmoder om beskyttede ressourcer fra servere, der drives af nginx. Den indeholder en daemon (ldap-auth), der kommunikerer med en godkendelsesserver, og en webserver-daemon, der genererer en godkendelsescookie baseret på brugerens legitimationsoplysninger. Daemonerne er skrevet i Python til brug med en Lightweight Directory Access Protocol (LDAP)-godkendelsesserver (OpenLDAP eller Microsoft Windows Active Directory 2003 og 2012).
    de_DE: Die Software dient der Authentifizierung von Benutzern, die geschützte Ressourcen von Servern anfordern, die über einen nginx-Proxy laufen. Sie umfasst einen Daemon (ldap-auth), der mit einem Authentifizierungsserver kommuniziert, und einen Webserver-Daemon, der anhand der Benutzerdaten ein Authentifizierungs-Cookie generiert. Die Daemons sind in Python geschrieben und für die Verwendung mit einem LDAP-Authentifizierungsserver (OpenLDAP oder Microsoft Windows Active Directory 2003 und 2012) vorgesehen.
    el_GR: Το λογισμικό προορίζεται για την επαλήθευση της ταυτότητας χρηστών που ζητούν προστατευμένους πόρους από διακομιστές που διαχειρίζονται μεσολάβηση από το nginx. Περιλαμβάνει έναν δαίμονα (ldap-auth) που επικοινωνεί με έναν διακομιστή ελέγχου ταυτότητας και έναν δαίμονα διακομιστή ιστού που δημιουργεί ένα cookie ελέγχου ταυτότητας με βάση τα διαπιστευτήρια του χρήστη. Οι δαίμονες είναι γραμμένοι σε Python για χρήση με έναν διακομιστή ελέγχου ταυτότητας Lightweight Directory Access Protocol (LDAP) (OpenLDAP ή Microsoft Windows Active Directory 2003 και 2012).
    en_GB: Software is for authenticating users who request protected resources from servers proxied by nginx. It includes a daemon (ldap-auth) that communicates with an authentication server, and a webserver daemon that generates an authentication cookie based on the user’s credentials. The daemons are written in Python for use with a Lightweight Directory Access Protocol (Ldap) authentication server (Openldap or Microsoft Windows Active Directory 2003 and 2012).
    es_ES: El software se utiliza para autenticar a los usuarios que solicitan recursos protegidos a servidores gestionados por nginx. Incluye un demonio (ldap-auth) que se comunica con un servidor de autenticación y un demonio de servidor web que genera una cookie de autenticación basada en las credenciales del usuario. Los demonios están escritos en Python para su uso con un servidor de autenticación LDAP (Protocolo ligero de acceso a directorios) (OpenLDAP o Microsoft Windows Active Directory 2003 y 2012).
    fr_FR: Ce logiciel permet d'authentifier les utilisateurs qui demandent des ressources protégées à des serveurs faisant intervenir un proxy Nginx. Il comprend un démon (ldap-auth) qui communique avec un serveur d'authentification, et un démon côté serveur web qui génère un cookie d'authentification à partir des informations d'identification de l'utilisateur. Ces démons sont écrits en Python et conçus pour fonctionner avec un serveur d'authentification LDAP (OpenLDAP ou Microsoft Windows Active Directory 2003 et 2012).
    ga_IE: Is chun úsáideoirí a fhíordheimhniú a iarrann acmhainní cosanta ó fhreastalaithe arna n-oibriú ag nginx atá an bogearra. Cuimsíonn sé daemon (ldap-auth) a chuireann cumarsáid le freastalaí fíordheimhnithe, agus daemon freastalaí gréasáin a ghineann fianán fíordheimhnithe bunaithe ar dhintiúir an úsáideora. Scríobhtar na daemon i Python lena n-úsáid le freastalaí fíordheimhnithe Lightweight Directory Access Protocol (LDAP) (OpenLDAP nó Microsoft Windows Active Directory 2003 agus 2012).
    hr_HR: Softver je namijenjen za autentifikaciju korisnika koji zahtijevaju zaštićene resurse s poslužitelja koje proxyira nginx. Uključuje daemon (ldap-auth) koji komunicira s poslužiteljem za autentifikaciju i daemon web poslužitelja koji generira kolačić za autentifikaciju na temelju korisničkih vjerodajnica. Daemoni su napisani u Pythonu za korištenje s poslužiteljem za autentifikaciju Lightweight Directory Access Protocol (LDAP) (OpenLDAP ili Microsoft Windows Active Directory 2003 i 2012).
    hu_HU: A szoftver olyan felhasználók hitelesítésére szolgál, akik védett erőforrásokat kérnek nginx által proxyzott szerverekről. Tartalmaz egy démont (ldap-auth), amely egy hitelesítési szerverrel kommunikál, és egy webszerver démont, amely a felhasználó hitelesítő adatai alapján hitelesítési sütit generál. A démonok Python nyelven íródtak, és egy Lightweight Directory Access Protocol (LDAP) hitelesítési szerverrel (OpenLDAP vagy Microsoft Windows Active Directory 2003 és 2012) használhatók.
    it_IT: Il software serve ad autenticare gli utenti che richiedono risorse protette da server proxy gestiti da nginx. Include un demone (ldap-auth) che comunica con un server di autenticazione e un demone web server che genera un cookie di autenticazione basato sulle credenziali dell'utente. I demoni sono scritti in Python per l'utilizzo con un server di autenticazione LDAP (Lightweight Directory Access Protocol) (OpenLDAP o Microsoft Windows Active Directory 2003 e 2012).
    ja_JP: このソフトウェアは、nginxによってプロキシされたサーバーから保護されたリソースを要求するユーザーを認証するためのものです。認証サーバーと通信するデーモン（ldap-auth）と、ユーザーの認証情報に基づいて認証クッキーを生成するWebサーバーデーモンが含まれています。これらのデーモンは、軽量ディレクトリアクセスプロトコル（LDAP）認証サーバー（OpenLDAPまたはMicrosoft Windows Active Directory 2003および2012）で使用するためにPythonで記述されています。
    ko_KR: 이 소프트웨어는 Nginx를 통해 프록시된 서버에서 보호된 리소스를 요청하는 사용자를 인증하기 위한 것입니다. 여기에는 인증 서버와 통신하는 데몬(ldap-auth)과 사용자의 자격 증명을 기반으로 인증 쿠키를 생성하는 웹 서버 데몬이 포함됩니다. 이 데몬들은 LDAP(Lightweight Directory Access Protocol) 인증 서버(OpenLDAP 또는 Microsoft Windows Active Directory 2003 및 2012)와 함께 사용하도록 Python으로 작성되었습니다.
    ml_IN: nginx പ്രോക്സി ചെയ്ത സെർവറുകളിൽ നിന്ന് പരിരക്ഷിത ഉറവിടങ്ങൾ അഭ്യർത്ഥിക്കുന്ന ഉപയോക്താക്കളെ ആധികാരികമാക്കുന്നതിനാണ് സോഫ്റ്റ്‌വെയർ. ഒരു ആധികാരികത സെർവറുമായി ആശയവിനിമയം നടത്തുന്ന ഒരു ഡെമൺ (ldap-auth), ഉപയോക്താവിന്റെ ക്രെഡൻഷ്യലുകളെ അടിസ്ഥാനമാക്കി ഒരു ആധികാരികത കുക്കി സൃഷ്ടിക്കുന്ന ഒരു വെബ്‌സെർവർ ഡെമൺ എന്നിവ ഇതിൽ ഉൾപ്പെടുന്നു. ലൈറ്റ്‌വെയ്റ്റ് ഡയറക്‌ടറി ആക്‌സസ് പ്രോട്ടോക്കോൾ (LDAP) പ്രാമാണീകരണ സെർവറിൽ (OpenLDAP അല്ലെങ്കിൽ Microsoft Windows Active Directory 2003, 2012) ഉപയോഗിക്കുന്നതിനായി ഡെമണുകൾ പൈത്തണിൽ എഴുതിയിരിക്കുന്നു.
    nb_NO: Programvaren er for autentisering av brukere som ber om beskyttede ressurser fra servere som drives av nginx. Den inkluderer en daemon (ldap-auth) som kommuniserer med en autentiseringsserver, og en webserver-daemon som genererer en autentiseringsinformasjonskapsel basert på brukerens påloggingsinformasjonskapsler. Daemonene er skrevet i Python for bruk med en Lightweight Directory Access Protocol (LDAP)-autentiseringsserver (OpenLDAP eller Microsoft Windows Active Directory 2003 og 2012).
    nl_NL: De software is bedoeld voor het authenticeren van gebruikers die beveiligde resources opvragen van servers die via Nginx worden geproxyd. Het omvat een daemon (ldap-auth) die communiceert met een authenticatieserver en een webserverdaemon die een authenticatiecookie genereert op basis van de gebruikersgegevens. De daemons zijn geschreven in Python voor gebruik met een Lightweight Directory Access Protocol (LDAP) authenticatieserver (OpenLDAP of Microsoft Windows Active Directory 2003 en 2012).
    pl_PL: Oprogramowanie służy do uwierzytelniania użytkowników, którzy żądają chronionych zasobów z serwerów proxy nginx. Zawiera demona (ldap-auth), który komunikuje się z serwerem uwierzytelniania, oraz demona serwera WWW, który generuje plik cookie uwierzytelniania na podstawie danych uwierzytelniających użytkownika. Demony są napisane w Pythonie do użytku z serwerem uwierzytelniania LDAP (Lightweight Directory Access Protocol) (OpenLDAP lub Microsoft Windows Active Directory 2003 i 2012).
    pt_BR: O software serve para autenticar usuários que solicitam recursos protegidos de servidores proxyados pelo nginx. Ele inclui um daemon (ldap-auth) que se comunica com um servidor de autenticação e um daemon de servidor web que gera um cookie de autenticação com base nas credenciais do usuário. Os daemons são escritos em Python para uso com um servidor de autenticação LDAP (OpenLDAP ou Microsoft Windows Active Directory 2003 e 2012).
    ro_RO: Software-ul este destinat autentificării utilizatorilor care solicită resurse protejate de la servere proxyate de nginx. Acesta include un daemon (ldap-auth) care comunică cu un server de autentificare și un daemon de server web care generează un cookie de autentificare pe baza acreditărilor utilizatorului. Daemon-urile sunt scrise în Python pentru a fi utilizate cu un server de autentificare Lightweight Directory Access Protocol (LDAP) (OpenLDAP sau Microsoft Windows Active Directory 2003 și 2012).
    ru_RU: Программное обеспечение предназначено для аутентификации пользователей, запрашивающих защищенные ресурсы с серверов, работающих через прокси-сервер nginx. Оно включает в себя демон (ldap-auth), взаимодействующий с сервером аутентификации, и демон веб-сервера, генерирующий cookie-файл аутентификации на основе учетных данных пользователя. Демоны написаны на Python для использования с сервером аутентификации LDAP (OpenLDAP или Microsoft Windows Active Directory 2003 и 2012).
    sk_SK: Softvér slúži na autentifikáciu používateľov, ktorí požadujú chránené zdroje zo serverov proxyovaných nginx. Obsahuje démona (ldap-auth), ktorý komunikuje s autentifikačným serverom, a démona webového servera, ktorý generuje autentifikačný súbor cookie na základe prihlasovacích údajov používateľa. Démóny sú napísané v jazyku Python na použitie s autentifikačným serverom LDAP (Lightweight Directory Access Protocol) (OpenLDAP alebo Microsoft Windows Active Directory 2003 a 2012).
    sv_SE: Programvaran är avsedd för autentisering av användare som begär skyddade resurser från servrar som hanteras av nginx via proxy. Den inkluderar en daemon (ldap-auth) som kommunicerar med en autentiseringsserver och en webbserverdaemon som genererar en autentiseringscookie baserat på användarens inloggningsuppgifter. Daemonerna är skrivna i Python för användning med en LDAP-autentiseringsserver (Lightweight Directory Access Protocol) (OpenLDAP eller Microsoft Windows Active Directory 2003 och 2012).
    tr_TR: Bu yazılım, nginx tarafından proxy edilen sunuculardan korumalı kaynaklar talep eden kullanıcıların kimlik doğrulamasını yapmak için tasarlanmıştır. Bir kimlik doğrulama sunucusuyla iletişim kuran bir arka plan programı (ldap-auth) ve kullanıcının kimlik bilgilerine dayalı olarak bir kimlik doğrulama çerezi oluşturan bir web sunucusu arka plan programı içerir. Arka plan programları, Hafif Dizin Erişim Protokolü (LDAP) kimlik doğrulama sunucusu (OpenLDAP veya Microsoft Windows Active Directory 2003 ve 2012) ile kullanılmak üzere Python dilinde yazılmıştır.
    zh_CN: 为经 Nginx 代理的资源提供 LDAP 身份验证。
    zh_TW: 為經 Nginx 代理的資源提供 LDAP 身份驗證。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ldap-auth-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ldap-auth-logo.png
  title:
    en_US: Ldap auth (LinuxServer.io)
    ca_ES: Ldap auth (LinuxServer.io)
    cs_CZ: Ldap auth (LinuxServer.io)
    da_DK: Ldap auth (LinuxServer.io)
    de_DE: Ldap auth (LinuxServer.io)
    el_GR: Ldap auth (LinuxServer.io)
    en_GB: Ldap auth (LinuxServer.io)
    es_ES: Ldap auth (LinuxServer.io)
    fr_FR: Ldap auth (LinuxServer.io)
    ga_IE: Ldap auth (LinuxServer.io)
    hr_HR: Ldap auth (LinuxServer.io)
    hu_HU: Ldap auth (LinuxServer.io)
    it_IT: Ldap auth (LinuxServer.io)
    ja_JP: Ldap auth (LinuxServer.io)
    ko_KR: Ldap auth (LinuxServer.io)
    ml_IN: Ldap auth (LinuxServer.io)
    nb_NO: Ldap auth (LinuxServer.io)
    nl_NL: Ldap auth (LinuxServer.io)
    pl_PL: Ldap auth (LinuxServer.io)
    pt_BR: Ldap auth (LinuxServer.io)
    ro_RO: Ldap auth (LinuxServer.io)
    ru_RU: Ldap auth (LinuxServer.io)
    sk_SK: Ldap auth (LinuxServer.io)
    sv_SE: Ldap auth (LinuxServer.io)
    tr_TR: Ldap auth (LinuxServer.io)
    zh_CN: Ldap auth（LinuxServer.io）
    zh_TW: Ldap auth（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxserverldapauth
  version: 3.4.8
