name: linuxserver-booksonic-air
services:
  app:
    image: linuxserver/booksonic-air:2201.1.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONTEXT_PATH: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: for UserID
        - container: PGID
          description:
            en_US: for GroupID
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: CONTEXT_PATH
          description:
            en_US: Base url for use with reverse proxies etc.
      volumes:
        - container: /config
          description:
            en_US: Appdata
      ports:
        - container: '4040'
          description:
            en_US: Webui Port
    ports:
      - target: 4040
        published: 4040
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/booksonic-air/config
        target: /config
      - type: bind
        source: /DATA/AppData/booksonic-air/audiobooks
        target: /audiobooks
      - type: bind
        source: /DATA/AppData/booksonic-air/podcasts
        target: /podcasts
      - type: bind
        source: /DATA/AppData/booksonic-air/othermedia
        target: /othermedia
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: 'Visit homepage: https://hub.docker.com/r/linuxserver/booksonic-air/'
    zh_CN: |-
      Booksonic 让你随时随地访问自己拥有的有声书。平台目前包括：Booksonic Air，用于串流有声书的服务器，是原 Booksonic 服务器的继任者，基于 Airsonic；以及 Booksonic App，基于 DSub 的 Android 应用，用于连接 Booksonic Air 服务器。

      访问项目主页：https://hub.docker.com/r/linuxserver/booksonic-air/
  tagline:
    en_US: 'A platform for accessing the audiobooks you own wherever you are. At the moment the platform consists of: * Booksonic Air - A server for streaming your audiobooks, successor to the original Booksonic server and based on Airsonic. * Booksonic App - An DSub based Android app for connection to Booksonic-Air servers.'
    zh_CN: 随时随地收听自己的有声书。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/booksonic-air.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/booksonic-air.png
  title:
    en_US: Booksonic air
    zh_CN: Booksonic air
  category: Others
  project_url: https://booksonic.org/
  port_map: '4040'
  id: wisdomsky.linuxserver.linuxserverbooksonicair
  version: 2201.1.0
  website: https://booksonic.org/
