name: linuxserver-calibre
services:
  app:
    image: linuxserver/calibre:9.14.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
      CLI_ARGS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
        - container: PGID
          description:
            en_US: Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
        - container: TZ
          description:
            en_US: specify a timezone to use, see this list.
        - container: PASSWORD
          description:
            en_US: Optionally set a password for the gui. [OPTIONAL]
        - container: CLI_ARGS
          description:
            en_US: Optionally pass cli start arguments to calibre. [OPTIONAL]
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 8181
        published: 8181
        protocol: tcp
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/calibre/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_US: Calibre is a powerful and easy to use e-book manager. Users say it's outstanding and a must-have. It'll allow you to do nearly everything and it takes things a step beyond normal e-book software. It's also completely free and open source and great for both casual users and computer experts.
    zh_CN: Calibre 是一款功能强大、易于使用的电子书管理器，深受用户好评。它能够完成几乎所有常见的电子书管理工作，功能超越一般电子书软件。Calibre 完全免费且开源，适合普通用户和计算机专业人士。
  tagline:
    en_US: A powerful and easy to use e-book manager. Users say it's outstanding and a must-have. It'll allow you to do nearly everything and it takes things a step beyond normal e-book software. It's also completely free and open source and great for both casual users and computer experts.
    zh_CN: 功能强大、易于使用的开源电子书管理器。
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/calibre-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/calibre-logo.png
  title:
    en_US: Calibre (LinuxServer.io)
    zh_CN: Calibre（LinuxServer.io）
  category: Home
  id: wisdomsky.linuxserver.linuxservercalibre
  port_map: '8080'
  version: 9.14.0
