name: linuxserver-tautulli
services:
  app:
    image: linuxserver/tautulli:2.18.1@sha256:7fbf4fe86bf89532574902e168dedb504a59d0f6a22da5eb75736ed36fa54711
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/tautulli/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservertautulli/assets/icon.png
  title:
    en_US: Tautulli (LinuxServer.io)
    zh_CN: Tautulli（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservertautulli
  port_map: '8181'
  version: 2.18.1
