name: linuxserver-dosbox-staging
services:
  app:
    image: linuxserver/dosbox-staging:0.83.0@sha256:6105e3296fde03a495d373aff260081aeb66b448e79044f37434098dd77a3a7a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dosbox-staging/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverdosboxstaging/assets/icon.png
  title:
    en_US: Dosbox staging (LinuxServer.io)
    zh_CN: Dosbox staging（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverdosboxstaging
  port_map: '3000'
  version: 0.83.0
