name: linuxserver-dosbox-staging
services:
  app:
    image: linuxserver/dosbox-staging:0.83.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dosbox-staging/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverdosboxstaging/assets/icon.png
  title:
    en_US: Dosbox staging (LinuxServer.io)
    ca_ES: Dosbox staging (LinuxServer.io)
    cs_CZ: Dosbox staging (LinuxServer.io)
    da_DK: Dosbox staging (LinuxServer.io)
    de_DE: Dosbox staging (LinuxServer.io)
    el_GR: Dosbox staging (LinuxServer.io)
    en_GB: Dosbox staging (LinuxServer.io)
    es_ES: Dosbox staging (LinuxServer.io)
    fr_FR: Dosbox staging (LinuxServer.io)
    ga_IE: Dosbox staging (LinuxServer.io)
    hr_HR: Dosbox staging (LinuxServer.io)
    hu_HU: Dosbox staging (LinuxServer.io)
    it_IT: Dosbox staging (LinuxServer.io)
    ja_JP: Dosbox staging (LinuxServer.io)
    ko_KR: Dosbox staging (LinuxServer.io)
    ml_IN: Dosbox staging (LinuxServer.io)
    nb_NO: Dosbox staging (LinuxServer.io)
    nl_NL: Dosbox staging (LinuxServer.io)
    pl_PL: Dosbox staging (LinuxServer.io)
    pt_BR: Dosbox staging (LinuxServer.io)
    ro_RO: Dosbox staging (LinuxServer.io)
    ru_RU: Dosbox staging (LinuxServer.io)
    sk_SK: Dosbox staging (LinuxServer.io)
    sv_SE: Dosbox staging (LinuxServer.io)
    tr_TR: Dosbox staging (LinuxServer.io)
    zh_CN: Dosbox staging（LinuxServer.io）
    zh_TW: Dosbox staging（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverdosboxstaging
  port_map: '3000'
  version: 0.83.0
