name: linuxserver-netbox
services:
  app:
    image: linuxserver/netbox:4.7.1@sha256:6cc7d1e490d7288cff67b3c52224ef476c8aa45711cc59f5865fe680b5f5a433
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SUPERUSER_EMAIL: ''
      SUPERUSER_PASSWORD: ''
      ALLOWED_HOST: ''
      DB_NAME: ''
      DB_USER: ''
      DB_PASSWORD: ''
      DB_HOST: ''
      DB_PORT: ''
      REDIS_HOST: ''
      REDIS_PORT: ''
      REDIS_USERNAME: ''
      REDIS_PASSWORD: ''
      REDIS_DB_TASK: ''
      REDIS_DB_CACHE: ''
      BASE_PATH: ''
      CSRF_TRUSTED_ORIGINS: ''
      REMOTE_AUTH_ENABLED: ''
      REMOTE_AUTH_BACKEND: ''
      REMOTE_AUTH_HEADER: ''
      REMOTE_AUTH_AUTO_CREATE_USER: ''
      REMOTE_AUTH_DEFAULT_GROUPS: ''
      REMOTE_AUTH_DEFAULT_PERMISSIONS: ''
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/netbox/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservernetbox/assets/icon.png
  title:
    en_US: Netbox (LinuxServer.io)
    ca_ES: Netbox (LinuxServer.io)
    cs_CZ: Netbox (LinuxServer.io)
    da_DK: Netbox (LinuxServer.io)
    de_DE: Netbox (LinuxServer.io)
    el_GR: Netbox (LinuxServer.io)
    en_GB: Netbox (LinuxServer.io)
    es_ES: Netbox (LinuxServer.io)
    fr_FR: Netbox (LinuxServer.io)
    ga_IE: Netbox (LinuxServer.io)
    hr_HR: Netbox (LinuxServer.io)
    hu_HU: Netbox (LinuxServer.io)
    it_IT: Netbox (LinuxServer.io)
    ja_JP: Netbox (LinuxServer.io)
    ko_KR: Netbox (LinuxServer.io)
    ml_IN: Netbox (LinuxServer.io)
    nb_NO: Netbox (LinuxServer.io)
    nl_NL: Netbox (LinuxServer.io)
    pl_PL: Netbox (LinuxServer.io)
    pt_BR: Netbox (LinuxServer.io)
    ro_RO: Netbox (LinuxServer.io)
    ru_RU: Netbox (LinuxServer.io)
    sk_SK: Netbox (LinuxServer.io)
    sv_SE: Netbox (LinuxServer.io)
    tr_TR: Netbox (LinuxServer.io)
    zh_CN: Netbox（LinuxServer.io）
    zh_TW: Netbox（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservernetbox
  port_map: '8000'
  version: 4.7.1
