name: linuxserver-manyfold
services:
  app:
    image: linuxserver/manyfold:0.149.0@sha256:d9922cc80f28d48984f5151d65336427527e4ecef0308bde7a92bbcb29059581
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DATABASE_URL: ''
      REDIS_URL: ''
      SECRET_KEY_BASE: ''
    ports:
      - target: 3214
        published: 3214
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/manyfold/config
        target: /config
      - type: bind
        source: /DATA/AppData/manyfold/libraries
        target: /libraries
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermanyfold/assets/icon.png
  title:
    en_US: Manyfold (LinuxServer.io)
    ca_ES: Manyfold (LinuxServer.io)
    cs_CZ: Manyfold (LinuxServer.io)
    da_DK: Manyfold (LinuxServer.io)
    de_DE: Manyfold (LinuxServer.io)
    el_GR: Manyfold (LinuxServer.io)
    en_GB: Manyfold (LinuxServer.io)
    es_ES: Manyfold (LinuxServer.io)
    fr_FR: Manyfold (LinuxServer.io)
    ga_IE: Manyfold (LinuxServer.io)
    hr_HR: Manyfold (LinuxServer.io)
    hu_HU: Manyfold (LinuxServer.io)
    it_IT: Manyfold (LinuxServer.io)
    ja_JP: Manyfold (LinuxServer.io)
    ko_KR: Manyfold (LinuxServer.io)
    ml_IN: Manyfold (LinuxServer.io)
    nb_NO: Manyfold (LinuxServer.io)
    nl_NL: Manyfold (LinuxServer.io)
    pl_PL: Manyfold (LinuxServer.io)
    pt_BR: Manyfold (LinuxServer.io)
    ro_RO: Manyfold (LinuxServer.io)
    ru_RU: Manyfold (LinuxServer.io)
    sk_SK: Manyfold (LinuxServer.io)
    sv_SE: Manyfold (LinuxServer.io)
    tr_TR: Manyfold (LinuxServer.io)
    zh_CN: Manyfold（LinuxServer.io）
    zh_TW: Manyfold（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservermanyfold
  port_map: '3214'
  version: 0.149.0
