name: linuxserver-mame
services:
  app:
    image: linuxserver/mame:version-0.289dfsg1-0@sha256:56d4093f07bbd7df7006ab453affe3a2f8974e49f998cf607811ec66e571b835
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mame/config
        target: /config
      - type: bind
        source: /DATA/AppData/mame/mame:ro
        target: /mame:ro
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermame/assets/icon.png
  title:
    en_US: Mame (LinuxServer.io)
    ca_ES: Mame (LinuxServer.io)
    cs_CZ: Mame (LinuxServer.io)
    da_DK: Mame (LinuxServer.io)
    de_DE: Mame (LinuxServer.io)
    el_GR: Mame (LinuxServer.io)
    en_GB: Mame (LinuxServer.io)
    es_ES: Mame (LinuxServer.io)
    fr_FR: Mame (LinuxServer.io)
    ga_IE: Mame (LinuxServer.io)
    hr_HR: Mame (LinuxServer.io)
    hu_HU: Mame (LinuxServer.io)
    it_IT: Mame (LinuxServer.io)
    ja_JP: Mame (LinuxServer.io)
    ko_KR: Mame (LinuxServer.io)
    ml_IN: Mame (LinuxServer.io)
    nb_NO: Mame (LinuxServer.io)
    nl_NL: Mame (LinuxServer.io)
    pl_PL: Mame (LinuxServer.io)
    pt_BR: Mame (LinuxServer.io)
    ro_RO: Mame (LinuxServer.io)
    ru_RU: Mame (LinuxServer.io)
    sk_SK: Mame (LinuxServer.io)
    sv_SE: Mame (LinuxServer.io)
    tr_TR: Mame (LinuxServer.io)
    zh_CN: Mame（LinuxServer.io）
    zh_TW: Mame（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservermame
  port_map: '3000'
  version: version-0.289dfsg1-0
