name: linuxserver-mame
services:
  app:
    image: linuxserver/mame:version-0.289dfsg1-0@sha256:56d4093f07bbd7df7006ab453affe3a2f8974e49f998cf607811ec66e571b835
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mame/config
        target: /config
      - type: bind
        source: /DATA/AppData/mame/mame:ro
        target: /mame:ro
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermame/assets/icon.png
  title:
    en_US: Mame (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxservermame
  port_map: '3000'
  version: version-0.289dfsg1-0
