name: linuxserver-ldap-auth
services:
  app:
    image: linuxserver/ldap-auth:3.4.8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FERNETKEY: ''
      CERTFILE: ''
      KEYFILE: ''
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 9000
        published: 9000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ldap-auth/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverldapauth/assets/icon.png
  title:
    en_US: Ldap auth (LinuxServer.io)
    ca_ES: Ldap auth (LinuxServer.io)
    cs_CZ: Ldap auth (LinuxServer.io)
    da_DK: Ldap auth (LinuxServer.io)
    de_DE: Ldap auth (LinuxServer.io)
    el_GR: Ldap auth (LinuxServer.io)
    en_GB: Ldap auth (LinuxServer.io)
    es_ES: Ldap auth (LinuxServer.io)
    fr_FR: Ldap auth (LinuxServer.io)
    ga_IE: Ldap auth (LinuxServer.io)
    hr_HR: Ldap auth (LinuxServer.io)
    hu_HU: Ldap auth (LinuxServer.io)
    it_IT: Ldap auth (LinuxServer.io)
    ja_JP: Ldap auth (LinuxServer.io)
    ko_KR: Ldap auth (LinuxServer.io)
    ml_IN: Ldap auth (LinuxServer.io)
    nb_NO: Ldap auth (LinuxServer.io)
    nl_NL: Ldap auth (LinuxServer.io)
    pl_PL: Ldap auth (LinuxServer.io)
    pt_BR: Ldap auth (LinuxServer.io)
    ro_RO: Ldap auth (LinuxServer.io)
    ru_RU: Ldap auth (LinuxServer.io)
    sk_SK: Ldap auth (LinuxServer.io)
    sv_SE: Ldap auth (LinuxServer.io)
    tr_TR: Ldap auth (LinuxServer.io)
    zh_CN: Ldap auth（LinuxServer.io）
    zh_TW: Ldap auth（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverldapauth
  version: 3.4.8
